### ISSUE TITLE
SciPy build failing on master 

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#10005]
My issue is about: 

Was there a breaking change to Cython version on master branch? 

### Reproducing code example:
```
(scipy-dev) Lucass-MacBook:stats rlucas$ git clean -xdf
(scipy-dev) Lucass-MacBook:stats rlucas$ python ../../runtests.py -v -s stats
```

### Error message:
```
Building, see build.log...
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
Running scipy/linalg/_generate_pyx.py
Running scipy/special/_generate_pyx.py
scipy/cluster/_vq.pyx has not changed
scipy/cluster/_optimal_leaf_ordering.pyx has not changed
scipy/cluster/_hierarchy.pyx has not changed
scipy/ndimage/src/_cytest.pyx has not changed
scipy/ndimage/src/_ni_label.pyx has not changed
scipy/linalg/cython_lapack.pyx has not changed
scipy/linalg/_solve_toeplitz.pyx has not changed
scipy/linalg/cython_blas.pyx has not changed
scipy/linalg/_decomp_update.pyx.in has not changed
scipy/optimize/_group_columns.pyx has not changed
scipy/optimize/_bglu_dense.pyx has not changed
scipy/optimize/_trlib/_trlib.pyx has not changed
scipy/optimize/_lsq/givens_elimination.pyx has not changed
scipy/io/matlab/mio_utils.pyx has not changed
scipy/io/matlab/streams.pyx has not changed
scipy/io/matlab/mio5_utils.pyx has not changed
scipy/_lib/_ccallback_c.pyx has not changed
scipy/_lib/messagestream.pyx has not changed
scipy/special/_ufuncs_cxx.pyx has not changed
scipy/special/cython_special.pyx has not changed
scipy/special/_ellip_harm_2.pyx has not changed
scipy/special/_comb.pyx has not changed
scipy/special/_test_round.pyx has not changed
Processing scipy/special/_ufuncs.pyx
scipy/interpolate/interpnd.pyx has not changed
scipy/interpolate/_bspl.pyx has not changed
scipy/interpolate/_ppoly.pyx has not changed
scipy/sparse/_csparsetools.pyx.in has not changed
Traceback (most recent call last):
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 307, in <module>
    main()
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 303, in main
    find_process_files(root_dir)
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 292, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 292, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 231, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/Users/rlucas/scipy-dev/scipy/tools/cythonize.py", line 83, in process_pyx
    '{}'.format(required_version, cython_version))
Exception: Building SciPy requires Cython >= 0.29.2, found 0.29
Cythonizing sources
Traceback (most recent call last):
  File "setup.py", line 500, in <module>
    setup_package()
  File "setup.py", line 484, in setup_package
    generate_cython()
  File "setup.py", line 260, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
Build failed! (0:00:03.013180 elapsed)
(scipy-dev) Lucass-MacBook:stats rlucas$ 
```

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+41f26a2 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by rlucas7** [comment]
I updated to Cython 0.29.6 in the conda virtual env:

```
(scipy-dev) Lucass-MacBook:scipy rlucas$ conda update Cython 
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.9

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/rlucas/anaconda3/envs/scipy-dev

  added / updated specs: 
    - cython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py36_0         155 KB
    openssl-1.1.1b             |       h1de35cc_1         3.4 MB
    cython-0.29.6              |   py36h0a44026_0         2.1 MB
    ------------------------------------------------------------
                                           Total:         5.7 MB

The following packages will be UPDATED:

    certifi: 2018.11.29-py36_0   --> 2019.3.9-py36_0      
    cython:  0.29-py36h0a44026_0 --> 0.29.6-py36h0a44026_0
    openssl: 1.1.1a-h1de35cc_0   --> 1.1.1b-h1de35cc_1   
```

which seems to solve the problem.

I updated my master branch with upstream from maybe 1-2 weeks ago when I was not seeing this issue. 

I'll leave the issue open in case this is something that was unknown and needs to be called out in the 1.3.0 release. 

If someone already knew about this and I was just uninformed (definitely possible), then issue should be closed.

**Comment by tylerjereddy** [comment]
We somewhat-recently bumped our minimum required Cython version, yes.

I think that happened more than two weeks ago though. We generally bump Cython versions as needed--a fair bit faster than other dependencies, I think.

**Comment by WarrenWeckesser** [comment]
Here's the commit: https://github.com/scipy/scipy/pull/9924/commits/ea61eeb4a46edc30c7b9f2a93da8fef67af8b5f8

It was part of https://github.com/scipy/scipy/pull/9924

**Comment by rlucas7** [comment]
Yep, I just missed the emails, thanks guys! I'll close the issue.
