### ISSUE TITLE
scipy.sparse.linalg.factorized works once per open console

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10031]
Hi Team,
Either I'm having a strong déjà vu or I have actually seen this before; in either case, I don't know how to fix it. When I open a console and first run this script:

```
import numpy as np
import scipy.sparse
from scipy.sparse.linalg import factorized

A = scipy.sparse.eye(100).tocsc()
factorized(A)
```
It's successful.

`<class 'scipy.sparse.csc.csc_matrix'>`

If I run the same script a second time:
```
Traceback (most recent call last):

  File "<ipython-input-2-630138451a6f>", line 1, in <module>
    runfile('/Users/matthaberland/Desktop/suitesparse_issue.py', wdir='/Users/matthaberland/Desktop')

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/matthaberland/Desktop/suitesparse_issue.py", line 14, in <module>
    factorized(A)

  File "/Users/matthaberland/Desktop/scipydev/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 436, in factorized
    umf.numeric(A)

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/scikits/umfpack/umfpack.py", line 542, in numeric
    self.symbolic(mtx)

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/scikits/umfpack/umfpack.py", line 499, in symbolic
    indx = self._getIndx(mtx)

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/scikits/umfpack/umfpack.py", line 467, in _getIndx
    raise TypeError('must be a CSC/CSR matrix (is %s)' % mtx.__class__)

TypeError: must be a CSC/CSR matrix (is <class 'scipy.sparse.csc.csc_matrix'>)
```

Other information:
UMFPACK is installed and is running properly the first time; I can tell because of the speed (for other matrices; this is a minimal example).

If I paste the code into the console instead of running the script, there is no problem. 

If I comment out the `scipy` imports or all imports before running the script again, I get a different error.
```
Traceback (most recent call last):

  File "<ipython-input-2-630138451a6f>", line 1, in <module>
    runfile('/Users/matthaberland/Desktop/suitesparse_issue.py', wdir='/Users/matthaberland/Desktop')

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/anaconda3/envs/scipydev/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/matthaberland/Desktop/suitesparse_issue.py", line 14, in <module>
    factorized(A)

  File "/Users/matthaberland/Desktop/scipydev/scipy/scipy/sparse/linalg/dsolve/linsolve.py", line 424, in factorized
    A = csc_matrix(A)

  File "/Users/matthaberland/Desktop/scipydev/scipy/scipy/sparse/compressed.py", line 88, in __init__
    self._set_self(self.__class__(coo_matrix(arg1, dtype=dtype)))

  File "/Users/matthaberland/Desktop/scipydev/scipy/scipy/sparse/coo.py", line 191, in __init__
    self.row, self.col = M.nonzero()

  File "/Users/matthaberland/Desktop/scipydev/scipy/scipy/sparse/base.py", line 287, in __bool__
    raise ValueError("The truth value of an array with more than one "

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```

For good measure I deleted the scipy build folder and rebuilt after SuiteSparse was installed, but this didn't fix the problem.

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+17bfd1f 1.14.3 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
The issue seems to have (inexplicably) fixed itself. But I repeated the process of setting up a development environment and installing SuiteSparse/scikit.umfpack on a different Mac and I'm experiencing the same issue there.

**Comment by ilayn** [comment]
Do you install or switch branches of scipy or umfpack between two runs?

**Comment by mdhaber** [comment]
No. I should have mentioned that I'm running the script in Spyder. I just click the "play" button twice. Works the first time but not the second time. When I restart the kernel, it works again (the first time).

**Comment by ilayn** [comment]
I am also using Spyder (very happily). I don't know if it is related but I see this when the scipy in the memory of spyder console doesn't match the version or reloading of the import doesn't go through for some reason. In other words, if the script that is run has import statements there can be problems depending on how reloading the already loaded modules are handled. 
Not exactly an answer but might be worth checking.

**Comment by mdhaber** [comment]
I turned off UMR so that modules do _not_ get reloaded. That fixed the problem. Changes I make to SciPy source still seem to take effect, so this is a fine workaround for me. OK to close this unless you think someone would be interested in a more complete solution.

**Comment by ilayn** [comment]
I really don't have any preference. All I know is that when a module is reloaded the previous instances won't be treated as valid objects though valid for only some modules and not all. Probably a person with a better Python low-level knowledge can explain better instead of my handwaving. Maybe this is a better issue for IPython/Spyder folks.

**Comment by rgommers** [comment]
It would be good to point out this issue to @rc. There is some state kept somewhere, and it may be in `scikit-umfpack`. There's some explicit use of `locals()`, and this line looks wrong: https://github.com/scikit-umfpack/scikit-umfpack/blob/master/scikits/umfpack/umfpack.py#L410 (should be `super.__init__` not `Struct.__init__`).

**Comment by rgommers** [comment]
But yes doesn't look like a SciPy issue so let's close here.
