### ISSUE TITLE
TypeError: ufunc 'gammaln' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by xuebaliang** [scipy/scipy#10137]
My issue is about the dirichlet.pdf function and 'gammaln' function.
Recently I am doing my project that is related to compositional data. I use the  dirichlet.pdf function in scipy1.2.1 version to calculate the likelihood value like below:

```
T = np.zeros((X.shape[0], Alpha.shape[0]))
    print(X)
    print(Alpha)
    for i in range(X.shape[0]):
        for j in range(Alpha.shape[0]):
            T[i, j] = rho[j]*(dirichlet.pdf(X[i], Alpha[j]))
        T[i] = T[i] / (np.sum( T[i] ))
```

where the X is my data and the Alpha is the parameter of dirichlet distribution. since I get some error, i print the X and Alpha. However, I can't find the solution.
The following is the X and Alpha and the error message:

```bash
Traceback (most recent call last):
[[1.6380123702694215e-05 9.82807422161653e-06 3.276024740538843e-06 ...

  File "C:/Users/clandzyy/PycharmProjects/mixture of dirichlet distribution/EM_for_dirichlet.py", line 132, in <module>

  0.0022244207988258743 2.2932173183771902e-05 0.009457883425935638]

    Alpha_init, EM_Alpha, kmeans_ARI, kmeans_NMI, EM_ARI, EM_NMI, kmeans_Alpha_distance, EM_Alpha_distance = realdata()

 [8.848200276063845e-05 2.9494000920212815e-05 0.00010027960312872358 ...
  0.00034802921085851123 1.7696400552127692e-05 0.009774311904958524]

  File "C:/Users/clandzyy/PycharmProjects/mixture of dirichlet distribution/EM_for_dirichlet.py", line 113, in realdata

    EM_T, EM_rho, EM_Alpha = EM(data, Alpha_init, rho_init)
  File "C:/Users/clandzyy/PycharmProjects/mixture of dirichlet distribution/EM_for_dirichlet.py", line 64, in EM

 [1.4674662727334986e-05 4.8915542424449935e-06 2.445777121222497e-05 ...
    T = update_T(rho, X, Alpha)

  File "C:/Users/clandzyy/PycharmProjects/mixture of dirichlet distribution/EM_for_dirichlet.py", line 19, in update_T

  0.00018098750697046482 1.4674662727334986e-05 0.0011495152469745734]
 ...

    **T[i, j] = rho[j]*(dirichlet.pdf(X[i], Alpha[j]))**

 [0.00030592670988225957 2.4804868368831846e-05 8.268289456277284e-06 ...
  0.06011873263659212 8.268289456277284e-06 0.012741434052123291]
 [6.306192681212951e-05 9.008846687447071e-06 9.008846687447071e-06 ...

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\stats\_multivariate.py", line 1473, in pdf

  0.009053890920884308 9.008846687447071e-06 0.02053116160069188]
    **out = np.exp(self._logpdf(x, alpha))**

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\stats\_multivariate.py", line 1429, in _logpdf

 [0.00016531027466937953 1.2716174974567656e-05 1.2716174974567656e-05

    **lnB = _lnB(alpha)**

  ... 0.11016022380467962 1.2716174974567656e-05 0.03716937945066126]]

  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\stats\_multivariate.py", line 1299, in _lnB

[[0.00025749317662424704 0.00010527436097002069 0.006325259016277311

    **return np.sum(gammaln(alpha)) - gammaln(np.sum(alpha))**

  0.003023905038568522 0.00012555038392464082 0.5658835931500006
  0.011065751322229143 0.00570021768234824 0.025502723498319616

**TypeError: ufunc 'gammaln' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**

  0.0051428807274590885 0.002294796333391969 0.0010615036272685196
  0.012437364502410298 0.00024151595375149294 0.010332509706751682
  0.005031209920683268 7.846435453567337e-05 0.0026861428497574977
  0.06875647943578653 0.008361325235419619 0.00016245998479071417
  0.0002301530456032632 0.00016991267083984486 0.030686970932744393
  5.0871060063154436e-05 0.0021000000348007867 0.00012395159273603657
  0.0030435112124668666 0.011251629396490834 0.02021390498139918
  0.01313284369492176 0.04339827248493694 0.00018056147926369425
  0.018653376755872156 0.0018309967416021635 0.03488521768762044
  0.004032810544503846 0.0585858564721706 0.0002382793332679742
  0.004080405103945404 0.002085968954210397 0.016448085559271585]
 [0.0005543181444832015 0.00038990700155413355 0.032221165473363976
  0.003795736733146513 4.4020469739244005e-05 0.1350590566042479
  0.09231428109256873 0.0025478549910384414 0.1245822262489607
  0.001570719924144179 0.005938566776728663 0.005565930084888204
  0.030098217523830434 0.00015709455979374652 0.018854956899699286
  0.01698214708382771 0.00038060762894568013 0.004971571160329566
  0.1991598532932719 0.0004807682039035813 0.0001642688630986217
  0.0003052054746457523 8.481009161396406e-05 0.012941598271413307
  0.001118484912472326 0.0010650260343213452 0.0007694611732580556
  0.001281602464167419 0.00826813935603708 0.006574234013925613
  0.008228975797096413 0.02317682316934123 0.00022877368073766165
  0.11139662080503565 0.0009295269718998134 0.056352225175161086
  0.00907631788126389 0.010645216233320333 0.0016416129761003657
  0.001675716704723395 0.022647678190705223 0.045758681861195256]
 [5.858751470377472e-05 2.8770914643764048e-05 0.004834688874646715
  0.003247576636838217 3.2885961609330386e-05 0.12864132082621932
  0.01752458544765391 0.0018739161595774055 0.012767876480287425
  0.0029378231588752836 0.002191247920199992 0.0007199490608731109
  0.013677285008259292 9.639424744397179e-05 0.029074873338190088
  0.0027686869389885816 2.182868355248044e-05 0.00012415416098739046
  0.05361400889552769 9.101201300920155e-05 7.85199312717243e-05
  0.00016460101742519465 0.00037037747026833525 0.015250526067846926
  0.001526071639479932 7.330011724909066e-05 0.004172067596945922
  0.0022292884043859716 0.008085368834649597 0.00912079137141882
  0.008783698748321602 0.029641616836750866 5.882082753789326e-05
  0.6127875765639251 0.0007557407697000327 0.01130988230173413
  0.0016169449884249527 0.008528080919174058 0.00011019545960193446
  0.0008722301414952267 0.003507088212478595 0.006629739537827344]]

Process finished with exit code 1
```

I hope that someone can give me some advice, thanks!

**Comment by person142** [comment]
Most likely `Alpha` is a dtype that `gammaln` can't handle. What dtype is it?

**Comment by WarrenWeckesser** [comment]
Can you create a small, self-contained example that we can run to reproduce the problem?  Over on stackoverflow, they call it a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve).

**Comment by WarrenWeckesser** [comment]
Also check `Alpha.dtype`, as @person142 suggests. I can reproduce that error if I pass an `object` array to `gammaln`:

```
In [11]: from scipy.special import gammaln                                      

In [12]: a = np.array([1, 2.5, 10], dtype=object)                               

In [13]: gammaln(a)                                                             
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-62aa566263af> in <module>
----> 1 gammaln(a)

TypeError: ufunc 'gammaln' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

If that is the problem, you can fix it by casting the array to `np.float64`:

```
In [14]: gammaln(a.astype(np.float64))                                          
Out[14]: array([ 0.        ,  0.28468287, 12.80182748])
```

(But it might be better to not create an `object` array in the first place.)

**Comment by xuebaliang** [comment]
@WarrenWeckesser  wow,thanks very much!!! I cast my input dataset to np.float64 and then it works. I find that the dtype of my original input data is really object, you are right.  Thank you very much.

**Comment by WarrenWeckesser** [comment]
@xuebaliang, thanks for the update.
