### ISSUE TITLE
DLL load failure while importing scipy.linalg on Python 3.7 (Microsoft Store)

### ISSUE THREAD

**Issue by stephtr** [scipy/scipy#10171]
Using the Microsoft Store version of Python 3.7 on Windows 10 importing `scipy.linalg` fails. To me this issue seems similar to [numpy#12667](https://github.com/numpy/numpy/issues/12667), which got resolved through [numpy#13019](https://github.com/numpy/numpy/pull/13019).

### Reproducing code example:

`import scipy.linalg`

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\stroy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 190, in <module>
    from .misc import *
  File "C:\Users\stroy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\stroy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

### Scipy/Numpy/Python version information:

```
1.2.1 1.16.3 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by borisal** [comment]
Is there a solution to that?

**Comment by stephtr** [comment]
I just tried it with a fresh installation of Python 3.8 (from the store) and there it seems to work.

**Comment by borisal** [comment]
Thanks 3.8 works fine.

**Comment by stephtr** [comment]
In that case I'll close the issue.
