### ISSUE TITLE
Problem with LTI system conversions in scipy.signal

### ISSUE THREAD

**Issue by JGSuw** [scipy/scipy#10299]
My issue is about using the LTI system class from scipy.signal. Some functions seem to break when they are given a MIMO system.  These issues seem to stem from a dimension test that is performed in lti_conversion.

I will reproduce the issue in the following example, which shows how a simple 2-input 2-output system can break the code. The state dimension for this example is 6, because that is the state dimension I had when I first encountered the issue. 

### Reproducing code example:

```
import scipy.signal as signal
import numpy as np

A = np.mat('0 -1  0  0  0  0;\
            0  0 -1  0  0  0;\
            0  0  0 -1  0  0;\
            0  0  0  0  0  0;\
            0  0  0  0 -1  0;\
            0  0  0  0  0 -1')

B = np.mat('0 0;\
            0 0;\
            0 0;\
            0 0;\
            0 0;\
            1 1')

C = np.mat('0 0 0 0 0 -1;\
            0 0 0 0 0  0')

D = np.mat('0 0;\
            0 0')

sys = signal.StateSpace(A,B,C,D)

# error is produced here
TF = signal.ss2tf(A,B,C,D,input=1)
```
### Error message:

This example causes the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-c755643a5f3e> in <module>()
     18 
     19 # error is produced here
---> 20 TF = signal.ss2tf(A,B,C,D,input=1)

/usr/local/lib/python3.6/dist-packages/scipy/signal/lti_conversion.py in ss2tf(A, B, C, D, input)
    276 
    277     num_states = A.shape[0]
--> 278     type_test = A[:, 0] + B[:, 0] + C[0, :] + D
    279     num = numpy.zeros((nout, num_states + 1), type_test.dtype)
    280     for k in range(nout):

ValueError: operands could not be broadcast together with shapes (6,6) (2,1) 
```

### Scipy/Numpy/Python version information:
The version I am using is from Google Colab,
```
1.3.0 1.16.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
As a general practice you might not want to use numpy.matrix but use numpy.array since numpy.matrix support is not quite uniform across the library and there are discussions about whether we should deprecate it. 

If I use `numpy.array`'s in your example the code goes through but still I think the result is not satisfactory because you get a SIMO result out of a MIMO example. 

Alternatives for now until we fix it using `python-control` with `slycot` installed (on linux it shouldn't be a problem but on windows it is a pain). 

```python
import control as cnt
cnt.ss2tf(A, B, C, D)
```
I get 

```bash
Traceback (most recent call last):

  File "<ipython-input-25-e02b0f2bf37a>", line 1, in <module>
    cnt.ss2tf(A, B, C, D)

  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\control\xferfcn.py", line 1348, in ss2tf
    return _convert_to_transfer_function(StateSpace(*args))

  File "c:\users\appdata\local\programs\python\python37\lib\site-packages\control\xferfcn.py", line 1150, in _convert_to_transfer_function
    raise TypeError("No support for MIMO without slycot.")

TypeError: No support for MIMO without slycot.
```

Or use `harold` (disclosure: I am the author and it almost never supports np.matrix)

```
>>> import harold as har
>>> G = har.State(*map(np.array, (A, B, C, D)))  # Mapping np.matrix objects to np.array
>>> H = har.state_to_transfer(G)
>>> H.polynomials
([[array([[-1., -1.,  0.,  0.,  0.,  0.]]),
   array([[-1., -1.,  0.,  0.,  0.,  0.]])],
  [array([[0.]]), array([[0.]])]],
 [[array([[ 1.,  2.,  1.,  0., -0.,  0.,  0.]]),
   array([[ 1.,  2.,  1.,  0., -0.,  0.,  0.]])],
  [array([[1.]]), array([[1.]])]])

>>> H
Continuous-Time Transfer function
 2 inputs and 2 outputs

  Poles(real)    Poles(imag)    Zeros(real)    Zeros(imag)
-------------  -------------  -------------  -------------
            0              0              0              0
            0              0             -0              0
            0              0              0              0
            0              0             -0              0
            0              0             -1              0
            0              0
            0              0
            0              0
           -1              0
           -1              0
           -1              0
           -1              0

```
