### ISSUE TITLE
QuTiP executive error due to upgrade of scipy

### ISSUE THREAD

**Issue by zhangyintai** [scipy/scipy#10308]
QuTiP executive error occured due to upgrade of scipy.

Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qutip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python36\lib\site-packages\qutip\__init__.py", line 171, in <module>
    from qutip.qobj import *
  File "D:\Python\Python36\lib\site-packages\qutip\qobj.py", line 60, in <module>
    from qutip.fastsparse import fast_csr_matrix, fast_identity
  File "D:\Python\Python36\lib\site-packages\qutip\fastsparse.py", line 37, in <module>
    from scipy.sparse.sputils import (upcast, upcast_char, to_native, isdense, isshape,
ImportError: cannot import name 'IndexMixin'
>>>

**Comment by rgommers** [comment]
`IndexMixin` got moved and changed in gh-7827. It was private though, so QuTiP should not be using it. I suggest you ping the QuTiP team about this.

**Comment by zhangyintai** [comment]
Thanks. I'll email them about the problem.
