### ISSUE TITLE
BUG: interpolate.NearestNDInterpolator with pandas

### ISSUE THREAD

**Issue by yamaken1343** [scipy/scipy#10352]
interpolate.NearestNDInterpolator does not work as expected when used  with selected pandas dataframe.
This is due to the index being maintained when making selections in pandas.

### Reproducing code example:
```
import numpy as np
import pandas as pd
from scipy import interpolate

df = pd.DataFrame(np.array([[0, 0, 0, 0, 1, 0, 1],
                            [0, 0, 0, 0, 0, 1, 1],
                            [0, 0, 0, 0, 1, 1, 2]]).T, columns=['x', 'y', 'z'])
df_select = df[3:]
NI = interpolate.NearestNDInterpolator((df_select.x, df_select.y), df_select.z)
print(NI([0.1, 0.9], [0.1, 0.9]))
```
I expect [0, 2] to be output.
But output is [Nan, 0] as pandas.Series.

This is due to the index being maintained when making selections in pandas.
Specifically, `df_select.z` has index[3, 4, 5, 6].
But, self.tree.query (xi) line 81, in scipy/interpolate/ndgriddata.py returns a index that assumes that the index starts from zero.
So, self.tree.query (xi) return [0, 3]
Therefore, self.values[i] line 82, in scipy/interpolate/ndgriddata.py using Invalid index.

### Note
if case of
```
df_select = df[3:].reset_index()
```
or
```
NI = interpolate.NearestNDInterpolator((df_select.x, df_select.y), np.array(df_select.z))
```
it works as expected.

Also, this bug does not occur in interpolate.LinearNDInterpolator.

### Scipy/Numpy/Python version information:
```
1.3.0 1.16.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
I think you have to watch for the warnings Pandas emits 

```
c:\users\appdata\local\programs\python\python36\lib\site-packages\pandas\core\series.py:696: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]
```

Here this is exactly what is happening as far as I can see

**Comment by yamaken1343** [comment]
Thank you.
There are similar warnings in my environment.

**Comment by yamaken1343** [comment]
Additional Note.
interpolate.NearestNDInterpolator does not work when used with python list.

```
NI = interpolate.NearestNDInterpolator((df_select.x, df_select.y), list(df_select.z))
print(NI(0.1, 0.1))
```
is work.

But, 
```
NI = interpolate.NearestNDInterpolator((df_select.x, df_select.y), list(df_select.z))
print(NI([0.1, 0.9], [0.1, 0.9]))
```
is not work with
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/JetBrains/apps/PyCharm-P/ch-0/191.7479.30/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/JetBrains/apps/PyCharm-P/ch-0/191.7479.30/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/yamaken/Programs/test_NearestNDInterpolator/v2.py", line 12, in <module>
    print(NI([0.1, 0.9], [0.1, 0.9]))
  File "/home/yamaken/Programs/test_NearestNDInterpolator/venv/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 81, in __call__
    return self.values[i]
TypeError: only integer scalar arrays can be converted to a scalar index
```
# 10353 corrects this.
