### ISSUE TITLE
ENH: optimize.minimize: slsqp: give better error when work array overflows

### ISSUE THREAD

**Issue by TimmyV117** [scipy/scipy#10416]
My issue is about ```mode``` in _minimize_slsqp  in slsqp.py where when minimize() is called, the key for which exit message is to be used is somehow generated and is not within the exit_modes dictionary and I'm not sure how that's possible. Specifically, -200448291 is somehow defined somewhere, which is the value causing the KeyError

### Reproducing code example:

```
# Where this seems to be failing
res = minimize(opt_funct, x0, method='SLSQP',
               constraints=[equality_constraints,
                            inequality_constraints],
               bounds=bounds,
               options={'ftol': 1e-3, 'eps': 10.0, 'maxiter': 5},
               args=(coef_df,))

# CODE FOR REPRODUCING ERROR

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.optimize import Bounds

bounds = Bounds(np.zeros(66619), np.full(66619, fill_value=1e12))

coef_df = pd.DataFrame(np.random.randint(0,200, size=(66619, 8)))
coef_df = coef_df.rename(columns={7:'coef'})

eq_matrix = np.array(np.random.randint(0,1000, size=(197, 66620)))
ineq_matrix = np.array(np.random.randint(0,1000, size=(42, 66620)))

def opt_funct(x, coef_df):
    """returns the optimization value"""
    return (-100000.0) * np.dot(
        coef_df['coef'], np.sqrt(x))

def _write_constraint_matrix(constr_matrix, x):
    """Create a constraint matrix that can be put into scipy.optimize.minimize

    Parameters
    ----------
    constr : 2-d np.array
        matrix of constraints
    x : np.array
        vector of optimization output values

    Returns
    -------
    vector of values for the inequality or equality constraint
    """
    return np.dot(constr_matrix[:, :-1], x) + constr_matrix[:, -1]


def initialize_x0(eq_matrix, ineq_matrix, coef_df):
    """Create a valid x0 to initialize scipy.optimize.minimize

    Parameters
    ----------
    eq_matrix : 2-d np.array
        matrix of equality constraints
    ineq_matrix : 2-d np.array
        matrix of inequality constraints
    coef_df : pd.DataFrame
        DataFrame that contains model coefficients

    Returns
    -------
    x0 that meets initialization constraints
    """
    # include only minimum constraints which must be met by x0 and
    # convert them to max constraints for initializing x0
    x0_ineq = -1 * ineq_matrix[ineq_matrix[:, -1] < 0, :]
    x0_ineq = np.vstack([eq_matrix, x0_ineq])
    bounds = Bounds(
            np.zeros(coef_df.shape[0]),
            np.full((coef_df.shape[0]), fill_value=1e12))

    inequality_constraints = {'type': 'ineq',
                              'fun': lambda x: np.array(
                                _write_constraint_matrix(
                                  x0_ineq, x
                                  )
                                  ),
                              'jac': lambda x: [y[:-1] for y in x0_ineq]
                              }
    x0 = np.zeros(coef_df.shape[0])
    # TODO replace/remove maxiter and update eps
    res = minimize(fun=opt_funct, x0=x0, method='SLSQP',
                   constraints=inequality_constraints,
                   bounds=bounds,
                   options={'ftol': 1e-3, 'eps': 10000.0,
                            'disp': True, 'maxiter': 1000000},
                   args=(coef_df, ))
    new_x0 = res['x']
    new_x0[new_x0 >= 1e11] = 0
    return new_x0

if __name__ == '__main__:
     x0 = initialize_x0(eq_matrix, ineq_matrix, coef_df)
```

### Error message:

```
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/Users/anaconda/envs/my_env/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 611, in minimize
    constraints, callback=callback, **options)
  File "/Users/anaconda/envs/my_env/lib/python3.6/site-packages/scipy/optimize/slsqp.py", line 454, in _minimize_slsqp
    message=exit_modes[int(mode)], success=(mode == 0))
KeyError: -200448291
```

### Scipy/Numpy/Python version information:

First discovered on scipy==1.1.0 but also tried on 1.2.0 and 1.3.0
```
numpy==1.16.3
pandas==0.23.4
scipy==1.1.0
python==3.6
```

**Comment by ev-br** [comment]
A reproducible example would be helpful

**Comment by TimmyV117** [comment]
@ev-br thanks for the reminder and looking into this. Added a reproducible script above in the ticket.

**Comment by pv** [comment]
It's due to work array size overflowing 32-bit signed integer.
The problem is too large for SLSQP (with the default fortran 32-bit integers).

**Comment by zhaonat** [comment]
@pv does this mean the type in your array of optimizable parameters should be downcasted?

**Comment by ilayn** [comment]
After #22524, this now gives a better error from the Python side since now the allocation is done on the Python side 

```Python
File ~\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_slsqp_py.py:455, in _minimize_slsqp(func, x0, args, jac, bounds, constraints, maxiter, ftol, iprint, disp, eps, callback, finite_diff_rel_step, workers, **unknown_options)
    453 if mieq == 0:
    454     buffer_size += 2*n*(n + 1)
--> 455 buffer = np.zeros(max(buffer_size, 1), dtype=np.float64)
    457 # mode is zero on entry, so call objective, constraints and gradients
    458 # there should be no func evaluations here because it's cached from
    459 # ScalarFunction
    460 fx = wrapped_fun(x)

MemoryError: Unable to allocate 281. GiB for an array with shape (37765513473,) and data type float64
```
