### ISSUE TITLE
BUG: scipy.fft does not support multiprocessing

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#10422]
`scipy.fft` interacts badly with `joblib`, specifically when using the "processes" method. @peterbell10 tested and reports that it also fails for `multiprocessing.Pool` directly. But here was my MWE with joblib:
```Python
>>> import numpy as np
>>> from joblib import Parallel, delayed
>>> from scipy.fft import rfft
>>> [rfft(np.zeros(1)) for _ in range(2)]  # works
>>> Parallel(n_jobs=2, prefer='threads')(delayed(rfft)(np.zeros(1)) for _ in range(2))  # works
>>> Parallel(n_jobs=2, prefer='processes')(delayed(rfft)(np.zeros(1)) for _ in range(2))  # fails
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/larsoner/python/joblib/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/larsoner/python/joblib/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/larsoner/python/joblib/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/larsoner/python/scipy/scipy/fft/_basic.py", line 298, in rfft
    return _pocketfft.rfft(x, n, axis, norm, overwrite_x)
  File "/home/larsoner/python/scipy/scipy/fft/_pocketfft/basic.py", line 134, in rfft
    return pfft.r2c(tmp, (axis,), True, norm, None, _default_workers)
RuntimeError: unsupported data type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/larsoner/python/joblib/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/larsoner/python/joblib/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: unsupported data type
```
Modifying the SciPy code to print the dtype and `__class__` of at least `tmp` shows `np.float64` and `np.ndarray` as expected, so I'm not sure what unsupported datatype we are getting.

**Comment by andyfaff** [comment]
Does rfft use openmp?

**Comment by peterbell10** [comment]
It's unrelated. The root cause is comparing dtypes using `is` which doesn't breaks across forks. I have a fix locally, PR soon.

**Comment by ariedel** [comment]
Some aspects of this bug still seem to exist in 1.4.1: I now get this error in fftconvolve unless I specifically cast my data (original type: numpy.ndarray) as a numpy.float32 dtype, which wasn't necessary before.

**Comment by peterbell10** [comment]
@ariedel thanks for your report, this should be fixed by gh-11534.

In future though, you might want to open a new issue instead of commenting on a different issue. Especially one that's been fixed already, since your comment could easily be missed.
