### ISSUE TITLE
module 'scipy' has no attribute 'special'

### ISSUE THREAD

**Issue by khider** [scipy/scipy#10662]
My issue is about spicy import

#### Reproducing code example:

```
from scipy.stats.mstats import mquantiles
```

#### Error message:

```
Traceback (most recent call last):

  File "<ipython-input-12-181213242524>", line 1, in <module>
    from scipy.stats.mstats import mquantiles

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 379, in <module>
    from .stats import *

  File "/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 180, in <module>
    import scipy.special as special

AttributeError: module 'scipy' has no attribute 'special'
  ...
```

**Comment by ev-br** [comment]
This is a symptom of a broken scipy installation. Reinstall scipy.
