### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid stored block lengths

### ISSUE THREAD

**Issue by kouxichao** [scipy/scipy#10705]
**when i lode gt.mat of SynthText dataset. The error occurs.**

**the details of error:** 
Traceback (most recent call last):
  File "dataset/synth-text/make_list.py", line 13, in <module>
    gt = io.loadmat(gt_mat_path)
  File "/home/kxc/.conda/envs/pt/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 218, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/home/kxc/.conda/envs/pt/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/home/kxc/.conda/envs/pt/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 719, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 892, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 703, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 776, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 195, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 171, in scipy.io.matlab.streams.ZlibInputStream.read_into
  File "streams.pyx", line 158, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -3 while decompressing data: invalid stored block lengths

**Comment by andyfaff** [comment]
Can you make the mat file available somewhere so that we can try and investigate further?

**Comment by kouxichao** [comment]
There is a problem with the downloaded file. There is no error after re-downloading. thanks for your reply.

**Comment by MEGHADDAS98** [comment]
Hi how did you configure what problem was with the downloaded file, because i am also getting the same error but dont know how to resolve it .
