### ISSUE TITLE
Inequality constraints incompatible for optimize.minimize/SLSQP (but machine-dependent?)

### ISSUE THREAD

**Issue by kratsg** [scipy/scipy#10740]
My issue is about trying to debug inequality constraints incompatible errors that are not reproducible on all machines (so far, reproducible on CC7, ubuntu - but not Mac or SLC6?). I can't find a simple MWE but I'm hoping to file this issue to get some help in trying to debug what's going on...

The constraint function we have is a single equality constraint function of `lambda v: v[variable index] - value`. I added print functions to understand what's going on in that constraint function, but it looks like it's behaving normally, yet `scipy.optimize.minimize` seems to not converge / error on some machines and I'm not sure what else to try.

#### Code overview

If you're ok with a non-simple MWE, try running (documented in scikit-hep/pyhf#532):

```
pip install pyhf
curl -sL https://git.io/fjxs5 | pyhf cls
```

with the minimization happening in `pyhf/optimize/opt_scipy.py#constrained_bestfit` (modified version reproduced below for attempt at debugging):

```
    def constrained_bestfit(
        self, objective, constrained_mu, data, pdf, init_pars, par_bounds
    ):
        def const_fun(v):
            print(v[pdf.config.poi_index], constrained_mu, v[pdf.config.poi_index] - constrained_mu)
            return v[pdf.config.poi_index] - constrained_mu

        # The Fit Conditions on a specific POI value
        cons = [{'type': 'eq', 'fun': const_fun}]

        result = minimize(
            objective,
            init_pars,
            constraints=cons,
            method='SLSQP',
            args=(data, pdf),
            bounds=par_bounds,
            options=dict(maxiter=self.maxiter, disp=True),
        )
        try:
            assert result.success
        except AssertionError:
            log.error(result)
            raise
        return result.x
```

#### Output and error message:

```
1.0 1.0 0.0
1.0 1.0 0.0
1.0 1.0 0.0
...
1.0 1.0 0.0
Inequality constraints incompatible    (Exit mode 4)
            Current function value: 77.15527561970944
            Iterations: 136
            Function evaluations: 14765
            Gradient evaluations: 135
ERROR:pyhf.optimize.opt_scipy:     fun: 77.15527561970944
     jac: array([-7.08480167e+00,  8.49217033e+00,  1.47080661e+10,  3.28612328e+00,
       -7.54327774e-02, -6.71205521e-02,  5.35310745e-01,  4.01000118e+00,
       -1.52311325e-02,  1.20483060e+10,  1.16036771e+10,  1.15527170e+10,
        1.18632331e+10,  1.17691731e+10,  1.18977633e+10,  1.19250902e+10,
        1.18539326e+10,  1.48514556e+10, -1.04761124e-02, -6.01768494e-03,
       -1.34086609e-02, -2.98023224e-03,  1.56818973e+10,  6.58941269e-02,
        1.38932475e+10, -1.28894511e+02, -1.01770562e+02, -8.27344036e+00,
        1.90276623e+00, -2.19297028e+00,  1.20877792e+10,  1.05468491e+02,
        9.59411879e+01,  1.06477322e+02, -1.38329642e+02,  1.00819942e+02,
        1.26329247e+10, -9.22628508e+01, -7.78497505e+00,  1.51617641e+10,
        5.25423813e+00,  7.95975685e+00, -1.40474367e+01, -9.47475433e-03,
        9.56916809e-03, -1.23852444e+00,  6.51121140e-02, -3.54166031e-02,
       -1.73975945e-01, -6.83498383e-03, -8.06808472e-03, -9.57841873e-02,
       -3.35457802e-01,  2.93636322e-03,  1.64589882e-01, -5.11579514e-02,
        2.00636864e-01,  1.38281822e-01,  6.02092743e-02,  1.48000717e-01,
        7.17143059e-01,  4.84459877e-01, -1.01908684e-01,  7.82966614e-04,
       -7.94630051e-02,  2.16858864e-01, -1.06441498e-01,  1.34514809e-01,
        6.90739632e-01, -9.29346085e-02,  2.29740143e-02, -1.27667427e-01,
       -5.42078018e-02,  9.33218002e-02,  1.10701561e-01,  8.41569901e-02,
       -8.58306885e-06, -4.67737198e-01, -5.64012527e-02, -3.72366905e-01,
        2.63403893e-01, -7.28788376e-02,  1.74274445e-01,  2.84705162e-01,
        1.45734787e-01,  2.28877068e-01, -3.75935555e-01, -2.49648094e-01,
        2.57492065e-05, -2.14330673e-01, -3.54086399e+00, -1.08406162e+00,
        5.66859245e-01,  7.30214119e-01,  2.56684303e-01, -2.06280708e-01,
        1.26627254e+00, -3.62828255e-01,  3.13681602e-01, -4.93485451e-01,
       -9.25016403e-02,  2.30152130e-01,  1.74009991e+00, -1.03737831e-01,
        1.68754578e-01])
 message: 'Inequality constraints incompatible'
    nfev: 14765
     nit: 136
    njev: 135
  status: 4
 success: False
       x: array([ 9.99931456e-01,  1.03394352e+00, -1.07643301e-01,  1.11943363e+00,
       -3.75214605e-01, -2.93212493e-01,  1.03617837e+00,  1.00233044e+00,
        2.11720459e-01, -1.41021389e-01, -3.57913462e-02, -2.00447156e-02,
       -1.00379036e-01, -8.00860497e-02, -1.10362235e-01, -1.15776289e-01,
       -9.94856267e-02, -1.08874137e-01, -9.04132016e-02, -1.26013655e-02,
       -6.78190876e-03,  3.51948286e-03,  7.88452777e-02, -2.03839214e-01,
        8.67741934e-02, -9.57755727e-02, -6.88399120e-02, -6.02747985e-03,
        2.89433559e-03, -1.45240618e-03,  1.30866135e-01,  6.32401900e-02,
        5.41963243e-02,  7.36358010e-02, -1.05494593e-01,  7.11174277e-02,
        1.08841570e-01, -6.17440100e-02, -5.65815477e-03,  8.00748101e-02,
       -9.12257332e-02,  1.00000000e+00,  9.99795418e-01,  4.26362464e-02,
        1.73185717e-02,  9.99265203e-01, -8.28649742e-02,  2.22891209e-02,
        1.64570376e-02, -4.48735856e-03, -1.77954514e-02, -1.65394409e-01,
        9.91774213e-01,  1.01181722e+00,  1.11034657e+00, -8.75109490e-02,
        9.98451577e-01,  9.71563037e-01,  1.00550858e+00,  9.87519064e-01,
        1.00053532e+00,  9.99716238e-01,  1.00236568e+00,  1.80122396e-02,
        1.01793523e+00,  9.81009553e-01,  1.03556916e+00,  1.01505353e+00,
        9.76753479e-01,  9.94956383e-01,  1.05613511e+00,  1.04774403e+00,
        1.01198600e+00,  1.00563437e+00,  9.63984652e-02,  9.81936668e-01,
       -1.86765293e-04,  1.01079457e+00,  9.93703776e-01,  1.01142716e+00,
        1.00674961e+00,  1.00424476e+00,  1.00195613e+00,  1.01622586e+00,
        1.01148516e+00,  9.98712072e-01,  9.96932377e-01,  9.78641139e-01,
        3.82186848e-05,  1.00012172e+00,  9.98450699e-01,  9.74585427e-01,
        1.02642222e+00,  1.00512905e+00,  9.97932481e-01,  1.00604323e+00,
        1.00370171e+00,  9.97360167e-01,  9.96021892e-01,  9.98139725e-01,
        9.99044265e-01,  9.90320861e-01,  1.02224232e+00,  9.79388460e-01,
        1.02875997e+00])
Traceback (most recent call last):
  File "/afs/cern.ch/user/g/gstark/env-pyhf/bin/pyhf", line 11, in <module>
    sys.exit(pyhf())
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/commandline.py", line 259, in cls
    result = hypotest(testpoi, w.data(p), p, qtilde=is_qtilde, return_expected_set=True)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/utils.py", line 288, in hypotest
    qmu(poi_test, asimov_data, pdf, init_pars, par_bounds), 0, max_value=None
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/utils.py", line 113, in qmu
    loglambdav, mu, data, pdf, init_pars, par_bounds
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/optimize/opt_scipy.py", line 48, in constrained_bestfit
    assert result.success
AssertionError
```

#### Scipy/Numpy/Python version information:

```
1.3.1 1.17.0 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

./cc @matthewfeickert @lukasheinrich

**Comment by kratsg** [comment]
NB: with the `disp=True` option enabled, we just additionally see this output

```
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 114.21281626391162
            Iterations: 204
            Function evaluations: 22071
            Gradient evaluations: 204
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 101.96132355405202
            Iterations: 219
            Function evaluations: 23720
            Gradient evaluations: 219
Inequality constraints incompatible    (Exit mode 4)
            Current function value: 77.15527561970944
            Iterations: 136
            Function evaluations: 14765
            Gradient evaluations: 135
```

**Comment by DongqinZhou** [comment]
Hi~ Did you solve this problem? I'm running into a similar one.

**Comment by kratsg** [comment]
Nope: still an open issue scikit-hep/pyhf#532

**Comment by lrnv** [comment]
Hi, 

If i understand correctly the thread here : http://scipy-user.10969.n7.nabble.com/SciPy-User-optimize-fmin-slsqp-bounds-problem-td18779.html the problem might come directly from the SLSQP fortran code, and is there since a few years now... Sadly i have no capabilities of reading fortran !

**Comment by JoElfner** [comment]
I'd also like to push this issue, since I recently ran into it. I checked that my constraints and solution are feasible.

**Comment by lrnv** [comment]
I know that the Nlopt code correct this issue. Maybe looking at it will give the solution ?

**Comment by pv** [comment]
The error message does not indicate a single issue, and can have many
causes (incl. just numerical precision issues). So if you have an issue
please try to find a reproducible example case and paste it on
gist.github.com and link here. The example here is not so easy to get
to reproduce.

Nlopt has fixes, but afaik the scipy slsqp has fixes for the same
issues. (If you known a same problem that works in one but not in the
other, please try to give a reproducible example.)

**Comment by a2tm7a** [comment]
Hi. I am running into a similar issue. Did you find the solution?

**Comment by a2tm7a** [comment]
I was able to solve the issue. My bounds for some of the variables were (0, 0). This was working in mac, but in windows I had to change it to (0, 0.000001) and then it worked.

**Comment by andyfaff** [comment]
SLSQP has had various amendments over the last year or so, including:

- clipping solutions to make sure x is within bounds.
- factorising out parameters that have lb==ub.

Given that there's no clear minimal working example I'm going to close the issue. If an MWE is found then please reopen.

**Comment by aleksejs-fomins** [comment]
Hey guys, I have found 2 minimal examples. Please reopen the issue

1.  "Inequality constraints incompatible" occurs when loss function is `np.nan`. I hope this helps somebody, the error message is really not useful in this case

2.  "Inequality constraints incompatible" occurs when loss function makes no sense to the optimizer. To really force the issue, I have used a completely random loss function. However, I can imagine that similar behaviour would occur for fully deterministic functions in case the loss function provided is sufficiently chaotic.  In any case, the error message is totally misleading, this error has nothing at all to do with the constraints, and everything to do with the inability of the solver to make progress.

```
import numpy as np
from scipy.optimize import minimize

np.random.seed = 42

def f(x):
    # return np.sum(x**2) - np.sum(x)
    return np.random.uniform(0, 1)

nParam = 300
bounds = [(0.0, 1.0)] * nParam

x0 = np.random.uniform(0, 1, nParam)
sol = minimize(f, x0, bounds=bounds, method='SLSQP')
```
