### ISSUE TITLE
Assert from f2py when installing from source

### ISSUE THREAD

**Issue by Juanlu001** [scipy/scipy#10779]
I am trying to install SciPy from source and I'm having this error:

```
$ python setup.py install
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
Running scipy/special/_generate_pyx.py
Running scipy/linalg/_generate_pyx.py
scipy/interpolate/_ppoly.pyx has not changed
scipy/optimize/_trlib/_trlib.pyx has not changed
scipy/optimize/_lsq/givens_elimination.pyx has not changed
scipy/signal/_max_len_seq_inner.pyx has not changed
scipy/interpolate/_bspl.pyx has not changed
scipy/signal/_upfirdn_apply.pyx has not changed
scipy/ndimage/src/_cytest.pyx has not changed
scipy/signal/_spectral.pyx has not changed
scipy/sparse/_csparsetools.pyx.in has not changed
scipy/optimize/_group_columns.pyx has not changed
scipy/sparse/csgraph/_traversal.pyx has not changed
scipy/sparse/csgraph/_min_spanning_tree.pyx has not changed
scipy/sparse/csgraph/_tools.pyx has not changed
scipy/sparse/csgraph/_reordering.pyx has not changed
scipy/special/_ufuncs_cxx.pyx has not changed
scipy/sparse/csgraph/_shortest_path.pyx has not changed
scipy/ndimage/src/_ni_label.pyx has not changed
scipy/interpolate/interpnd.pyx has not changed
scipy/special/_ellip_harm_2.pyx has not changed
scipy/special/cython_special.pyx has not changed
scipy/spatial/ckdtree.pyx has not changed
scipy/spatial/_voronoi.pyx has not changed
scipy/special/_comb.pyx has not changed
scipy/spatial/qhull.pyx has not changed
scipy/linalg/_decomp_update.pyx.in has not changed
scipy/spatial/_hausdorff.pyx has not changed
scipy/linalg/cython_lapack.pyx has not changed
scipy/special/_ufuncs.pyx has not changed
scipy/linalg/cython_blas.pyx has not changed
scipy/special/_test_round.pyx has not changed
scipy/linalg/_solve_toeplitz.pyx has not changed
scipy/cluster/_optimal_leaf_ordering.pyx has not changed
scipy/cluster/_hierarchy.pyx has not changed
scipy/cluster/_vq.pyx has not changed
scipy/_lib/messagestream.pyx has not changed
scipy/_lib/_ccallback_c.pyx has not changed
scipy/stats/_stats.pyx has not changed
scipy/io/matlab/mio_utils.pyx has not changed
scipy/io/matlab/streams.pyx has not changed
scipy/io/matlab/mio5_utils.pyx has not changed

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Cythonizing sources
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/home/juanlu/.pyenv/versions/scipy37_4/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC

creating /tmp/tmpwqu_j502/tmp
creating /tmp/tmpwqu_j502/tmp/tmpwqu_j502
compile options: '-c'
gcc: /tmp/tmpwqu_j502/source.c
gcc -pthread /tmp/tmpwqu_j502/tmp/tmpwqu_j502/source.o -L/usr/lib/x86_64-linux-gnu -lopenblas -o /tmp/tmpwqu_j502/a.out
customize UnixCCompiler
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

Splitting linalg.interpolative Fortran source files
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/home/juanlu/.pyenv/versions/scipy37_4/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

blis_info:
customize UnixCCompiler
  libraries blis not found in ['/home/juanlu/.pyenv/versions/scipy37_4/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

[makenpz] scipy/special/tests/data/boost.npz is already up to date
[makenpz] scipy/special/tests/data/gsl.npz is already up to date
[makenpz] scipy/special/tests/data/local.npz is already up to date
non-existing path in 'scipy/signal/windows': 'tests'
non-existing path in 'scipy/sparse': 'sparsetools/sparsetools_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/bsr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csc_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/other_impl.h'
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building library "dfftpack" sources
building library "fftpack" sources
building library "mach" sources
building library "quadpack" sources
building library "lsoda" sources
building library "vode" sources
building library "dop" sources
building library "fitpack" sources
building library "fwrappers" sources
building library "odrpack" sources
building library "minpack" sources
building library "rootfind" sources
building library "superlu_src" sources
building library "arpack_scipy" sources
building library "sc_c_misc" sources
building library "sc_cephes" sources
building library "sc_mach" sources
building library "sc_amos" sources
building library "sc_cdf" sources
building library "sc_specfun" sources
building library "statlib" sources
building extension "scipy.cluster._vq" sources
building extension "scipy.cluster._hierarchy" sources
building extension "scipy.cluster._optimal_leaf_ordering" sources
building extension "scipy.fftpack._fftpack" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/fftpack/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/fftpack' to include_dirs.
building extension "scipy.fftpack.convolve" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/fftpack/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/fftpack' to include_dirs.
building extension "scipy.integrate._quadpack" sources
building extension "scipy.integrate._odepack" sources
building extension "scipy.integrate.vode" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate' to include_dirs.
building extension "scipy.integrate.lsoda" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate' to include_dirs.
building extension "scipy.integrate._dop" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate' to include_dirs.
building extension "scipy.integrate._test_multivariate" sources
building extension "scipy.integrate._test_odeint_banded" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/integrate' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/scipy/integrate/_test_odeint_banded-f2pywrappers.f' to sources.
building extension "scipy.interpolate.interpnd" sources
building extension "scipy.interpolate._ppoly" sources
building extension "scipy.interpolate._bspl" sources
building extension "scipy.interpolate._fitpack" sources
building extension "scipy.interpolate.dfitpack" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/interpolate/src/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/interpolate/src' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/scipy/interpolate/src/dfitpack-f2pywrappers.f' to sources.
building extension "scipy.interpolate._interpolate" sources
building extension "scipy.io._test_fortran" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/io/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/io' to include_dirs.
building extension "scipy.io.matlab.streams" sources
building extension "scipy.io.matlab.mio_utils" sources
building extension "scipy.io.matlab.mio5_utils" sources
building extension "scipy.linalg._fblas" sources
f2py options: []
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg' to include_dirs.
  adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_fblas-f2pywrappers.f' to sources.
building extension "scipy.linalg._flapack" sources
f2py options: []
f2py: build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf
Running from scipy source directory.
/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.7m is invalid.
  return self.get_paths(self.section, key)
/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/include/python3.7m is invalid.
  return self.get_paths(self.section, key)
Reading fortran codes...
	Reading file 'build/src.linux-x86_64-3.7/scipy/linalg/flapack.pyf' (format:free)
Traceback (most recent call last):
  File "setup.py", line 415, in <module>
    setup_package()
  File "setup.py", line 411, in setup_package
    setup(**metadata)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/egg_info.py", line 26, in run
    self.run_command("build_src")
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/juanlu/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 142, in run
    self.build_sources()
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_extension_sources(ext)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 319, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/distutils/command/build_src.py", line 535, in f2py_sources
    + ['--build-dir', target_dir, source])
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1098, in analyzeline
    last_name = updatevars(typespec, selector, attr, edecl)
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1542, in updatevars
    attrspec = [x.strip() for x in markoutercomma(attrspec).split('@,@')]
  File "/home/juanlu/.pyenv/versions/scipy37_4/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'intent(in))', 'intent(in))')
```

#### Scipy/Numpy/Python version information:

```
$ python
Python 3.7.4 (default, Aug 26 2019, 17:42:54) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version_info)
1.17.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by Juanlu001** [comment]
Sorry, I was building an ancient version of SciPy, prior to https://github.com/scipy/scipy/pull/8530. Closing.
