### ISSUE TITLE
BUG: optimize: methods unknown to `scipy.optimize.show_options`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10782]
Some `scipy.optimize.minimize` and `scipy.optimize.linprog` solvers aren't known to `scipy.optimize.show_options`.

#### Reproducing code example:

```
from scipy.optimize import show_options
show_options('minimize', 'trust-ncg')  # OK
show_options('minimize', 'trust-constr')  # not OK
show_options('linprog', 'interior-point')  # OK
show_options('linprog', 'revised simplex')  # not OK
```

#### Error message:

```
Traceback (most recent call last):

  File "<ipython-input-9-2adcf805db05>", line 1, in <module>
    show_options('linprog', 'revised simplex')

  File "C:\Users\mhaberla\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 3104, in show_options
    raise ValueError("Unknown method %r" % (method,))

ValueError: Unknown method 'revised simplex'
  ...
```

#### Scipy/Numpy/Python version information:
```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
Should probably add a test like:
```
solver_methods = {'linprog':['simplex', 'revised simplex', 'interior-point']} 
for solver, methods in solver_methods.items():
    for method in methods:
        show_options(solver, method)
```
to make sure there are no errors, except that the method names should not be hard-coded into the test itself, rather imported from a list in the solver's main file as proposed in gh-10763.
