### ISSUE TITLE
BUG: solve_ivp and lsoda method does not work with array_like jacobians 

### ISSUE THREAD

**Issue by MatthewFlamm** [scipy/scipy#10864]
solve_ivp supposedly accepts jacobians with `array_like` type for jacobians that can be assumed to be constant with time and state.  However, both LSODA implementations in scipy require callable jacobians, and solve_ivp uses the ode integrator implementation.

Note that LSODA method requires a stiff ODE to actually test this, but only recently have stiff solutions been added to tests, although only in a limited fashion, in #10309.  So this isn't being tested for in the test suite.

I'm using the same problem set up as in #10793 .

#### Reproducing code example:

```
from scipy.integrate import solve_ivp, odeint, ode
import numpy as np

def f(t, y):
    return np.array([
        y[0],
        -0.04 * y[1] + 1e4 * y[2] * y[3],
        0.04 * y[1] - 1e4 * y[2] * y[3] - 3e7 * y[2]**2,
        3e7 * y[2]**2,
        y[4]
    ])

def jac(t, y):
    return np.array([
        [1,     0,                    0,         0, 0],
        [0, -0.04,             1e4*y[3],  1e4*y[2], 0],
        [0,  0.04, -1e4*y[3]-3e7*2*y[2], -1e4*y[2], 0],
        [0,     0,           3e7*2*y[2],         0, 0],
        [0,     0,                    0,         0, 1]
    ])

rtol = 1e-8
atol = 1e-10

tspan = (0, 1000)
t_eval = np.linspace(*tspan, 100)
y0 = np.array([0, 1, 0, 0, 0])
method = 'LSODA'

jac_const = jac(0, y0)

sol = solve_ivp(f, tspan, y0, t_eval=t_eval, method='LSODA', rtol=rtol, atol=atol)
sol_jac = solve_ivp(f, tspan, y0, jac=jac, t_eval=t_eval, method='LSODA', rtol=rtol, atol=atol)
assert np.allclose(sol.y, sol_jac.y)
sol_jac_const = solve_ivp(f, tspan, y0, jac=jac_const, t_eval=t_eval, method='LSODA', rtol=rtol, atol=atol)
#error
assert np.allclose(sol.y, sol_jac_const.y)
```

#### Error message:

```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    sol_jac_const = solve_ivp(f, tspan, y0, jac=jac_const, t_eval=t_eval, method='LSODA', rtol=rtol, atol=atol)
  File "/SFS/user/wp/flammm/testsp/venv/lib/python3.6/site-packages/scipy/integrate/_ivp/ivp.py", line 502, in solve_ivp
    message = solver.step()
  File "/SFS/user/wp/flammm/testsp/venv/lib/python3.6/site-packages/scipy/integrate/_ivp/base.py", line 182, in step
    success, message = self._step_impl()
  File "/SFS/user/wp/flammm/testsp/venv/lib/python3.6/site-packages/scipy/integrate/_ivp/lsoda.py", line 149, in _step_impl
    solver.f, solver.jac or (lambda: None), solver._y, solver.t,
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by MatthewFlamm** [comment]
This is clearly stated in the documentation, but IMO, the documentation is hard to parse in the current format with so many edge cases depending on solver usage.
