### ISSUE TITLE
ImportWarning: can't resolve package from __spec__ or __package__ ...

### ISSUE THREAD

**Issue by EricCousineau-TRI** [scipy/scipy#11000]
My issue is about an `ImportWarning` when importing scipy 0.19.1 on Ubuntu 18.04 (encountered in https://github.com/robotlocomotion/drake/pull/12218)

#### Reproducing code example:
```
import warnings; warnings.simplefilter("error", Warning); import scipy
```

#### Error message:
```
$ python3 -c 'import warnings; warnings.simplefilter("error", Warning); import scipy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/usr/lib/python3/dist-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "scipy/_lib/_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c (scipy/_lib/_ccallback_c.c:3479)
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

#### Extra Notes

I've tried rebuilding `scipy @ v0.19.1` on my system to see if it's an issue with the Debian distributed package, using either `python3 runtests.py -v` or:
```
python3 -m virtualenv -p python3 ./scipy-dev
source ./scipy-dev/bin/activate
pip install Numpy Nose Cython Tempita
python setup.py install
```
But I get errors like this:
```
f2py: build/src.linux-x86_64-3.6/scipy/linalg/flapack.pyf
Reading fortran codes...
        Reading file 'build/src.linux-x86_64-3.6/scipy/linalg/flapack.pyf' (format:free)
Traceback (most recent call last):
  File "setup.py", line 416, in <module>
    setup_package()
...
  File "/home/eacousineau/devel/tmp/scipy/scipy-dev/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'intent(in))', 'intent(in))')
```

EDIT: Ah, 0.19.1 is ~2 years old. Yeah, not expecting that to work. I'll see if this is still an issue for `master`.

**Comment by EricCousineau-TRI** [comment]
Confirmed that I can reproduce this error on 0.19.1 on Ubuntu 18.04, but using `pip` rather than the package manager:
```
$ python3 -m virtualenv -p python3 .
$ source ./bin/activate
$ pip install scipy==0.19.1
$ python -c 'import warnings; warnings.simplefilter("error", Warning); import scipy'
# Same error as above.
```

However, this does not happen with the latest version:
```
$ pip install scipy==1.3.1
$ python -c 'import warnings; warnings.simplefilter("error", Warning); import scipy'
# No error
```

Gonna bisect briefly...

**Comment by EricCousineau-TRI** [comment]
The release of `0.19.1` is `1.0.0`, and the import warning goes away. So yeah, I'm just gonna close this.
