### ISSUE TITLE
spatial/tests/test_kdtree.py crash

### ISSUE THREAD

**Issue by frenzymadness** [scipy/scipy#11021]
I am building scipy 1.3.1 in Fedora rawhide with Python 3.8 and multiple tests from `spatial/tests/test_kdtree.py` crash.

#### Reproducing code example:
The simplest reproducer is from one of the tests:

```
from test_kdtree import *

# from test_onetree_query_compiled
np.random.seed(0)
n = 100
k = 4
points = np.random.randn(n,k)
T = cKDTree(points)

# from check_onetree_query
d = 0.1

T.query_pairs(d)
```

#### Error message:
```
$ python3 reproducer.py 
/usr/include/c++/9/bits/stl_vector.h:1120: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::front() [with _Tp = ordered_pair; _Alloc = std::allocator<ordered_pair>; std::vector<_Tp, _Alloc>::reference = ordered_pair&]: Assertion '__builtin_expect(!this->empty(), true)' failed.
Aborted (core dumped)
```

GDB output:
```
Thread 1 "python3-debug" received signal SIGABRT, Aborted.
0x00007ffff7e39625 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7e39625 in raise () from /lib64/libc.so.6
#1  0x00007ffff7e228d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff200f358 in std::__replacement_assert(char const*, int, char const*, char const*) ()
   from /usr/lib64/python3.8/site-packages/scipy/spatial/ckdtree.cpython-38-x86_64-linux-gnu.so
#3  0x00007ffff2004c1f in __pyx_pw_5scipy_7spatial_7ckdtree_13ordered_pairs_9set(_object*, _object*) ()
   from /usr/lib64/python3.8/site-packages/scipy/spatial/ckdtree.cpython-38-x86_64-linux-gnu.so
#4  0x00007ffff1fde7bf in __pyx_pw_5scipy_7spatial_7ckdtree_7cKDTree_13query_pairs(_object*, _object*, _object*) ()
   from /usr/lib64/python3.8/site-packages/scipy/spatial/ckdtree.cpython-38-x86_64-linux-gnu.so
#5  0x00007ffff7b6cd15 in method_vectorcall_VARARGS_KEYWORDS ()
   from /lib64/libpython3.8d.so.1.0
#6  0x00007ffff7c53a91 in _PyEval_EvalFrameDefault () from /lib64/libpython3.8d.so.1.0
#7  0x00007ffff7a986d8 in PyEval_EvalFrameEx () from /lib64/libpython3.8d.so.1.0
#8  0x00007ffff7bf3e32 in _PyEval_EvalCodeWithName () from /lib64/libpython3.8d.so.1.0
#9  0x00007ffff7bf3fb8 in PyEval_EvalCodeEx () from /lib64/libpython3.8d.so.1.0
#10 0x00007ffff7bf3fe6 in PyEval_EvalCode () from /lib64/libpython3.8d.so.1.0
#11 0x00007ffff7bf40de in run_eval_code_obj () from /lib64/libpython3.8d.so.1.0
#12 0x00007ffff7c8b283 in run_mod () from /lib64/libpython3.8d.so.1.0
#13 0x00007ffff7c8c11a in PyRun_FileExFlags () from /lib64/libpython3.8d.so.1.0
#14 0x00007ffff7c8e7b5 in PyRun_SimpleFileExFlags () from /lib64/libpython3.8d.so.1.0
#15 0x00007ffff7c8e9ba in PyRun_AnyFileExFlags () from /lib64/libpython3.8d.so.1.0
#16 0x00007ffff7c90828 in pymain_run_file () from /lib64/libpython3.8d.so.1.0
#17 0x00007ffff7c9115b in pymain_run_python () from /lib64/libpython3.8d.so.1.0
#18 0x00007ffff7c91ed8 in Py_RunMain () from /lib64/libpython3.8d.so.1.0
#19 0x00007ffff7c91f55 in pymain_main () from /lib64/libpython3.8d.so.1.0
#20 0x00007ffff7c92019 in Py_BytesMain () from /lib64/libpython3.8d.so.1.0
#21 0x0000555555555142 in main ()
```

#### Scipy/Numpy/Python version information:
Scipy: 1.3.1
Numpy: 1.17.3
Python: 3.8.0

**Comment by peterbell10** [comment]
Looks like the issue fixed in #10567. @pv can you confirm?
