### ISSUE TITLE
Regression in scipy.stats where distribution will not accept loc and scale parameters

### ISSUE THREAD

**Issue by glemaitre** [scipy/scipy#11089]
The scikit-learn CRON job started to fail 2 days ago due to the following change:
https://github.com/scipy/scipy/commit/8d5b840fbcd80a0c8b9cf3f041d6fee7954faff4#diff-15a69deb9bb3f587270cbce8186b4465R431

if the underlying `_get_support` does not have the parameter `loc` and `scale`, it will fail. Thus, several distributions.

#### Reproducing code example:

```python
>>> from scipy.stats import reciprocal
>>> reciprocal(a=0.00623, b=1.01)
>>> reciprocal(a=0.00623, b=1.01, loc=2, scale=3)
```

#### Error message:

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-5917b24eb1bb> in <module>
----> 1 reciprocal(a=0.00623, b=1.01, loc=2, scale=3)

~/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in __call__(self, *args, **kwds)
    769 
    770     def __call__(self, *args, **kwds):
--> 771         return self.freeze(*args, **kwds)
    772     __call__.__doc__ = freeze.__doc__
    773 

~/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in freeze(self, *args, **kwds)
    766 
    767         """
--> 768         return rv_frozen(self, *args, **kwds)
    769 
    770     def __call__(self, *args, **kwds):

~/miniconda3/envs/scipy-dev/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in __init__(self, dist, *args, **kwds)
    430         shapes, _, _ = self.dist._parse_args(*args, **kwds)
    431         self.dist._argcheck(*shapes)
--> 432         self.a, self.b = self.dist._get_support(*args, **kwds)
    433 
    434     @property

TypeError: _get_support() got an unexpected keyword argument 'loc'
```

#### Scipy/Numpy/Python version information:

```
Linux-4.15.0-65-generic-x86_64-with-debian-buster-sid
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
NumPy 1.17.3
SciPy 1.5.0.dev0+cf4a407
```

**Comment by tylerjereddy** [comment]
@pvanmulbregt @rlucas7 Can you confirm if there is a problem/bug here that would affect the 1.4.x release?

**Comment by glemaitre** [comment]
FYI the PR is included in 1.4.X: https://github.com/scipy/scipy/pull/10104

**Comment by ev-br** [comment]
Would be helpful if you could check if gh-11092 fixes it @glemaitre

**Comment by rlucas7** [comment]
> @pvanmulbregt @rlucas7 Can you confirm if there is a problem/bug here that would affect the 1.4.x release?

@tylerjereddy here is what I see on my box: 

```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.stats import reciprocal
>>> reciprocal(a=0.00623, b=1.01)
<scipy.stats._distn_infrastructure.rv_frozen object at 0x10753f9e8>
>>> reciprocal(a=0.00623, b=1.01, loc=2, scale=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 771, in __call__
    return self.freeze(*args, **kwds)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 768, in freeze
    return rv_frozen(self, *args, **kwds)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 432, in __init__
    self.a, self.b = self.dist._get_support(*args, **kwds)
TypeError: _get_support() got an unexpected keyword argument 'loc'
>>> 

(scipy-dev) Lucass-MacBook:scipy rlucas$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.stats import reciprocal
>>> reciprocal(a=0.00623, b=1.01)
<scipy.stats._distn_infrastructure.rv_frozen object at 0x10753f9e8>
>>> reciprocal(a=0.00623, b=1.01, loc=2, scale=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 771, in __call__
    return self.freeze(*args, **kwds)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 768, in freeze
    return rv_frozen(self, *args, **kwds)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 432, in __init__
    self.a, self.b = self.dist._get_support(*args, **kwds)
TypeError: _get_support() got an unexpected keyword argument 'loc'
>>> 
(scipy-dev) Lucass-MacBook:scipy rlucas$ vi  scipy/stats/_distn_infrastructure.py
(scipy-dev) Lucass-MacBook:scipy rlucas$ git status 
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   scipy/stats/_distn_infrastructure.py

no changes added to commit (use "git add" and/or "git commit -a")
(scipy-dev) Lucass-MacBook:scipy rlucas$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.stats import reciprocal
>>> reciprocal(a=0.00623, b=1.01)
<scipy.stats._distn_infrastructure.rv_frozen object at 0x1048f59e8>
>>> reciprocal(a=0.00623, b=1.01, loc=2, scale=3)
<scipy.stats._distn_infrastructure.rv_frozen object at 0x1048f5a20>
>>> 
(scipy-dev) Lucass-MacBook:scipy rlucas$ git add -p . 
diff --git a/scipy/stats/_distn_infrastructure.py b/scipy/stats/_distn_infrastructure.py
index 91e15adbd..b2e7de6ca 100644
--- a/scipy/stats/_distn_infrastructure.py
+++ b/scipy/stats/_distn_infrastructure.py
@@ -429,7 +429,7 @@ class rv_frozen(object):
 
         shapes, _, _ = self.dist._parse_args(*args, **kwds)
         self.dist._argcheck(*shapes)
-        self.a, self.b = self.dist._get_support(*args, **kwds)
+        self.a, self.b = self.dist._get_support(*shapes)
 
     @property
     def random_state(self):
Stage this hunk [y,n,q,a,d,e,?]? n

(scipy-dev) Lucass-MacBook:scipy rlucas$ 
```
which matches what @glemaitre is seeing. It looks to me like the PR from @ev-br fixes the issue, at least on my box anyway.

**Comment by glemaitre** [comment]
> Would be helpful if you could check if gh-11092 fixes it @glemaitre

It solves the issue. Thanks
