### ISSUE TITLE
DOC: building local documentation import fail

### ISSUE THREAD

**Issue by mkg33** [scipy/scipy#11179]
Disclaimer: I've spent a lot of time trying to resolve this problem but to no avail. I've tried some online solutions (e.g., [here](https://stackoverflow.com/questions/10324393/sphinx-build-fail-autodoc-cant-import-find-module?noredirect=1&lq=1)) but they don't work either, hence this question.

When trying to build the documentation (`git clone` the latest version), i.e., by doing:

```
cd scipy/doc
make clean
make html
```

I get the import fail (traceback excerpt, full output [here](https://gist.github.com/mkg33/9f1d03ce411edbed7256ccc7c470d0c3)):

```
make html
# for testing
# @echo installed scipy 2bea64c334 matches git version 2bea64c334; exit 1
mkdir -p build/html build/doctrees
LANG=C python3 -msphinx -b html -d build/doctrees   source build/html 
Running Sphinx v2.2.1
SciPy (VERSION 1.5.0.dev0+2bea64c)
[autosummary] generating autosummary for: api.rst, ccallback.rst, cluster.hierarchy.rst, cluster.rst, cluster.vq.rst, constants.rst, fft.rst, fftpack.rst, hacking.rst, index.rst, ..., sparse.linalg.rst, sparse.rst, spatial.distance.rst, spatial.rst, spatial.transform.rst, special.cython_special.rst, special.rst, stats.mstats.rst, stats.rst, toolchain.rst
Failed to import 'scipy.fftpack': no module named scipy.fftpack
Failed to import 'scipy.sparse.linalg': no module named scipy.sparse.linalg
Failed to import 'scipy.sparse': no module named scipy.sparse
Failed to import 'scipy.cluster.vq': no module named scipy.cluster.vq
Failed to import 'scipy.sparse.csgraph': no module named scipy.sparse.csgraph
Failed to import 'scipy.linalg.cython_lapack': no module named scipy.linalg.cython_lapack
Failed to import 'scipy.cluster': no module named scipy.cluster
Failed to import 'scipy.stats.mstats': no module named scipy.stats.mstats
Failed to import 'scipy.spatial.transform': no module named scipy.spatial.transform
Failed to import 'scipy.signal.windows': no module named scipy.signal.windows
Failed to import 'scipy.io': no module named scipy.io
Failed to import 'scipy.cluster.hierarchy': no module named scipy.cluster.hierarchy
Failed to import 'scipy.interpolate': no module named scipy.interpolate
Failed to import 'scipy.signal': no module named scipy.signal
Failed to import 'scipy.special.cython_special': no module named scipy.special.cython_special
Failed to import 'scipy.optimize.nonlin': no module named scipy.optimize.nonlin
Failed to import 'scipy.linalg.cython_blas': no module named scipy.linalg.cython_blas
Failed to import 'scipy.optimize.cython_optimize': no module named scipy.optimize.cython_optimize
Failed to import 'scipy.stats': no module named scipy.stats
Failed to import 'scipy.special': no module named scipy.special
Failed to import 'scipy.integrate': no module named scipy.integrate
Failed to import 'scipy.linalg.interpolative': no module named scipy.linalg.interpolative
Failed to import 'scipy.spatial.distance': no module named scipy.spatial.distance
Failed to import 'scipy.spatial': no module named scipy.spatial
Failed to import 'scipy.linalg': no module named scipy.linalg
Failed to import 'scipy.ndimage': no module named scipy.ndimage
Failed to import 'scipy.optimize': no module named scipy.optimize
```

I'm assuming it's something with the `sys.path` in the `conf.py` file. For the record, I have the latest version of `Sphinx`, I'm using `Python 3.7`, and the full list of Python packages is [here](https://gist.github.com/mkg33/7da5dcc4f5c4a54eca6043b219eed5f4). In case it's important, I always use `homebrew`.

I'd be really grateful for any help because I do need the local documentation for testing purposes.

**Comment by Kai-Striega** [comment]
I've just tried building the docs on the current master branch (``1.5.0.dev0+0a7b39a``) and didn't have  any issues. Are you able to build, install and use SciPy, without building the docs?

**Comment by mkg33** [comment]
@Kai-Striega Yes, I can install the current master branch version of SciPy (and use it) locally without any problems. Only the documentation fails.

**Comment by rgommers** [comment]
@mkg33 the problem seems to be that your doc build doesn't pick up the location where you built SciPy. If you built with `python runtests.py`, then build the docs with `python runtests.py --doc`. If you built with `python setup.py build_ext -i` (or similar), then you want to get that location on your pythonpath, e.g. with `export PYTHONPATH=~/path/to/repo/roo` and then `make html` in the doc dir.

**Comment by mkg33** [comment]
@rgommers , many thanks for the comments and the live troubleshooting advice :-) Here's [the outcome](https://gist.github.com/mkg33/7186c5f110155f3db695cd7a9a58983d) of `python3 runtests.py`. As you rightly suspected, it failed.

**Comment by rgommers** [comment]
> `scipy/linalg/tests/test_cython_blas.py ..Fatal Python error: Segmentation fault`

I'm ~80% sure that it's the compilers you used - the Gfortran from gcc.org is fishy. You can try to replace it with Homebrew Gfortran (should be 8.3.0 at the moment I think). This combination is compatible on macOS 10.13 (probably 10.14 too, but given the bad reviews that OS is getting, I refuse to upgrade):

```
TODO copy versions here
```

**Comment by rgommers** [comment]
If that doesn't work it may be the Python/Cython which isn't compatible. At that point I'd more suggest to install Miniconda and install everything from there, then you're definitely getting a compatible set of compilers.

**Comment by mkg33** [comment]
Thanks! I installed the hombrew gfortran and I'm getting another set of errors. I'll do as you suggest and reinstall everything from Miniconda.

**Comment by rgommers** [comment]
Hi @mkg33, did you manage to solve this issue?

**Comment by mkg33** [comment]
Apologies for the long silence but I have several exams coming up. So I did try to do as you suggested (Miniconda every required package from there) and I'm still getting the same error, see [here](https://gist.github.com/mkg33/400eb6912012a48421964d42796816f8).

**Comment by andyfaff** [comment]
I'm starting to run into this issue (macOS 10.15.3, conda Python). I can `runtests.py`, I can't run `make html`, but the doc seems to build with `runtests.py --doc`. However, the documentation is currently failing:
```
Building, see build.log...
Build OK (0:00:08.051058 elapsed)
mkdir -p build/html build/doctrees
LANG=C "/Users/andrew/miniconda3/envs/dev3/bin/python" -msphinx -WT --keep-going -t scipyorg -b html -d build/doctrees  "-j1" source build/html-scipyorg 
Running Sphinx v2.3.1
SciPy (VERSION 1.5.0.dev0+1ee0d72)
[autosummary] generating autosummary for: api.rst, ccallback.rst, cluster.hierarchy.rst, cluster.rst, cluster.vq.rst, constants.rst, fft.rst, fftpack.rst, hacking.rst, index.rst, ..., sparse.linalg.rst, sparse.rst, spatial.distance.rst, spatial.rst, spatial.transform.rst, special.cython_special.rst, special.rst, stats.mstats.rst, stats.rst, toolchain.rst
[autosummary] generating autosummary for: /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.average.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.centroid.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.complete.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.cophenet.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.correspond.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.cut_tree.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.dendrogram.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.fcluster.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.fclusterdata.rst, ..., /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.wishart.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.wrapcauchy.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.yeojohnson.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.yeojohnson_llf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.yeojohnson_normmax.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.yeojohnson_normplot.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.yulesimon.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.zipf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.zmap.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.zscore.rst
[autosummary] generating autosummary for: /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.get_count.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.get_id.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.get_left.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.get_right.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.is_leaf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.pre_order.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.integrate.BDF.TOO_SMALL_STEP.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.integrate.BDF.dense_output.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.integrate.BDF.step.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.integrate.BDF.step_size.rst, ..., /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.nnlf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.pdf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.ppf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.random_state.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.rvs.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.sf.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.stats.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.std.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.support.rst, /Users/andrew/Documents/Andy/programming/scipy/doc/source/generated/scipy.stats.rv_histogram.var.rst
loading intersphinx inventory from https://docs.python.org/dev/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://asv.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 959 source files that are out of date
updating environment: [new config] 3369 added, 0 changed, 0 removed
<string>:26: UserWarning: generated/scipy.interpolate.LSQSphereBivariateSpline                                                                                                                                                                                             
WARNING. The coefficients of the spline returned have been computed as the
         minimal norm least-squares solution of a (numerically) rank
         deficient system (deficiency=34, rank=42). Especially if the rank
         deficiency, which is computed by 6+(nt-8)*(np-7)+ier, is large,
         the results may be inaccurate. They could also seriously depend on
         the value of eps.
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/signal/windows/windows.py:1545: DeprecationWarning: slepian is deprecated and will be removed in a future version, use dpss instead                                         
  'version, use dpss instead', DeprecationWarning)
<string>:8: DeprecationWarning: `frechet_l` is deprecated!                                                                                                                                                                                                                 
The distribution `frechet_l` is a synonym for `weibull_max`; this historical
usage is deprecated because of possible confusion with the (quite different)
Frechet distribution.  To preserve the existing behavior of the program, use
`scipy.stats.weibull_max`.  For the Frechet distribution (i.e. the Type II
extreme value distribution), use `scipy.stats.invweibull`.
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:762: DeprecationWarning: `frechet_l` is deprecated!
The distribution `frechet_l` is a synonym for `weibull_max`; this historical
usage is deprecated because of possible confusion with the (quite different)
Frechet distribution.  To preserve the existing behavior of the program, use
`scipy.stats.weibull_max`.  For the Frechet distribution (i.e. the Type II
extreme value distribution), use `scipy.stats.invweibull`.
  return self.freeze(*args, **kwds)
<string>:8: DeprecationWarning: `frechet_r` is deprecated!                                                                                                                                                                                                                 
The distribution `frechet_r` is a synonym for `weibull_min`; this historical
usage is deprecated because of possible confusion with the (quite different)
Frechet distribution.  To preserve the existing behavior of the program, use
`scipy.stats.weibull_min`.  For the Frechet distribution (i.e. the Type II
extreme value distribution), use `scipy.stats.invweibull`.
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:762: DeprecationWarning: `frechet_r` is deprecated!
The distribution `frechet_r` is a synonym for `weibull_min`; this historical
usage is deprecated because of possible confusion with the (quite different)
Frechet distribution.  To preserve the existing behavior of the program, use
`scipy.stats.weibull_min`.  For the Frechet distribution (i.e. the Type II
extreme value distribution), use `scipy.stats.invweibull`.
  return self.freeze(*args, **kwds)
reading sources... [100%] tutorial/stats/discrete_zipf                                                                                                                                                                                                                     
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr.rst:10: WARNING: autosummary: stub file not found 'scipy.odr.odr'. Check your autosummary_generate setting.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorial/stats/discrete_zipf                                                                                                                                                                                                                      
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/odrpack.py:docstring of scipy.odr.Model:61: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/odrpack.py:docstring of scipy.odr.OdrError:4: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/odrpack.py:docstring of scipy.odr.OdrStop:4: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/odrpack.py:docstring of scipy.odr.Output:16: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/odrpack.py:docstring of scipy.odr.Output:16: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr:23:<autosummary>:1: WARNING: py:obj reference target not found: scipy.odr.odr
/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr:68: WARNING: py:obj reference target not found: odr
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying images... [100%] tutorial/../../build/plot_directive/tutorial/stats/plots/mgc_plot4.png                                                                                                                                                                            
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 8 warnings.
make: *** [html-scipyorg] Error 1
Traceback (most recent call last):
  File "runtests.py", line 497, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 202, in main
    subprocess.run(cmd, check=True)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['make', '-Cdoc', 'PYTHON="/Users/andrew/miniconda3/envs/dev3/bin/python"', 'html-scipyorg', 'SPHINXOPTS="-j1"']' returned non-zero exit status 2.

```

**Comment by sethtroisi** [comment]
I also run into this.

I did this to fix it, not sure what part of it was necessary. 

```
# Delete temp state
git clean -Xdf
pip uninstall -y scipy
make -C doc clean

python runtests.py --build-only -j3 --doc
pip install .
```
