### ISSUE TITLE
scipy.spatial import error

### ISSUE THREAD

**Issue by epennington** [scipy/scipy#11206]
I would like to use the scipy.spatial.KDTree class, but when I attempt "from scipy import spatial", I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackupp13/epenning/anaconda3/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 99, in <module>
    from .kdtree import *
  File "/nobackupp13/epenning/anaconda3/lib/python3.7/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/nobackupp13/epenning/anaconda3/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/nobackupp13/epenning/anaconda3/lib/python3.7/site-packages/scipy/sparse/base.py", line 7, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/nobackupp13/epenning/anaconda3/lib/python3.7/site-packages/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns
AttributeError: module 'numpy' has no attribute 'testing'

This was working yesterday (Dec. 10, 2019), but failed today. I'm using Python 3.7.4 distributed through Anaconda3. I didn't manually update anything, and I'm not sure if something updated automatically.

**Comment by WarrenWeckesser** [comment]
Did you create a file called `numpy.py` in your working directory?

**Comment by epennington** [comment]
I did not intentionally do so. I just tried importing again and it is working now; I apologize for the inconvenience.
