### ISSUE TITLE
Can't install scipy from pip3 or python3 setup.py install in Raspbian

### ISSUE THREAD

**Issue by RationalBH** [scipy/scipy#11271]
**It seem like can‘t get pip from pip3??**

```
python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.18.0'
 pi @ raspberrypi in ~/scipy-1.4.1 [10:47:48]
$ sudo python3 setup.py install
Alias tip: _ python3 setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbvfvqcwq', '--quiet', 'pybind11>=2.4.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 540, in <module>
    setup_package()
  File "setup.py", line 536, in setup_package
    setup(**metadata)
  File "/usr/local/lib/python3.7/dist-packages/numpy-1.18.0-py3.7-linux-armv7l.egg/numpy/distutils/core.py", line 128, in setup
    dist = setup(**new_attr)
  File "/usr/local/lib/python3.7/dist-packages/numpy-1.18.0-py3.7-linux-armv7l.egg/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbvfvqcwq', '--quiet', 'pybind11>=2.4.0']' returned non-zero exit status 1.
```

```
pi @ raspberrypi in ~/scipy-1.4.1 [10:47:59] C:1
$ sudo pip3 install scipy
Alias tip: _ pip3 install scipy
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ol_votqy --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython>=0.29.13 "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'" pybind11>=2.4.0:
  /usr/bin/python3: No module named pip

  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ol_votqy --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython>=0.29.13 "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'" "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'" "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'" "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'" pybind11>=2.4.0" failed with error code 1 in None
Time: 0h:00m:24s
```

**but pip install scipy work**

**Comment by RationalBH** [comment]
sudo apt install python3-scipy
try this,it works

**Comment by rgommers** [comment]
Hi @RationalBH, it's not clear to me what your problem is. You seem to have solved it though. A few comments:

- never use `sudo` to build
- `pip` vs `pip3` is just a naming thing, depends on what's default. the best way to build is with `python -m pip`, a little more verbose but it always uses the `pip` connected to the Python version you're trying to install for.

Your issue seems unrelated to SciPy, so I'll close this bug report. Please feel free to rephrase your question and we'll continue the discussion.
