### ISSUE TITLE
unable to import scipy 1.4.1 on python 3.5.1

### ISSUE THREAD

**Issue by pythoneerd** [scipy/scipy#11356]
Import of scipy fails with an import error:

'>>> import scipy
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import scipy
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\user\pyvenvs\lmfit-test\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

This is (probably) caused by changes in the typing module in the early Python 3.5 development - some relevant parts were added after 3.5.1
I saw that on master, declared compatibility is >= Python 3.6
But on tag 1.4.1, it states >= 3.5, so it should still be working.
From another issue, i think i understood uarray is a vendored dependency.

**Comment by peterbell10** [comment]
Happily, this has already been fixed by gh-11300. Confirmed by cherry-picking onto the 1.4.x maintenance branch:
```
Python 3.5.1 | packaged by conda-forge | (default, Jun 29 2016, 12:18:14) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import scipy; print(scipy.__version__)
1.4.1
```
