### ISSUE TITLE
Unable to find _fblas module

### ISSUE THREAD

**Issue by mickaelandrieu** [scipy/scipy#11430]
My issue is about loading simple Python script using Scipy on Windows 10, Python 3.7.6.

I'm not a Python expert, but I don't get what I'm missing here :/

#### Reproducing code example:

```
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots()
ax.axis("equal")
ax.pie([24, 18],
        labels = ["Femmes", "Hommes"],
        autopct="%1.1f pourcents")
plt.title("Un superbe graphique")
plt.show()
```

#### Error message:

```
PS C:\Users\micka\Projects\learn-python\best_practices> python .\test.py
Traceback (most recent call last):
  File ".\test.py", line 2, in <module>
    import seaborn as sns
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\seaborn\__init__.py", line 6, in <module>
    from .rcmod import *
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\seaborn\rcmod.py", line 6, in <module>
    from . import palettes, _orig_rc_params
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\seaborn\palettes.py", line 10, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\seaborn\utils.py", line 7, in <module>
    from scipy import stats
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\stats\__init__.py", line 384, in <module>
    from .stats import *
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\stats\stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\micka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: Le module spécifié est introuvable.
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Seems like your scipy installation is corrupted.

**Comment by mickaelandrieu** [comment]
Hi @cirosantilli 

how can I check if Scipy installation is corrupted ?

Thanks for your help

**Comment by cirosantilli** [comment]
@mickaelandrieu I'm not sure, it has just worked for me with pip on latest Ubuntus, I would just start nuking stuff and reinstalling until it works :-)
