### ISSUE TITLE
Configuration error in runtests.py --doc

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#11480]
I'm trying to build docs for a PR I'm working on, 
I haven't done that from the test harness (runtest.py) before and I didn't have sphinx in my virtual env. When I ran the runtests.py file I got a message that I need to install sphinx. I did that and reran runtests.py with --doc option, that gave me a prompt to install some submodule. I did that and now the submodule setup just hangs, is this dead code or an error that needs to be fixed? 

I'm on a branched off master on January 16th, 2019 so I don't think any relevant changes since then but let me know if I missed something.

Full traceback:
```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python runtests.py --doc
Building, see build.log...
Build OK (0:00:08.553786 elapsed)
mkdir -p build/html build/doctrees
LANG=C "/Users/rlucas/anaconda3/envs/scipy-dev/bin/python" -msphinx -WT --keep-going -t scipyorg -b html -d build/doctrees  "-j1" source build/html-scipyorg 
Running Sphinx v2.3.1
SciPy (VERSION 1.5.0.dev0+45e8ee6)

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/application.py", line 217, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 197, in read
    namespace = eval_config_file(filename, tags)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 378, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update

make: *** [html-scipyorg] Error 2
Traceback (most recent call last):
  File "runtests.py", line 497, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 202, in main
    subprocess.run(cmd, check=True)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['make', '-Cdoc', 'PYTHON="/Users/rlucas/anaconda3/envs/scipy-dev/bin/python"', 'html-scipyorg', 'SPHINXOPTS="-j1"']' returned non-zero exit 
(scipy-dev) Lucass-MacBook:scipy rlucas$ git submodule init & update
[2] 3747
-bash: update: command not found
(scipy-dev) Lucass-MacBook:scipy rlucas$ Submodule 'doc/scipy-sphinx-theme' (https://github.com/scipy/scipy-sphinx-theme.git) registered for path 'doc/scipy-sphinx-theme'
Submodule 'doc/source/_static/scipy-mathjax' (https://github.com/scipy/scipy-mathjax.git) registered for path 'doc/source/_static/scipy-mathjax'
Submodule 'doc/sphinxext' (https://github.com/numpy/numpydoc.git) registered for path 'doc/sphinxext'
```
 
EDIT it looks like I need to install a sphinx theme from somewhere but the error message doesn't state where. An informative error meesage would provide the repo url. 
Does anyone know where is the necessary sphinx repo?

#### Scipy/Numpy/Python version information:
```
1.5.0.dev0+45e8ee6 1.16.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by EverLookNeverSee** [comment]
I got this error:

![Screenshot_20200207_115614](https://user-images.githubusercontent.com/57490926/74013000-c102c280-49a0-11ea-875d-47ceedc2a133.png)

**Comment by ilayn** [comment]
Did you do this `git submodule init & update` to get the sphinx theme?

**Comment by rlucas7** [comment]
@ilayn when I tried that I initially my system hung for about 5 minutes, I'm not sure if the remote helper is grabbing the correct commit or something else. When I ran again this morning I get:
```
(scipy-dev) Lucass-MacBook:scipy rlucas$ git submodule init & update
[2] 4320
-bash: update: command not found
```
if I run just the `git submodule init` there isn't any output to stdout to indicate success or failure so not sure if working correctly. However, if I retry the test harness with `--doc` flag I get  the process error  seen by @EverLookNeverSee 

```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python runtests.py --doc
Building, see build.log...
Build OK (0:00:05.029780 elapsed)
mkdir -p build/html build/doctrees
LANG=C "/Users/rlucas/anaconda3/envs/scipy-dev/bin/python" -msphinx -WT --keep-going -t scipyorg -b html -d build/doctrees  "-j1" source build/html-scipyorg 
Running Sphinx v2.3.1
SciPy (VERSION 1.5.0.dev0+45e8ee6)

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/application.py", line 217, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 197, in read
    namespace = eval_config_file(filename, tags)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 378, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/rlucas/scipy-dev/scipy/doc/source/conf.py", line 188, in <module>
    raise RuntimeError("Get the scipy-sphinx-theme first, "
RuntimeError: Get the scipy-sphinx-theme first, via git submodule init & update

make: *** [html-scipyorg] Error 2
Traceback (most recent call last):
  File "runtests.py", line 497, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 202, in main
    subprocess.run(cmd, check=True)
  File "/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['make', '-Cdoc', 'PYTHON="/Users/rlucas/anaconda3/envs/scipy-dev/bin/python"', 'html-scipyorg', 'SPHINXOPTS="-j1"']' returned non-zero exit 
[2]-  Done                    git submodule init
```

Also, shouldn't there be 2 ampersands? e.g. `git submodule init && update`? Either way when I do that the

**Comment by rlucas7** [comment]
Actually what I was really trying to do is run the doctests, I see now that there is a flag for that in test runner but appears in unsupported:
```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python runtests.py --doctests
Building, see build.log...
Build OK (0:00:04.520745 elapsed)
Traceback (most recent call last):
  File "runtests.py", line 497, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 308, in main
    parallel=args.parallel)
  File "/Users/rlucas/scipy-dev/scipy/build/testenv/lib/python3.6/site-packages/scipy/_lib/_testutils.py", line 39, in __call__
    raise ValueError("Doctests not supported")
ValueError: Doctests not supported
(scipy-dev) Lucass-MacBook:scipy rlucas$ 
```
I'd like to be able to both build the docs from the test runner and execute the doctests. I tried directly running doctests via `python scipy/stats/stats.py` but the imports don't work because of relative import paths and no easy way around that that I can see.

For now, I can push once I have the PR code working as I expect. I can push to CI and use that as the doc builder and doctest runner but would prefer to conserve the resources. I'm not super familiar with the test runner logic, if the issues are still unresolved after that one is in a good state I can take a look but might be awhile.

**Comment by peterbell10** [comment]
I think you can call `tools/refguide_check.py` directly.

**Comment by rlucas7** [comment]
@peterbell10 yes that works for doctests, thanks! 

e.g. 
```
 python tools/refguide_check.py --doctests stats
```

gives me the failing doctest for `median_absolute_deviation`

**Comment by ilayn** [comment]
Sorry completely my mistake.. I meant two separate commands; either 

```bash
git submodule init
git submpdule update
```

or 

```bash
git submodule update --init
```

**Comment by rlucas7** [comment]
@ilayn 

I had to resetup dev end after some changes to my machine. After I got everything running this evening it looks like running:
```
git submodule update --init
``` 
on master branch sets up correctly. The docs are currently building and everything looks ok-thanks! 

Now, given that doctests are supported but not directly in the test runner, should the value error message change? e.g. should I open a PR that changes 
```
raise ValueError("Doctests not supported")
```

at line 308 of `runtests.py` to something like

```
raise ValueError("to run doctests please use: python tools/refguide_check.py --doctests")
```
or should the doctests call be delegated directly in `runtests.py`? 
Not sure if the latter is possible or what would be the preferred way to achieve that with current setup.

**Comment by ev-br** [comment]
`$ python runtests.py -s optimize --refguide-check` should work, does it not?

**Comment by rlucas7** [comment]
@ev-br yes that also works. I'm unclear what is the difference between 
`python tools/refguide_check.py --doctests stats`
and 
`python runtests.py -s stats --refguide-check`

if looks like the latter calls the former to execute doctests, is that correct?

**Comment by ev-br** [comment]
Not sure.
While I never used `runtests.py --doctest`, the only use of `args.doctests`,
https://github.com/scipy/scipy/blob/master/runtests.py#L304
seems to imply that `runtests.py --doctest` runs all tests + doctests (using the standard doctest checker). `--refguide-check` OTOH only runs the doctests and uses a modified checker.

**Comment by rlucas7** [comment]
Thanks for helping @ev-br @ilayn @peterbell10 issue was fixed so closing.
