### ISSUE TITLE
Johnson SU distribution issues with array parameters

### ISSUE THREAD

**Issue by 0x0badc0de** [scipy/scipy#11556]
Johnson SU distribution works just fine when all parameters are scalars. But some array combinations result in exceptions

#### Reproducing code example:

```
>>> from scipy import stats as sp_stats
>>> distr = sp_stats.johnsonsu([2, 2], 2, [2, 2], [2, 2])
>>> distr.mean()
array([-0.66335483, -0.66335483])
>>> distr.std()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 486, in std
    return self.dist.std(*self.args, **self.kwds)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1294, in std
    res = sqrt(self.stats(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1064, in stats
    if np.isinf(mu):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> distr = sp_stats.johnsonsu([2, 2], [2, 2], [2, 2], [2, 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 771, in __call__
    return self.freeze(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 768, in freeze
    return rv_frozen(self, *args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 431, in __init__
    self.dist._argcheck(*shapes)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 4012, in _argcheck
    return (b > 0) & (a == a)
TypeError: '>' not supported between instances of 'list' and 'int'
>>> distr.mean()
array([-0.66335483, -0.66335483])
>>> distr.std()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 486, in std
    return self.dist.std(*self.args, **self.kwds)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1294, in std
    res = sqrt(self.stats(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1064, in stats
    if np.isinf(mu):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> distr = sp_stats.johnsonsu(np.array([2, 2]), np.array([2, 2]), np.array([2, 2]), np.array([2, 2]))
>>> distr.mean()
array([-0.66335483, -0.66335483])
>>> distr.std()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 486, in std
    return self.dist.std(*self.args, **self.kwds)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1294, in std
    res = sqrt(self.stats(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1064, in stats
    if np.isinf(mu):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Looks like we need to add some calls to `asarray()` in a few places, to convert list inputs to numpy arrays.

**Comment by mdhaber** [comment]
I just tested this and it looks like the particular issue reported has been resolved, e.g.
```
> from scipy import stats as sp_stats
> distr = sp_stats.johnsonsu([2, 2], 2, [2, 2], [2, 2])
> distr.std()
Out[19]: array([1.81993549, 1.81993549])
```
@0x0badc0de or @WarrenWeckesser I'm closing, but if this should stay open for another reason, please reopen.
