### ISSUE TITLE
SciPy trunk compiled for Python3.9 does not work

### ISSUE THREAD

**Issue by Marco-Sulla** [scipy/scipy#11568]
```python
(venv_********_3_9) [2020-02-21 12:09:02 ~ $] python
Python 3.9.0a3+ (heads/master-dirty:f2ee21d858, Feb 19 2020, 23:19:22) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/_lib/uarray.py", line 28, in <module>
    from ._uarray import *
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/_lib/_uarray/__init__.py", line 115, in <module>
    from ._backend import *
  File "/home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/_lib/_uarray/_backend.py", line 4, in <module>
    from . import _uarray  # type: ignore
ImportError: /home/marco/Desktop/********/venv_********_3_9/lib/python3.9/site-packages/scipy/_lib/_uarray/_uarray.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTISt9bad_alloc
```

**Comment by peterbell10** [comment]
It looks like you aren't linking in the C++ runtime. How are you compiling SciPy and are you able to compile for other python versions in the same way?

**Comment by Marco-Sulla** [comment]
Yes, with Python 3.8 I can `pip install scipy` without problems

**Comment by ilayn** [comment]
Also we are not supporting nonrelease versions of python.

**Comment by rgommers** [comment]
Python 3.9 works fine now, closing.
