### ISSUE TITLE
Installing scipy: Preparing wheel metadata ... -error

### ISSUE THREAD

**Issue by jfranco202** [scipy/scipy#11561]
```bash
Python 3.7.1 (default, Dec 20 2019, 18:32:49) 
[Clang 11.0.0 (clang-1100.0.33.16)]

pip install --no-build-isolation wfdb scipy

Collecting wfdb
  Using cached wfdb-2.2.1.tar.gz (94 kB)
Collecting scipy
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
    Preparing wheel metadata ... -error

ERROR: Command errored out with exit status 1:
     command: /var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/bin/python3 /var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /private/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/tmp/tmppct6olfy
         cwd: /private/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/tmp/pip-install-1cr7lj7q/scipy
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 101, in prepare_metadata_for_build_wheel
        backend = _build_backend()
      File "/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 60, in _build_backend
        ep = os.environ['PEP517_BUILD_BACKEND']
      File "/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/os.py", line 680, in __getitem__
        raise KeyError(key) from None
    KeyError: 'PEP517_BUILD_BACKEND'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/bin/python3 /var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /private/var/mobile/Containers/Data/Application/650AC656-F238-4658-B7A4-1644B6535B6E/tmp/tmppct6olfy Check the logs for full command output.
```

**Comment by i0nsec** [comment]
Have you managed to resolve the issue?

**Comment by shierote** [comment]
I have the same issue. (Mac OS, Big Sur, python 3.7.9, pyenv)

**Comment by Dmisawa** [comment]
To solve this problem...
- brew install lapack
- brew install openblas
- use pip=20.3.3

**Comment by rgommers** [comment]
This is a matter of missing dependencies when trying to install from source on some platform we don't have wheels for. There's nothing to fix here, so I'll close this.
