### ISSUE TITLE
Array shape mismatch in scipy.optimize

### ISSUE THREAD

**Issue by positr0nium** [scipy/scipy#11886]
Shape mismatch of some np.matrix class
The issue can be solved easily by inserting
f0 = np.array(f0)[0]
below the line
f0 = fun.f
in _constraints.py

#### Reproducing code example:

```
def opt(x):
    return x[0]**2+x[1]**2

import scipy.optimize
A = np.matrix(np.diag([1,1]))
lin_cons = scipy.optimize.LinearConstraint(A, -1, np.inf)
    
params = scipy.optimize.minimize(opt, 2*[1], constraints = lin_cons)
```

#### Error message:

```

  File "C:\Users\Rapha\Desktop\Sigma\scratchbook.py", line 18, in <module>
    params = scipy.optimize.minimize(opt, 2*[1], constraints = lin_cons)

  File "c:\users\rapha\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py", line 595, in minimize
    constraints = standardize_constraints(constraints, x0, meth)

  File "c:\users\rapha\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_minimize.py", line 825, in standardize_constraints
    old_constraints = new_constraint_to_old(con, x0)

  File "c:\users\rapha\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_constraints.py", line 355, in new_constraint_to_old
    pcon = PreparedConstraint(con, x0)

  File "c:\users\rapha\appdata\local\programs\python\python37\lib\site-packages\scipy\optimize\_constraints.py", line 247, in __init__
    if np.any(f0[mask] < lb[mask]) or np.any(f0[mask] > ub[mask]):

  File "c:\users\rapha\appdata\local\programs\python\python37\lib\site-packages\numpy\matrixlib\defmatrix.py", line 195, in __getitem__
    out = N.ndarray.__getitem__(self, index)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 2  ...
```

**Comment by andyfaff** [comment]
The issue here is that `A` is a `np.matrix`, your example works ok if `A` is simply an array, `np.diag([1, 1])`. The use of `np.matrix` is [no longer recommended](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html#numpy.matrix).

With your example `f0` is a `(1, 2)` matrix (this calculation is done in [LinearVectorFunction](https://github.com/scipy/scipy/blob/master/scipy/optimize/_differentiable_functions.py#L487). This is something akin to:
```
>>> A = np.matrix(np.diag([1,1]))
>>> B = np.diag([1, 1])
>>> A.dot([1, 1.]), B.dot([1, 1.])
(matrix([[1., 1.]]), array([1., 1.]))
```
The trouble is that the matrix is not subscriptable by booleans:
```
>>> dp = A.dot([1, 1.])
>>> dp
matrix([[1., 1.]])
>>> idx = np.array([False, False])
>>> dp[idx]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-180-4876f18bf5d6> in <module>
----> 1 dp[idx]

~/miniconda3/envs/dev38/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py in __getitem__(self, index)
    193 
    194         try:
--> 195             out = N.ndarray.__getitem__(self, index)
    196         finally:
    197             self._getitem = False

IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 2
```

A decision needs to be made as to where to go from here, using one of the following:

1. because `matrix` shouldn't be used for new code, we're not going to make any changes.
2. in `_differentiable_functions` test if `A` is a `matrix`, and if it is convert it to an `ndarray`.

**Comment by andyfaff** [comment]
Any change made would be made to `LinearVectorFunction`:

```
# use of extra np.array call is in case A is a matrix
self.J = np.atleast_2d(np.array(A, copy=False)))
```

**Comment by andyfaff** [comment]
@mdhaber, any thoughts?

**Comment by mdhaber** [comment]
I agree that this doesn't _have_ to be patched, but if it's a straightforward fix like you suggested `self.J = np.atleast_2d...` then I would be happy to review and merge.
