### ISSUE TITLE
Problem in running scipy.spatial.distance

### ISSUE THREAD

**Issue by ramendrasingla** [scipy/scipy#11901]
python .\base_code.py
Traceback (most recent call last):
  File ".\base_code.py", line 5, in <module>
    from scipy.spatial.distance import cosine
  File "C:\Users\RAMENDRA_SINGLA\anaconda3\lib\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "C:\Users\RAMENDRA_SINGLA\anaconda3\lib\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:\Users\RAMENDRA_SINGLA\anaconda3\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\RAMENDRA_SINGLA\anaconda3\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\RAMENDRA_SINGLA\anaconda3\lib\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The network name cannot be found.

Running on Python 3.8.2(Tried with the previous versionas well) on Windows 7

**Comment by tylerjereddy** [comment]
The traceback makes this look the same as #11826, but I'm a little concerned that this is being reported for `Python 3.8.2` instead of the `3.7.x` series, since my impression was that `3.8.x` should be working okay with our `_distributor_init.py` file.

**Comment by tylerjereddy** [comment]
How did you install SciPy? It is directly from Anaconda or from a `pip install` command?

**Comment by tylerjereddy** [comment]
And which version of SciPy? `scipy.__version__`?

**Comment by mdhaber** [comment]
No followup for several years, and this seems to be related to installation, so seems safe to close.
