### ISSUE TITLE
MAINT, CI: new Cython 3.0a4 issue

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#12037]
Observed in the Travis CI of #12036 with bleeding edge Cython the cause based on my local reproducer. Locally, I did `python -m pip install --pre cython==3.0a4` then build SciPy and observe something similar to CI:

```
Processing scipy/ndimage/src/_cytest.pyx
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/optimize/_bglu_dense.pyx

Error compiling Cython file:
------------------------------------------------------------
...

        with nogil:
            while PyArray_ITER_NOTDONE(iti):
                # Optimization - for 2D, line_buffer becomes next iteration's
                # neighbor buffer
                if output.ndim == 2:
                        ^
------------------------------------------------------------

_ni_label.pyx:313:25: Calling gil-requiring function not allowed without gil
Processing scipy/optimize/_group_columns.pyx
Traceback (most recent call last):
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 305, in <module>
    main()
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 301, in main
    find_process_files(root_dir)
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 290, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/mnt/c/Users/treddy/github_projects/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-6.5.0/python-3.7.4-65ohvllfnv7y2kaul5mcz3hg7cppcbby/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/mnt/c/Users/treddy/github_projects/spack/opt/spack/linux-ubuntu16.04-broadwell/gcc-6.5.0/python-3.7.4-65ohvllfnv7y2kaul5mcz3hg7cppcbby/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 290, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 229, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/mnt/c/Users/treddy/github_projects/scipy/tools/cythonize.py", line 94, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
```

**Comment by tylerjereddy** [comment]
There's another one here too, and possibly a few more in the code base:

```
Error compiling Cython file:
------------------------------------------------------------
...
                if facet.coplanarset:
                    for i in range(qh_setsize(self._qh, facet.coplanarset)):
                        point = <pointT*>facet.coplanarset.e[i].p
                        vertex = qh_nearvertex(self._qh, facet, point, &dist)

                        if ncoplanar >= coplanar.shape[0]:
                                               ^
------------------------------------------------------------

qhull.pyx:654:48: Calling gil-requiring function not allowed without gil
```

**Comment by tylerjereddy** [comment]
Yep, those two Travis CI entries are using `cython==3.0a4` as well. Anyway, at least the local reproducer is pretty fast/at start of build process.

**Comment by tylerjereddy** [comment]
I'm not planning to work on this this evening, so someone else should feel free of course.

**Comment by rgommers** [comment]
Cc @mattip here as well, since he probably can point out the right fix easily
