### ISSUE TITLE
Undefined reference to _main from qhull module

### ISSUE THREAD

**Issue by mathstuf** [scipy/scipy#12054]
My issue is about a custom build of SciPy from source tarballs having weird missing symbols in the qhull module on macOS.

I've looked at the code and can't see where `_main` is being requested. I suspect something is up with the Pyrex/Cython code in some way, but am not well-versed enough in that stuff to know for sure.

#### Error message:
```
>>> from scipy.spatial import Delaunay
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/ParaView-5.7.0.app/Contents/Python/scipy/spatial/__init__.py", line 100, in <module>
    from .qhull import *
ImportError: dlopen(/Applications/ParaView-5.7.0.app/Contents/Python/scipy/spatial/qhull.so, 2): Symbol not found: _main
  Referenced from: /Applications/ParaView-5.7.0.app/Contents/Python/scipy/spatial/qhull.so
  Expected in: flat namespace
 in /Applications/ParaView-5.7.0.app/Contents/Python/scipy/spatial/qhull.so
```

#### Scipy/Numpy/Python version information:
Python 3.7, NumPy 1.16.4, SciPy 1.2.2 (reproduced with 1.2.3 as well).

**Comment by andyfaff** [comment]
I suspect it's probably the way the ParaView app bundles scipy, and you should approach them for help in the first instance.
I've just installed scipy 1.2.3 into a Python3.7 environment with numpy and that import works in an interpreter.

One thing you could try is using the `nm` command on the shared library:

```
(dev3) P0014M:spatial anz$nm -gu qhull.cpython-37m-darwin.so
 _PyBaseObject_Type
_PyBuffer_Release
_PyBytes_FromString
_PyBytes_FromStringAndSize
_PyBytes_Type
_PyCFunction_NewEx
_PyCFunction_Type
_PyCapsule_New
_PyCode_New
_PyDict_DelItem
_PyDict_GetItemString
_PyDict_New
_PyDict_Next
_PyDict_SetItem
_PyDict_SetItemString
_PyDict_Size
_PyDict_Type
_PyErr_Clear
_PyErr_ExceptionMatches
_PyErr_Fetch
_PyErr_Format
_PyErr_GivenExceptionMatches
_PyErr_NoMemory
_PyErr_NormalizeException
_PyErr_Occurred
_PyErr_PrintEx
_PyErr_Restore
_PyErr_SetNone
_PyErr_SetObject
_PyErr_SetString
_PyErr_WarnEx
_PyErr_WarnFormat
_PyErr_WriteUnraisable
_PyEval_EvalCodeEx
_PyEval_EvalFrameEx
_PyEval_RestoreThread
_PyEval_SaveThread
_PyExc_AssertionError
_PyExc_AttributeError
_PyExc_BufferError
_PyExc_DeprecationWarning
_PyExc_Exception
_PyExc_ImportError
_PyExc_IndexError
_PyExc_KeyError
_PyExc_NameError
_PyExc_NotImplementedError
_PyExc_OverflowError
_PyExc_RuntimeError
_PyExc_StopIteration
_PyExc_SystemError
_PyExc_TypeError
_PyExc_UnboundLocalError
_PyExc_ValueError
_PyExc_ZeroDivisionError
_PyException_SetTraceback
_PyFloat_AsDouble
_PyFloat_FromDouble
_PyFloat_Type
_PyFrame_New
_PyFrame_Type
_PyFrozenSet_New
_PyFrozenSet_Type
_PyFunction_Type
_PyGILState_Ensure
_PyGILState_Release
_PyImport_AddModule
_PyImport_GetModuleDict
_PyImport_ImportModule
_PyImport_ImportModuleLevelObject
_PyInterpreterState_GetID
_PyList_Append
_PyList_AsTuple
_PyList_New
_PyList_Type
_PyLong_AsLong
_PyLong_AsSsize_t
_PyLong_FromLong
_PyLong_FromSize_t
_PyLong_FromSsize_t
_PyLong_Type
_PyMem_Free
_PyMem_Malloc
_PyMem_Realloc
_PyMethodDescr_Type
_PyMethod_New
_PyMethod_Type
_PyModuleDef_Init
_PyModule_AddObject
_PyModule_GetDict
_PyModule_NewObject
_PyNumber_Add
_PyNumber_InPlaceAdd
_PyNumber_InPlaceMultiply
_PyNumber_Index
_PyNumber_Multiply
_PyNumber_Negative
_PyNumber_Power
_PyNumber_Remainder
_PyNumber_Subtract
_PyNumber_TrueDivide
_PyOS_snprintf
_PyObject_Call
_PyObject_CallFinalizerFromDealloc
_PyObject_ClearWeakRefs
_PyObject_Free
_PyObject_GC_Del
_PyObject_GC_Track
_PyObject_GC_UnTrack
_PyObject_GenericGetAttr
_PyObject_GetAttr
_PyObject_GetAttrString
_PyObject_GetBuffer
_PyObject_GetItem
_PyObject_GetIter
_PyObject_Hash
_PyObject_IsTrue
_PyObject_Malloc
_PyObject_Not
_PyObject_RichCompare
_PyObject_RichCompareBool
_PyObject_SetAttr
_PyObject_SetAttrString
_PyObject_SetItem
_PyObject_Size
_PySequence_Contains
_PySequence_Tuple
_PySet_Add
_PySet_Contains
_PySet_Discard
_PySet_New
_PySet_Size
_PySet_Type
_PySlice_New
_PySlice_Type
_PyThreadState_Get
_PyThread_allocate_lock
_PyThread_free_lock
_PyTraceBack_Here
_PyTuple_GetItem
_PyTuple_GetSlice
_PyTuple_New
_PyTuple_Pack
_PyTuple_Type
_PyType_IsSubtype
_PyType_Modified
_PyType_Ready
_PyType_Type
_PyUnicode_AsUnicode
_PyUnicode_Compare
_PyUnicode_Decode
_PyUnicode_DecodeASCII
_PyUnicode_Format
_PyUnicode_FromFormat
_PyUnicode_FromString
_PyUnicode_FromStringAndSize
_PyUnicode_FromUnicode
_PyUnicode_InternFromString
_PyUnicode_Type
_Py_FatalError
_Py_GetVersion
_Py_OptimizeFlag
__DefaultRuneLocale
__PyBytes_Join
__PyDict_GetItem_KnownHash
__PyDict_SetItem_KnownHash
__PyList_Extend
__PyObject_GC_New
__PyObject_GetDictPtr
__PySet_NextEntry
__PyThreadState_UncheckedGet
__PyType_Lookup
__PyUnicode_Ready
__Py_CheckRecursionLimit
__Py_CheckRecursiveCall
__Py_EllipsisObject
__Py_FalseStruct
__Py_NoneStruct
__Py_TrueStruct
___bzero
___maskrune
___sincos_stret
___sprintf_chk
___stack_chk_fail
___stack_chk_guard
___stderrp
___stdinp
___strcat_chk
___strncat_chk
___toupper
___vsnprintf_chk
_asin
_calloc
_clock
_cos
_dgecon_
_dgetrf_
_dgetrs_
_exit
_fgets
_floor
_fprintf
_free
_freopen
_ldexp
_localtime
_longjmp
_malloc
_memcmp
_memcpy
_memmove
_memset_pattern16
_pow
_qsort
_realloc
_setjmp
_strchr
_strcmp
_strcpy
_strlen
_strncmp
_strncpy
_strpbrk
_strrchr
_strstr
_strtod
_strtol
_time
_vfprintf
dyld_stub_binder
```
This lists undefined symbols, you can see main is not one of them. If you try `otool -L` on the library it will tell you what libraries it will want to load.

I'm going to close this issue because I think it's probably not scipy's responsibility at this point (it's probably Paraview??). If you can't do this import from a straightforward interpreter please feel free to reopen.

**Comment by mathstuf** [comment]
I am a ParaView developer. I'm at my wit's end trying to figure out why qhull even wants `_main` in the first place.

**Comment by mathstuf** [comment]
`nm` does mention ` U _main`, so it is wanted from *somewhere*, but I can't find the reference in the source.

**Comment by andyfaff** [comment]
`nm` on my copy (1.2.3) of that shared library, list above, does not mention `_main`.

**Comment by andyfaff** [comment]
Did you compile numpy and scipy yourself? With what blas? Is it pip installed numpy, or numpy with MKL (e.g. from conda)?
Does anything in https://github.com/numpy/numpy/issues/10613 help?

**Comment by mathstuf** [comment]
Yes, numpy and scipy are compiled using `setup.py` (we do this in general for Intel compilers and MKL support on some platforms, but Intel isn't involved in this specific instance) from source. We're using LAPACK's blas libraries. This specific configuration is just using the Xcode toolchain and gfortran.

I haven't tried anything from that issue yet. Not sure it'd help since that seems Intel-related.
