### ISSUE TITLE
signal.fftconvolve no longer convolves types f8 and numpy.float64

### ISSUE THREAD

**Issue by ajeldorado** [scipy/scipy#12119]
My issue is about signal.fftconvolve. It used to convolve arrays of dtype('>f8') and dtype('float64') just fine but now it does not. This comes up quite often for me because the dtype('>f8') array is returned by astropy.io.fits.getdata, and the dtype('float64') convolution kernel is made with numpy.  

#### Error message:
```
Traceback (most recent call last):

  File "/Users/ajriggs/Repos/falco-python/wfirst_modeling/EXAMPLE_main_WFIRST_PhaseB_PROPER_HLC_baseline.py", line 131, in <module>
    fldFull, sampling = proper.prop_run('wfirst_phaseb', lambda_um, nout,  QUIET=True, PASSVALUE=optval.__dict__)

  File "/Users/ajriggs/.local/lib/proper_v3.2.1_python_3.x_12feb20/proper/prop_run.py", line 145, in prop_run
    psf_ilam, pixscale = func(lam[ilam], gridsize, kwargs["PASSVALUE"])

  File "/Users/ajriggs/Repos/falco-python/wfirst_modeling/wfirst_phaseb.py", line 511, in wfirst_phaseb
    if use_dm1 != 0: proper.prop_dm( wavefront, dm1_m, dm1_xc_act, dm1_yc_act, dm_sampling_m, XTILT=dm1_xtilt_deg, YTILT=dm1_ytilt_deg, ZTILT=dm1_ztilt_deg )

  File "/Users/ajriggs/.local/lib/proper_v3.2.1_python_3.x_12feb20/proper/prop_dm.py", line 197, in prop_dm
    dm_grid = ss.fftconvolve(dm_grid, inf, mode = 'same')

  File "/Users/ajriggs/opt/anaconda3/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 542, in fftconvolve
    ret = _freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)

  File "/Users/ajriggs/opt/anaconda3/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 383, in _freq_domain_conv
    sp2 = fft(in2, fshape, axes=axes)

  File "/Users/ajriggs/opt/anaconda3/lib/python3.7/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)

  File "/Users/ajriggs/opt/anaconda3/lib/python3.7/site-packages/scipy/fft/_pocketfft/basic.py", line 186, in r2cn
    return pfft.r2c(tmp, axes, forward, norm, None, workers)

RuntimeError: unsupported data type
```

#### Scipy/Numpy/Python version information:
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

**Comment by peterbell10** [comment]
Thanks for the report. This is a known issue, fixed in gh-11534. Unfortunately not in any released version yet.
