### ISSUE TITLE
pip install scipy error

### ISSUE THREAD

**Issue by ypchan** [scipy/scipy#12163]
```
$pip install scipy==1.4.0 -i https://mirrors.aliyun.com/pypi/simple/
4.8.2
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting scipy==1.4.0
  Using cached https://mirrors.aliyun.com/pypi/packages/48/74/ed053620f675ce5408b8dda34949fdc403e5f40db779c07a4436631dcbfb/scipy-1.4.0.tar.gz
  Installing build dependencies ... error
  ERROR: Complete output from command /psd/biosoft/anaconda/envs/Python-3.7/bin/python /psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /psd/tmp/pip-build-env-1kr87w04/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://mirrors.aliyun.com/pypi/simple/ -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.2.4':
  ERROR: 4.8.2
  Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
  Collecting wheel
    Using cached https://mirrors.aliyun.com/pypi/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
  Collecting setuptools
    Using cached https://mirrors.aliyun.com/pypi/packages/2c/c5/0d38afb961f83e0d51f319f7dc166195ebabc1ea3cb20a10a77f500f7156/setuptools-46.4.0-py3-none-any.whl
  Collecting Cython>=0.29.13
    Using cached https://mirrors.aliyun.com/pypi/packages/9b/24/3416df8ae5962b09f6b522ad6d61e711dadb57816a6e4e76c3b99732f3c5/Cython-0.29.17-py2.py3-none-any.whl
  Collecting numpy==1.14.5
    Using cached https://mirrors.aliyun.com/pypi/packages/d5/6e/f00492653d0fdf6497a181a1c1d46bbea5a2383e7faf4c8ca6d6f3d2581d/numpy-1.14.5.zip
  Collecting pybind11>=2.2.4
    Using cached https://mirrors.aliyun.com/pypi/packages/89/e3/d576f6f02bc75bacbc3d42494e8f1d063c95617d86648dba243c2cb3963e/pybind11-2.5.0-py2.py3-none-any.whl
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Complete output from command /psd/biosoft/anaconda/envs/Python-3.7/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /psd/tmp/pip-wheel-ina_ygo4 --python-tag cp37:
    ERROR: Running from numpy source directory.
    4.8.2
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

    non-existing path in 'numpy/distutils': 'site.cfg'
    F2PY Version 2
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

      FOUND:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

    /psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running bdist_wheel
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.linux-x86_64-3.7
    creating build/src.linux-x86_64-3.7/numpy
    creating build/src.linux-x86_64-3.7/numpy/distutils
    building library "npymath" sources
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using config
    C compiler: gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/psd/biosoft/anaconda/envs/Python-3.7/include/python3.7m -c'
    gcc: _configtest.c
    gcc -pthread -Wl,--sysroot=/ _configtest.o -o _configtest
    /usr/bin/ld: this linker was not configured to use sysroots
    collect2: error: ld returned 1 exit status
    /usr/bin/ld: this linker was not configured to use sysroots
    collect2: error: ld returned 1 exit status
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py", line 394, in <module>
        setup_package()
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py", line 386, in setup_package
        setup(**metadata)
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
        self.run_command('build')
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
        self.build_library_sources(*libname_info)
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 675, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
    ERROR: Failed building wheel for numpy
    Running setup.py clean for numpy
    ERROR: Complete output from command /psd/biosoft/anaconda/envs/Python-3.7/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
    ERROR: Running from numpy source directory.

    `setup.py clean` is not supported, use one of the following instead:

      - `git clean -xdf` (cleans all files)
      - `git clean -Xdf` (cleans all versioned files, doesn't touch
                          files that aren't checked into the git repo)

    Add `--force` to your command to use it anyway if you must (unsupported).

    ----------------------------------------
    ERROR: Failed cleaning build dir for numpy
  Failed to build numpy
  Installing collected packages: wheel, setuptools, Cython, numpy, pybind11
    Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Complete output from command /psd/biosoft/anaconda/envs/Python-3.7/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /psd/tmp/pip-record-eiuhchfy/install-record.txt --single-version-externally-managed --prefix /psd/tmp/pip-build-env-1kr87w04/overlay --compile:
      ERROR: Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      4.8.2
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        FOUND:
          libraries = ['mkl_rt', 'pthread']
          library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
          define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
          include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

        FOUND:
          libraries = ['mkl_rt', 'pthread']
          library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
          define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
          include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

      non-existing path in 'numpy/distutils': 'site.cfg'
      F2PY Version 2
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        FOUND:
          libraries = ['mkl_rt', 'pthread']
          library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
          define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
          include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

        FOUND:
          libraries = ['mkl_rt', 'pthread']
          library_dirs = ['/psd/biosoft/anaconda/envs/Python-3.7/lib']
          define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
          include_dirs = ['/usr/local/include', '/usr/include', '/usr/include/suitesparse', '/psd/biosoft/anaconda/envs/Python-3.7/include']

      /psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      building library "npymath" sources
      get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
      customize Gnu95FCompiler
      Found executable /usr/bin/gfortran
      customize Gnu95FCompiler
      customize Gnu95FCompiler using config
      C compiler: gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

      compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/psd/biosoft/anaconda/envs/Python-3.7/include/python3.7m -c'
      gcc: _configtest.c
      gcc -pthread -Wl,--sysroot=/ _configtest.o -o _configtest
      /usr/bin/ld: this linker was not configured to use sysroots
      collect2: error: ld returned 1 exit status
      /usr/bin/ld: this linker was not configured to use sysroots
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py", line 394, in <module>
          setup_package()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py", line 386, in setup_package
          setup(**metadata)
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/install.py", line 62, in run
          r = self.setuptools_run()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
          return distutils_install.run(self)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build.py", line 47, in run
          old_build.run(self)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 148, in run
          self.build_sources()
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
          self.build_library_sources(*libname_info)
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/psd/tmp/pip-install-b5q3l0tg/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 675, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program
      ----------------------------------------
  ERROR: Command "/psd/biosoft/anaconda/envs/Python-3.7/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/psd/tmp/pip-install-b5q3l0tg/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /psd/tmp/pip-record-eiuhchfy/install-record.txt --single-version-externally-managed --prefix /psd/tmp/pip-build-env-1kr87w04/overlay --compile" failed with error code 1 in /psd/tmp/pip-install-b5q3l0tg/numpy/
  ----------------------------------------
ERROR: Command "/psd/biosoft/anaconda/envs/Python-3.7/bin/python /psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /psd/tmp/pip-build-env-1kr87w04/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://mirrors.aliyun.com/pypi/simple/ -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.2.4'" failed with error code 1 in None
```

**Comment by ilayn** [comment]
Please use `conda` command if you are using Anaconda distributions. pip is often messes things up when used with those.

**Comment by Ayke** [comment]
I'm having the exact same problem. 

`python -m pip install scipy` gives me the following error:
`
Defaulting to user installation because normal site-packages is not writeable
Collecting scipy
  Using cached scipy-1.5.0.tar.gz (25.6 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /home/nvidia/.local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hinst5x0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.18' 'numpy==1.14.5; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.3'
       cwd: None
  Complete output (724 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting setuptools
    Using cached setuptools-47.3.1-py3-none-any.whl (582 kB)
  Collecting Cython>=0.29.18
    Using cached Cython-0.29.20-py2.py3-none-any.whl (973 kB)
  Collecting numpy==1.14.5
    Using cached numpy-1.14.5.zip (4.9 MB)
  Collecting pybind11>=2.4.3
    Using cached pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ef3wqsj9/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ef3wqsj9/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0g433n0w
         cwd: /tmp/pip-install-ef3wqsj9/numpy/
`


To confirm, I have a newly installed ubuntu 18.04 with python 3.6, pip and numpy are correctly installed. 

`
python -m pip --version
pip 20.1.1 from /home/nvidia/.local/lib/python3.6/site-packages/pip (python 3.6)
`

`
python -m pip install --upgrade numpy
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: numpy in ./.local/lib/python3.6/site-packages (1.19.0)
`
