### ISSUE TITLE
spatial.ConvexHull is uninterruptible when running

### ISSUE THREAD

**Issue by hexchain** [scipy/scipy#12219]
It seems that when `spatial.ConvexHull` is running it cannot be interrupted with `SIGINT`.

#### Reproducing code example:

Feed the following array into `spatial.ConvexHull` and try to interrupt.

<details>
<summary>Example data</summary>

```python
D=array([[ 7.603686e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  7.603686e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  7.603686e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  7.603686e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  8.936956e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         8.936956e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  8.936956e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  8.936956e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  5.410814e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  5.410814e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.410814e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.410814e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  7.011844e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  7.011844e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  7.011844e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         7.011844e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  4.518964e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  4.518964e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  4.518964e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  4.518964e+00],
       [-3.662633e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00, -3.628802e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00, -3.757803e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.025917e-01,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00, -3.682054e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.904448e-01,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.825832e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.135007e-01],
       [ 5.873305e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.662633e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        -3.628802e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00, -3.757803e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.025917e-01,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00, -3.682054e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.904448e-01,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00, -3.825832e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.135007e-01],
       [ 5.873305e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.662633e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.628802e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        -3.757803e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.025917e-01,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00, -3.682054e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.904448e-01,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00, -3.825832e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.135007e-01],
       [ 5.873305e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.873305e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00, -3.662633e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         5.819055e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  5.819055e-01,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.628802e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         6.025917e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00, -3.757803e+00,
         0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  5.904448e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        -3.682054e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  6.135007e-01,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00, -3.825832e+00],
       [ 1.343122e+00, -6.418205e-02,  1.768226e+00,  1.064634e+00,  1.590279e+00,  1.343122e+00,
        -6.418205e-02,  1.768226e+00,  1.064634e+00,  1.590279e+00,  1.343122e+00, -6.418205e-02,
         1.768226e+00,  1.064634e+00,  1.590279e+00,  1.343122e+00, -6.418205e-02,  1.768226e+00,
         1.064634e+00,  1.590279e+00],
       [-8.810935e-01,  4.210370e-02, -1.159964e+00, -6.984042e-01, -1.043230e+00,  1.412899e-01,
        -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01, -6.751642e-03,
         1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01, -6.751642e-03,  1.860088e-01,
         1.119943e-01,  1.672897e-01],
       [ 1.412899e-01, -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01, -8.810935e-01,
         4.210370e-02, -1.159964e+00, -6.984042e-01, -1.043230e+00,  1.412899e-01, -6.751642e-03,
         1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01, -6.751642e-03,  1.860088e-01,
         1.119943e-01,  1.672897e-01],
       [ 1.412899e-01, -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01,
        -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01, -8.810935e-01,  4.210370e-02,
        -1.159964e+00, -6.984042e-01, -1.043230e+00,  1.412899e-01, -6.751642e-03,  1.860088e-01,
         1.119943e-01,  1.672897e-01],
       [ 1.412899e-01, -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01,
        -6.751642e-03,  1.860088e-01,  1.119943e-01,  1.672897e-01,  1.412899e-01, -6.751642e-03,
         1.860088e-01,  1.119943e-01,  1.672897e-01, -8.810935e-01,  4.210370e-02, -1.159964e+00,
        -6.984042e-01, -1.043230e+00],
       [ 1.065574e-01,  1.082666e+00,  1.211024e+00,  7.435147e-01,  2.417595e+00,  1.065574e-01,
         1.082666e+00,  1.211024e+00,  7.435147e-01,  2.417595e+00,  1.065574e-01,  1.082666e+00,
         1.211024e+00,  7.435147e-01,  2.417595e+00,  1.065574e-01,  1.082666e+00,  1.211024e+00,
         7.435147e-01,  2.417595e+00],
       [-7.182555e-02, -7.297762e-01, -8.162966e-01, -5.011698e-01, -1.629592e+00,  1.151776e-02,
         1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,  1.170251e-01,
         1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,  1.170251e-01,  1.308992e-01,
         8.036631e-02,  2.613172e-01],
       [ 1.151776e-02,  1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01, -7.182555e-02,
        -7.297762e-01, -8.162966e-01, -5.011698e-01, -1.629592e+00,  1.151776e-02,  1.170251e-01,
         1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,  1.170251e-01,  1.308992e-01,
         8.036631e-02,  2.613172e-01],
       [ 1.151776e-02,  1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,
         1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01, -7.182555e-02, -7.297762e-01,
        -8.162966e-01, -5.011698e-01, -1.629592e+00,  1.151776e-02,  1.170251e-01,  1.308992e-01,
         8.036631e-02,  2.613172e-01],
       [ 1.151776e-02,  1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,
         1.170251e-01,  1.308992e-01,  8.036631e-02,  2.613172e-01,  1.151776e-02,  1.170251e-01,
         1.308992e-01,  8.036631e-02,  2.613172e-01, -7.182555e-02, -7.297762e-01, -8.162966e-01,
        -5.011698e-01, -1.629592e+00]])
```
</details>

#### Error messages
```
% python test.py
^C^C^C^C^C^C^CTraceback (most recent call last):
  File "test.py", line 146, in <module>
    spatial.ConvexHull(D)
  File "qhull.pyx", line 2430, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 1551, in scipy.spatial.qhull._QhullUser.__init__
  File "qhull.pyx", line 2463, in scipy.spatial.qhull.ConvexHull._update
  File "qhull.pyx", line 1580, in scipy.spatial.qhull._QhullUser._update
  File "/usr/lib/python3.8/site-packages/numpy/core/_methods.py", line 32, in _amin
    def _amin(a, axis=None, out=None, keepdims=False,
KeyboardInterrupt

python test.py  146.06s user 0.62s system 98% cpu 2:28.72 total
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.4 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by tylerjereddy** [comment]
Note that if you read through the closed PR, there was a desire to adjust this issue to more generally track the use case of empowering keyboard interrupts for loops that don't have signal handlers active. For loops that we control ourselves, like Cython loops, we might be able to do something like this: https://stackoverflow.com/a/16778026/2942522

That appears to be portable, low-overhead, and could be called every `n` iterations when looping in some long-running code.

That said, I took a look at this specific case, and found that the time-consuming looping was happening in a location pretty far-removed from Cython, deep in the guts of a few different looping-locations in `scipy/spatial/qhull_src/src/libqhull_r.c`. I don't know that we'd want to start mixing in `PyErr_CheckSignals()` from CPython in that vendored code, and if not, writing the signal handler portably may be more trouble than it is worth for that particular case?

Still, for directly-exposed Cython loops it strikes me as less controversial.
