### ISSUE TITLE
eigh fails to catch ill-conditioned eigenvalue

### ISSUE THREAD

**Issue by dkweiss31** [scipy/scipy#12258]
I would like to solve a real symmetric generalized eigenvalue problem ```Hx=\lambda Mx```. ```M``` has smallest eigenvalue on the order of 1e-9, so ```eigh``` treats that as positive definite. ```H``` on the other hand due to rounding errors is indefinite, i.e. it was constructed to be positive definite but has an eigenvalue of -1e-9. Note that if the roles were reversed, ```eigh``` would throw an error, but in this case it does not because ```H``` does not have to be positive definite. ```sp.linalg.eigh(H, M, eigvals=(0, 4))``` returns an ill-conditioned eigenvalue in addition to the correct eigenvalues, which does not feel like the correct behavior. 

On the other hand, if I feed the matrices into ```sp.linalg.ordqz(H, M)```, that algorithm correctly recognizes the ill-conditioned eigenvalue and allows for it to be filtered out.

The smallest working example I could come up with is defined by the two following 12x12 arrays. The M matrix is
```
1.802187623667999894e+00,0.000000000000000000e+00,0.000000000000000000e+00,1.207214247488000103e+00,2.230110000000000109e-07,1.169148657665999957e+00,1.776820963759000005e+00,3.423742296599999874e-02,-2.144229999999999872e-07,1.281081722182999982e+00,4.728299999999999796e-07,1.279399686531000002e+00
0.000000000000000000e+00,9.492886218099999551e-02,-2.230110000000000109e-07,-0.000000000000000000e+00,-0.000000000000000000e+00,0.000000000000000000e+00,-3.423739552099999695e-02,-3.490215428599999919e-02,-5.903489999999999614e-07,5.301589727500000127e-02,4.535200000000000006e-07,1.799516241209999923e-01
-0.000000000000000000e+00,-2.230110000000000109e-07,1.487617355660000029e-01,0.000000000000000000e+00,-0.000000000000000000e+00,-0.000000000000000000e+00,3.108339999999999893e-07,-3.745480000000000264e-07,-3.252343818299999884e-02,-4.146949999999999954e-07,2.887277747090000179e-01,-1.697595999999999950e-06
1.207214247488000103e+00,-0.000000000000000000e+00,0.000000000000000000e+00,1.116386524484999976e+00,2.355845999999999958e-06,1.073551814690999917e+00,1.281081682621000084e+00,-5.301581596899999915e-02,-1.210017999999999923e-06,7.435734797390000095e-01,-1.672677000000000096e-06,8.577447696769999741e-01
2.230110000000000109e-07,0.000000000000000000e+00,-0.000000000000000000e+00,2.355845999999999958e-06,5.886066034600000441e-01,-3.351065999999999892e-06,4.920669999999999552e-07,-1.459819999999999899e-07,-2.887275432659999752e-01,-6.143120000000000020e-07,-1.287571321759999887e-01,-2.675088000000000111e-06
1.169148657665999957e+00,0.000000000000000000e+00,0.000000000000000000e+00,1.073551814690999917e+00,-3.351065999999999892e-06,1.341693447351000046e+00,1.279399705699999945e+00,-1.799519385610000022e-01,2.340678000000000123e-06,8.577446543519999800e-01,-1.774977999999999974e-06,7.922985907149999729e-01
1.776820963759000005e+00,-3.423739552099999695e-02,3.108339999999999893e-07,1.281081682621000084e+00,4.920669999999999552e-07,1.279399705699999945e+00,1.802188302972000056e+00,-0.000000000000000000e+00,-0.000000000000000000e+00,1.207214772571000072e+00,2.385999999999999991e-08,1.169149171436999923e+00
3.423742296599999874e-02,-3.490215428599999919e-02,-3.745480000000000264e-07,-5.301581596899999915e-02,-1.459819999999999899e-07,-1.799519385610000022e-01,-0.000000000000000000e+00,9.492879890500000029e-02,-2.385999999999999991e-08,0.000000000000000000e+00,0.000000000000000000e+00,-0.000000000000000000e+00
-2.144229999999999872e-07,-5.903489999999999614e-07,-3.252343818299999884e-02,-1.210017999999999923e-06,-2.887275432659999752e-01,2.340678000000000123e-06,0.000000000000000000e+00,-2.385999999999999991e-08,1.487616882879999880e-01,0.000000000000000000e+00,-0.000000000000000000e+00,0.000000000000000000e+00
1.281081722182999982e+00,5.301589727500000127e-02,-4.146949999999999954e-07,7.435734797390000095e-01,-6.143120000000000020e-07,8.577446543519999800e-01,1.207214772571000072e+00,0.000000000000000000e+00,-0.000000000000000000e+00,1.116385989892000108e+00,2.520439999999999771e-07,1.073552587520000046e+00
4.728299999999999796e-07,4.535200000000000006e-07,2.887277747090000179e-01,-1.672677000000000096e-06,-1.287571321759999887e-01,-1.774977999999999974e-06,2.385999999999999991e-08,0.000000000000000000e+00,0.000000000000000000e+00,2.520439999999999771e-07,5.886073592620000294e-01,-3.585220000000000124e-07
1.279399686531000002e+00,1.799516241209999923e-01,-1.697595999999999950e-06,8.577447696769999741e-01,-2.675088000000000111e-06,7.922985907149999729e-01,1.169149171436999923e+00,0.000000000000000000e+00,0.000000000000000000e+00,1.073552587520000046e+00,-3.585220000000000124e-07,1.341693157966999950e+00
```

While the H matrix is 

```
5.075113158453000040e+00,1.692027881819999913e-01,-9.282389999999999781e-07,2.884403172956000017e+00,2.636978000000000149e-06,2.524115861548000161e+00,4.674297916203999925e+00,3.710353482250000057e-01,-4.305297000000000227e-06,4.054024127681000067e+00,1.820061999999999956e-06,4.264478358266000413e+00
1.692027881819999913e-01,1.564592287893999956e+00,-3.730107999999999880e-06,1.907881846470000087e-01,-4.326379999999999860e-07,1.382638931780000024e-01,-3.710354013780000071e-01,-5.838325488969999810e-01,-2.226391400000000037e-05,9.137725441309999530e-01,7.087982999999999896e-06,3.053514126062999878e+00
-9.282389999999999781e-07,-3.730107999999999880e-06,2.428790908788999836e+00,-1.872953000000000082e-06,-1.139116101279999960e-01,-2.009990000000000120e-07,3.940460000000000386e-06,6.722471000000000269e-06,-4.754968299489999994e-01,-6.393055000000000067e-06,4.739353739035999880e+00,-2.797214100000000158e-05
2.884403172956000017e+00,1.907881846470000087e-01,-1.872953000000000082e-06,6.754052898928000204e+00,3.681529999999999970e-05,5.953898076200999867e+00,4.054023406179999789e+00,-9.137714640720000503e-01,-2.075175099999999938e-05,4.572173552830000043e-01,-3.198068299999999706e-05,2.799659810394000026e+00
2.636978000000000149e-06,-4.326379999999999860e-07,-1.139116101279999960e-01,3.681529999999999970e-05,9.716561310370000371e+00,-5.555816700000000254e-05,1.007655499999999961e-05,-2.558852999999999944e-06,-4.739350242922999890e+00,-7.982467999999999346e-06,-2.349900604935000192e+00,-4.255320999999999843e-05
2.524115861548000161e+00,1.382638931780000024e-01,-2.009990000000000120e-07,5.953898076200999867e+00,-5.555816700000000254e-05,1.065365725547199993e+01,4.264478169518000072e+00,-3.053519506476999990e+00,3.725209200000000010e-05,2.799656996747000193e+00,-3.210292200000000075e-05,1.812841261823999961e+00
4.674297916203999925e+00,-3.710354013780000071e-01,3.940460000000000386e-06,4.054023406179999789e+00,1.007655499999999961e-05,4.264478169518000072e+00,5.075114713199000427e+00,-1.692032618179999948e-01,-9.552619999999999945e-07,2.884405243803000118e+00,-2.237995000000000076e-06,2.524118162685000222e+00
3.710353482250000057e-01,-5.838325488969999810e-01,6.722471000000000269e-06,-9.137714640720000503e-01,-2.558852999999999944e-06,-3.053519506476999990e+00,-1.692032618179999948e-01,1.564590913505000014e+00,-4.991080000000000247e-07,-1.907885248129999878e-01,-1.104550000000000054e-07,-1.382647270429999964e-01
-4.305297000000000227e-06,-2.226391400000000037e-05,-4.754968299489999994e-01,-2.075175099999999938e-05,-4.739350242922999890e+00,3.725209200000000010e-05,-9.552619999999999945e-07,-4.991080000000000247e-07,2.428790286268999843e+00,-3.218289999999999895e-07,1.139117242900000021e-01,-7.284759999999999647e-07
4.054024127681000067e+00,9.137725441309999530e-01,-6.393055000000000067e-06,4.572173552830000043e-01,-7.982467999999999346e-06,2.799656996747000193e+00,2.884405243803000118e+00,-1.907885248129999878e-01,-3.218289999999999895e-07,6.754037462956000049e+00,1.607814000000000053e-06,5.953907320812000137e+00
1.820061999999999956e-06,7.087982999999999896e-06,4.739353739035999880e+00,-3.198068299999999706e-05,-2.349900604935000192e+00,-3.210292200000000075e-05,-2.237995000000000076e-06,-1.104550000000000054e-07,1.139117242900000021e-01,1.607814000000000053e-06,9.716573175465999412e+00,-7.746122999999999832e-06
4.264478358266000413e+00,3.053514126062999878e+00,-2.797214100000000158e-05,2.799659810394000026e+00,-4.255320999999999843e-05,1.812841261823999961e+00,2.524118162685000222e+00,-1.382647270429999964e-01,-7.284759999999999647e-07,5.953907320812000137e+00,-7.746122999999999832e-06,1.065364929937899952e+01
```

The smallest correct eigenvalues are 2.71, 15.79, 16.01, ... However eigh also reports an eigenvalue of -0.0898 which is ill-conditioned, and should therefore be excluded.

I am hoping either that eigh would be able to recognize and eliminate the ill-conditioned eigenvalue or throw a `LinAlgError` due to its presence.

I am running python 3.7, scipy 1.4.1 and numpy 1.18.1

**Comment by ilayn** [comment]
I don't understand why you mark it as a wrong eigenvalue. The generalized problem is not guaranteed to spit out all nonnegative eigenvalues. Only `M` needs to be positive definite, in fact if you use the new `eigh` API that will come with v1.5.0 very soon: 

```python
>>> # get the smallest eigenvalue/vector
>>> lamb, lv = sp.linalg.eigh(H, M, subset_by_index=[0,0])
>>> # verify 
>>> H @ lv - lamb*(M @ lv)
array([[ 2.86798925e-12],
       [ 1.12912555e-13],
       [-6.03325441e-14],
       [ 4.47212216e-12],
       [-7.26112855e-13],
       [ 3.55239406e-12],
       [ 3.26919648e-12],
       [ 6.87823225e-13],
       [-5.41438585e-13],
       [ 6.22805865e-12],
       [ 6.70560179e-13],
       [ 4.52661541e-12]])
```

Let's look at individual eigenvalues 

```python
>>> sp.linalg.eigh(M, eigvals_only=True)
array([2.01370083e-09, 1.76238671e-07, 4.49004556e-07, 2.57986279e-05,
       1.41712591e-04, 4.42986535e-02, 2.40607867e-01, 4.07263687e-01,
       6.41134550e-01, 7.66993120e-01, 8.33576589e-01, 7.25108749e+00])
>>> sp.linalg.eigh(H, eigvals_only=True)
Out[45]: 
array([-1.09199044e-09,  2.57760434e-06,  2.74875085e-05,  1.08342798e-03,
        5.95843249e-03,  7.80144608e-01,  4.39895407e+00,  5.46808052e+00,
        1.02709327e+01,  1.21202521e+01,  1.40186782e+01,  2.53214095e+01])
```

So M is barely posdef and H isn't so if you swap them around H fails to serve because it's not posdef as B matrix. Not because it is ill-conditioned. The error says this explicitly

```python
lamb, lv = sp.linalg.eigh(M, H)
Traceback (most recent call last):

  File "<ipython-input-46-de7faa5cdf51>", line 1, in <module>
    lamb, lv = sp.linalg.eigh(M, H)

  File "c:\users\ilhan polat\appdata\local\programs\python\python38\lib\site-packages\scipy-1.5.0.dev0+297e602-py3.8-win-amd64.egg\scipy\linalg\decomp.py", line 575, in eigh
    raise LinAlgError('The leading minor of order {} of B is not '

LinAlgError: The leading minor of order 12 of B is not positive definite. The factorization of B could not be completed and no eigenvalues or eigenvectors were computed.
```

**Comment by dkweiss31** [comment]
Thanks for taking a look at this @ilayn . I agree that it is an eigenvalue, however if the matrices are perturbed slightly, that eigenvalue changes dramatically while the others are quite stable. That is what I mean in this context by ill-conditioned. For example

```
evals = sp.linalg.eigh(H, M)  # Returns [-8.98210260e-02,  2.71169952e+00,  1.57966875e+01,  1.60197076e+01 ... ]
M_perturb = np.random.rand(12, 12)
H_perturb = np.random.rand(12, 12)
M_rand = M + 10**(-9) * np.matmul(M_perturb.T, M_perturb) # ensure still symmetric
H_rand = H + 10**(-9) * np.matmul(H_perturb.T, H_perturb)
evals_r = sp.linalg.eigh(H_rand, M_rand) # Returns [1.83117898e-02 2.71169952e+00 1.57963505e+01 1.60191746e+01, ... ]
```
That is, a perturbation on the order of 1e-9 created a change on the order of 1e-2 to the offending eigenvalue, while the others are relatively unchanged. This of course is a user (me) problem, for passing eigh an eigenvalue problem that is ill posed in this way. However I would have expected an error to be thrown or perhaps a warning that not all of the eigenvalues are stable.

**Comment by ilayn** [comment]
That is expected because the eig of both H and M is just on the fence of being zero and the perturbation you are adding is at the same order of magnitude with that eigenvalue moving it around hence in that sense the perturbation is not so innocent amount with respect to that. I would say this is not necessarily a forward stability error.

Also since this is a generalized eigenvalue problem the perturbation scheme should take that into account. The perturbations do not enter linearly into the problem.

**Comment by ilayn** [comment]
I'll close this but please feel free to add remarks if you wish
