### ISSUE TITLE
integer overflow in scipy.sparse.sputils.check_shape when matrix size > 2^32

### ISSUE THREAD

**Issue by shilinng** [scipy/scipy#12301]
When trying to reshape a sparse matrix with size more than 2**32, scipy.sparse.sputils.check_shape would sometimes throw an "cannot reshape array of size x into shape (y, 'newshape')", even though the new shape is compatible with the size. This is due to overflow error when calculating size of the sparse matrix via np.prod, with datatype = int. Changing the datatype to np.int64 solves this problem (and allow reshape to proceed). 

Note: I believe https://github.com/scipy/scipy/pull/9087 solves the problem of integer overflowing when reshaping sparse matrix with size > 2^32. However, it might be better to have another pair of eyes on this in case I miss something, as fixing the overflowing bug on check_shape allow reshape to proceed for sparse matrix with size >2^32.

The following example load a matrix with size (2^16 -1) * (2^16 -1) * 2 = 8589672450. Reshaping to shape (10, -1) should work. However, an integer overflowing error in np.prod calculated the size as  -262142.

#### Reproducing code example:

```
import scipy.sparse
A = scipy.sparse.hstack(
    [scipy.sparse.eye(2**16 - 1), scipy.sparse.eye(2**16 - 1)])
A.reshape((10, -1))
```

#### Error message:

```
Traceback (most recent call last):

  File "<ipython-input-14-b3568b621ba3>", line 3, in <module>
    A.reshape((10,-1))

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\coo.py", line 195, in reshape
    shape = check_shape(args, self.shape)

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\sputils.py", line 307, in check_shape
    ''.format(current_size, err_shape))

ValueError: cannot reshape array of size -262142 into shape (10, 'newshape')
```

#### Scipy/Numpy/Python version information:
```
1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by shilinng** [comment]
My suggestion is to use get_index_dtype to check if int64 is needed, if changing of dtype for np.prod is not recommended. Basically, the following version of scipy.sparse.sputils.check_shape works for me:
```
def check_shape(args, current_shape=None):
    """Imitate numpy.matrix handling of shape arguments"""
    if len(args) == 0:
        raise TypeError("function missing 1 required positional argument: "
                        "'shape'")
    elif len(args) == 1:
        try:
            shape_iter = iter(args[0])
        except TypeError:
            new_shape = (operator.index(args[0]), )
        else:
            new_shape = tuple(operator.index(arg) for arg in shape_iter)
    else:
        new_shape = tuple(operator.index(arg) for arg in args)


    if current_shape is None:
        if len(new_shape) != 2:
            raise ValueError('shape must be a 2-tuple of positive integers')
        elif new_shape[0] < 0 or new_shape[1] < 0:
            raise ValueError("'shape' elements cannot be negative")

    else:
        # upcast to avoid overflow when calculating size
        nrows, ncols = current_shape
        dtype = scipy.sparse.sputils.get_index_dtype(maxval=(nrows * ncols))
        
        # Check the current size only if needed
#        current_size = np.prod(current_shape, dtype=int) # original scipy version
        current_size = np.prod(current_shape, dtype=dtype) # solve overlfow problem

        # Check for negatives
        negative_indexes = [i for i, x in enumerate(new_shape) if x < 0]
        if len(negative_indexes) == 0:
#            new_size = np.prod(new_shape, dtype=int) # original scipy version
            new_size = np.prod(new_shape, dtype=dtype) # solve overlfow problem
            if new_size != current_size:
                raise ValueError('cannot reshape array of size {} into shape {}'
                                 .format(new_size, new_shape))
        elif len(negative_indexes) == 1:
            skip = negative_indexes[0]
            specified = np.prod(new_shape[0:skip] + new_shape[skip+1:])
            unspecified, remainder = divmod(current_size, specified)
            if remainder != 0:
                err_shape = tuple('newshape' if x < 0 else x for x in new_shape)
                raise ValueError('cannot reshape array of size {} into shape {}'
                                 ''.format(current_size, err_shape))
            new_shape = new_shape[0:skip] + (unspecified,) + new_shape[skip+1:]
        else:
            raise ValueError('can only specify one unknown dimension')

        # Add and remove ones like numpy.matrix.reshape
        if len(new_shape) != 2:
            new_shape = tuple(arg for arg in new_shape if arg != 1)

            if len(new_shape) == 0:
                new_shape = (1, 1)
            elif len(new_shape) == 1:
                new_shape = (1, new_shape[0])

    if len(new_shape) > 2:
        raise ValueError('shape too large to be a matrix')

    return new_shape
```
