### ISSUE TITLE
ODR could not generate output

### ISSUE THREAD

**Issue by keithyipkw** [scipy/scipy#12420]
When `np.seterr(all='raise')`, some data cause crashes. 

#### Reproducing code example:

```
import numpy as np
from scipy import odr

def main():
    np.seterr(all='raise')
    trueXs = [0, 0.15, 0.5, 0.75, 1.5]
    trueModel = [10, 4, 0.5, 12]
    
    yOk = [10.05402736, 10.21411013, 11.10575636, 11.88982182, 12.18411301]
    yCrash = [10.09633071, 10.09851683, 10.98351559, 11.86245156, 11.79502592]
    res1 = OdrFitFunction(FourPL, trueModel, trueXs, yOk)
    print(res1.beta)

    res2 = OdrFitFunction(FourPL, trueModel, trueXs, yCrash)
    print(res2.beta)

def OdrFitFunction(f, initial, xs, ys):
    return odr.ODR(odr.Data(xs, ys, wd=1, we=1), odr.Model(f), initial).run()

def FourPL(a, x):
    r = a[3] + (a[0] - a[3]) / (1 + (x / a[2]) ** a[1])
    return r

if __name__ == "__main__":
    main()
```

#### Error message:

```
Traceback (most recent call last):
  File "odr_bug.py", line 25, in <module>
    main()
  File "odr_bug.py", line 14, in main
    res2 = OdrFitFunction(FourPL, trueModel, trueXs, yCrash)
  File "odr_bug.py", line 18, in OdrFitFunction
    return odr.ODR(odr.Data(xs, ys, wd=1, we=1), odr.Model(f), initial).run()
  File "C:\Users\user\.conda\envs\mkl\lib\site-packages\scipy\odr\odrpack.py", line 1101, in run
    self.output = Output(odr(*args, **kwds))
RuntimeError: could not generate output
```

#### Scipy/Numpy/Python version information:
```
1.5.0 1.18.1 sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)
```

**Comment by keithyipkw** [comment]
`odr.odr` crashes too but only when `np.seterr(all='raise')` is not called. If `np.seterr(all='raise')` is called, the code prints the normal error `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`.

```
import numpy as np
from scipy import odr

def main():
    trueXs = [0, 0.15, 0.5, 0.75, 1.5]
    trueModel = [10, 4, 0.5, 12]
    
    yOk = [10.05402736, 10.21411013, 11.10575636, 11.88982182, 12.18411301]
    yCrash = [10.09633071, 10.09851683, 10.98351559, 11.86245156, 11.79502592]
    res1 = OdrFitFunction(FourPL, trueModel, trueXs, yOk)
    print(res1.beta)

    res2 = OdrFitFunction(FourPL, trueModel, trueXs, yCrash)
    print(res2.beta)

def OdrFitFunction(f, initial, xs, ys):
    res = odr.odr(f, initial, ys, xs)
    return res[0]

def FourPL(a, x):
    r = a[3] + (a[0] - a[3]) / (1 + (x / a[2]) ** a[1])
    # crashing-----------------------------------------------------------------------------
    if not np.isfinite(r):
        print("incorrect use of isfinite")
    return r

if __name__ == "__main__":
    main()
```
