### ISSUE TITLE
failed scipy installation on AIX7.2

### ISSUE THREAD

**Issue by bergen288** [scipy/scipy#12454]
My issue is about failed scipy installation on AIX7.2

#### Reproducing code example:

```r
pkg=$1
python -m pip install --no-build-isolation --no-index --find-links ./ $pkg >$pkg.log 2>&1 &
```
Where $pkg is scipy-1.5.0.tar.gz.

#### Error message:
```r
Looking in links: ./
Processing ./scipy-1.5.0.tar.gz
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpsnjw8132
         cwd: /tmp/pip-req-build-68354t7t
    Complete output (122 lines):
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/bin/../../opt/freeware/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/usr/bin/../../opt/freeware/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    openblas_clapack_info:
      libraries openblas,lapack not found in ['/usr/bin/../../opt/freeware/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    flame_info:
      libraries flame not found in ['/usr/bin/../../opt/freeware/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
      libraries tatlas,tatlas not found in /usr/bin/../../opt/freeware/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries tatlas,tatlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/
      libraries tatlas,tatlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
      libraries satlas,satlas not found in /usr/bin/../../opt/freeware/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries satlas,satlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/
      libraries satlas,satlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/bin/../../opt/freeware/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries lapack_atlas not found in /usr/bin/../../opt/freeware/lib
      libraries f77blas,cblas,atlas not found in /usr/bin/../../opt/freeware/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries f77blas,cblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/
      libraries f77blas,cblas,atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['/usr/bin/../../opt/freeware/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:462: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-z8s5x9yp'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from SciPy source directory.
    /opt/freeware/lib64/python3.7/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    /opt/freeware/lib64/python3.7/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    Traceback (most recent call last):
      File "/opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
      File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/build_meta.py", line 249, in run_setup
      File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/build_meta.py", line 142, in run_setup
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/opt/freeware/lib64/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /opt/freeware/lib/python3.7/site-packages/pip-20.2.dev1-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpsnjw8132 Check the logs for full command output.
```

#### Scipy/Numpy/Python version information:
```r
Python  3.7.6
numpy  1.19.0
scipy     1.5.0 to be installed.
```

**Comment by pv** [comment]
As the message indicates, you will need to install BLAS and LAPACK (and potentially tell Scipy which ones to use):
https://docs.scipy.org/doc/scipy/reference/building/index.html

**Comment by luckydonald** [comment]
@pv the link leads to 404.
