### ISSUE TITLE
scipy validation error

### ISSUE THREAD

**Issue by bergen288** [scipy/scipy#12467]
My issue is about scipy validation error. After the installation of OpenBLAS, scipy package is installed successfully on AIX7.2.  Below is my script to install Python packages:
```r
pkg=$1
python -m pip install --no-build-isolation --no-index --find-links ./ $pkg >$pkg.log 2>&1 &
``` 
Below is the installation log:
```r
Looking in links: ./
Processing ./scipy-1.5.0.tar.gz
    Preparing wheel metadata: started
    Preparing wheel metadata: still running...
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: scipy
  Building wheel for scipy (PEP 517): started
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): still running...
  Building wheel for scipy (PEP 517): finished with status 'done'
  Created wheel for scipy: filename=scipy-1.5.0-cp37-cp37m-aix_7_2.whl size=23810275 sha256=40b7a9b01f91d56915979c028ab085729bfe5a3594344f0f20886d42cd2abd86
  Stored in directory: /.cache/pip/wheels/fc/ff/0c/e2506c30e4687c7a7ead3be3e6c3146c6c29daae89b14af2d6
Successfully built scipy
Installing collected packages: scipy
Successfully installed scipy-1.5.0
```
#### Reproducing code example:

```
import numpy as np
np.test('full')
import scipy
scipy.test()
```

#### Error message:

I started a batch python step with above 4 lines around 9am this morning.  Its output file hadn't been updated since 9:04am and the session was still running.  I was afraid it was in endless looping so it was killed around 3:45pm.  The log file is very large so I will attached it at the bottom.  Below are just first few lines. 
```
NumPy version 1.19.0
NumPy relaxed strides checking option: True

==================================== ERRORS ====================================
______________ ERROR collecting testing/tests/test_decorators.py _______________
/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py:16: in <module>
    import nose  # noqa: F401
        KnownFailureException = <class 'numpy.testing._private.utils.KnownFailureException'>
        SkipTest   = <class 'unittest.case.SkipTest'>
        __builtins__ = <builtins>
        __cached__ = '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/__pycache__/test_decorators.cpython-37.pyc'
        __doc__    = '\nTest the decorators from ``testing.decorators``.\n\n'
        __file__   = '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0xa00000000e1e508>
        __name__   = 'numpy.testing.tests.test_decorators'
        __package__ = 'numpy.testing.tests'
        __spec__   = ModuleSpec(name='numpy.testing.tests.test_decorators', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at 0xa00000000e1e508>, origin='/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py')
        assert_    = <function assert_ at 0xa000000013443a8>
        assert_raises = <function assert_raises at 0xa00000001344e58>
        dec        = <module 'numpy.testing._private.decorators' from '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/_private/decorators.py'>
        pytest     = <module 'pytest' from '/opt/freeware/lib/python3.7/site-packages/pytest/__init__.py'>
        warnings   = <module 'warnings' from '/opt/freeware/lib64/python3.7/warnings.py'>
```

#### Scipy/Numpy/Python version information:
```
Python 3.7.6
numpy  1.19.0
scipy  1.5.0  
```
It will give me the following output lines if I only run ```import numpy as np``` and ```np.test('full')```.  Not sure it is numpy issue or scipy issue.  Let me know if I should post it in numpy forum.
Thanks.
```
Traceback (most recent call last):
  File "numpy.py", line 1, in <module>
    import numpy as np
  File "/home/xzhang/python/numpy.py", line 2, in <module>
    np.test('full')
AttributeError: module 'numpy' has no attribute 'test'
```

**Comment by andyfaff** [comment]
This is a numpy issue.
