### ISSUE TITLE
pip install scipy==0.11.0 and python27 setup.py install both not work

### ISSUE THREAD

**Issue by rosegong-D** [scipy/scipy#12470]
I use two methods to install scipy, but none of them works, Can any one help
#### Reproducing code example:
one method 

```
D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\Scripts\scipy-0.11.0>python27 setup.py install
Forcing DISTUTILS_USE_SDK=1
Running from scipy source directory.
blas_opt_info:
blas_mkl_info:
D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py:538: UserWarning: Specified path u:\users\tky\mkllib is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py:538: UserWarning: Specified path u:\users\tky\mklinc is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib
  libraries ptf77blas,ptcblas,atlas not found in C:\
  libraries ptf77blas,ptcblas,atlas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\libs
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib
  libraries f77blas,cblas,atlas not found in C:\
  libraries f77blas,cblas,atlas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\libs
  NOT AVAILABLE

D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py:1425: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
blas_info:
  libraries blas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib
  libraries blas not found in C:\
  libraries blas not found in D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\libs
  NOT AVAILABLE

D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py:1434: UserWarning:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  warnings.warn(BlasNotFoundError.__doc__)
blas_src_info:
  NOT AVAILABLE

D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py:1437: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  warnings.warn(BlasSrcNotFoundError.__doc__)
Traceback (most recent call last):
  File "setup.py", line 208, in <module>
    setup_package()
  File "setup.py", line 199, in setup_package
    configuration=configuration )
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\core.py", line 152, in setup
    config = configuration()
  File "setup.py", line 136, in configuration
    config.add_subpackage('scipy')
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
    caller_level = 2)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
    caller_level = caller_level + 1)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy\setup.py", line 8, in configuration
    config.add_subpackage('integrate')
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
    caller_level = 2)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
    caller_level = caller_level + 1)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy\integrate\setup.py", line 10, in configuration
    blas_opt = get_info('blas_opt',notfound_action=2)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py", line 321, in get_info
    return cl().get_info(notfound_action)
  File "D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\lib\site-packages\numpy\distutils\system_info.py", line 472, in get_info
    raise self.notfounderror(self.notfounderror.__doc__)
numpy.distutils.system_info.BlasNotFoundError:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.

Another method use pip:
D:\softwareAq\SIMULIA\CAE\2019SE\win_b64\tools\SMApy\python2.7\Scripts>pip install scipy==0.11.0
Downloading/unpacking scipy==0.11.0
  Could not fetch URL https://pypi.python.org/simple/scipy/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Will skip URL https://pypi.python.org/simple/scipy/ when looking for download links for scipy==0.11.0
  Could not fetch URL https://pypi.python.org/simple/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Will skip URL https://pypi.python.org/simple/ when looking for download links for scipy==0.11.0
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/scipy/0.11.0: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Will skip URL https://pypi.python.org/simple/scipy/0.11.0 when looking for download links for scipy==0.11.0
  Could not fetch URL https://pypi.python.org/simple/scipy/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  Will skip URL https://pypi.python.org/simple/scipy/ when looking for download links for scipy==0.11.0
  Could not find any downloads that satisfy the requirement scipy==0.11.0
Cleaning up...
No distributions at all found for scipy==0.11.0
Storing debug log for failure in C:\Users\Lenovo\pip\pip.log

#### Scipy/Numpy/Python version information:
<I use python 2.7.3 ( which belong to Abqus, I can not update). numpy1.6.2. As the version is low, I want to install scipy 0.11.0.
-->

**Comment by pv** [comment]
Scipy 0.11.0 is 8 years old, and cannot be installed with pip.
You'll need to build from sources (hard) or use the old release files at https://sourceforge.net/projects/scipy/files/

**Comment by rosegong-D** [comment]
> Scipy 0.11.0 is 8 years old, and cannot be installed with pip on Windows.
> 
> You'll need to build from sources (hard) or use the old release files at https://sourceforge.net/projects/scipy/files/

Thanks, it seens complicated. The reason is the numpy in abaqus built in python is 1.6.2. If I install Scipy-0.18.1(which is the oldest version i can download for windows10),it tells me to use numpy >=1.7.1. But if I update the numpy in abaqus built in python, a problem will be raised. And  it makes me can not open abaqus. So I have to find lower versionof scipy which suits numpy 1.6.2; Do you know other version of numpy fits that?

**Comment by rosegong-D** [comment]
> Scipy 0.11.0 is 8 years old, and cannot be installed with pip on Windows.
> 
> You'll need to build from sources (hard) or use the old release files at https://sourceforge.net/projects/scipy/files/

Thanks for your support. I find scipy 0.16.2 is also suitable for numpy1.6.2. But I still cannot find this version for win64. Dose that mean I have to download zip or tar.gz and use commad python-X setup.py install? This version still can not use pip?
