### ISSUE TITLE
Build from source fails during cythonize

### ISSUE THREAD

**Issue by astromancer** [scipy/scipy#12496]
Building from source fails on current master. Stack trace below.

#### Reproducing code example:

```
sudo -H python3 setup.py build
```

#### Error message:

```
Cythonizing sources
Running scipy/special/_generate_pyx.py
Running scipy/linalg/_generate_pyx.py
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
Processing scipy/ndimage/src/_cytest.pyx
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/cluster/_optimal_leaf_ordering.pyx
Processing scipy/cluster/_hierarchy.pyx
Processing scipy/cluster/_vq.pyx
Processing scipy/special/_test_round.pyx
Processing scipy/special/_comb.pyx
Processing scipy/special/_ufuncs.pyx
Processing scipy/special/_ellip_harm_2.pyx
Processing scipy/special/_ufuncs_cxx.pyx
Processing scipy/special/cython_special.pyx
Processing scipy/_lib/_test_deprecation_call.pyx
Processing scipy/_lib/_ccallback_c.pyx
Processing scipy/_lib/_test_deprecation_def.pyx
Processing scipy/_lib/messagestream.pyx
Processing scipy/sparse/_csparsetools.pyx.in
Processing scipy/sparse/csgraph/_matching.pyx
warning: _cython_special_custom.pxi:9:8: Unreachable code
warning: _cython_special_custom.pxi:13:4: Unreachable code
warning: _cython_special_custom.pxi:21:8: Unreachable code
warning: _cython_special_custom.pxi:25:4: Unreachable code
warning: _cython_special_custom.pxi:33:8: Unreachable code
warning: _cython_special_custom.pxi:37:4: Unreachable code
warning: _cython_special_custom.pxi:45:8: Unreachable code
warning: _cython_special_custom.pxi:49:4: Unreachable code
Processing scipy/sparse/csgraph/_tools.pyx
Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
Processing scipy/sparse/csgraph/_reordering.pyx
Processing scipy/sparse/csgraph/_flow.pyx
Processing scipy/sparse/csgraph/_shortest_path.pyx
Processing scipy/sparse/csgraph/_traversal.pyx
Processing scipy/spatial/_hausdorff.pyx
Processing scipy/spatial/_voronoi.pyx
Processing scipy/spatial/qhull.pyx
Processing scipy/spatial/ckdtree.pyx
Processing scipy/spatial/transform/rotation.pyx
Processing scipy/io/matlab/mio_utils.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        if angles.ndim != 2 or angles.shape[-1] != num_axes:
            raise ValueError("Expected angles to have shape (num_rotations, "
                             "num_axes), got {}.".format(angles.shape))

        quat = _elementary_quat_compose(seq.encode(), angles, intrinsic)
        return cls(quat[0] if is_single else quat, normalize=False, copy=False)
                  ^
------------------------------------------------------------

rotation.pyx:988:19: Incompatible types in conditional expression (double[:]; double[:, :])
Processing scipy/io/matlab/streams.pyx
Processing scipy/io/matlab/mio5_utils.pyx
Processing scipy/optimize/_bglu_dense.pyx
Traceback (most recent call last):
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 305, in <module>
    main()
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 301, in main
    find_process_files(root_dir)
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 290, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 290, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 229, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/home/hannes/work/repos/scipy/tools/cythonize.py", line 94, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 590, in <module>
    setup_package()
  File "setup.py", line 574, in setup_package
    generate_cython()
  File "setup.py", line 334, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

```

#### Scipy/Numpy/Python version information:

python: 3.6.9
cython: 3.0a5
numpy: 1.20.0.dev0+2ccfd79
OS: ubuntu 18.04

**Comment by mckib2** [comment]
Hi @astromancer, Python 3.6 is now unsupported.  I tried building using Python 3.8 using Cython 3.0a5 and was unable to reproduce the error reported.  Is this still an issue or does upgrading to Python >3.6 resolve this issue?

**Comment by rgommers** [comment]
No reply, and I don't think this is still a problem. Thanks for the report @astromancer, and thanks for looking into it @mckib2!
