### ISSUE TITLE
LinearNDInterpolator raises ValueError when value array has writeable=False flag.

### ISSUE THREAD

**Issue by lhfriedman** [scipy/scipy#12499]
LinearNDInterpolator and CloughToucher2DInterppolator raise ValueError when value array has writeable=False flag. This is unanticipated and undocumented. Suggest that documentation or code should be changed. Given that they work with writeable
arrays, other bugs might result as well such as side-effects from code executed later on. 

#### Reproducing code example:
```
import numpy as np
from scipy.interpolate import LinearNDInterpolator, CloughTocher2DInterpolator

xs = np.arange(0, 4, dtype=float)
xs, ys = np.meshgrid(xs, xs)
values = np.ravel(xs + ys)
points = np.reshape([xs, ys], (2, -1)).T


print(70*'*')
print('LinearNDInterpolator')
interp_0 = LinearNDInterpolator(points, values)

print('interpolated values = :', interp_0(2, 2))
print('\nWith values.setflags(write=False), evaluation raises a ValueError')
values.setflags(write=False)
interp_1 = LinearNDInterpolator(points, values)
print('interpolated values = :', interp_1(2, 2))
```

#### Output and Error message:

```
**********************************************************************
LinearNDInterpolator
interpolated values = : 4.0

With values.setflags(write=False), evaluation raises a ValueError
********************************************************************** 

Traceback (most recent call last):

  File "<ipython-input-2-fd2384f87746>", line 19, in <module>
    print('interpolated values = :', interp_1(2, 2))

  File "interpnd.pyx", line 151, in scipy.interpolate.interpnd.NDInterpolatorBase.__call__

  File "interpnd.pyx", line 251, in scipy.interpolate.interpnd.LinearNDInterpolator._evaluate_double

  File "interpnd.pyx", line 259, in scipy.interpolate.interpnd.LinearNDInterpolator._do_evaluate

  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__

ValueError: buffer source array is read-only
```

#### Scipy/Numpy/Python version information:
 1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)

**Comment by lhfriedman** [comment]
A similar issue arises with CloughToucher2DInterpolator, but with instantiation:

```
import numpy as np
from scipy.interpolate import LinearNDInterpolator, CloughTocher2DInterpolator

print(70*'*')
print('CloughTocher2DInterpolator')
xs = np.arange(0, 4, dtype=float)
xs, ys = np.meshgrid(xs, xs)
values = np.ravel(xs + ys)
points = np.reshape([xs, ys], (2, -1)).T
interp_0 = CloughTocher2DInterpolator(points, values)
print('interpolated values = :', interp_0(2, 2))

print('\nWith values.setflags(write=False), instantiation raises a ValueError')
print(70*'*', '\n')

values.setflags(write=False)
interp_1 = CloughTocher2DInterpolator(points, values)
```

#### Output and Error message
```
**********************************************************************
CloughTocher2DInterpolator
interpolated values = : 4.0

With values.setflags(write=False), instantiation raises a ValueError
********************************************************************** 

Traceback (most recent call last):

  File "<ipython-input-1-95325d66f264>", line 17, in <module>
    interp_1 = CloughTocher2DInterpolator(points, values)

  File "interpnd.pyx", line 847, in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__

  File "interpnd.pyx", line 520, in scipy.interpolate.interpnd.estimate_gradients_2d_global

  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__

ValueError: buffer source array is read-only
```
