### ISSUE TITLE
eigh checks elements it won't beusing, and then aborts

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#12542]
This example should work correctly, and ignore the nan:

>>> import numpy as np
>>> from scipy.linalg import eigh
>>> A=np.array([[1,np.nan],[1,2]])
>>> B=np.eye(2)
>>> eigh(A,B,lower=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/scipy/linalg/decomp.py", line 374, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/usr/local/lib/python3.6/dist-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
    a = toarray(a)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by ilayn** [comment]
This is already mentioned in the docs. Currently there is no lower/upper distinction in the check_finite checks and all elements of the array are checked.

**Comment by keithbriggs** [comment]
Ok, thanks.

________________________________
