### ISSUE TITLE
signal.spectral._triage_segments doesn't support window as tuple with Nx parameter.

### ISSUE THREAD

**Issue by fireattack** [scipy/scipy#12544]
signal.spectral._triage_segments (called by various higher level functions, such as `scipy.signal.welch`) has an issue to deal with a tuple type input of window, such as `('hann', 1024)`, with or without additional `nperseg`.

According to the doc:
```
    Parameters
    ----------
    window : string, tuple, or ndarray
        If window is specified by a string or tuple and nperseg is not
        specified, nperseg is set to the default of 256 and returns a window of
        that length.
        If instead the window is array_like and nperseg is not specified, then
        nperseg is set to the length of the window. A ValueError is raised if
        the user supplies both an array_like window and a value for nperseg but
        nperseg does not equal the length of the window.
```

The expected behavior of something like signal.spectral._triage_segments(window=('hann', 1024), nperseg=None)` should be to generate a Hann window with Nx = 1024.

However, due to the way it codes:

https://github.com/scipy/scipy/blob/e777eb9e4a4cd9844629a3c37b3e94902328ad0b/scipy/signal/spectral.py#L1956-L1965

It will try to call `get_window(('hann', 1024), 256)` which gives the error of 

#### Reproducing code example:

```python
import numpy as np
from scipy import signal

np.random.seed(0)
time_step = .01
time_vec = np.arange(0, 70, time_step)
sig = np.sin(0.5 * np.pi * time_vec * (1 + .1 * time_vec))

freqs, psd = signal.welch(sig, window=('hann', 1024))

#### Error message:

```
Traceback (most recent call last):
  File "F:\sync\code\python\audio\_test.py", line 9, in <module>
    freqs, psd = signal.welch(sig, window=('hann', 1024))
  File "C:\Program Files\Python37\lib\site-packages\scipy\signal\spectral.py", line 452, in welch
    freqs, Pxx = csd(x, x, fs=fs, window=window, nperseg=nperseg,
  File "C:\Program Files\Python37\lib\site-packages\scipy\signal\spectral.py", line 584, in csd
    freqs, _, Pxy = _spectral_helper(x, y, fs, window, nperseg, noverlap, nfft,
  File "C:\Program Files\Python37\lib\site-packages\scipy\signal\spectral.py", line 1743, in _spectral_helper
    win, nperseg = _triage_segments(window, nperseg, input_length=x.shape[-1])
  File "C:\Program Files\Python37\lib\site-packages\scipy\signal\spectral.py", line 1968, in _triage_segments
    win = get_window(window, nperseg)
  File "C:\Program Files\Python37\lib\site-packages\scipy\signal\windows\windows.py", line 2124, in get_window
    return winfunc(*params)
TypeError: hann() takes from 1 to 2 positional arguments but 3 were given
```

#### Scipy/Numpy/Python version information:
<!-- You can simply run the following and paste the result in a code block
```
1.4.1 1.18.3 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)```
-->

**Comment by h-vetinari** [comment]
Needs to be re-milestoned

**Comment by DietBru** [comment]
After merging #22460, `_triage_segments` became became legacy function, since it  is only utilized by the legacy functions [stft] and [spectrogram]. Hence, it will not be updated anymore.

[stft]: https://scipy.github.io/devdocs/reference/generated/scipy.signal.stft.html
[spectrogram]: https://scipy.github.io/devdocs/reference/generated/scipy.signal.spectrogram.html
