### ISSUE TITLE
ImportError: cannot import name '_minimize_neldermead' from 'scipy.optimize.optimize'

### ISSUE THREAD

**Issue by jialesmu** [scipy/scipy#12598]
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/PJ1/package_loading.py", line 9, in <module>
    from scipy import optimize
  File "/Users/user/.conda/envs/PJ1/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 388, in <module>
    from ._minimize import *
  File "/Users/user/.conda/envs/PJ1/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 19, in <module>
    from .optimize import (_minimize_neldermead, _minimize_powell, _minimize_cg,
ImportError: cannot import name '_minimize_neldermead' from 'scipy.optimize.optimize' (/Users/user/.conda/envs/PJ1/lib/python3.8/site-packages/scipy/optimize/optimize.py)

First time facing this problem, I tried uninstall scipy and re-download it, it didn't work, also I check the version of scipy and up it to newest one also not work.

**Comment by rgommers** [comment]
`optimize.optimize` is now deprecated, and this was a private function. 

The action problem seems to be `from scipy import optimize` failing, indicating a corrupted install. So I'll close this issue, since there is nothing to fix.
