### ISSUE TITLE
Disable building numpy as dependency

### ISSUE THREAD

**Issue by adityaatluri** [scipy/scipy#12608]
Hi,
I am trying to build scipy from source. When I do `pip3 install .`, pip3 is building numpy from source even though there is numpy installed. The command emits:
```
error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/zlib/include -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DSCIPY_MKL_H -DHAVE_CBLAS -I/usr/local/include -I/Users/aditya/.local/Python3.10.0/include -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/umath -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/aditya/.local/Python3.10.0/include/python3.10 -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/common -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/common -Ibuild/src.macosx-10.14-x86_64-3.1/numpy/core/src/npymath -c numpy/core/src/multiarray/scalarapi.c -o build/temp.macosx-10.14-x86_64-3.10/numpy/core/src/multiarray/scalarapi.o -MMD -MF build/temp.macosx-10.14-x86_64-3.10/numpy/core/src/multiarray/scalarapi.o.d" failed with exit status 1
        ----------------------------------------
    ERROR: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-install-15w7cwis/numpy/setup.py'"'"'; __file__='"'"'/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-install-15w7cwis/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-record-fvibunjn/install-record.txt --single-version-externally-managed --prefix /private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-build-env-x0vdzcwx/overlay --compile --install-headers /private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-build-env-x0vdzcwx/overlay/include/python3.10/numpy Check the logs for full command output.
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 /Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-build-env-x0vdzcwx/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.18' 'numpy==1.14.5; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.3' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 /Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-build-env-hfvcyq24/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1' Check the logs for full command output.
```

But I can't find the numpy directory when the command exits

1. Is there a way to disable building numpy from scipy?
2. Is there a way to make scipy check for numpy already installed in pip and not build it from source?
3. How to preserve dependencies when building scipy?

**Comment by bashtage** [comment]
Use `--no-build-isolation` when installing from pip.

**Comment by adityaatluri** [comment]
Thank you for the response. But it didn't work 
```
    writing manifest file '/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-modern-metadata-oudt9rzg/scipy.egg-info/SOURCES.txt'
    creating '/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-modern-metadata-oudt9rzg/scipy.dist-info'
    error: invalid command 'bdist_wheel'
    Preparing wheel metadata ... error
ERROR: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 /Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/tmpn5vtbhdw Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 332, in run
    requirement_set = resolver.resolve(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 300, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 531, in prepare_editable_requirement
    abstract_dist = _get_prepared_distribution(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 550, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    return generate_metadata(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 36, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 176, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    self._subprocess_runner(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 270, in runner
    call_subprocess(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 /Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/tmpn5vtbhdw Check the logs for full command output.
Removed file:///Users/aditya/Code/github/src/scipy from build tracker '/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-req-tracker-y9ufaegu'
Removed build tracker: '/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-req-tracker-y9ufaegu'
```

**Comment by bashtage** [comment]
You need to pip install wheel before building with isolation.

**Comment by adityaatluri** [comment]
Did `pip3 install wheel`, got this:
```
    #### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall'] #######
    customize UnixCCompiler using build_clib
    CCompilerOpt.__init__[746] : load cache from file -> /Users/aditya/Code/github/src/scipy/build/temp.macosx-10.14-x86_64-3.10/ccompiler_opt_cache_clib.py
    CCompilerOpt.__init__[757] : hit the file cache
    building 'mach' library
    error: library mach has Fortran sources but no Fortran compiler found

    ########### CLIB COMPILER OPTIMIZATION ###########
    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3

    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   : none
    CCompilerOpt._cache_write[784] : write cache to path -> /Users/aditya/Code/github/src/scipy/build/temp.macosx-10.14-x86_64-3.10/ccompiler_opt_cache_clib.py
ERROR: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/aditya/Code/github/src/scipy/setup.py'"'"'; __file__='"'"'/Users/aditya/Code/github/src/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 398, in run
    installed = install_given_reqs(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 67, in install_given_reqs
    requirement.install(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 780, in install
    install_editable_legacy(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/operations/install/editable_legacy.py", line 49, in install_editable
    call_subprocess(
  File "/Users/aditya/.local/Python3.10.0/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/aditya/.local/Python3.10.0/bin/python3.10 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/aditya/Code/github/src/scipy/setup.py'"'"'; __file__='"'"'/Users/aditya/Code/github/src/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/private/var/folders/lr/0nwbv3tn4_38gjzn_wxk63jw0000gn/T/pip-req-tracker-9wt22l_4'
```

**Comment by ilayn** [comment]
Wait did Python 3.10 out already?

**Comment by rgommers** [comment]
> Wait did Python 3.10 out already?

No, still more than a year out, 3.10 is not even at alpha1 yet: https://www.python.org/dev/peps/pep-0619/. This will be just a master branch build.

**Comment by rgommers** [comment]
@adityaatluri this (`ERROR: Command errored out with exit status 1`) is not a useful traceback that tells you anything. Whenever you build from source and have an issue during the build phase, you need to add `-v` to your `pip` command for it to show you the actual build log. Can you try again?

**Comment by bashtage** [comment]
Pretty clear that problem is fortran compiler:

```
#### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall'] #######
    customize UnixCCompiler using build_clib
    CCompilerOpt.__init__[746] : load cache from file -> /Users/aditya/Code/github/src/scipy/build/temp.macosx-10.14-x86_64-3.10/ccompiler_opt_cache_clib.py
    CCompilerOpt.__init__[757] : hit the file cache
    building 'mach' library
    error: library mach has Fortran sources but no Fortran compiler found
```

**error: library mach has Fortran sources but no Fortran compiler found**

**Comment by rgommers** [comment]
oops, that's what I get by reading from the bottom. would be nice to move that `CLIB COMPILER OPTIMIZATION` output to be above the actual failure.

**Comment by adityaatluri** [comment]
> Pretty clear that problem is fortran compiler:
> 
> ```
> #### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall'] #######
>     customize UnixCCompiler using build_clib
>     CCompilerOpt.__init__[746] : load cache from file -> /Users/aditya/Code/github/src/scipy/build/temp.macosx-10.14-x86_64-3.10/ccompiler_opt_cache_clib.py
>     CCompilerOpt.__init__[757] : hit the file cache
>     building 'mach' library
>     error: library mach has Fortran sources but no Fortran compiler found
> ```
> 
> **error: library mach has Fortran sources but no Fortran compiler found**

I was hoping to skip using gfortran to build. But, I used gfortran from `brew cask install gfortran` and it re ran the build. It worked. I can successfully use scipy in python3.10.

Unfortunately, I can't use flang (fortran compiler from llvm), to build scipy. Does scipy plan to use flang as a compiler for building fortran files?

**Comment by rgommers** [comment]
> Unfortunately, I can't use flang (fortran compiler from llvm), to build scipy. Does scipy plan to use flang as a compiler for building fortran files?

If it works we'd like to support it, yes. It's still pretty new, I'm not sure if anyone has tried it yet.

**Comment by adityaatluri** [comment]
Sure. Thanks!
