### ISSUE TITLE
newton chokes when iteration steps outside function domain

### ISSUE THREAD

**Issue by astrojuanlu** [scipy/scipy#12625]
When finding the roots of scalar functions that are undefined in finite or infinite regions of the real line, the iteration might stop prematurely and fail to find a solution, even if it's trivial.

#### Reproducing code example:

```python
import numpy as np
from scipy.optimize import newton
def f(x):
    return np.log(x)
    
newton(f, 3)
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/py38/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 361, in newton
    raise RuntimeError(msg)
RuntimeError: Failed to converge after 50 iterations, value is nan.
```

#### Scipy/Numpy/Python version information:

1.5.2 1.18.2 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)

#### Extra information

I know the common wisdom: if one chooses a starting guess closer to the real solution, convergence is achieved:

```
In [6]: newton(f, 2)         
Out[6]: 1.0
```

However, MATLAB (tested with R2020a) manages to achieve convergence with initial guesses further away:

```matlab
>> fzero(@(x) log(x), 3)

ans =

     1

>> fzero(@(x) log(x), 10)

ans =

     1
```

MATLAB is not entirely smart though:

```matlab
>> fzero(@(x) log(x), 12)
Exiting fzero: aborting search for an interval containing a sign change
    because complex function value encountered during search.
(Function value at -3.36 is 1.2119+3.1416i.)
Check function or try again with a different starting value.

ans =

   NaN
```

However, GNU Octave (tested with 5.2.0) is capable of solving this with arbitrarily bad initial guesses!

```octave
>> fzero(@(x) log(x), 12)
ans =  1
>> fzero(@(x) log(x), 20)
ans =  1
>> fzero(@(x) log(x), 100)
ans =  1
>> fzero(@(x) log(x), 100000)
ans =  1
```

**Although understanding one's problem and looking for better initial guesses is always a good thing, I think it would be more user friendly to not fail when one step returns a non finite value.**

cc @alexs12 @martosc

**Comment by ilayn** [comment]
Matlab's problem is automatically overloading log function for complex case when real log fails (I've bitten by this so many times), hence that's a separate issue. 

Here the domain of the function is violated so it should step down as you proposed but should test for nonrealness not just infs (NaNs, complexes, etc. all should lead to a interval halving),
