### ISSUE TITLE
readsav MemoryError for files >100MB

### ISSUE THREAD

**Issue by paradesic** [scipy/scipy#12828]
When loading an IDL .sav file into Python using scipy.readsav(), anything over ~100 MB gives a memory error:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "c:/Users/User/viewer.py", line 293, in load_new_imdata
    image_data = readsav(imdata_file.name, python_dict=True, verbose=True)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\scipy\io\idl.py", line 818, in readsav
    r = _read_record(f)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\scipy\io\idl.py", line 356, in _read_record
    record['data'] = _read_structure(f, rectypedesc['array_desc'],
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\scipy\io\idl.py", line 256, in _read_structure
    structure[col['name']][i] = _read_array(f, dtype,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\scipy\io\idl.py", line 284, in _read_array
    array = np.frombuffer(f.read(array_desc['nbytes']),
MemoryError
```

**Comment by pv** [comment]
You can try using 64-bit Python (you appear have the 32-bit one installed). If the problem is with continuous address space availability rather than real memory usage, this probably fixes the issue. Otherwise, could you provide a >100MB file that you have problems with (maybe containing dummy data)?

**Comment by paradesic** [comment]
> You can try using 64-bit Python (you appear have the 32-bit one installed). If the problem is with continuous address space availability rather than real memory usage, this probably fixes the issue. Otherwise, could you provide a >100MB file that you have problems with (maybe containing dummy data)?

Thank you, this resolved it. I had issues running 64 bit python but now managed to solve them and try it out. readsav() is working perfectly with larger file sizes now, thanks.
