### ISSUE TITLE
BUG: ValueError upon calling Scipy Interpolator objects

### ISSUE THREAD

**Issue by Patol75** [scipy/scipy#12834]
This is similar to #12499, which was addressed in #12602. Despite the latter being merged in master, the code below still fails. Adding the keyword `const` to the relevant variables seem to solve the problem (see this [branch](https://github.com/Patol75/scipy/tree/InterpolatorValueErrorFix)).

#### Reproducing code example:

```
import numpy as np
import ray
from scipy.interpolate import (CloughTocher2DInterpolator,
                               LinearNDInterpolator)


@ray.remote
def reproduceBug(linearInterp, cloughInterp):
    linearValue = linearInterp((1, 2))
    cloughValue = cloughInterp((1, 2))
    return linearValue, cloughValue


xs = np.arange(0, 4, dtype=float)
xs, ys = np.meshgrid(xs, xs)
values = np.ravel(xs + ys)
points = np.reshape([xs, ys], (2, -1)).T
linear = LinearNDInterpolator(points, values)
cloToc = CloughTocher2DInterpolator(points, values)
ray.init()
linearID = ray.put(linear)
cloTocID = ray.put(cloToc)
print(ray.get(reproduceBug.remote(linearID, cloTocID)))
ray.shutdown()
```

#### Error message:

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    print(ray.get(reproduceBug.remote(linearID, cloTocID)))
  File "/home/thomas/.local/lib/python3.6/site-packages/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::__main__.reproduceBug() (pid=32281, ip=10.1.1.250)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "test.py", line 9, in reproduceBug
    linearValue = linearInterp((1, 2))
  File "interpnd.pyx", line 150, in scipy.interpolate.interpnd.NDInterpolatorBase.__call__
  File "interpnd.pyx", line 250, in scipy.interpolate.interpnd.LinearNDInterpolator._evaluate_double
  File "interpnd.pyx", line 258, in scipy.interpolate.interpnd.LinearNDInterpolator._do_evaluate
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

#### Scipy/Numpy/Python version information:

```
1.6.0.dev0+bbbd9a4 1.20.0.dev0+0518d92 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment]
@Patol75 Hi. If your branch already fixed the issue, I think your PR is welcome.

**Comment by tylerjereddy** [comment]
Fixed by gh-12867.
