### ISSUE TITLE
CI: Persistent Travis CI failure for test with PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#12912]
The Travis CI run named "Wheel, Optimised, GCC 4.8" is failing in all PRs.   The end of the log for that run in a recent PR is

```
$ if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
  python -u runtests.py -g -j2 -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD -- -rfEX --durations=10 $TEST_GROUP_ARGS 2>&1 | tee runtests.log
  tools/validate_runtests_log.py $TESTMODE < runtests.log
fi

Traceback (most recent call last):
  File "runtests.py", line 531, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 319, in main
    parallel=args.parallel)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/scipy/_lib/_testutils.py", line 67, in __call__
    code = pytest.main(pytest_args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1167, in _preparse
    self._consider_importhook(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1115, in _consider_importhook
    self._warn_about_missing_assertion(mode)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1498, in _warn_about_missing_assertion
    PytestConfigWarning(warning_text), stacklevel=3,
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1318, in issue_config_time_warning
    warnings.warn(warning, stacklevel=stacklevel)
pytest.PytestConfigWarning: assertions not in test modules or plugins will be ignored because assert statements are not executed by the underlying Python interpreter (are you using python -O?)
```
The relevant section of `.travis.yml` that configures this test run is

```
    - python: 3.6
      name: "Wheel, Optimised, GCC 4.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-4.8
            - gcc-4.8
      env:
        # GCC 4.8 is used by manylinux1 wheel builds
        - CC="gcc-4.8"
        - CXX="g++-4.8"
        - TESTMODE=fast
        - COVERAGE=
        - USE_WHEEL=1
        - NUMPYSPEC="numpy==1.16.5"
        # The following is needed for optimized "-OO" test run but since we use
        # pytest-xdist plugin for load scheduling its workers don't pick up the
        # flag. This environment variable starts all Py instances in -OO mode.
        - PYTHONOPTIMIZE=2
```

**Comment by WarrenWeckesser** [comment]
I can reproduce this locally with python 3.7 and pytest 6.1.0 with the commands

```
$ PYTHONOPTIMIZE=2 python setup.py install
$ PYTHONOPTIMIZE=2 python runtests.py -n -s stats
```
(I haven't tried this with Python 3.8--my 3.8 installation is broken at the moment.)

**Comment by ilayn** [comment]
Interesting. I can't see why this started to become an issue other than pytest changing its behavior on warnings. I will check the release notes of pytest. We can add this to pytest warning filters to silence it.

**Comment by WarrenWeckesser** [comment]
I created a PR to filter the pytest warning: https://github.com/scipy/scipy/pull/12913

**Comment by WarrenWeckesser** [comment]
Note that with the change in https://github.com/scipy/scipy/pull/12913, locally I get some failures in `scipy.stats` related to the `geninvgauss` distribution and the lack of docstrings, so I expect we'll see those in Travis CI, too.

**Comment by ilayn** [comment]
I've checked the pytest changes and I don't know which one is the responsible for it but there was some activity over warnings as per the first item here https://docs.pytest.org/en/stable/changelog.html#improvements

This warning is indeed the earliest warning that is emitted by the xdist workers and probably was being ignored until now.

**Comment by WarrenWeckesser** [comment]
This was fixed by https://github.com/scipy/scipy/pull/12913, so closing.
