### ISSUE TITLE
BUG: lint_diff.py still fails for backport PRs

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#13030]
Despite including gh-12974; see gh-13028: 

```
$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
   python tools/lint_diff.py --branch $TRAVIS_BRANCH
fi
fatal: ambiguous argument 'maintenance/1.5.x': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "tools/lint_diff.py", line 92, in <module>
    main()
  File "tools/lint_diff.py", line 83, in main
    branch_point = find_branch_point(args.branch)
  File "tools/lint_diff.py", line 44, in find_branch_point
    master_commits = set(rev_list(branch, 1000))
  File "tools/lint_diff.py", line 31, in rev_list
    res.check_returncode()
  File "/opt/python/3.6.7/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['git', 'rev-list', '--max-count', '1000', '--first-parent', 'maintenance/1.5.x']' returned non-zero exit status 128.
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
   python tools/lint_diff.py --branch $TRAVIS_BRANCH
fi
" exited with 1.
```

cc @peterbell10

**Comment by tylerjereddy** [comment]
I've pushed a small attempted fix into the backport PR for now; this almost certainly looks like an issue with Travis CI using shallow clones. If it works in the backport PR then I'll forward port the 1-liner.
