### ISSUE TITLE
BUG, DOC: refguide check is failing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#13111]
Likely because of gh-13109, an issue with refguide-check has snuck in to CI; see: https://github.com/scipy/scipy/pull/13110, where the refguide-check was reactivated in Azure and full log will be available for 10 days (I can reproduce locally on latest `master` as well)

A sample of the refguide failures:

```

File "doc/source/tutorial/csgraph.rst", line 47, in /home/vsts/work/1/s/tools/../doc/source/tutorial/csgraph.rst
Failed example:
    word_list = [word for word in word_list if len(word) == 3]
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest /home/vsts/work/1/s/tools/../doc/source/tutorial/csgraph.rst[2]>", line 1, in <module>
        word_list = [word for word in word_list if len(word) == 3]
    NameError: name 'word_list' is not defined

```

**Comment by peterbell10** [comment]
The failure isn't a change in the documentation (last commit was September 2019). The error is a missing file on the CI worker:
```
File "doc/source/tutorial/csgraph.rst", line 38, in /home/vsts/work/1/s/tools/../doc/source/tutorial/csgraph.rst
Failed example:
    word_list = open('/usr/share/dict/words').readlines()
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest /home/vsts/work/1/s/tools/../doc/source/tutorial/csgraph.rst[0]>", line 1, in <module>
        word_list = open('/usr/share/dict/words').readlines()
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dict/words'
```

**Comment by tylerjereddy** [comment]
ok, but note that I can reproduce locally; perhaps the error handling re: missing dependency or something could be a bit more clear
