### ISSUE TITLE
integer overflow error in scipy.sparse.csgraph.connected_components

### ISSUE THREAD

**Issue by gplepage** [scipy/scipy#13135]
The code below is crashing because matrix ``m`` has more than ``2**31`` elements. A possible explanation:  Index ``nnz`` in the ``scipy`` routine wants to be as large ``N**2``, which is just a bit larger than ``2**31``. if ``nnz`` is an ``int32``,  it will be negative (integer overflow). My code runs fine with ``N=46000`` instead of ``47000``, because ``N**2`` is then less than ``2**31``. 

You probably want 64GB of RAM to run these examples. Run time is a few minutes on a MacBook Pro. (The same behavior was seen on the Darwin supercomputer at Cambridge, so this is not a MacBook Pro issue.) My version of ``scipy`` (1.5.2) is not completely up-to-date but I couldn't see anything in the release notes for subsequent versions that addressed this.

#### Reproducing code example:

```
import numpy as np 
import scipy 

N = 47000 
m = np.array(N * [ N * [True]])
scipy.sparse.csgraph.connected_components(m, directed=False)
```

#### Error message:

```
Traceback (most recent call last):
  File "/Users/gpl/software/python/corrfitter/tmp/abc.py", line 49, in <module>
    main()
  File "/Users/gpl/software/python/corrfitter/tmp/abc.py", line 11, in main
    scipy.sparse.csgraph.connected_components(m, directed=False)
  File "_traversal.pyx", line 110, in scipy.sparse.csgraph._traversal.connected_components
  File "/Users/gpl/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/csc.py", line 141, in tocsr
    indices = np.empty(self.nnz, dtype=idx_dtype)
ValueError: negative dimensions are not allowed
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment]
This appears to be the same issue as gh-13155.
