### ISSUE TITLE
Unexpected ValueError: `x0` violates bound constraints

### ISSUE THREAD

**Issue by JoanPuig** [scipy/scipy#13277]
Optimization problem with feasible x0 errors with: Unexpected ValueError: `x0` violates bound constraints

This issue is similar to: https://github.com/scipy/scipy/pull/13041/files, I applied the code changes from it, but it doesn't seem to solve the issue.

#### Reproducing code example:
```
from scipy.optimize import minimize
import numpy as np


def deviation_from_target(mix_ratio):
    value = np.sum(np.append(mix_ratio, 1.0 - sum(mix_ratio)) * [306.6, 20.7])

    target_value = 59.5

    deviation = ((value - target_value) / target_value)

    return deviation


minimize(deviation_from_target,
         x0=[0.5],
         bounds=[(0.1, 1.0)],
         constraints={'type': 'ineq', 'fun': lambda x: (1.0 - sum(x))},
         )
```

```
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\203.5981.165\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\...\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\203.5981.165\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/PyNPM/scr_sym.py", line 48, in <module>
    minimize(deviation_from_target,
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\_minimize.py", line 625, in minimize
    return _minimize_slsqp(fun, x0, args, jac, bounds,
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\slsqp.py", line 426, in _minimize_slsqp
    g = append(sf.grad(x), 0.0)
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 188, in grad
    self._update_grad()
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 171, in _update_grad
    self._update_grad_impl()
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 91, in update_grad
    self.g = approx_derivative(fun_wrapped, self.x, f0=self.f,
  File "C:\Users\...\Anaconda3\envs\py39\lib\site-packages\scipy\optimize\_numdiff.py", line 391, in approx_derivative
    raise ValueError("`x0` violates bound constraints.")
ValueError: `x0` violates bound constraints.
```

#### Scipy/Numpy/Python version information:
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.2 1.19.4 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)

**Comment by JoanPuig** [comment]
@andyfaff since you solved https://github.com/scipy/scipy/issues/11403 you might have some insights on what is going on. Thanks

**Comment by andyfaff** [comment]
This will be fixed in the master branch, and will be in the next scipy release, which won't be too long now. You will still get a warning in 1.6 though:

```
/Users/andrew/Documents/Andy/programming/scipy/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
```

The fix was made in https://github.com/scipy/scipy/pull/13009. There are more details there on why the problem originated.

**Comment by JoanPuig** [comment]
Thanks!
