### ISSUE TITLE
fftn crashes if shape arguments are supplied as ndarrays

### ISSUE THREAD

**Issue by DavidStirling** [scipy/scipy#13342]
My issue is about `scipy.fftpack`. It appears that the fftpack helper function `_good_shape` was added to check `shape` arguments supplied to `fftn` and other functions. The documentation for `fft2` and `fftn` suggests that `shape` can be supplied as an `int` or `array_like`, but the `_good_shape` function crashes if an ndarray is supplied. 

As far as I can tell older versions had no trouble with shape being passed in as an array.

#### Reproducing code example:
```
import numpy as np
from scipy.fftpack import fft2
y = np.mgrid[:5, :5][0]

# Works
fft2(y, shape=[5,5])

# Triggers an error
fft2(y, shape=np.array([5,5]))
```

#### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\scipy\fftpack\basic.py", line 384, in fft2
    return fftn(x,shape,axes,overwrite_x)
  File "C:\Program Files\Python38\lib\site-packages\scipy\fftpack\basic.py", line 336, in fftn
    shape = _good_shape(x, shape, axes)
  File "C:\Program Files\Python38\lib\site-packages\scipy\fftpack\helper.py", line 106, in _good_shape
    if shape and not axes:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.3 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)```

**Comment by DavidStirling** [comment]
Not sure if the fix would be to change `helper.py L106` to `if shape is not None and not axes:`?
