### ISSUE TITLE
PipEnv installation fails on MacOs with python 3.9

### ISSUE THREAD

**Issue by dplepage** [scipy/scipy#13361]
Scipy's pyproject.toml [explicitly requires numpy==1.19.3](https://github.com/scipy/scipy/blob/ab1c0907fe9255582397db04592d6066745018d3/pyproject.toml#L8), but numpy 1.19.3 doesn't build on MacOs (numpy/numpy#17987).

This means that even if you've pegged your local numpy as numpy==1.20.0rc2 (the recommended workaround for numpy/numpy#17987), pipenv can't build scipy (because it builds it in an isolated environment defined by pyproject.toml)

Full output:

<details>

```sh
~/tmp ❯❯❯ cd test
~/tmp/test ❯❯❯ pipenv install scipy
Creating a virtualenv for this project...
Pipfile: /Users/dplepage/tmp/test/Pipfile
Using /usr/local/bin/python3 (3.9.1) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.9.1.final.0-64 in 432ms
  creator CPython3Posix(dest=/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/dplepage/Library/Application Support/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp
Creating a Pipfile for this project...
Installing scipy...
Adding scipy to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/bin/python /Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-aucigwyh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.16.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'pybind11>=2.4.3'
     cwd: None
Complete output (232 lines):
Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools<=51.0.0
  Using cached setuptools-51.0.0-py3-none-any.whl (785 kB)
Collecting Cython>=0.29.18
  Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
Collecting numpy==1.19.3
  Using cached numpy-1.19.3.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/bin/python /Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/tmprfi4lwe2
         cwd: /private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy
    Complete output (209 lines):
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/_common.pyx
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    accelerate_info:
      libraries accelerate not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
    Library accelerate was not found. Ignoring
      libraries veclib not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
    Library veclib was not found. Ignoring
      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['/Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries tatlas,tatlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries satlas,satlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries ptf77blas,ptcblas,atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries f77blas,cblas,atlas not found in /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

    /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-11-x86_64-3.9
    creating build/src.macosx-11-x86_64-3.9/numpy
    creating build/src.macosx-11-x86_64-3.9/numpy/distutils
    building library "npymath" sources
    Traceback (most recent call last):
      File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-i976zski/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-i976zski/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-i976zski/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 500, in setup_package
        setup(**metadata)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-i976zski/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-i976zski/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/egg_info.py", line 24, in run
        self.run_command("build_src")
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
        self.build_library_sources(*libname_info)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 658, in get_mathlib_info
        st = config_cmd.try_link('int main(void) { return 0;}')
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/config.py", line 241, in try_link
        self._check_compiler()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/command/config.py", line 80, in _check_compiler
        self.fcompiler = new_fcompiler(compiler=self.fcompiler,
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
        compiler = get_default_fcompiler(plat, requiref90=requiref90,
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
        compiler_type =  _find_existing_fcompiler(matching_compiler_types,
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
        c.customize(dist)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/__init__.py", line 526, in customize
        linker_so_flags = self.flag_vars.linker_so
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
        return self._get_var(name, conf_desc)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
        var = self._hook_handler(name, hook)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
        return hook()
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/gnu.py", line 346, in get_flags_linker_so
        flags = GnuFCompiler.get_flags_linker_so(self)
      File "/private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-install-mqo0__b4/numpy/numpy/distutils/fcompiler/gnu.py", line 136, in get_flags_linker_so
        os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
        value = self.encodevalue(value)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
        raise TypeError("str expected, not %s" % type(value).__name__)
    TypeError: str expected, not int
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/bin/python /Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/tmprfi4lwe2 Check the logs for full command output.
----------------------------------------
Traceback (most recent call last):
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/build_env.py", line 202, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/dplepage/.local/share/virtualenvs/test-iD9QGKrp/bin/python /Users/dplepage/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/qs/bmrclsp928b57m4yp_1p65940000gn/T/pip-build-env-aucigwyh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.16.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'pybind11>=2.4.3' Check the logs for full command output.
```

</details>

**Comment by rgommers** [comment]
Ah sorry, missed this issue - I only got a notification for your comment on the commit. 

The workaround right now is to install a numpy release candidate with a fix first (see https://github.com/numpy/numpy/issues/17987#issuecomment-752023228), and then install scipy in a separate step. You can use the `--no-build-isolation` option to `pip install` (which I assume `pipenv` supports) to use the already-installed numpy.

For how to fix in scipy I just opened gh-13363. I'll leave this issue open as well, because other users may be looking for the same workaround.

**Comment by rgommers** [comment]
@dplepage why do you need to build from source? Maybe just upgrading `pip` will fix it - IIRC there was an issue with wheel tags, but latest `pip` should be able to install the `x86_64` numpy wheels on macOS 11.

**Comment by rgommers** [comment]
It seems like it's just `pipenv` getting this wrong. Maybe it's bundling a too old pip version.

**Comment by rgommers** [comment]
Ah, see gh-13102. Just download a recent SciPy wheel and rename it from `10_9` to `11_0`.

**Comment by rgommers** [comment]
https://github.com/scipy/scipy/issues/13102#issuecomment-751351981 says updating to `pip 20.3.3` fixes things, that can install wheels with `10_9` tags. The build log here is for `pip` 20.3.1`. 

If you could confirm that works @dplepage, that'd be very useful.

**Comment by rgommers** [comment]
Added a release note about the minimum required pip version in gh-13518. Nothing else to do, so closing.
