### ISSUE TITLE
python runtest.py -t path-to-test.py failed

### ISSUE THREAD

**Issue by V0lantis** [scipy/scipy#13440]
My issue is about running specific test in my development environnement.

#### Reproducing code example:

I use the command described in the [doc](http://scipy.github.io/devdocs/dev/contributor/runtests.html#runtests) : 
`python runtests.py -v -t scipy/optimize/tests/test_linprog.py::test_unknown_solver --no-build`

#### Error message:

```
=================================================================== test session starts ====================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /workspaces/scipy, configfile: pytest.ini
collected 0 items                                                                                                                                          

================================================================== no tests ran in 0.09s ===================================================================
ERROR: module or package not found: scipy/optimize/tests/test_linprog.py::test_unknown_solver (missing __init__.py?)
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.7.0.dev0+a274d79 1.19.5 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

#### OS:
Working with docker with the following Dockerfile:
```Dockerfile
# ubuntu focal has python 3.8 as default
FROM ubuntu:focal

# add deadsnakes ppa to install python 3.7
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y \
	python3.7 \
	python3.7-dev \
	python3-pip git \
	build-essential \
	vim \
	libatlas-base-dev \
	gfortran \
	libgfortran4 \
	liblapack-dev \
	curl \
	libgmp-dev \
	libmpfr-dev \
	libsuitesparse-dev \
	libmpc-dev

# setup pips, pip3.7 and pip3.8
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.7 get-pip.py && python3.8 get-pip.py && rm get-pip.py
```

**Comment by ilayn** [comment]
`::test_unknown_solver` is not an actual test because apparently it has been renamed

https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test_linprog.py#L232

It is just an example anyways so feel free to pickup any other test.

**Comment by WarrenWeckesser** [comment]
It looks like there is a mistake in those docs.  The argument to the `-t` option should be a Python name (i.e. a dotted Python module path), not a file path.  And as @ilayn pointed out, the test that you were trying to run no longer exists.

This works for me:
```
$  python runtests.py -v -n -t scipy.optimize.tests.test_linprog::test_unknown_solvers_and_options
============================================================= test session starts =============================================================
platform darwin -- Python 3.7.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /Users/warren/mc37allpip/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/warren/repos/git/forks/scipy/build/test/.hypothesis/examples')
rootdir: /Users/warren/repos/git/forks/scipy, configfile: pytest.ini
plugins: hypothesis-5.16.1, forked-1.1.3, xdist-1.32.0
collected 1 item                                                                                                                              

../../::test_unknown_solvers_and_options PASSED                                                                                         [100%]

============================================================== 1 passed in 0.15s ==============================================================
```

**Comment by mdhaber** [comment]
> It looks like there is a mistake in those docs

File paths work, although it's nice to know that Python name works.

**Comment by WarrenWeckesser** [comment]
Ah, I see what happened (to me, anyway--I'm not sure this helps @V0lantis).  My attempt to use file paths failed because I used `-n`, and I am not using an in-place build (i.e. I first ran `python setup.py install`).  To use `-t` with a file path, I would need to give the path to the *installed* file, which is in the site-packages/scipy directory of the current Python installation.

So one can use file paths or Python names.  (I don't see a reason to prefer either one, except perhaps for the case that I ran into.)

**Comment by V0lantis** [comment]
Thank you so much guys ! 
Indeed, the issue was laying with the file path. just did : `python runtests.py -v -n -t scipy.optimize.tests.test_linprog::test_unknown_solvers_and_options` and it worked perfectly. 
I didn't try with true path although, because I installed scipy on a ubuntu docker container. 
Is it a doc issue? If so, I can correct the doc if you want

**Comment by mdhaber** [comment]
Yes, it's just a doc issue. A PR would be welcome. Please just change the test from `test_unknown_solvers` to `test_unknown_solvers_and_options`. Thanks!

**Comment by ilayn** [comment]
we should probably leave the test name as a placeholder to avoid such issues:

```bash
python runtests.py -v -n -t scipy.<module>.tests.<test_file>::<test_name>
```

or something like that because that is really a specific use and only those who need it would actually do it.

**Comment by mdhaber** [comment]
> we should probably leave the test name as a placeholder

The other opinion is that we should have something that runs as shown.  Assuming that what is shown should run (which was not true here),  the user can then tell if there's something wrong. We can write a note in that test reminding us not to change the name again, if that helps.

@V0lantis, which would you prefer?

**Comment by V0lantis** [comment]
I can do all the three suggestions, which are : 

- Put test name as placeholder `python runtests.py -v -n -t scipy.<module>.tests.<test_file>::<test_name>`
- Put an example with a working test (i.e. `python runtests.py -v -n -t scipy.optimize.tests.test_linprog::test_unknown_solvers_and_options`)
- Write a note in test_unknown_solvers_and_options reminding us not the change name again

Is that fine for you?

**Comment by mdhaber** [comment]
Yes, sounds good. 

Was the python name required for you, though, or does the path work as long as the name is correct? 

An advantage of path is that it can be copy-pasted if, for example, the user has already browsed to the location of the file in the terminal or some other program (as one does to edit the file). Not a big advantage, but if there's no other reason to change what's there, it may be enough of an advantage to leave that part alone.

**Comment by V0lantis** [comment]
No unfortunately, it does not work with the path even if the path is correct : 
```bash
python runtests.py -v -n -t scipy/optimize/tests/test_linprog.py::test_unknown_solvers_and_options
====================================================================================== test session starts ======================================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /workspaces/scipy, configfile: pytest.ini
collected 0 items                                                                                                                                                                               

===================================================================================== no tests ran in 0.11s =====================================================================================
ERROR: module or package not found: scipy/optimize/tests/test_linprog.py::test_unknown_solvers_and_options (missing __init__.py?)
```

**Comment by mdhaber** [comment]
Interesting. I guess it doesn't work with the -n option. It's fine without it on my machine.

**Comment by WarrenWeckesser** [comment]
It works with the file path and `-n`, but if you haven't done an in-place build, you have to specify the absolute path to the *installed* scipy package, e.g. something like `-t <path-to-python-installation>/lib/python3.8/site-packages/<path-to-scipy-test-file>`

**Comment by mdhaber** [comment]
I always use in-place build.  I get:
```
(scipydev) C:\Users\matth\scipy>python runtests.py -v -n -t scipy.optimize.tests.test_linprog.py
================================================= test session starts =================================================
platform win32 -- Python 3.7.9, pytest-6.1.2, py-1.10.0, pluggy-0.13.1 -- C:\Users\matth\Anaconda3\envs\scipydev\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\matth\scipy, configfile: pytest.ini
collected 0 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 257, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 312, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 323, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 607, in perform_collect
INTERNALERROR>     as_pypath=self.config.option.pyargs,
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 851, in resolve_collection_argument
INTERNALERROR>     strpath = search_pypath(strpath)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\main.py", line 810, in search_pypath
INTERNALERROR>     spec = importlib.util.find_spec(module_name)
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\importlib\util.py", line 94, in find_spec
INTERNALERROR>     parent = __import__(parent_name, fromlist=['__path__'])
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\assertion\rewrite.py", line 171, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "C:\Users\matth\scipy\scipy\optimize\tests\test_linprog.py", line 1712, in <module>
INTERNALERROR>     class TestLinprogIPSparse(LinprogIPTests):
INTERNALERROR>   File "C:\Users\matth\scipy\scipy\optimize\tests\test_linprog.py", line 1715, in TestLinprogIPSparse
INTERNALERROR>     @pytest.mark.xfail_on_32bit("This test is sensitive to machine epsilon level "
INTERNALERROR>   File "C:\Users\matth\Anaconda3\envs\scipydev\lib\site-packages\_pytest\mark\structures.py", line 521, in __getattr__
INTERNALERROR>     2,
INTERNALERROR> pytest.PytestUnknownMarkWarning: Unknown pytest.mark.xfail_on_32bit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html

================================================ no tests ran in 0.59s ================================================
```

**Comment by WarrenWeckesser** [comment]
When you use a dotted Python name, don't include `.py` at the end.  The argument is interpreted as a Python module, not a filename.

**Comment by mdhaber** [comment]
Of course. OK, I like this!  I've never been able to do no-build tests before. This will save some time.
