### ISSUE TITLE
TST: stats: test distribution `support` method behavior for array input

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#13504]
**Is your feature request related to a problem? Please describe.**
Before gh-13295, the [`support`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.support.html#scipy.stats.rv_continuous.support) method of stats distributions stated that it would accept array inputs and return floats. I think it was only meant to support float inputs.

```
>>> import numpy as np
>>> from scipy.stats import binom
>>> binom.support(10, 0.5)
(0, 10)
>>> binom.support([10, 12], 0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\matth\scipy\scipy\stats\_distn_infrastructure.py", line 1430, in support
    return _a * scale + loc, _b * scale + loc
TypeError: can only concatenate list (not "int") to list
>>> binom.support(np.array([10, 20]), 0.5)
(0, array([10, 20]))
>>> binom.support(10, [0.5, 0.6])
(0, 10)
```

gh-13295 fixed this (unintentionally, I think). After that, array inputs seem to work fine.
```
>>> binom.support(10, 0.5)
(0, 10)
>>> binom.support([10, 12], 0.5)
(array([0, 0]), array([10, 12]))
>>> binom.support(np.array([10, 20]), 0.5)
(array([0, 0]), array([10, 20]))
>>> binom.support(10, [0.5, 0.6])
(array([0, 0]), array([10, 10]))
```

But because the problem was not detected before, it seems there is not a sufficiently strong test for the `support` method with array inputs.

**Describe the solution you'd like**
Add tests for distribution `support` (and possibly other) method(s) with array inputs.

**Comment by mdhaber** [comment]
We'll address this as part of gh-15928.
