### ISSUE TITLE
minimize using Powell methods with Bounds leads to  "TypeError: only integer scalar arrays can be converted to a scalar index"

### ISSUE THREAD

**Issue by bertrandhaut** [scipy/scipy#13501]
The following minimal optimize problem leads to the following exception: 
```
TypeError: only integer scalar arrays can be converted to a scalar index
```

#### Reproducing code example:
```
import numpy as np
from scipy.optimize import minimize, Bounds

def f(x):
    return x

bounds = Bounds(lb=[0., 0.],
                ub=[1., 1.])

minimize(f, x0=np.array([0,0]), method='Powell', bounds=bounds)
```

#### Error message:

```
Traceback (most recent call last):
  File "C:/Users/DEK328/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/bug_scipy.py", line 17, in <module>
    minimize(f, x0=np.array([0,0]), method='Powell', bounds=bounds)
  File "C:\Users\DEK328\Anaconda3\envs\vibration\lib\site-packages\scipy\optimize\_minimize.py", line 608, in minimize
    return _minimize_powell(fun, x0, args, callback, bounds, **options)
  File "C:\Users\DEK328\Anaconda3\envs\vibration\lib\site-packages\scipy\optimize\optimize.py", line 2932, in _minimize_powell
    fval, x, direc1 = _linesearch_powell(func, x, direc1,
  File "C:\Users\DEK328\Anaconda3\envs\vibration\lib\site-packages\scipy\optimize\optimize.py", line 2667, in _linesearch_powell
    bound = _line_for_search(p, xi, lower_bound, upper_bound)
  File "C:\Users\DEK328\Anaconda3\envs\vibration\lib\site-packages\scipy\optimize\optimize.py", line 2610, in _line_for_search
    lower_bound, upper_bound = lower_bound[nonzero], upper_bound[nonzero]
TypeError: only integer scalar arrays can be converted to a scalar index
```

The issue is that lower_bound is a list and not an np.array. It cannot be indexed by nonzero which is np.array[int64]

lower_bound  is derived from the Bounds object that I've defined by passing lists (and not np.array) for the lb & ub arguments. 

According to the doc of Bounds, this should be good (at least under my understanding of the "array_like" wording).
    lb, ub : array_like, optional

I would suggest to modify the constructor of Bounds to something like
```
    def __init__(self, lb, ub, keep_feasible=False):
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.keep_feasible = keep_feasible
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Indeed, good catch. The other methods which convert bounds from old to new return `np.array`. And this case is not in the tests. Do you want to make a PR? I can propose to do it otherwise.

**Comment by andyfaff** [comment]
#13502
