### ISSUE TITLE
BUG: Doc's build failed in CI

### ISSUE THREAD

**Issue by V0lantis** [scipy/scipy#13525]
My issue is about the doc's failure in Continuous Integration workflow. 
For examples see : 
gh-13354 [doc failed link](https://app.circleci.com/pipelines/github/scipy/scipy/5391/workflows/fefa97cf-7591-4b33-ba03-b572dd4c11dc/jobs/26286)
gh-13519 [doc failed link]()

Here is what I found so far : 
The bug is related to the `build_docs`'s job inside `.circleci/config.yml` file (line 68).
The job execute the following command : 

```sh
. venv/bin/activate
export SHELL=$(which bash)
python -u runtests.py -g -j2 --doc html-scipyorg --doc latex
make -C doc/build/latex all-pdf LATEXOPTS="-file-line-error -halt-on-error"
cp -f doc/build/latex/scipy-ref.pdf doc/build/html-scipyorg/
```

but the build failed at line `python -u runtests.py -g -j2 --doc html-scipyorg --doc latex`.
the shell command build the scipy from source and then wait for workers to build the doc. What is suspicious though is the delay before workers start (around 5 minutes). But I understood that we are just calling 2 workers (`-j2` options). Removing the workers or adding more doesn't seem to change anything (or it is not visible).

To build the doc, `runtest.py` call `make html-scipyorg`. This is where it failed exactly according to the log, line 127 : 
```Makefile
html-scipyorg:
	mkdir -p build/html build/doctrees
	$(SPHINXBUILD) -WT --keep-going -t scipyorg $(VERSIONWARNING) -b html $(ALLSPHINXOPTS) build/html-scipyorg $(FILES)
	@echo
	@echo "Build finished. The HTML pages are in build/html-scipyorg."
```

#### Reproducing code example:
While writing this issue, I have tested on my computer multiple time, and I have reached a point where I cannot reproduce the error 🤷‍♂️

You will need to have Docker installed. Caution, after building, the image weight around 3GigaBytes.
Create a Dockerfiles inside your working directory : 
```yml
FROM python:3.7.0

WORKDIR /workspace

ARG GIT_USER
ARG GIT_TOKEN

RUN apt-get -y update \
    && apt-get -y install libatlas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libfreetype6-dev \
    libpng-dev zlib1g zlib1g-dev texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra \
    texlive-generic-extra latexmk texlive-xetex fonts-freefont-otf git

RUN git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/scipy/scipy.git \
    && cd scipy && git submodule init && git submodule update

WORKDIR scipy

# setup Python venv
RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install --install-option="--no-cython-compile" cython \
    && pip install numpy \
    && pip install nose mpmath argparse Pillow codecov matplotlib "Sphinx!=3.1.0" asv \
    && pip install pybind11
```

To build the image, execute the following (replace `github_username` and `your_github_token` by your data : 
`docker build --build-arg GIT_USER=<github_username> --build-arg GIT_TOKEN=<your_github_token> -t test-scipy-doc-build .`

When the image has built execute the following to test the building of the doc : 
`docker run -it test-scipy-doc-build bash`

And then inside your container : 
```sh
. venv/bin/activate
export SHELL=$(which bash)
python -u runtests.py -v -g -j2 --doc html-scipyorg --doc latex
```
#### Error message:

<img width="1229" alt="Capture d’écran 2021-02-07 à 12 18 04" src="https://user-images.githubusercontent.com/37664438/107144922-9c885000-693e-11eb-9a44-bc4e819836c0.png">
<img width="1225" alt="Capture d’écran 2021-02-07 à 12 18 14" src="https://user-images.githubusercontent.com/37664438/107144923-9db97d00-693e-11eb-850d-5712f016f769.png">

<details>

```bash
(venv) root@44f6a6fa080a:/workspace# python -u runtests.py -g -j2 --doc html-scipyorg --doc latex

Building, see build.log...

Build OK (0:00:10.528631 elapsed)

make: Entering directory '/workspace/doc'

mkdir -p build/html build/doctrees

LANG=C "/workspace/venv/bin/python" -msphinx -WT --keep-going -t scipyorg -b html -d build/doctrees "-j2" source build/html-scipyorg

Running Sphinx v3.4.3

Matplotlib is building the font cache; this may take a moment.

SciPy (VERSION 1.7.0.dev0+f6762e4)

making output directory... done

[autosummary] generating autosummary for: api.rst, ccallback.rst, cluster.hierarchy.rst, cluster.rst, cluster.vq.rst, constants.rst, fft.rst, fftpack.rst, hacking.rst, index.rst, ..., sparse.rst, spatial.distance.rst, spatial.rst, spatial.transform.rst, special.cython_special.rst, special.rst, stats.mstats.rst, stats.qmc.rst, stats.rst, toolchain.rst

[autosummary] generating autosummary for: /workspace/doc/source/generated/scipy.LowLevelCallable.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.DisjointSet.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.average.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.centroid.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.complete.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.cophenet.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.correspond.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.cut_tree.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.dendrogram.rst, ..., /workspace/doc/source/generated/scipy.stats.wrapcauchy.rst, /workspace/doc/source/generated/scipy.stats.yeojohnson.rst, /workspace/doc/source/generated/scipy.stats.yeojohnson_llf.rst, /workspace/doc/source/generated/scipy.stats.yeojohnson_normmax.rst, /workspace/doc/source/generated/scipy.stats.yeojohnson_normplot.rst, /workspace/doc/source/generated/scipy.stats.yulesimon.rst, /workspace/doc/source/generated/scipy.stats.zipf.rst, /workspace/doc/source/generated/scipy.stats.zipfian.rst, /workspace/doc/source/generated/scipy.stats.zmap.rst, /workspace/doc/source/generated/scipy.stats.zscore.rst

[autosummary] generating autosummary for: /workspace/doc/source/generated/scipy.LowLevelCallable.__getitem__.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.__len__.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.__mul__.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.count.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.from_cython.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.function.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.index.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.signature.rst, /workspace/doc/source/generated/scipy.LowLevelCallable.user_data.rst, /workspace/doc/source/generated/scipy.cluster.hierarchy.ClusterNode.get_count.rst, ..., /workspace/doc/source/generated/scipy.stats.rv_histogram.nnlf.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.pdf.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.ppf.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.random_state.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.rvs.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.sf.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.stats.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.std.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.support.rst, /workspace/doc/source/generated/scipy.stats.rv_histogram.var.rst

loading intersphinx inventory from https://docs.python.org/dev/objects.inv...

loading intersphinx inventory from https://numpy.org/devdocs

/objects.inv..

.

loading intersphinx inventory from https://matplotlib.org/objects.inv...

loading intersphinx inventory from https://asv.readthedocs.io/en/stable/objects.inv...

building [mo]: targets for 0 po files that are out of date

building [html]: targets for 291 source files that are out of date

updating environment: [new config] 3584 added, 0 changed, 0 removed

reading sources... [100%] stats .. tutorial/stats/discrete_zipfian

waiting for workers...

/workspace/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr.rst:10: WARNING: autosummary: stub file not found 'scipy.odr.odr'. Check your autosummary_generate setting.

looking for now-outdated files... none found

pickling environment... done

checking consistency... done

preparing documents... done

writing output... [ 26%] generated/scipy.linalg.interpolative.reconstruct_skel_matrix .. generated/scipy.linat_matrix_from_id

docstring of _odrpack.odr:16: WARNING: py:obj reference target not found: ODRed/scipy.optimize.LinearConstraint

docstring of _odrpack.odr:28: WARNING: py:obj reference target not found: ODR

/workspace/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr:29:<autosummary>:1: WARNING: py:obj reference target not found: scipy.odr.ODR

release/1.6.0-notes.rst:47: WARNING: py:obj reference target not found: scipy.odr.ODR9;00m


waiting for workers...

generating indices... genindex py-modindex done

writing additional pages... search done

copying images... [ 3%] generated/../../build/plot_directive/generated/scipy-integrate-solve_bvp-1_00_00.png

copying images... [ 10%] generated/../../build/plot_directive/generated/scipy-misc-electrocardiogram-1_03_00.png

copying images... [ 13%] generated/../../build/plot_directive/generated/scipy-ndimage-rotate-1_00_00.png

copying images... [ 20%] generated/../../build/plot_directive/generated/scipy-signal-convolve-1.png

copying images... [ 27%] generated/../../build/plot_directive/generated/scipy-signal-gausspulse-1.png

copying images... [ 34%] generated/../../build/plot_directive/generated/scipy-signal-peak_prominences-1_00_00.png

copying images... [ 41%] generated/../../build/plot_directive/generated/scipy-signal-welch-1_01_00.png

rated/

copying images... [ 47%] generated/../../build/plot_directive/generated/scipy-signal-windows-hamming-1_00.png

copying images... [ 54%] generated/../../build/plot_directive/generated/scipy-spatial-tsensform-RotationSpline-1_02_00.png

arch-1.png39

copying images... [ 61%] generated/../../build/plot_directive/generated/scipy-stats-binned_statistic_dd-1.png

copying images... [ 68%] generated/../../build/plot_directive/generated/scipy-stats-genhalflogistic-1.png39;49

;00m

copying images... [ 75%] generated/../../build/plot_directive/generated/scipy-stats-loggamma-1.png

copying images... [ 81%] generated/../../build/plot_directive/generated/scipy-stats-randint-1_00_00.png

copying images... [ 88%] ../build/plot_directive/optimizctive/generated/scipy-stats-zipfian-1_00_00.png

copying images... [ 95%] tutorial/../../build/plot_directive/tutorial/signal-5.png


copying images... [100%] tutorial/../../build/plot_directive/tutorial/stats/plots/mgc_plot4.png

copying static files... done

copying extra files... done

dumping search index in English (code: en)... done

dumping object inventory... done

build finished with problems, 5 warnings.

Makefile:127: recipe for target 'html-scipyorg' failed

make: *** [html-scipyorg] Error 1

make: Leaving directory '/workspace/doc'

Traceback (most recent call last):

File "runtests.py", line 565, in <module>

main(argv=sys.argv[1:])

File "runtests.py", line 214, in main

subprocess.run(cmd, check=True)

File "/usr/local/lib/python3.7/subprocess.py", line 468, in run

output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['make', '-Cdoc', 'PYTHON="/workspace/venv/bin/python"', 'html-scipyorg', 'latex', 'SPHINXOPTS="-j2"']' returned non-zero exit status 2.
```

</details>

**Comment by V0lantis** [comment]
Seems to be working now, so I'll close this Issue
