### ISSUE TITLE
optimize.shgo: handle objective functions that return the gradient alongside the objective value

### ISSUE THREAD

**Issue by cherrywoods** [scipy/scipy#13547]
The shgo implementation seems to be unable to handle the gradient calculation option where the gradient is directly returned alongside the objective value by the objective function (as indicated by using `'jac': True`). 
I think the minimal working example below demonstrates the issue quite well.

It works fine when passing a separate Callable that calculates the gradient for `'jac'`

#### Reproducing code example:

```
from scipy.optimize import shgo

def func(x):
    return np.sum(np.power(x, 2)), 2 * x

shgo(
    func, 
    bounds=[[-1,1], [1,2], [-1,1], [1,2], [0,3]],  
    n=100, iters=5, 
    sampling_method="sobol", 
    minimizer_kwargs={'method': 'SLSQP', 'jac': True}
)
```

#### Error message:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 421, in shgo
    shc.construct_complex()
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 726, in construct_complex
    self.iterate()
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 869, in iterate
    self.iterate_complex()
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 906, in iterate_delaunay
    self.sampled_surface(infty_cons_sampl=self.infty_cons_sampl)
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 1236, in sampled_surface
    self.fun_ref()
  File "/home/david/anaconda3/envs/bachelor-project/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 1447, in fun_ref
    self.F[i] = self.func(self.C[i, :], *self.args)
ValueError: setting an array element with a sequence.
```

#### Scipy/Numpy/Python version information:
```
scipy: 1.6.0 
numpy: 1.19.2 
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```
-->

**Comment by pmla** [comment]
@Stefan-Endres

**Comment by Stefan-Endres** [comment]
Thank you for reporting this @cherrywoods and @pmla for the ping. This should be also be relatively easy to fix I just need to split the `func` argument output in `SHGO.__init__` when a bool indstead of a vector function is supplied. Also need to update the documentation to match the new documentation [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize).

**Comment by tupui** [comment]
Just to add that the error is also present when not using `sobol`.

**Comment by cherrywoods** [comment]
That sounds good. Thanks for working on it!

**Comment by tupui** [comment]
@Stefan-Endres just checking in. Do you plan a PR to address some issues like these? Thanks.

**Comment by Stefan-Endres** [comment]
Thank you for the reminder, I will try to finish the PR this weekend.

**Comment by tupui** [comment]
> Thank you for the reminder, I will try to finish the PR this weekend.

Thanks for the update 😃
