### ISSUE TITLE
ValueError in scipy.signal.lsim2 using more than one input

### ISSUE THREAD

**Issue by FWuellhorst** [scipy/scipy#13545]
My issue is about the `scipy.signal.lsim2` function. When I try to simulate systems using two or more inputs, the error below occurs. 
I fixed this locally by changing line 1908 in `ltisys.py`  from
```python
return dot(sys.A, x) + squeeze(dot(sys.B, nan_to_num(ufunc([t]))))
```
to 
```python
return dot(sys.A, x) + squeeze(dot(sys.B, nan_to_num(ufunc([t])).flatten()))
```

This may be related to #7228. I also tried out the `vstack` function used in the issue, same error.
The middle error is as expected, however, I wanted to be sure that my input was correctly formatted.

#### Reproducing code example:

```python
from scipy import signal
import numpy as np
sys = signal.StateSpace([0], [1, 2], [0], [0, 0])
t = np.arange(10)
x0 = [0]
u = np.ones((len(t), 2))
try:
    signal.lsim2(system=sys, T=t, U=u, X0=x0)
except ValueError as e:
    print("Does not work: " + str(e))
u = np.ones((2, len(t)))
try:
    signal.lsim2(system=sys, T=t, U=u, X0=x0)
except ValueError as e:
    print("Does not work: " + str(e))
u = np.arange(10)
u = np.vstack((u, u)).T
try:
    signal.lsim2(system=sys, T=t, U=u, X0=x0)
except ValueError as e:
    print("Does not work: " + str(e))
    raise e
```

#### Error message:

```
Traceback (most recent call last):
  File "<input>", line 21, in <module>
  File "<input>", line 18, in <module>
  File "C:\...\lib\site-packages\scipy\signal\ltisys.py", line 1909, in lsim2
    xout = integrate.odeint(fprime, X0, T, args=(sys, ufunc), **kwargs)
  File "C:\...\lib\site-packages\scipy\integrate\odepack.py", line 241, in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
  File "C:\...\site-packages\scipy\signal\ltisys.py", line 1908, in fprime
    return dot(sys.A, x) + squeeze(dot(sys.B, nan_to_num(ufunc([t]))))
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)
```

#### Scipy/Numpy/Python version information:

1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by DietBru** [comment]
The `lsim2` function was removed in favor of the [lsim] function in SciPy [SciPy 1.13.0].

[lsim]: https://scipy.github.io/devdocs/reference/generated/scipy.signal.lsim.html
[SciPy 1.13.0]: https://docs.scipy.org/doc/scipy-1.18.0/release/1.13.0-notes.html#expired-deprecations
