### ISSUE TITLE
truncnorm gives incorrect means and variances 

### ISSUE THREAD

**Issue by gregdeon** [scipy/scipy#13580]
`truncnorm.mean` and `truncnorm.var` appear to give incorrect outputs when `loc` or `scale` are array-like and contain more than one number: 
```
>>> import scipy.stats as stats
>>> stats.truncnorm.mean(-1, 2, loc=0)
0.229637179091329
>>> stats.truncnorm.mean(-1, 2, loc=[0])
array([0.22963718])
>>> stats.truncnorm.mean(-1, 2, loc=[0, 0]) # expect to get 0.2296 twice
array([0., 0.])
>>> stats.truncnorm.var(-1, 1, loc=0)
0.29112509477279314
>>> stats.truncnorm.var(-1, 1, loc=[0])
array([0.29112509])
>>> stats.truncnorm.var(-1, 1, loc=[0, 0]) # expect to get 0.2911 twice
array([1., 1.])
```
`truncnorm.moment` doesn't seem to support array-likes at all, either:
```
>>> stats.truncnorm.moment(1, -1, 1, loc=[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1266, in moment
    fac = float(scale) / float(loc)
TypeError: float() argument must be a string or a number, not 'list'
```

This is on Scipy version 1.6.0. This problem was even worse on version 1.4.1, where `truncnorm.var()` could produce negative numbers:
```
>>> stats.truncnorm.var(-1, 1, loc=0)
0.29112509477279314
>>> stats.truncnorm.var(-1, 1, loc=[0, 0])
array([-0.41774981, -0.41774981])
```

I don't think I'm using these functions incorrectly, as the docstrings for `mean()`, `var()`, and `moment()` all say that `loc` and `scale` can be array-like.

**Comment by mdhaber** [comment]
gh-12192 fixes `moment`'s issues with input arrays. That's a problem for all stats distributions. (Potential reviewers: that PR is waiting for review. I was reviewing, but ended up writing a fair amount of code, so I think it needs an independent review.) 

I'll take a look into `truncnorm` mean and variance. I think that is distribution specific.

**Comment by mdhaber** [comment]
While smoking out this issue, I'm going to collect the other bugs I find here to avoid slowing things down. I'll open separate issues if need be. 
```
mean, var, skew, kurt = stats.kappa4.stats(0.1, 0, moments='mvsk', loc=np.array([1, 2]))  # ValueError: The truth value of
mean, var, skew, kurt = stats.kappa3.stats(1, moments='mvsk', loc=np.array([1, 2]))  # ValueError: The truth value of
```

**Comment by mdhaber** [comment]
OK, I was concerned that there might be something wrong with the way `distn_infrastructure` was dealing with `loc`, but no, it is that `truncnorm.stats` is not dealing with array shape parameters correctly.
```python3
stats.truncnorm.stats([-1], [2])  # right: (array([0.22963718]), array([0.51976254]))
stats.truncnorm.stats([-1, -1], [2, 2])  # wrong: (array([0., 0.]), array([1., 1.]))
```

**Comment by mdhaber** [comment]
Problem is line 7917:
```
        pA, pB = self._pdf(np.array([a, b]), a, b)
```
fix is:
```
        pA, pB = self.pdf(np.array([a, b]), a, b)
```
I'll open a PR.

**Comment by czgdp1807** [comment]
Hi @mdhaber Can I try your fix and open a PR for this issue? Please let me know. Thanks.

**Comment by mdhaber** [comment]
I opened gh-13581 to fix this in February. It just hasn't been reviewed by another maintainer.

**Comment by czgdp1807** [comment]
Ah! I missed it. No problems. Thanks for highlighting your work on this issue.
