### ISSUE TITLE
find_objects blowing up memory

### ISSUE THREAD

**Issue by william-silversmith** [scipy/scipy#13648]
Hi all, 

Thanks for the wonderful package! On Python 3.9.2, on MacOS Big Sur on an Apple Silicon chip with SciPy 1.6.1 and numpy 1.20.1 the find_objects function is using so much memory that it's getting OOM killed.

#### Reproducing code example:

To reproduce, you can download an image volume. It's public data, but please don't integrate the network call version of this into an automated test. ^_^ You'll need to run:

```
pip install cloud-volume scipy 
```
```python
from cloudvolume import CloudVolume
from scipy.ndimage import find_objects

cv = CloudVolume("precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/segmentation", cache=False, progress=False)
img = cv.download_point((10320, 29908, 19427), size=512, mip=1)[...,0]

find_objects(img) # OOM
```

The data can be viewed using this [link](https://hemibrain-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B10279.9921875%2C30010.0234375%2C19427.5%5D%2C%22crossSectionScale%22:5.07016240595119%2C%22crossSectionDepth%22:-37.62185354999912%2C%22projectionOrientation%22:%5B-0.12254740297794342%2C-0.23909232020378113%2C-0.08598940074443817%2C0.9593867063522339%5D%2C%22projectionScale%22:4099.465892278677%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/emdata/clahe_yz/jpeg%22%2C%22name%22:%22emdata%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/segmentation%22%2C%22crossSectionRenderScale%22:0.07830255818115668%2C%22name%22:%22segmentation%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/rois%22%2C%22subsources%22:%7B%22default%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22segments%22%2C%22pick%22:false%2C%22selectedAlpha%22:0%2C%22saturation%22:0%2C%22objectAlpha%22:0.8%2C%22ignoreNullVisibleSet%22:false%2C%22meshSilhouetteRendering%22:3%2C%22colorSeed%22:2685294016%2C%22name%22:%22roi%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses%22%2C%22tab%22:%22rendering%22%2C%22ignoreNullSegmentFilter%22:false%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22red%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22blue%5C%22%29%5Cn#uicontrol%20float%20preConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn#uicontrol%20float%20postConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setColor%28defaultColor%28%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%200.5%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%200.5%29%29%3B%5Cn%20%20setEndpointMarkerSize%282.0%2C%202.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28prop_pre_synaptic_confidence%28%29%3C%20preConfidence%20%7C%7C%5Cn%20%20%20%20%20%20prop_post_synaptic_confidence%28%29%3C%20postConfidence%29%20discard%3B%5Cn%7D%5Cn%22%2C%22linkedSegmentationLayer%22:%7B%22pre_synaptic_cell%22:%22segmentation%22%2C%22post_synaptic_cell%22:%22segmentation%22%7D%2C%22filterBySegmentation%22:%5B%22post_synaptic_cell%22%2C%22pre_synaptic_cell%22%5D%2C%22name%22:%22synapse%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/mito_20190717.27250582%22%2C%22tab%22:%22segments%22%2C%22pick%22:false%2C%22selectedAlpha%22:0.82%2C%22name%22:%22mito%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/mask_normalized_round6%22%2C%22tab%22:%22segments%22%2C%22pick%22:false%2C%22selectedAlpha%22:0.53%2C%22segments%22:%5B%222%22%5D%2C%22name%22:%22mask%22%2C%22visible%22:false%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22segmentation%22%2C%22visible%22:true%2C%22size%22:290%7D%2C%22layout%22:%224panel%22%7D).

#### Scipy/Numpy/Python version information:
SciPy 1.6.1 Numpy 1.20.1 
Python: sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

**Comment by william-silversmith** [comment]
It's notable that I was creating this example specifically to stress the bounding box function, much of the data is approximately diagonal across the bbox.

**Comment by tylerjereddy** [comment]
To clarify, are you claiming that this is a *regression* and that you could previously do this with an older version of SciPy or on another platform that is not bleeding-edge like M1?

**Comment by william-silversmith** [comment]
The following test was conducted on an Ubuntu 16.04 workstation with Python 3.6, scipy 1.3.1, and numpy 1.19.5. The workstation has 32 GB of RAM.

```python
(cv) me@workstation:~/cloud-volume$ time mprof run scipytest.py 
mprof: Sampling memory every 0.1s
running as a Python program...
Traceback (most recent call last):
  File "/usr/people/ws9/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/people/ws9/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/people/ws9/.virtualenvs/cv/lib/python3.6/site-packages/memory_profiler.py", line 1227, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/usr/people/ws9/.virtualenvs/cv/lib/python3.6/site-packages/memory_profiler.py", line 1128, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "scipytest.py", line 7, in <module>
    find_objects(img) # OOM, note that img is in Fortran order but this also happens in C order
  File "/usr/people/ws9/.virtualenvs/cv/lib/python3.6/site-packages/scipy/ndimage/measurements.py", line 305, in find_objects
    return _nd_image.find_objects(input, max_label)
MemoryError

real	0m5.778s
user	0m4.136s
sys	0m0.976s
```

**Comment by william-silversmith** [comment]
I think I found the issue in find_objects.

https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/ndimage/src/ni_measure.c#L76

It takes a "max_label" but I think it expects the label to be small. Since the labels in this volume are large, it allocates a huge array.

The workaround for me is to do the following:

```bash
pip install fastremap
```

```python
fastremap.renumber(img, in_place=True)
```

https://github.com/seung-lab/fastremap

**Comment by william-silversmith** [comment]
Hmm, on second thought now that I think about the interface, that seems like the design. You're supposed to access the result using the index of the label - 1.

**Comment by jni** [comment]
@william-silversmith indeed it's hard/impossible to change the API for `find_objects` but we would welcome a defaultdict implementation at skimage — see https://github.com/scikit-image/scikit-image/issues/4855
