### ISSUE TITLE
scipy.signal.sepfir2d fails with complex input on Windows

### ISSUE THREAD

**Issue by leofang** [scipy/scipy#13643]
Hi, I am bringing test failures that we noticed in CuPy's new Windows CI to your attention. We confirmed locally that this is reproducible. Below is the test (very simple) and the error log:

```
____ TestSepFIR2d_param_0_{hcol=1, hrow=1, input=(256, 256)}.test_sepfir2d ____

self = <<test_bsplines.TestSepFIR2d_param_0_{hcol=1, hrow=1, input=(256, 256)} testMethod=test_sepfir2d>  parameter: {'hcol': 1, 'hrow': 1, 'input': (256, 256)}>
xp = <module 'numpy' from 'C:\\Development\\Python\\Python37\\lib\\site-packages\\numpy\\__init__.py'>
scp = <module 'scipy' from 'C:\\Development\\Python\\Python37\\lib\\site-packages\\scipy\\__init__.py'>
dtype = <class 'numpy.complex64'>

    @testing.for_all_dtypes()
    @testing.numpy_cupy_allclose(atol=1e-5, rtol=1e-5, scipy_name='scp')
    def test_sepfir2d(self, xp, scp, dtype):
        input = testing.shaped_random(self.input, xp, dtype)
        hrow = testing.shaped_random((self.hrow,), xp, dtype)
        hcol = testing.shaped_random((self.hcol,), xp, dtype)
>       return scp.signal.sepfir2d(input, hrow, hcol)
E       AssertionError: Only numpy raises error
E       
E       Traceback (most recent call last):
E         File "C:\Windows\TEMP\flexci\run-00142981\work\src\cupy\testing\helper.py", line 47, in _call_func
E           result = impl(self, *args, **kw)
E         File "C:\Windows\TEMP\flexci\run-00142981\work\src\tests\cupyx_tests\scipy_tests\signal_tests\test_bsplines.py", line 27, in test_sepfir2d
E           return scp.signal.sepfir2d(input, hrow, hcol)
E       ValueError: Incorrect type.

tests\cupyx_tests\scipy_tests\signal_tests\test_bsplines.py:27: AssertionError
---------------------------- Captured stdout call -----------------------------
dtype is <class 'numpy.complex64'>
```

The same tests pass just fine on Linux, but not on Windows, so we skip this test in cupy/cupy#4804 when
- the OS is Windows
- `input.dtype.kind == 'c'`

I think most likely in the C implementation of sepfir2d the input array type got cast to something not supported by mistake, leading to the ValueError.

#### Scipy/Numpy/Python version information:

NumPy 1.20.1, SciPy 1.6.1, Python 3.7

**Comment by rgommers** [comment]
This code looks a bit fishy :
```C
  thetype = PyArray_ObjectType(image, NPY_FLOAT);
  thetype = PyArray_MIN(thetype, NPY_CDOUBLE);
  a_image = (PyArrayObject *)PyArray_FromObject(image, thetype, 2, 2);
```
and this is worse - why would we only support complex dtypes for GCC?:
```C
#ifdef __GNUC__
  case NPY_CFLOAT:
    {
      __complex__ float zc0 = c0.real + 1.0i*c0.imag;
      __complex__ float zz1 = z1.real + 1.0i*z1.imag;      
      if ((precision <= 0.0) || (precision > 1.0)) precision = 1e-6;
      ret = C_IIR_forback1 (zc0, zz1, (__complex__ float *)PyArray_DATA(a_sig), 
			    (__complex__ float *)PyArray_DATA(out), N,
			    instrides, outstrides, (float )precision);
    }
    break;
  case NPY_CDOUBLE:
    {
      __complex__ double zc0 = c0.real + 1.0i*c0.imag;
      __complex__ double zz1 = z1.real + 1.0i*z1.imag;      
      if ((precision <= 0.0) || (precision > 1.0)) precision = 1e-11;
      ret = Z_IIR_forback1 (zc0, zz1, (__complex__ double *)PyArray_DATA(a_sig), 
			    (__complex__ double *)PyArray_DATA(out), N,
			    instrides, outstrides, precision);
    }
    break;
#endif
  default:
    PYERR("Incorrect type.");
  }
```
The filter code being called (e.g. in `C_bspline_util.c`) also uses `#ifdef __GNUC__`. I think this code predates Clang being a thing, and perhaps there was some bug with an exotic compiler that the original author didn't feel like looking at.

PR gh-14367 is making some fixes to `sepfir2d`, let's see if we can take this along.

**Comment by leofang** [comment]
Thanks for digging into it, Ralf!

> why would we only support complex dtypes for GCC?

Sounds like the code was added way before C99 was supported by the majority of compilers. IIRC I was still battling with Clang and Intel compilers not long ago (2~3 yrs) on some weird complex-number behaviors, so it's not surprising...
