### ISSUE TITLE
wheel Building failure and failed cleaning bulid dir for scipy 

### ISSUE THREAD

**Issue by Schrscat** [scipy/scipy#13834]
I met the error when building the wheel for scipy. The error message is:

```bash
Building wheels for collected packages: scipy
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/d/ANDI/envs/clinicaEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d48y30cb
       cwd: /tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/
  Complete output (109 lines):
  Running from scipy source directory.
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries tatlas,tatlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib64
    libraries tatlas,tatlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries satlas,satlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib64
    libraries satlas,satlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries ptf77blas,ptcblas,atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib64
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries f77blas,cblas,atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/lib64
    libraries f77blas,cblas,atlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  /home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/system_info.py:1849: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  /home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/system_info.py:1849: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 492, in <module>
      setup_package()
    File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 488, in setup_package
      setup(**metadata)
    File "/home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 395, in configuration
      raise NotFoundError(msg)
  numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Command errored out with exit status 1:
   command: /mnt/d/ANDI/envs/clinicaEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2
  Complete output (9 lines):

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy, pytz, pydot, prov, pillow, nibabel, kiwisolver, joblib, filelock, etelemetry, docopt, cycler, click, torch, scikit-learn, PyWavelets, pandas, num2words, nipype, matplotlib, MarkupSafe, imageio, grabbit, future, xvfbwrapper, xlrd, xgboost, torchvision, scikit-image, pybids, nilearn, niflow-nipype1-workflows, jinja2, colorama, argcomplete, clinica
  Attempting uninstall: scipy
    Found existing installation: scipy 1.6.2
    Uninstalling scipy-1.6.2:
      Successfully uninstalled scipy-1.6.2
    Running setup.py install for scipy ... error
    ERROR: Command errored out with exit status 1:
     command: /mnt/d/ANDI/envs/clinicaEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j2nhzvey/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/d/ANDI/envs/clinicaEnv/include/python3.9/scipy
         cwd: /tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/
    Complete output (118 lines):

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries tatlas,tatlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries tatlas,tatlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries satlas,satlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries satlas,satlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries ptf77blas,ptcblas,atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries f77blas,cblas,atlas not found in /mnt/d/ANDI/envs/clinicaEnv/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib64
      libraries f77blas,cblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['/mnt/d/ANDI/envs/clinicaEnv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    /home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    /home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 492, in <module>
        setup_package()
      File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 488, in setup_package
        setup(**metadata)
      File "/home/garyshap/.local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py", line 395, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
  Rolling back uninstall of scipy
  Moving to /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/scipy-1.6.2.dist-info/
   from /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/~cipy-1.6.2.dist-info
  Moving to /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/scipy.libs/
   from /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/~cipy.libs
  Moving to /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/scipy/
   from /mnt/d/ANDI/envs/clinicaEnv/lib/python3.9/site-packages/~cipy
ERROR: Command errored out with exit status 1: /mnt/d/ANDI/envs/clinicaEnv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sodpeg7j/scipy_e803d129c50f431db957540d75192dc2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j2nhzvey/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/d/ANDI/envs/clinicaEnv/include/python3.9/scipy Check the logs for full command output.
```

**Comment by tupui** [comment]
Hi, did you check you have installed LAPACK or BLAS as suggested by the error log: `No lapack/blas resources found.`?

Did you follow the install instructions completely?

**Comment by tupui** [comment]
I am closing this for now. You can add more comments with more details and I could re-open. But I think believe there is no issue here as all CI can build on all architectures.

**Comment by Schrscat** [comment]
I reinstalled the python environment by python 3.7 instead of python 3.9. and the problem was solved. Installing LAPACK and BLAS didn't help.

**Comment by tupui** [comment]
Can you share your environment? What OS and where you trying to build master (which commit hash?)? Are you in a virtual env, conda, etc.

**Comment by Schrscat** [comment]
I used win10 linux wsl, ubuntu. The environment is built by:
conda create --name clinicaEnv python=3.7
conda activate clinicaEnv

**Comment by tupui** [comment]
And then what do you do? Do you follow the instructions from the doc I linked?
