### ISSUE TITLE
bsr_matrix does not initialize with block matrices using the (data,ij) format

### ISSUE THREAD

**Issue by cntaylor** [scipy/scipy#13856]
My issue is about creating a bsr style sparse matrix using scipy.sparse.bsr_matrix.  Specifically, creating a matrix when using the bsr_matrix((data,ij)) format.

As long as data is a 1d array, bsr_matrix works as expected.  However, the whole point of a bsr (as opposed to csr) matrix is that data should be able to be an array of numpy arrays (all of the same size).  However, when 'data' is in this format, a "ValueError" is thrown by bsr_matrix, making it much harder to initialize bsr_matrix.

#### Reproducing code example:

```
import scipy.sparse as sp
# This code works
row = np.array([0,0,1,2,2,2])
col = np.array([0,2,2,0,1,2])
ij = np.zeros((2,6),dtype=int)
ij[0]=row
ij[1]=col
data = np.array([1,2,3,4,5,6])
mtx = sp.bsr_matrix((data,ij))
print(mtx.toarray())
# This code breaks
data = np.zeros((6,2,2))
for i in range(6):
    data[i] = np.ones(2)*(i+1)
mtx = sp.bsr_matrix((data,ij)) # This throws an exception
print(mtx.toarray())
```

#### Error message:

```
Traceback (most recent call last):
  File "c:/.../tst.py", line 16, in <module>
    mtx = sp.bsr_matrix((data,ij))
  File "C:\...\lib\site-packages\scipy\sparse\bsr.py", line 158, in __init__
    coo_matrix(arg1, dtype=dtype, shape=shape).tobsr(
  File "C:\...\lib\site-packages\scipy\sparse\coo.py", line 197, in __init__
    self._check()
  File "C:\...\lib\site-packages\scipy\sparse\coo.py", line 282, in _check
    if self.nnz > 0:
  File "C:\...\lib\site-packages\scipy\sparse\base.py", line 246, in nnz
    return self.getnnz()
  File "C:\...\lib\site-packages\scipy\sparse\coo.py", line 249, in getnnz
    raise ValueError('row, column, and data arrays must be 1-D')
ValueError: row, column, and data arrays must be 1-D
```

#### Scipy/Numpy/Python version information:

1.6.1 1.19.2 sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
Initializing with block-format data is supported by the `(data, indices, indptr)` constructor:

```python
indices = np.array([0,2,2,0,1,2])
indptr = np.array([0,2,3,6])
mtx = sp.bsr_matrix((data, indices, indptr))
```

I agree that we should support block-format data in the coordinate-style constructor as well, however. Currently it delegates initialization to the `coo_matrix` constructor, which is why we have the 1-d data limitation.
