### ISSUE TITLE
scipy.stats.spearmanr na_policy='omit' does not handle DataFrames with variables with too many NaNs

### ISSUE THREAD

**Issue by tobsecret** [scipy/scipy#13900]
Handing `scipy.stats.spearmanr` a DataFrame with a single variable with too many missing values, results in error `ValueError: The input must have at least 3 entries!`, as opposed to returning NaN for those comparisons where not enough overlapping non-NaN values are present.

#### Reproducing code example:

```
import numpy as np
import pandas as pd
import scipy
df1 = pd.DataFrame({'col1':[1.,2.,3.,4.], 'col2':[1.,2.,3.,4.]})
df2 = pd.DataFrame({'col1':[1.7,2.4,3.8,4.3], 'col2':[1.9,2.8,3.2,4.1]})
df3 = pd.DataFrame({'col1':[1.7,np.nan, np.nan, np.nan], 'col2':[1.9,2.8,3.2,4.1]})
scipy.stats.spearmanr(df1,df2, nan_policy='omit') #This will run fine
```
>SpearmanrResult(correlation=array([[1., 1., 1., 1.],
>       [1., 1., 1., 1.],
>       [1., 1., 1., 1.],
>       [1., 1., 1., 1.]]), pvalue=array([[0., 0., 0., 0.],
>       [0., 0., 0., 0.],
>       [0., 0., 0., 0.],
>       [0., 0., 0., 0.]]))

```
scipy.stats.spearmanr(df1,df3, nan_policy='omit') #This will produce the error
```
#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-67-6965e82bff98> in <module>
----> 1 scipy.stats.spearmanr(df1,df3, nan_policy='omit')

~/scratch/miniconda3/envs/phdis/lib/python3.8/site-packages/scipy/stats/stats.py in spearmanr(a, b, axis, nan_policy)
   4206     if a_contains_nan:
   4207         if nan_policy == 'omit':
-> 4208             return mstats_basic.spearmanr(a, axis=axis, nan_policy=nan_policy)
   4209         elif nan_policy == 'propagate':
   4210             if a.ndim == 1 or n_vars <= 2:

~/scratch/miniconda3/envs/phdis/lib/python3.8/site-packages/scipy/stats/mstats_basic.py in spearmanr(x, y, use_ties, axis, nan_policy)
    539         for var1 in range(n_vars - 1):
    540             for var2 in range(var1+1, n_vars):
--> 541                 result = _spearmanr_2cols(x[:, [var1, var2]])
    542                 rs[var1, var2] = result.correlation
    543                 rs[var2, var1] = result.correlation

~/scratch/miniconda3/envs/phdis/lib/python3.8/site-packages/scipy/stats/mstats_basic.py in _spearmanr_2cols(x)
    509         dof = n_obs - 2 - int(m.sum(axis=0)[0])
    510         if dof < 0:
--> 511             raise ValueError("The input must have at least 3 entries!")
    512 
    513         # Gets the ranks and rank differences

ValueError: The input must have at least 3 entries!
```

#### Scipy/Numpy/Python version information:

`1.6.2 1.20.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)`

**Comment by tupui** [comment]
Thanks for reporting. But in this case I think you were looking for `propagate` and not `omit`. Omit is not looking at the values with NaNs, hence your error.

Can you check this and close if this answer your issue? Thanks in advance.

**Comment by mdhaber** [comment]
I think the issue is valid. If i remember correctly, the hypothesis tests are not very consistent with what they do when there are not enough samples to perform the test. It is reasonable that the user would expect them to return nan instead of raising an error. Il revise this post when I look at what our nan_policy document has to say about what should happen.

**Comment by tupui** [comment]
Because here it says that `omit` will not consider the values. So to me it looked coherent with the message. 

![Screenshot 2021-04-21 at 19 01 43](https://user-images.githubusercontent.com/23188539/115592827-083e5000-a2d4-11eb-9482-9f95211bbb22.png)

Agreed for the message 😅

**Comment by tupui** [comment]
And using propagate with this example gives:

```python
scipy.stats.spearmanr(df1,df3, nan_policy='propagate')
Out[5]: 
SpearmanrResult(correlation=array([[ 1.,  1., nan,  1.],
       [ 1.,  1., nan,  1.],
       [nan, nan, nan, nan],
       [ 1.,  1., nan,  1.]]), pvalue=array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]]))

```

**Comment by tobsecret** [comment]
To me, the description for omit implied that if I have 2 vectors that contain NaNs, it will just ignore all the positions where the 2 vectors don't both have a NaN. It doesn't talk about what happens when there are too few matching pairs, so since it wasn't mentioned in the vignette on the docs page, I assumed it would default to returning np.NaN for p-value and correlation. 

I also don't quite understand the error - it says it requires at least 3 values but the error only triggers when there is exactly one matching value. It gives a warning when there are 2 matching values and just returns the expected np.NaN for both p-value and correlation if there are no matching values. 

```
from scipy.stats import spearmanr
import pandas as pd
import numpy as np
arr1  = np.array([np.nan, np.nan, 2, 3])
arr2  = np.array([4, 1, 2, 3])
spearmanr(arr1, arr2)
```
>SpearmanrResult(correlation=nan, pvalue=nan)

```
spearmanr(arr1, arr2, nan_policy='omit')
```
>/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/mstats_basic.py:507: >RuntimeWarning: invalid value encountered in true_divide
>  t = rs * np.sqrt((dof / ((rs+1.0) * (1.0-rs))).clip(0))
>SpearmanrResult(correlation=1.0, pvalue=nan)

```
arr3  = np.array([np.nan, np.nan, np.nan, 3])
spearmanr(arr3, arr2, nan_policy='omit')
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/stats.py", line 4276, in spearmanr
>     return mstats_basic.spearmanr(a, axis=axis, nan_policy=nan_policy)
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/mstats_basic.py", line 521, in spearmanr
>     return _spearmanr_2cols(x)
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/mstats_basic.py", line 497, in _spearmanr_2cols
>     raise ValueError("The input must have at least 3 entries!")
> ValueError: The input must have at least 3 entries!

```
arr1_positions_matter = np.array([np.nan, np.nan, 1,2])
arr2_positions_matter = np.array([np.nan, 1, np.nan,2])
spearmanr(arr1_positions_matter, arr2_positions_matter, nan_policy='omit')
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/stats.py", line 4276, in spearmanr
>     return mstats_basic.spearmanr(a, axis=axis, nan_policy=nan_policy)
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/mstats_basic.py", line 521, in spearmanr
>     return _spearmanr_2cols(x)
>   File "/gpfs/home/schrat01/scratch/miniconda3/envs/scipy_testenv/lib/python3.9/site-packages/scipy/stats/mstats_basic.py", line 497, in _spearmanr_2cols
>     raise ValueError("The input must have at least 3 entries!")
> ValueError: The input must have at least 3 entries!
> 
```
arr_nan  = np.array([np.nan, np.nan, np.nan, np.nan])
spearmanr(arr_nan, arr2, nan_policy='omit')
```
>SpearmanrResult(correlation=nan, pvalue=nan)

I am not interested in using propagate because I work with reasonably sparse data, so propagate would just return NaN.

**Comment by mdhaber** [comment]
Here is what is supposed to happen:
http://scipy.github.io/devdocs/dev/api-dev/nan_policy.html

**Comment by tobsecret** [comment]
> More generally, for functions that return a scalar, func(a, nan_policy='omit') should behave the same as func(a[~np.isnan(a)]).

Isn't this violated in the case I described above? `spearmanr(np.array([2]), np.array([1]), nan_policy='omit')` returns two NaN values and `spearmanr(np.array([2, np.nan]), np.array([1, np.nan]), nan_policy='omit')` gives an error. Should both function calls return NaNs or should they both throw the less than 3 error <3? 

And would you welcome me trying to tackle this with a PR? I have never contributed here before but I'm willing to try.

**Comment by mdhaber** [comment]
Yes, you're right, it is violated. 

It's because when `nan_policy='omit'`, `spearmanr` calls the `mstats` version of `spearmanr`, which behaves differently when there is an insufficient number of observations.

**Comment by tobsecret** [comment]
That makes sense! Yes, that's what I'd propose - happy to hear use cases where it's important that it errors out in the cases I described above. Just because it's not convenient for me ofc doesn't mean there wasn't a good reason for it.

I just signed up for the mailing list, and will look into the standards for proposals like this.
Thanks for the feedback @mdhaber and @tupui!

**Comment by mdhaber** [comment]
Please review gh-12241. I thought I remember this coming up before.

**Comment by tobsecret** [comment]
Sent the proposal just now.

**Comment by mdhaber** [comment]
Will fix as part of gh-14651

**Comment by mdhaber** [comment]
This is not fixed in `spearmanr`, and it's not clear that it can be in a backward compatible way.

```python3
import numpy as np
from scipy import stats
df1 = np.asarray([[1.,2.,3.,4.], [1.,2.,3.,4.]]).T
df2 = np.asarray([[1.7,2.4,3.8,4.3], [1.9,2.8,3.2,4.1]]).T
df3 = np.asarray([[1.7,np.nan, np.nan, np.nan], [1.9,2.8,3.2,4.1]]).T
ref = stats.spearmanr(df1, df3, nan_policy='omit')
# ValueError: The input must have at least 3 entries!
```

But it would be resolved in the proposed `spearmanrho` (gh-23851). After a reasonable warning, we get the expected result.

```python3
x = np.concatenate((df1, df3), axis=-1).T
res = stats.spearmanrho(x[:, np.newaxis], x[np.newaxis, :], axis=-1, nan_policy='omit')
# <ipython-input-38-7517b97c85e7>:2: SmallSampleWarning: After omitting NaNs, one or more axis-slices of one or more sample arguments is too small; corresponding elements of returned arrays will be NaN. See documentation for sample size requirements.
#  res = stats.spearmanrho(x[:, np.newaxis], x[np.newaxis, :], axis=-1, nan_policy='omit')
# array([[ 1.,  1., nan,  1.],
#        [ 1.,  1., nan,  1.],
#        [nan, nan, nan, nan],
#        [ 1.,  1., nan,  1.]])
```

Somebody is welcome to re-open this issue, but it would be preferable if they did so with a plan for resolving it for `spearmanr` (e.g. deprecating?). It was closed for three years without that bothering anyone, and now that gh-23851 proposes a way forward, it makes even more sense to leave it that way.
