### ISSUE TITLE
scipy.io.netcdf cannot read large netcdf files

### ISSUE THREAD

**Issue by raphaeldussin** [scipy/scipy#13980]
My issue is about the support of large netcdf3 files in scipy.io It seems that files larger than 2GB are not supported, using `mmap` or not. Netcdf3 classic implementation has this hard limit but was lifted with the netcdf3 64bit offset. If scipy.io cannot handle the 64bit offset files, maybe there could be a way to capture the error and return a more informative message. Also this limitation
should be mentioned in the documentation as it is used as a backend for other packages (e.g. xarray).

#### Reproducing code example:

```
import xarray as xr
import scipy.io as sio
import numpy as np
import uuid


for k in range(5,7):
    print(f'creating {k} variables')
    print(f'datasize = {k * 1e8 * 4 /1024 /1024 /1024} GB')
    ds = xr.Dataset()
    # populate with bogus arrays
    for n in range(k):
        var = str(uuid.uuid4())
        ds[var] = xr.DataArray(data=np.empty((1,100,1000,1000), dtype='f4'),
                               dims=('time', 'z', 'y', 'x'))

    print('write to file with netcdf4')
    ds.to_netcdf('test_ds.nc', format='NETCDF3_64BIT', unlimited_dims=('time'))
    print('read with scipy.io')
    f = sio.netcdf_file('test_ds.nc','r')
```

#### Error message:
```
Traceback (most recent call last):
  File "/home/raphael/dev/sandbox/scipy_largefiles/scipy_large_netcdf_issue.py", line 20, in <module>
    f = sio.netcdf_file('test_ds.nc','r')
  File "/home/raphael/anaconda3/envs/test_scipy/lib/python3.9/site-packages/scipy/io/netcdf.py", line 281, in __init__
    self._read()
  File "/home/raphael/anaconda3/envs/test_scipy/lib/python3.9/site-packages/scipy/io/netcdf.py", line 610, in _read
    self._read_var_array()
  File "/home/raphael/anaconda3/envs/test_scipy/lib/python3.9/site-packages/scipy/io/netcdf.py", line 716, in _read_var_array
    rec_array = self._mm_buf[begin:begin+self._recs*self._recsize].view(dtype=dtypes)
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype
```

#### Scipy/Numpy/Python version information:

```
1.6.3 1.20.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment]
I can reproduce this issue using SciPy 1.15.0 and the provided reproducing code.
