### ISSUE TITLE
Unable to import `scipy.ftt`

### ISSUE THREAD

**Issue by siscia** [scipy/scipy#14136]
So, I am not sure if I am doing something completely wrong, since this report seems quite basic, and I cannot believe that I am the first reporting this problem.

Anyway, in a quite fresh mac, I try to install scipy to get access to the fourier transform.

#### Reproducing code example:

```
import scipy.ftt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy.ftt'
```

#### Error message:

```
➜  $ pip3 install scipy
Requirement already satisfied: scipy in /usr/local/lib/python3.9/site-packages (1.6.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.9/site-packages (from scipy) (1.20.3)
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
➜  $ python3 -c 'import scipy.ftt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy.ftt'
```

#### Scipy/Numpy/Python version information:

```
$ python3 -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'
1.6.3 1.20.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
```

#### Installation log

```
➜  $ pip3 install scipy
Collecting scipy
  Downloading scipy-1.6.3-cp39-cp39-macosx_10_9_x86_64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 8.5 MB/s
Collecting numpy<1.23.0,>=1.16.5
  Downloading numpy-1.20.3-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
     |████████████████████████████████| 16.1 MB 9.3 MB/s
Installing collected packages: numpy, scipy
Successfully installed numpy-1.20.3 scipy-1.6.3
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
```

#### Mac OS

macOS Big Sur
11.3.1 (20E241)

2 GHz Quad-Core Intel Core i5

**Comment by WarrenWeckesser** [comment]
I think you meant to import `scipy.fft`.  Is that correct?

**Comment by siscia** [comment]
We can close!

Sorry sorry!
