### ISSUE TITLE
ValueError: On entry to DGESDD parameter number 10 had an illegal value

### ISSUE THREAD

**Issue by keloemma** [scipy/scipy#14244]
My issue is about ... the library scipy, I used the classifier : LDA to train on a small dataset but I keep getting the error below : 
ValueError: On entry to DGESDD parameter number 10 had an illegal value

#### Reproducing code example:

```

Sample code to reproduce the problem

# scikit-learn==0.22.1
# pandas == 1.0.3
# numpy == 1.18.4
# scipy == 1.4.1
# torch == 1.5.0a0
# python == 3.7.6
# matplotlib==3.2.2
# transformers==4.4.2


model8 = XGBClassifier(eval_metric="logloss")
model7 = LinearDiscriminantAnalysis()
models_list = {'Model_XGB': model8, 'Model_LDA': model7}

# cross_validation

cv_splitter = KFold(n_splits=10, shuffle=True, random_state=42)
features, s = get_flaubert_layer(features, lge_model)
#print(features)
for model_name, model in models_list.items():
print("Model name: {}".format(model_name))
print("------------cross val predict used----------------", "\n")
y_pred = cross_val_predict(model, features, ylabels, cv=cv_splitter, verbose=1)
accuracy_score_predict = accuracy_score(ylabels, y_pred)
print("accuracy with cross_val_predict :", accuracy_score_predict)


```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  Loading pytorch-gpu/py3/1.5.0
  Loading requirement: gcc/8.3.1 cuda/10.1.2 nccl/2.5.6-2-cuda
    cudnn/10.1-v7.5.1.10 intel-compilers/19.0.4 openmpi/4.0.1-cuda
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    3.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed: 15.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   47.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
Traceback (most recent call last):
  File "training_for_multiclasse_classification.py", line 62, in <module>
    main()
  File "training_for_multiclasse_classification.py", line 44, in main
    dic_acc, dic_report, dic_cm, s = cross_validation(data_train, data_label_train, models_list, name, language_model_dir)
  File "../traitements/functions_for_training.py", line 58, in cross_validation
    y_pred = cross_val_predict(model, features, ylabels, cv=cv_splitter, verbose=1)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 755, in cross_val_predict
    for train, test in cv.split(X, y, groups))
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 206, in apply_async
    result = ImmediateResult(func)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 570, in __init__
    self.results = batch()
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 841, in _fit_and_predict
    estimator.fit(X_train, y_train, **fit_params)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/sklearn/discriminant_analysis.py", line 477, in fit
    self._solve_svd(X, y)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/sklearn/discriminant_analysis.py", line 396, in _solve_svd
    _, S, V = linalg.svd(X, full_matrices=0)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 125, in svd
    compute_uv=compute_uv, full_matrices=full_matrices)
  File "/gpfslocalsup/pub/anaconda-py3/2020.02/envs/pytorch-gpu-1.5.0/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 806, in _compute_lwork
    ret = routine(*args, **kwargs)
ValueError: On entry to DGESDD parameter number 10 had an illegal value
srun: error: r6i7n6: task 0: Exited with exit code 1
srun: Terminating job step 221450.0


# X equal 


[[ 0.  0. -0. ... -0. -0. -0.]
 [ 0. -0. -0. ... -0. -0. -0.]
 [ 0.  0.  0. ... -0. -0.  0.]
 ...
 [ 0. -0. -0. ... -0. -0. -0.]
 [ 0. -0. -0. ... -0. -0. -0.]
 [ 0.  0. -0. ... -0. -0. -0.]]

```

```

#### Scipy/Numpy/Python version information:
<!-- You can simply run the following and paste the result in a code block
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
--> 
1.4.1 1.18.4 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Hi @keloemma Could you please identify exactly the value that hits `svd`  on this line in the stacktrace? 

```
_, S, V = linalg.svd(X, full_matrices=0)
```

Otherwise we don't know what happens internally inside the scikit-learn part and probably should be better suited for sklearn folks to have a look. Seems like at some point this `X`  becomes an empty array.

**Comment by keloemma** [comment]
@ilayn  When printing X , I get an array of 0 elements. (see below)
