### ISSUE TITLE
Sparse constructors don't accept dtypes from ctypes

### ISSUE THREAD

**Issue by david-cortes** [scipy/scipy#14365]
This will throw an error:
```python
from scipy.sparse import csr_matrix
import ctypes
csr_matrix((10,10), ctypes.c_double)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/del/scipy/scipy/sparse/compressed.py", line 90, in __init__
    self._shape = check_shape(shape)
  File "/home/david/del/scipy/scipy/sparse/sputils.py", line 279, in check_shape
    if len(args) == 0:
TypeError: object of type '_ctypes.PyCSimpleType' has no len()
```

It only accepts dtypes from numpy, whereas numpy itself also accepts dtypes from ctypes:
```python
import numpy as np
np.array(1, dtype=ctypes.c_double)
```

**Comment by david-cortes** [comment]
Closed, just noticed that the argument needs to be named, regardless of whether it is from ctypes or not.
