### ISSUE TITLE
Issue Runnin SciPy with BigML on Windows

### ISSUE THREAD

**Issue by par-justinf** [scipy/scipy#14375]
My issue is about ...

#### Error message:

```
(venv) C:\Users\redacted\source\repos\par-redacted\par-redacted>main.py
Traceback (most recent call last):
  File "C:\Users\redacted\source\repos\par-redacted\par-redacted\main.py", line 6, in <module>
    from bigml.model import Model
  File "C:\Users\redacted\source\repos\par-redacted\par-redacted\venv\lib\site-packages\bigml\model.py", line 56, in <module>
    import bigml.predict_utils.regression as r
  File "C:\Users\redacted\source\repos\par-redacted\par-redacted\venv\lib\site-packages\bigml\predict_utils\regression.py", line 24, in <module>
    from scipy import stats
  File "C:\Users\redacted\source\repos\par-redacted\par-redacted\venv\lib\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\redacted\source\repos\par-redacted\par-redacted\venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
  ...
```

#### Scipy/Numpy/Python version information: Tried this on several different versions on scipy (1.7,1.5.1,1.6.1, etc) all with the same result. Python 3.

-->

**Comment by tupui** [comment]
Hi, thanks for posting. Could you post a minimal reproducible example? It's difficult to help you otherwise.

**Comment by rgommers** [comment]
Indeed, a full build/install log would be useful here.

**Comment by andyfaff** [comment]
Going to close the issue, no further information.
