### ISSUE TITLE
Raspberry Pi 4 aarch64: ModuleNotFoundError: No module named 'numpy.random.bit_generator'

### ISSUE THREAD

**Issue by kaoh** [scipy/scipy#14541]
I'm using the NLU framework [Rasa](https://rasa.com) using TensorFlow which is relying on scipy. I have no issues running the code on a amd64 platform, but I'm using a Raspberry Pi 4 aarch64 architecture, where I hit the problem:

> ModuleNotFoundError: No module named 'numpy.random.bit_generator'

I thought recompiling everything would fix this issue with:
    
    pip3 install scipy==1.7.1 numpy==1.18.5 scikit-learn==0.24.2 --no-cache-dir --no-binary :all:

but I get the same error.

I cannot update at least numpy, because version 1.19 is introducing some breaking changes and TensorFlow does not work anymore.

#### Reproducing code example:

The problem can be also reproduced by executing in a Python3 shell:

~~~shell
mkdir test
cd test
python3 -m venv venv
source venv/bin/activate
pip3 install scipy==1.7.1 numpy==1.18.5 scikit-learn==0.24.2
python3
~~~

~~~
from sklearn.model_selection import train_test_split
~~~

#### Error message:

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.model_selection import train_test_split
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/scipy/stats/distributions.py", line 11, in <module>
    from . import _discrete_distns
  File "/home/ubuntu/accessibility/a/venv/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py", line 19, in <module>
    from .biasedurn import (_PyFishersNCHypergeometric,
  File "biasedurn.pyx", line 1, in init scipy.stats.biasedurn
ModuleNotFoundError: No module named 'numpy.random.bit_generator'
>>> 
```

#### Scipy/Numpy/Python version information:

    1.7.1 1.18.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by rkern** [comment]
Unfortunately, numpy 1.18 renamed `bit_generator` to `_bit_generator` as part of an overall privatization of the modules in `numpy.random`. However, that particular module was intended to be public, so it was renamed back to `bit_generator` in 1.19. You can try downgrading to 1.17.

**Comment by kaoh** [comment]
This helps at this end, but unfortunately brings up:

    ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by rkern** [comment]
You may need to rebuild `thinc` with the version of numpy that you have installed.

**Comment by kaoh** [comment]
Currently trying this (again), I think I tried this already, but then TensorFlow complaint, maybe I have to rebuilt this also (which is taking a day), but I'm wondering why on amd64 platforms these issues do not exist, there must be something special with the aarch64 wheels.

**Comment by rgommers** [comment]
This does look like a bug in how we build the `biasedurn` module, it shouldn't try to use `numpy.random.bit_generator` for numpy < 1.1.9, see https://github.com/scipy/scipy/blob/master/scipy/stats/setup.py#L63.

Also, IIRC TensorFlow misdiagnosed the issue here, and should have changed their constraint. Indeed, downloading a TensorFlow 2.5.0 wheel I see:
```
Requires-Dist: numpy (~=1.19.2)
```
So any other NumPy version should work.

**Comment by tupui** [comment]
> Also, IIRC TensorFlow misdiagnosed the issue here, and should have changed their constraint. Indeed, downloading a TensorFlow 2.5.0 wheel I see:
> 
> ```
> Requires-Dist: numpy (~=1.19.2)
> ```
> 
> So any other NumPy version should work.

Yeah, they even refuse to support 1.20 for now because they don't want to have >1.20 in their CI...

**Comment by rgommers** [comment]
@tupui not sure what you mean, do you have a link? The Requires-Dist above says any numpy version is fine except 1.19.2. I don't see a `<1.19` constraint anywhere.

**Comment by tupui** [comment]
> @tupui not sure what you mean, do you have a link? The Requires-Dist above says any numpy version is fine except 1.19.2. I don't see a `<1.19` constraint anywhere.

There are multiple threads:
https://github.com/tensorflow/tensorflow/issues/47691
https://github.com/tensorflow/tensorflow/pull/48918#issuecomment-868734334

**Comment by rgommers** [comment]
What a mess. The attitude of the TensorFlow maintainers is that it's just not important for them. Both the bug and the unwillingness to fix it are 100% on their side.

**Comment by tupui** [comment]
> What a mess. The attitude of the TensorFlow maintainers is that it's just not important for them. Both the bug and the unwillingness to fix it are 100% on their side.

Totally... Glad to read it's not just me 😅

**Comment by kaoh** [comment]
I could create a workaround with a lot of compile time. All numpy modules have to be built from scratch. Important is `--no-build-isolation`, otherwise the buggy 1.18.5  version is used when building the wheel.

~~~shell
sudo apt-get install python3-dev python3-pip python3-venv python3-wheel libssl-dev
sudo apt-get install gcc gfortran python3-dev libopenblas-dev liblapack-dev
pip3 install wheel Cython
pip3 uninstall scipy spacy numpy blis thinc scikit-learn 
pip3 install numpy==1.17.5 pybind11 pythran=0.9.11
pip3 install scipy==1.7.1 blis==0.7.4 scikit-learn==0.24.2 thinc==8.0.8 spacy==3.0.7 --no-build-isolation --no-binary :all:
~~~

**Comment by rgommers** [comment]
I've looked into this, and the reason is this (from `pyproject.toml`):
```
    # numpy 1.19 was the first minor release to provide aarch64 wheels, but
    # wheels require fixes contained in numpy 1.19.2
    "numpy==1.19.2; python_version=='3.8' and platform_machine=='aarch64'",
```

This is what caused the original problem with numpy `1.18.5`: the `aarch64` wheel is built with `1.19.2`, so not usable with older NumPy versions.

The from-source build is fine, I verified the generated Cython code. The second reported problem here is a misunderstanding by the user.

The things that could be done here are:
1. declare this a non-issue and close it
2. have a clearer error message, so that `import scipy` says something like _"installed numpy version is too old"_
3. have `install_requires` entries for `numpy` which are different in each wheel build. so that if we build against `1.19.2`, it would say `install_requires>=1.19.2,<1.24.0` rather than using the global numpy minimum version (= `1.17.5` here).

Either (2) or (3) would be more correct, but annoying in terms of build infra / code generation. There is no way to run into this problem unless one mixed a wheel build with a from-source build, so it's not high prio. I think it'd be nice to fix, but it's not blocking for `1.17.3`.

**Comment by rgommers** [comment]
Thinking about this again, the way to fix this is to add `installed_numpy_version = x.y.z` to `_distributor_init` at wheel build time and use that from the main `__init__.py`. Not too hard to implement, and should be robust.

Moving to the `1.8.0` milestone.

**Comment by rgommers** [comment]
We got another report about this (gh-15209), so should prioritize this and try to backport the fix.

**Comment by mihaimaruseac** [comment]
TF should now support numpy > 1.20 :) (TF maintainer here :P)

**Comment by rgommers** [comment]
Thanks @mihaimaruseac!

**Comment by tirthasheshpatel** [comment]
@rgommers Should we consider closing this now? Now that it's fixed on TF side, I don't know if it's worth doing (2) or (3).

**Comment by rgommers** [comment]
Good point Tirth. If one waits long enough, some problems fix themselves:)

In this case, let's close it when we drop numpy `1.18.x` support, which we can do for the next release. No need to backport to `1.8.1` anymore I'd say.

**Comment by rgommers** [comment]
Actually we stuck with numpy 1.18.5 for the 1.9.0 release, so bumping the milestone to `1.10.0`.

**Comment by rgommers** [comment]
Upgraded to 1.19.5 as minimum version now in `main`, so this will be fixed in 1.10.0. Nothing further to do, so I'll close it now.

If anyone still runs into this for 1.9.0: use numpy >=1.19.5 to build (use `pip install scipy --no-build-isolation` to avoid picking up numpy 1.18.x) if needed, or build from `main`.
