### ISSUE TITLE
not able to install scipy 1.7.1 and  1.7.0 in alphine linux  3.14.0 version

### ISSUE THREAD

**Issue by navengp** [scipy/scipy#14550]
HI ,

i am trying to install scipy package of version 1.7.1 in alphine linux 3.14.0 version getting following error.

command :  python3 -m pip install scipy

(3/3) Installing .builddeps (20210804.132804)
Executing busybox-1.33.1-r3.trigger
OK: 399 MiB in 95 packages
Collecting scipy
  Downloading scipy-1.7.1.tar.gz (36.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status -11:
     command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxsne7l14
         cwd: /tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0
    Complete output (61 lines):
    setup.py:490: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-rokvf19e'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    Running scipy/linalg/_generate_pyx.py
    Running scipy/special/_generate_pyx.py
    Running scipy/stats/_generate_pyx.py
    Processing scipy/sparse/_csparsetools.pyx.in
    Processing scipy/sparse/csgraph/_traversal.pyx
    Processing scipy/sparse/csgraph/_tools.pyx
    Processing scipy/sparse/csgraph/_shortest_path.pyx
    Processing scipy/sparse/csgraph/_flow.pyx
    Processing scipy/sparse/csgraph/_matching.pyx
    Processing scipy/sparse/csgraph/_reordering.pyx
    Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
    Processing scipy/io/matlab/mio5_utils.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 324, in <module>
        main()
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 320, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 309, in find_process_files
        for result in pool.imap_unordered(lambda args: process(*args), jobs):
      File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
        raise value
      File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 309, in <lambda>
        for result in pool.imap_unordered(lambda args: process(*args), jobs):
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 243, in process
        processor_function(fromfile, tofile, cwd=path)
      File "/tmp/pip-install-uxrm3lbb/scipy_5680caa76656464c8556c0477f8364c0/tools/cythonize.py", line 108, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "setup.py", line 356, in generate_cython
        import pip
    ModuleNotFoundError: No module named 'pip'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-djadfjth/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-djadfjth/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-djadfjth/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 629, in <module>
        setup_package()
      File "setup.py", line 613, in setup_package
        generate_cython()
      File "setup.py", line 365, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!

i tried for the version 1.7.0 version getting same error as above.
command:  python3 -m pip install scipy==1.7.0

python version that i am using is 3.9.5
can you please what is the problem is there any configuration issue for it?

**Comment by rgommers** [comment]
Sorry this fell through the cracks @navengp. I'm pretty sure was fixed recently.
