### ISSUE TITLE
`shgo` error since scipy 1.8.0.dev0+1529.803e52d 

### ISSUE THREAD

**Issue by ericpre** [scipy/scipy#14589]
`shgo` raises an error with the following example since scipy 1.8.0.dev0+1529.803e52d.

This error was noticed in the hyperspy test suite (https://github.com/hyperspy/hyperspy-extensions-list/actions/runs/1111267440) and previous scipy development version (1.8.0.dev0+1503.8647ee9) didn't raise an error. Scipy development version are installed from https://pypi.anaconda.org/scipy-wheels-nightly/simple.

#### Reproducing code example:

```python
import sys

import numpy as np
import scipy
from scipy.optimize import shgo

print(scipy.__version__, np.__version__, sys.version_info)


def func(x_values, param):
    a, b = param
    return a*x_values + b


def errfunc(param, y):
    return func(x_values, param) - y


def errfunc_sq(param, y, weights=None):
    if weights is None:
        weights = 1.0
    return ((weights * errfunc(param, y)) ** 2).sum()

x_values = np.arange(100)
y_values = func(x_values, (2, 10)) + np.random.random(x_values.size)

results = shgo(errfunc_sq,
               bounds=((-100, 100), (-100, 100)),
               args=(y_values, None)
               )

print(results)
```

#### Error message:

```python
1.8.0.dev0+1529.803e52d 1.21.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo_lib/triangulation.py", line 630, in __getitem__
    return self.cache[x]
KeyError: (0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "untitled0.py", line 34, in <module>
    results = shgo(errfunc_sq,
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 420, in shgo
    shc.construct_complex()
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 733, in construct_complex
    self.iterate()
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 876, in iterate
    self.iterate_complex()
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo.py", line 895, in iterate_hypercube
    self.HC = Complex(self.dim, self.func, self.args,
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo_lib/triangulation.py", line 25, in __init__
    self.n_cube(dim, symmetry=symmetry)
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo_lib/triangulation.py", line 76, in n_cube
    self.C0.add_vertex(self.V[origintuple])
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo_lib/triangulation.py", line 634, in __getitem__
    xval = Vertex(x, bounds=self.bounds,
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/_shgo_lib/triangulation.py", line 557, in __init__
    self.f = func(x_a, *func_args)
  File "/opt/miniconda3/envs/test_env/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 464, in function_wrapper
    fx = function(np.copy(x), *(wrapper_args + args))
TypeError: errfunc_sq() takes from 2 to 3 positional arguments but 5 were given
```

#### Scipy/Numpy/Python version information:

1.8.0.dev0+1529.803e52d 1.21.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thanks for the report. @Stefan-Endres is working on a PR that is going to refactor quite some things. Stefan, does your PR address this?

**Comment by Stefan-Endres** [comment]
Thank you for the report @ericpre. @tupui this is a new bug, but on the old caching please keep the issue open I will fix this in the new caching library.

**Comment by ericpre** [comment]
It seems that the regression has been introduced in https://github.com/scipy/scipy/pull/14274.

**Comment by jjramsey** [comment]
I think I've found a solution. On line 900 of `scipy/optimize/_shgo.py`, change
```python
self.HC = Complex(self.dim, self.func, self.args,
```
to
```python
self.HC = Complex(self.dim, self.func, (),
```
What's happening is that since `self.func` already contains the contents of `self.args`, when `Complex` is constructed, it effectively includes `self.args` *twice*, so when it calls the objective function, it effectively calls it as `func(x, *(args+args))`.

Unfortunately, an alternative like setting `self.func` to `_wrap_scalar_function(func, ())` doesn't work, since there are other places in the code where it's assumed that `self.func` wraps the contents of `self.args`. `self.args` is also used in other places in the code, so setting it to `()` probably won't work either. If the sampling method is changed from the default `simplicial`, SHGO still appears to work properly, regardless of my change. The change I recommend appears to be the most minimal change needed to get SHGO to work with externally supplied arguments again.

**Comment by tupui** [comment]
There are large development in progress changing the whole architecture of `shgo`. We will keep these in mind.

**Comment by jjramsey** [comment]
Understood, but bear in mind that this bug is not only almost a year old, but breaks some very basic documented functionality. A minimal fix now will provide an indicator to those making large changes of what should or shouldn't be done with function arguments, while solving a problem facing end users of SHGO now.

**Comment by tupui** [comment]
The large developments are happening here #14013

**Comment by jjramsey** [comment]
Looks like the pull request for those large developments has been stalled since Jul 26, 2021, apparently due to some automatic tests failing for some unclear reason. Any way to rerun the tests to see if the failure was a fluke (or perhaps some fault in the Azure pipelines)?

**Comment by tupui** [comment]
@jjramsey the PR is not staled due to failing tests but it's conditioned to maintainers time to work on SciPy. Most of us are volunteers and don't have much time to work on SciPy.

**Comment by WarrenWeckesser** [comment]
@abianco88, I posted this answer to your question, the essential part of which is:

> You can avoid the bug in `shgo` by avoiding the use of the `args` parameter. Instead of using `args`, use a wrapper of `fobj` that captures `y` and `z` in a closure.  A simple way to do that is with a `lambda` expression: change the first argument of `shgo` from `func=fobj` to `func=lambda x, y=y, z=z: fobj(x, y, z)`, and remove the `args` parameter from the call.
