### ISSUE TITLE
BUG: Error constructing sparse matrix with indices larger than 32 bits from smaller matrices, using sparse.bmat()

### ISSUE THREAD

**Issue by theo649** [scipy/scipy#14623]
When constructing a sparse matrix with indices larger than 32-bits from smaller matrices with indices that fit in 32-bits, I am getting the following error:
```
python debugConstructH.py 
Traceback (most recent call last):
  File "debugConstructH.py", line 11, in <module>
    H = sparse.bmat([[B,B],[B,A]], format='csr')    
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx/Core/scipy-stack/2021a/lib/python3.8/site-packages/scipy/sparse/construct.py", line 625, in bmat
    return coo_matrix((data, (row, col)), shape=shape).asformat(format)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx/Core/scipy-stack/2021a/lib/python3.8/site-packages/scipy/sparse/coo.py", line 196, in __init__
    self._check()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx/Core/scipy-stack/2021a/lib/python3.8/site-packages/scipy/sparse/coo.py", line 287, in _check
    raise ValueError('negative row index found')
ValueError: negative row index found
```
This error is produced by the following code:

```
from scipy import sparse
import numpy as np

n = 1100000000  # Greater than half of 2^31
indices = np.array([n-1])
vals = np.array([1])
A = sparse.csr_matrix((vals,(indices,indices)),[n,n])
B = sparse.csr_matrix((n,n))

# 2n x 2n Diagonal matrix, with non-zero value at bottom right of matrix
H = sparse.bmat([[B,B],[B,A]], format='csr')
```
Any help is greatly appreciated.

**Comment by kevinrichardgreen** [comment]
The offenders are the two lines at https://github.com/scipy/scipy/blob/master/scipy/sparse/construct.py#L621
When the blocks are small enough to work with 32bit indices, `B.row` and `B.col` are np.int32, and the addition is type-narrowing. A quick fix is to replace them with 
```
        row[idx] = np.int64(B.row) + row_offsets[i]
        col[idx] = np.int64(B.col) + col_offsets[j]
```
But there is probably a better way upstream to handle that.

**Comment by tupui** [comment]
Thanks @theo649. In general we could maybe have a better story around types as we rely on lot of compiled code. We don't have things like `dtype` to handle this and it's very function dependant what we do.
