### ISSUE TITLE
BUG: (sort of) mannwhitneyu hits max recursion limit with imbalanced input sizes due to selection of 'exact' method; could method selection depend on max(n1,n2)?

### ISSUE THREAD

**Issue by phbradley** [scipy/scipy#14622]
### Reproducing Code Example

```python
from scipy.stats import mannwhitneyu
import numpy as np
a = np.random.randn(5)
b = np.random.randn(5000)
mannwhitneyu(a,b)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 414, in mannwhitneyu
    p = _mwu_state.sf(U.astype(int), n1, n2)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 53, in sf
    return self.cdf(k, m, n)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 41, in cdf
    pmfs = self.pmf(np.arange(0, np.max(k) + 1), m, n)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 33, in pmf
    self._f(m, n, i)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  [Previous line repeated 991 more times]
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 71, in _f
    if k < 0 or m < 0 or n < 0 or k > m*n:
RecursionError: maximum recursion depth exceeded in comparison
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by phbradley** [comment]
Hi there, sorry if this isn't a BUG per se, but it did break our code when we updated to the newest scipy. Of course, there's an easy work-around, but I wonder if the method selection logic could take into account the sizes of both inputs.

**Comment by mdhaber** [comment]
Good idea. 
You can add `method='asymptotic'`, since those are the p-values you were getting before.

**Comment by phbradley** [comment]
Thanks, yes, that's what I am doing now (specifying method). It's just a tiny bit tricky since older mannwhitneyu code (which we still need to account for) doesn't know about method as an argument, so I have to do a little check first.

**Comment by mdhaber** [comment]
As suggested above, the quick fix would be to figure out some additional conditions for choosing the asymptotic method and add them [here](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_mannwhitneyu.py#L164).

Another possibility would be for [`_MWU`](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_mannwhitneyu.py#L19) to remember its own stack.

**Comment by szkafander** [comment]
@mdhaber I have an iterative solution that post-order traverses the stack (binary tree) with memoization. It uses a list as a stack. Solution is equivalent to your implementation but takes about twice the time as native recursion. IMHO the best course of action is to use a check on n and m and if one is <8 and the other is large (would hit the recursion limit), switch to the iterative solution and issue a warning. I don't think the iterative solution can be as fast as recursion. Would you be OK with iteration being a little slower than recursion?
