### ISSUE TITLE
CI for Python 3.10 failing with mypy 

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14668]
This just started, recent log in https://github.com/scipy/scipy/pull/14666/checks?check_run_id=3464627479
```
Traceback (most recent call last):
  File "/home/runner/work/scipy/scipy/runtests.py", line 565, in <module>
    main(argv=sys.argv[1:])
  File "/home/runner/work/scipy/scipy/runtests.py", line 150, in main
    sys.exit(run_mypy(args))
  File "/home/runner/work/scipy/scipy/runtests.py", line 523, in run_mypy
    report, errors, status = mypy.api.run([
  File "/home/runner/.local/lib/python3.10/site-packages/mypy/api.py", line 68, in run
    from mypy.main import main
  File "/home/runner/.local/lib/python3.10/site-packages/mypy/main.py", line 11, in <module>
    from typing_extensions import Final, NoReturn
  File "/home/runner/.local/lib/python3.10/site-packages/typing_extensions.py", line 2390, in <module>
    class _ConcatenateGenericAlias(list):
  File "/home/runner/.local/lib/python3.10/site-packages/typing_extensions.py", line 2394, in _ConcatenateGenericAlias
    __class__ = _GenericAlias
NameError: name '_GenericAlias' is not defined
Error: Process completed with exit code 1.
```
Giving the timing of the failures starting, it could be related to gh-14655 - or it could be something that changed in `typing_extensions` or in Python 3.10

**Comment by rgommers** [comment]
Oh looks like it's already being fixed by a new `typing_extensions` release that just landed on PyPI. xref https://github.com/python/typing/pull/871

**Comment by rgommers** [comment]
Indeed fixed again, closing.
