### ISSUE TITLE
BUG: multiplying CSR matrix by a constant instantiates huge dense index arrays

### ISSUE THREAD

**Issue by jszymon** [scipy/scipy#14674]
### Reproducing Code Example

```python
from scipy.sparse import coo_matrix

A = coo_matrix(([5.0,5.0], ([0, 1000_000], [0, 1000_000])))
A = A.tocsr()
A[:,0:10000] *= -1
```

### Error message

```shell
Traceback (most recent call last):
  File "/tmp/test_sparse_mul.py", line 5, in <module>
    A[:,0:10000] *= -1
  File "/home/s/.local/lib/python3.9/site-packages/scipy/sparse/_index.py", line 116, in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
  File "/home/s/.local/lib/python3.9/site-packages/scipy/sparse/compressed.py", line 808, in _set_arrayXarray_sparse
    self._zero_many(*self._swap((row, col)))
  File "/home/s/.local/lib/python3.9/site-packages/scipy/sparse/compressed.py", line 924, in _zero_many
    i, j, M, N = self._prepare_indices(i, j)
  File "/home/s/.local/lib/python3.9/site-packages/scipy/sparse/compressed.py", line 874, in _prepare_indices
    i = np.array(i, dtype=self.indices.dtype, copy=False, ndmin=1).ravel()
numpy.core._exceptions.MemoryError: Unable to allocate 37.3 GiB for an array with shape (1000001, 10000) and data type int32
```

### SciPy/NumPy/Python version information

1.7.1 1.19.5 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by stefanv** [comment]
This only happens when the slice is unassigned.  I.e., the following works:

```
B = A[:,0:10000]
B *= -1
```

**Comment by jszymon** [comment]
Thanks for looking into this.  The code above works, but doing

`A[:,0:10000] = B`

results in a similar problem.  So there is no way to change sign
of selected elements.  Actually the slice sign change operation
is used in `scipy.optimize.linprog`.

The following works:

`A.data[A.indices < 10000] *= -1`

but is a hack.
