### ISSUE TITLE
CI for Python 3.10 is failing due to a change in Pythran master

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14687]
See for example https://github.com/scipy/scipy/pull/14673/checks?check_run_id=3499875442:

```
Running from SciPy source directory.
Traceback (most recent call last):
  File "/home/runner/work/scipy/scipy/setup.py", line 631, in <module>
    setup_package()
  File "/home/runner/work/scipy/scipy/setup.py", line 608, in setup_package
    cmdclass['build_ext'] = get_build_ext_override()
  File "/home/runner/work/scipy/scipy/setup.py", line 240, in get_build_ext_override
    import pythran
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/__init__.py", line 41, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/backend.py", line 7, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/home/runner/.local/lib/python3.10/site-packages/pythran/tables.py", line 4524, in <module>
    omp_version = getattr(__import__('omp'), 'VERSION', 45)
  File "/home/runner/.local/lib/python3.10/site-packages/omp/__init__.py", line 140, in <module>
    sys.modules[__name__] = OpenMP()
  File "/home/runner/.local/lib/python3.10/site-packages/omp/__init__.py", line 33, in __init__
    self.init_not_msvc()
  File "/home/runner/.local/lib/python3.10/site-packages/omp/__init__.py", line 125, in init_not_msvc
    "or adjust the {} environment variable.".format(env_vars[O]))
NameError: name 'O' is not defined
```

**Comment by rgommers** [comment]
fixed upstream
