### ISSUE TITLE
ENH: rotate a 2D meshgrid

### ISSUE THREAD

**Issue by srkunze** [scipy/scipy#14711]
### Is your feature request related to a problem? Please describe.

https://github.com/numpy/numpy/issues/19315

### Describe the solution you'd like.

Something like the following (just working):

```
import numpy as np
from scipy.spatial.transform import Rotation as R

T_size = slice(2, 30, 1)
P_size = slice(0, 80, 2)
grid = np.mgrid[T_size, P_size]

r = R.from_euler('z', 1)
r.apply(grid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rotation.pyx", line 1667, in scipy.spatial.transform.rotation.Rotation.apply
ValueError: Expected input of shape (3,) or (P, 3), got (2, 28, 40).
```

### Describe alternatives you've considered.

cf. the SO entry

**Comment by rkern** [comment]
As discussed in the originating issue, the meshgrid is not the important bit. The user has an array of 2D vectors and wants a convenient way to rotate them. `Rotation` gives us a way to represent and apply rotations in 3D space. It would be nice to have some kind of API for at least getting the canonical 2D rotation matrix given an angle.
