### ISSUE TITLE
BUG:`import scipy.io` error

### ISSUE THREAD

**Issue by gongyibei** [scipy/scipy#14747]
### Describe your issue.

The existence of `copy.py` in the same directory will cause the error of `import scipy.io`

### Reproducing Code Example

```python
# .
#├── copy.py   (empty file)
#└── test.py

# test.py
import scipy.io
```

### Error message

```shell
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import scipy.io
  File "~/anaconda3/lib/python3.8/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "~/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/__init__.py", line 11, in <module>
    from .mio import loadmat, savemat, whosmat
  File "~/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 10, in <module>
    from .mio5 import MatFile5Reader, MatFile5Writer
  File "~/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/mio5.py", line 95, in <module>
    from .mio5_utils import VarReader5
  File "mio5_utils.pyx", line 17, in init scipy.io.matlab.mio5_utils
ImportError: cannot import name copy
```

### SciPy/NumPy/Python version information

1.6.2 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
`copy` is a builtin standard library module of Python like `os` or `sys`. You shouldn't use filenames that clashes with stdlib names.
