### ISSUE TITLE
BUG: scipy.stats.bootstrap unable to deal with constant samples

### ISSUE THREAD

**Issue by Saibo-creator** [scipy/scipy#14804]
### Describe your issue.

It seems scipy.stats.boostrap will raise an error when the sample data are constant numbers. From the statistical perspective, I agree that bootstrap may not be used on constant numbers. So raising an error may be ok, but we may also consider the confidence interval to be 0 which would not stop the program. 

If you think it's a better idea to raise an error, maybe the error message could be more self-explain ? 

Thanks

### Reproducing Code Example

```python
from scipy import stats
import numpy as np
stats.bootstrap([[1]*10],statistic=np.mean)
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/saibo/Research/project001/BT-eval-metric-corr/debug.py", line 24, in <module>
    stats.bootstrap([[1]*10],statistic=np.mean)
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/scipy/stats/_bootstrap.py", line 454, in bootstrap
    ci_l = percentile_fun(theta_hat_b, interval[0]*100)
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/scipy/stats/_bootstrap.py", line 78, in _percentile_along_axis
    percentiles[indices] = np.percentile(theta_hat_b_i, alpha_i)
  File "<__array_function__ internals>", line 5, in percentile
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3818, in percentile
    return _quantile_unchecked(
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3937, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3515, in _ureduce
    r = func(a, **kwargs)
  File "/opt/anaconda3/envs/BT-eval-metric/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4047, in _quantile_ureduce_func
    ap.partition(concatenate((
ValueError: kth(=-9223372036854765809) out of bounds (9999)
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
gh-14351 would fix this. It's waiting for review if you'd like to take a look.

**Comment by AEYOU** [comment]
Same problem on 5th July 2022.
