### ISSUE TITLE
MAINT, DOC: CI failure for doc building

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#14911]
I see the traceback below the fold in several unrelated PRs/merge event doc builds in the last day or two. The `pyparsing` library shows up in the error output, and I note that version `3.0.0` was released on Oct. 23/2021 and `3.0.1` just 5 hours ago. Before that, there were nothing but pre-releases going back to April 2020, so this seems like a decent candidate for the source of the error.

We may want to temporarily pin `pyparsing` as an interim workaround.

<details>

```
waiting for workers...
/home/circleci/repo/build/testenv/lib/python3.8/site-packages/scipy/integrate/_quad_vec.py:docstring of scipy.integrate._quad_vec.quad_vec:126: WARNING: Exception occurred in plotting scipy-integrate-quad_vec-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.integrate.quad_vec.rst:
pyparsing.exceptions.ParseException: Expected {accentprefixed | accent | symbol | c_over_c | function | group | frac | dfrac | binom | genfrac | overset | underset | sqrt | overline | operatorname}, found 'dx'  (at char 22), (line:1, col:23)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/_mathtext.py", line 2277, in parse
    result = self._expression.parseString(s)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/pyparsing/core.py", line 1101, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseSyntaxException: Expected {accentprefixed | accent | symbol | c_over_c | function | group | frac | dfrac | binom | genfrac | overset | underset | sqrt | overline | operatorname}, found 'dx'  (at char 22), (line:1, col:23)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 612, in render_figures
    figman.canvas.figure.savefig(img.filename(fmt), dpi=dpi)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 508, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/axis.py", line 1155, in draw
    self.label.draw(renderer)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/text.py", line 679, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/text.py", line 314, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 235, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/mathtext.py", line 452, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/mathtext.py", line 473, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/_mathtext.py", line 2279, in parse
    raise ValueError("\n".join(["",
ValueError: 
\int_{0}^{2} x^\alpha dx
                      ^
Expected {accentprefixed | accent | symbol | c_over_c | function | group | frac | dfrac | binom | genfrac | overset | underset | sqrt | overline | operatorname}, found 'dx'  (at char 22), (line:1, col:23)
```

</details>

**Comment by Smit-create** [comment]
This seems to be working fine with pyparsing version `3.0.2`

**Comment by tylerjereddy** [comment]
Fixed by gh-14969 (or rather, but upstream stuff happening, so the pin was removed)
