### ISSUE TITLE
BUG: An issue with using the command line `python runtests.py -s sparse`

### ISSUE THREAD

**Issue by zhaog6** [scipy/scipy#15115]
### Describe your issue.

Dear all, I recently updated SciPy  on my laptop and use `python runtests.py -s sparse` to test the modified codes of the sparse module. But I encounter an issue. It reports the following error
```bash
RuntimeError: Missing the `PROPACK` submodule! Run `git submodule update --init` to fix this
```
and then I run the command line `git submodule update --init` again, but it still reports this error and specific details as "Error message". Could anyone help me solve it?

### Reproducing Code Example

```python
None
```

### Error message

```shell
Traceback (most recent call last):
  File "setup.py", line 622, in <module>
    setup_package()
  File "setup.py", line 618, in setup_package
    setup(**metadata)
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 528, in configuration
    config.add_subpackage('scipy')
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 20, in configuration
    config.add_subpackage('sparse')
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/sparse/setup.py", line 14, in configuration
    config.add_subpackage('linalg')
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/sparse/linalg/setup.py", line 14, in configuration
    config.add_subpackage('_propack')
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/zhaog6/zg/python3-venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/sparse/linalg/_propack/setup.py", line 36, in configuration
    check_propack_submodule()
  File "scipy/sparse/linalg/_propack/setup.py", line 13, in check_propack_submodule
    raise RuntimeError("Missing the `PROPACK` submodule! Run "
RuntimeError: Missing the `PROPACK` submodule! Run `git submodule update --init` to fix this.

Build failed! (0:00:01.002321 elapsed)
```

### SciPy/NumPy/Python version information

1.7.3 1.21.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
Do you have the followng directory in your scipy repository: `scipy/sparse/linalg/_propack/PROPACK`?

**Comment by zhaog6** [comment]
> Do you have the followng directory in your scipy repository: `scipy/sparse/linalg/_propack/PROPACK`?

Yes, the `PROPACK` exists, but only `.git` in `PROPACK`.

**Comment by andyfaff** [comment]
How about `git submodule init; git submodule update`?

**Comment by zhaog6** [comment]
The command line indeed grab the files, and I use the command line `git submodule init; git submodule update` again, the output is as follow
![2021-11-29 19-22-17 的屏幕截图](https://user-images.githubusercontent.com/31978442/143859611-54d7ad9f-57fa-4a08-908e-aed9dfa200d2.png)

**Comment by andyfaff** [comment]
So are the files there now?

**Comment by zhaog6** [comment]
Still only `.git` exists in `PROPACK`.

**Comment by zhaog6** [comment]
I try it on my laptop, server respectively, there seems to be this problem.

**Comment by zhaog6** [comment]
My system is Ubuntu 20.04.3.

**Comment by tupui** [comment]
> The command line indeed grab the files, and I use the command line `git submodule init; git submodule update` again, the output is as follow
> ![2021-11-29 19-22-17 的屏幕截图](https://user-images.githubusercontent.com/31978442/143859611-54d7ad9f-57fa-4a08-908e-aed9dfa200d2.png)

@zhaog6 The submodule is not defined there but in the main folder under `scipy/.gitmodules`. Can you try to do the submodule initialization at the root of SciPy?

**Comment by zhaog6** [comment]
There is still this problem, the output is as follows
![Uploading 2021-11-30 08-46-07 的屏幕截图.png…]()

**Comment by andyfaff** [comment]
Maybe something is wrong with your git setup. The following demonstrates that my suggestion works:
```
(dev3) 192-168-1-103:temp andrew$ git clone https://github.com/scipy/scipy.git
Cloning into 'scipy'...
remote: Enumerating objects: 192071, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 192071 (delta 2), reused 3 (delta 0), pack-reused 192064
Receiving objects: 100% (192071/192071), 133.58 MiB | 6.25 MiB/s, done.
Resolving deltas: 100% (148374/148374), done.
Updating files: 100% (3268/3268), done.
(dev3) 192-168-1-103:temp andrew$ cd scipy
(dev3) 192-168-1-103:scipy andrew$ ls
CITATION.bib		LICENSE.txt		azure-pipelines.yml	doc			mypy_requirements.txt	runtests.py		tools
CONTRIBUTING.rst	LICENSES_bundled.txt	benchmarks		doc_requirements.txt	pavement.py		scipy			tox.ini
HACKING.rst.txt		MANIFEST.in		ci			environment.yml		pyproject.toml		setup.py
INSTALL.rst.txt		README.rst		codecov.yml		mypy.ini		pytest.ini		site.cfg.example
(dev3) 192-168-1-103:scipy andrew$ cd scipy/sparse/linalg/
(dev3) 192-168-1-103:linalg andrew$ ls
__init__.py		_expm_multiply.py	_matfuncs.py		_propack		eigen.py		matfuncs.py
_dsolve			_interface.py		_norm.py		_svdp.py		interface.py		setup.py
_eigen			_isolve			_onenormest.py		dsolve.py		isolve.py		tests
(dev3) 192-168-1-103:linalg andrew$ cd _propack/
(dev3) 192-168-1-103:_propack andrew$ ls
PROPACK		cpropack.pyf	dpropack.pyf	setup.py	spropack.pyf	zpropack.pyf
(dev3) 192-168-1-103:_propack andrew$ cd PROPACK/
(dev3) 192-168-1-103:PROPACK andrew$ ls
(dev3) 192-168-1-103:PROPACK andrew$ ls -al
total 0
drwxr-xr-x  2 andrew  staff   64 30 Nov 11:59 .
drwxr-xr-x  9 andrew  staff  288 30 Nov 11:59 ..
(dev3) 192-168-1-103:PROPACK andrew$ cd ..
(dev3) 192-168-1-103:_propack andrew$ git submodule init
Submodule 'doc/source/_static/scipy-mathjax' (https://github.com/scipy/scipy-mathjax.git) registered for path '../../../../doc/source/_static/scipy-mathjax'
Submodule 'doc/sphinxext' (https://github.com/numpy/numpydoc.git) registered for path '../../../../doc/sphinxext'
Submodule 'scipy/_lib/boost' (https://github.com/scipy/boost-headers-only) registered for path '../../../_lib/boost'
Submodule 'scipy/_lib/unuran' (https://github.com/scipy/unuran.git) registered for path '../../../_lib/unuran'
Submodule 'scipy/sparse/linalg/_propack/PROPACK' (https://github.com/scipy/PROPACK) registered for path 'PROPACK'
(dev3) 192-168-1-103:_propack andrew$ git submodule update
Cloning into '/Users/andrew/Desktop/temp/scipy/doc/source/_static/scipy-mathjax'...
Cloning into '/Users/andrew/Desktop/temp/scipy/doc/sphinxext'...
Cloning into '/Users/andrew/Desktop/temp/scipy/scipy/_lib/boost'...
Cloning into '/Users/andrew/Desktop/temp/scipy/scipy/_lib/unuran'...
Cloning into '/Users/andrew/Desktop/temp/scipy/scipy/sparse/linalg/_propack/PROPACK'...
Submodule path '../../../../doc/source/_static/scipy-mathjax': checked out '3d21c58225c09243d5a088b1557654d280925e02'
Submodule path '../../../../doc/sphinxext': checked out 'd2baf3a4cac5895ed85fb94636d75dea59f3ac75'
remote: Enumerating objects: 3519, done.
remote: Counting objects: 100% (3519/3519), done.
remote: Compressing objects: 100% (1590/1590), done.
remote: Total 1949 (delta 1619), reused 678 (delta 350), pack-reused 0
Receiving objects: 100% (1949/1949), 1.20 MiB | 5.75 MiB/s, done.
Resolving deltas: 100% (1619/1619), completed with 1258 local objects.
From https://github.com/scipy/boost-headers-only
 * branch              2110ce20e59917b85b12059b3ddd8b133549f662 -> FETCH_HEAD
Submodule path '../../../_lib/boost': checked out '2110ce20e59917b85b12059b3ddd8b133549f662'
Submodule path '../../../_lib/unuran': checked out '993f84a70ea4788f85b2343eb6eaef2204e94ec1'
Submodule path 'PROPACK': checked out 'fb21d62f0167bf07aa3a48f6169c29ddc314f046'
(dev3) 192-168-1-103:_propack andrew$ ls
PROPACK		cpropack.pyf	dpropack.pyf	setup.py	spropack.pyf	zpropack.pyf
(dev3) 192-168-1-103:_propack andrew$ cd PROPACK/
(dev3) 192-168-1-103:PROPACK andrew$ ls
Changelog	Make		Makefile	README		complex16	complex8	configure	double		license.txt	make.inc	single
```

**Comment by zhaog6** [comment]
I reinstall scipy and track the outputs.

**Comment by zhaog6** [comment]
@andyfaff Everything is normal on my macOS 12.0.1 platform, but on my Ubuntu 20.04.3, it still reports the error. I don't know if it is a problem caused by networks or different operating system platform

**Comment by zhaog6** [comment]
I use docker image and container, on Ubuntu 20.04, This problem always seems to arise.

**Comment by andyfaff** [comment]
Is the git version a lot older on Ubuntu? Anyway, could you just mount the scipy directory as a virtual directory in the docker container?

**Comment by andyfaff** [comment]
I don't really think this is ultimately a scipy issue though.

**Comment by zhaog6** [comment]
My git version is 2.25.1, I feel it may be networks, but the problem has puzzled me for weeks. I also try reinstall operating system, venv, scipy etc, even install and use scipy in docker container, but the problem always occur.

**Comment by zhaog6** [comment]
This error has never happened before on Ubuntu 20.04, it's a little strange

**Comment by zhaog6** [comment]
I resolved the problem, it is indeed affected by my networks environment. To avoid it, I used `git clone https://github.com/scipy/unuran` in `scipy/scipy/_lib/` and `git clone https://github.com/scipy/PROPACK` in `_propack/` to download `unuran` and `PROPACK` respectively after makeing `git submodule update --init`. Thanks @andyfaff and @tupui for your reminders and suggestions.
