### ISSUE TITLE
[Bug]: ValueError: too many values to unpack (expected 2) on scipy.signal.pcolormesh

### ISSUE THREAD

**Issue by panos1998** [scipy/scipy#15174]
### Describe your issue.

My code below  records a  sound from microphone and stores it as numpy array in voice array. The problem is that i followed the scipy documentation of scipy.signal.pcolormesh but i cannot understand why this error is thrown. It says too many values to unpack expected two, then i unpack 2 and it throws error: expected 1 or  3 positional arguments. My code could be more definite way to understand the problem

### Reproducing Code Example

```python
import matplotlib.pyplot as plt
import numpy as np
import sounddevice as sd
from scipy import signal

Fs = 8000  # Sampling frequency
duration = 5  # Recording duration in seconds
voice = sd.rec(frames=duration * Fs, samplerate=Fs, channels=1, dtype='int16')  # Capture the voice
# frames indicate  indirectly the duration of record, dtype is 16 bits per sample.
sd.wait()  # close after recording finish

time = np.linspace(0, len(voice - 1) / Fs, len(voice - 1))  # split x axis in voice-1 points
# points have 1/Fs distance each other
plt.plot(voice)
plt.ylabel('Voice amplitude')
plt.xlabel('No of sample')
plt.title("Voice Signal with respect to sample number")
plt.show()
plt.plot(time, voice)  # plot in seconds
plt.title("Voice Signal")
plt.xlabel("Time [seconds]")
plt.ylabel("Voice amplitude")
plt.show()
plt.plot((10**3)*time, voice)  # plot in milliseconds
plt.title("Voice Signal")
plt.xlabel("Time [milliseconds]")
plt.ylabel("Voice amplitude")
plt.show()

N = len(voice)
# Fourier transform
F = np.fft.fft(voice)
f = np.linspace(0, Fs - Fs / N, N)
plt.plot(f, abs(F))
plt.title("FFT of the signal")
plt.xlabel('Frequency')
plt.ylabel('Signal Amplitude')
plt.show()
# Vocals recorded with the following order e\ a\ o\  ii\
# It seems that a and o are very close, but magnitude and frequency of e is significant lower
# Also i has very high frequency but too low magnitude



freq, t, Sxx = signal.spectrogram(voice, Fs, nperseg=1)
print(freq)
print(t)
print(Sxx)
print(len(Sxx))
print(len(Sxx[0]))
plt.pcolormesh(t, freq, Sxx, shading='gouraud')
plt.ylabel('Frequency [Hz]')
plt.xlabel('Time [seconds]')
plt.show()
```

### Error message

```shell
Traceback (most recent call last):
  File "C:\Users\Πανος\Documents\GitHub\EMB\Voice_Capture.py", line 52, in <module>
    plt.pcolormesh(t, freq, Sxx, shading='gouraud')
  File "C:\Users\Πανος\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 2718, in pcolormesh
    __ret = gca().pcolormesh(
  File "C:\Users\Πανος\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\Πανος\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_axes.py", line 6016, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "C:\Users\Πανος\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\axes\_axes.py", line 5504, in _pcolorargs
    nrows, ncols = C.shape
ValueError: too many values to unpack (expected 2)
```

### SciPy/NumPy/Python version information

1.7.3/1.21.4/3.10.1

**Comment by panos1998** [comment]
I think i found the error. For some reason the voice np-array had subarray elements like that [[1] [2]....[100]] so it was 2-dim array. I used np.array.flatten() and worked specgram
