### ISSUE TITLE
BUG: Changing data attribute due to conversion to other format

### ISSUE THREAD

**Issue by MorganPhobo5** [scipy/scipy#15226]
### Describe your issue.

Good day. 
I have sparse coo matrix with shape (7693, 2155830) with unique values (-1, 1) and dtype np.int64 
So, when i convert it to csr format np.unique  returns (-2, -1, 1, 2)
And i have 2 questions: 
1: Is this ok?
2: if its ok how to get unique values from this sparse matrix? 

### Reproducing Code Example

```python
def check_convert(sparse_data):
    write_info(sparse_data)
    print()
    bsr = sparse_data.tobsr()
    write_info(bsr)
    if (sparse_data - bsr).nnz == 0:
        print('BSR format convertation does not have any data loss')
    else:
        print('Data loss with BSR convertation')
    print()
    coo = sparse_data.tocoo()
    write_info(coo)
    if (sparse_data - coo).nnz == 0:
        print('COO format convertation does not have any data loss')
    else:
        print('Data loss with COO convertation')
    print()
    csc = sparse_data.tocsc()
    write_info(csc)
    if (sparse_data - csc).nnz == 0:
        print('CSC format convertation does not have any data loss')
    else:
        print('Data loss with CSC convertation')
    print()
    csr = sparse_data.tocsr()
    write_info(csr)
    if (sparse_data - csr).nnz == 0:
        print('CSC format convertation does not have any data loss')
    else:
        print('Data loss with CSC convertation')
    print()
    dia = sparse_data.todia()
    write_info(dia)
    if (sparse_data - dia).nnz == 0:
        print('DIA format convertation does not have any data loss')
    else:
        print('Data loss with DIA convertation')
    print()
```

### Error message

```shell
TYPE <class 'scipy.sparse.coo.coo_matrix'>
SHAPE: (7693, 2155830)
UNIQUE VALUES [-1 1]

TYPE <class 'scipy.sparse.bsr.bsr_matrix'>
SHAPE: (7693, 2155830)
UNIQUE VALUES [-2 -1 1 2]
BSR format convertation does not have any data loss

TYPE <class 'scipy.sparse.coo.coo_matrix'>
SHAPE: (7693, 2155830)
UNIQUE VALUES [-1 1]
COO format convertation does not have any data loss

TYPE <class 'scipy.sparse.csc.csc_matrix'>
SHAPE: (7693, 2155830)
UNIQUE VALUES [-2 -1 1 2]
CSC format convertation does not have any data loss

TYPE <class 'scipy.sparse.csr.csr_matrix'>
SHAPE: (7693, 2155830)
UNIQUE VALUES [-2 -1 1 2]
CSC format convertation does not have any data loss

/app/conda/envs/python36/lib/python3.6/site-packages/scipy/sparse/coo.py:434: SparseEfficiencyWarning: Constructing a DIA matrix with 2155268 diagonals is inefficient
"is inefficient" % len(diags), SparseEfficiencyWarning)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 32, in check_convert
File "/app/conda/envs/python36/lib/python3.6/site-packages/scipy/sparse/coo.py", line 440, in todia
data = np.zeros((len(diags), self.col.max()+1), dtype=self.dtype)
MemoryError: Unable to allocate array with shape (2155268, 2155830) and data type int64
```

### SciPy/NumPy/Python version information

1.6.2 1.19.2 sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)

**Comment by Enolerobotti** [comment]
Hi, I can reproduce it with the following 
```python
import numpy as np
import scipy.sparse
from typing import Tuple
from timeit import default_timer


def generate_random_matrix(
        data_size: int, target_size: Tuple[int, int]) -> scipy.sparse.coo_matrix:
    row = np.random.choice(range(target_size[0]), size=(data_size, ))
    col = np.random.choice(range(target_size[1]), size=(data_size, ))
    data = np.random.choice([-1, 1], size=(data_size,)).astype(np.int64)
    return scipy.sparse.coo_matrix((data, (row, col)), shape=target_size)


if __name__ == '__main__':
    start = default_timer()
    m = generate_random_matrix(71377179, (2000000, 8000))
    elapsed = default_timer() - start
    d = m.nnz / m.shape[0] / m.shape[1]
    print("Density:", d)
    print(f"Runtime {elapsed:.3f}")
    print(f"Unique before conversion {np.unique(m.data)}")
    m_csr = m.tocsr()
    print(f"Unique after conversion {np.unique(m_csr.data)}")
```

The output:
```
Density: 0.0044610736875
Runtime 1.918
Unique before conversion [-1  1]
Unique after conversion [-3 -2 -1  0  1  2  3]
```

/Cheers,
Artem

**Comment by tupui** [comment]
Hi @MorganPhobo5 the error is telling you that NumPy is trying to create an array which would not fit in memory.

Not sure about what is the best way to do what you want but this is not the place to ask as we don't have the bandwidth to answer user related questions. If there is no other bug related to SciPy I would close the issue.

**Comment by WarrenWeckesser** [comment]
I suspect the matrices in both @MorganPhobo5's and @Enolerobotti's examples have repeated occurrences of the same indices.
 
SciPy's COO sparse matrices have the (questionable) feature that they can store repeated occurrences of the *same* row and column indices.  Some actions on the sparse matrix will cause the duplicated entries to be combined by summing the values associated with the repeated indices.  For example, in the following, the input to `coo_matrix` repeats the indices [0, 1] three times and [1, 2] twice.
```
In [35]: from scipy.sparse import coo_matrix

In [36]: data = [1, 1, 1, 1, 1]

In [37]: i = [0, 0, 0, 1, 1]

In [38]: j = [1, 1, 1, 2, 2]

In [39]: a = coo_matrix((data, (i, j)))
```
The following says that `a` has "5 stored elements"--which it does--but in fact, there are only two unique pairs of indices that hold nonzero values:
```
In [40]: a
Out[40]: 
<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in COOrdinate format>
```
When the matrix is converted to a dense array, the values of the repeated indices are summed:
```
In [41]: a.A
Out[41]: 
array([[0, 3, 0],
       [0, 0, 2]])
```
`a.data` still holds the original input, but when `a` is converted to CSR, the code combines the repeated values (just like the conversion to a dense array did):
```
In [42]: a.data
Out[42]: array([1, 1, 1, 1, 1])

In [43]: b = a.tocsr()

In [44]: b
Out[44]: 
<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [45]: b.data
Out[45]: array([3, 2])

In [46]: b.A
Out[46]: 
array([[0, 3, 0],
       [0, 0, 2]])
```

**Comment by Enolerobotti** [comment]
Good point @WarrenWeckesser ! Thanks!
```python
m = scipy.sparse.coo_matrix((np.array([1, -1, 1]), (np.array([1, 1, 0]), np.array([1, 1, 0]))), shape=(3, 3))
print(m.A)
[[1 0 0]
 [0 0 0]
 [0 0 0]]

m = scipy.sparse.coo_matrix((np.array([1, -1, 1]), (np.array([1, 1, 0]), np.array([1, 0, 0]))), shape=(3, 3))
print(m.A)
[[ 1  0  0]
 [-1  1  0]
 [ 0  0  0]]
```
The matrices in my and @MorganPhobo5 's examples are seem corrupted. 

Anyway, it would be great if `scipy` warns users when overlapping indices present.
