### ISSUE TITLE
BUG: sparse `dot` method should accept scalars

### ISSUE THREAD

**Issue by toslunar** [scipy/scipy#15258]
### Describe your issue.

1. `spmatrix.dot` is stricter with 1.8.0rc1 than before.  The `dot` method of `spmatrix` classes should accept scalar operands like `numpy.ndarray` and `numpy.matrix` do.  It seems #14822 changed the behavior.

2. `_sparray.dot` could also accept `.dot(scalar)`.

### Reproducing Code Example

```python
sparse.csr_matrix([[2]]).dot(3)
sparse.csr_array([[2]]).dot(3)
```

### Error message

```shell
>>> sparse.csr_matrix([[2]]).dot(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/.pyenv/versions/p10/lib/python3.10/site-packages/scipy/sparse/_base.py", line 413, in dot
    return self @ other
  File "/Users/tos/.pyenv/versions/p10/lib/python3.10/site-packages/scipy/sparse/_base.py", line 619, in __matmul__
    raise ValueError("Scalar operands are not allowed, "
ValueError: Scalar operands are not allowed, use '*' instead
>>> sparse.csr_array([[2]]).dot(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tos/.pyenv/versions/p10/lib/python3.10/site-packages/scipy/sparse/_base.py", line 413, in dot
    return self @ other
  File "/Users/tos/.pyenv/versions/p10/lib/python3.10/site-packages/scipy/sparse/_base.py", line 619, in __matmul__
    raise ValueError("Scalar operands are not allowed, "
ValueError: Scalar operands are not allowed, use '*' instead
```

### SciPy/NumPy/Python version information

1.8.0rc1 1.22.0rc2 sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @toslunar thanks for reporting. I can see that this could be a regression but at the same time could understand that we want to make a difference. @stefanv was this intentional?

**Comment by stefanv** [comment]
Are we sure that the array interface changed that behavior? But, no, if so it was not intentional.

**Comment by tupui** [comment]
> Are we sure that the array interface changed that behavior? But, no, if so it was not intentional. 

I am not, just assuming here based on the report.

**Comment by rgommers** [comment]
This indeed worked in 1.7.0 and got broken in 1.8.0 due to the `*` -> `@` change.
