### ISSUE TITLE
BUG: solve_ivp produces exception constructing an OdeSolution

### ISSUE THREAD

**Issue by furii** [scipy/scipy#15262]
### Describe your issue.

Integrating a system with an inherently small `t` values (and steps between time points) can produce a `ValueError` if dense_output=True and event.terminal=True. The root cause can be traced to `solve_event_equation(event, sol, t_old, t)`. In in the call to `brentq` here `xtol=4*EPS`, which is in this case bigger than the interval between `t_old` and `t` and returns the root equal to `t_old`. This results in the two last values in `ts` being equal, and since the difference between these values is not increasing, i.e. 0, `OdeSolution` throws the below exception. 

As it stands to reason that the user would want the precision of the root returned by `solve_event_equation` to be better than the distance between the time points, it would make sense to make `xtol=np.abs(t-t_old)*4*EPS`. This fixes the current issue and increases the accuracy of event detection for ODEs with very small `t` values in general. Additionally, `OdeSolution` could be modified to deal with 0 increase between the `ts` values. 

### Reproducing Code Example

```python
import numpy as np

from scipy.integrate import solve_ivp
import scipy.constants as sc


E0=1e9
d=1e-6
tend=1.51*np.sqrt((2*d*sc.m_e)/(sc.e*E0))

def f(t,q):
    v=q[1]
    dqdt=np.zeros(2)
    dqdt[0]=v
    dqdt[1]=(sc.e/sc.m_e)*E0
    return dqdt

event=lambda t,q: q[0]-d
event.terminal=True

# Run solver
out=solve_ivp(f, [0,tend], np.zeros(2), dense_output=True, events=event,
              max_step=tend/1000)
```

### Error message

```shell
Traceback (most recent call last):

  File "/home/krecinic/.local/lib/python3.8/site-packages/scipy/integrate/_ivp/untitled0.py", line 30, in <module>
    out=solve_ivp(f, [0,tend], np.zeros(2), dense_output=True, events=event,

  File "/home/krecinic/.local/lib/python3.8/site-packages/scipy/integrate/_ivp/ivp.py", line 655, in solve_ivp
    sol = OdeSolution(ts, interpolants)

  File "/home/krecinic/.local/lib/python3.8/site-packages/scipy/integrate/_ivp/common.py", line 157, in __init__
    raise ValueError("`ts` must be strictly increasing or decreasing.")

ValueError: `ts` must be strictly increasing or decreasing.
```

### SciPy/NumPy/Python version information

1.6.2 1.20.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by Patol75** [comment]
`EPS` is obtained using the `eps` attribute of the `finfo` class defined in NumPy. The documentation page of [finfo](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html) mentions

![image](https://user-images.githubusercontent.com/23244688/147900741-81d1958f-5cbf-4d8f-b59c-71b180a2e541.png)

In the example code you give, the maximum time step you impose to the solver is `1.6102052787852986e-16`, which is lower than `EPS` and, therefore, cannot be properly represented.

I do not think that changing the current `xtol` and `rtol` is a good idea.

**Comment by fkrecinic** [comment]
> In the example code you give, the maximum time step you impose to the solver is `1.6102052787852986e-16`, which is lower than `EPS` and, therefore, cannot be properly represented.

This is incorrect. According to the `numpy.finfo` [documentation](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html) 
> tiny : float
>     The smallest positive floating point number with full precision (see Notes).

On my 64-bit, x86_64 CPU `numpy.finfo(float).tiny` gives `2.2250738585072014e-308`, which is much smaller than `1.6102052787852986e-16`. Indeed, `solve_ivp` works fine with such small numbers. `EPS` is more accurately understood as the number of digits behind the comma a float number has, and is therefore relative. 

> I do not think that changing the current `xtol` and `rtol` is a good idea.

The proposed modifications is only to change `xtol`, which is used as absolute tolerance when calling `brentq` to approximate the exact root (see [brentq documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brentq.html))
> xtol : number, optional
>     The computed root x0 will satisfy np.allclose(x, x0, atol=xtol, rtol=rtol), where x is the exact root.

As floating point numbers with absolute sizes much smaller that `EPS` can be represented, I think that changing the `xtol` parameter does make sense here (as was argued in the original post).

PS. The code example given in the initial post is also not an extreme case, per se. It solves for an electron accelerated in a static electric field, and arises frequently enough in physics applications.

**Comment by Patol75** [comment]
Thank you for the clarification, and sorry for my misunderstanding of the situation. Considering you have identified the root of the problem and have come up with a fix, feel free to open a PR. A potential suggestion would be to make use of the default value in `brentq`, i.e. use `xtol=np.abs(t-t_old)*2e-12` instead of `xtol=np.abs(t-t_old)*4*EPS`. Also, if hard-coding is not desired, default values of `brentq` can be obtained this way
```
>>> from scipy.optimize import brentq
>>> brentq.__defaults__
((), 2e-12, 8.881784197001252e-16, 100, False, True)
```

**Comment by laurent90git** [comment]
I think this issue would be better resolved on the user side by rescaling your time vector. This is also a good practice in general. 
Instead of solving dy/dt=f(y), solve dy/dt' = f(y)/K with t' = Kt. Here is a small modification of your code:
```
import numpy as np

from scipy.integrate import solve_ivp
import scipy.constants as sc


E0=1e9
d=1e-6
tend=1.51*np.sqrt((2*d*sc.m_e)/(sc.e*E0))
K= 1/tend
tend=tend*K # time scale

def f(t,q):
    v=q[1]
    dqdt=np.zeros(2)
    dqdt[0]=v
    dqdt[1]=(sc.e/sc.m_e)*E0
    return (1/K)*dqdt

event=lambda t,q: q[0]-d
event.terminal=True

# Run solver
out=solve_ivp(f, [0,tend], np.zeros(2), dense_output=True, events=event,
              max_step=tend/1000)
# rescale time
out.t /= K
out.t_events /= K
print('first event occured at {:.3e} s'.format(out.t_events[0][0]))
```

This seems to work.

The issue arises when you have time steps which are less than 4*EPS apart, i.e roughly 1e-15. This is often considered to be too small anyway, because you may accumulate error on the time t = sum(dt) of your solution, because then dt may so small that it does not contribute anymore to t within machine precision.

Finally, maybe it would be more coherent to set the absolute tolerance xtol to something closer to the minimum time step allowed in solve_ivp routines, which is 1e-20.
