### ISSUE TITLE
BUG: refguide check and CircleCI failures in master

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#15327]
### Describe your issue.

There are two new CI failures in master that started today.

### Error message

[refguide](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=15691&view=logs&j=ede89041-5e8e-5201-ce5c-f68c2cbf02dd&t=bf6d2fae-c4b4-5aaf-e29f-d3092465da33&l=740) (e.g. gh-15325)

<details>

```

File "doc/source/tutorial/interpolate.rst", line 261, in /home/vsts/work/1/s/tools/../doc/source/tutorial/interpolate.rst
Failed example:
    interpolate.sproot(tck)
Expected:
    array([3.1416])
Got:
    array([1.05630421e-17, 3.14159265e+00])
/home/vsts/work/1/s/tools/refguide_check.py:662: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if want == got:

```

</details>

[CircleCI build_docs](https://app.circleci.com/pipelines/github/scipy/scipy/10615/workflows/73f779d1-3682-48f5-aaf9-19bb66a50e05/jobs/41016?invite=true#step-103-58) (e.g. gh-15326)

<details>

```
waiting for workers...
/home/circleci/repo/build/testenv/lib/python3.8/site-packages/scipy/signal/windows/_windows.py:docstring of scipy.signal.windows._windows.bohman:33: WARNING: Exception occurred in plotting scipy-signal-windows-bohman-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.signal.windows.bohman.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
RuntimeWarning: divide by zero encountered in log10
/home/circleci/repo/build/testenv/lib/python3.8/site-packages/scipy/signal/windows/_windows.py:docstring of scipy.signal.windows._windows.cosine:36: WARNING: Exception occurred in plotting scipy-signal-windows-cosine-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.signal.windows.cosine.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
RuntimeWarning: divide by zero encountered in log10
```

</details>

### SciPy/NumPy/Python version information

master

**Comment by ev-br** [comment]
The sproot failure is curious. The text below the example reads, literally (https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html) :

> Notice that sproot failed to find an obvious solution at the edge of the approximation interval, 

So, somehow this one failed to fail to find that obvious solution :-). This is likely rather brittle, and not really controllable ,  cf gh-8376. 

The easiest fix to unblock the CI is to add `# may vary` comment to an example.

**Comment by rgommers** [comment]
I'll have a look at fixing the remaining `log10` and `linalg.lapack` warnings.

**Comment by rgommers** [comment]
The reason these failures showed up is the NumPy `1.22.0` release yesterday.

**Comment by rgommers** [comment]
Copying the warnings here:
```
docstring of scipy.linalg.lapack.ssyevr:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.ssyevr:22: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.ssyevr:22: WARNING: Inline emphasis start-string without end-string.
docstring of scipy.linalg.lapack.ssyevr:22: WARNING: Inline emphasis start-string without end-string.
docstring of scipy.linalg.lapack.ssyevx:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.ssyevx:22: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.zheevr:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.zheevx:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.zheevx:16: WARNING: Inline emphasis start-string without end-string.
docstring of scipy.linalg.lapack.dsyevr:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.dsyevr:22: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.dsyevr:22: WARNING: Inline emphasis start-string without end-string.
docstring of scipy.linalg.lapack.dsyevr:22: WARNING: Inline emphasis start-string without end-string.
docstring of scipy.linalg.lapack.dsyevx:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.dsyevx:22: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.cheevr:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.cheevx:16: WARNING: Inline literal start-string without end-string.
docstring of scipy.linalg.lapack.cheevx:16: WARNING: Inline emphasis start-string without end-string
```

These are coming from `f2py`-generated docstrings, which are ending up in `build/scipy/linalg/_flapackmodule.c`. There isn't anything we can do to fix this I think, so let's pin to numpy `1.21.5` in the doc build and see if it can be fixed in `1.22.1`.

**Comment by rgommers** [comment]
The `log10` warnings seem to be present for numpy `1.21.5` as well, it's not entirely clear why they are showing up now. If someone else would want to investigate, and tweak the example code if needed, that'd be great.

**Comment by rgommers** [comment]
The fix for the lapack issues will be in numpy `1.22.1`.
