### ISSUE TITLE
BUG: scipy.sparse.rand raises ValueError on ppc64le

### ISSUE THREAD

**Issue by ckastner** [scipy/scipy#15404]
### Describe your issue.

On a ppc64le QEMU instance running Debian unstable, I noticed that scikit-learn's test suite was triggering an error during test collection. I could trace this back to a call to `scipy.sparse.rand(10, 3, density=0.5)`.

This only happens on ppc64le as far as I know. The call worked fine on other architectures.

This is with gfortran, libblas and liblapack from Debian. scipy was built/installed using `pip`.

It works with a density up to 0.11, but fails with 0.12 and higher (at least, from the few samples I tested manually).

### Reproducing Code Example

```python
>>> from scipy import sparse
>>> sparse.rand(10, 3, density=0.5)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.9/site-packages/scipy/sparse/construct.py", line 868, in rand
    return random(m, n, density, format, dtype, random_state)
  File "/root/venv/lib/python3.9/site-packages/scipy/sparse/construct.py", line 813, in random
    return coo_matrix((vals, (i, j)), shape=(m, n)).asformat(format,
  File "/root/venv/lib/python3.9/site-packages/scipy/sparse/coo.py", line 196, in __init__
    self._check()
  File "/root/venv/lib/python3.9/site-packages/scipy/sparse/coo.py", line 283, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions
```

### SciPy/NumPy/Python version information

1.7.3 1.22.0 sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)

**Comment by ckastner** [comment]
Update: I now had the chance to test this on actual ppc64le hardware (rather than QEMU) and the problem is not reproducible there. Therefore, closing this bug.
