### ISSUE TITLE
BUG: root search with krylow leads to the message that there probably is a bug in the Jacobian approximation

### ISSUE THREAD

**Issue by tpstps** [scipy/scipy#15474]
### Describe your issue.

Hi,

using the code below leads to the following error message:

`ValueError: Jacobian inversion yielded zero vector. This indicates a bug in the Jacobian approximation.`

Is there anything I can do myself for this?

### Reproducing Code Example

```python
import scipy.optimize as sco
import numpy as np

import sys, scipy, numpy;

print(scipy.__version__, numpy.__version__, sys.version_info)

startValue = 100000

amountOfCalls =0

def myFunc(x):
    global amountOfCalls
    amountOfCalls += 1
    y = x ** 3 + x - 5

    return y

algo = 'krylov'
root1_result = sco.root(myFunc, [startValue, ], method=algo, )

print("root1_result=", root1_result)
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/user/PycharmProjects/project/filename.py", line 22, in <module>
    root1_result = sco.root(myFunc, [startValue, ], method=algo, )
  File "/home/user/venv/numba38/lib/python3.8/site-packages/scipy/optimize/_root.py", line 197, in root
    sol = _root_nonlin_solve(fun, x0, args=args, jac=jac,
  File "/home/user/venv/numba38/lib/python3.8/site-packages/scipy/optimize/_root.py", line 295, in _root_nonlin_solve
    x, info = nonlin.nonlin_solve(f, x0, jacobian=jacobian(**jac_options),
  File "/home/user/venv/numba38/lib/python3.8/site-packages/scipy/optimize/nonlin.py", line 312, in nonlin_solve
    raise ValueError("Jacobian inversion yielded zero vector. "
ValueError: Jacobian inversion yielded zero vector. This indicates a bug in the Jacobian approximation.
1.7.3 1.21.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @tpstps, thank you for reporting. I am afraid we don't have the bandwidth to answer user questions. Please try either StackOverflow or our [user](https://mail.python.org/archives/list/scipy-user@python.org/) mailing list. Without the evidence of a bug, I will close it for now. If you have new elements showing there is a bug, I will be happy to reopen the issue.
