### ISSUE TITLE
CI: asv 0.5 release causing a failure

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#15535]
In PRs with unrelated changes like gh-15531 the new `asv` version fails the "refguide check" Azure job with traceback below. Maybe I'll pin it temporarily.

```
2022-02-06T07:38:26.8809402Z Generating script.
2022-02-06T07:38:26.8818177Z Script contents:
2022-02-06T07:38:26.8819634Z pip install "asv>=0.4.1"
2022-02-06T07:38:26.8821155Z ========================== Starting Command Output ===========================
2022-02-06T07:38:26.8840664Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/4fea1db0-e8f1-4af6-9cf3-991cfe58ba0e.sh
2022-02-06T07:38:27.2805040Z Collecting asv>=0.4.1
2022-02-06T07:38:27.3072908Z   Downloading asv-0.5.tar.gz (486 kB)
2022-02-06T07:38:27.3961664Z   Installing build dependencies: started
2022-02-06T07:38:29.1150758Z   Installing build dependencies: finished with status 'done'
2022-02-06T07:38:29.1185009Z   Getting requirements to build wheel: started
2022-02-06T07:38:29.7928447Z   Getting requirements to build wheel: finished with status 'error'
2022-02-06T07:38:29.7929628Z   ERROR: Command errored out with exit status 1:
2022-02-06T07:38:29.7930798Z    command: /opt/hostedtoolcache/Python/3.9.10/x64/bin/python /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpmngw6og5
2022-02-06T07:38:29.7931788Z        cwd: /tmp/pip-install-rvb1kdv9/asv
2022-02-06T07:38:29.7932255Z   Complete output (20 lines):
2022-02-06T07:38:29.7932716Z   Traceback (most recent call last):
2022-02-06T07:38:29.7933609Z     File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
2022-02-06T07:38:29.7934204Z       main()
2022-02-06T07:38:29.7935016Z     File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
2022-02-06T07:38:29.7935856Z       json_out['return_val'] = hook(**hook_input['kwargs'])
2022-02-06T07:38:29.7936815Z     File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
2022-02-06T07:38:29.7937750Z       return hook(config_settings)
2022-02-06T07:38:29.7938645Z     File "/tmp/pip-build-env-hmarp7mu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 161, in get_requires_for_build_wheel
2022-02-06T07:38:29.7939295Z       return self._get_build_requires(
2022-02-06T07:38:29.7940151Z     File "/tmp/pip-build-env-hmarp7mu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in _get_build_requires
2022-02-06T07:38:29.7940776Z       self.run_setup()
2022-02-06T07:38:29.7941563Z     File "/tmp/pip-build-env-hmarp7mu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 266, in run_setup
2022-02-06T07:38:29.7942191Z       super(_BuildMetaLegacyBackend,
2022-02-06T07:38:29.7943015Z     File "/tmp/pip-build-env-hmarp7mu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in run_setup
2022-02-06T07:38:29.7943810Z       exec(compile(code, __file__, 'exec'), locals())
2022-02-06T07:38:29.7944315Z     File "setup.py", line 292, in <module>
2022-02-06T07:38:29.7944797Z       run_setup(build_binary=True)
2022-02-06T07:38:29.7945458Z     File "setup.py", line 207, in run_setup
2022-02-06T07:38:29.7946159Z       with open('requirements-dev.txt', 'r') as f:
2022-02-06T07:38:29.7946941Z   FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'
2022-02-06T07:38:29.7947709Z   ----------------------------------------
2022-02-06T07:38:29.7949257Z ERROR: Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.9.10/x64/bin/python /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpmngw6og5 Check the logs for full command output.
2022-02-06T07:38:29.8103917Z WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
2022-02-06T07:38:29.8105214Z You should consider upgrading via the '/opt/hostedtoolcache/Python/3.9.10/x64/bin/python -m pip install --upgrade pip' command.
2022-02-06T07:38:29.8763694Z ##[error]Bash exited with code '1'.
2022-02-06T07:38:29.8778785Z ##[section]Finishing: Install asv
```

**Comment by charris** [comment]
This is a known asv bug, see [this comment](https://github.com/airspeed-velocity/asv/issues/967#issuecomment-1030661996).

**Comment by datapythonista** [comment]
asv 0.5.1 has been just released, this should be fixed now.

**Comment by tylerjereddy** [comment]
alright, I'll close it then
