### ISSUE TITLE
BUG: different performances of cKDTree and its weird memory consumptions

### ISSUE THREAD

**Issue by alisheikholeslam** [scipy/scipy#15621]
### Describe your issue.

As it is discussed in the comments of [one of my SO issues](https://stackoverflow.com/a/71135783/13394817), `cKDTree` have shown some different performances on 3 different systems:
1. Richard system (6-core machine with a i5-9600KF processor, 16 GiB of RAM 2 channels DDR4 @ 3200MHz reaching 36~40 GiB/s)
2. Colab CPU and TPU
3. my system ( i5 1st gen cpu intel core 760 @ 2.8GHz, 16gb ram cl9 dual channel DDR3 ripjaws, x64 windows system)

I have prepared two data sets one with 23.000 data volume (***small***) and another one with 550.000 data volume (***large***). Ram usage and performance for all of these data volumes are well on the ***Richard system***, but just *23.000* data set perform well on both *colab* and *my system*, which for the numba code takes less than a second to solve. For 550.000 data set, solving time increase a lot **comparing to *Richard*** (I could not test this data volume on both *colab* and *my system*) which will get error due to full ram consumptions (*colab* just can run on one-fifth of the large data set i.e. 100.000 and *my system* could handle data volumes up to 200.000); These 100.000 and 200.000 data sets are prepared by separating from the 550.000 data set. I have test this problem by various versions of scipy and …, but the same issue. It takes just 3 seconds for *Richard* to solve the 550000 data set. On my system, as it is shown on the below image, for 23000 data set it takes less than even 15000 data volume (which is separated from the large data set) by lower memory consumption. Perhaps, it could be related to differences in the neighbors numbers in the two samples. If so and if memory consumption and runtime are strictly under the influence of neighbors numbers, why *Richard* have not such issue and solve the problem very fast for 550000 data set. since my system is a little old, I tested it by Colab to overcome probable cpu and ram limitations of mine, but the same results achieved.

![image (3)](https://user-images.githubusercontent.com/63285654/154689387-74495f60-0c09-4621-a46f-3657faf632b5.png)

using memory profiler for *23000, 40000, 100000, 200000* data volumes:

![image](https://user-images.githubusercontent.com/63285654/154689467-125111af-822b-433a-9979-deec32b0a706.png)

I have read some related issues on memory problems for `cKDTree` on scipy and scikit learn, by which I think it may be a `cKDTree` problem (I read somewhere that said each high memory consumption will be a problem of modules not the neighbors number, but perhaps I understand wrongly). In my code I must iterate over all spheres, so, I think, I can not use something like `chunk` and … .

**I could not figure out why this memory leakage and weird different performances are happening, and how to overcome this problem?**

**Sample data:** (`.npy` formats are 23000)
[data.zip](https://github.com/scipy/scipy/files/8097505/data.zip)
 

### Reproducing Code Example

```python
def ends_gap_opt(poss, dia_max):         # optimized algorithm
    particle_corsp_overlaps = []
    ends_ind = [np.empty([1, 2], dtype=np.int64)]

    kdtree = cKDTree(poss)

    for particle_idx in range(len(poss)):
        # Find the nearest point including the current one and
        # then remove the current point from the output.
        # The distances can be computed directly without a new query.
        cur_point = poss[particle_idx]
        nears_i_ind = np.array(kdtree.query_ball_point(cur_point, r=dia_max), dtype=np.int64)
        assert len(nears_i_ind) > 0

        if len(nears_i_ind) <= 1:
            continue

        nears_i_ind = nears_i_ind[nears_i_ind != particle_idx]
        dist_i = distance.cdist(poss[nears_i_ind], cur_point[None, :]).squeeze()

        contact_check = dist_i - (radii[nears_i_ind] + radii[particle_idx])
        connected = contact_check[contact_check <= 0]

        particle_corsp_overlaps.append(connected)

        contacts_ind = np.where([contact_check <= 0])[1]
        contacts_sec_ind = nears_i_ind[contacts_ind]
        sphere_olps_ind = np.sort(contacts_sec_ind)

        ends_ind_mod_temp = np.array([np.repeat(particle_idx, len(sphere_olps_ind)), sphere_olps_ind], dtype=np.int64).T
        if particle_idx > 0:
            ends_ind.append(ends_ind_mod_temp)
        else:
            ends_ind[0][:] = ends_ind_mod_temp[0, 0], ends_ind_mod_temp[0, 1]

    ends_ind_org = np.concatenate(ends_ind)
    ends_ind, ends_ind_idx = np.unique(np.sort(ends_ind_org), axis=0, return_index=True)                                # <--- relatively high time consumer
    gap = np.concatenate(particle_corsp_overlaps)[ends_ind_idx]
    return gap, ends_ind, ends_ind_idx, ends_ind_org


@nb.jit('(float64[:, ::1], int64[::1], int64[::1], float64)')
def compute(poss, all_neighbours, all_neighbours_sizes, dia_max):
    particle_corsp_overlaps = []
    ends_ind_lst = [np.empty((1, 2), dtype=np.int64)]
    an_offset = 0

    for particle_idx in range(len(poss)):
        cur_point = poss[particle_idx]
        cur_len = all_neighbours_sizes[particle_idx]
        nears_i_ind = all_neighbours[an_offset:an_offset+cur_len]
        an_offset += cur_len
        assert len(nears_i_ind) > 0

        if len(nears_i_ind) <= 1:
            continue

        nears_i_ind = nears_i_ind[nears_i_ind != particle_idx]
        dist_i = np.empty(len(nears_i_ind), dtype=np.float64)

        # Compute the distances
        x1, y1, z1 = poss[particle_idx]
        for i in range(len(nears_i_ind)):
            x2, y2, z2 = poss[nears_i_ind[i]]
            dist_i[i] = np.sqrt((x2-x1)**2 + (y2-y1)**2 + (z2-z1)**2)

        contact_check = dist_i - (radii[nears_i_ind] + radii[particle_idx])
        connected = contact_check[contact_check <= 0]

        particle_corsp_overlaps.append(connected)

        contacts_ind = np.where(contact_check <= 0)
        contacts_sec_ind = nears_i_ind[contacts_ind]
        sphere_olps_ind = np.sort(contacts_sec_ind)

        ends_ind_mod_temp = np.empty((len(sphere_olps_ind), 2), dtype=np.int64)
        for i in range(len(sphere_olps_ind)):
            ends_ind_mod_temp[i, 0] = particle_idx
            ends_ind_mod_temp[i, 1] = sphere_olps_ind[i]

        if particle_idx > 0:
            ends_ind_lst.append(ends_ind_mod_temp)
        else:
            tmp = ends_ind_lst[0]
            tmp[:] = ends_ind_mod_temp[0, :]

    return particle_corsp_overlaps, ends_ind_lst

def ends_gap_nb(poss, dia_max):         # numba
    kdtree = cKDTree(poss)
    tmp = kdtree.query_ball_point(poss, r=dia_max, workers=-1)
    all_neighbours = np.concatenate(tmp, dtype=np.int64)
    all_neighbours_sizes = np.array([len(e) for e in tmp], dtype=np.int64)
    particle_corsp_overlaps, ends_ind_lst = compute(poss, all_neighbours, all_neighbours_sizes, dia_max)
    ends_ind_org = np.concatenate(ends_ind_lst)
    ends_ind, ends_ind_idx = np.unique(np.sort(ends_ind_org), axis=0, return_index=True)
    gap = np.concatenate(particle_corsp_overlaps)[ends_ind_idx]
    return gap, ends_ind, ends_ind_idx, ends_ind_org
```

### Error message

```shell
**for numba method with workers = 1:**

Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/test2.py", line 225, in <module>
    opt_ = ends_gap_optimized_(poss, dia_max)
  File "C:/Users/Ali/Desktop/test2.py", line 195, in ends_gap_optimized_
    tmp = kdtree.query_ball_point(poss, r=dia_max)
  File "ckdtree.pyx", line 986, in scipy.spatial.ckdtree.cKDTree.query_ball_point
  File "ckdtree.pyx", line 1608, in scipy.spatial.ckdtree._run_threads
  File "ckdtree.pyx", line 983, in scipy.spatial.ckdtree.cKDTree.query_ball_point._thread_func
MemoryError

Process finished with exit code 1

---

**for numba method with workers = -1:**

Exception in thread Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Exception in thread Thread-1:
Thread-4Traceback (most recent call last):
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 932, in _bootstrap_inner
:
Thread-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 870, in run
    self.run()
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 870, in run
            self.run()
self.run()self._target(*self._args, **self._kwargs)
  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 870, in run

  File "C:\Users\Ali\anaconda3\envs\PFC_FiPy\lib\threading.py", line 870, in run
  File "ckdtree.pyx", line 979, in scipy.spatial.ckdtree.cKDTree.query_ball_point._thread_func
    self._target(*self._args, **self._kwargs)
      File "ckdtree.pyx", line 979, in scipy.spatial.ckdtree.cKDTree.query_ball_point._thread_func
self._target(*self._args, **self._kwargs)
  File "ckdtree.pyx", line 979, in scipy.spatial.ckdtree.cKDTree.query_ball_point._thread_func
    self._target(*self._args, **self._kwargs)
  File "ckdtree.pyx", line 979, in scipy.spatial.ckdtree.cKDTree.query_ball_point._thread_func
MemoryError
MemoryError
MemoryError
MemoryError
Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/test2.py", line 222, in <module>
    opt = ends_gap_optimized(poss, dia_max)
  File "C:/Users/Ali/Desktop/test2.py", line 184, in ends_gap_optimized
    all_neighbours = np.concatenate(tmp, dtype=np.int64)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 132920 has 0 dimension(s)

Process finished with exit code 1
```

### SciPy/NumPy/Python version information

COLAB: 1.4.1 1.21.5 sys.version_info(major=3, minor=7, micro=12, releaselevel='final', serial=0) __________ My system: 1.8.0 1.21.3 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by rfezzani** [comment]
Hello @alisheikholeslam, as advised in #12956, a solution for the reduction of `cKDTree.query_ball_point` memory use is to process your data by chunk. Here is a small refactoring of your sample code
```python

def ends_gap_naive(poss, dia_max):
    kdtree = cKDTree(poss)
    out = [kdtree.query_ball_point(pt, r=dia_max) for pt in poss]
    return out


def ends_gap_vectorized(poss, dia_max):
    kdtree = cKDTree(poss)
    return kdtree.query_ball_point(poss, r=dia_max, workers=-1)


def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    kdtree = cKDTree(poss)
    chunk_count = poss.shape[0] // chunk_size
    out = []
    for chunk in np.array_split(poss, chunk_count):
        out.append(
            kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    return np.hstack(out)
```
<details>
<summary>And a script for the evaluation of these different implementations:</summary>

```python
from time import time
import numpy as np
from scipy.spatial import cKDTree

from memory_profiler import profile


def ends_gap_naive(poss, dia_max):
    kdtree = cKDTree(poss)
    out = [kdtree.query_ball_point(pt, r=dia_max) for pt in poss]
    return out


def ends_gap_vectorized(poss, dia_max):
    kdtree = cKDTree(poss)
    return kdtree.query_ball_point(poss, r=dia_max, workers=-1)


def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    kdtree = cKDTree(poss)
    chunk_count = poss.shape[0] // chunk_size
    out = []
    for chunk in np.array_split(poss, chunk_count):
        out.append(
            kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    return np.hstack(out)


if __name__ == "__main__":

    rnd = np.random.RandomState(70)
    data_volume = 200000

    radii = rnd.uniform(0.0005, 0.122, data_volume)
    x = rnd.uniform(-1.02, 1.02, (data_volume, 1))
    y = rnd.uniform(-3.52, 3.52, (data_volume, 1))
    z = rnd.uniform(-1.02, -0.575, (data_volume, 1))

    poss = np.hstack((x, y, z))

    dia_max = 2 * radii.max()

    func_list = [ends_gap_naive, ends_gap_vectorized]
    run_count = 5

    for func in func_list:
        print(f"\n*** {func.__name__} ***")
        print(16 * "-")

        profile(func)(poss, dia_max)

        t0 = time()
        for _ in range(run_count):
            func(poss, dia_max)
        t1 = time()

        print(f"\nElapsed time: {(t1 - t0) / run_count:.02f}sec")
        print(16 * "-")

    # Monitor chunk_size effect
    for size in [100, 200, 500, 1000, 2000, 5000]:
        print(f"\n*** ends_gap_chunk with chunk_size={size} ***")
        print(16 * "-")
        profile(ends_gap_chunk)(poss, dia_max, chunk_size=size)

        t0 = time()
        for _ in range(run_count):
            ends_gap_chunk(poss, dia_max, chunk_size=size)
        t1 = time()

        print(f"\nElapsed time: {(t1 - t0) / run_count:.02f}sec")
        print(16 * "-")

```
</details>

<details>
<summary>Here is the result on my system (Intel® Core™ i7-10700K CPU @ 3.80GHz × 16; 32GiB of RAM)</summary>

```
*** ends_gap_naive ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     8     92.6 MiB     92.6 MiB           1   def ends_gap_naive(poss, dia_max):
     9     96.7 MiB      4.1 MiB           1       kdtree = cKDTree(poss)
    10  11130.6 MiB  11033.9 MiB      200003       out = [kdtree.query_ball_point(pt, r=dia_max) for pt in poss]
    11  11130.6 MiB      0.0 MiB           1       return out

Elapsed time: 17.13sec
----------------

*** ends_gap_vectorized ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    14    106.2 MiB    106.2 MiB           1   def ends_gap_vectorized(poss, dia_max):
    15    106.2 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    16  13862.2 MiB  13756.0 MiB           1       return kdtree.query_ball_point(poss, r=dia_max, workers=-1)

Elapsed time: 11.63sec
----------------

*** ends_gap_chunk with chunk_size=100 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19    494.7 MiB    494.7 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20    494.7 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21    494.7 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22    494.7 MiB      0.0 MiB           1       out = []
    23  11340.0 MiB      0.0 MiB        2001       for chunk in np.array_split(poss, chunk_count):
    24  11340.0 MiB      0.0 MiB        4000           out.append(
    25  11340.0 MiB  10845.3 MiB        2000               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11340.0 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 14.44sec
----------------

*** ends_gap_chunk with chunk_size=200 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19   1372.8 MiB   1372.8 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20   1372.8 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21   1372.8 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22   1372.8 MiB      0.0 MiB           1       out = []
    23  11252.7 MiB  -5115.4 MiB        1001       for chunk in np.array_split(poss, chunk_count):
    24  11252.7 MiB -10230.8 MiB        2000           out.append(
    25  11252.7 MiB   4764.5 MiB        1000               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11252.7 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 13.30sec
----------------

*** ends_gap_chunk with chunk_size=500 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19   1117.3 MiB   1117.3 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20   1117.3 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21   1117.3 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22   1117.3 MiB      0.0 MiB           1       out = []
    23  11254.7 MiB    -55.0 MiB         401       for chunk in np.array_split(poss, chunk_count):
    24  11254.7 MiB    -94.4 MiB         800           out.append(
    25  11254.7 MiB  10082.4 MiB         400               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11254.7 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 12.13sec
----------------

*** ends_gap_chunk with chunk_size=1000 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19   1233.0 MiB   1233.0 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20   1233.0 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21   1233.0 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22   1233.0 MiB      0.0 MiB           1       out = []
    23  11258.1 MiB    -39.5 MiB         201       for chunk in np.array_split(poss, chunk_count):
    24  11258.1 MiB    -68.8 MiB         400           out.append(
    25  11258.1 MiB   9985.7 MiB         200               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11258.1 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 12.74sec
----------------

*** ends_gap_chunk with chunk_size=2000 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19   1451.1 MiB   1451.1 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20   1451.1 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21   1451.1 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22   1451.1 MiB      0.0 MiB           1       out = []
    23  11271.2 MiB      0.0 MiB         101       for chunk in np.array_split(poss, chunk_count):
    24  11271.2 MiB      0.0 MiB         200           out.append(
    25  11271.2 MiB   9820.1 MiB         100               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11271.2 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 12.72sec
----------------

*** ends_gap_chunk with chunk_size=5000 ***
----------------
Filename: /tmp/test.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    19   1121.3 MiB   1121.3 MiB           1   def ends_gap_chunk(poss, dia_max, chunk_size=2000):
    20   1121.3 MiB      0.0 MiB           1       kdtree = cKDTree(poss)
    21   1121.3 MiB      0.0 MiB           1       chunk_count = poss.shape[0] // chunk_size
    22   1121.3 MiB      0.0 MiB           1       out = []
    23  11303.8 MiB      0.0 MiB          41       for chunk in np.array_split(poss, chunk_count):
    24  11303.8 MiB      0.0 MiB          80           out.append(
    25  11303.8 MiB  10182.5 MiB          40               kdtree.query_ball_point(chunk, r=dia_max, workers=-1))
    26  11303.8 MiB      0.0 MiB           1       return np.hstack(out)

Elapsed time: 12.24sec
```
</details>

## Summary

- The "naive" approach is the more memory efficient (11130.6 MiB) approach but also the slowest (17.13sec),
- the "vectorized" approach is the fastest (11.63sec) but the most memory intensive (13862.2 MiB),
- the "chunked" approach with a chunk size of 500 is the best compromise in term of speed/memory use (12.13sec / 11254.7 MiB)

**Comment by rfezzani** [comment]
I'm sorry, I can't understand this huge performance gap :confused:. My config is:
- Ubuntu 20.04
- conda 4.9.2
- python 3.8.12
- numpy 1.21.2
- scipy 1.7.1

**Comment by alisheikholeslam** [comment]
> 

The performance difference was relating to Richard mistake. Memory issue is the main problem now.

**Comment by alisheikholeslam** [comment]
> As it is discussed in the comments of [one of my SO issues](https://stackoverflow.com/a/71135783/13394817), `cKDTree` have shown some different performances on 3 different systems.

The performance difference was relating to Richard mistake. Memory issue is the main problem now.

**Comment by rfezzani** [comment]
Thank you for the clarification @alisheikholeslam :wink:

**Comment by sturlamolden** [comment]
The inherent parallelism in ```query``` and ```query_ball_point``` does chunk the data. Unfortunately each thread gets an equal chunk and there is just one chunk per thread. You can decrease the chunk size by spawning more workers (just specify the number of workers, it can be as high as your system allows). However, increasing the number of spawned threads is not a scalable solution.

I wanted to use a threadpool design for the very reason you show here. And the first versions of the parallel queries actually did this using OpenMP ans Apple/FreeBSD GCD instead of Python threads. However, I was ruled down due to the complexity of the code. 

I hope this issue is good enough evidence that we should use a threadpool instead of allocating a fixed chunk to each worker thread. May I suggest we use ```concurrent.futures``` since we now have threadpools in the Python standard library?

**Comment by sturlamolden** [comment]
Also note that the GIL is not an issue. The query functions do release the GIL. So they do not lock up the interpreter. That was the very reason I wrote them in C++. And not for the sake of parallel processing. There are other reasons as well, such as maintaining a responsive UI and avoiding moments of frosen graphics while running a game. And for the same reason, if run queries from Python threads they will execute in parallel.

**Comment by Palash123-4** [comment]
Thanks @alisheikholeslam for the code, Can you please tell me how this code can be modified for 64 cores system and 32 GB RAM. What is the appropriate chunk size for data = 2000000. Should I consider a very small chunk_size or very large? 

I have tried from from 100 to 10000. Everytime it overflows.
