### ISSUE TITLE
BUG: Crash when compiling against OneAPI MKL

### ISSUE THREAD

**Issue by AlexKurek** [scipy/scipy#15672]
### Describe your issue.

Im trying to compile Numpy and Scipy master aginst OneAPI MKL inside Singularity (version 3.9.5) container. Numpy comliles, but Scipy crashes.The recipe is pasted below. But it crashes saying:
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/src/scipy/scipy/_lib/highs/CMakeLists.txt'`

### Reproducing Code Example

```python
Bootstrap: docker
From: debian:bullseye

%post
   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
   export SRC=/usr/local/src

   export MKL_ONEAPI_VERSION=2022.0.2
   export NUMPY3_VERSION=1.19.5

   apt-get update -q
   apt-get install -y -q git wget


   ###########################   OpenBLAS
   apt-get install -y -q build-essential gfortran
   mkdir -p $SRC/OpenBLAS/
   cd $SRC/OpenBLAS/
   git clone https://github.com/xianyi/OpenBLAS.git src/
   cd src/
   make -j 8 > /dev/null 2>&1
   make install USE_OPENMP=0 NUM_THREADS=28 TARGET=SKYLAKEX > /dev/null 2>&1


   ###########################   MKL oneAPI
   cd $SRC/
   wget -q --retry-connrefused https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
   apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
   rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
   sh -c 'echo deb https://apt.repos.intel.com/oneapi all main > /etc/apt/sources.list.d/oneAPI.list'
   apt-get update -q
   apt-get install -y -q intel-oneapi-mkl-devel

   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so libblas.so-x86_64-linux-gnu /opt/intel/oneapi/mkl/$MKL_ONEAPI_VERSION/lib/intel64/libmkl_rt.so 50
   update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so.3 libblas.so.3-x86_64-linux-gnu /opt/intel/oneapi/mkl/$MKL_ONEAPI_VERSION/lib/intel64/libmkl_rt.so 50
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so liblapack.so-x86_64-linux-gnu /opt/intel/oneapi/mkl/$MKL_ONEAPI_VERSION/lib/intel64/libmkl_rt.so 50
   update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so.3 liblapack.so.3-x86_64-linux-gnu /opt/intel/oneapi/mkl/$MKL_ONEAPI_VERSION/lib/intel64/libmkl_rt.so 50
   echo "/opt/intel/oneapi/mkl/latest/lib/intel64" >> /etc/ld.so.conf.d/mkl.conf
   echo "MKL_THREADING_LAYER=GNU" >> /etc/environment
   ldconfig

   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SRC/intel/oneapi/mkl/$MKL_ONEAPI_VERSION/lib/intel64/
   bash -c "source /opt/intel/oneapi/mkl/latest/env/vars.sh"
   bash -c "source /opt/intel/oneapi/compiler/latest/env/vars.sh"


   ###########################   Cython
   apt-get install -y -q python3-dev python3-pip
   mkdir -p $SRC/cython/build/
   cd $SRC/cython/build/
   git clone -b 0.29.21 https://github.com/cython/cython.git source/
   cd source/
   python3 ./setup.py install


   ###########################   Numpy, Scipy @ MKL oneAPI
   # Python 3 Numpy
   pip3 install pybind11
   cd $SRC/
   wget -q --retry-connrefused https://github.com/numpy/numpy/archive/v$NUMPY3_VERSION.tar.gz
   tar xzf v$NUMPY3_VERSION.tar.gz
   rm -f v$NUMPY3_VERSION.tar.gz
   cd numpy-$NUMPY3_VERSION/
   cp site.cfg.example site.cfg
   echo "[mkl]" >> site.cfg
   echo "library_dirs = /opt/intel/oneapi/mkl/latest/lib/intel64" >> site.cfg
   echo "include_dirs = /opt/intel/oneapi/mkl/latest/include" >> site.cfg
   echo "mkl_libs = mkl_rt" >> site.cfg
   echo "lapack_libs =" >> site.cfg
   python3 setup.py config build_clib build_ext install
   cd ../
   python3 -c "import numpy as np;np.__config__.show()"

   # Python 3 SciPy
   pip3 install pythran
   apt-get install -y -q curl libgmp-dev libmpfr-dev libsuitesparse-dev libmpc-dev
   cd $SRC/
   git clone https://github.com/scipy/scipy.git scipy/
   cd scipy/
   # python3 -c "import sys, numpy; print(numpy.__version__, sys.version_info)"  # result:  1.19.5 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
   python3 setup.py config build_clib build_ext install
   cd ../
   python3 -c "import scipy as sp;sp.__config__.show()"
```

### Error message

```shell
Cythonizing sources
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/mkl/latest/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/mkl/latest/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/mkl/latest/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/mkl/latest/include']

/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/system_info.py:838: UserWarning: Specified path /usr/local/include/python3.9 is invalid.
  return self.get_paths(self.section, key)
/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/system_info.py:838: UserWarning: Specified path /usr/include/suitesparse/python3.9 is invalid.
  return self.get_paths(self.section, key)
blas_opt_info:
blas_mkl_info:
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/mkl/latest/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/mkl/latest/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/mkl/latest/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/mkl/latest/include']

Traceback (most recent call last):
  File "/usr/local/src/scipy/setup.py", line 532, in <module>
    setup_package()
  File "/usr/local/src/scipy/setup.py", line 528, in setup_package
    setup(**metadata)
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "/usr/local/src/scipy/setup.py", line 438, in configuration
    config.add_subpackage('scipy')
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 1018, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 984, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 18, in configuration
    config.add_subpackage('optimize')
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 1018, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 984, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/optimize/setup.py", line 130, in configuration
    config.add_subpackage('_highs')
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 1018, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 984, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/usr/local/lib/python3.9/dist-packages/numpy-1.19.5-py3.9-linux-x86_64.egg/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/optimize/_highs/setup.py", line 63, in configuration
    _major_dot_minor = _get_version(
  File "scipy/optimize/_highs/setup.py", line 50, in _get_version
    with open(CMakeLists, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/src/scipy/scipy/_lib/highs/CMakeLists.txt'
FATAL:   While performing build: while running engine: exit status 1
```

### SciPy/NumPy/Python version information

Scipy master;  1.19.5 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @AlexKurek, thanks for reporting. From your recipe I can see that you are missing the submodules initialization. Please do `git submodule update --init` before trying to compile. This should fix your issue.

The information about compiling the dev environment can be found https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#development-environment

**Comment by tupui** [comment]
No worries, thanks for coming back and closing!
