### ISSUE TITLE
BUG: ImportError: cannot import name 'MatFile4Reader' from 'scipy.io.matlab

### ISSUE THREAD

**Issue by jschueller** [scipy/scipy#15716]
### Describe your issue.

the following line results in a warning:
`from scipy.io.matlab.mio4 import MatFile4Reader`

```
<string>:1: DeprecationWarning: Please use `MatFile4Reader` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.mio4` namespace is deprecated.
```

then if I follow this advice I get:
`from scipy.io.matlab import MatFile4Reader`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'MatFile4Reader' from 'scipy.io.matlab' (/usr/lib/python3.10/site-packages/scipy/io/matlab/__init__.py)
```

### Reproducing Code Example

```python
`from scipy.io.matlab import MatFile4Reader`
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'MatFile4Reader' from 'scipy.io.matlab' (/usr/lib/python3.10/site-packages/scipy/io/matlab/__init__.py)
```
```


### SciPy/NumPy/Python version information

1.8.0

**Comment by tupui** [comment]
Hi Julien, long time no see 😉 

Indeed, the message is wrong. In this particular case, you should use `scipy.io.loadmat` which is behind the seen calling `MatFile4Reader` (or another one).

**Comment by jschueller** [comment]
hi, thanks for the answer

**Comment by tupui** [comment]
Linked to #15766

**Comment by AtsushiSakai** [comment]
I think this query is already answered and solved. So, let's close this issue.
