### ISSUE TITLE
Race condition in macOS Meson build between `_matfuncs_expm` and `cython_lapack.pxd`

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15962]
It happens rarely in CI, but I've seen it twice now in the build logs:
- https://github.com/scipy/scipy/runs/5823922422?check_suite_focus=true
- https://github.com/scipy/scipy/runs/5891684256?check_suite_focus=true

Traceback:

```
[627/1564] Generating 'scipy/linalg/_matfuncs_expm.cpython-310-darwin.so.p/_matfuncs_expm.c'.
FAILED: scipy/linalg/_matfuncs_expm.cpython-310-darwin.so.p/_matfuncs_expm.c 
/usr/local/miniconda/envs/scipy-meson/bin/python /Users/runner/work/scipy/scipy/scipy/_build_utils/cythoner.py scipy/linalg/_matfuncs_expm.pyx scipy/linalg/_matfuncs_expm.cpython-310-darwin.so.p/_matfuncs_expm.c

Error compiling Cython file:
------------------------------------------------------------
...
import random
cimport numpy as cnp
import numpy as np
from libc.stdlib cimport malloc, free
from libc.math cimport fabs, ceil, log2, pow
from scipy.linalg.cython_lapack cimport (sgetrf, sgetrs, dgetrf, dgetrs,
^
------------------------------------------------------------

scipy/linalg/_matfuncs_expm.pyx:9:0: 'scipy/linalg/cython_lapack.pxd' not found
Traceback (most recent call last):
  File "/Users/runner/work/scipy/scipy/scipy/_build_utils/cythoner.py", line 28, in <module>
    main()
  File "/Users/runner/work/scipy/scipy/scipy/_build_utils/cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "/usr/local/miniconda/envs/scipy-meson/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', '/Users/runner/work/scipy/scipy/build/scipy/linalg/_matfuncs_expm.cpython-310-darwin.so.p/_matfuncs_expm.c', '--include-dir', '/Users/runner/work/scipy/scipy/build', '/Users/runner/work/scipy/scipy/build/scipy/linalg/_matfuncs_expm.pyx']' returned non-zero exit status 1.
```

It looks like a dependency for the Cython generator involved here isn't quite correct.

**Comment by matthew-brett** [comment]
Aha - yes - I specified that file depended on the local `__init__.py` file, but it also depends on the generated Cython lapack etc files - I think the correct fix is in #15970
