### ISSUE TITLE
BUG: Missing ``matmat`` coverage in ``scipy.sparse.linalg.aslinearoperator``

### ISSUE THREAD

**Issue by mfeuerle** [scipy/scipy#16113]
### Describe your issue.

When calling ``scipy.sparse.linalg.aslinearoperator`` with an matrix ``A`` that implements all of the methods ``matvec``, ``matmat``, ``rmatvec`` and ``rmatmat`` the resulting ``scipy.sparse.linalg.LinearOperator`` uses the provided methods for ``matvec``, ``rmatvec`` and ``rmatmat`` but not for ``matmat`` where the default implementation is used instead of the user-provided implementation. This is annoying since the default implementation is inefficient and falls back to several ``matvec`` calls.

This should be changed such that the user provided implementation is used.

### Reproducing Code Example

```python
from scipy.sparse.linalg import aslinearoperator
class Matrix:
    shape = (1,1)
    dtype = float
    
    def matvec(self, x):
        print("matvec")

    def matmat(self, x):
        print("matmat")
    
    def rmatvec(self, x):
        print("rmatvec")
        
    def rmatmat(self, x):
        print("rmatmat")
        
A = aslinearoperator(Matrix())
A._matvec(1)
A._rmatvec(1)
A._rmatvec(1)
A._matmat(1)
```

### Error message

```shell
matvec
rmatvec
rmatvec
Traceback (most recent call last):
  File "/home/moritz/uni/13semester/Masterarbeit/Vorloeper/wave_equation_py/examples/kron/test_cases.py", line 912, in <module>
    A._matmat(1)
  File "/home/moritz/uni/13semester/Masterarbeit/Vorloeper/venv/lib/python3.9/site-packages/scipy/sparse/linalg/_interface.py", line 527, in _matmat
    return super()._matmat(X)
  File "/home/moritz/uni/13semester/Masterarbeit/Vorloeper/venv/lib/python3.9/site-packages/scipy/sparse/linalg/_interface.py", line 187, in _matmat
    return np.hstack([self.matvec(col.reshape(-1,1)) for col in X.T])
AttributeError: 'int' object has no attribute 'T'
```

### SciPy/NumPy/Python version information

1.8.0

**Comment by lobpcg** [comment]
Is not it needed to return something meaningful in the definition of matmat so that it doesn't fall back to matvec?

**Comment by mfeuerle** [comment]
If you call ``aslinearoperator`` with a object that is not a (sparse) matrix or a ``LinearOperator`` the [following code is executed](https://github.com/scipy/scipy/blob/651a9b717deb68adde9416072c1e1d5aa14a58a1/scipy/sparse/linalg/_interface.py#L810):

```
if hasattr(A, 'shape') and hasattr(A, 'matvec'):
    rmatvec = None
    rmatmat = None
    dtype = None
    
    if hasattr(A, 'rmatvec'):
        rmatvec = A.rmatvec
    if hasattr(A, 'rmatmat'):
        rmatmat = A.rmatmat
    if hasattr(A, 'dtype'):
        dtype = A.dtype
    return LinearOperator(A.shape, A.matvec, rmatvec=rmatvec,
                          rmatmat=rmatmat, dtype=dtype)
```
Obviously the ``matmul`` function is completely ignored. There are two major problems with that:
1. Your object **must** implement the ``matvec`` function. A object that only implements ``matmul`` is not accepted even though ``matvec`` could be implemented by simply falling back to ``matmul`` as the default implementation of ``LinearOperator`` already does anyways. 
2. Even if your object supplies a efficient ``matmul`` implementation it will always fall back to a probably inefficient default implementation based on ``matvec``.

**Comment by lobpcg** [comment]
I do not see this example as a proof of a bug. It's documented at https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.aslinearoperator.html :
"An object with .shape and .matvec attributes"

It is reasonable to request that aslinearoperator takes objects with other attributes in which case the request is for an enhancement, rather than a bug report., - just like your already opened https://github.com/scipy/scipy/issues/16114

**Comment by lucascolley** [comment]
Here is a clearer demonstration of the bug:

```python
In [22]: from scipy.sparse.linalg import aslinearoperator
    ...: class Matrix:
    ...:     shape = (1,1)
    ...:     dtype = float
    ...:
    ...:     def matvec(self, x):
    ...:         return x
    ...:
    ...:     def matmat(self, x):
    ...:         return 2 * x
    ...:
    ...:     def rmatvec(self, x):
    ...:         return x
    ...:
    ...:     def rmatmat(self, x):
    ...:         return x
    ...:
    ...: A = aslinearoperator(Matrix())

In [24]: A.matmat(one.reshape(1, 1))
Out[24]: array([[1]])
```

**Comment by lucascolley** [comment]
this diff fixes the issue:

```diff
diff --git a/scipy/sparse/linalg/_interface.py b/scipy/sparse/linalg/_interface.py
index 7b421cd93e..e826f2690e 100644
--- a/scipy/sparse/linalg/_interface.py
+++ b/scipy/sparse/linalg/_interface.py
@@ -1142,14 +1142,12 @@ def aslinearoperator(A):
         if hasattr(A, 'shape') and hasattr(A, 'matvec'):
-            rmatvec = None
-            rmatmat = None
-            dtype = None
-
-            if hasattr(A, 'rmatvec'):
-                rmatvec = A.rmatvec
-            if hasattr(A, 'rmatmat'):
-                rmatmat = A.rmatmat
-            if hasattr(A, 'dtype'):
-                dtype = A.dtype
-            return LinearOperator(A.shape, A.matvec, rmatvec=rmatvec,
-                                  rmatmat=rmatmat, dtype=dtype)
+            matmat = getattr(A, 'matmat', None)
+            rmatvec = getattr(A, 'rmatvec', None)
+            rmatmat = getattr(A, 'rmatmat', None)
+            dtype = getattr(A, 'dtype', None)
+
+            return LinearOperator(
+                A.shape, A.matvec,
+                matmat=matmat, rmatvec=rmatvec, rmatmat=rmatmat,
+                dtype=dtype,
+            )
```

sorry for the wait @mfeuerle . This should probably be fixed alongside gh-24510 for the next release.

**Comment by mfeuerle** [comment]
Funily enough, after 4 years i stumbled over that again just a few days ago and was planning a PR to fix that for tomorrow. Quite the coincidence :D

You need one additional adaption, i think, it should also be supportet to only supply `matmat`. Your implementation of `aslinearoperator` does that, but if i remember correct, `_CustomLinearOperator` thakes `matvec` as a mandatory argument, i.e. `matvec=None` is not supported. That should be changed to an optional argement as well and then check in `_CustomLinearOperator.__init__` that `matmat` and `matvec` are not both `None` at the same time.

**Comment by lucascolley** [comment]
> it should also be supportet to only supply `matmat`

Haha, see gh-24510

**Comment by lucascolley** [comment]
by the way, in case you happened to be interested, please do check out https://github.com/scipy/scipy/pull/23836 and https://discuss.scientific-python.org/t/batching-linearoperator-status-and-benchmarks/2199
