### ISSUE TITLE
BUG: dll loading failure with qhull

### ISSUE THREAD

**Issue by Code4SAFrankie** [scipy/scipy#16182]
### Describe your issue.

Getting this error when importing seaborn

`ImportError: DLL load failed while importing qhull: The specified module could not be found.`

### Reproducing Code Example

```python
import seaborn as sns
```

### Error message

```shell
Traceback (most recent call last):
File "", line 1, in
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn_init_.py", line 2, in
from .rcmod import * # noqa: F401,F403
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\rcmod.py", line 7, in
from . import palettes
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\palettes.py", line 9, in
from .utils import desaturate, get_color_cycle
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\utils.py", line 10, in
from scipy import stats
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\stats_init_.py", line 441, in
from .stats import *
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\stats\stats.py", line 37, in
from scipy.spatial.distance import cdist
File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\spatial_init_.py", line 98, in
from .qhull import *
ImportError: DLL load failed while importing qhull: The specified module could not be found.
```

### SciPy/NumPy/Python version information

1.7.2 1.22.3 sys.version_info(major=3, minor=9, micro=8, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @Code4SAFrankie, thank you for reporting. Please add a meaningful title for your issue.

How did you install SciPy in your environment?

**Comment by tupui** [comment]
I am afraid that we do not support these wheels. The only guarantee we provide is with wheels available on PyPi and conda-forge. Can you try these instead? In the meantime I will close this issue.

**Comment by Code4SAFrankie** [comment]
Installing recently released scipy and seaborn latest fixed it.

**Comment by tupui** [comment]
Glad to read 👍
