### ISSUE TITLE
BUG: find_peaks() fails if x.flags.writable = False

### ISSUE THREAD

**Issue by adlerandy** [scipy/scipy#16197]
### Describe your issue.

If the writable flag has been set to False on a np.array, then find_peaks() fails with a ValueError: buffer source array is read-only.
 
It seems that the View.MemoryView functions require writable arrays, but then why are they called "View"?

### Reproducing Code Example

```python
import numpy, scipy.signal

x = numpy.linspace(0,1,100)
x.flags.writeable = False
p = scipy.signal.find_peaks(x)
```

### Error message

```shell
Traceback (most recent call last):
  File "<ipython-input-18-b0e8a4dbfe44>", line 1, in <module>
    p=scipy.signal.find_peaks(x)
  File "/usr/lib/python3/dist-packages/scipy/signal/_peak_finding.py", line 936, in find_peaks
    peaks, left_edges, right_edges = _local_maxima_1d(x)
  File "_peak_finding_utils.pyx", line 20, in scipy.signal._peak_finding_utils._local_maxima_1d
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

### SciPy/NumPy/Python version information

1.8.0 1.21.5 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by rkern** [comment]
Indeed, we should use `const` to indicate that read-only arrays are permissible since the function doesn't actually write back into the input array. [This feature](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#read-only-views) isn't exactly _new_ to Cython, but I expect that it didn't exist at the time `_local_maxima_1d()` was first written.
