### ISSUE TITLE
BUG: scipy.spatial.ConvexHull does not allow deep-copy when setting incremental=True

### ISSUE THREAD

**Issue by Jarvis-X** [scipy/scipy#16190]
### Describe your issue.

Hi, Scipy team,

I got a problem when working with scipy.spatial.ConvexHull class. After creating an instance of ConvexHull object with flag `incremental=True`, trying to `copy.deepcopy` yields `TypeError: self._qh cannot be converted to a Python object for pickling`. The error does not appear when `incremental=False`. Minimal reproducing code is attached in the Reproducing Code Example textbox. 

Full error message:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "$...my_path...$\Python\Python38\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in scipy.spatial._qhull._Qhull.__reduce_cython__
TypeError: self._qh cannot be converted to a Python object for pickling
```

My environment setup:
System: Windows 10 Home
CPU: Intel i7-10700
Python version: 3.8.6
Scipy version: 1.8.0 installed with Pycharm
Numpy version: 1.21.4 installed with Pycharm

I appreciate it if you look into this issue. Feel free to relabel it. Thank you!

### Reproducing Code Example

```python
from scipy.spatial import ConvexHull
import copy

# random non-degenerate input 
hull1 = ConvexHull(np.array([[0, 1,3], [2,3,4], [8,-1,9], [2,4,0]]), incremental=True) 
hull2 = copy.deepcopy(hull1)
```

### Error message

```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "$...my_path...$\Python\Python38\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "$...my_path...$\Python\Python38\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in scipy.spatial._qhull._Qhull.__reduce_cython__
TypeError: self._qh cannot be converted to a Python object for pickling
```

### SciPy/NumPy/Python version information

1.8.0 1.21.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
Note that this isn't specific to `ConvexHull`--all `incremental=True` cases below fail. `_qh` looks like a C pointer, which is probably why it is a pain to pickle sometimes. The reason this works when `incremental=False` didn't immediately jump out at me.

```diff
diff --git a/scipy/spatial/tests/test_qhull.py b/scipy/spatial/tests/test_qhull.py
index 597837297..8ebf63550 100644
--- a/scipy/spatial/tests/test_qhull.py
+++ b/scipy/spatial/tests/test_qhull.py
@@ -794,6 +794,24 @@ class TestConvexHull:
         expected = np.array([True, False, False, False], dtype=bool)
         assert_equal(hull.good, expected)
 
+
+    @pytest.mark.parametrize("class_obj", [
+        qhull.ConvexHull,
+        qhull.Voronoi,
+        qhull.Delaunay,
+    ])
+    @pytest.mark.parametrize("incremental", [False, True])
+    def test_pickle(self, class_obj, incremental):
+        # test for gh-16190
+        points = np.array([[0.2, 0.2],
+                           [0.2, 0.4],
+                           [0.4, 0.4],
+                           [0.4, 0.2],
+                           [0.3, 0.3]])
+        obj = class_obj(points=points,
+                        incremental=incremental)
+        obj_copied = copy.deepcopy(obj)
+
 class TestVoronoi:
     def test_masked_array_fails(self):
         masked_array = np.ma.masked_all(1)

```

**Comment by WarrenWeckesser** [comment]
Another report of the pickling proble, on stackoverflow: https://stackoverflow.com/questions/76361414/is-there-a-way-to-save-pre-calculated-voronoi-diagrams-with-incremental-option-t
