### ISSUE TITLE
BUG: sphinx fails on building documentation as man page

### ISSUE THREAD

**Issue by kloczek** [scipy/scipy#16207]
### Describe your issue.

I'm trying to package your module as an rpm package. more than 5/9 of all my +930 packages with python modules provides documentation as man pages. Look like building such documentation fails with few call traces. In case of `scipy` I'm building that documetation as next step after `python3 -sBm build -w --no-isolation` so after that whole module with its DSOs is under build/

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
[tkloczko@devel-g2v scipy-1.8.1]$ PYTHONPATH=$PWD/build/$(cd build; ls -d1 lib*) /usr/bin/sphinx-build -n -T -b man doc/source build/sphinx/man
Running Sphinx v4.5.0
SciPy (VERSION 1.8.1)
[autosummary] generating autosummary for: building/faq.rst, building/index.rst, building/linux.rst, building/macosx.rst, building/windows.rst, dev/api-dev/api-dev-toc.rst, dev/api-dev/nan_policy.rst, dev/api-dev/special_ufuncs.rst, dev/conduct/code_of_conduct.rst, dev/conduct/report_handling_manual.rst, ..., tutorial/stats/discrete_yulesimon.rst, tutorial/stats/discrete_zipf.rst, tutorial/stats/discrete_zipfian.rst, tutorial/stats/sampling.rst, tutorial/stats/sampling_dau.rst, tutorial/stats/sampling_dgt.rst, tutorial/stats/sampling_hinv.rst, tutorial/stats/sampling_pinv.rst, tutorial/stats/sampling_srou.rst, tutorial/stats/sampling_tdr.rst
[autosummary] generating autosummary for: /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.optimize.LbfgsInvHessProduct.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.bsr_array.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.csc_array.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.csc_matrix.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.csr_array.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.csr_matrix.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.dok_array.rst, /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.sparse.lil_array.rst
loading intersphinx inventory from https://docs.python.org/dev/objects.inv...
loading intersphinx inventory from https://numpy.org/devdocs/objects.inv...
loading intersphinx inventory from https://numpy.org/neps/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://asv.readthedocs.io/en/stable/objects.inv...
intersphinx inventory has moved: https://matplotlib.org/objects.inv -> https://matplotlib.org/stable/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 4201 added, 0 changed, 0 removed
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeOneSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeTwoSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeThreeSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFourSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFiveSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmsy10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmr10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmtt10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmmi10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmb10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmss10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmex10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans Display'] not found. Falling back to DejaVu Sans.
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/interpolate/_fitpack2.py:docstring of scipy.interpolate._fitpack2.RectSphereBivariateSpline:95: WARNING: Exception occurred in plotting scipy-interpolate-RectSphereBivariateSpline-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.interpolate.RectSphereBivariateSpline.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 647, in render_figures
    figman.canvas.figure.savefig(img.filename(fmt), dpi=dpi)
  File "/usr/lib64/python3.8/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 2788, in print_pdf
    file.finalize()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 809, in finalize
    self.writeImages()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1758, in writeImages
    self._writeImg(data, ob.id, smaskObject)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1721, in _writeImg
    img = img.convert(mode='P', dither=Image.NONE,
  File "/usr/lib64/python3.8/site-packages/PIL/Image.py", line 67, in __getattr__
    warnings.warn(
DeprecationWarning: NONE is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/io/wavfile.py:docstring of scipy.io.wavfile.read:84: WARNING: Exception occurred in plotting scipy-io-wavfile-read-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.io.wavfile.read.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 12, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/io/wavfile.py", line 647, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/io/tests/data/test-44100Hz-2ch-32bit-float-be.wav'
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/ndimage/_interpolation.py:docstring of scipy.ndimage._interpolation.rotate:108: WARNING: Exception occurred in plotting scipy-ndimage-rotate-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.ndimage.rotate.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 647, in render_figures
    figman.canvas.figure.savefig(img.filename(fmt), dpi=dpi)
  File "/usr/lib64/python3.8/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 2788, in print_pdf
    file.finalize()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 809, in finalize
    self.writeImages()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1758, in writeImages
    self._writeImg(data, ob.id, smaskObject)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1721, in _writeImg
    img = img.convert(mode='P', dither=Image.NONE,
  File "/usr/lib64/python3.8/site-packages/PIL/Image.py", line 67, in __getattr__
    warnings.warn(
DeprecationWarning: NONE is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/ndimage/_interpolation.py:docstring of scipy.ndimage._interpolation.zoom:117: WARNING: Exception occurred in plotting scipy-ndimage-zoom-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.ndimage.zoom.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 647, in render_figures
    figman.canvas.figure.savefig(img.filename(fmt), dpi=dpi)
  File "/usr/lib64/python3.8/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 2788, in print_pdf
    file.finalize()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 809, in finalize
    self.writeImages()
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1758, in writeImages
    self._writeImg(data, ob.id, smaskObject)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 1721, in _writeImg
    img = img.convert(mode='P', dither=Image.NONE,
  File "/usr/lib64/python3.8/site-packages/PIL/Image.py", line 67, in __getattr__
    warnings.warn(
DeprecationWarning: NONE is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/signal/windows/_windows.py:docstring of scipy.signal.windows._windows.bohman:33: WARNING: Exception occurred in plotting scipy-signal-windows-bohman-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.signal.windows.bohman.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
RuntimeWarning: divide by zero encountered in log10
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/signal/windows/_windows.py:docstring of scipy.signal.windows._windows.cosine:36: WARNING: Exception occurred in plotting scipy-signal-windows-cosine-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.signal.windows.cosine.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 16, in <module>
RuntimeWarning: divide by zero encountered in log10
/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/stats/_qmc.py:docstring of scipy.stats._qmc.MultivariateNormalQMC:43: WARNING: Exception occurred in plotting scipy-stats-qmc-MultivariateNormalQMC-1
 from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/reference/generated/scipy.stats.qmc.MultivariateNormalQMC.rst:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 3, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/stats/_qmc.py", line 1547, in __init__
    self.engine = Sobol(d=engine_dim, scramble=True, seed=seed)  # type: QMCEngine
  File "/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/stats/_qmc.py", line 1334, in __init__
    initialize_direction_numbers()
  File "_sobol.pyx", line 101, in scipy.stats._sobol.initialize_direction_numbers
  File "/usr/lib64/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/build/lib.linux-x86_64-cpython-38/scipy/stats/_sobol_direction_numbers.npz'
ERROR: [numpydoc] While processing docstring for 'scipy.optimize._linprog._linprog_highs_doc'

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 281, in run
    return super().run()
  File "/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/scipyoptdoc.py", line 144, in run
    mangle_docstrings(env.app, 'function', impl_name,
  File "/usr/lib/python3.8/site-packages/numpydoc/numpydoc.py", line 170, in mangle_docstrings
    doc = get_doc_object(obj, what, u_NL.join(lines), config=cfg,
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 442, in get_doc_object
    return SphinxFunctionDoc(obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 396, in __init__
    FunctionDoc.__init__(self, obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 572, in __init__
    NumpyDocString.__init__(self, doc, config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 147, in __init__
    self._parse()
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 380, in _parse
    sections = list(self._read_sections())
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 211, in _read_sections
    data = self._read_to_next_section()
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 201, in _read_to_next_section
    while not self._is_at_section() and not self._doc.eof():
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 181, in _is_at_section
    self._error_location("potentially wrong underline length... \n%s \n%s in \n%s"\
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 440, in _error_location
    warn(msg)
UserWarning: potentially wrong underline length...
Returns
---------------- in
Linear programming: minimize a linear objective function subject to linear
equality and inequality constraints using one of the HiGHS solvers....

Exception occurred:
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 440, in _error_location
    warn(msg)
UserWarning: potentially wrong underline length...
Returns
---------------- in
Linear programming: minimize a linear objective function subject to linear
equality and inequality constraints using one of the HiGHS solvers....
The full traceback has been saved in /tmp/sphinx-err-56k7l0wd.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/sphinx-err-kqm37p1k.log
# Sphinx version: 4.5.0
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   reading sources... [ 93%] reference/linalg.cython_blas
#   reading sources... [ 93%] reference/linalg.cython_lapack
#   reading sources... [ 93%] reference/linalg.interpolative
#   reading sources... [ 93%] reference/linalg.lapack
#   reading sources... [ 93%] reference/misc
#   reading sources... [ 94%] reference/ndimage
#   reading sources... [ 94%] reference/odr
#   reading sources... [ 94%] reference/optimize
#   reading sources... [ 94%] reference/optimize.cython_optimize
#   reading sources... [ 94%] reference/optimize.linprog-highs
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.coverage (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.intersphinx (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   numpydoc (1.3.1) from /usr/lib/python3.8/site-packages/numpydoc/__init__.py
#   sphinx_panels (0.6.0) from /usr/lib/python3.8/site-packages/sphinx_panels/__init__.py
#   scipyoptdoc (unknown version) from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/scipyoptdoc.py
#   doi_role (0.1) from /home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/doi_role.py
#   matplotlib.sphinxext.plot_directive (3.5.1) from /usr/lib64/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py
#   sphinx.ext.linkcode (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/linkcode.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 281, in run
    return super().run()
  File "/home/tkloczko/rpmbuild/BUILD/scipy-1.8.1/doc/source/scipyoptdoc.py", line 144, in run
    mangle_docstrings(env.app, 'function', impl_name,
  File "/usr/lib/python3.8/site-packages/numpydoc/numpydoc.py", line 170, in mangle_docstrings
    doc = get_doc_object(obj, what, u_NL.join(lines), config=cfg,
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 442, in get_doc_object
    return SphinxFunctionDoc(obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 396, in __init__
    FunctionDoc.__init__(self, obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 572, in __init__
    NumpyDocString.__init__(self, doc, config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 147, in __init__
    self._parse()
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 380, in _parse
    sections = list(self._read_sections())
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 211, in _read_sections
    data = self._read_to_next_section()
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 201, in _read_to_next_section
    while not self._is_at_section() and not self._doc.eof():
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 181, in _is_at_section
    self._error_location("potentially wrong underline length... \n%s \n%s in \n%s"\
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 440, in _error_location
    warn(msg)
UserWarning: potentially wrong underline length...
Returns
---------------- in
Linear programming: minimize a linear objective function subject to linear
equality and inequality constraints using one of the HiGHS solvers....
```
```


### SciPy/NumPy/Python version information

1.8.1

**Comment by rossbar** [comment]
This was fixed by #15443, looks like I should have raised it for backport in 1.8.1 - sorry for the oversight "/

**Comment by kloczek** [comment]
OK will try to test this. If it will be OK pelase let me close thi sticket 😋 
Thx

**Comment by rgommers** [comment]
Thanks @rossbar, I've added the backport label to your PR.

> OK I've tested that PR and indeed it fixed that issue however I'm still not able to render man page because some other issue

We've been over this: https://github.com/numpy/numpy/issues/20229. We're not supporting `man pages`, and no we're not re-discussing it. Closing as invalid.

**Comment by kloczek** [comment]
Just checked my spec files
```console
[tkloczko@devel-g2v SPECS]$ grep 'python3dist(numpydoc)' python-* -l
python-cycler.spec
python-fsspec.spec
python-joblib.spec
python-jupyterlab-server.spec
python-matplotlib.spec
python-pandas.spec
python-pydata-sphinx-theme.spec
python-scipy.spec
python-sphinxcontrib-bibtex.spec
python-sphinx-material.spec
python-sphinxtesters.spec
python-xyzservices.spec
```
Issue is that only in case of `scipy` and `numpy` generate man pages is failing.
