### ISSUE TITLE
BUG: Build fails on Ubuntu (error about missing CMakeLists.txt)

### ISSUE THREAD

**Issue by chetmurthy** [scipy/scipy#16331]
### Describe your issue.

Trying to build scipy (top of git: commit 0d73a949ee6632349e1c55022b18571e882890c6) on Ubuntu 20.04 LTS in a freshly-created virtualenv.
```
$ python --version
Python 3.8.10
```
I installed prereqs:
```
pip install numpy pybind11 pythran
```
and then build:
```
python setup.py build
.... lots of text, including backtrace, leading up to ....
    config = setup_module.configuration(*args)
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/optimize/_highs/setup.py", line 63, in configuration
    _major_dot_minor = _get_version(
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/optimize/_highs/setup.py", line 50, in _get_version
    with open(CMakeLists, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chet/Hack/IBMQ/src/scipy/scipy/_lib/highs/CMakeLists.txt'
```

### Reproducing Code Example

```python
python setup.py build
```

### Error message

```shell
$ python setup.py build
Running from SciPy source directory.
Cythonizing sources
Running scipy/special/_generate_pyx.py
Running scipy/linalg/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
scipy/io/matlab/_mio5_utils.pyx has not changed
scipy/interpolate/interpnd.pyx has not changed
scipy/interpolate/_bspl.pyx has not changed
scipy/interpolate/_ppoly.pyx has not changed
scipy/special/_ufuncs_cxx.pyx has not changed
scipy/io/matlab/_mio_utils.pyx has not changed
scipy/special/_comb.pyx has not changed
scipy/io/matlab/_streams.pyx has not changed
scipy/special/_ufuncs.pyx has not changed
scipy/special/cython_special.pyx has not changed
scipy/special/_test_round.pyx has not changed
scipy/spatial/_qhull.pyx has not changed
scipy/spatial/_ckdtree.pyx has not changed
scipy/spatial/transform/_rotation.pyx has not changed
scipy/special/_ellip_harm_2.pyx has not changed
scipy/ndimage/src/_cytest.pyx has not changed
scipy/spatial/_hausdorff.pyx has not changed
scipy/ndimage/src/_ni_label.pyx has not changed
scipy/linalg/_solve_toeplitz.pyx has not changed
scipy/linalg/_decomp_update.pyx.in has not changed
scipy/linalg/_cythonized_array_utils.pyx has not changed
scipy/linalg/cython_lapack.pyx has not changed
scipy/linalg/_matfuncs_sqrtm_triu.pyx has not changed
scipy/linalg/cython_blas.pyx has not changed
scipy/spatial/_voronoi.pyx has not changed
scipy/fftpack/convolve.pyx has not changed
scipy/linalg/_matfuncs_expm.pyx.in has not changed
scipy/stats/_stats.pyx has not changed
scipy/stats/_qmc_cy.pyx has not changed
scipy/stats/_sobol.pyx has not changed
scipy/stats/_biasedurn.pyx has not changed
scipy/stats/_boost/src/hypergeom_ufunc.pyx has not changed
scipy/stats/_boost/src/binom_ufunc.pyx has not changed
scipy/stats/_boost/src/nbinom_ufunc.pyx has not changed
scipy/stats/_levy_stable/levyst.pyx has not changed
scipy/stats/_boost/src/beta_ufunc.pyx has not changed
scipy/stats/_unuran/unuran_wrapper.pyx has not changed
scipy/_lib/messagestream.pyx has not changed
scipy/_lib/_ccallback_c.pyx has not changed
scipy/_lib/_test_deprecation_call.pyx has not changed
scipy/signal/_spectral.pyx has not changed
scipy/_lib/_test_deprecation_def.pyx has not changed
scipy/signal/_sosfilt.pyx has not changed
scipy/signal/_max_len_seq_inner.pyx has not changed
scipy/optimize/_bglu_dense.pyx has not changed
scipy/optimize/_group_columns.pyx has not changed
scipy/stats/_boost/src/ncf_ufunc.pyx has not changed
scipy/signal/_peak_finding_utils.pyx has not changed
scipy/optimize/cython_optimize/_zeros.pyx.in has not changed
scipy/optimize/_lsq/givens_elimination.pyx has not changed
scipy/optimize/tnc/_moduleTNC.pyx has not changed
scipy/optimize/_trlib/_trlib.pyx has not changed
scipy/optimize/_highs/cython/src/_highs_wrapper.pyx has not changed
scipy/cluster/_optimal_leaf_ordering.pyx has not changed
scipy/cluster/_hierarchy.pyx has not changed
scipy/sparse/_csparsetools.pyx.in has not changed
scipy/sparse/csgraph/_reordering.pyx has not changed
scipy/sparse/csgraph/_traversal.pyx has not changed
scipy/cluster/_vq.pyx has not changed
scipy/optimize/_highs/cython/src/_highs_constants.pyx has not changed
scipy/sparse/csgraph/_matching.pyx has not changed
scipy/sparse/csgraph/_shortest_path.pyx has not changed
scipy/sparse/csgraph/_min_spanning_tree.pyx has not changed
scipy/signal/_upfirdn_apply.pyx has not changed
scipy/sparse/csgraph/_flow.pyx has not changed
scipy/sparse/csgraph/_tools.pyx has not changed
INFO: lapack_opt_info:
INFO: lapack_armpl_info:
INFO: customize UnixCCompiler
INFO:   libraries armpl_lp64_mp not found in ['/home/chet/Hack/Python-VENV/Debug/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
INFO:   NOT AVAILABLE
INFO: 
INFO: lapack_mkl_info:
INFO:   libraries mkl_rt not found in ['/home/chet/Hack/Python-VENV/Debug/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
INFO:   NOT AVAILABLE
INFO: 
INFO: openblas_lapack_info:
INFO: C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmpjapf_mad/tmp
creating /tmp/tmpjapf_mad/tmp/tmpjapf_mad
INFO: compile options: '-c'
INFO: x86_64-linux-gnu-gcc: /tmp/tmpjapf_mad/source.c
INFO: x86_64-linux-gnu-gcc -pthread /tmp/tmpjapf_mad/tmp/tmpjapf_mad/source.o -lopenblas -o /tmp/tmpjapf_mad/a.out
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/usr/lib/x86_64-linux-gnu']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/usr/lib/x86_64-linux-gnu']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/system_info.py:937: UserWarning: Specified path /usr/local/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/system_info.py:937: UserWarning: Specified path /usr/include/suitesparse/python3.8 is invalid.
  return self.get_paths(self.section, key)
/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/system_info.py:937: UserWarning: Specified path /home/chet/Hack/Python-VENV/Debug/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
non-existing path in 'scipy/linalg': 'src/lapack_deprecations/LICENSE'
INFO: blas_opt_info:
INFO: blas_armpl_info:
INFO:   libraries armpl_lp64_mp not found in ['/home/chet/Hack/Python-VENV/Debug/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
INFO:   NOT AVAILABLE
INFO: 
INFO: blas_mkl_info:
INFO:   libraries mkl_rt not found in ['/home/chet/Hack/Python-VENV/Debug/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
INFO:   NOT AVAILABLE
INFO: 
INFO: blis_info:
INFO:   libraries blis not found in ['/home/chet/Hack/Python-VENV/Debug/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
INFO:   NOT AVAILABLE
INFO: 
INFO: openblas_info:
INFO: C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmpkmtcy_me/tmp
creating /tmp/tmpkmtcy_me/tmp/tmpkmtcy_me
INFO: compile options: '-c'
INFO: x86_64-linux-gnu-gcc: /tmp/tmpkmtcy_me/source.c
INFO: x86_64-linux-gnu-gcc -pthread /tmp/tmpkmtcy_me/tmp/tmpkmtcy_me/source.o -lopenblas -o /tmp/tmpkmtcy_me/a.out
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/usr/lib/x86_64-linux-gnu']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/usr/lib/x86_64-linux-gnu']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
Traceback (most recent call last):
  File "setup.py", line 532, in <module>
    setup_package()
  File "setup.py", line 528, in setup_package
    setup(**metadata)
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 438, in configuration
    config.add_subpackage('scipy')
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/setup.py", line 18, in configuration
    config.add_subpackage('optimize')
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/optimize/setup.py", line 147, in configuration
    config.add_subpackage('_highs')
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/chet/Hack/Python-VENV/Debug/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/optimize/_highs/setup.py", line 63, in configuration
    _major_dot_minor = _get_version(
  File "/home/chet/Hack/IBMQ/src/scipy/scipy/optimize/_highs/setup.py", line 50, in _get_version
    with open(CMakeLists, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chet/Hack/IBMQ/src/scipy/scipy/_lib/highs/CMakeLists.txt'
```

### SciPy/NumPy/Python version information

>>> import sys, numpy; print(numpy.__version__, sys.version_info) 1.22.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by chetmurthy** [comment]
I did install blas, lapack, atlas, cmake, meson via apt before building.

**Comment by chetmurthy** [comment]
1. I cloned from github, and .... I never got the error-message you're citing.
2. I also tried `pip install .` and got other errors.

I'm trying your suggestion now, and it seems to have gotten further.  In the meantime, you wrote that "setup.py" is "the old setup.py" ?  Is there a way to build/install that doesn't use pip ?  I mean, something ... "low-level" ?

**Comment by eli-schwartz** [comment]
> In the meantime, you wrote that "setup.py" is "the old setup.py" ? Is there a way to build/install that doesn't use pip ? I mean, something ... "low-level" ?

SciPy is in the process of transitioning to Meson; it's now the default when using `pip install`. You can invoke it low-level:

```
meson setup builddir/ -Dpython.install_env=auto
ninja -C builddir/
ninja -C builddir/ install
```

This will build SciPy and install it, but it will be lacking pip metadata so other packages you install with `pip install` will not know SciPy is installed. The pip metadata is handled via the build backend which isn't part of Meson. In the future, Meson will probably grow its own build backend, and `ninja install` will install that too. :)

**Comment by rgommers** [comment]
> It sounds like you didn't initialize the git submodule, but this is supposed to be validated beforehand by

It's an ordering bug in the validation it looks like, `optimize` is done before `_lib`: https://github.com/scipy/scipy/blob/0d73a949ee6632349e1c55022b18571e882890c6/scipy/setup.py#L18. This check used to work, it must have broken with the addition of `_highs` because it wants to use a path during the config stage already, before the understandable error message can be emitted. I'll send a fix for that.

**Comment by rgommers** [comment]
I'll need to fix the same in the Meson build, that ends with:
```
scipy/sparse/linalg/_propack/meson.build:92:2: ERROR: File PROPACK/single/printstat.F does not exist.
```
which is also not quite as descriptive as we'd like.

**Comment by chetmurthy** [comment]
> I'll need to fix the same in the Meson build

I wondered what was causing that!  Thanks!  Also, once I did the submodule update, everything started working.  Thank you!  Closing.
