### ISSUE TITLE
BUG: IIRdesign function ftype='bessel' not recognized

### ISSUE THREAD

**Issue by nielsvanetten** [scipy/scipy#16342]
### Describe your issue.

When using `signal.iirdesign(wp, ws, gpass, gstop, analog, ftype = 'bessel', output, fs)`
Then an error is returned.

### Reproducing Code Example

```python
filter = signal.iirdesign(wp=10, ws=15, gpass=0.1, gstop=60, analog=False, ftype='bessel', output='ba', fs=1000)
```

### Error message

```shell
PS ..\python\IIR filter design> python .\iir_filter_design.py
Traceback (most recent call last):
  File "..\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\signal\_filter_design.py", line 2277, in iirdesign
    ordfunc = filter_dict[ftype][1]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\python\IIR filter design\iir_filter_design.py", line 335, in <module>
    main()
  File "..\python\IIR filter design\iir_filter_design.py", line 317, in main
    filter = signal.iirdesign(wp=10, ws=15, gpass=0.1, gstop=60, analog=False, ftype='bessel', output='ba', fs=1000)
  File "..\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\signal\_filter_design.py", line 2281, in iirdesign
    raise ValueError(("%s does not have order selection. Use "
ValueError: bessel does not have order selection. Use iirfilter function.
```

### SciPy/NumPy/Python version information

1.8.1 1.22.3 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @nielsvanetten, thank you for reporting. Yes `signal.iirdesign` does not support `ftype='bessel'`. Maybe the error message could be improved.

**Comment by nielsvanetten** [comment]
Well the most confusing thing was that in the documentation its stated that `signal.iirdesign` does support 'ftype='bessel'.
See:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.iirdesign.html

**Comment by tupui** [comment]
Right and this can be fixed. Would you like to make a PR to improve the documentation?

**Comment by nielsvanetten** [comment]
I tried to make one, hopefully I didnt mess up the procedure.

**Comment by nielsvanetten** [comment]
@tupui sorry, but i have no idea which branch I have to create this PR. Sorry, I'm not experienced enough in github.

**Comment by tupui** [comment]
@nielsvanetten No problem 😃 You have to create a branch from `main`

**Comment by nielsvanetten** [comment]
done, hopefully i did it right this time ;). thanks for your help
