### ISSUE TITLE
BUG: Python 3.10  & pandas 1.4.2 data interpolation None type error when running with PyCharm Debugger

### ISSUE THREAD

**Issue by davidjiang-gorsline** [scipy/scipy#16445]
### Describe your issue.

When tried to invoke various interpolation method in `scipy.interpolate.interp1d` via pandas Data frame in python 3.10 through pycharm debugger, the module throws a NoneType object is not callable error.

Note:
* The df.interpolate method works when it is not invoked with a method that requires Scipy package. e.g. `filled_df = gap_df.interpolate(method='linear', axis=1)` works fine. Leading me to believe the issue isn't in pandas library
* The same script that generates this error runs perfectly fine when using a python 3.9 interpreter. This led me to believe the issue is the scipy & python 3.10 compatibility.
* The same script runs perfectly fine with python 3.10 without the pycharm debugger

### Reproducing Code Example

```python
filled_df = gap_df.interpolate(method='quadratic', axis=1)

or

filled_df = gap_df.interpolate(method='cubic', axis=1)

or

filled_df = gap_df.interpolate(method='spline', order=3, axis=1)
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/numpy/core/getlimits.py", line 649, in __init__
    self.dtype = numeric.dtype(int_type)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 1099, in interpolate
    missing.interpolate_array_2d(
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/missing.py", line 249, in interpolate_array_2d
    _interpolate_2d_with_fill(
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/missing.py", line 344, in _interpolate_2d_with_fill
    np.apply_along_axis(func, axis, data)  # type: ignore[arg-type]
  File "<__array_function__ internals>", line 180, in apply_along_axis
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/missing.py", line 324, in func
    _interpolate_1d(
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/missing.py", line 455, in _interpolate_1d
    yvalues[invalid] = _interpolate_scipy_wrapper(
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/pandas/core/missing.py", line 480, in _interpolate_scipy_wrapper
    from scipy import interpolate
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/interpolate/__init__.py", line 166, in <module>
    from ._interpolate import *
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 11, in <module>
    import scipy.special as spec
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/special/__init__.py", line 652, in <module>
    from . import _basic
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/special/_basic.py", line 16, in <module>
    from . import _orthogonal
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 198, in <module>
    from ._misc import *
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/linalg/_misc.py", line 4, in <module>
    from .lapack import get_lapack_funcs
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/scipy/linalg/lapack.py", line 990, in <module>
    _int32_max = _np.iinfo(_np.int32).max
  File "/Users/David.Jiang-Gorsline/Developer/miniconda3/envs/ey-esg/lib/python3.10/site-packages/numpy/core/getlimits.py", line 651, in __init__
    self.dtype = numeric.dtype(type(int_type))
TypeError: 'NoneType' object is not callable
python-BaseException
```

### SciPy/NumPy/Python version information

1.8.1 1.22.4 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
If the suspicion is that a problem is in scipy, can you provide a standalone example which does not use pandas? Just scipy and numpy.

**Comment by davidjiang-gorsline** [comment]
This issue turned out to be due to internal setup. My sincere apologies and thank you for all your work in making and maintaining scipy!
