### ISSUE TITLE
odr.Model default meta value fails with __getattr__

### ISSUE THREAD

**Issue by kakila** [scipy/scipy#16500]
The default value ``None`` for meta is not iterable. The method ``__getattr__`` will fail.
One could change the line
https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/odr/_odrpack.py#L521

with 
```python
self.meta = [] if meta is None else meta
```

**Comment by tupui** [comment]
Hi @kakila, thank you for reporting. Could you maybe follow our template and indicate what you are trying to do, why this is needed (with some sample code maybe), what you considered etc.?

**Comment by kakila** [comment]
I found this by running doctests on a module that created a model:
```python
unilin_orig = odr.Model(
    lambda B, x: B[0] * x,
    fjacb=lambda B, x: x,
    fjacd=lambda B, x: np.full(np.shape(x), B[0]),
    estimate=lambda d: (1.0,),
 )
```
The failure is:
```
$ python -m unittest -f
...
======================================================================
ERROR: tests.test_fitters (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/juanpi/tests/test_fitters.py", line 8, in load_tests
    tests.addTests(doctest.DocTestSuite(ft))
  File "/usr/lib/python3.9/doctest.py", line 2380, in DocTestSuite
    tests = test_finder.find(module, globs=globs, extraglobs=extraglobs)
  File "/usr/lib/python3.9/doctest.py", line 939, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/usr/lib/python3.9/doctest.py", line 998, in _find
    if ((inspect.isroutine(inspect.unwrap(val))
  File "/usr/lib/python3.9/inspect.py", line 521, in unwrap
    while _is_wrapper(func):
  File "/usr/lib/python3.9/inspect.py", line 512, in _is_wrapper
    return hasattr(f, '__wrapped__')
  File "/home/juanpi/virtual_enviroments/tests/lib/python3.9/site-packages/scipy/odr/_odrpack.py", line 538, in __getattr__
    if attr in self.meta:
TypeError: argument of type 'NoneType' is not iterable
```

 This fixes it
```python
unilin_orig = odr.Model(
    lambda B, x: B[0] * x,
    fjacb=lambda B, x: x,
    fjacd=lambda B, x: np.full(np.shape(x), B[0]),
    estimate=lambda d: (1.0,),
    meta=[],  # Workaround issue https://github.com/scipy/scipy/issues/16500
)
```
Anyways, any code that uses ``__getattr__`` will fail if ``meta`` has the default value.

**Comment by boatwrong** [comment]
@tupui Hello is this issue still active? I'd like to help contribute

**Comment by tupui** [comment]
Hi @boatwrong, yes this is still an issue. Since @kakila did not reply, feel free to make a PR.

**Comment by eshirvana** [comment]
@tupui took this and made the PR .
