### ISSUE TITLE
BLD: meson 0.63.0 and new CI testing failures on Linux

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#16540]
Perhaps the most likely suspect is the release of `meson` `0.63.0` to PyPI 6 hours ago. At first I thought this was unique to the maintenance branch in https://github.com/scipy/scipy/pull/16539 but now I see it in recent PRs against `main` as well like https://github.com/scipy/scipy/pull/16537.

Quite a few of the errors at the testing stage look like this:

```
2022-07-03T20:32:00.9735081Z ___________________________ test_modules_importable ____________________________
2022-07-03T20:32:00.9736081Z [gw0] linux -- Python 3.9.13 /opt/hostedtoolcache/Python/3.9.13/x64/bin/python
2022-07-03T20:32:00.9737211Z /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/scipy/_lib/tests/test_import_cycles.py:53: in test_modules_importable
2022-07-03T20:32:00.9738187Z     subprocess.check_call([sys.executable, '-c', cmd])
2022-07-03T20:32:00.9738931Z         cmd        = 'import scipy.integrate'
2022-07-03T20:32:00.9739607Z         module     = 'scipy.integrate'
2022-07-03T20:32:00.9740239Z /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py:373: in check_call
2022-07-03T20:32:00.9740881Z     raise CalledProcessError(retcode, cmd)
2022-07-03T20:32:00.9741946Z E   subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.13/x64/bin/python', '-c', 'import scipy.integrate']' returned non-zero exit status 1.
2022-07-03T20:32:00.9743114Z         cmd        = ['/opt/hostedtoolcache/Python/3.9.13/x64/bin/python', '-c', 'import scipy.integrate']
2022-07-03T20:32:00.9743703Z         kwargs     = {}
2022-07-03T20:32:00.9744548Z         popenargs  = (['/opt/hostedtoolcache/Python/3.9.13/x64/bin/python', '-c', 'import scipy.integrate'],)
2022-07-03T20:32:00.9745166Z         retcode    = 1
2022-07-03T20:32:00.9746041Z ----------------------------- Captured stderr call -----------------------------
2022-07-03T20:32:00.9746653Z Traceback (most recent call last):
2022-07-03T20:32:00.9747137Z   File "<string>", line 1, in <module>
2022-07-03T20:32:00.9748081Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/scipy/integrate/__init__.py", line 95, in <module>
2022-07-03T20:32:00.9748798Z     from ._bvp import solve_bvp
2022-07-03T20:32:00.9749698Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/scipy/integrate/_bvp.py", line 9, in <module>
2022-07-03T20:32:00.9750619Z     from scipy.optimize import OptimizeResult
2022-07-03T20:32:00.9751586Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/scipy/optimize/__init__.py", line 414, in <module>
2022-07-03T20:32:00.9752314Z     from ._lsap import linear_sum_assignment
2022-07-03T20:32:00.9752919Z ImportError: dynamic module does not define module export function (PyInit__lsap)
```

**Comment by eli-schwartz** [comment]
PR submitted with the fix. We had originally gotten all of these, but another one crept in. :( It shouldn't happen again, because now the latest release of Meson actually exercises this.
