### ISSUE TITLE
BUG: fail to import scipy.signal with glibc 2.2.5 and scipy 1.8.x

### ISSUE THREAD

**Issue by neutrinoceros** [scipy/scipy#16602]
### Describe your issue.

`scipy.signal` fails to import, on a test server that we use at [yt](https://github.com/yt-project/yt/)
Here's the output of `import platform; print(platform.platform())` on that machine
```
Linux-4.4.26-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E5-2620_v3_@_2.40GHz-with-glibc2.2.5
```

Does this mean the wheel is somehow broken, or is scipy explicitly not supporting glibc 2.2.5 any more ?

### Reproducing Code Example

```python
import scipy.signal
```

### Error message

```shell
-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/signal/__init__.py", line 309, in <module>
    from . import _sigtools, windows
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/signal/windows/__init__.py", line 41, in <module>
    from ._windows import *
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/signal/windows/_windows.py", line 7, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /var/jenkins_home/shiningpanda/jobs/c9e5cb26/virtualenvs/d41d8cd9/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so: symbol _ZSt15__once_callable, version GLIBCXX_3.4.11 not defined in file libstdc++.so.6 with link time reference
```
I don't get this problem with scipy 1.6.3, but I see it for all more recent versions that I tested (1.7.3, 1.8.0 and 1.8.1)
```


### SciPy/NumPy/Python version information

Python 3.8, scipy 1.7.3 to 1.8.1 (at least), numpy 1.23.1

**Comment by tylerjereddy** [comment]
>  is scipy explicitly not supporting glibc 2.2.5 any more ?

I don't think it is really a SciPy-specific decision, but rather a broader community policy from i.e., PEP 600. If you look at the wheel naming transition for x86_64 between `1.6.3` and `1.7.3`, the tags switch from `manylinux1` to `manylinux2014`. According to the table in PEP600 that translates to:

> manylinux1_x86_64 is now an alias for manylinux_2_5_x86_64
> manylinux2014_x86_64 is now an alias for manylinux_2_17_x86_64

> `manylinux_${GLIBCMAJOR}_${GLIBCMINOR}_${ARCH}`
> This tag is a promise: the wheel’s creator promises that the wheel will work on any mainstream Linux distro that uses glibc version `${GLIBCMAJOR}.${GLIBCMINOR}` **or later**

From a [quick check](https://sourceware.org/glibc/wiki/Glibc%20Timeline) `glibc` `2.2.5` was released > 20 years ago, so this doesn't seem too rushed?

**Comment by neutrinoceros** [comment]
Thank you so much for this insight. I'm discovering much of the aspects of this problem as I go, your answer is extremely helpful. It now seems clear that there's nothing to be done on the side of `scipy`, so feel free to close
