### ISSUE TITLE
ENH: sparse matrix assigning should be optimized rather than using densified matrixes

### ISSUE THREAD

**Issue by likaiwen123** [scipy/scipy#16601]
### Is your feature request related to a problem? Please describe.

According to [the document of LIL sparse matrix](https://docs.scipy.org/doc/scipy-1.8.1/reference/generated/scipy.sparse.lil_matrix.html#scipy.sparse.lil_matrix), it is good at slicing and is proper to be used to construct sparse matrix. And I have found several packages using LIL sparse matrix to build an adjacent matrix like [microsoft/recommenders](https://github.com/microsoft/recommenders/blob/main/recommenders/models/deeprec/DataModel/ImplicitCF.py#L169-L178). 

However, the assigning of a sparse matrix to the slice of an LIL matrix will result in memory error, because the assigned matrix will be densified during the process. The call stack is like this below:

```python
Traceback (most recent call last):
  File "test_scipy.py", line 22, in <module>
    mat_lil[1:mini_m+1, 10:mini_n+10] = mini_lil
  File "/data/kaiwen.li/venv-pytorch/lib/python3.7/site-packages/scipy/sparse/lil.py", line 346, in __setitem__
    IndexMixin.__setitem__(self, key, x)
  File "/data/kaiwen.li/venv-pytorch/lib/python3.7/site-packages/scipy/sparse/_index.py", line 103, in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
  File "/data/kaiwen.li/venv-pytorch/lib/python3.7/site-packages/scipy/sparse/lil.py", line 332, in _set_arrayXarray_sparse
    x = np.asarray(x.toarray(), dtype=self.dtype)
  File "/data/kaiwen.li/venv-pytorch/lib/python3.7/site-packages/scipy/sparse/coo.py", line 323, in toarray
    B = self._process_toarray_args(order, out)
  File "/data/kaiwen.li/venv-pytorch/lib/python3.7/site-packages/scipy/sparse/base.py", line 1186, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 186. GiB for an array with shape (5000, 10000000) and data type float32
```

This problem can be easily regenerated using the following code:

```python
import scipy.sparse as sp
import numpy as np

rows = [0, 0, 4, 7]
cols = [1, 0, 3, 3]
vals = [2, 1, 3, 9]
m, n = int(1E4), int(1E8)
mat = sp.csr_matrix((vals, (rows, vals)), shape=(m, n), dtype=np.float32)

mini_rows = [0, 0, 4, 7]
mini_cols = [1, 0, 3, 3]
mini_vals = [2, 1, 3, 9]
mini_m, mini_n = int(5E3), int(1E7)
mini_mat = sp.csr_matrix((mini_vals, (mini_rows, mini_cols)), shape=(mini_m, mini_n), dtype=np.float32)

mat_lil = mat.tolil()
mini_lil = mini_mat.tolil()

mat_lil[1:mini_m+1, 10:mini_n+10] = mini_lil
```

From [the code of scipy](https://github.com/scipy/scipy/blob/main/scipy/sparse/_index.py#L260-L264) mentioned in the call stack, I noticed that the assignment of a sparse matrix will be degraded to dense matrix assignment. For a large sparse matrix, that may request an unbearable amount of memory. 

For the example above, assigning LIL matrix to a slice of an LIL matrix should be optimized and efficiently processed using its sparse nature, rather than converting to a dense matrix.

I know using the sparse nature to assign maybe has to consider all of the possible pairs of the types of the assigning matrix and the assignee. But I think it is worthy as dense matrixes are unbearable for most of the cases in many actual scenarios.

### Describe the solution you'd like.

The best solution would be implementation of all the possible pairs of the types of the assigning matrix and the assignee with sparse natures considered. For example, if an LIL matrix is assigned to the slice of another LIL matrix, the representation of each row of the assignee can be inserted or modified directly.

### Describe alternatives you've considered.

If it is impossible to implement all of the possible pairs, maybe implementation for a specific sparse matrix type (LIL for example) and the corresponding documents would be enough.

**Comment by likaiwen123** [comment]
Oh sorry, I didn't notice that the `IndexMixin.__setitem__(self, key, x)`'s self is set to the original LIL matrix. But maybe the full matrix assignment is a little too limited, and for other cases, the densification may lead to memory shortage. 

For my case, I have switched to directly initialize the final sparse matrix with CSR type. I may try to contribute to the extension of that feature if I could find some spare time.

Thanks for your kind reply!

**Comment by RivkaW327** [comment]
is this issue still relevant?

**Comment by WarrenWeckesser** [comment]
@RivkaW327, yes, the issue still exists.

I'd call it a bug.  We should never "fall back to densifying" a sparse matrix like we do here:

https://github.com/scipy/scipy/blob/0ef7c86a1760fc153f979c56eeab6b484ab7131e/scipy/sparse/_lil.py#L251-L255.

**Comment by bkalafut1** [comment]
> is this issue still relevant?

If LIL is to be a fully-supported representation, then yes.  Its implications for `__iadd__` break LIL.

**Comment by RivkaW327** [comment]
ok, so @WarrenWeckesser let me try to fix it.

**Comment by RivkaW327** [comment]
Hi, I’ve been working on this issue (see my PR above) and noticed something interesting.

In `IndexMixin.__setitem__`, which all sparse matrix types inherit, the code creates two very large index arrays (`i` and `j`) via broadcasting. Although they are not explicitly allocated at first, they are later materialized, which can cause assignments like the example above to fail with a `MemoryError`.

In my PR I fixed the LIL implementation to avoid densifying and instead insert only the non-zero elements. However, the failure still occurs earlier due to the creation of these broadcasted index arrays.

This raised a broader question: do other sparse formats handle large slice assignments any better?
I tested CSR and observed the same memory allocation failure (example and traceback below).

It seems that fixing this at the LIL level avoids densification but does not address the root cause in `__setitem__`.

For the LIL-specific case I can implement a localized fix, but addressing the general behavior would require changes in the shared indexing logic and may affect all sparse formats.

What would you prefer?

Should I limit the fix to LIL to resolve this issue?

Or would you like to open a separate issue to address the root cause in the indexing logic?

Alternatively, do you want me to explore a general solution?

---
### CSR example (Jupyter):
```Python
import scipy.sparse as sp
import numpy as np

rows = [0, 0, 4, 7]
cols = [1, 0, 3, 3]
vals = [2, 1, 3, 9]
m, n = int(1E4), int(1E8)
mat = sp.csr_matrix((vals, (rows, vals)), shape=(m, n), dtype=np.float32)

mini_rows = [0, 0, 4, 7]
mini_cols = [1, 0, 3, 3]
mini_vals = [2, 1, 3, 9]
mini_m, mini_n = int(5E3), int(1E7)
mini_mat = sp.csr_matrix((mini_vals, (mini_rows, mini_cols)), shape=(mini_m, mini_n), dtype=np.float32)

mat[1:mini_m+1, 10:mini_n+10] = mini_mat
```
### Result
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[2], line 16
     13 mini_m, mini_n = int(5E3), int(1E7)
     14 mini_mat = sp.csr_matrix((mini_vals, (mini_rows, mini_cols)), shape=(mini_m, mini_n), dtype=np.float32)
---> 16 mat[1:mini_m+1, 10:mini_n+10] = mini_mat

File ~\anaconda3\Lib\site-packages\scipy\sparse\_index.py:142, in IndexMixin.__setitem__(self, key, x)
    140     x = x.tocoo(copy=True)
    141     x.sum_duplicates()
--> 142     self._set_arrayXarray_sparse(i, j, x)
    143 else:
    144     # Make x and i into the same shape
    145     x = np.asarray(x, dtype=self.dtype)

File ~\anaconda3\Lib\site-packages\scipy\sparse\_compressed.py:847, in _cs_matrix._set_arrayXarray_sparse(self, row, col, x)
    845 def _set_arrayXarray_sparse(self, row, col, x):
    846     # clear entries that will be overwritten
--> 847     self._zero_many(*self._swap((row, col)))
    849     M, N = row.shape  # matches col.shape
    850     broadcast_row = M != 1 and x.shape[0] == 1

File ~\anaconda3\Lib\site-packages\scipy\sparse\_compressed.py:999, in _cs_matrix._zero_many(self, i, j)
    994 def _zero_many(self, i, j):
    995     """Sets value at each (i, j) to zero, preserving sparsity structure.
    996 
    997     Here (i,j) index major and minor respectively.
    998     """
--> 999     i, j, M, N = self._prepare_indices(i, j)
   1001     n_samples = len(i)
   1002     offsets = np.empty(n_samples, dtype=self.indices.dtype)

File ~\anaconda3\Lib\site-packages\scipy\sparse\_compressed.py:949, in _cs_matrix._prepare_indices(self, i, j)
    945     if idx < -bound:
    946         raise IndexError('index (%d) out of range (< -%d)' %
    947                          (idx, bound))
--> 949 i = np.atleast_1d(np.asarray(i, dtype=self.indices.dtype)).ravel()
    950 j = np.atleast_1d(np.asarray(j, dtype=self.indices.dtype)).ravel()
    951 check_bounds(i, M)

MemoryError: Unable to allocate 186. GiB for an array with shape (50000000000,) and data type int32
```
### Output as test
```
_________________ TestCSRNonCanonicalMatrix.test_csr_sparse_assignment_no_densify_memory_error _________________

self = <scipy.sparse.tests.test_base.TestCSRNonCanonicalMatrix object at 0x7f46f487c7d0>

    def test_csr_sparse_assignment_no_densify_memory_error(self):
        # Issue #16601: Verify sparse assignment doesn't cause memory error
        rows = [0, 0, 4, 7]
        cols = [1, 0, 3, 3]
        vals = [2, 1, 3, 9]
        m, n = int(1E4), int(1E8)
        mat = sparse.csr_matrix((vals, (rows, cols)), shape=(m, n), dtype=np.float32)
    
        # Create a smaller sparse matrix to assign
        mini_rows = [0, 0, 2, 3]
        mini_cols = [1, 0, 2, 2]
        mini_vals = [2, 1, 3, 9]
        mini_m, mini_n = int(5E3), int(1E7)
        mini_mat = sparse.csr_matrix((mini_vals, (mini_rows, mini_cols)),
                                  shape=(mini_m, mini_n), dtype=np.float32)
    
>       mat[1:mini_m+1, 10:mini_n+10] = mini_mat
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

cols       = [1, 0, 3, 3]
m          = 10000
mat        = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>
mini_cols  = [1, 0, 2, 2]
mini_m     = 5000
mini_mat   = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (5000, 10000000)>
mini_n     = 10000000
mini_rows  = [0, 0, 2, 3]
mini_vals  = [2, 1, 3, 9]
n          = 100000000
rows       = [0, 0, 4, 7]
self       = <scipy.sparse.tests.test_base.TestCSRNonCanonicalMatrix object at 0x7f46f487c7d0>
vals       = [2, 1, 3, 9]

scipy/sparse/tests/test_base.py:4545: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scipy/sparse/_index.py:208: in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
        _          = []
        broadcast_col = False
        broadcast_row = False
        col        = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(1, 10000000))
        i          = array([[   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       [   3,    3...  [4999, 4999, 4999, ..., 4999, 4999, 4999],
       [5000, 5000, 5000, ..., 5000, 5000, 5000]], shape=(5000, 10000000))
        index      = (slice(1, 5001, None), slice(10, 10000010, None))
        j          = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009],
       [      10,       11,       12, ..., 1...08, 10000009],
       [      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(5000, 10000000))
        key        = (slice(1, 5001, None), slice(10, 10000010, None))
        new_shape  = (5000, 10000000)
        row        = array([[   1],
       [   2],
       [   3],
       ...,
       [4998],
       [4999],
       [5000]], shape=(5000, 1))
        self       = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>
        x          = <COOrdinate sparse matrix of dtype 'float32'
        with 4 stored elements and shape (5000, 10000000)>
scipy/sparse/_compressed.py:737: in _set_arrayXarray_sparse
    self._zero_many(*self._swap((row, col)))
        col        = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009],
       [      10,       11,       12, ..., 1...08, 10000009],
       [      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(5000, 10000000))
        row        = array([[   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       [   3,    3...  [4999, 4999, 4999, ..., 4999, 4999, 4999],
       [5000, 5000, 5000, ..., 5000, 5000, 5000]], shape=(5000, 10000000))
        self       = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>
        x          = <COOrdinate sparse matrix of dtype 'float32'
        with 4 stored elements and shape (5000, 10000000)>
scipy/sparse/_compressed.py:895: in _zero_many
    i, j, M, N = self._prepare_indices(i, j)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        i          = array([[   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       [   3,    3...  [4999, 4999, 4999, ..., 4999, 4999, 4999],
       [5000, 5000, 5000, ..., 5000, 5000, 5000]], shape=(5000, 10000000))
        j          = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009],
       [      10,       11,       12, ..., 1...08, 10000009],
       [      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(5000, 10000000))
        self       = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>
i = array([[   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       [   3,    3...  [4999, 4999, 4999, ..., 4999, 4999, 4999],
       [5000, 5000, 5000, ..., 5000, 5000, 5000]], shape=(5000, 10000000))
j = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009],
       [      10,       11,       12, ..., 1...08, 10000009],
       [      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(5000, 10000000))

    def _prepare_indices(self, i, j):
        M, N = self._swap(self._shape_as_2d)
    
        def check_bounds(indices, bound):
            idx = indices.max()
            if idx >= bound:
                raise IndexError(f'index ({idx}) out of range (>= {bound})')
            idx = indices.min()
            if idx < -bound:
                raise IndexError(f'index ({idx}) out of range (< -{bound})')
    
>       i = np.atleast_1d(np.asarray(i, dtype=self.indices.dtype)).ravel()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       numpy._core._exceptions._ArrayMemoryError: Unable to allocate 186. GiB for an array with shape (5000, 10000000) and data type int32

M          = 10000
N          = 100000000
check_bounds = <function _cs_matrix._prepare_indices.<locals>.check_bounds at 0x7f46f3f18360>
i          = array([[   1,    1,    1, ...,    1,    1,    1],
       [   2,    2,    2, ...,    2,    2,    2],
       [   3,    3...  [4999, 4999, 4999, ..., 4999, 4999, 4999],
       [5000, 5000, 5000, ..., 5000, 5000, 5000]], shape=(5000, 10000000))
j          = array([[      10,       11,       12, ..., 10000007, 10000008, 10000009],
       [      10,       11,       12, ..., 1...08, 10000009],
       [      10,       11,       12, ..., 10000007, 10000008, 10000009]],
      shape=(5000, 10000000))
self       = <Compressed Sparse Row sparse matrix of dtype 'float32'
        with 4 stored elements and shape (10000, 100000000)>

scipy/sparse/_compressed.py:845: MemoryError
```

**Comment by dschult** [comment]
Yes -- this densification upon setting with two fancy array indexes that broadcast to each other is a bug I introduced in release 1.17.0.  It is (hopefully) fixed in #24511 and #24499 , so it should not be there for an updated branch. And will be backported for the 1.17.1 release.

The original discussion is in #24339 

Can you try your experiments with the main branch? (or with a branch that has been merged with main)?  It should no longer blow up memory due to broadcasting the indices.

**Comment by RivkaW327** [comment]
@dschult I reproduced this on current main as well. Note that my case is slice*slice assignment (`mat[r0:r1, c0:c1] = sparse_rhs`), not two fancy index arrays.

`IndexMixin.__setitem__` still converts the slices to `np.arange` arrays and then broadcasts them to `i` and `j` with shape (5000, 10_000_000). These are later materialized in `_prepare_indices(...).ravel()` (CSR/CSC) or `.flatten()` (LIL), which triggers a `MemoryError`.

This therefore appears distinct from the “two fancy array indices” regression discussed in #24339.

As I understand it, `__setitem__` converts the slices into row and column index arrays and broadcasts them to full 2D grids. When these broadcasted arrays are later flattened/raveled, they require a huge memory allocation.

I suspect the root of the problem is the conversion of slice indexing into fully broadcasted index arrays.

Do you consider slice*slice sparse assignment expected to work without allocating broadcasted indices?
What kind of fix would you prefer - addressing the root cause in the indexing logic, or handling it locally in specific sparse formats?
If this is considered a separate issue, should I open a new one, or would you prefer extending the existing fix to cover this case?

**Comment by dschult** [comment]
Sorry -- I missed that this was slice*slice.  This broadcasting of slices issue is actually quite old (8 years according to the blame report).  We don't handle sparse setting of parts of a matrix that big. It seems we allow row and column indices to be slices with the intent of broadcasting them. And we allow the values to be broadcast into the shape of the broadcast row and column. But we handle in ways that don't preserve the broadcast arrays as views -- they get converted to full arrays. So if you want to set a large region of a sparse matrix using indexing you have to be able to hold a dense version of the input.

You might be able to fix this by making sure that the i/j broadcast coords never get morphed from numpy views into numpy arrays.  That is often ugly -- I have used checking if `i.base is None` to see if it has converted (i.base is the array that the view is pointing to -- None means it is no longer a view.  Note that the incoming matrix `x` also gets broadcast to the shape of i and j. So to handle sparse arrays there we have to manually handle the broadcasting effects. 

To fix this, in `_index.py` I think we would have to go back to the broadcasting at line 190 and work down to the call of `_set_arrayXarray_sparse` and then move to that method. There is some special code to check that broadcasting of `x` to the i,j values works.  But I think that is correct -- we just need to make sure i, j, and x don't get changed from numpy views into numpy arrays.  THEN in _set_arrayXarray_sparse for each format you will need to figure out how to handle the broadcasting manually.  That's probably why the original authors punted and just converted the input to dense.

Note that the choice they made is not densifying the original sparse matrix. It is densifying the setting of a region of the sparse array by using sliceXslice or arrayXarray indexing.  That's how we got here AFAICT...

Short answer to your question: you will need to change things in both _index.py and the format-specific files.

**Comment by pirgovalex** [comment]
Hello! I want to tackle this problem head on. My current idea is to write the logic either inside the  setitem func or write a separate func/funcs to replace the indexmixin call. This is off the top of my head and i have not implemented anything right now, just wanted to level with you. Is there a pattern you would like me to follow or should I go for my approach?

**Comment by dschult** [comment]
PR #24398 is pretty far along in fixing this issue.
And there is a discussion there too. Other PRs (that appear on the right under "Development") associated with this Issue and might have helpful discussions too.

**Comment by pirgovalex** [comment]
Appreciate it!

**Comment by LeonxLJX** [comment]
I'd like to take this one (`ENH: LIL sparse matrix assigning should be optimized rather `). I'll look into the root cause and follow up with a PR. (claiming via @LeonxLJX)
