### ISSUE TITLE
BUG: Windows build problem with Cythonized files

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#16611]
### Describe your issue.

During the build of the current main branch, the build encounters failures with error codes that seem to be unsigned int overflow but might be normal.

Once again, apologies for the continuous bug reports from windows land.

### Reproducing Code Example

```python
C:> $env:CC="gcc";$env:CXX="g++";$env:PKG_CONFIG_PATH="C:\opt\64\lib\pkgconfig\";$env:SCIPY_USE_PYTHRAN=0
C:> python dev.py build
```

### Error message

<details>

```shell
[132/1551] Generating 'scipy\\sparse\\csgraph\\_flow.cp39-win_amd64.pyd.p\\_flow.c'.
FAILED: scipy/sparse/csgraph/_flow.cp39-win_amd64.pyd.p/_flow.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/sparse/csgraph/_flow.pyx" "scipy/sparse/csgraph/_flow.cp39-win_amd64.pyd.p/_flow.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\sparse\\csgraph\\_flow.cp39-win_amd64.pyd.p\\_flow.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\sparse\\csgraph\\_flow.pyx']' returned non-zero exit status 3221225477.
[133/1551] Generating 'scipy\\linalg\\_matfuncs_sqrtm_triu.cp39-win_amd64.pyd.p\\_matfuncs_sqrtm_triu.c'.
FAILED: scipy/linalg/_matfuncs_sqrtm_triu.cp39-win_amd64.pyd.p/_matfuncs_sqrtm_triu.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/linalg/_matfuncs_sqrtm_triu.pyx" "scipy/linalg/_matfuncs_sqrtm_triu.cp39-win_amd64.pyd.p/_matfuncs_sqrtm_triu.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_matfuncs_sqrtm_triu.cp39-win_amd64.pyd.p\\_matfuncs_sqrtm_triu.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\linalg\\_matfuncs_sqrtm_triu.pyx']' returned non-zero exit status 3221225477.
[134/1551] Generating 'scipy\\special\\_test_round.cp39-win_amd64.pyd.p\\_test_round.c'.
FAILED: scipy/special/_test_round.cp39-win_amd64.pyd.p/_test_round.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/special/_test_round.pyx" "scipy/special/_test_round.cp39-win_amd64.pyd.p/_test_round.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\special\\_test_round.cp39-win_amd64.pyd.p\\_test_round.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\special\\_test_round.pyx']' returned non-zero exit status 3221225477.
[135/1551] Generating 'scipy\\special\\_comb.cp39-win_amd64.pyd.p\\_comb.c'.
FAILED: scipy/special/_comb.cp39-win_amd64.pyd.p/_comb.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/special/_comb.pyx" "scipy/special/_comb.cp39-win_amd64.pyd.p/_comb.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\special\\_comb.cp39-win_amd64.pyd.p\\_comb.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\special\\_comb.pyx']' returned non-zero exit status 3221225477.
[136/1551] Generating 'scipy\\linalg\\_cythonized_array_utils.cp39-win_amd64.pyd.p\\_cythonized_array_utils.c'.
FAILED: scipy/linalg/_cythonized_array_utils.cp39-win_amd64.pyd.p/_cythonized_array_utils.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/linalg/_cythonized_array_utils.pyx" "scipy/linalg/_cythonized_array_utils.cp39-win_amd64.pyd.p/_cythonized_array_utils.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_cythonized_array_utils.cp39-win_amd64.pyd.p\\_cythonized_array_utils.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\linalg\\_cythonized_array_utils.pyx']' returned non-zero exit status 3221225477.
[137/1551] Generating 'scipy\\linalg\\_decomp_update.cp39-win_amd64.pyd.p\\_decomp_update.c'.
FAILED: scipy/linalg/_decomp_update.cp39-win_amd64.pyd.p/_decomp_update.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "scipy/linalg/_decomp_update.pyx" "scipy/linalg/_decomp_update.cp39-win_amd64.pyd.p/_decomp_update.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_decomp_update.cp39-win_amd64.pyd.p\\_decomp_update.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_decomp_update.pyx']' returned non-zero exit status 3221225477.
[138/1551] Generating 'scipy\\linalg\\_solve_toeplitz.cp39-win_amd64.pyd.p\\_solve_toeplitz.c'.
FAILED: scipy/linalg/_solve_toeplitz.cp39-win_amd64.pyd.p/_solve_toeplitz.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/linalg/_solve_toeplitz.pyx" "scipy/linalg/_solve_toeplitz.cp39-win_amd64.pyd.p/_solve_toeplitz.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_solve_toeplitz.cp39-win_amd64.pyd.p\\_solve_toeplitz.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\linalg\\_solve_toeplitz.pyx']' returned non-zero exit status 3221225477.
[139/1551] Generating 'scipy\\linalg\\cython_blas.cp39-win_amd64.pyd.p\\cython_blas.c'.
FAILED: scipy/linalg/cython_blas.cp39-win_amd64.pyd.p/cython_blas.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "scipy/linalg/cython_blas.pyx" "scipy/linalg/cython_blas.cp39-win_amd64.pyd.p/cython_blas.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\cython_blas.cp39-win_amd64.pyd.p\\cython_blas.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\cython_blas.pyx']' returned non-zero exit status 3221225477.
[141/1551] Generating 'scipy\\sparse\\csgraph\\_matching.cp39-win_amd64.pyd.p\\_matching.c'.
FAILED: scipy/sparse/csgraph/_matching.cp39-win_amd64.pyd.p/_matching.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "../scipy/sparse/csgraph/_matching.pyx" "scipy/sparse/csgraph/_matching.cp39-win_amd64.pyd.p/_matching.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\sparse\\csgraph\\_matching.cp39-win_amd64.pyd.p\\_matching.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\scipy\\sparse\\csgraph\\_matching.pyx']' returned non-zero exit status 3221225477.
[142/1551] Generating 'scipy\\linalg\\_matfuncs_expm.cp39-win_amd64.pyd.p\\_matfuncs_expm.c'.
FAILED: scipy/linalg/_matfuncs_expm.cp39-win_amd64.pyd.p/_matfuncs_expm.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "scipy/linalg/_matfuncs_expm.pyx" "scipy/linalg/_matfuncs_expm.cp39-win_amd64.pyd.p/_matfuncs_expm.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_matfuncs_expm.cp39-win_amd64.pyd.p\\_matfuncs_expm.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\_matfuncs_expm.pyx']' returned non-zero exit status 3221225477.
[143/1551] Generating 'scipy\\linalg\\cython_lapack.cp39-win_amd64.pyd.p\\cython_lapack.c'.
FAILED: scipy/linalg/cython_lapack.cp39-win_amd64.pyd.p/cython_lapack.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "scipy/linalg/cython_lapack.pyx" "scipy/linalg/cython_lapack.cp39-win_amd64.pyd.p/cython_lapack.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\cython_lapack.cp39-win_amd64.pyd.p\\cython_lapack.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\linalg\\cython_lapack.pyx']' returned non-zero exit status 3221225477.
[144/1551] Generating 'scipy\\sparse\\_csparsetools.cp39-win_amd64.pyd.p\\_csparsetools.c'.
FAILED: scipy/sparse/_csparsetools.cp39-win_amd64.pyd.p/_csparsetools.c
"C:\Users\ilhan\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils/cythoner.py" "scipy/sparse/_csparsetools.pyx" "scipy/sparse/_csparsetools.cp39-win_amd64.pyd.p/_csparsetools.c"
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 28, in <module>
    main()
  File "C:\Users\ilhan\Documents\GitHub\scipy\scipy\_build_utils\cythoner.py", line 20, in main
    sbp.run(['cython', '-3', '--fast-fail',
  File "C:\Users\ilhan\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cython', '-3', '--fast-fail', '--output-file', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\sparse\\_csparsetools.cp39-win_amd64.pyd.p\\_csparsetools.c', '--include-dir', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build', 'C:\\Users\\ilhan\\Documents\\GitHub\\scipy\\build\\scipy\\sparse\\_csparsetools.pyx']' returned non-zero exit status 3221225477.
[149/1551] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cp39-win_amd64.pyd.p/bsr.cxx.obj
ninja: build stopped: subcommand failed.
Build failed!
```

</details>

### SciPy/NumPy/Python version information

main+0bb3a79, 1.23.1 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
This is somehow happening when meson install is used but I can't know what the problem might be and I don't want to bother people with crystal ball debugging.
