### ISSUE TITLE
BUG: CI: dev.py fails to propagate doc generation errors

### ISSUE THREAD

**Issue by mckib2** [scipy/scipy#16636]
### Describe your issue.

An error occurs while generating docs using `dev.py`, but `dev.py` returns a zero-error code preventing the Circle CI docs job from failing

### Reproducing Code Example

See gh-14563

### Error message

```shell
#!/bin/bash -eo pipefail
export PYTHONPATH=$PWD/build-install/lib/python3.8/site-packages
python dev.py --no-build doc -j2

Skipping build
# for testing
# @echo installed scipy 9cd719f matches git version 9cd719f; exit 1
mkdir -p build/html build/doctrees
LANG=C /home/circleci/.pyenv/versions/3.8.13/bin/python -msphinx -WT --keep-going  -b html -d build/doctrees -j2 source build/html 
Running Sphinx v4.5.0
SciPy (VERSION pull/14563)
[autosummary] generating autosummary for: dev/api-dev/api-dev-toc.rst, dev/api-dev/nan_policy.rst, dev/api-dev/special_ufuncs.rst, dev/conduct/code_of_conduct.rst, dev/conduct/report_handling_manual.rst, dev/contributor/adding_new.rst, dev/contributor/benchmarking.rst, dev/contributor/building.rst, dev/contributor/building_faq.rst, dev/contributor/compiled_code.rst, ..., tutorial/stats/discrete_yulesimon.rst, tutorial/stats/discrete_zipf.rst, tutorial/stats/discrete_zipfian.rst, tutorial/stats/sampling.rst, tutorial/stats/sampling_dau.rst, tutorial/stats/sampling_dgt.rst, tutorial/stats/sampling_hinv.rst, tutorial/stats/sampling_pinv.rst, tutorial/stats/sampling_srou.rst, tutorial/stats/sampling_tdr.rst
[autosummary] generating autosummary for: /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.ClusterNode.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.DisjointSet.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.average.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.centroid.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.complete.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.cophenet.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.correspond.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.cut_tree.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.dendrogram.rst, ..., /home/circleci/repo/doc/source/reference/generated/scipy.stats.wrapcauchy.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.yeojohnson.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.yeojohnson_llf.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.yeojohnson_normmax.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.yeojohnson_normplot.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.yulesimon.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.zipf.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.zipfian.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.zmap.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.zscore.rst
[autosummary] generating autosummary for: /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.__getitem__.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.__len__.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.__mul__.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.count.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.from_cython.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.function.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.index.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.signature.rst, /home/circleci/repo/doc/source/reference/generated/scipy.LowLevelCallable.user_data.rst, /home/circleci/repo/doc/source/reference/generated/scipy.cluster.hierarchy.ClusterNode.get_count.rst, ..., /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.NumericalInversePolynomial.set_random_state.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.NumericalInversePolynomial.u_error.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.SimpleRatioUniforms.rvs.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.SimpleRatioUniforms.set_random_state.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.hat_area.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.ppf_hat.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.rvs.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.set_random_state.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.squeeze_area.rst, /home/circleci/repo/doc/source/reference/generated/scipy.stats.sampling.TransformedDensityRejection.squeeze_hat_ratio.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/devdocs/objects.inv...
loading intersphinx inventory from https://numpy.org/neps/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
loading intersphinx inventory from https://asv.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 323 source files that are out of date
updating environment: [new config] 4233 added, 0 changed, 0 removed
reading sources... [  3%] dev/api-dev/api-dev-toc .. reference/generated/scipy.fft.ifht
reading sources... [  6%] reference/generated/scipy.fft.ihfft .. reference/generated/scipy.integrate.ode.successful
reading sources... [ 10%] reference/generated/scipy.integrate.ode.y .. reference/generated/scipy.interpolate.NdPPoly.construct_fast
reading sources... [ 13%] reference/generated/scipy.interpolate.NdPPoly.derivative .. reference/generated/scipy.io.netcdf_file.close
reading sources... [ 16%] reference/generated/scipy.io.netcdf_file.createDimension .. reference/generated/scipy.linalg.blas.zherk
reading sources... [ 20%] reference/generated/scipy.linalg.blas.zhpmv .. reference/generated/scipy.linalg.lapack.chesvx_lwork
reading sources... [ 23%] reference/generated/scipy.linalg.lapack.chetrd .. reference/generated/scipy.linalg.lapack.dpbtrs
reading sources... [ 26%] reference/generated/scipy.linalg.lapack.dpftrf .. reference/generated/scipy.linalg.lapack.sormrz
reading sources... [ 30%] reference/generated/scipy.linalg.lapack.sormrz_lwork .. reference/generated/scipy.linalg.lapack.zhegv_lwork
reading sources... [ 33%] reference/generated/scipy.linalg.lapack.zhegvd .. reference/generated/scipy.ndimage.binary_hit_or_miss
reading sources... [ 36%] reference/generated/scipy.ndimage.binary_opening .. reference/generated/scipy.optimize.brenth
reading sources... [ 40%] reference/generated/scipy.optimize.brentq .. reference/generated/scipy.signal.ellip
reading sources... [ 43%] reference/generated/scipy.signal.ellipap .. reference/generated/scipy.sparse.block_diag
reading sources... [ 46%] reference/generated/scipy.sparse.bmat .. reference/generated/scipy.sparse.bsr_matrix.tanh
reading sources... [ 50%] reference/generated/scipy.sparse.bsr_matrix.toarray .. reference/generated/scipy.sparse.coo_matrix.tocsr
reading sources... [ 53%] reference/generated/scipy.sparse.coo_matrix.todense .. reference/generated/scipy.sparse.csc_matrix.sqrt
reading sources... [ 56%] reference/generated/scipy.sparse.csc_matrix.sum .. reference/generated/scipy.sparse.csr_matrix.format
reading sources... [ 60%] reference/generated/scipy.sparse.csr_matrix.getH .. reference/generated/scipy.sparse.dia_matrix.maximum
reading sources... [ 63%] reference/generated/scipy.sparse.dia_matrix.mean .. reference/generated/scipy.sparse.dok_matrix.trace
reading sources... [ 66%] reference/generated/scipy.sparse.dok_matrix.transpose .. reference/generated/scipy.sparse.linalg.expm_multiply
reading sources... [ 70%] reference/generated/scipy.sparse.linalg.factorized .. reference/generated/scipy.spatial.delaunay_plot_2d
reading sources... [ 73%] reference/generated/scipy.spatial.distance.braycurtis .. reference/generated/scipy.special.errstate
reading sources... [ 76%] reference/generated/scipy.special.euler .. reference/generated/scipy.special.nbdtrik
reading sources... [ 80%] reference/generated/scipy.special.nbdtrin .. reference/generated/scipy.stats.arcsine
reading sources... [ 83%] reference/generated/scipy.stats.argus .. reference/generated/scipy.stats.lognorm
reading sources... [ 86%] reference/generated/scipy.stats.logser .. reference/generated/scipy.stats.qmc.QMCEngine.fast_forward
reading sources... [ 90%] reference/generated/scipy.stats.qmc.QMCEngine.integers .. reference/generated/scipy.stats.somersd
reading sources... [ 93%] reference/generated/scipy.stats.spearmanr .. release.0.18.0
reading sources... [ 96%] release.0.18.1 .. tutorial/stats/continuous_weibull_max
reading sources... [100%] tutorial/stats/continuous_weibull_min .. tutorial/stats/sampling_tdr

waiting for workers...
/home/circleci/repo/build-install/lib/python3.8/site-packages/scipy/stats/_stats_py.py:docstring of scipy.stats._stats_py.relfreq:50: WARNING: Exception occurred in plotting scipy-stats-relfreq-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.stats.relfreq.rst:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 4, in <module>
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'default_rng'

Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 405, in read
    self._read_parallel(docnames, nproc=self.app.parallel)
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 456, in _read_parallel
    tasks.join()
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/util/parallel.py", line 93, in join
    if not self._join_one():
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sphinx/util/parallel.py", line 112, in _join_one
    exc, logs, result = pipe.recv()
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Exception occurred:
  File "/home/circleci/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
The full traceback has been saved in /tmp/sphinx-err-wnr5ntw8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:110: html-build] Error 2

CircleCI received exit code 0
```

### SciPy/NumPy/Python version information

latest, numpy 1.21.5, Python 3.8

**Comment by ev-br** [comment]
Cross-ref https://github.com/scipy/scipy/issues/16476

**Comment by mckib2** [comment]
> Cross-ref #16476

Apologies @ev-br -- did not see yours.  Closing this is favor of gh-16476

**Comment by ev-br** [comment]
This one is certainly not *completed*! 
So indeed this is `task_meta` thing in dev.py, which is suspect. 
Any ideas on how to fix the dev.py `doc` tasks, regardless of which issue tracks the `task_meta` swalloiwing error codes?

**Comment by mckib2** [comment]
@ev-br I'm not very familiar with the contents of dev.py, but a quick look seems like (for the `doc` task at least), there needs to be a way to tell the doit framework to return non-zero on error.  Right now, the [`Doc`](https://github.com/scipy/scipy/blob/906e91e412b1e0809932320b10a00587002814f9/dev.py#L933) class doesn't seem to be explaining how it'd like to handle errors

**Comment by ev-br** [comment]
I only note the difference between the test class, which uses ` run() ` and the doc task related classes which use something else.
