### ISSUE TITLE
BUG: csgraph.laplacian form as LinearOperator is not fully implemented - rmatvec or rmatmat is missing

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#16757]
### Describe your issue.

https://github.com/scipy/scipy/blob/main/scipy/sparse/csgraph/_laplacian.py form as LinearOperator is not fully implemented - rmatvec or rmatmat is missing, which prevents from, e.g., using it as an input to svds

The issue fix is simple - just adding the  rmatmat.

### Reproducing Code Example

```python
from scipy.sparse.linalg import svds
from scipy.sparse import rand
from scipy.sparse import csgraph
G = rand(9, 9)
L = csgraph.laplacian(G, form="lo")
svds(L)
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_eigen\_svds.py", line 339, in svds
    _, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter,
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_eigen\arpack\arpack.py", line 1689, in eigsh
    params.iterate()
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_eigen\arpack\arpack.py", line 547, in iterate
    self.workd[yslice] = self.OP(self.workd[xslice])
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 232, in matvec
    y = self._matvec(x)
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 530, in _matvec
    return self.__matvec_impl(x)
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_eigen\_svds.py", line 278, in matvec_XH_X
    return XH_dot(X_dot(x))
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 279, in rmatvec
    y = self._rmatvec(x)
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 535, in _rmatvec
    raise NotImplementedError("rmatvec is not defined")
NotImplementedError: rmatvec is not defined
```

### SciPy/NumPy/Python version information

1.9.0 1.23.1 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by lobpcg** [comment]
Probably not of practical interest...
