### ISSUE TITLE
BUG: LinearOperator is broken for functions that change the dimension of their input vectors? 

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#16777]
### Describe your issue.

Broken shape in LinearOperator from a function compared to aslinearoperator from a non-square matrix generated by the function:

Two linear operators, one created directly from a function by LinearOperator, and another made aslinearoperator from the matrix = function(np.eye), are expected to be identical, with the same shapes. The shape of the former needs to be explicitly set as an input to the LinearOperator, while the shape of the latter is automatically determined by the shape of the matrix.

In the code, however, this gives an error for the LinearOperator, but mysteriously works if the shape in LinearOperator is reversed rather then being the same. Although, the wrong shape gives then other problems if used this way down the road... 

So, may be LinearOperator is just broken for functions that change the dimension of their input vectors... 

### Reproducing Code Example

```python
import numpy as np
from scipy.sparse.linalg import LinearOperator, aslinearoperator
n = 5
M = np.diff(np.eye(n))
print(f"Matrix shape ", M.shape)
diff_matrix_aslo = aslinearoperator(M)
print(f"Matrix aslinearoperator shape ", diff_matrix_aslo.shape)
diff_func_aslo = LinearOperator(matvec=np.diff, matmat=np.diff, shape=(n - 1, n))
print(f"diff LinearOperator shape ", diff_func_aslo.shape)
LinearOperator(matvec=np.diff, matmat=np.diff, shape=(n, n - 1))
```

### Error message

```shell
Matrix shape  (5, 4)
Matrix aslinearoperator shape  (5, 4)
diff LinearOperator shape  (4, 5)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 521, in __init__
    self._init_dtype()
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 178, in _init_dtype
    self.dtype = np.asarray(self.matvec(v)).dtype
  File "C:\Users\uurun\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_interface.py", line 240, in matvec
    y = y.reshape(M)
ValueError: cannot reshape array of size 3 into shape (5,)
```

### SciPy/NumPy/Python version information

1.9.0 1.23.1 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by lobpcg** [comment]
I now suspect that there is simply a mistake in my arguments, so I close the issue.
