### ISSUE TITLE
Update `scipy/__config__.py` to contain useful information

### ISSUE THREAD

**Issue by KeepLost** [scipy/scipy#16803]
### Describe your issue.

Just as the title suggests, on Windows when the username contains a single quote, importing the scipy package would cause an error.

### Reproducing Code Example

```python
python -c "import scipy"
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Praxelogist's Lab\.conda\envs\losthub\lib\site-packages\scipy\__init__.py", line 134, in <module>
    from scipy.__config__ import show as show_config
  File "C:\Users\Praxelogist's Lab\.conda\envs\losthub\lib\site-packages\scipy\__config__.py", line 27
    lapack_info={'libraries': ['lapack', 'blas', 'lapack', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'language': 'f77'}
                                                                                                           ^
SyntaxError: invalid syntax
```

### SciPy/NumPy/Python version information

numpy==1.23.1  python==3.9.13  scipy==1.9.0

**Comment by KeepLost** [comment]
The reason behind the error is that in the `__config__.py` file, the file paths specified by the four dictionaries `blas_info`, `blas_opt_info`, `lapack_info`, and `lapack_opt_info` are hard-coded. Since the file path is represented as a string enclosed in single quotes, and the string itself contains a Windows username that also contains a single quote, it's unavoidable that the string would be broken, resulting in a syntax error, e.g.
```python
lapack_info={'libraries': ['lapack', 'blas', 'lapack', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'language': 'f77'}
blas_info={'libraries': ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include'], 'language': 'f77', 'define_macros': [('HAVE_CBLAS', None)]}
blas_opt_info={'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include'], 'language': 'f77'}
lapack_opt_info={'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\lib'], 'language': 'f77', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['C:/Users/Praxelogist's Lab/.conda/envs/losthub\\Library\\include']}
```

**Comment by rkern** [comment]
So, `scipy/__config__.py` is just a copy of the `numpy/__config__.py` from the `numpy` installation that was used during the building of `scipy`, so the core error is over there. AFAICT, the line responsible for generating this should use correctly-escaped strings:

https://github.com/numpy/numpy/blob/v1.23.1/numpy/distutils/misc_util.py#L2356

Given that the backslashes in that path are correctly escaped while the problematic part uses foreward slashes, I expect that the `conda` post-installation process is doing a regex search-and-replace to "rehome" the configuration to wherever the root of your `conda` installation is. So the error is in the `conda` packages' post-installation scripts, not `numpy` or `scipy`.

**Comment by rgommers** [comment]
The full implementation in `tools/config_utils.py` right now is:

```python
import sys
from pathlib import Path
import numpy as np
outfile = Path(sys.argv[1])

# This piece of code will just just copy the Numpy's `__config__.py` file,
# rather than write out SciPy's build-time config settings. This file should be
# generated by `config.make_config_py()` in `scipy/setup.py` which relies on an
# instance of `numpy.distutils.Configuration`. It cannot be accessed directly
# with a Meson build. This is a workaround for the same.
# For more details the implementation of this method is at https://github.com/numpy/numpy/blob/main/numpy/distutils/misc_util.py#L2113

outfile.write_text(Path(str(np.__config__.__file__)).read_text())
```

So let's repurpose this issue to a task to get rid of that and instead create a more useful `__config__.py`; what is there right now does not make much sense (and I think never has).

**Comment by rgommers** [comment]
I'm think that we store the output of the configure stage of the build in `__config__.py`, minus the known Cython-related warnings (`WARNING: custom_target '_cython_tree' has more than one output! `). That would look like:

```
Build started at 2022-10-17T18:06:33.672633
Main binary: /home/rgommers/mambaforge/envs/scipy-dev/bin/python3.10
Build Options: -Dprefix=/home/rgommers/code/scipy/build-install
Python system: Linux
The Meson build system
Version: 0.63.99
Source dir: /home/rgommers/code/scipy
Build dir: /home/rgommers/code/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.10.0.dev0
C compiler for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc (gcc 10.4.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 10.4.0-16) 10.4.0")
C linker for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.36.1
C++ compiler for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++ (gcc 10.4.0 "x86_64-conda-linux-gnu-c++ (conda-forge gcc 10.4.0-16) 10.4.0")
C++ linker for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Library m found: YES
Fortran compiler for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran (gcc 10.4.0 "GNU Fortran (conda-forge gcc 10.4.0-16) 10.4.0")
Fortran linker for the host machine: /home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran ld.bfd 2.36.1
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: YES 
Program cython found: YES (/home/rgommers/mambaforge/envs/scipy-dev/bin/cython)
Program pythran found: YES (/home/rgommers/mambaforge/envs/scipy-dev/bin/pythran)
Program cp found: YES (/usr/bin/cp)
Program python3 found: YES (/home/rgommers/mambaforge/envs/scipy-dev/bin/python3.10)
Found pkg-config: /home/rgommers/mambaforge/envs/scipy-dev/bin/pkg-config (0.29.2)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
Run-time dependency openblas found: YES 0.3.21
Dependency openblas found: YES 0.3.21 (cached)
Program _build_utils/cythoner.py found: YES (/home/rgommers/mambaforge/envs/scipy-dev/bin/python3.10 /home/rgommers/code/scipy/scipy/_build_utils/cythoner.py)
Compiler for C supports arguments -Wno-maybe-uninitialized: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers: YES 
Compiler for C supports arguments -Wno-empty-body: YES 
Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
Compiler for C supports arguments -Wno-parentheses: YES 
Compiler for C supports arguments -Wno-switch: YES 
Compiler for C supports arguments -Wno-unused-label: YES 
Compiler for C supports arguments -Wno-unused-variable: YES 
Compiler for C++ supports arguments -Wno-cpp: YES 
Compiler for C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for C++ supports arguments -Wno-class-memaccess: YES 
Compiler for C++ supports arguments -Wno-format-truncation: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-sign-compare: YES 
Compiler for C++ supports arguments -Wno-switch: YES 
Compiler for C++ supports arguments -Wno-terminate: YES 
Compiler for C++ supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C++ supports arguments -Wno-unused-function: YES 
Compiler for C++ supports arguments -Wno-unused-local-typedefs: YES 
Compiler for C++ supports arguments -Wno-unused-variable: YES 
Compiler for C++ supports arguments -Wno-int-in-bool-context: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES 
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-intrinsic-shadow: YES 
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-surprising: YES 
Compiler for Fortran supports arguments -Wno-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES 
Compiler for Fortran supports arguments -Wno-unused-label: YES 
Compiler for Fortran supports arguments -Wno-unused-variable: YES 
Compiler for Fortran supports arguments -Wno-tabs: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES (cached)
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-label: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-variable: YES (cached)
Compiler for Fortran supports arguments -Wno-tabs: YES (cached)
Checking for function "open_memstream" : NO 
Configuring messagestream_config.h using configuration
Compiler for Fortran supports arguments -w: YES 
Checking for size of "void*" : 8
Compiler for C supports arguments -Wno-unused-variable: YES (cached)
Compiler for C supports arguments -Wno-parentheses: YES (cached)
Compiler for C supports arguments -Wno-unused-label: YES (cached)
Compiler for C supports arguments -Wno-implicit-function-declaration: YES (cached)
Compiler for C supports arguments -Wno-switch: YES (cached)
Compiler for Fortran supports arguments -w: YES (cached)
Checking for size of "void*" : 8
Build targets in project: 206

SciPy 1.10.0.dev0

  User defined options
    prefix: /home/rgommers/code/scipy/build-install

Found ninja-1.11.0 at /home/rgommers/mambaforge/envs/scipy-dev/bin/ninja
Meson build setup OK
```

And that's a thing that `scipy.show_config()` can show. This will be helpful when interacting with folks who file build/install issues. It shows a number of things that we usually need to know and have a hard time getting info on:
- Any user-specified options in the install command
- Compilers used
- Which build dependencies were found, and what versions of them
- How Python was installed (typically obvious from the install location)
- OS and CPU type

One little complication is that that info that is printed to the terminal is not readily available in a separate log file The `build/meson-logs/meson-log.txt` file has more content that we don't necessarily want to store (too large and verbose). So the file needs parsing before storing this. Or am I missing an easier way @eli-schwartz?

The way to get at this content during the build is probably to move the `generate_config` custom target to the bottom of `scipy/meson.build` and invoke an updated Python script that does the parsing.

**Comment by eli-schwartz** [comment]
You can get the compilers with:

```meson
comp.get_id()
comp.get_linker_id()
comp.version()
comp.cmd_array()
```

You can get the OS and CPU type with:
```meson
host_machine.cpu()
host_machine.cpu_family()
```

For build dependencies, you can push them to an array when looking them up, then iterate over them and check:
```meson
dep.name()
dep.found()
dep.version()
```
For the found version of Python, I think the primary useful information shown in the debug log is the path, anyway, right? So,
```meson
py_installation.path()
```

By the way, you can also use
```meson
py_installation.get_path('xxx')
py_installation.get_variable('xxx')
```

to get arbitrary sysconfig paths and config_vars, respectively, from that found python installation.

The one thing missing here is user-specified `Build Options: xxx`. By coincidence, someone else has proposed the same feature at https://github.com/mesonbuild/meson/issues/10898 and there's a linked PR to implement it as well.

**Comment by eli-schwartz** [comment]
The generally official approach would then be to collect all this information using the meson methods I listed, stuff them all into a dict, and use that via `configure_file()`.

**Comment by rgommers** [comment]
That does sound like a much nicer way of doing things than parsing a text log, thanks @eli-schwartz.

@h-vetinari WDYT?

**Comment by h-vetinari** [comment]
> @h-vetinari WDYT?

Sounds exactly what I had been hoping for 🤩

**Comment by rgommers** [comment]
This is now in progress for NumPy: https://github.com/numpy/numpy/pull/22769. So probably best to finish it there, and then sync whatever comes out to SciPy.

**Comment by rgommers** [comment]
The NumPy PR is now merged @h-vetinari

**Comment by ganesh-k13** [comment]
Shall I do the same for SciPy?

**Comment by h-vetinari** [comment]
> Shall I do the same for SciPy?

I was planning to do it, but don't let that stop you. ;)

**Comment by rgommers** [comment]
This is addressed by gh-17862. Thanks all!
