### ISSUE TITLE
BUG: AttributeError: module 'scipy.stats' has no attribute 'fit'

### ISSUE THREAD

**Issue by zjgt** [scipy/scipy#17067]
### Describe your issue.

Hi, I'm simply getting started testing out scipy and encountered the following problems.
One, I was told stats has no attribute fit.
Second, I was not allowed to generate a random series.
I used conda to install scipy, the version is 1.7.0.
Thanks,
Sam

### Reproducing Code Example

```python
import numpy as np
from scipy import stats
rng = np.random.default_rng()
dist = stats.nbinom
shapes = (5, 0.5)
data = dist.rvs(*shapes, size=1000, random_state=rng)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sunengfu/opt/anaconda3/envs/p37ml/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2846, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/Users/opt/anaconda3/envs/p37ml/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 946, in rvs
    self._random_state = check_random_state(rndm)
  File "/Users/opt/anaconda3/envs/p37ml/lib/python3.7/site-packages/scipy/_lib/_util.py", line 190, in check_random_state
    ' instance' % seed)
ValueError: Generator(PCG64) at 0x7FCF884F3AA0 cannot be used to seed a numpy.random.RandomState instance

When I simply made up a data series, it encountered another problem.
>>> res = stats.fit(dist, data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy.stats' has no attribute 'fit'
```

### Error message

```shell
Two error message:
1) ValueError: Generator(PCG64) at 0x7FCF884F3AA0 cannot be used to seed a numpy.random.RandomState instance

2) AttributeError: module 'scipy.stats' has no attribute 'fit'
```

### SciPy/NumPy/Python version information

1.7.0

**Comment by zjgt** [comment]
Thanks, it worked after updating.
