### ISSUE TITLE
BUG: possible issue in basinhopping.py print_report() (self.energy = energy_trial = minres.fun)

### ISSUE THREAD

**Issue by nbfazel** [scipy/scipy#17133]
### Describe your issue.

My understanding is that in basinhopping.py, **lowest_f** represents the current global minimum, **f** represents the value of the function at the current step, and **trial_f** is the value of the function following the next global step (which may or may not be accepted). I frequently get the same values for f, trial_f, and lowest_f, which is surprising since the value of the function before and after taking a step is expected to change:
```
basinhopping step 91: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 92: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 93: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 94: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 95: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 96: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 97: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 98: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
basinhopping step 99: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06
adaptive stepsize: acceptance rate 0.940000 target 0.500000 new stepsize 0.617284 old stepsize 0.555556
basinhopping step 100: f 2.38367e+06 trial_f 2.38367e+06 accepted 1  lowest_f 2.38367e+06```

In print_report(), this could indicate that self.energy = energy_trial = minres.fun:
```
    def print_report(self, energy_trial, accept):
        """print a status update"""
        minres = self.storage.get_lowest()
        print("basinhopping step %d: f %g trial_f %g accepted %d "
              " lowest_f %g" % (self.nstep, self.energy, energy_trial,
                                accept, minres.fun))
```
It may be that they are different but the difference is small and the precision of the reporting needs to be increased. 

### Reproducing Code Example

```python
parameters = (contour, self.default_spectrum)
x0 = [0] * self.num_detectors[contour]

minimizer_args = {"args": parameters, "method": "L-BFGS-B", "jac": True, "options": {'disp': False}}

OptimizeResult = optimize.basinhopping(self.optimize_func, x0, minimizer_kwargs=minimizer_args, disp=True)
```

### Error message

```shell
none
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by nbfazel** [comment]
Please let me know if additional information would help.

**Comment by mdhaber** [comment]
Can you provide code that we can run to replicate the problem?

**Comment by nbfazel** [comment]
Thanks, Matt. I will try to provide code to replicate the problem. (The program reads a lot of input in order to construct the multi-variable function to minimize and I need to think about how to do it.)

Your suggestions on how to move forward (in the 3 bullet points above) make sense to me. Do I need to do anything on my end?

**Comment by mdhaber** [comment]
> Do I need to do anything on my end?

Well, you're welcome to submit a PR : )  Would you like to do that?

**Comment by nbfazel** [comment]
Thanks. Is PR a request for enhancement? If so, I will do that.

**Comment by mdhaber** [comment]
PR means "pull request", you submit code that you request get pulled (merged) into SciPy. You can find more information in the contributor [guide](https://docs.scipy.org/doc/scipy/dev/index.html)

**Comment by mdhaber** [comment]
@nbfazel Did you plan to submit a pull request for this? SciPy 1.10 will branch in early December, so if you'd like to see this feature in the next version of SciPy, it would need to happen soon.

**Comment by nbfazel** [comment]
Thanks for the reminder. This fell off my radar. I will work on it when I return to the US late next week.

**Comment by nbfazel** [comment]
Sorry, I've been trying to build SciPy (using info from here: https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html), but got stuck on gfortran errors when building SciPy. I'm using Conda (it's up-to-date), and gfortran come with it. Not sure why the the gfortran compiler is unhappy:

(scipy-dev) fnal@neilfazelsmacbook[scipy][3]> python dev.py build
💻  meson setup /Users/fnal/.ssh/scipy/build --prefix /Users/fnal/.ssh/scipy/build-install
The Meson build system
Version: 0.64.1
<snip>
meson.build:63:0: ERROR: Compiler /Users/fnal/opt/anaconda3/envs/scipy-dev/bin/x86_64-apple-darwin13.4.0-gfortran can not compile programs.

A full log can be found at /Users/fnal/.ssh/scipy/build/meson-logs/meson-log.txt
Meson build setup failed!
[meson-log.txt](https://github.com/scipy/scipy/files/10326010/meson-log.txt)

**Comment by j-bowhay** [comment]
> Sorry, I've been trying to build SciPy (following the steps from here: https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html), but got stuck on gfortran errors when building SciPy. I'm using Conda (it's up-to-date), and gfortran come with it. Not sure why the gfortran compiler is unhappy:
> 
> ```
> (scipy-dev) fnal@neilfazelsmacbook[scipy][3]> python dev.py build
> 💻  meson setup /Users/fnal/.ssh/scipy/build --prefix /Users/fnal/.ssh/scipy/build-install
> The Meson build system
> Version: 0.64.1
> <snip>
> meson.build:63:0: ERROR: Compiler /Users/fnal/opt/anaconda3/envs/scipy-dev/bin/x86_64-apple-darwin13.4.0-gfortran can not compile programs.
> 
> A full log can be found at /Users/fnal/.ssh/scipy/build/meson-logs/meson-log.txt
> Meson build setup failed!
> ```
> 
> [meson-log.txt](https://github.com/scipy/scipy/files/10326010/meson-log.txt)

Try posting on the slack group scipy-community.slack.com

**Comment by andyfaff** [comment]
Something is going wrong with the compiler toolchain you are using. If I had to hazard a guess I'd say that one or more of the compilers is too old for the macOS version you are using (what is that?) because of the following:

> x86_64-apple-darwin13.4.0-gfortran: warning: could not understand version 13.01.00

I'm guessing you're on Ventura 13.01, but that the compilers have a upper version limit that they can compile for, hence the error message.
You may also be getting conflicts between the system build chain (from xcode) and from the compilers installed into the conda env.

 I'm on macOS 13.01 (arm64) and use the system command line tools installed via Xcode. I then install gfortran from https://github.com/fxcoudert/gfortran-for-macOS/releases, making sure to select the correct architecture. If you're reluctant to use those gfortran builds you could try gfortran from homebrew. I build in a conda env with conda-forge supplied Python and a pip installed numpy/cython/pybind11/pythran (but no conda installed compilers)

**Comment by nbfazel** [comment]
Thanks for the information. Your guess makes sense. (I'm on Ventura 13.1.)

**Comment by nbfazel** [comment]
I installed gfortran 12.2 for Ventura (macOS 13) for Apple Silicon computers from the link you provided. (I'm using Xcode.) Then tried to build again and got the same error. This was in scipy-dev environment. Then I tried the base environment but that one produced different errors:

```
(scipy-dev) fnal@neilfazelsmacbook[scipy][15]> conda deactivate 
(base) fnal@neilfazelsmacbook[scipy][16]> python dev.py build
Traceback (most recent call last):
  File "/Users/fnal/.ssh/scipy/dev.py", line 126, in <module>
    from doit import task_params
ModuleNotFoundError: No module named 'doit'
(base) fnal@neilfazelsmacbook[scipy][17]> 
```

**Comment by andyfaff** [comment]
You need to pip install the `doit` package to get past that.

**Comment by nbfazel** [comment]
Thanks. I installed that, and needed to also install pydevtool and rich_click. The last one gave an error:

```
(base) fnal@neilfazelsmacbook[scipy][7]> pip install rich_click
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.
This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 requires pyqt5<5.13, which is not installed.
spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.

Successfully installed markdown-it-py-2.1.0 mdurl-0.1.2 pygments-2.14.0 rich-13.3.1 rich_click-1.6.1
```

Despite the error, rich_click appeared to install successfully, so I then tried to build SciPy:

```
(base) fnal@neilfazelsmacbook[scipy][9]> python dev.py build
💻  meson setup /Users/fnal/.ssh/scipy/build --prefix /Users/fnal/.ssh/scipy/build-install
Task Error - build => PythonAction Error
╭───────────────────────────────────────────────────── build ──────────────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                               │
│   File "/Users/fnal/opt/anaconda3/lib/python3.9/site-packages/doit/action.py", line 461, in execute              │
│     returned_value = self.py_callable(*self.args, **kwargs)                                                      │
│   File "/Users/fnal/.ssh/scipy/dev.py", line 607, in run                                                         │
│     env = cls.setup_build(dirs, args)                                                                            │
│   File "/Users/fnal/.ssh/scipy/dev.py", line 465, in setup_build                                                 │
│     ret = subprocess.call(cmd, env=env, cwd=run_dir)                                                             │
│   File "/Users/fnal/opt/anaconda3/lib/python3.9/subprocess.py", line 349, in call                                │
│     with Popen(*popenargs, **kwargs) as p:                                                                       │
│   File "/Users/fnal/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__                            │
│     self._execute_child(args, executable, preexec_fn, close_fds,                                                 │
│   File "/Users/fnal/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child                     │
│     raise child_exception_type(errno_num, err_msg, err_filename)                                                 │
│ FileNotFoundError: [Errno 2] No such file or directory: 'meson'                                                  │
│                                                                                                                  │
╰─────────────────────────────────────────────── PythonAction Error ───────────────────────────────────────────────╯
```
I don't seem to be set up to do development work in SciPy. It would help if print_report() could be improved to display using more significant digits.

**Comment by nbfazel** [comment]
I realized meson was missing and installed it

```
(base) fnal@neilfazelsmacbook[scipy][28]> conda install -c conda-forge meson
```
Then tried again to build SciPy:
```
(base) fnal@neilfazelsmacbook[scipy][45]> python dev.py build
...
meson.build:63:0: ERROR: Compiler gfortran can not compile programs.

A full log can be found at /Users/fnal/.ssh/scipy/build/meson-logs/meson-log.txt
Meson build setup failed!
```
Not sure why gfortran cannot compile. (I also updated Xcode.)
