### ISSUE TITLE
BUG: scipy.linalg.expm, coshm, sinhm and tanhm fail for read-only inputs

### ISSUE THREAD

**Issue by misho88** [scipy/scipy#17172]
### Describe your issue.

scipy.linalg.expm, coshm, sinhm and tanhm fail for read-only inputs

Error only appears if input is 3x3 or larger.

Possibly other functions fail, too, but the trigonometric and fractional_matrix_power functions seem fine, so not all.

### Reproducing Code Example

```python
from numpy import eye
from scipy.linalg import expm  # or coshm, sinhm, tanhm
i = eye(3)
i.flags.writeable = False
expm(i)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 335, in expm
    lu = bandwidth(aw)
  File "_cythonized_array_utils.pyx", line 104, in scipy.linalg._cythonized_array_utils.bandwidth
  File "_cythonized_array_utils.pyx", line 114, in scipy.linalg._cythonized_array_utils.bandwidth_c
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
I suspect this is the same issue with Cython code as seen in https://github.com/scipy/scipy/issues/12905.  It would seem the solution is to sprinkle `const` qualifiers throughout the Cython code as needed, but there is a Cython bug in the way: https://github.com/cython/cython/issues/3783

**Comment by steppi** [comment]
I tried adding the needed `const`s since https://github.com/cython/cython/pull/5076 went in, but ran into https://github.com/cython/cython/issues/5230, so this is still blocked by a different Cython bug.

**Comment by ilayn** [comment]
With Cython 3.0 this should have been fixed if I understood correctly. The const qualifiers need to go into bandwidth in `_cythonized_array_utils` if a few lines here and there

**Comment by steppi** [comment]
> With Cython 3.0 this should have been fixed if I understood correctly. The const qualifiers need to go into bandwidth in `_cythonized_array_utils` in a few lines here and there

Yeah, I thought so too, and that solution was actually backported into 0.29.X. The problem is that it still doesn't work for `def` functions. See https://github.com/cython/cython/issues/5230. There's a PR to fix it, https://github.com/cython/cython/pull/5233, but it's been languishing since January
