### ISSUE TITLE
BUG: SciPy use of NumPy API version on Windows and Python 3.10

### ISSUE THREAD

**Issue by bashtage** [scipy/scipy#17197]
### Describe your issue.

I have recently started seeing

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

on CI when scipy is imported.  Our NumPy is 1.21.6, which comes from oldest-supported-numpy 2022.8.16. We build against this NumPy and then try and test against it. 

### Reproducing Code Example

```python
Haven't been able to locally reproduce, but can always reproduce on clean Azure CI Windows and Python 3.10
```

### Error message

```shell
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\_pytest\config\__init__.py", line 1642, in parse_warning_filter
    category: Type[Warning] = _resolve_warning_category(category_)
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\_pytest\config\__init__.py", line 1680, in _resolve_warning_category
    m = __import__(module, None, None, [klass])
  File "D:\a\1\s\statsmodels\tools\__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "D:\a\1\s\statsmodels\tools\tools.py", line 6, in <module>
    import scipy.linalg
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\scipy\linalg\__init__.py", line 197, in <module>
    from ._misc import *
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\scipy\linalg\_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\scipy\linalg\blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: numpy.core.multiarray failed to import
```
```


### SciPy/NumPy/Python version information

scipy: 1.9.2, numpy: 1.21.6

**Comment by rgommers** [comment]
Thanks for the report @bashtage. This is because of https://github.com/scipy/scipy/blob/fdf3c0e3a5fdd7c2cd9b91ae53e366c7447d26f2/pyproject.toml#L38-L41

From `oldest-supported-numpy` we have: https://github.com/scipy/oldest-supported-numpy/blob/7c61f628ef4e10a6954d65f1ea317a85d31eac0c/setup.cfg#L57-L59

Also relevant: https://github.com/scipy/oldest-supported-numpy/pull/44#issuecomment-1207190697

This is quite annoying to align. The easiest fix is to get the runtime dependency in the SciPy wheels on NumPy correct. Right now it simply says `>=1.19.5`: https://github.com/scipy/scipy/blob/fdf3c0e3a5fdd7c2cd9b91ae53e366c7447d26f2/pyproject.toml#L73-L77. That's the same metadata bug that the `distutils` build has always had. Packaging tooling doesn't give us a good way of getting this right automatically. The correct fix is to implement https://github.com/FFY00/meson-python/issues/29. 

We could also manually updating the metadata in the SciPy wheels in the meantime, but I'm not enthusiastic about doing that. @bashtage can you just bump the test dependency to NumPy 1.22?

**Comment by j-bowhay** [comment]
Can we close this now since there doesn't seem like there's anything to do here?

**Comment by rgommers** [comment]
Yep, this is quite outdated.
