### ISSUE TITLE
BUG: 1.9.2 Download failed on requirement to build wheel

### ISSUE THREAD

**Issue by nualapennycook** [scipy/scipy#17202]
### Describe your issue.

Failed to download scipy version 1.9.2 with error shown below, but download of 1.9.1 was successful with no other changes.

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
Collecting scipy
  Using cached scipy-1.9.2.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      The Meson build system
      Version: 0.63.3
      Source dir: C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135
      Build dir: C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135\.mesonpy-bbbo_wf9\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.2
      C compiler for the host machine: cc (gcc 7.2.0 "cc (Rev1, Built by MSYS2 project) 7.2.0")
      C linker for the host machine: cc ld.bfd 2.29.1
      C++ compiler for the host machine: c++ (gcc 7.2.0 "c++ (Rev1, Built by MSYS2 project) 7.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.29.1
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES

      ..\..\meson.build:49:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135\.mesonpy-bbbo_wf9\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\Nuala\AppData\Local\Programs\Python\Python39-32 C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135 C:\Users\Nuala\AppData\Local\Temp\pip-install-egqriuyh\scipy_5d92559bae454a638f7586d0433c9135\.mesonpy-bbbo_wf9\build
      Traceback (most recent call last):
        File "C:\Users\Nuala\Python Projects\PythonEnvironments\mlpaper_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\Nuala\Python Projects\PythonEnvironments\mlpaper_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Nuala\Python Projects\PythonEnvironments\mlpaper_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\Nuala\AppData\Local\Programs\Python\Python39-32\lib\contextlib.py", line 119, in __enter__
          return next(self.gen)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\Nuala\AppData\Local\Programs\Python\Python39-32\lib\contextlib.py", line 119, in __enter__
          return next(self.gen)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 713, in _configure
          self._meson(
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "C:\Users\Nuala\AppData\Local\Temp\pip-build-env-v2hc239m\overlay\Lib\site-packages\mesonpy\__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "C:\Users\Nuala\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\Nuala\\AppData\\Local\\Temp\\pip-install-egqriuyh\\scipy_5d92559bae454a638f7586d0433c9135\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\Nuala\\AppData\\Local\\Programs\\Python\\Python39-32', 'C:\\Users\\Nuala\\AppData\\Local\\Temp\\pip-install-egqriuyh\\scipy_5d92559bae454a638f7586d0433c9135', 'C:\\Users\\Nuala\\AppData\\Local\\Temp\\pip-install-egqriuyh\\scipy_5d92559bae454a638f7586d0433c9135\\.mesonpy-bbbo_wf9\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
Does `pip install --prefer-binary` work just fine?

Any chance you're on 32-bit Windows? I believe `1.9.2` drops 32-bit Windows wheel/binaries on PyPI, at least for now, because we switched to `cibuildwheel` + `meson`, and that new toolchain may not be quite ready for 32-bit Windows.

There are also a bunch of discussion threads about the need to continue providing 32-bit Windows binaries (if that's your use case, maybe best to look for those discussions and chime in).

**Comment by nualapennycook** [comment]
@tylerjereddy thanks for your response. Yeah I am on 32-bit Python on Windows. I've tried adding the prefer binary flag, but I am still getting the same error when I try to install it. If I switch to 64-bit Python might the issue go away?

**Comment by tylerjereddy** [comment]
That's a bit weird, maybe `--only-binary` would be sufficiently strict. I would hope the problem goes away with 64-bit since we did release `1.9.2` binaries on that arch.

**Comment by nualapennycook** [comment]
@tylerjereddy just tried the only binary flag and no luck! Not sure if I used the correct argument though.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/114914831/195190122-1d435ab3-1c3d-4a7a-b06e-08d0b869b6ac.png">

**Comment by andyfaff** [comment]
There are no windows 32-bit wheels for 1.9.2. I think Tyler was suggesting `pip install scipy --only-binary=:all:`. If you transition to 64-bit Python you shouldn't have a problem upgrading to 1.9.2

**Comment by nualapennycook** [comment]
@andyfaff thanks, I've just unistalled scipy and I reinstalled with no issues using `pip install scipy --only-binary=:all:` so that works.

**Comment by andyfaff** [comment]
Good.
