### ISSUE TITLE
BUG: failing scipy tests on i686 architecture

### ISSUE THREAD

**Issue by psimovec** [scipy/scipy#17213]
### Describe your issue.

I want to make latest scipy version 1.9.2 available on Fedora, but 5 tests are failing specifically on i686 architecture.
There were the same tests fails on 1.9.1, and no such fails on 1.8.1.

build.log in case I missed any important information: https://kojipkgs.fedoraproject.org//work/tasks/1373/92881373/build.log

### Reproducing Code Example

```python
=========================== short test summary info ============================
FAILED scipy/sparse/linalg/tests/test_propack.py::test_examples[False-double]
FAILED scipy/sparse/linalg/tests/test_propack.py::test_examples[True-single]
FAILED scipy/sparse/tests/test_base.py::TestCSR::test_fancy_assignment_dtypes
FAILED scipy/interpolate/tests/test_rbfinterp.py::TestRBFInterpolatorNeighborsNone::test_chunking
FAILED scipy/interpolate/tests/test_rbfinterp.py::TestRBFInterpolatorNeighborsInf::test_chunking
```

### Error message

```shell
=================================== FAILURES ===================================
_________________________ test_examples[False-double] __________________________
[gw1] linux -- Python 3.11.0 /usr/bin/python3
precision = 'double', irl = False
    @pytest.mark.parametrize('precision', _dtype_testing)
    @pytest.mark.parametrize('irl', (False, True))
    def test_examples(precision, irl):
        # Note: atol for complex8 bumped from 1e-4 to 1e-3 because of test failures
        # with BLIS, Netlib, and MKL+AVX512 - see
        # https://github.com/conda-forge/scipy-feedstock/pull/198#issuecomment-999180432
        atol = {
            'single': 1.3e-4,
            'double': 1e-9,
            'complex8': 1e-3,
            'complex16': 1e-9,
        }[precision]
    
        path_prefix = os.path.dirname(__file__)
        # Test matrices from `illc1850.coord` and `mhd1280b.cua` distributed with
        # PROPACK 2.1: http://sun.stanford.edu/~rmunk/PROPACK/
        relative_path = "propack_test_data.npz"
        filename = os.path.join(path_prefix, relative_path)
        data = np.load(filename, allow_pickle=True)
    
        dtype = _dtype_map[precision]
        if precision in {'single', 'double'}:
            A = data['A_real'].item().astype(dtype)
        elif precision in {'complex8', 'complex16'}:
            A = data['A_complex'].item().astype(dtype)
    
        k = 200
        u, s, vh, _ = _svdp(A, k, irl_mode=irl, random_state=0)
    
        # complex example matrix has many repeated singular values, so check only
        # beginning non-repeated singular vectors to avoid permutations
        sv_check = 27 if precision in {'complex8', 'complex16'} else k
        u = u[:, :sv_check]
        vh = vh[:sv_check, :]
        s = s[:sv_check]
    
        # Check orthogonality of singular vectors
        assert_allclose(np.eye(u.shape[1]), u.conj().T @ u, atol=atol)
        assert_allclose(np.eye(vh.shape[0]), vh @ vh.conj().T, atol=atol)
    
        # Ensure the norm of the difference between the np.linalg.svd and
        # PROPACK reconstructed matrices is small
        u3, s3, vh3 = np.linalg.svd(A.todense())
        u3 = u3[:, :sv_check]
        s3 = s3[:sv_check]
        vh3 = vh3[:sv_check, :]
        A3 = u3 @ np.diag(s3) @ vh3
        recon = u @ np.diag(s) @ vh
>       assert_allclose(np.linalg.norm(A3 - recon), 0, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-09
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 1.84554848
E       Max relative difference: inf
E        x: array(1.845548)
E        y: array(0)
scipy/sparse/linalg/tests/test_propack.py:166: AssertionError
__________________________ test_examples[True-single] __________________________
[gw1] linux -- Python 3.11.0 /usr/bin/python3
precision = 'single', irl = True
    @pytest.mark.parametrize('precision', _dtype_testing)
    @pytest.mark.parametrize('irl', (False, True))
    def test_examples(precision, irl):
        # Note: atol for complex8 bumped from 1e-4 to 1e-3 because of test failures
        # with BLIS, Netlib, and MKL+AVX512 - see
        # https://github.com/conda-forge/scipy-feedstock/pull/198#issuecomment-999180432
        atol = {
            'single': 1.3e-4,
            'double': 1e-9,
            'complex8': 1e-3,
            'complex16': 1e-9,
        }[precision]
    
        path_prefix = os.path.dirname(__file__)
        # Test matrices from `illc1850.coord` and `mhd1280b.cua` distributed with
        # PROPACK 2.1: http://sun.stanford.edu/~rmunk/PROPACK/
        relative_path = "propack_test_data.npz"
        filename = os.path.join(path_prefix, relative_path)
        data = np.load(filename, allow_pickle=True)
    
        dtype = _dtype_map[precision]
        if precision in {'single', 'double'}:
            A = data['A_real'].item().astype(dtype)
        elif precision in {'complex8', 'complex16'}:
            A = data['A_complex'].item().astype(dtype)
    
        k = 200
        u, s, vh, _ = _svdp(A, k, irl_mode=irl, random_state=0)
    
        # complex example matrix has many repeated singular values, so check only
        # beginning non-repeated singular vectors to avoid permutations
        sv_check = 27 if precision in {'complex8', 'complex16'} else k
        u = u[:, :sv_check]
        vh = vh[:sv_check, :]
        s = s[:sv_check]
    
        # Check orthogonality of singular vectors
        assert_allclose(np.eye(u.shape[1]), u.conj().T @ u, atol=atol)
        assert_allclose(np.eye(vh.shape[0]), vh @ vh.conj().T, atol=atol)
    
        # Ensure the norm of the difference between the np.linalg.svd and
        # PROPACK reconstructed matrices is small
        u3, s3, vh3 = np.linalg.svd(A.todense())
        u3 = u3[:, :sv_check]
        s3 = s3[:sv_check]
        vh3 = vh3[:sv_check, :]
        A3 = u3 @ np.diag(s3) @ vh3
        recon = u @ np.diag(s) @ vh
>       assert_allclose(np.linalg.norm(A3 - recon), 0, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0.00013
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 1.84415603
E       Max relative difference: inf
E        x: array(1.844156, dtype=float32)
E        y: array(0)
scipy/sparse/linalg/tests/test_propack.py:166: AssertionError
_____________________ TestCSR.test_fancy_assignment_dtypes _____________________
[gw1] linux -- Python 3.11.0 /usr/bin/python3
actual = (nan+nanj), desired = (2+0j), err_msg = '', verbose = True
    def assert_equal(actual, desired, err_msg='', verbose=True):
        """
        Raises an AssertionError if two objects are not equal.
    
        Given two objects (scalars, lists, tuples, dictionaries or numpy arrays),
        check that all elements of these objects are equal. An exception is raised
        at the first conflicting values.
    
        When one of `actual` and `desired` is a scalar and the other is array_like,
        the function checks that each element of the array_like object is equal to
        the scalar.
    
        This function handles NaN comparisons as if NaN was a "normal" number.
        That is, AssertionError is not raised if both objects have NaNs in the same
        positions.  This is in contrast to the IEEE standard on NaNs, which says
        that NaN compared to anything must return False.
    
        Parameters
        ----------
        actual : array_like
            The object to check.
        desired : array_like
            The expected object.
        err_msg : str, optional
            The error message to be printed in case of failure.
        verbose : bool, optional
            If True, the conflicting values are appended to the error message.
    
        Raises
        ------
        AssertionError
            If actual and desired are not equal.
    
        Examples
        --------
        >>> np.testing.assert_equal([4,5], [4,6])
        Traceback (most recent call last):
            ...
        AssertionError:
        Items are not equal:
        item=1
         ACTUAL: 5
         DESIRED: 6
    
        The following comparison does not raise an exception.  There are NaNs
        in the inputs, but they are in the same positions.
    
        >>> np.testing.assert_equal(np.array([1.0, 2.0, np.nan]), [1, 2, np.nan])
    
        """
        __tracebackhide__ = True  # Hide traceback for py.test
        if isinstance(desired, dict):
            if not isinstance(actual, dict):
                raise AssertionError(repr(type(actual)))
            assert_equal(len(actual), len(desired), err_msg, verbose)
            for k, i in desired.items():
                if k not in actual:
                    raise AssertionError(repr(k))
                assert_equal(actual[k], desired[k], f'key={k!r}\n{err_msg}',
                             verbose)
            return
        if isinstance(desired, (list, tuple)) and isinstance(actual, (list, tuple)):
            assert_equal(len(actual), len(desired), err_msg, verbose)
            for k in range(len(desired)):
                assert_equal(actual[k], desired[k], f'item={k!r}\n{err_msg}',
                             verbose)
            return
        from numpy.core import ndarray, isscalar, signbit
        from numpy.lib import iscomplexobj, real, imag
        if isinstance(actual, ndarray) or isinstance(desired, ndarray):
            return assert_array_equal(actual, desired, err_msg, verbose)
        msg = build_err_msg([actual, desired], err_msg, verbose=verbose)
    
        # Handle complex numbers: separate into real/imag to handle
        # nan/inf/negative zero correctly
        # XXX: catch ValueError for subclasses of ndarray where iscomplex fail
        try:
            usecomplex = iscomplexobj(actual) or iscomplexobj(desired)
        except (ValueError, TypeError):
            usecomplex = False
    
        if usecomplex:
            if iscomplexobj(actual):
                actualr = real(actual)
                actuali = imag(actual)
            else:
                actualr = actual
                actuali = 0
            if iscomplexobj(desired):
                desiredr = real(desired)
                desiredi = imag(desired)
            else:
                desiredr = desired
                desiredi = 0
            try:
>               assert_equal(actualr, desiredr)
/usr/lib/python3.11/site-packages/numpy/testing/_private/utils.py:370: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
actual = nan, desired = 2.0, err_msg = '', verbose = True
    def assert_equal(actual, desired, err_msg='', verbose=True):
        """
        Raises an AssertionError if two objects are not equal.
    
        Given two objects (scalars, lists, tuples, dictionaries or numpy arrays),
        check that all elements of these objects are equal. An exception is raised
        at the first conflicting values.
    
        When one of `actual` and `desired` is a scalar and the other is array_like,
        the function checks that each element of the array_like object is equal to
        the scalar.
    
        This function handles NaN comparisons as if NaN was a "normal" number.
        That is, AssertionError is not raised if both objects have NaNs in the same
        positions.  This is in contrast to the IEEE standard on NaNs, which says
        that NaN compared to anything must return False.
    
        Parameters
        ----------
        actual : array_like
            The object to check.
        desired : array_like
            The expected object.
        err_msg : str, optional
            The error message to be printed in case of failure.
        verbose : bool, optional
            If True, the conflicting values are appended to the error message.
    
        Raises
        ------
        AssertionError
            If actual and desired are not equal.
    
        Examples
        --------
        >>> np.testing.assert_equal([4,5], [4,6])
        Traceback (most recent call last):
            ...
        AssertionError:
        Items are not equal:
        item=1
         ACTUAL: 5
         DESIRED: 6
    
        The following comparison does not raise an exception.  There are NaNs
        in the inputs, but they are in the same positions.
    
        >>> np.testing.assert_equal(np.array([1.0, 2.0, np.nan]), [1, 2, np.nan])
    
        """
        __tracebackhide__ = True  # Hide traceback for py.test
        if isinstance(desired, dict):
            if not isinstance(actual, dict):
                raise AssertionError(repr(type(actual)))
            assert_equal(len(actual), len(desired), err_msg, verbose)
            for k, i in desired.items():
                if k not in actual:
                    raise AssertionError(repr(k))
                assert_equal(actual[k], desired[k], f'key={k!r}\n{err_msg}',
                             verbose)
            return
        if isinstance(desired, (list, tuple)) and isinstance(actual, (list, tuple)):
            assert_equal(len(actual), len(desired), err_msg, verbose)
            for k in range(len(desired)):
                assert_equal(actual[k], desired[k], f'item={k!r}\n{err_msg}',
                             verbose)
            return
        from numpy.core import ndarray, isscalar, signbit
        from numpy.lib import iscomplexobj, real, imag
        if isinstance(actual, ndarray) or isinstance(desired, ndarray):
            return assert_array_equal(actual, desired, err_msg, verbose)
        msg = build_err_msg([actual, desired], err_msg, verbose=verbose)
    
        # Handle complex numbers: separate into real/imag to handle
        # nan/inf/negative zero correctly
        # XXX: catch ValueError for subclasses of ndarray where iscomplex fail
        try:
            usecomplex = iscomplexobj(actual) or iscomplexobj(desired)
        except (ValueError, TypeError):
            usecomplex = False
    
        if usecomplex:
            if iscomplexobj(actual):
                actualr = real(actual)
                actuali = imag(actual)
            else:
                actualr = actual
                actuali = 0
            if iscomplexobj(desired):
                desiredr = real(desired)
                desiredi = imag(desired)
            else:
                desiredr = desired
                desiredi = 0
            try:
                assert_equal(actualr, desiredr)
                assert_equal(actuali, desiredi)
            except AssertionError:
                raise AssertionError(msg)
    
        # isscalar test to check cases such as [np.nan] != np.nan
        if isscalar(desired) != isscalar(actual):
            raise AssertionError(msg)
    
        try:
            isdesnat = isnat(desired)
            isactnat = isnat(actual)
            dtypes_match = (np.asarray(desired).dtype.type ==
                            np.asarray(actual).dtype.type)
            if isdesnat and isactnat:
                # If both are NaT (and have the same dtype -- datetime or
                # timedelta) they are considered equal.
                if dtypes_match:
                    return
                else:
                    raise AssertionError(msg)
    
        except (TypeError, ValueError, NotImplementedError):
            pass
    
        # Inf/nan/negative zero handling
        try:
            isdesnan = gisnan(desired)
            isactnan = gisnan(actual)
            if isdesnan and isactnan:
                return  # both nan, so equal
    
            # handle signed zero specially for floats
            array_actual = np.asarray(actual)
            array_desired = np.asarray(desired)
            if (array_actual.dtype.char in 'Mm' or
                    array_desired.dtype.char in 'Mm'):
                # version 1.18
                # until this version, gisnan failed for datetime64 and timedelta64.
                # Now it succeeds but comparison to scalar with a different type
                # emits a DeprecationWarning.
                # Avoid that by skipping the next check
                raise NotImplementedError('cannot compare to a scalar '
                                          'with a different type')
    
            if desired == 0 and actual == 0:
                if not signbit(desired) == signbit(actual):
                    raise AssertionError(msg)
    
        except (TypeError, ValueError, NotImplementedError):
            pass
    
        try:
            # Explicitly use __eq__ for comparison, gh-2552
            if not (desired == actual):
>               raise AssertionError(msg)
E               AssertionError: 
E               Items are not equal:
E                ACTUAL: nan
E                DESIRED: 2.0
/usr/lib/python3.11/site-packages/numpy/testing/_private/utils.py:425: AssertionError
During handling of the above exception, another exception occurred:
self = <scipy.sparse.tests.test_base.TestCSR object at 0xed1c3710>
    def test_fancy_assignment_dtypes(self):
        def check(dtype):
            A = self.spmatrix((5, 5), dtype=dtype)
            with suppress_warnings() as sup:
                sup.filter(SparseEfficiencyWarning,
                           "Changing the sparsity structure of a cs[cr]_matrix is expensive")
                A[[0,1],[0,1]] = dtype.type(1)
                assert_equal(A.sum(), dtype.type(1)*2)
                A[0:2,0:2] = dtype.type(1.0)
                assert_equal(A.sum(), dtype.type(1)*4)
                A[2,2] = dtype.type(1.0)
                assert_equal(A.sum(), dtype.type(1)*4 + dtype.type(1))
    
        for dtype in supported_dtypes:
>           check(np.dtype(dtype))
scipy/sparse/tests/test_base.py:3006: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dtype = dtype('complex192')
    def check(dtype):
        A = self.spmatrix((5, 5), dtype=dtype)
        with suppress_warnings() as sup:
            sup.filter(SparseEfficiencyWarning,
                       "Changing the sparsity structure of a cs[cr]_matrix is expensive")
            A[[0,1],[0,1]] = dtype.type(1)
>           assert_equal(A.sum(), dtype.type(1)*2)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: (nan+nanj)
E            DESIRED: (2+0j)
scipy/sparse/tests/test_base.py:2999: AssertionError
________________ TestRBFInterpolatorNeighborsNone.test_chunking ________________
[gw3] linux -- Python 3.11.0 /usr/bin/python3
self = <scipy.interpolate.tests.test_rbfinterp.TestRBFInterpolatorNeighborsNone object at 0xf0cd2630>
    @pytest.mark.slow
    def test_chunking(self):
        # If the observed data comes from a polynomial, then the interpolant
        # should be able to reproduce the polynomial exactly, provided that
        # `degree` is sufficiently high.
        rng = np.random.RandomState(0)
        seq = Halton(2, scramble=False, seed=rng)
        degree = 3
    
        largeN = 1000000 + 33
        # this is large to check that chunking of the RBFInterpolator is tested
        x = seq.random(50)
        xitp = seq.random(largeN)
    
        P = _vandermonde(x, degree)
        Pitp = _vandermonde(xitp, degree)
    
        poly_coeffs = rng.normal(0.0, 1.0, P.shape[1])
    
        y = P.dot(poly_coeffs)
        yitp1 = Pitp.dot(poly_coeffs)
>       yitp2 = self.build(x, y, degree=degree)(xitp)
scipy/interpolate/tests/test_rbfinterp.py:178: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scipy/interpolate/_rbfinterp.py:490: in __call__
    out = self._chunk_evaluator(
scipy/interpolate/_rbfinterp.py:438: in _chunk_evaluator
    vec = _build_evaluation_coefficients(
scipy/interpolate/_rbfinterp_pythran.py:213: in _build_evaluation_coefficients
    polynomial_vector(xhat[i], powers, vec[i, p:])
scipy/interpolate/_rbfinterp_pythran.py:60: in polynomial_vector
    out[i] = np.prod(x**powers[i])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = (array([0.00600092, 1.        ]),), kwargs = {}
>   ???
E   Failed: Timeout >500.0s
<__array_function__ internals>:177: Failed
----------------------------- Captured stderr call -----------------------------
~~~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (4144069440) ~~~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.11/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/lib/python3.11/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/execnet/gateway_base.py", line 967, in _thread_receiver
    msg = Message.from_io(io)
  File "/usr/lib/python3.11/site-packages/execnet/gateway_base.py", line 432, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/usr/lib/python3.11/site-packages/execnet/gateway_base.py", line 400, in read
    data = self._read(numbytes - len(buf))
________________ TestRBFInterpolatorNeighborsInf.test_chunking _________________
[gw0] linux -- Python 3.11.0 /usr/bin/python3
self = <scipy.interpolate.tests.test_rbfinterp.TestRBFInterpolatorNeighborsInf object at 0xf0a54650>
    @pytest.mark.slow
    def test_chunking(self):
        # If the observed data comes from a polynomial, then the interpolant
        # should be able to reproduce the polynomial exactly, provided that
        # `degree` is sufficiently high.
        rng = np.random.RandomState(0)
        seq = Halton(2, scramble=False, seed=rng)
        degree = 3
    
        largeN = 1000000 + 33
        # this is large to check that chunking of the RBFInterpolator is tested
        x = seq.random(50)
        xitp = seq.random(largeN)
    
        P = _vandermonde(x, degree)
        Pitp = _vandermonde(xitp, degree)
    
        poly_coeffs = rng.normal(0.0, 1.0, P.shape[1])
    
        y = P.dot(poly_coeffs)
        yitp1 = Pitp.dot(poly_coeffs)
>       yitp2 = self.build(x, y, degree=degree)(xitp)
scipy/interpolate/tests/test_rbfinterp.py:178: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scipy/interpolate/_rbfinterp.py:535: in __call__
    out[xidx] = self._chunk_evaluator(
scipy/interpolate/_rbfinterp.py:438: in _chunk_evaluator
    vec = _build_evaluation_coefficients(
scipy/interpolate/_rbfinterp_pythran.py:212: in _build_evaluation_coefficients
    kernel_vector(xeps[i], yeps, kernel_func, vec[i, :p])
scipy/interpolate/_rbfinterp_pythran.py:54: in kernel_vector
    out[i] = kernel_func(np.linalg.norm(x - y[i]))
<__array_function__ internals>:180: in norm
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = array([-0.11523342,  0.20845211]), ord = None, axis = None, keepdims = False
    @array_function_dispatch(_norm_dispatcher)
    def norm(x, ord=None, axis=None, keepdims=False):
        """
        Matrix or vector norm.
    
        This function is able to return one of eight different matrix norms,
        or one of an infinite number of vector norms (described below), depending
        on the value of the ``ord`` parameter.
    
        Parameters
        ----------
        x : array_like
            Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
            is None. If both `axis` and `ord` are None, the 2-norm of
            ``x.ravel`` will be returned.
        ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
            Order of the norm (see table under ``Notes``). inf means numpy's
            `inf` object. The default is None.
        axis : {None, int, 2-tuple of ints}, optional.
            If `axis` is an integer, it specifies the axis of `x` along which to
            compute the vector norms.  If `axis` is a 2-tuple, it specifies the
            axes that hold 2-D matrices, and the matrix norms of these matrices
            are computed.  If `axis` is None then either a vector norm (when `x`
            is 1-D) or a matrix norm (when `x` is 2-D) is returned. The default
            is None.
    
            .. versionadded:: 1.8.0
    
        keepdims : bool, optional
            If this is set to True, the axes which are normed over are left in the
            result as dimensions with size one.  With this option the result will
            broadcast correctly against the original `x`.
    
            .. versionadded:: 1.10.0
    
        Returns
        -------
        n : float or ndarray
            Norm of the matrix or vector(s).
    
        See Also
        --------
        scipy.linalg.norm : Similar function in SciPy.
    
        Notes
        -----
        For values of ``ord < 1``, the result is, strictly speaking, not a
        mathematical 'norm', but it may still be useful for various numerical
        purposes.
    
        The following norms can be calculated:
    
        =====  ============================  ==========================
        ord    norm for matrices             norm for vectors
        =====  ============================  ==========================
        None   Frobenius norm                2-norm
        'fro'  Frobenius norm                --
        'nuc'  nuclear norm                  --
        inf    max(sum(abs(x), axis=1))      max(abs(x))
        -inf   min(sum(abs(x), axis=1))      min(abs(x))
        0      --                            sum(x != 0)
        1      max(sum(abs(x), axis=0))      as below
        -1     min(sum(abs(x), axis=0))      as below
        2      2-norm (largest sing. value)  as below
        -2     smallest singular value       as below
        other  --                            sum(abs(x)**ord)**(1./ord)
        =====  ============================  ==========================
    
        The Frobenius norm is given by [1]_:
    
            :math:`||A||_F = [\\sum_{i,j} abs(a_{i,j})^2]^{1/2}`
    
        The nuclear norm is the sum of the singular values.
    
        Both the Frobenius and nuclear norm orders are only defined for
        matrices and raise a ValueError when ``x.ndim != 2``.
    
        References
        ----------
        .. [1] G. H. Golub and C. F. Van Loan, *Matrix Computations*,
               Baltimore, MD, Johns Hopkins University Press, 1985, pg. 15
    
        Examples
        --------
        >>> from numpy import linalg as LA
        >>> a = np.arange(9) - 4
        >>> a
        array([-4, -3, -2, ...,  2,  3,  4])
        >>> b = a.reshape((3, 3))
        >>> b
        array([[-4, -3, -2],
               [-1,  0,  1],
               [ 2,  3,  4]])
    
        >>> LA.norm(a)
        7.745966692414834
        >>> LA.norm(b)
        7.745966692414834
        >>> LA.norm(b, 'fro')
        7.745966692414834
        >>> LA.norm(a, np.inf)
        4.0
        >>> LA.norm(b, np.inf)
        9.0
        >>> LA.norm(a, -np.inf)
        0.0
        >>> LA.norm(b, -np.inf)
        2.0
    
        >>> LA.norm(a, 1)
        20.0
        >>> LA.norm(b, 1)
        7.0
        >>> LA.norm(a, -1)
        -4.6566128774142013e-010
        >>> LA.norm(b, -1)
        6.0
        >>> LA.norm(a, 2)
        7.745966692414834
        >>> LA.norm(b, 2)
        7.3484692283495345
    
        >>> LA.norm(a, -2)
        0.0
        >>> LA.norm(b, -2)
        1.8570331885190563e-016 # may vary
        >>> LA.norm(a, 3)
        5.8480354764257312 # may vary
        >>> LA.norm(a, -3)
        0.0
    
        Using the `axis` argument to compute vector norms:
    
        >>> c = np.array([[ 1, 2, 3],
        ...               [-1, 1, 4]])
        >>> LA.norm(c, axis=0)
        array([ 1.41421356,  2.23606798,  5.        ])
        >>> LA.norm(c, axis=1)
        array([ 3.74165739,  4.24264069])
        >>> LA.norm(c, ord=1, axis=1)
        array([ 6.,  6.])
    
        Using the `axis` argument to compute matrix norms:
    
        >>> m = np.arange(8).reshape(2,2,2)
        >>> LA.norm(m, axis=(1,2))
        array([  3.74165739,  11.22497216])
        >>> LA.norm(m[0, :, :]), LA.norm(m[1, :, :])
        (3.7416573867739413, 11.224972160321824)
    
        """
        x = asarray(x)
    
        if not issubclass(x.dtype.type, (inexact, object_)):
            x = x.astype(float)
    
        # Immediately handle some default, simple, fast, and common cases.
        if axis is None:
            ndim = x.ndim
            if ((ord is None) or
                (ord in ('f', 'fro') and ndim == 2) or
                (ord == 2 and ndim == 1)):
    
>               x = x.ravel(order='K')
E               Failed: Timeout >500.0s
/usr/lib/python3.11/site-packages/numpy/linalg/linalg.py:2512: Failed
```

### SciPy/NumPy/Python version information

scipy1.9.2/numpy1.22.0/python3.11

**Comment by andyfaff** [comment]
Unfortunately we don't have a 686 entry in our CI.

**Comment by rgommers** [comment]
@andyfaff we do, for both Windows and Linux on Azure:
- `Main Linux_Python_38_32bit_full`
- `Main Windows Python38-32bit-fast`
