### ISSUE TITLE
BUG: Failure to download due to unsuccessful wheel build

### ISSUE THREAD

**Issue by YungAlfa** [scipy/scipy#17225]
### Describe your issue.

Tried installing scipy normally, then with binaries to no avail. I am getting an error code as requirements to build wheel did not run successfully. I am very new to this so its probably an obvious answer. I am running on MacOS Big Sur version 11.2.3.

### Reproducing Code Example

```python
pip3 install scipy --no-binary scipy
```

### Error message

```shell
Collecting scipy
  Using cached scipy-1.9.2.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      The Meson build system
      Version: 0.63.3
      Source dir: /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17
      Build dir: /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-ywpsyk65/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.2
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      Host machine cpu family: aarch64
      Host machine cpu: arm64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:49:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-ywpsyk65/build/meson-logs/meson-log.txt
      + meson setup --native-file=/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Library/Frameworks/Python.framework/Versions/3.10 /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17 /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-ywpsyk65/build
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-c30l3yxe/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/Library/Frameworks/Python.framework/Versions/3.10', '/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17', '/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-f3yq5hdx/scipy_5721a2941b1948029a7075433f845c17/.mesonpy-ywpsyk65/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

### SciPy/NumPy/Python version information

Name: numpy Version: 1.23.4

**Comment by tylerjereddy** [comment]
Decent chance you're on an M1 (ARM) Mac and running an operating system that is too old to support our binaries. We require >= `12.x` for MacOS version to use binary wheels on ARM.

**Comment by andyfaff** [comment]
This question comes up quite frequently. Do we have a potted answer prepared for when it gets asked?

**Comment by tupui** [comment]
Yeah we have this one https://github.com/scipy/scipy/issues/15861 I will pin it since the title is more explicit.

**Comment by tupui** [comment]
Yeah we have this one https://github.com/scipy/scipy/issues/15861 I will pin it since the title is more explicit.
