### ISSUE TITLE
BUG: Installation error

### ISSUE THREAD

**Issue by Joshwlks** [scipy/scipy#17266]
### Describe your issue.

Attempting to install Scipy on a Windows 10 Enterprise machine and the build wheel is failing with on the following issue: `..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]`. Not sure where to go from here. 

Please see the full error below for more information.

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
error: subprocess-exited-with-error



 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      The Meson build system
      Version: 0.63.3
      Source dir: C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87
      Build dir: C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87\.mesonpy-ar5rhfs_\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cl (msvc 19.33.31630 "Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x86")
      C linker for the host machine: link link 14.33.31630.0
      C++ compiler for the host machine: cl (msvc 19.33.31630 "Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x86")
      C++ linker for the host machine: link link 14.33.31630.0
      Host machine cpu family: x86
      Host machine cpu: x86
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
      Library m found: NO



     ..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"



     A full log can be found at C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87\.mesonpy-ar5rhfs_\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\apoor2538\.pyenv\pyenv-win\versions\3.8.10-win32 C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87 C:\Users\apoor2538\AppData\Local\Temp\pip-install-3_fif94n\scipy_1748fdd570814af5a719c919df719d87\.mesonpy-ar5rhfs_\build
      Traceback (most recent call last):
        File "C:\Users\apoor2538\.virtualenvs\evidently-localserver-monitoring-1-Vs_K9hqJ\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\apoor2538\.virtualenvs\evidently-localserver-monitoring-1-Vs_K9hqJ\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\apoor2538\.virtualenvs\evidently-localserver-monitoring-1-Vs_K9hqJ\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\apoor2538\AppData\Local\Temp\pip-build-env-h47cqqwq\overlay\Lib\site-packages\mesonpy\__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\apoor2538\.pyenv\pyenv-win\versions\3.8.10-win32\lib\contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "C:\Users\apoor2538\AppData\Local\Temp\pip-build-env-h47cqqwq\overlay\Lib\site-packages\mesonpy\__init__.py", line 948, in _project
```

### SciPy/NumPy/Python version information

SciPy 1.9.3 / NumPy 1.23.3 / Python 3.8.10

**Comment by tylerjereddy** [comment]
Maybe you're using 32-bit Python on Windows? We don't provide binaries on that platform anymore, but we do for 64-bit Python on Windows.

You could also try `pip install scipy --only-binary`; I think that might force `pip` to go back to a slightly older binary release rather than trying to build from source at the latest release.

**Comment by eli-schwartz** [comment]
> and the build wheel is failing with on the following issue: `..\..\meson.build:57:0: ERROR: Unknown compiler(s): <.......>`. Not sure where to go from here.


The real important part of the error message is the lines immediately below that. The full message is:

```
..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
 The following exception(s) were encountered:
 Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
 Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
 Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
 Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
 Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
 Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
 Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
 Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
 Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
 Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"
```

The error, basically, is that none of these programs (compilers for fortran software) could be found. You will need to install at least one of them in order to build from source, or else do as @tylerjereddy suggested and attempt to install older versions of SciPy so that you can get one available as a binary wheel instead of messing around with getting a Windows development environment with Fortran support set up.

**Comment by Joshwlks** [comment]
Thanks all, SciPy 1.9.0 worked :)
