### ISSUE TITLE
BUG: RegularGridInterpolator cannot interpolate cubically with stacked outputs

### ISSUE THREAD

**Issue by aoerder** [scipy/scipy#17293]
### Describe your issue.

Hi all,
i don't know if I got the vocabulary for description correctly but here is the issue.

When using `scipy.interpolate.RegularGridInterpolator` with input vector lengths of  `m` and `n` I can interpolate higher dimension ouputput data with the shape of `(m,n,k)` as expected. 

With an output shape of `(m,n)` both `linear` and `cubic` methods can be used.
With an output shape of `(m,n,k)` only the `linear` method can be used. Using the `cubic`method errors out in this case. 

### Reproducing Code Example

```python
from scipy.interpolate import RegularGridInterpolator
import numpy as np

# Input data
x0 = np.linspace(-1,1,5)
x1 = np.linspace(-1,1,10)
points = (x0,x1)

# Output data
values         = np.zeros((len(x0),len(x1)))
values_stacked = np.zeros((len(x0),len(x1),2)) 

# Define models
linear_model         = RegularGridInterpolator(points,values        ,"linear")
linear_model_stacked = RegularGridInterpolator(points,values_stacked,"linear")
cubic_model          = RegularGridInterpolator(points,values        ,"cubic")
cubic_model_stacked  = RegularGridInterpolator(points,values_stacked,"cubic")

# Evalute models
xi = np.array([0,0])

print(f"\nLinear model\nshould return [0.] and returns:")
print(linear_model(xi))

print(f"\nLinear model\nshould return [[0., 0.]] and returns:")
print(linear_model_stacked(xi))

print(f"\nCubic model\nshould return [0.] and returns:")
print(cubic_model(xi))

print(f"\nCubic model\nshould return [[0., 0.]] and returns:")
print(cubic_model_stacked(xi))
```

### Error message

```shell
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    print(cubic_model_stacked(xi))
  File "/home/lt6037/scrap/.venv/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 335, in __call__
    result = self._evaluate_spline(self.values.T, xi,
  File "/home/lt6037/scrap/.venv/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 388, in _evaluate_spline
    first_values = self._do_spline_fit(self.grid[last_dim],
  File "/home/lt6037/scrap/.venv/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 414, in _do_spline_fit
    local_interp = make_interp_spline(x, y, k=k, axis=0)
  File "/home/lt6037/scrap/.venv/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1249, in make_interp_spline
    raise ValueError('Shapes of x {} and y {} are incompatible'
ValueError: Shapes of x (10,) and y (2, 10, 5) are incompatible
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
The changes on main fix this

```
In [1]: from scipy.interpolate import RegularGridInterpolator
   ...: import numpy as np
   ...:
   ...: # Input data
   ...: x0 = np.linspace(-1,1,5)
   ...: x1 = np.linspace(-1,1,10)
   ...: points = (x0,x1)
   ...:
   ...: # Output data
   ...: values         = np.zeros((len(x0),len(x1)))
   ...: values_stacked = np.zeros((len(x0),len(x1),2))
   ...:
   ...: # Define models
   ...: linear_model         = RegularGridInterpolator(points,values        ,"linear")
   ...: linear_model_stacked = RegularGridInterpolator(points,values_stacked,"linear")
   ...: cubic_model          = RegularGridInterpolator(points,values        ,"cubic")
   ...: cubic_model_stacked  = RegularGridInterpolator(points,values_stacked,"cubic")
   ...:
   ...: # Evalute models
   ...: xi = np.array([0,0])
   ...:
   ...: print(f"\nLinear model\nshould return [0.] and returns:")
   ...: print(linear_model(xi))
   ...:
   ...: print(f"\nLinear model\nshould return [[0., 0.]] and returns:")
   ...: print(linear_model_stacked(xi))
   ...:
   ...: print(f"\nCubic model\nshould return [0.] and returns:")
   ...: print(cubic_model(xi))
   ...:
   ...: print(f"\nCubic model\nshould return [[0., 0.]] and returns:")
   ...: print(cubic_model_stacked(xi))

Linear model
should return [0.] and returns:
[0.]

Linear model
should return [[0., 0.]] and returns:
[[0. 0.]]

Cubic model
should return [0.] and returns:
[0.]

Cubic model
should return [[0., 0.]] and returns:
[[0. 0.]]

```

**Comment by aoerder** [comment]
yes, this is fixed in the nightly build. I should have tried this before. many thanks!
