### ISSUE TITLE
doc build warning in scipy.ndimage.rotate

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#17320]
Our doc build complains about something related to either `directionalmean` or `Covariance` in scipy.stats:

```
$ python dev.py doc -j6

<snip>

WARNING: autodoc: failed to import property 'Covariance.dimensionality' from module 'scipy.stats'; the following exception was raised:
Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/util/inspect.py", line 380, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'Covariance' has no attribute 'dimensionality'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 101, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 307, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2795, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/util/inspect.py", line 396, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: dimensionality

WARNING: autodoc: failed to import function 'directionalmean' from module 'scipy.stats'; the following exception was raised:
Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/util/inspect.py", line 380, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'scipy.stats' has no attribute 'directionalmean'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 101, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 307, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2795, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/sphinx/util/inspect.py", line 396, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: directionalmean

/home/br/repos/scipy/scipy/build-install/lib/python3.8/site-packages/scipy/ndimage/_interpolation.py:docstring of scipy.ndimage._interpolation.rotate:108: WARNING: Exception occurred in plotting scipy-ndimage-rotate-1
 from /home/br/repos/scipy/scipy/doc/source/reference/generated/scipy.ndimage.rotate.rst:
Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 14, in <module>
AttributeError: 'Figure' object has no attribute 'set_layout_engine'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/br/repos/scipy/scipy/doc/source/reference/generated/scipy.stats.directionalmean.rst: WARNING: document isn't included in any toctree
done

<snip>

dumping object inventory... done
build finished with problems, 4 warnings.
make: *** [Makefile:110: html-build] Error 1
```

The doc build  finishes and produces other doc pages, so whatever the issue is, it is not fatal.

**Comment by WarrenWeckesser** [comment]
Did you do an update and complete clean of the git repo before running `python dev.py doc -j6`?  I don't find any occurrences of `directionalmean` in the main development branch.

**Comment by ev-br** [comment]
Thanks Warren. Indeed, `$ git clean -xdf` removes the `directionalmean` related warning. The ndimage one remains though:

```
/home/br/repos/scipy/scipy/build-install/lib/python3.8/site-packages/scipy/ndimage/_interpolation.py:docstring of scipy.ndimage._interpolation.rotate:108: WARNING: Exception occurred in plotting scipy-ndimage-rotate-1
 from /home/br/repos/scipy/scipy/doc/source/reference/generated/scipy.ndimage.rotate.rst:
Traceback (most recent call last):
  File "/home/br/.virtualenvs/scipy-dev/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in _run_code
    exec(code, ns)
  File "<string>", line 14, in <module>
AttributeError: 'Figure' object has no attribute 'set_layout_engine'

```

**Comment by j-bowhay** [comment]
See #17144, maybe try updating matplotlib?

**Comment by ev-br** [comment]
Thanks Jake, upgrading matplotlib does it. All set, the issue is a collection of user flukes, closing.
