### ISSUE TITLE
BUG: cannot install scipy/meson.build ERROR: Dependency "OpenBLAS" not found, tried pkgconfig, framework and cmake

### ISSUE THREAD

**Issue by jamesbraza** [scipy/scipy#17337]
### Describe your issue.

I am trying to install `scipy` on my Mac M1, macOS Monterey version 12.6.

I keep getting this message, despite having OpenBLAS specified:

```none
../../scipy/meson.build:131:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig, framework and cmake
```

Inspired by https://github.com/scipy/scipy/issues/13409#issuecomment-1021057368.

### Reproducing Code Example

```python
> pip list
Package        Version
-------------- --------
attrs          22.1.0
beniget        0.4.1
Cython         0.29.32
exceptiongroup 1.0.0
gast           0.5.3
iniconfig      1.1.1
meson          0.63.3
ninja          1.10.2.4
numpy          1.23.4
packaging      21.3
pip            22.3
pluggy         1.0.0
ply            3.11
pybind11       2.10.1
pyparsing      3.0.9
pytest         7.2.0
pythran        0.12.0
setuptools     56.0.0
tomli          2.0.1

> brew install openblas
> export OPENBLAS=$(/opt/homebrew/bin/brew --prefix openblas)
> export CFLAGS="-falign-functions=8 ${CFLAGS}"
> pip install scipy
```

### Error message

```shell
Looking in indexes: https://pypi.org/simple
Collecting scipy
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      ld: warning: directory not found for option '-L/opt/homebrew/opt/lapack/lib'
      The Meson build system
      Version: 0.63.3
      Source dir: /private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6
      Build dir: /private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-5zpf6fue/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.102)")
      C linker for the host machine: cc ld64 819.6
      C++ compiler for the host machine: c++ (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.102)")
      C++ linker for the host machine: c++ ld64 819.6
      Host machine cpu family: aarch64
      Host machine cpu: arm64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
      Fortran linker for the host machine: gfortran ld64 819.6
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Program cython found: YES (/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/bin/cython)
      Program pythran found: YES (/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/bin/pythran)
      Program cp found: YES (/bin/cp)
      Program python found: YES (/Users/james.braza/code/stingray/venv/bin/python)
      Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Found CMake: /opt/homebrew/bin/cmake (3.24.2)
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)

      ../../scipy/meson.build:131:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig, framework and cmake

      A full log can be found at /private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-5zpf6fue/build/meson-logs/meson-log.txt
      + meson setup --native-file=/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Users/james.braza/.pyenv/versions/3.8.14 /private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6 /private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-5zpf6fue/build
      Traceback (most recent call last):
        File "/Users/james.braza/code/stingray/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/james.braza/code/stingray/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/james.braza/code/stingray/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/Users/james.braza/.pyenv/versions/3.8.14/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/Users/james.braza/.pyenv/versions/3.8.14/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-build-env-y04279an/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/Users/james.braza/.pyenv/versions/3.8.14/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/Users/james.braza/.pyenv/versions/3.8.14', '/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6', '/private/var/folders/78/lm6p91s90fx99cshsxqz_19w0000gn/T/pip-install-5u70s5ho/scipy_e3eb27a162664e6297ee8511faef33d6/.mesonpy-5zpf6fue/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### SciPy/NumPy/Python version information

n/a, 1.23.4, 3.8.14

**Comment by andyfaff** [comment]
I'm not sure why pip doesn't install the wheel that's on PyPI, `scipy-1.9.3-cp38-cp38-macosx_12_0_arm64.whl`. If I create a Python 3.8 environment then try and pip install scipy it collects the correct wheel. What happens if you try:
```
pip install scipy==1.9.3 --only-binary=:all:
```

**Comment by jamesbraza** [comment]
Yeah I am also not sure why `pip install` is not playing nice with the macOS binaries. 🥲 

Adding either `--only-binary=:all:` or `--prefer-binary` enabled the installation to work, by installing a macOS binary.

Thank you so much @andyfaff !  Please feel free to close this ticket if you see no further action necessary.

**Comment by hafiz031** [comment]
Check your Python version. I was able to install this in `Python 3.11.4` (in Anaconda).

**Comment by juandelperal** [comment]
I found the solution by running 
`brew info openblas`

and then setting the variables added shown there:

...
==> Caveats
openblas is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides BLAS in Accelerate.framework.

For compilers to find openblas you may need to set:
  **export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"**

For pkg-config to find openblas you may need to set:
  **export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"**

**Comment by lucascolley** [comment]
Yep, the pkg-config part is now included in the macOS section of our building docs: https://scipy.github.io/devdocs/building/index.html#system-level-dependencies
