### ISSUE TITLE
BUG: scipy.test() failures on macOS 12.6/x86_64

### ISSUE THREAD

**Issue by khpeterson** [scipy/scipy#17360]
### Describe your issue.

@rgommers The test suite finishes on arm64:
```
=================================== 37188 passed, 3336 skipped, 12061 deselected, 138 xfailed, 11 xpassed, 326 warnings in 416.61s (0:06:56) ===================================
```
but on x86_64 there are failures in "scipy/stats/tests/test_sampling" and eventually pytest dies with "OSError: [Errno 24] Too many open files":
```
scipy/stats/tests/test_sampling.py .......................................................................................................................................FFFF [ 97%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.....F.....FFFFFFF.FFFFssFFFssssssssssFFsFF.....F.FF..........F.FFFFssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 97%]
ssssssssssssssssssssssssssssssssssssssFFFFFFFFFF..FFFFFFFFFFFFFFF.........FFFFFFFFF..sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 98%]
sssssssssssssssssssss.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssFFFssssssssssFFsFFFFFFFFF..........FFFFFF...    
```
Everything else finishes OK and when I just run 'scipy.test(tests=['scipy/stats/tests'])' it finishes OK too.

Attached are verbose logs for arm64 and x86_64 as well as the standalone run.

[scipy_test_arm64.log](https://github.com/scipy/scipy/files/9946424/scipy_test_arm64.log)
[scipy_test_x86_64.log](https://github.com/scipy/scipy/files/9946428/scipy_test_x86_64.log)
[scipy_test_stats_x86_64.log](https://github.com/scipy/scipy/files/9946452/scipy_test_stats_x86_64.log)

### Reproducing Code Example

```python
python3 -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.test()'
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/khp/Downloads/Temp/scipy/_lib/_testutils.py", line 69, in __call__
    code = pytest.main(pytest_args)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/config/__init__.py", line 167, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/main.py", line 305, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/terminal.py", line 818, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py", line 34, in _multicall
    next(gen)  # first yield
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/terminal.py", line 833, in pytest_terminal_summary
    self.summary_failures()
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/terminal.py", line 1015, in summary_failures
    self._outrep_summary(rep)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/terminal.py", line 1034, in _outrep_summary
    rep.toterminal(self._tw)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/reports.py", line 90, in toterminal
    longrepr_terminal.toterminal(out)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_code/code.py", line 1030, in toterminal
    element[0].toterminal(tw)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_code/code.py", line 1060, in toterminal
    entry.toterminal(tw)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_code/code.py", line 1147, in toterminal
    self._write_entry_lines(tw)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_code/code.py", line 1137, in _write_entry_lines
    tw._write_source(source_lines, indents)
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_io/terminalwriter.py", line 192, in _write_source
    new_lines = self._highlight(source).splitlines()
  File "/Users/khp/Library/Python/3.9/lib/python/site-packages/_pytest/_io/terminalwriter.py", line 203, in _highlight
    from pygments.formatters.terminal import TerminalFormatter
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1347, in _path_importer_cache
OSError: [Errno 24] Too many open files
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
@tirthasheshpatel @chrisb83 The x86 log shows a lot of failures from `scipy.stats.sampling`. Could you take a look?
```
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
____________ TestNumericalInverseHermite.test_basic[3-dist0-mv_ex0] ____________
/Users/khp/Downloads/Temp/scipy/stats/tests/test_sampling.py:980: in test_basic
    ???
        dist       = <scipy.stats.tests.test_sampling.TestNumericalInverseHermite.dist0 object at 0x12ddb7610>
        mv_ex      = [-0.15915494309189535, 0.30800303742274887]
        order      = 3
        self       = <scipy.stats.tests.test_sampling.TestNumericalInverseHermite object at 0x12df17790>
scipy/stats/unuran_wrapper.pyx:2006: in scipy.stats.unuran_wrapper.NumericalInverseHermite.__cinit__
    ???
        DiscreteAliasUrn = <class 'scipy.stats.unuran_wrapper.DiscreteAliasUrn'>
        DiscreteGuideTable = <class 'scipy.stats.unuran_wrapper.DiscreteGuideTable'>
        Method     = <class 'scipy.stats.unuran_wrapper.Method'>
        NumericalInverseHermite = <class 'scipy.stats.unuran_wrapper.NumericalInverseHermite'>
        NumericalInversePolynomial = <class 'scipy.stats.unuran_wrapper.NumericalInversePolynomial'>
        SimpleRatioUniforms = <class 'scipy.stats.unuran_wrapper.SimpleRatioUniforms'>
        TransformedDensityRejection = <class 'scipy.stats.unuran_wrapper.TransformedDensityRejection'>
        UError     = <class 'importlib._bootstrap.UError'>
        UNURANError = <class 'scipy.stats.unuran_wrapper.UNURANError'>
        _URNG      = <class 'scipy.stats.unuran_wrapper._URNG'>
        __all__    = ['UNURANError',
 'TransformedDensityRejection',
 'DiscreteAliasUrn',
 'NumericalInversePolynomial']
        __builtins__ = <builtins>
        __doc__    = None
        __file__   = '/Users/khp/Downloads/Temp/scipy/stats/_unuran/unuran_wrapper.cpython-39-darwin.so'
        __loader__ = <_frozen_importlib_external.ExtensionFileLoader object at 0x123ffcfa0>
        __name__   = 'scipy.stats._unuran.unuran_wrapper'
        __package__ = 'scipy.stats._unuran'
        __pyx_unpickle_Enum = <built-in function __pyx_unpickle_Enum>
        __pyx_unpickle__URNG = <built-in function __pyx_unpickle__URNG>
        __spec__   = ModuleSpec(name='scipy.stats._unuran.unuran_wrapper', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x123ffcfa0>, origin='/Users/khp/Downloads/Temp/scipy/stats/_unuran/unuran_wrapper.cpython-39-darwin.so')
        __test__   = {'TransformedDensityRejection.ppf_hat (line 962)': '\n'
                                                   '        ppf_hat(u)\n'
                                                   '\n'
                                                   '        Evaluate the '
                                                   'inverse of the CDF of the '
                                                   'hat distribution at `u`.\n'
                                                   '\n'
                                                   '        Parameters\n'
                                                   '        ----------\n'
                                                   '        u : array_like\n'
                                                   '            An array of '
                                                   'percentiles\n'
                                                   '\n'
                                                   '        Returns\n'
                                                   '        -------\n'
                                                   '        ppf_hat : '
                                                   'array_like\n'
                                                   '            Array of '
                                                   'quantiles corresponding to '
                                                   'the given percentiles.\n'
                                                   '\n'
                                                   '        Examples\n'
                                                   '        --------\n'
                                                   '        >>> from '
                                                   'scipy.stats.sampling '
                                                   'import '
                                                   'TransformedDensityRejection\n'
                                                   '        >>> from '
                                                   'scipy.stats import norm\n'
                                                   '        >>> from math '
                                                   'import exp\n'
                                                   '        >>> \n'
                                                   '        >>> class MyDist:\n'
                                                   '        ...     def '
                                                   'pdf(self, x):\n'
                                                   '        ...         return '
                                                   'exp(-0.5 * x**2)\n'
                                                   '        ...     def '
                                                   'dpdf(self, x):\n'
                                                   '        ...         return '
                                                   '-x * exp(-0.5 * x**2)\n'
                                                   '        ... \n'
                                                   '        >>> dist = '
                                                   'MyDist()\n'
                                                   '        >>> rng = '
                                                   'TransformedDensityRejection(dist)\n'
                                                   '        >>> \n'
                                                   '        >>> '
                                                   'rng.ppf_hat(0.5)\n'
                                                   '        '
                                                   '-0.00018050266342393984\n'
                                                   '        >>> norm.ppf(0.5)\n'
                                                   '        0.0\n'
                                                   '        >>> u = '
                                                   'np.linspace(0, 1, '
                                                   'num=1000)\n'
                                                   '        >>> ppf_hat = '
                                                   'rng.ppf_hat(u)\n'
                                                   '        '}
        _validate_domain = <built-in function _validate_domain>
        _validate_qmc_input = <built-in function _validate_qmc_input>
        argsreduce = <function argsreduce at 0x123590ee0>
        check_random_state = <function check_random_state at 0x114222550>
        functools  = <module 'functools' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py'>
        namedtuple = <function namedtuple at 0x105a824c0>
        np         = <module 'numpy' from '/Users/khp/Downloads/Temp/numpy/__init__.py'>
        rv_frozen  = <class 'scipy.stats._distn_infrastructure.rv_frozen'>
        stats      = <module 'scipy.stats' from '/Users/khp/Downloads/Temp/scipy/stats/__init__.py'>
        threading  = <module 'threading' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py'>
        warnings   = <module 'warnings' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/warnings.py'>
messagestream.pyx:29: in scipy._lib.messagestream.MessageStream.__cinit__
    ???
        MessageStream = <class 'scipy._lib.messagestream.MessageStream'>
        __builtins__ = <builtins>
        __doc__    = None
        __file__   = '/Users/khp/Downloads/Temp/scipy/_lib/messagestream.cpython-39-darwin.so'
        __loader__ = <_frozen_importlib_external.ExtensionFileLoader object at 0x117346a90>
        __name__   = 'scipy._lib.messagestream'
        __package__ = 'scipy._lib'
        __spec__   = ModuleSpec(name='scipy._lib.messagestream', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x117346a90>, origin='/Users/khp/Downloads/Temp/scipy/_lib/messagestream.cpython-39-darwin.so')
        __test__   = {}
        os         = <module 'os' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py'>
        tempfile   = <module 'tempfile' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tempfile.py'>
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tempfile.py:332: in mkstemp
    ???
        dir        = b'/var/folders/_k/4315zzfs7jgdm_p_lwr1f8300000gn/T'
        flags      = 2818
        output_type = <class 'bytes'>
        prefix     = b'scipy-'
        suffix     = b''
        text       = False
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tempfile.py:251: in _mkstemp_inner
    ???
E   OSError: [Errno 24] Too many open files: b'/var/folders/_k/4315zzfs7jgdm_p_lwr1f8300000gn/T/scipy-ayd26db3'
        dir        = b'/var/folders/_k/4315zzfs7jgdm_p_lwr1f8300000gn/T'
        file       = b'/var/folders/_k/4315zzfs7jgdm_p_lwr1f8300000gn/T/scipy-ayd26db3'
        flags      = 2818
        name       = b'ayd26db3'
        names      = <map object at 0x1401e2ac0>
        output_type = <class 'bytes'>
        pre        = b'scipy-'
        seq        = 0
        suf        = b''
```

**Comment by mdhaber** [comment]
@tirthasheshpatel @chrisb83 Could you look into these `stats.sampling` test failures?

**Comment by mdhaber** [comment]
@tirthasheshpatel @chrisb83 could you take a look at this? Can you imagine why this might happen, or does it look like a build/installation issue to you?

@khpeterson do you have the same problem in 1.10.0?

**Comment by mdhaber** [comment]
@khpeterson do you have the same problem in 1.10.0?

**Comment by khpeterson** [comment]
Apologies for the delay, I’m traveling at the moment but will try on my macOS x86_64 env when I get back to the office.

On Feb 14, 2023, at 11:42 AM, Matt Haberland ***@***.******@***.***>> wrote:



@khpeterson<https://github.com/khpeterson> do you have the same problem in 1.10.0?

**Comment by khpeterson** [comment]
Here's a log from 1.10.0 on my macOS 12.6.3 x86_64 machine - looks like the problem persists:

[scipy_test_x86_64_1.10.0.log](https://github.com/scipy/scipy/files/10786955/scipy_test_x86_64_1.10.0.log)

And FWIW, here's the same thing on my macOS 12.6.3 arm64 machine:

[scipy_test_arm64_1.10.0.log](https://github.com/scipy/scipy/files/10787101/scipy_test_arm64_1.10.0.log)

**Comment by tupui** [comment]
I think there is no issue. Searching for the error it just seems to be because the Python process opened too many files for the platform. You could try with higher values like `ulimit -n 10240`.

If the tests are individually running (or higher batches like the whole module), then it should be ok. Also, side note, macOS intel is going to disappear and we are going to drop support soon.

**Comment by tupui** [comment]
Actually, @tirthasheshpatel I see we have `self._messages = MessageStream()`. Is this closing properly?? I don't see any calls to `MessageStream.close`

**Comment by tirthasheshpatel** [comment]
It is called in `__dealloc__` which should be triggered automatically by GC. Although, I do think since the call to the destructor isn't deterministic, it might stay open. I don't have a macOS machine so can't test if calling `.close()` explicitly solves this issue but I can submit a PR. Would you be able to build and test @khpeterson?

**Comment by tupui** [comment]
Which line is closing `self._message`?

```python
    @cython.final
    def __dealloc__(self):
        if self.distr != NULL:
            unur_distr_free(self.distr)
            self.distr = NULL
        if self.par != NULL:
            unur_par_free(self.par)
            self.par = NULL
        if self.rng != NULL:
            unur_free(self.rng)
            self.rng = NULL
        if self.urng != NULL:
            unur_urng_free(self.urng)
            self.urng = NULL
```

If you overwrite the dealloc mechanism, are you sure everything else is being free when GC kicks in?

**Comment by tirthasheshpatel** [comment]
> If you overwrite the dealloc mechanism, are you sure everything else is being free when GC kicks in?

It should be. Cython docs recommend doing that:

![image](https://user-images.githubusercontent.com/43181252/220198082-e9efdf41-985c-4448-a598-08fe71fd7706.png)


> Which line is closing `self._message`?

https://github.com/scipy/scipy/blob/a92035d52e95a6b2670fa1155974313664bd7f89/scipy/_lib/messagestream.pyx#L45-L46

**Comment by tupui** [comment]
mmm ok but in the dealloc of `Method` we do not dealloc or del `MessageStream`. This is probably the issue no?

**Comment by tupui** [comment]
Actually yes, this is what I understand of the doc: `any C data explicitly allocated should be freed`. Which we don't do.

**Comment by tirthasheshpatel** [comment]
You might be right. I was relying on Cython that it will call `__dealloc__` when ref count of the object reaches zero. But I need someone to confirm that.

**Comment by tupui** [comment]
@da-woods if you have some time to bring some light 😄

**Comment by da-woods** [comment]
Hi.

> any C data explicitly allocated should be freed

This is really referring to things allocated with `malloc`, C++ `new`, `stdio.fclose` or similar. Essentially any C level operations that you'd have to write out manually if you were writing C code.

Python reference counting should happen as normal - it isn't broken by a custom `__dealloc__` method.

I'm not quite sure exactly where all the code you're discussing is, but you have a `cdef class Something` which contains a `_messages` attribute which is a `cdef class MessageStream`. `MessageStream.__dealloc__` closes itself.

So `Something` does its manual C deallocation, then it automatically decrefs all it's PyObject attributes (including `_messages`). if `MessageStream` has a reference count of 1 then it is deallocated, and `MessageStream.close` should be called. Obviously if more references to it exist then it'll stay alive.

So I can't see anything obviously wrong with your destruction scheme here

**Comment by tirthasheshpatel** [comment]
Thanks for clearing that out @da-woods! I think that is is exact behaviour I was relying on and also can't spot anything obviously wrong with the code. @khpeterson Can you please try @tupui's suggestion to increase the allowed number of open files using `ulimit -n 10240`?

**Comment by tupui** [comment]
Thank you for the insights!

**Comment by tupui** [comment]
@da-woods for reference the Cython code we are referring to is here: https://github.com/scipy/scipy/blob/main/scipy/stats/_unuran/unuran_wrapper.pyx

**Comment by da-woods** [comment]
A couple of comments (having had a proper look).

1. I don't think there's any benefit to `@cython.final` on `__dealloc__`. Deallocation doesn't happen via the "virtual function" mechanism so the best case is it won't do anything. The worst case is that it's causing Cython to do something wrong (this'd be a bug in Cython, but it'd be simpler not to have it).
2. I don't think this should be happening, but if the `MessageStream` objects are being clearer up by the GC rather than be decref, Cython might end up dropping `_filename` to try to break reference counting cycles, which could be the error that you see. I think it should be clever enough to know that `bytes` (nor anything else in `MessageStream`) can't appear in reference counting cycles though. You could fix that with `@cython.no_gc` on `MessageStream` (https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html).

**Comment by khpeterson** [comment]
ulimit -n 10240 does make the failures go away.

[scipy_test_x86_64_1.10.0_ulimit_10240.log](https://github.com/scipy/scipy/files/10788148/scipy_test_x86_64_1.10.0_ulimit_10240.log)

**Comment by tirthasheshpatel** [comment]
Thanks @da-woods for looking into the code and for the suggestions!

Thanks for confirming that increasing the limit works @khpeterson! My best guess why this might be happening is that more instances of classes in the sampling module get created by the tests than the maximum limit of open files in macOS. That's not necessarily a bug in the code and I would opt to close this issue. What do you think @mdhaber @tupui?

**Comment by tupui** [comment]
If I understood the above correctly, our current code seems ok so I would be fine closing it and hope it does not pop up later in our CI.

**Comment by mdhaber** [comment]
> My best guess why this might be happening is that more instances of classes in the sampling module get created by the tests than the maximum limit of open files in macOS.

So it sounds like the failure does not actually indicate a problem. That's good. Is there any easy way to reduce the number of open files without significantly changing the tests? If not, I'd be OK asking users to change the default limit if they don't want to see the errors.

**Comment by khpeterson** [comment]
Seems also to be timing (processor speed) dependent in that the identical config on macOS/arm64 has no problem, which in my case is a much faster machine.

On Feb 20, 2023, at 4:02 PM, Matt Haberland ***@***.******@***.***>> wrote:



My best guess why this might be happening is that more instances of classes in the sampling module get created by the tests than the maximum limit of open files in macOS.

So it sounds like the failure does not actually indicate a problem. That's good. Is there any easy way to reduce the number of open files without significantly changing the tests? If not, I'd be OK asking users to change the default limit if they don't want to see the errors.

**Comment by mdhaber** [comment]
OK. Good to know in case it comes up again. @tirthasheshpatel if there's something you can do to reduce the number of open files, please consider it, but it sounds like this doesn't need to be tracked.
