### ISSUE TITLE
BUG: freqz does not work on multi-dimensional array, despite what documentation claims

### ISSUE THREAD

**Issue by sliedes** [scipy/scipy#17387]
### Describe your issue.

freqz documentation seems to imply that it supports multidimensional inputs as long as the first dimension is the filter coeffients:

```
b: array_like

Numerator of a linear filter. If b has dimension greater than 1, it is assumed that the coefficients are stored in the first dimension, and b.shape[1:], a.shape[1:], and the shape of the frequencies array must be compatible for broadcasting.
```

However, freqz fails when given a 2-dimensional array.

### Reproducing Code Example

```python
import scipy
import numpy as np

scipy.signal.freqz(np.zeros((128, 10)))
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sami/.virtualenvs/tmp/lib/python3.10/site-packages/scipy/signal/_filter_design.py", line 474, in freqz
    h = (npp_polyval(zm1, b, tensor=False) /
  File "/home/sami/.virtualenvs/tmp/lib/python3.10/site-packages/numpy/polynomial/polynomial.py", line 754, in polyval
    c0 = c[-1] + x*0
ValueError: operands could not be broadcast together with shapes (10,) (512,)
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @sliedes, thank you for reporting. The documentation could probably be improved, if you have a look at the broadcasting example at the end of the docstrings, you need to be careful with the shape. Does that help? https://scipy.github.io/devdocs/reference/generated/scipy.signal.freqz.html

We could maybe improve the error messaging here.

**Comment by tinaoberoi** [comment]
Hi @tupui , 
Is anybody working on this? If not would love to take this up.

**Comment by tupui** [comment]
Hi @tinaoberoi, you are more than welcome to work on this. We don't do issue/work assignment, we just make sure there is just 1 PR open for a given task so there is no competing work.

**Comment by Dronten** [comment]
can i work on this issue

**Comment by melissawm** [comment]
@Dronten as you can see from the linked PR above, it looks like a fix is already under way. Feel free to look at other issues in the repo with no PRs attached to them. Cheers!

**Comment by SarahSchachter** [comment]
Is this issue still relevant?
