### ISSUE TITLE
BUG: ImportError: cannot import name '_prepare_scalar_function' from 'scipy.optimize.optimize' 

### ISSUE THREAD

**Issue by jhrsya** [scipy/scipy#17383]
### Describe your issue.

ImportError: cannot import name '_prepare_scalar_function' from 'scipy.optimize.optimize' .
scipy == 1.0.1

### Reproducing Code Example

```python
from scipy.optimize.optimize import (MemoizeJac, OptimizeResult,
                       _check_unknown_options, _prepare_scalar_function)
```

### Error message

```shell
Traceback (most recent call last):
  File "/data2/huchaowen/LaMOO/molecule/MCTS.py", line 18, in <module>
    from Node import Node
  File "/data2/huchaowen/LaMOO/molecule/Node.py", line 1, in <module>
    from Classifier import Classifier
  File "/data2/huchaowen/LaMOO/molecule/Classifier.py", line 35, in <module>
    from botorch_lamcts.botorch.optim.optimize import optimize_acqf, optimize_acqf_list
  File "/data2/huchaowen/LaMOO/molecule/botorch_lamcts/botorch/optim/optimize.py", line 21, in <module>
    from botorch_lamcts.botorch.generation.gen import gen_candidates_scipy
  File "/data2/huchaowen/LaMOO/molecule/botorch_lamcts/botorch/generation/gen.py", line 24, in <module>
    from minimize import minimize
  File "/data2/huchaowen/LaMOO/molecule/minimize.py", line 33, in <module>
    from lbfgsb import _minimize_lbfgsb
  File "/data2/huchaowen/LaMOO/molecule/lbfgsb.py", line 40, in <module>
    from scipy.optimize.optimize import (MemoizeJac, OptimizeResult,
ImportError: cannot import name '_prepare_scalar_function' from 'scipy.optimize.optimize'
```

### SciPy/NumPy/Python version information

python=3.8.13   scipy=1.0.1  numpy=1.23.3

**Comment by andyfaff** [comment]
All functions beginning with a leading underscore should be considered private, for internal use of the library. That's not to say that they can't be used, but don't be surprised if things break. This should be reported as an issue for the package that's doing the importing.
