### ISSUE TITLE
`pip install scipy` fails under PyPy on Windows

### ISSUE THREAD

**Issue by snydej** [scipy/scipy#17508]
### Describe your issue.

Installing scipy through pip fails under pypy3 but works fine under python3.
@rgommers

### Reproducing Code Example

```python
pypy3 -m pip install scipy
```

### Error message

```shell
Collecting scipy
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  ├ù Preparing metadata (pyproject.toml) did not run successfully.
  Γöé exit code: 1
  Γò░ΓöÇ> [72 lines of output]
      + meson setup --prefix=C:\Users\snydej\programs\pypy C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b\.mesonpy-5a_a1ish\build --native-file=C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      The Meson build system
      Version: 0.64.1
      Source dir: C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b
      Build dir: C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b\.mesonpy-5a_a1ish\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      Activating VS 17.2.6
      C compiler for the host machine: cl (msvc 19.32.31332 "Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64")
      C linker for the host machine: link link 14.32.31332.0
      C++ compiler for the host machine: cl (msvc 19.32.31332 "Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64")
      C++ linker for the host machine: link link 14.32.31332.0
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
      Library m found: NO

      ..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\snydej\AppData\Local\Temp\pip-install-wmxweksf\scipy_c3a06fc99d40498d82871aa16bf7b76b\.mesonpy-5a_a1ish\build\meson-logs\meson-log.txt
      Traceback (most recent call last):
        File "C:\Users\snydej\programs\pypy\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\snydej\programs\pypy\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\snydej\programs\pypy\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\snydej\programs\pypy\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "C:\Users\snydej\programs\pypy\Lib\contextlib.py", line 119, in __enter__
          return next(self.gen)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\snydej\programs\pypy\Lib\contextlib.py", line 119, in __enter__
          return next(self.gen)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "C:\Users\snydej\AppData\Local\Temp\pip-build-env-a9nptern\overlay\Lib\site-packages\mesonpy\__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "C:\Users\snydej\programs\pypy\Lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=C:\\Users\\snydej\\programs\\pypy', 'C:\\Users\\snydej\\AppData\\Local\\Temp\\pip-install-wmxweksf\\scipy_c3a06fc99d40498d82871aa16bf7b76b', 'C:\\Users\\snydej\\AppData\\Local\\Temp\\pip-install-wmxweksf\\scipy_c3a06fc99d40498d82871aa16bf7b76b\\.mesonpy-5a_a1ish\\build', '--native-file=C:\\Users\\snydej\\AppData\\Local\\Temp\\pip-install-wmxweksf\\scipy_c3a06fc99d40498d82871aa16bf7b76b\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

├ù Encountered error while generating package metadata.
Γò░ΓöÇ> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### SciPy/NumPy/Python version information

Python 3.9.10 (b332b321bbaa72bffb0207da5b7fe4c38047d3b2, Mar 16 2022, 16:03:21) [PyPy 7.3.9 with MSC v.1929 64 bit (AMD64)] on win32

**Comment by eli-schwartz** [comment]
```
      ..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"
```

In order to build SciPy from source, you need a fortran compiler installed. On Windows, that may be a bit fiddly to set up -- the official SciPy binaries are built with the mingw toolchain IIRC.

> Installing scipy through pip fails under pypy3 but works fine under python3.

But I'm assuming in the python3 case it simply downloaded a binary wheel, right? So this isn't a pypy issue, except inasmuch as there are no official wheels for pypy?

**Comment by rgommers** [comment]
Yes, no Fortran compiler is the problem. @snydej a warning that this will be hard to get to work. PyPy on Windows is completely untested, it may be broken even if you get the right compiler toolchain installed etc. I recommend avoiding it, you may be in for a very rough ride if you do try.

**Comment by snydej** [comment]
Would it be possible to copy over the already built files from my python3 installation such that the build system sees them as already built and doesn't try to rebuild them?

**Comment by rgommers** [comment]
no, that won't work. there are no PyPy prebuilt binaries for SciPy at all. you cannot just take ones for CPython, PyPy will not work with those.

**Comment by eli-schwartz** [comment]
The built extensions are compiled against the CPython headers, and those are the only already built files you get.

...

However even if you had the individual`*.obj` files for just the fortran code extracted from an in progress build of the CPython extensions... build systems don't support short circuiting their core setup and grabbing individual `*.obj` files that already exist. In theory you could do this by making all the fortran code into static libraries and then installing or otherwise sharing those, and using them as detected dependencies, but that would be a lot of work, and it's unclear how to best distribute them (PyPI isn't a good fit for non-python code).

**Comment by rgommers** [comment]
If anyone is interested in better PyPy support, here is the place to look and help out: https://github.com/conda-forge/scipy-feedstock/pull/208.

I re-titled this, it's not really a bug. PyPy is simply not a well-supported platform at this point.

**Comment by tanypredator** [comment]
Hello! I have the same error. I'm working in PyCharm and I've tried to install scipy via its package manager and also via cmd ("pip install scipy" in my PyCharm project folder). I'm not sure, but that is not "PyPy"? Yet I'm getting "Preparing metadata (pyproject.toml): finished with status 'error'".

**Comment by rgommers** [comment]
That is not related to PyPy @tanypredator, it's a generic error message. Please avoid installing from source if you can. If you do want to try, please open a new issue with a full build log.

**Comment by tanypredator** [comment]
But I don't do it from source :( I'm trying to install it via PyCharm package manager, I don't download source files to my PC to install them manually. I've read your note about fortran higher, and I've found the recommendation to install "gfortran" package to enable installation of scipy, but PyCharm package manager doesn't find gfortran.

I'm sorry that I write in this issue, I thought it would be good idea since I have the same error...

**Comment by rgommers** [comment]
> I'm trying to install it via PyCharm package manager,

I don't know what that manager does exactly, but it probably just invokes `pip` which unfortunately does try to build from source if it cannot find a suitable binary wheel.

**Comment by lesshaste** [comment]
Would a  solution be if scipy provided binary wheels ?

**Comment by rgommers** [comment]
> Would a solution be if scipy provided binary wheels ?

That's one of a number of possible solutions - let's leave that to a separate issue though. This one is "user error" because of not having the required setup for building from source. So I'll close this issue - there is nothing else to do here, and the reason for the build-from-source failure has been given.
