### ISSUE TITLE
ImportError on macOS arm64: dynamic module does not define module export function

### ISSUE THREAD

**Issue by arunppsg** [scipy/scipy#17647]
I want to install scipy via pip in an arm64 machine. I did `pip install scipy` and when I ran `import scipy`, I am running into the following error:

```
>>> import scipy
Traceback (most recent call last):
  File "/Users/arun/Applications/venv/pyg/lib/python3.10/site-packages/scipy/__init__.py", line 166, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/Users/arun/Applications/venv/pyg/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dynamic module does not define module export function (PyInit__ccallback_c)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arun/Applications/venv/pyg/lib/python3.10/site-packages/scipy/__init__.py", line 171, in <module>
    raise ImportError(msg) from e
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.
```

Here are additional details: Machine: MacBook Air (M1, 2020), `arch` output: `arm64`, `uname -a` output: `Darwin arun 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64`, numpy version: 1.24.0, output of `import sys; print (sys.version)`: `3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]`, python version: 3.10.8

**Comment by tupui** [comment]
Hi @arunppsg thank you for reporting. Which version of macOS are you on? On m1 only recent versions are supported (Monterey and above). See #15861

**Comment by arunppsg** [comment]
I am on macOS Big Sur. I did a `pip install scipy --verbose` and it built wheel for scipy, create a wheel file named `scipy-1.9.3-cp310-cp310-macosx_11_0_arm64.whl` and installed it. Here are some parts of log which might be relevant:

```
Collecting scipy
  Downloading scipy-1.9.3.tar.gz (42.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 6.1 MB/s eta 0:00:00

# some more log

  The Meson build system
  Version: 0.64.1
  Source dir: /private/var/folders/jx/dw7vjbkj6c90w0c0nfr4r3mh0000gn/T/pip-install-i4cguiwz/scipy_6a3625a1832d4d72bf03790879c408b2
  Build dir: /private/var/folders/jx/dw7vjbkj6c90w0c0nfr4r3mh0000gn/T/pip-install-i4cguiwz/scipy_6a3625a1832d4d72bf03790879c408b2/.mesonpy-pr1i4oyg/build
  Build type: native build
  Project name: SciPy
  Project version: 1.9.3
  C compiler for the host machine: ccache cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
  C linker for the host machine: cc ld64 650.9
  C++ compiler for the host machine: ccache c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
  C++ linker for the host machine: c++ ld64 650.9
  Host machine cpu family: aarch64
  Host machine cpu: aarch64
  Compiler for C supports arguments -Wno-unused-but-set-variable: NO
  Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
  Compiler for C supports arguments -Wno-unused-function: YES
  Compiler for C supports arguments -Wno-conversion: YES
  Compiler for C supports arguments -Wno-misleading-indentation: YES
  Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
  Library m found: YES
  Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
  Fortran linker for the host machine: gfortran ld64 650.9
  Compiler for Fortran supports arguments -Wno-conversion: YES
  Program cython found: YES (/private/var/folders/jx/dw7vjbkj6c90w0c0nfr4r3mh0000gn/T/pip-build-env-n88u9jj0/overlay/bin/cython)
  Program pythran found: YES (/private/var/folders/jx/dw7vjbkj6c90w0c0nfr4r3mh0000gn/T/pip-build-env-n88u9jj0/overlay/bin/pythran)
  Program cp found: YES (/bin/cp)
  Program python found: YES (/Users/arun/Applications/venv/pyg/bin/python3)
  Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
  Run-time dependency threads found: YES
  Library npymath found: YES
  Library npyrandom found: YES
  Found CMake: /usr/local/bin/cmake (3.22.3)
  Run-time dependency openblas found: NO (tried pkgconfig and framework)
  Run-time dependency openblas found: YES 0.3.21
  Dependency openblas found: YES 0.3.21 (cached)

# some more log

Building wheels for collected packages: scipy
  Running command Building wheel for scipy (pyproject.toml)
  Building wheel for scipy (pyproject.toml) ... done
  Created wheel for scipy: filename=scipy-1.9.3-cp310-cp310-macosx_11_0_arm64.whl size=40268671 sha256=3a85258d051ce5aedecac78df2aeda435520c25865d3b375ffb13277ff253077
```

Maybe I will update my macOS version to latest version and try again.

**Comment by arunppsg** [comment]
I also have a noob question: why is some parts of scipy written in fortran? Just trying to understand more about scipy's design. Maybe a pointer to a relevant section in docs will be helpful.

**Comment by rgommers** [comment]
This is perhaps related to symbol hiding (xref gh-15996) somehow. I don't understand how though. I'm not sure that the combination of a new gfortran 12.2.0 from Homebrew plus an old macOS 11 has been tested much. Upgrading to macOS 12 seems like a good idea.

> I also have a noob question: why is some parts of scipy written in fortran? 

There are simply lots of old and well-tested Fortran libraries available, that are used in Fortran. There are no 1:1 C/C++ libraries for them, so replacing them is a lot of work.

**Comment by arunppsg** [comment]
Upgrading to macOS 13 (ventura) fixed the issue. Thanks @rgommers @tupui !
