### ISSUE TITLE
BUG: RegularGridInterpolator does not work on non-native byteorder anymore

### ISSUE THREAD

**Issue by maxnoe** [scipy/scipy#17727]
### Describe your issue.

With the most recent update, applying the `scipy.interpolate.REgularGridInterpolator` using non-native byteorder raises an exception.

This worked in 1.9.

### Reproducing Code Example

```python
import scipy
import numpy as np
from scipy.interpolate import RegularGridInterpolator

print(scipy.__version__)


x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 15)

xg, yg = np.meshgrid(x, y, indexing='ij', sparse=True)

# make values non-native byteorder
values = (2 * xg + yg).astype('>f8')
points = np.array([[0.5, 0.5]])

print(f'{points.dtype = }')
print(f'{values.dtype = }')
print(f'{x.dtype      = }')

interpolator = RegularGridInterpolator((x, y), values)
print(interpolator(points))
```

### Error message

```shell
1.10.0
points.dtype = dtype('float64')
values.dtype = dtype('>f8')
x.dtype      = dtype('float64')
Traceback (most recent call last):
  File "/home/maxnoe/Uni/CTA/ctapipe/test_interp.py", line 22, in <module>
    print(interpolator(points))
  File "/usr/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 336, in __call__
    result = evaluate_linear_2d(self.values,
  File "_rgi_cython.pyx", line 19, in scipy.interpolate._rgi_cython.evaluate_linear_2d
ValueError: Big-endian buffer not supported on little-endian compiler
```

### SciPy/NumPy/Python version information

1.10.0 1.23.5 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
Does https://github.com/scipy/scipy/pull/17717 fix it?

**Comment by maxnoe** [comment]
I didn't test it, but the PR explicitly mentions this error message

**Comment by ev-br** [comment]
If you could actually test it, that would be most helpful.

**Comment by maxnoe** [comment]
The PR actually has a unit test that is basically my example above

**Comment by ev-br** [comment]
OK, I've edited the _closes gh-17727_ incantation to gh-17717. Thanks for double-checking it!
