### ISSUE TITLE
BUG: pip download scipy requires openblas

### ISSUE THREAD

**Issue by XL64** [scipy/scipy#17766]
### Describe your issue.

For my usage I need to use pip download on a machine and then pip install on the target machine with no access to internet.
I can't run pip download on scipy as it requires openblas which is not installed on my machine, is it expected.

### Reproducing Code Example

```python
Run pip download scipy on a machine without openblas
```

### Error message

```shell
python3 -m pip download scipy
Collecting scipy
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /tmp/Python-3.8.5-install/bin/python3 /tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkq7kaw0a
         cwd: /tmp/pip-download-wlya4wbi/scipy
    Complete output (75 lines):
    The Meson build system
    Version: 1.0.0
    Source dir: /tmp/pip-download-wlya4wbi/scipy
    Build dir: /tmp/pip-download-wlya4wbi/scipy/.mesonpy-ip8_p61a/build
    Build type: native build
    Project name: SciPy
    Project version: 1.10.0
    C compiler for the host machine: cc (gcc 8.4.1 "cc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
    C linker for the host machine: cc ld.bfd 2.30-93
    C++ compiler for the host machine: c++ (gcc 8.4.1 "c++ (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
    C++ linker for the host machine: c++ ld.bfd 2.30-93
    Host machine cpu family: ppc64
    Host machine cpu: ppc64le
    Compiler for C supports arguments -Wno-unused-but-set-variable: YES
    Compiler for C supports arguments -Wno-unused-function: YES
    Compiler for C supports arguments -Wno-conversion: YES
    Compiler for C supports arguments -Wno-misleading-indentation: YES
    Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
    Library m found: YES
    Fortran compiler for the host machine: gfortran (gcc 8.4.1 "GNU Fortran (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
    Fortran linker for the host machine: gfortran ld.bfd 2.30-93
    Compiler for Fortran supports arguments -Wno-conversion: YES
    Checking if "-Wl,--version-script" : links: YES
    Program cython found: YES (/tmp/pip-build-env-sgbnggps/overlay/bin/cython)
    Program python found: YES (/tmp/Python-3.8.5-install/bin/python3)
    Found pkg-config: /usr/bin/pkg-config (1.4.2)
    Program pythran found: YES (/tmp/pip-build-env-sgbnggps/overlay/bin/pythran)
    Run-time dependency threads found: YES
    Library npymath found: YES
    Library npyrandom found: YES
    Found CMake: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel7-power8le/gcc-4.8.5/cmake-3.21.4-t2lf7jyc3qc3wkhc7mf4ska7akugi3ko/bin/cmake (3.21.4)
    Run-time dependency openblas found: NO (tried pkgconfig and cmake)
    Run-time dependency openblas found: NO (tried pkgconfig and cmake)

    ../../scipy/meson.build:134:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake

    A full log can be found at /tmp/pip-download-wlya4wbi/scipy/.mesonpy-ip8_p61a/build/meson-logs/meson-log.txt
    + meson setup --prefix=/tmp/Python-3.8.5-install /tmp/pip-download-wlya4wbi/scipy /tmp/pip-download-wlya4wbi/scipy/.mesonpy-ip8_p61a/build --native-file=/tmp/pip-download-wlya4wbi/scipy/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
    Traceback (most recent call last):
      File "/tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
        with _project(config_settings) as project:
      File "/tmp/Python-3.8.5-install/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 975, in _project
        with Project.with_temp_working_dir(
      File "/tmp/Python-3.8.5-install/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
        yield cls(source_dir, tmpdir, build_dir, meson_args)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 632, in __init__
        self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 680, in _configure
        self._meson('setup', *setup_args)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 657, in _meson
        return self._proc('meson', *args)
      File "/tmp/pip-build-env-sgbnggps/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 652, in _proc
        subprocess.check_call(list(args), env=self._env)
      File "/tmp/Python-3.8.5-install/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/tmp/Python-3.8.5-install', '/tmp/pip-download-wlya4wbi/scipy', '/tmp/pip-download-wlya4wbi/scipy/.mesonpy-ip8_p61a/build', '--native-file=/tmp/pip-download-wlya4wbi/scipy/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/Python-3.8.5-install/bin/python3 /tmp/Python-3.8.5-install/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkq7kaw0a Check the logs for full command output.
```

### SciPy/NumPy/Python version information

Any/Any/3.8.5

**Comment by ilayn** [comment]
If you need an offline install two options are either use the wheels if compatible wheel exists or you build scipy yourself. For the latter you need bunch of dependencies present in the machine to build it. pip download won't give you a productive way of working for that goal. See https://docs.scipy.org/doc/scipy/dev/contributor/building.html and relevant parts

**Comment by andyfaff** [comment]
I'm guessing you're on a cluster. Besides following @ilayn instructions, it seems like you have spack installed. Could you try installing scipy with spack, is the python you're using provided by spack?

**Comment by rgommers** [comment]
The answers here seem sufficient. gh-17743 updates the build instructions. Things should work once OpenBLAS is installed. Or use Spack to install SciPy (package is named `py-scipy` in Spack) indeed.

I'll close this, since there is no bug and nothing more to fix on our side. Please feel free to ask follow up questions of course @XL64.
