### ISSUE TITLE
BUG: Erratic results from RectBivariateSpline when smoothing large arrays

### ISSUE THREAD

**Issue by loicseguin** [scipy/scipy#17787]
### Describe your issue.

According to the documentation, RectBivariateSpline can be used for smoothing by setting `s` to a non zero value. This works on small grids, but on larger grids, using any `s` value other than zero produces a spline that evaluates to NaN everywhere. To be clear, this occurs on data that do not contain any NaN. The problem occurs without any warning or error message. The problem occurs irregularly (running the code sometimes work, but most of the time it does not).

The problem occurs on grid with dtype int as well as float.

The problem occurs on Windows 10 and mac OS.

Since the problem does not alway occur, I suspect it may be due to a failure to allocate memory. If enough memory is available, everything works fine. However, it the memory allocation fails, RectBivariateSpline returns a nonsensical result without informing the user about the memory error.

### Reproducing Code Example

```python
import numpy as np
from scipy import interpolate

s = 1  # any value greater than zero causes the problem
nx, ny = 1000, 1700    # Set to larger values to reproduce the problem more consistently
img = np.random.randint(0, 100, size=(nx, ny))
x = np.arange(nx)
y = np.arange(ny)
spl = interpolate.RectBivariateSpline(x, y, img, s=s)
print(np.isnan(spl(x, y)).any())
```

### Error message

```shell
No error message
```

### SciPy/NumPy/Python version information

1.9.3 1.23.5 sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)

1.10.0 1.24.1 sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
Confirmed on linux, with an older scipy. So the issue is there "forever". Hmm. 
Any chance you are set up to step it in gdb to see where the nans start creeping in?

**Comment by ev-br** [comment]
Took a quick look to see if it's not fixed by gh-17212. Of course it is not. 

In the OP, nans appear in the spline coefficients which are computed here: https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack2.py#L1599 

so in the OP the last line can be simplified to `assert np.isnan( spl.tck[2] ).any()`

The offending line in RectBivariateSpline calls into the f2py-d `regrid` routine, which itself delegates to `fpregr`
https://github.com/scipy/scipy/blob/main/scipy/interpolate/fitpack/regrid.f#L348

Now, the `c` array is OK before entering `fpregr` and is full of NaNs on exit. So ISTM, the problem is somewhere in `fpregr`. To make progress, I'd first try to build scipy Fortran with `-g -fbounds-check` to see if we're lucky and it's a simple OOB.

However, I did not manage to add a command line switch to the build --- IIRC it used to react to the FOPT env variable, but it does not seem to now. Will ping @rgommers for a build advice.

**Comment by rgommers** [comment]
> However, I did not manage to add a command line switch to the build --- IIRC it used to react to the FOPT env variable, but it does not seem to now. Will ping @rgommers for a build advice.

`FFLAGS` will work. Meson only supports bog-standard env vars and prefer command line switches for everything else. And it comes with docs even:) https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables

Note though that env vars only works from a clean build, because they affect the configure stage (i.e., `meson setup`) and not a partial rebuild. So you can either `git clean -xdf` and set the env vars you want, or alternatively you can edit the relevant `meson.build` entry and add `fortran_args: -fbounds-check` temporarily.

Note that `-g` is never needed, that's already the default in `dev.py` and in general is controlled via setting the build type: https://mesonbuild.com/Builtin-options.html#details-for-buildtype.

**Comment by rgommers** [comment]
> I think this would be nice to add to some building from source docs. Not necessarily the Fortran info, may be similar info for more popular languages :-).

This is in the plan already:)

**Comment by ev-br** [comment]
A quick note so far: nans start appearing around this line https://github.com/scipy/scipy/blob/v1.3.0/scipy/interpolate/fitpack/fpgrre.f#L262

when `nx == nxe`, the maximum allowed number of knots in the x direction.

**Comment by nepomnyi** [comment]
Hello, dear SciPy team.
I understand you're very busy and I am grateful for your time spent on maintaining SciPy. In our package used for particle image velocimetry[ OpenPIV, we employ RectBivariateSpline](https://github.com/OpenPIV/openpiv-python/blob/master/openpiv/windef.py). Recently, my custom code that makes heavy use of OpenPIV started stopping randomly without any error. It might be a memory leak. I traced back the issue to the implementation of RectBivariateSpline (see lines 690 and 693 in the provided link). I don't know how to troubleshoot it further, but I guess my issue might be related to the current discussion. With that in mind, I am wondering if you can be so kind to update me on the state of resolving the issue in the current discussion, please. I updated my SciPy to v1.14.1 and it still, presumably, leaks memory.

**Comment by ev-br** [comment]
There was no recent changes in or around RectBivariateSpline. 
git blame concurs: https://github.com/scipy/scipy/blame/v1.14.1/scipy/interpolate/_fitpack2.py#L1526-L1611

**Comment by czgdp1807** [comment]
Hi folks. I am able to reproduce the error on my macOS and that too on repeated runs,

```zsh
(scipy-dev) 21:18:08:~/Quansight/scipy % python dev.py --no-build python ../debug.py
Skipping build
True
(scipy-dev) 21:18:10:~/Quansight/scipy % python dev.py --no-build python ../debug.py
Skipping build
True
(scipy-dev) 21:18:12:~/Quansight/scipy % python dev.py --no-build python ../debug.py
Skipping build
True
```

I will investigate further.

**Comment by czgdp1807** [comment]
I investigated this issue. My preliminary conclusion is that it's not a memory issue. One of the reasons is denominator becoming 0.0 in a division operation. Following is the code path,

The call starts from here,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/_fitpack2.py#L1631-L1632

and then to,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/fitpack/regrid.f#L348-L351

and then to,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/fitpack/fpregr.f#L214-L217

and then to,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/fitpack/fpgrre.f#L263

and finally inside `fpback` subroutine as soon as one of `a(i, 1)` or `a(n, 1)` becomes `0`, `c(n)` or `c(i)` becomes `NaN` in the following lines,

`a(n, 1)` becoming `0.0` causes `c(n)` to become `NaN`,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/fitpack/fpback.f#L16

and similarly, `a(i, 1)` becoming `0.0` causes `c(i)` to become `NaN`,

https://github.com/scipy/scipy/blob/e9722d427f1d2d42c2b77f2eb799983b310ac9bd/scipy/interpolate/fitpack/fpback.f#L28

I applied the following diff to SciPy,

```diff
diff --git a/scipy/interpolate/fitpack/fpback.f b/scipy/interpolate/fitpack/fpback.f
index 093cc7e43..fea5f0ff6 100644
--- a/scipy/interpolate/fitpack/fpback.f
+++ b/scipy/interpolate/fitpack/fpback.f
@@ -13,6 +13,9 @@ c  ..local scalars..
       integer i,i1,j,k1,l,m
 c  ..
       k1 = k-1
+      if( a(n, 1) == 0 ) then
+            a(n, 1) = epsilon(0.0_8)
+      end if
       c(n) = z(n)/a(n,1)
       i = n-1
       if(i.eq.0) go to 30
@@ -25,6 +28,9 @@ c  ..
           m = m+1
           store = store-c(m)*a(i,l+1)
   10    continue
+        if( a(i, 1) == 0 ) then
+            a(i, 1) = epsilon(0.0_8)
+        end if
         c(i) = store/a(i,1)
         i = i-1
   20  continue
```

and, then I get the following output on the reproducer code of this issue,

```zsh
(scipy-dev) 19:31:47:~/Quansight/scipy % python dev.py python ../debug.py
False
(scipy-dev) 19:32:03:~/Quansight/scipy % python dev.py python ../debug.py
True
(scipy-dev) 19:32:22:~/Quansight/scipy % python dev.py python ../debug.py
True
(scipy-dev) 19:32:30:~/Quansight/scipy % python dev.py python ../debug.py
False
```

It becomes flaky. :-). Before my diff, it was always True because `a(i, 1)` and `a(n, 1)` were always becoming 0.0.

IMO, we should stop when we discover that division operation is not possible because denominator is 0.0. There must be an option in GFortran to raise a runtime error in this case.

**Comment by ev-br** [comment]
Well, the next question is of course why there's a zero. `fpback` is a backsubstitution solve of a linear system with the triangular l.h.s. The triangular matrix itself comes from a QR factorization least-squares. This might mean one of two things: 1) either the LSQ problem is rank-deficient and needs a pivoted QR, or 2) there's an off-by-one type error somewhere.
Since the whole procedure is bespoke and all matrices are built in the code, I'd suspect the second one. The fact that it only happens when `nx == nxe` (https://github.com/scipy/scipy/issues/17787#issuecomment-2299287077) is a lead.

**Comment by czgdp1807** [comment]
I see. Thanks for the idea. So I think the problem is that the position of the following check is wrong (IMO),

https://github.com/scipy/scipy/blob/243b305c3c767b524d8a23d580152b3b877f9b18/scipy/interpolate/fitpack/fpregr.f#L227-L230

It happens too late. It happens after the following check,

https://github.com/scipy/scipy/blob/243b305c3c767b524d8a23d580152b3b877f9b18/scipy/interpolate/fitpack/fpregr.f#L225-L226

which becomes `true` and the space issue is never detected. I think `if(nx.eq.nxe .and. ny.eq.nye) go to 420` should be right after the call to `fpgrre` (see call below),

https://github.com/scipy/scipy/blob/243b305c3c767b524d8a23d580152b3b877f9b18/scipy/interpolate/fitpack/fpregr.f#L214-L217

The reason being space issue should be detected at the earliest. I applied the following diff,

```diff
diff --git a/scipy/interpolate/fitpack/fpregr.f b/scipy/interpolate/fitpack/fpregr.f
index e43726d28..857b24b74 100644
--- a/scipy/interpolate/fitpack/fpregr.f
+++ b/scipy/interpolate/fitpack/fpregr.f
@@ -215,6 +215,9 @@ c  fp gives the total sum of squared residuals.
      *  ny,p,c,nc,fp,fpintx,fpinty,mm,mynx,kx1,kx2,ky1,ky2,wrk(lsx),
      *  wrk(lsy),wrk(lri),wrk(lq),wrk(lax),wrk(lay),wrk(lbx),wrk(lby),
      *  nrx,nry)
+c  if nx=nxe and ny=nye we cannot further increase the number of knots
+c  because of the storage capacity limitation.
+        if(nx.eq.nxe .and. ny.eq.nye) go to 420
         if(ier.eq.(-2)) fp0 = fp
 c  test whether the least-squares spline is an acceptable solution.
         if(iopt.lt.0) go to 440
@@ -225,9 +228,6 @@ c  if f(p=inf) < s, we accept the choice of knots.
 c  if nx=nmaxx and ny=nmaxy, sinf(x,y) is an interpolating spline.
         if(nx.eq.nmaxx .and. ny.eq.nmaxy) go to 430
 c  increase the number of knots.
-c  if nx=nxe and ny=nye we cannot further increase the number of knots
-c  because of the storage capacity limitation.
-        if(nx.eq.nxe .and. ny.eq.nye) go to 420
         ier = 0
 c  adjust the parameter reducx or reducy according to the direction
 c  in which the last added knots were located.
@@ -365,4 +365,3 @@ c  error codes and messages.
       fp = 0.
  440  return
       end
-
```

and then I see a memory related `ValueError` (should be `MemoryError` instead),

```zsh
Traceback (most recent call last):
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1740, in <module>
    cli()
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/pydevtool/cli.py", line 271, in callback
    sys.exit(cls.run(**kwargs))
             ^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1395, in run
    exec(script, ns)
  File "<string>", line 9, in <module>
  File "/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py", line 1636, in __init__
    raise ValueError(msg)
ValueError: 
The required storage space exceeds the available storage space: nxest
or nyest too small, or s too small.
The weighted least-squares spline corresponds to the current set of
knots.
```

However, with the above `diff`, other tests also give the same `ValueError`. Probably this check isn't good enough to detect space issues?

**Comment by czgdp1807** [comment]
In fact, the following diff also gives memory error false positively for SciPy tests,

```diff
diff --git a/scipy/interpolate/fitpack/fpregr.f b/scipy/interpolate/fitpack/fpregr.f
index e43726d28..198b0276e 100644
--- a/scipy/interpolate/fitpack/fpregr.f
+++ b/scipy/interpolate/fitpack/fpregr.f
@@ -215,6 +215,8 @@ c  fp gives the total sum of squared residuals.
      *  ny,p,c,nc,fp,fpintx,fpinty,mm,mynx,kx1,kx2,ky1,ky2,wrk(lsx),
      *  wrk(lsy),wrk(lri),wrk(lq),wrk(lax),wrk(lay),wrk(lbx),wrk(lby),
      *  nrx,nry)
+        if(nx.eq.nmaxx .and. nx.eq.nxest .and.
+     *     ny.eq.nmaxy .and. ny.eq.nyest) go to 420
         if(ier.eq.(-2)) fp0 = fp
 c  test whether the least-squares spline is an acceptable solution.
         if(iopt.lt.0) go to 440
@@ -365,4 +367,3 @@ c  error codes and messages.
       fp = 0.
  440  return
       end
-
```

**Comment by czgdp1807** [comment]
For now, I can do the following,

```diff
(scipy-dev) 10:25:57:~/Quansight/scipy % git diff scipy/interpolate/fitpack/fpregr.f
diff --git a/scipy/interpolate/fitpack/fpregr.f b/scipy/interpolate/fitpack/fpregr.f
index e43726d28..d1fc48719 100644
--- a/scipy/interpolate/fitpack/fpregr.f
+++ b/scipy/interpolate/fitpack/fpregr.f
@@ -215,6 +215,7 @@ c  fp gives the total sum of squared residuals.
      *  ny,p,c,nc,fp,fpintx,fpinty,mm,mynx,kx1,kx2,ky1,ky2,wrk(lsx),
      *  wrk(lsy),wrk(lri),wrk(lq),wrk(lax),wrk(lay),wrk(lbx),wrk(lby),
      *  nrx,nry)
+        if( any(isnan(c)) .and. nx.eq.nxe .and. ny.eq.nye ) goto 420
         if(ier.eq.(-2)) fp0 = fp
 c  test whether the least-squares spline is an acceptable solution.
         if(iopt.lt.0) go to 440
@@ -365,4 +366,3 @@ c  error codes and messages.
       fp = 0.
  440  return
       end
-
```

As soon as we detect `NaN` and the space condition is `true`, then set `ier` to `1`. With this the tests pass (no false positives for space shortage error).

**Comment by ev-br** [comment]
Checking locally with the patch from https://github.com/scipy/scipy/issues/17787#issuecomment-2565026701, the OP example fails with a legible ValueError, so it's an improvement: 

```
ValueError: 
The required storage space exceeds the available storage space: nxest
or nyest too small, or s too small.
The weighted least-squares spline corresponds to the current set of
knots.
```

The error message is somewhat helpful in that increasing `s` to 1e9 or more does return some result.  

All that said, I think it would be great to try finding the cause (the patch basically treats the symptoms).

Changing to `s=0` in the OP does return a result, so it's not that the Fortran code cannot handle `(nx == nxe).and.(ny == nye)` at all. 

So I'd suggest to trace the difference between `s=0` and `s > 0` code paths to see  
1) what is the difference between the failing (s>0) and not failing cases (s=0, interpolation) 
2) in the failing case, what is the cause for the division by zero, where do these zeros come from?

**Comment by czgdp1807** [comment]
Correct. `s = 0` works, `s = 1e9` works but `s = 1` doesn't. So probably its more about tuning `s`. I will resume my work on this and see what is the difference between code paths taken by `s = 0` and `s = 1`.

**Comment by czgdp1807** [comment]
I did some more investigation, the difference between `s = 0` and `s > 0` is case is the following piece of code,

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpregr.f#L83-L126

The above code executed (if `s = 0`, see `if(s.gt.0.) go to 100`)). If I comment out `if(s.gt.0.) go to 100` then the above code is always executed and the tests also pass. In addition, `s = 0` and `s = 1` both produce non-NaN values in the output. However then `s = 1e9` (basically very large values of `s` don't work). The following error is produced,

```zsh
A theoretically impossible result was found during the iteration
process for finding a smoothing spline with fp = s: s too small or
badly chosen eps.
Weighted sum of squared residuals does not satisfy abs(fp-s)/s < tol.
```

Also, I noticed that with the following line commented out,

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpregr.f#L83

If I increase `s` the absolute difference (sort of error?)  between `img` and `spl(x, y)` increases, which makes sense to me, because according to the documentation, `sum((z[i]-f(x[i], y[i]))**2, axis=0) <= s` so larger `s` means the condition will become true earlier and so the algorithm will terminate early. With `s = 0`, `img` and `spl(x, y)` are exactly same.

Am I making sense @ev-br ?

Here's the code,

```python
import numpy as np
from scipy import interpolate
import sys

s = int(sys.argv[1])  # any value greater than zero causes the problem
kx = int(sys.argv[2])
ky = int(sys.argv[3])
nx, ny = 1000, 1700    # Set to larger values to reproduce the problem more consistently
img = np.random.randint(0, 100, size=(nx, ny))
x = np.arange(nx)
y = np.arange(ny)
spl = interpolate.RectBivariateSpline(x, y, img, s=s, kx=kx, ky=ky)
print(np.max(np.abs(img - spl(x, y))))
```

I input, `s`, `kx` and `ky`.

The diff applied on `main` branch,

```diff
diff --git a/scipy/interpolate/fitpack/fpregr.f b/scipy/interpolate/fitpack/fpregr.f
index e43726d28..cb3ecea5e 100644
--- a/scipy/interpolate/fitpack/fpregr.f
+++ b/scipy/interpolate/fitpack/fpregr.f
@@ -80,7 +80,7 @@ c  find nxe and nye which denote the maximum number of knots
 c  allowed in each direction
       nxe = min0(nmaxx,nxest)
       nye = min0(nmaxy,nyest)
-      if(s.gt.0.) go to 100
+      !if(s.gt.0.) go to 100
 c  if s = 0, s(x,y) is an interpolating spline.
       nx = nmaxx
       ny = nmaxy
@@ -365,4 +365,3 @@ c  error codes and messages.
       fp = 0.
  440  return
       end
-
```

Output patterns,

```zsh
(scipy-dev) 20:45:04:~/Quansight/scipy % python dev.py python ../debug.py 0 3 3
8.526512829121202e-14
(scipy-dev) 20:45:13:~/Quansight/scipy % python dev.py python ../debug.py 1 3 3
0.0030084379485373347
(scipy-dev) 20:45:20:~/Quansight/scipy % python dev.py python ../debug.py 2 3 3
Traceback (most recent call last):
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1740, in <module>
    cli()
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/pydevtool/cli.py", line 271, in callback
    sys.exit(cls.run(**kwargs))
             ^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1395, in run
    exec(script, ns)
  File "<string>", line 12, in <module>
  File "/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py", line 1636, in __init__
    raise ValueError(msg)
ValueError: 
the maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached:
s too small.
Weighted sum of squared residuals does not satisfy abs(fp-s)/s < tol.
(scipy-dev) 20:45:27:~/Quansight/scipy % python dev.py python ../debug.py 3 3 3
0.005548244087075993
(scipy-dev) 20:45:34:~/Quansight/scipy % python dev.py python ../debug.py 2 4 4
0.004557346935598616
(scipy-dev) 20:45:43:~/Quansight/scipy % python dev.py python ../debug.py 4 3 3
0.005971085224657946
(scipy-dev) 20:46:02:~/Quansight/scipy % python dev.py python ../debug.py 10000000000 3 3
Traceback (most recent call last):
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1740, in <module>
    cli()
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/pydevtool/cli.py", line 271, in callback
    sys.exit(cls.run(**kwargs))
             ^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1395, in run
    exec(script, ns)
  File "<string>", line 12, in <module>
  File "/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py", line 1636, in __init__
    raise ValueError(msg)
ValueError: 
A theoretically impossible result was found during the iteration
process for finding a smoothing spline with fp = s: s too small or
badly chosen eps.
Weighted sum of squared residuals does not satisfy abs(fp-s)/s < tol.
```

I am a bit surprised with `s = 2` and `kx = 3` and `ky = 3`, it gives `ValueError`. However, with `s = 0` the output is very small, which means that `spl` exactly fits the `img`, right?

**Comment by czgdp1807** [comment]
So when I was discussing with @ev-br he mentioned about 1D analog of the interpolation algorithm. I went to, `scipy/interpolate/fitpack/fpcurf.f` and observed the following, 

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpcurf.f#L218-L222

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpcurf.f#L64

Notice, `if(n.eq.nmax) go to 10` in the first snippet. In 1D implementation, it goes to `mk1 = m-k1` if `n` reaches `nmax` (maximum nots I guess).

Now see, 2D case,

For `x`,

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpregr.f#L267-L270

For `y`,

https://github.com/scipy/scipy/blob/2299d44490067ec50ca144987e16bb2b7597f462/scipy/interpolate/fitpack/fpregr.f#L280-L283

There is no check for `if(nx.eq.nmaxx)` and `if(ny.eq.nmaxy)`. I added the same in the following diff,

```diff
diff --git a/scipy/interpolate/fitpack/fpregr.f b/scipy/interpolate/fitpack/fpregr.f
index e43726d28..12c6cdca5 100644
--- a/scipy/interpolate/fitpack/fpregr.f
+++ b/scipy/interpolate/fitpack/fpregr.f
@@ -88,7 +88,7 @@ c  test whether the required storage space exceeds the available one.
       if(ny.gt.nyest .or. nx.gt.nxest) go to 420
 c  find the position of the interior knots in case of interpolation.
 c  the knots in the x-direction.
-      mk1 = mx-kx1
+  10  mk1 = mx-kx1
       if(mk1.eq.0) go to 60
       k3 = kx/2
       i = kx1+1
@@ -267,6 +267,7 @@ c  add a new knot in the x-direction
           call fpknot(x,mx,tx,nx,fpintx,nrdatx,nrintx,nxest,1)
 c  test whether we cannot further increase the number of knots in the
 c  x-direction.
+          if(nx.eq.nmaxx) go to 10
           if(nx.eq.nxe) go to 250
  220    continue
         go to 250
@@ -280,6 +281,7 @@ c  add a new knot in the y-direction.
           call fpknot(y,my,ty,ny,fpinty,nrdaty,nrinty,nyest,1)
 c  test whether we cannot further increase the number of knots in the
 c  y-direction.
+          if(ny.eq.nmaxy) go to 60
           if(ny.eq.nye) go to 250
  240    continue
 c  restart the computations with the new set of knots.
@@ -365,4 +367,3 @@ c  error codes and messages.
       fp = 0.
  440  return
       end
-
```

and the results are as follows,

Code

```python
import numpy as np
from scipy import interpolate
import sys

s = int(sys.argv[1])  # any value greater than zero causes the problem
nx, ny = 1000, 1700    # Set to larger values to reproduce the problem more consistently
img = np.random.randint(0, 100, size=(nx, ny))
x = np.arange(nx)
y = np.arange(ny)
spl = interpolate.RectBivariateSpline(x, y, img, s=s)
print(np.max(np.abs(img - spl(x, y))))
print(np.isnan(spl(x, y)).any())
```

```zsh
(scipy-dev) 22:39:37:~/Quansight/scipy % python dev.py python ../debug.py 0
8.526512829121202e-14
False
(scipy-dev) 22:39:42:~/Quansight/scipy % python dev.py python ../debug.py 1
0.003062541946125208
False
(scipy-dev) 22:39:49:~/Quansight/scipy % python dev.py python ../debug.py 2
Traceback (most recent call last):
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1740, in <module>
    cli()
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/site-packages/pydevtool/cli.py", line 271, in callback
    sys.exit(cls.run(**kwargs))
             ^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/Quansight/scipy/dev.py", line 1395, in run
    exec(script, ns)
  File "<string>", line 10, in <module>
  File "/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py", line 1636, in __init__
    raise ValueError(msg)
ValueError: 
the maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached:
s too small.
Weighted sum of squared residuals does not satisfy abs(fp-s)/s < tol.
(scipy-dev) 22:39:56:~/Quansight/scipy % python dev.py python ../debug.py 3
0.005477170369213398
False
(scipy-dev) 22:40:08:~/Quansight/scipy % python dev.py python ../debug.py 1000000000
88.17913887265436
False
```

Not sure, why `s = 2` errors, but there is no NaN output with any `s` value. @ev-br Does my reasoning make sense to you?

**Comment by ev-br** [comment]
Makes sort of sense but that's not the final answer still.
The ValueError is reasonable: s is too small. However it's a bit worrying that s=1 gives some answer and s=2 does not. Normally I'd expect that it errors our of s is too small, and returns some result for larger values of s.
This behavior seems to hint that your fix still papers over the underlying issue.
 
The patch also looks a tad strange with wildly different code flow for `nx == nmaxx` and `nx == nxe`. Given that `nmaxx` and `nxe` are most likely equal to each other, it's very much not clear what is the effect of the control flow change. 

I still think it's worth figuring out what actually triggers the problem.
