### ISSUE TITLE
BUG: inconsistent checks for integrality in several distributions

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#17891]
In the infrastructure for discrete distributions, we have a [check](https://github.com/scipy/scipy/blob/v1.10.0/scipy/stats/_discrete_distns.py#L25-L26) whether certain parameters are integral, which gets used in 6 distributions:
* binom
* betabinom
* boltzmann
* hypergeom
* nhypergeom
* randint

This check explicitly lets floats pass that are just integers in disguise, i.e. `_isintegral(1.0) == True`. However, those values are then propagated to underlying and _typed_ methods that barf on floats, for (the respective parameters of) all the above distributions, leading to very unintuitive error-messages.

```
>>> import scipy.stats
>>> scipy.stats.binom.rvs(1.0, 0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/[xxx]/.conda/envs/scipy_env/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 3357, in rvs
    return super().rvs(*args, **kwargs)
  File "/home/[xxx]/.conda/envs/scipy_env/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 1048, in rvs
    vals = self._rvs(*args, size=size, random_state=random_state)
  File "/home/[xxx]/.conda/envs/scipy_env/lib/python3.9/site-packages/scipy/stats/_discrete_distns.py", line 62, in _rvs
    return random_state.binomial(n, p, size)
  File "mtrand.pyx", line 3439, in numpy.random.mtrand.RandomState.binomial
TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
>>> scipy.__version__
'1.10.0'
>>> numpy.__version__
'1.24.1'
```

I think we should keep the integrality checks as-is, but cast those parameters to integers as appropriate. It's not 100% obvious to me how this should be handled in the context of the dist infrastructure, which calls `_argcheck` in several places, but doesn't have capabilities to signal that certain parameters now should be cast to integers.

Still, I could imagine a similar private method `_cast_params(*args)`, which would get called _after_ each invocation to `_argcheck` in [`_distn_infrastructure.py`](https://github.com/scipy/scipy/blob/main/scipy/stats/_distn_infrastructure.py), and that could be overridden by each distribution as necessary (just as they're already overriding `_argcheck`).

**Comment by mdhaber** [comment]
> It's not 100% obvious to me how this should be handled in the context of the dist infrastructure

Personally, I'd prefer to wait for the resolution of gh-15928 as part of [this project](https://chanzuckerberg.com/eoss/proposals/scipy-fundamental-tools-for-biomedical-research/); I'd rather not fix it twice.

It's a little surprising that NumPy `RandomState` and `Generator` are happy to accept scalar floats:
```python3
import numpy as np
np.random.binomial(10.0, 0.5)  # OK
rng = np.random.default_rng()
rng.binomial(10.0, 0.5)  # OK
# and even
np.random.binomial(np.float64(10.1), 0.5)  # OK
rng.binomial(np.float64(10.1), 0.5)  # OK
```
but float arrays are not OK:
```python3
np.random.binomial(np.array(10.0), 0.5)  # TypeError: Cannot cast scalar from dtype('float64') to dtype('int32') according to the rule 'safe'
rng.binomial(np.array([10.0]), 0.5)  # TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
```

AFAICT, all shape parameters have been turned into arrays for at least a decade, so I think this issue has been present for a while, and while the error message could certainly be improved or eliminated, it can also be interpreted (one of the arguments to `random_state.binomial` - `n`, `p`, or `size` - is a `float64` when it needs to be an `int32`) - I've seen worse! With that in mind, do you think we can wait for gh-15928 to resolve this?

**Comment by rgommers** [comment]
> This check explicitly lets floats pass that are just integers in disguise, i.e. `_isintegral(1.0) == True`.

It'd be good to get rid of this at some point. It's the kind of design decision that always comes back to bite you. If we need integers, accept only integers.

**Comment by h-vetinari** [comment]
> @rgommers: It's the kind of design decision that always comes back to bite you.

Not sure I agree in this case. The dist infrastructure intentionally templates over (univariate) distributions, with very minor differences between continuous and discrete ones (i.e. presence of `scale=` kwarg). That makes it feasible to use that flexibility elsewhere, e.g. have a mechanism that allows a user to control the distribution in use for a given app/calculation by name. Say:

```python
import scipy.stats
def scipy_dist_wrapper(dist_name, *args, **kwargs):
    if dist_name not in allowlist:
        raise ValueError(f"scipy.stats does not have distribution {dist_name}")
    dist_funct = getattr(scipy.stats, dist_name)
    result = dist_func(*args, **kwargs)
```
This is just a dummy for the sake of argument (in reality that wrapper would have a bunch more things to do), but the value of generically specifying the distribution should be understandable I hope? Such a kind of interface would get _a lot_ harder (or more brittle) if you now need to cast certain parameters for certain distributions to integers.

> @rgommers: If we need integers, accept only integers.

I get that the current infrastructure isn't necessarily made for it, but once we've assured `_isintegral(x)`, we could just as well cast. It's certainly more user-friendly, because floats just creep in at so many different points in the course of handling (what should be) an integer in python.

> @mdhaber: With that in mind, do you think we can wait for [gh-15928](https://github.com/scipy/scipy/issues/15928) to resolve this?

In general: of course. Though it's not clear to me from https://github.com/scipy/scipy/issues/15928 what the status is there. Has the project started? Is there an approximate timeline? I have a pretty non-invasive patch in mind to fix this, but I don't mind waiting if the dist infra overhaul arrives in the next 1-2 releases.

**Comment by mdhaber** [comment]
> It'd be good to get rid of this at some point.

The integer check was added relatively recently as a resolution to gh-2414, which was migrated from Trac. Before gh-15769, some distributions produced garbage if a non-integral value was passed as a shape parameter. Five stats maintainers participated in the decision, a compromise between backward compatibility and not continuing to produce incorrect results. I can see being even more restrictive (accepting only integer types) when we have the opportunity to start fresh, but I don't think this patch was wrong.

> Has the project started? Is there an approximate timeline?

There are many other things in the queue, like all issues and PRs that come in, but I expect to start focusing on it during the summer.

That said, if your solution can be described as non-invasive, I'd consider reviewing it. If it's as simple as doing dtype conversions just in the methods that need it, that might be ok (even if it's a bit verbose). I hesitate to touch deeper things like changing the behavior of `_argcheck` at the infrastructure level.

**Comment by h-vetinari** [comment]
Thanks @mdhaber @steppi et al.! Quick double-check: this issue lists several distributions, whereas #22312 seems to deal mostly with `stats.Binomial` - have all the other places been fixed, or would you just like to close this in the sense of "we've decided how to handle this case, and it'll be fixed automatically as distributions are converted to the new infrastructure"?

**Comment by mdhaber** [comment]
Yup, the latter. I don't think we'll actually fix the old code, but that will eventually be obsolete.
