### ISSUE TITLE
BUG: ImportError: DLL load failed while importing _ufuncs: %1 is not a valid Win32 applic

### ISSUE THREAD

**Issue by anantshukla** [scipy/scipy#17978]
### Describe your issue.

Python Version: Python 3.11.2
OS: Windows 11
SciPy version: 1.10.0
Distribution: pip (Conda not installed on the system)
Environment: Isolated virtual environment with no deps on host python.

I get the import DLL error every time I execute my python code. This issue started when I re-formatted my laptop and installed the latest SciPy and Python version.
If I pip uninstall SciPy, I can execute my code once. As soon as my second execution takes place, I get the same error again.

My best guess is there is an issue with version compatibility.
Are there any suggestions?

### Reproducing Code Example

```python
from scipy.interpolate import interp1d
```

### Error message

```shell
Traceback (most recent call last):
  File "E:\test_proj\doubleIntegration.py", line 4, in <module>
    from scipy.interpolate import interp1d
  File "E:\test_proj\venv\Lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
  File "E:\test_proj\venv\Lib\site-packages\scipy\interpolate\_interpolate.py", line 8, in <module>                    import scipy.special as spec
  File "E:\test_proj\venv\Lib\site-packages\scipy\special\__init__.py", line 663, in <module>                        from . import _ufuncs
ImportError: DLL load failed while importing _ufuncs: %1 is not a valid Win32 application.
```

### SciPy/NumPy/Python version information

1.10.0 1.24.2 sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)

**Comment by anantshukla** [comment]
Hi, I tried almost everything, but this issue still persists. Probably the next step for me is to downgrade to Py 3.9 and previous release of SciPy where I didn't have the issue. 

Are there any known issues that could be triggering the DLL to get deleted after the execution of a SciPy code? Any suggestions?

**Comment by Filthy999** [comment]
Same thing happening for me after a fresh windows 11 install. Scipy will import the first time it is run after installing. But every subsequent run results in 

ImportError: DLL load failed while importing _iterative: %1 is not a valid Win32 application.

Various combinations of python and scipy have not solved anything.

**Comment by andyfaff** [comment]
I've just tried installing scipy into a 3.11 conda env on Windows 10. Importing `scipy.interpolate` worked. 
These kinds of errors can come from a range of things.
@anantshukla can you:

- look in `E:\test_proj\venv\Lib\site-packages\scipy`, or in `site-packages` and tell me if you see a `scipy.libs` directory?  What is the contents of that directory?

- Does `scipy-1.9.3` work? (both scipy-1.10.0 and 1.9.3 were made with the same cibuildwheel infrastructure and I'm trying to see if that's an issue).

- does it make a difference if you install the Microsoft VC redistributable package, https://aka.ms/vs/17/release/vc_redist.x64.exe?  (link from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

It's going to be hard to solve this issue unless the devs can replicate it locally.

**Comment by Filthy999** [comment]
This seems to me very likely to be related to a recent windows update as both me and anantshukla experienced it after a fresh windows 11 install. And I'd suggest trying to reproduce would probably have to start from there. (Or maybe just making sure windows 11 all updates are installed)

Scipy version seems to be irrelevant. It fails for 1.9.2 (the oldest scipy I can easily install) to 1.10.0.

scipy.libs folder:
![image](https://user-images.githubusercontent.com/15950879/219940006-abb5a995-8d63-4ba8-bc09-13214171f6c0.png)

Both scipy and scipy.libs folders do not appear to change at all from before the first successful import, to after the first successful import, to after the first unsuccessful import.

VC redistributable package install has no effect.

The error appears to happen after python is invoked for 2nd time onwards, regardless of what you do the first time you invoke python the first time. So:

```
pip uninstall scipy
pip install scipy
python
import scipy.stats
from scipy import interpolate
quit()
python
import scipy.stats
```

Both imports in the first invocation of python succeed. Import in second invocation of python fail.

```
pip uninstall scipy
pip install scipy
python
quit()
python
import scipy.stats
```

This import fails. So it appears something is happening when a python process is shut down regardless of which packages were imported.

**Comment by Filthy999** [comment]
Mine has now been fixed... I assume by a windows update which processed (KB5022497 or KB5022845)?

**Comment by jdegenstein** [comment]
I am seeing a similar issue on win10 with scipy==1.10.1 in a pyinstaller build:
```
>>> import scipy.sparse
...
File scipy\sparse\linalg\_isolve\iterative.py:9, in <module>
ImportError: DLL load failed while importing _iterative: The specified module could not be found.
```
```
>>> import scipy.interpolate
...
File scipy\special\__init__.py:663, in <module>
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found.
```

**Comment by andyfaff** [comment]
Looks like this might be starting to manifest in CI, https://github.com/scipy/scipy/actions/runs/4239541488/jobs/7367701437

**Comment by anantshukla** [comment]
Hi, sorry I was away this week but I am back in my original timezone now. Will test tomorrow and let you know if the new Windows Build fixed the issue.

**Comment by carlkl** [comment]
The aforementioned extensions contain a PE section named `redll`. A section with this name seems to be completely wrong. This could be an artefact produced by binutils `ld` related to the fact, that static libraries build with MSVC from numpy are linked together with gcc libraries in the scipy meson build. 
There is a related issue from last year: https://github.com/matthew-brett/dll_investigation/issues/1. See also: https://github.com/numpy/numpy/issues/20880 
@rgommers, what do you think?

**Comment by rgommers** [comment]
Argh, this sounds like it could spell significant trouble.

> There is a related issue from last year: [matthew-brett/dll_investigation#1](https://github.com/matthew-brett/dll_investigation/issues/1). See also: [numpy/numpy#20880](https://github.com/numpy/numpy/issues/20880)
> @rgommers, what do you think?

Yes, I remember that - I think we have very few guarantees here, because with including the static libraries `npymath` and `npyrandom` we are doing things that are pretty unhealthy. I don't have the Windows expertise to say more about PE sections and if/how we could fix that. I think the main points though are:

- There are a ton of users with existing installs, which we can do very little about. If those are break from Windows updates, I'd hope that Microsoft undoes whatever it did here quickly. Maybe they already have, seeing that @Filthy999 reports higher up that a new Windows update fixed it for them.
- Our only real fix is to move away from including static libraries built with MSVC at all. Now that NumPy also builds with Meson, we're in a much better position to be able to do so. Probably doable in 1-2 days of work.

**Comment by rgommers** [comment]
> Looks like this might be starting to manifest in CI, https://github.com/scipy/scipy/actions/runs/4239541488/jobs/7367701437

It's kind of strange that that only happened once. Similar reports for `_ufuncs` can be found elsewhere, like https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5579. It seems to only happen once in a while.

**Comment by carlkl** [comment]
I don't see this behaviour on my locally build scipy wheels. However I'm using the latest conpiler tolchains from msys2. Maybe the gcc toolchain and binutils contained in rtools is to old to handle this. rtools is used in CI - right?

**Comment by rgommers** [comment]
> I don't see this behaviour on my locally build scipy wheels. However I'm using the latest conpiler tolchains from msys2. Maybe the gcc toolchain and binutils contained in rtools is to old to handle this. rtools is used in CI - right?

Yes indeed. But it failed just once in a single job, so I'm not sure how reproducible it is even if it does depend on the Mingw-w64 version.

**Comment by carlkl** [comment]
My guess is that the PE files are corrupted, but in such a way that it does not show up in all circumstances. The `redll` section is the last entry. As we do not know the logic behind the OS checks during loading of a PE binary all considerations are speculative.
We should check against _clean_ wheels (wheels without containig such a section).

**Comment by rgommers** [comment]
You're probably right. The problem is that there's no good way to be sure that any file is not corrupted. Before it was a `.voltdb` section (IIRC), now a `redll` section - there's no easy check for this, we rely on "CI jobs are passing".

**Comment by carlkl** [comment]
For now it could help to use the standard msys2/ucrt64 toolchain instead of rtools.

**Comment by ilayn** [comment]
To give another data point,  msys2/ucrt64 is the only way I can build Scipy on my Win10 box

**Comment by andyfaff** [comment]
@ilayn , @carlkl , how do you set msys2/ucrt64 up for building?

**Comment by ilayn** [comment]
After installing the MSYS2, and performing a few times `pacman -Syu`. After that, I install `pacman -S mingw-w64-x86_64-gcc-fortran` and other dependencies I don't quite remember all of them. Then I'm adding the bin folder of the MSYS2 on the path and aggressively praying to all deities above and below.

**Comment by carlkl** [comment]
I'm using a special configuration to install msys2 and ucrt64 packages

```sh
pacman -Sy git svn zip autoconf automake autogen dejagnu make lndir libtool libarchive p7zip patch flex bison gettext-devel sshpass texinfo
pacman -Sy mingw-w64-ucrt-x86_64-gcc-fortran mingw-w64-ucrt-x86_64-pkgconf mingw-w64-ucrt-x86_64-ntldd mingw-w64-ucrt-x86_64-drmingw
```

I don't install `mingw-w64-ucrt-x86_64-python` to avoid conflicts with vanilla CPython. Therefore I do not install `mingw-w64-ucrt-x86_64-toolchain` and `mingw-w64-ucrt-x86_64-gdb`.

Setting up the PATH in `.bashrc` is a little bit compilated in my case:

```sh
# setting the PATH
export PATH=./:/usr/bin:/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

# MSYS2 architecture
if [ $MSYSTEM != "MSYS" ]
then
  export PATH=$MSYSTEM_PREFIX/bin:$PATH
fi

# Microsoft MSMPI (if available)
if [[ $MSMPI_BIN ]]
then
 export PATH=$PATH:`cygpath "$MSMPI_BIN"`
fi

# BASEPATH
export BASEPATH=$PATH

# add Python with alias
alias _py38='export PATH=~/devel/Python38:~/devel/Python38/Scripts:$BASEPATH;export PKG_CONFIG_PATH=~/devel/openblas/x86_64/lib/pkgconfig:$PKG_CONFIG_PATH'
alias _py39='export PATH=~/devel/Python39:~/devel/Python39/Scripts:$BASEPATH;export PKG_CONFIG_PATH=~/devel/openblas/x86_64/lib/pkgconfig:$PKG_CONFIG_PATH'
alias _py310='export PATH=~/devel/Python310:~/devel/Python310/Scripts:$BASEPATH;export PKG_CONFIG_PATH=~/devel/openblas/x86_64/lib/pkgconfig:$PKG_CONFIG_PATH'
alias _py311='export PATH=~/devel/Python311:~/devel/Python311/Scripts:$BASEPATH;export PKG_CONFIG_PATH=~/devel/openblas/x86_64/lib/`:$PKG_CONFIG_PATH'
```

The start the ucrt64 terminal. With that I can simply type `_py311` in the ucrt64 terminal to switch to my Python-3.11 environment.

The Python environments as well as OpenBLAS has to be installed or copied according to the paths given in th `.bashrc` file. `pkgconfig` should be able to locate the OpenBLAS folder.

**Comment by andyfaff** [comment]
> Maybe the gcc toolchain and binutils contained in rtools is to old to handle this. rtools is used in CI - right?

Further to Ralf's comments I think the rtools package from choco ackages `gcc=8.3.0`. The `MinGW-w64` package from choco is up to 12.2.0. Is it worth trying to get that to work?

**Comment by andyfaff** [comment]
FWIW I tried re-running the wheel build again. The [`cp39-win_amd64` run](https://github.com/scipy/scipy/actions/runs/4239541488/jobs/7367701437#step:5:7370) is still failing. I don't know why it's not present in the cp310 or cp311 entries, or why we don't see this more generally.

**Comment by andyfaff** [comment]
I can get a wheel to build with mingw64-12.2.0 (on my own fork, https://github.com/andyfaff/scipy/pull/41) with `windows-2022` instead of `windows-2019`. However it doesn't solve the cp39 issue. Things build fine for cp310 and cp311, just not cp39.

**Comment by rgommers** [comment]
An upgrade to mingw64 10.x or 12.x instead of 8.x sounds like a good idea regardless, +1 for that.

For the `cp39` failure, it sounds like we're stuck and can't build new wheels right now. I guess we have not yet tried using the Msys2 mingw64 package, but good chances that it'll also give the same result as the other compiler/OS versions that all failed.

**Comment by rgommers** [comment]
> Looks like this might be starting to manifest in CI, https://github.com/scipy/scipy/actions/runs/4239541488/jobs/7367701437

I found the issue, I think gh-18036 should make this problem go away. The py39 wheel issue is unrelated to the end user bug reports on this issue.

**Comment by andyfaff** [comment]
Suddenly everything becomes crystal clear. Yes, we had that issue during cibuildwheel introduction last year. Should've remembered that.

**Comment by carlkl** [comment]
I created sucessfully a local python-3.9 scipy build from https://github.com/rgommers/npy-staticlibs with numpy-1.21.6 (64-bit). All test are passing.

**Comment by carlkl** [comment]
This issue should be closed, I think.
