### ISSUE TITLE
Unable to install Scipy

### ISSUE THREAD

**Issue by saalimzafar** [scipy/scipy#17991]
```bash
Processing /data/data/com.termux/files/home/SCIPY/scipy-1.10.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /data/data/com.termux/files/home/SCIPY/scipy-1.10.0
      Build dir: /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 15.0.7 "clang version 15.0.7")
      C linker for the host machine: cc ld.lld 15.0.7
      C++ compiler for the host machine: c++ (clang 15.0.7 "clang version 15.0.7")
      C++ linker for the host machine: c++ ld.lld 15.0.7
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES

      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

      A full log can be found at /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build/meson-logs/meson-log.txt
      + meson setup --prefix=/data/data/com.termux/files/usr /data/data/com.termux/files/home/SCIPY/scipy-1.10.0 /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build --native-file=/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 1041, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/data/data/com.termux/files/usr', '/data/data/com.termux/files/home/SCIPY/scipy-1.10.0', '/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build', '--native-file=/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ilayn** [comment]
Hi @saalimzafar could you please follow the issue template for filling in the missing details? When you click "new issue" button you will see a template with information pieces we need to know to understand things better, machine type CPU, python version numpy version etc. You can copy paste the information above to the error message window to mark and style it properly

![image](https://user-images.githubusercontent.com/1303842/219619302-812982da-d147-44ba-8f96-011ae24f70f8.png)
