### ISSUE TITLE
BUG: Unable to install Scipy

### ISSUE THREAD

**Issue by saalimzafar** [scipy/scipy#17994]
### Describe your issue.

Unable to install Scipy!

### Reproducing Code Example

```python
NA
```

### Error message

```shell
Processing /data/data/com.termux/files/home/SCIPY/scipy-1.10.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /data/data/com.termux/files/home/SCIPY/scipy-1.10.0
      Build dir: /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 15.0.7 "clang version 15.0.7")
      C linker for the host machine: cc ld.lld 15.0.7
      C++ compiler for the host machine: c++ (clang 15.0.7 "clang version 15.0.7")
      C++ linker for the host machine: c++ ld.lld 15.0.7
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES

      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"

      A full log can be found at /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build/meson-logs/meson-log.txt
      + meson setup --prefix=/data/data/com.termux/files/usr /data/data/com.termux/files/home/SCIPY/scipy-1.10.0 /data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build --native-file=/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 1041, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-18q_fk9y/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/data/data/com.termux/files/usr', '/data/data/com.termux/files/home/SCIPY/scipy-1.10.0', '/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-zi64j2ba/build', '--native-file=/data/data/com.termux/files/home/SCIPY/scipy-1.10.0/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.


note: This error originates from a subprocess, and is likely not a problem with pip.
```

### SciPy/NumPy/Python version information

python 3.11.2 | numpy 1.23.2

**Comment by tylerjereddy** [comment]
Do you mean to be building from source? What happens if you install an appropriate Fortran compiler as it can't find one?

What is your operating system version? Are you on an M1 mac or something else?

What command did you use to try to install SciPy?

On MacOS M1/M2 you need MacOS version `>= 12.0` to install a pre-built binary rather than building from source.

**Comment by saalimzafar** [comment]
I'm trying to install it on Termux,

error: library mach has Fortran sources but no Fortran compiler found 

I have  Lfortran but not Fortran,

I can use matplotlib, numpy and pandas which are heavy weight but not Scipy!!!

**Comment by matthew-brett** [comment]
Scipy needs a compatible Fortran compiler - because it has a lot of Fortran code.  In that sense is is a lot "heavier" than - say Numpy or Pandas.  I don't think anyone has succeeded in compiling Scipy with LFortran - as you may know, it's an evolving compiler, and I believe there is still some work to do before it can compile Scipy.

**Comment by tupui** [comment]
Yes, LFortran compatibility is still in the work and not supported yet. The LFortran team is actively working towards that goal.

Not sure there is anything to do here and would propose to close the issue.

**Comment by rgommers** [comment]
Agreed. `gfortran` will get you past this hurdle.
