### ISSUE TITLE
BUG: dev.py does not work in a Windows CI environment on GHA because of emojis

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#18046]
### Describe your issue.

I'm trying to use dev.py in [windows.yml ](https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml) to build and test scipy. However, there seems to be some special characters being produced as a consequence of dev.py that can't be encoded, and so a `python dev.py build -j 2` step fails.

See https://github.com/scipy/scipy/actions/runs/4266898229/jobs/7427938975

I'm not sure if the bug lies in dev.py / rich / rich_click / doit because they all seem to be involved in the stack trace.

### Reproducing Code Example

```python
# use python dev.py build in a Windows GHA step.
```

### Error message

```shell
Run echo "SCIPY_USE_PROPACK=1" >> $env:GITHUB_ENV
  echo "SCIPY_USE_PROPACK=1" >> $env:GITHUB_ENV
  python dev.py build -j 2
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.10.10\x64
    PKG_CONFIG_PATH: c:\opt\64\lib\pkgconfig;
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.10\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.10\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.10\x64
Task Error - build => PythonAction Error
+----------------------------------- build -----------------------------------+
| Traceback (most recent call last):                                          |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\doit\actio |
| n.py", line 461, in execute                                                 |
|     returned_value = self.py_callable(*self.args, **kwargs)                 |
|   File "D:\a\scipy\scipy\dev.py", line 638, in run                          |
|     env = cls.setup_build(dirs, args)                                       |
|   File "D:\a\scipy\scipy\dev.py", line 470, in setup_build                  |
|     cls.console.print(f"{EMOJI.cmd}  {cmd_str}")                            |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\conso |
| le.py", line 1667, in print                                                 |
|     with self:                                                              |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\conso |
| le.py", line 869, in __exit__                                               |
|     self._exit_buffer()                                                     |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\conso |
| le.py", line 827, in _exit_buffer                                           |
|     self._check_buffer()                                                    |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\conso |
| le.py", line 2023, in _check_buffer                                         |
|     legacy_windows_render(buffer, LegacyWindowsTerm(self.file))             |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\_wind |
| ows_renderer.py", line 19, in legacy_windows_render                         |
|     term.write_text(text)                                                   |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\rich\_win3 |
| 2_console.py", line 403, in write_text                                      |
|     self.write(text)                                                        |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\doit\actio |
| n.py", line 355, in write                                                   |
|     stream.write(text)                                                      |
|   File                                                                      |
| "C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\encodings\cp1252.py",    |
| line 19, in encode                                                          |
|     return codecs.charmap_encode(input,self.errors,encoding_table)[0]       |
| UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4bb' in  |
| position 0: character maps to <undefined>                                   |
|                                                                             |
+---------------------------- PythonAction Error -----------------------------+
Error: Process completed with exit code 1.
```

### SciPy/NumPy/Python version information

python 3.10

**Comment by andyfaff** [comment]
dev.py should possibly try encoding the characters before it tries to print them somewhere. If the encoding fails it should strip the offending chars and try again.

**Comment by andyfaff** [comment]
I tried doing this on a windows box as well. Those emojis/characters can't be represented in a windows CMD prompt either, except it doesn't stop the whole build process running.

@sayantikabanik

**Comment by andyfaff** [comment]
In #18012 I worked around the emoji issue by usning `">"` on windows and `":command:"` on other platforms.

**Comment by tupui** [comment]
@andyfaff only this emoji is an issue or should we just replace all emojis on windows?

**Comment by andyfaff** [comment]
On my local machine I use a CMD shell, but it's not a big issue, the chars don't print properly.
On a CI machine it's a big issue - it causes the CI run to fail.

**Comment by tupui** [comment]
Instead of tweaking the chars, we could just not use rich in the CI in this script.

**Comment by andyfaff** [comment]
Currently `rich` has to be installed as it's pulled in by `rich_click` which is imported in the `dev.py` script.

**Comment by tupui** [comment]
Here I am just suggesting to wrap `self.console` so that `rich` does not do anything with the emojis or colours when it cannot. There might be a simpler way to just deactivate this from `rich` directly. I did not check it's doc.

**Comment by melissawm** [comment]
Could this note https://rich.readthedocs.io/en/stable/console.html#terminal-detection help here?

**Comment by lucascolley** [comment]
I have reproduced this error following the move to `spin`. CI log at https://github.com/rgommers/pixi-dev-scipystack/actions/runs/16102019590/job/45432356711?pr=23. The error there is triggered by the emoji in https://github.com/scientific-python/spin/blob/fee6abe42cea118c2e4577cce5e0ca034c55748e/spin/cmds/meson.py#L766.

**Comment by lucascolley** [comment]
I found [a solution in a very helpful Gist](https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15#solutions).

**Comment by ilayn** [comment]
I think this is resolved by switching to `spin` but please reopen if it is not.
