### ISSUE TITLE
Cygwin strange error with pip install==1.9.3

### ISSUE THREAD

**Issue by natanb** [scipy/scipy#18205]
'll try to install Scipy via pip on Cygwin platform. The installatin works on 2/3 pc which have similar Cygwin environmental.
The last one pc when give command pip install scipy==1.9.3 iusse a very strange error: 
 `/usr/bin/python3.9.exe -c 'import os; os.chdir(".."); import numpy; print(numpy.get_include())'` failed with status 1.

The command `/usr/bin/....`  works perfectly in bash shell!?

I report the log file:

Collecting scipy==1.9.3
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      The Meson build system
      Version: 1.0.1
      Source dir: /tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494
      Build dir: /tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494/.mesonpy-lidor935/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (gcc 11.3.0 "cc (GCC) 11.3.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (GCC) 11.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 11.3.0 "GNU Fortran (GCC) 11.3.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.40
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Program cython found: YES (/tmp/pip-build-env-x6qcewsj/overlay/bin/cython)
      Program pythran found: YES (/tmp/pip-build-env-x6qcewsj/overlay/bin/pythran)
      Program cp found: YES (/usr/bin/cp)
      Program python found: YES (/usr/bin/python3.9.exe)
      Found pkg-config: /usr/bin/pkg-config (1.9.4)
      Run-time dependency threads found: YES

      ../../scipy/meson.build:40:0: ERROR: Command `/usr/bin/python3.9.exe -c 'import os; os.chdir(".."); import numpy; print(numpy.get_include())'` failed with status 1.

 A full log can be found at /tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494/.mesonpy-lidor935/build/meson-logs/meson-log.txt
      + meson setup --prefix=/usr /tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494 /tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494/.mesonpy-lidor935/build --native-file=/tmp/pip-install-dyygzzdz/scipy_5e46628b044d4399bd91492651cbe494/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rgommers** [comment]
Hmm, probably some strange environment-related error. Hard to tell without seeing `meson-log.txt` contents. And even then it may not be clear cut. Can you try adding `--config-settings=builddir=./builddir` to preserve the build output, and then look at `builddir/meson-logs/meson-log.txt`?

**Comment by natanb** [comment]
Sorry but how where add --config-settings=builddir=./builddir?

**Comment by natanb** [comment]
Build started at 2023-03-28T20:57:35.306786
Main binary: /usr/bin/python3.9.exe
Build Options: -Ddebug=false -Doptimization=2 -Dprefix=/usr --native-file=/tmp/pip-install-dmkfdv9d/scipy_f3d0986db037447ebb06cba64c6159d5/.mesonpy-native-file.ini
Python system: CYGWIN_NT-10.0-19044
The Meson build system
Version: 1.0.1
Source dir: /tmp/pip-install-dmkfdv9d/scipy_f3d0986db037447ebb06cba64c6159d5
Build dir: /home/bruno/builddir
Build type: native build
Project name: SciPy
Project version: 1.9.3
-----
Detecting compiler via: cc --version
compiler returned <Popen: returncode: 0 args: ['cc', '--version']>
compiler stdout:
cc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: cc -E -dM -
-----
Detecting linker via: cc -Wl,--version
linker returned <Popen: returncode: 0 args: ['cc', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 11.3.0
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld -plugin /usr/lib/gcc/x86_64-pc-cygwin/11/cyglto_plugin.dll -plugin-opt=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe -plugin-opt=-fresolution=/tmp/ccbVC3CE.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lcygwin -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id -m i386pep --wrap _Znwm --wrap _Znam --wrap _ZdlPv --wrap _ZdaPv --wrap _ZnwmRKSt9nothrow_t --wrap _ZnamRKSt9nothrow_t --wrap _ZdlPvRKSt9nothrow_t --wrap _ZdaPvRKSt9nothrow_t -Bdynamic --dll-search-prefix=cyg --tsaware /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/crt0.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtbegin.o -L/usr/lib/gcc/x86_64-pc-cygwin/11 -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../.. --version -lgcc_s -lgcc -lcygwin -ladvapi32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/default-manifest.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtend.o

Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/bruno/builddir/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the host machine: cc ld.bfd 2.40
-----
Detecting compiler via: c++ --version
compiler returned <Popen: returncode: 0 args: ['c++', '--version']>
compiler stdout:
c++ (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: c++ -E -dM -
-----
Detecting linker via: c++ -Wl,--version
linker returned <Popen: returncode: 0 args: ['c++', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 11.3.0
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld -plugin /usr/lib/gcc/x86_64-pc-cygwin/11/cyglto_plugin.dll -plugin-opt=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe -plugin-opt=-fresolution=/tmp/cc6GFC7k.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lcygwin -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id -m i386pep --wrap _Znwm --wrap _Znam --wrap _ZdlPv --wrap _ZdaPv --wrap _ZnwmRKSt9nothrow_t --wrap _ZnamRKSt9nothrow_t --wrap _ZdlPvRKSt9nothrow_t --wrap _ZdaPvRKSt9nothrow_t -Bdynamic --dll-search-prefix=cyg --tsaware /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/crt0.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtbegin.o -L/usr/lib/gcc/x86_64-pc-cygwin/11 -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../.. --version -lstdc++ -lgcc_s -lgcc -lcygwin -ladvapi32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/default-manifest.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtend.o

Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/bruno/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (GCC) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.40
-----
Detecting compiler via: cc --version
compiler returned <Popen: returncode: 0 args: ['cc', '--version']>
compiler stdout:
cc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: cc -E -dM -
-----
Detecting linker via: cc -Wl,--version
linker returned <Popen: returncode: 0 args: ['cc', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 11.3.0
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld -plugin /usr/lib/gcc/x86_64-pc-cygwin/11/cyglto_plugin.dll -plugin-opt=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe -plugin-opt=-fresolution=/tmp/ccd33bCC.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lcygwin -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id -m i386pep --wrap _Znwm --wrap _Znam --wrap _ZdlPv --wrap _ZdaPv --wrap _ZnwmRKSt9nothrow_t --wrap _ZnamRKSt9nothrow_t --wrap _ZdlPvRKSt9nothrow_t --wrap _ZdaPvRKSt9nothrow_t -Bdynamic --dll-search-prefix=cyg --tsaware /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/crt0.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtbegin.o -L/usr/lib/gcc/x86_64-pc-cygwin/11 -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../.. --version -lgcc_s -lgcc -lcygwin -ladvapi32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/default-manifest.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtend.o

Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/bruno/builddir/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the build machine: cc ld.bfd 2.40
-----
Detecting compiler via: c++ --version
compiler returned <Popen: returncode: 0 args: ['c++', '--version']>
compiler stdout:
c++ (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: c++ -E -dM -
-----
Detecting linker via: c++ -Wl,--version
linker returned <Popen: returncode: 0 args: ['c++', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 11.3.0
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld -plugin /usr/lib/gcc/x86_64-pc-cygwin/11/cyglto_plugin.dll -plugin-opt=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe -plugin-opt=-fresolution=/tmp/cc9Qf7BH.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lcygwin -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id -m i386pep --wrap _Znwm --wrap _Znam --wrap _ZdlPv --wrap _ZdaPv --wrap _ZnwmRKSt9nothrow_t --wrap _ZnamRKSt9nothrow_t --wrap _ZdlPvRKSt9nothrow_t --wrap _ZdaPvRKSt9nothrow_t -Bdynamic --dll-search-prefix=cyg --tsaware /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/crt0.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtbegin.o -L/usr/lib/gcc/x86_64-pc-cygwin/11 -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../.. --version -lstdc++ -lgcc_s -lgcc -lcygwin -ladvapi32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/default-manifest.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtend.o

Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/bruno/builddir/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: c++ (gcc 11.3.0 "c++ (GCC) 11.3.0")
C++ linker for the build machine: c++ ld.bfd 2.40
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmp1nyn_qz6
Command line:  cc /home/bruno/builddir/meson-private/tmp1nyn_qz6/testfile.c -o /home/bruno/builddir/meson-private/tmp1nyn_qz6/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wunused-but-set-variable -Wno-unused-but-set-variable 

Code:
 extern int i;
int i;

Compiler stdout:
 
Compiler stderr:
 
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Using cached compile:
Cached command line:  cc /home/bruno/builddir/meson-private/tmp1nyn_qz6/testfile.c -o /home/bruno/builddir/meson-private/tmp1nyn_qz6/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wunused-but-set-variable -Wno-unused-but-set-variable 

Code:
 extern int i;
int i;

Cached compiler stdout:
 
Cached compiler stderr:
 
Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmpr98axl28
Command line:  cc /home/bruno/builddir/meson-private/tmpr98axl28/testfile.c -o /home/bruno/builddir/meson-private/tmpr98axl28/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wunused-function -Wno-unused-function 

Code:
 extern int i;
int i;

Compiler stdout:
 
Compiler stderr:
 
Compiler for C supports arguments -Wno-unused-function: YES 
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmpuux7wvw1
Command line:  cc /home/bruno/builddir/meson-private/tmpuux7wvw1/testfile.c -o /home/bruno/builddir/meson-private/tmpuux7wvw1/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wconversion -Wno-conversion 

Code:
 extern int i;
int i;

Compiler stdout:
 
Compiler stderr:
 
Compiler for C supports arguments -Wno-conversion: YES 
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmpvelcyf3s
Command line:  cc /home/bruno/builddir/meson-private/tmpvelcyf3s/testfile.c -o /home/bruno/builddir/meson-private/tmpvelcyf3s/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wmisleading-indentation -Wno-misleading-indentation 

Code:
 extern int i;
int i;

Compiler stdout:
 
Compiler stderr:
 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmpzq5ti36p
Command line:  cc /home/bruno/builddir/meson-private/tmpzq5ti36p/testfile.c -o /home/bruno/builddir/meson-private/tmpzq5ti36p/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 -Wincompatible-pointer-types -Wno-incompatible-pointer-types 

Code:
 extern int i;
int i;

Compiler stdout:
 
Compiler stderr:
 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmp5uuft77l
Command line:  cc /home/bruno/builddir/meson-private/tmp5uuft77l/testfile.c -o /home/bruno/builddir/meson-private/tmp5uuft77l/output.exe -D_FILE_OFFSET_BITS=64 -O0 -Wl,--start-group -lm -Wl,--end-group -Wl,--allow-shlib-undefined 

Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 
Library m found: YES
Running command: gfortran -E -dM -
-----
Detecting linker via: gfortran -Wl,--version
linker returned <Popen: returncode: 0 args: ['gfortran', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 11.3.0
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld -plugin /usr/lib/gcc/x86_64-pc-cygwin/11/cyglto_plugin.dll -plugin-opt=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe -plugin-opt=-fresolution=/tmp/ccv75x01.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lcygwin -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id -m i386pep --wrap _Znwm --wrap _Znam --wrap _ZdlPv --wrap _ZdaPv --wrap _ZnwmRKSt9nothrow_t --wrap _ZnamRKSt9nothrow_t --wrap _ZdlPvRKSt9nothrow_t --wrap _ZdaPvRKSt9nothrow_t -Bdynamic --dll-search-prefix=cyg --tsaware /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/crt0.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtbegin.o -L/usr/lib/gcc/x86_64-pc-cygwin/11 -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/11/../../.. --version -lgcc_s -lgcc -lcygwin -ladvapi32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/default-manifest.o /usr/lib/gcc/x86_64-pc-cygwin/11/crtend.o

Sanity testing Fortran compiler: gfortran
Is cross compiler: False.
Sanity check compiler command line: gfortran sanitycheckf.f90 -o sanitycheckf.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/bruno/builddir/meson-private/sanitycheckf.exe
Fortran compiler for the host machine: gfortran (gcc 11.3.0 "GNU Fortran (GCC) 11.3.0")
Fortran linker for the host machine: gfortran ld.bfd 2.40
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmppcexppzd
Command line:  gfortran /home/bruno/builddir/meson-private/tmppcexppzd/testfile.f90 -o /home/bruno/builddir/meson-private/tmppcexppzd/output.obj -D_FILE_OFFSET_BITS=64 -c -O0 -Wconversion -Wno-conversion 

Code:
 stop; end program
Compiler stdout:
 
Compiler stderr:
 
Compiler for Fortran supports arguments -Wno-conversion: YES 
Program cython found: YES (/tmp/pip-build-env-ulhn28nb/overlay/bin/cython)
Program pythran found: YES (/tmp/pip-build-env-ulhn28nb/overlay/bin/pythran)
Program cp found: YES (/usr/bin/cp)
Program python found: YES (/usr/bin/python3.9.exe)
Searching for 'python-3.9' via pkgconfig lookup in LIBPC
Pkg-config binary for 1 is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.9.4)
Determining dependency 'python-3.9' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_LIBDIR]: /usr/lib/pkgconfig
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion python-3.9` -> 0
stdout:
3.9
-----------
env[PKG_CONFIG_LIBDIR]: /usr/lib/pkgconfig
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags python-3.9` -> 0
stdout:
-I/usr/include/python3.9
-----------
env[PKG_CONFIG_LIBDIR]: /usr/lib/pkgconfig
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs python-3.9` -> 0
stdout:
-lpython3.9
-----------
env[PKG_CONFIG_LIBDIR]: /usr/lib/pkgconfig
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs python-3.9` -> 0
stdout:
-lpython3.9
-----------
Running compile:
Working directory:  /home/bruno/builddir/meson-private/tmp502fmpmm
Command line:  c++ /home/bruno/builddir/meson-private/tmp502fmpmm/testfile.cpp -o /home/bruno/builddir/meson-private/tmp502fmpmm/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Wl,--start-group -lpython3.9 -Wl,--end-group -Wl,--allow-shlib-undefined 

Code:
 int main(void) { return 0; }

Compiler stdout:
 
Compiler stderr:
 
Run-time dependency threads found: YES
Running command: /usr/bin/python3.9.exe -c 'import os; os.chdir(".."); import numpy; print(numpy.get_include())'
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "/tmp/pip-build-env-ulhn28nb/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/tmp/pip-build-env-ulhn28nb/overlay/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/tmp/pip-build-env-ulhn28nb/overlay/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-env-ulhn28nb/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/tmp/pip-build-env-ulhn28nb/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3.9.exe"
  * The NumPy version is: "1.19.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No such file or directory




../../../tmp/pip-install-dmkfdv9d/scipy_f3d0986db037447ebb06cba64c6159d5/scipy/meson.build:40:0: ERROR: Command `/usr/bin/python3.9.exe -c 'import os; os.chdir(".."); import numpy; print(numpy.get_include())'` failed with status 1.

**Comment by natanb** [comment]
[meson-log.txt](https://github.com/scipy/scipy/files/11093294/meson-log.txt)

**Comment by rgommers** [comment]
Yes indeed, a plain numpy import doesn't seem to work. I'm not sure how to help with that @natanb, beyond "remove it all thoroughly and try again". There's many things it can be caused by.

**Comment by rgommers** [comment]
I'll close this as it seems clear this is not a SciPy issue but an environment-specific problem. Please feel free to continue adding comments or asking questions though @natanb.

**Comment by natanb** [comment]
Well I resolved it! It's clean: I installed last version of windows Python3.11, then in .bashrc I set the PATH 
export PATH=/cygdrive/c/Users/youruser/AppData/Local/Programs/Python/Python311/:$PATH

Install module with pip in bash windows
