### ISSUE TITLE
environment.yml is missing myst_nb

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#18338]
Building the docs in a fresh conda environment created via `$ mamba env create -f environment.yml` fails to find `myst_nb`. I guess the `yml` file needs an update

```
Found ninja-1.11.1 at /home/br/mambaforge/envs/scipy-dev/bin/ninja
Cleaning... 0 files.
[355/355] Linking target scipy/sparse/spar...parsetools.cpython-310-x86_64-linux-gnu.so
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
# for testing
# @echo installed scipy 9a8ec79 matches git version 9a8ec79; exit 1
mkdir -p build/html build/doctrees
LANG=C /home/br/mambaforge/envs/scipy-dev/bin/python -msphinx -WT --keep-going  -b html -d build/doctrees -j1 source build/html 
Running Sphinx v5.3.0
SciPy (VERSION 1.11.0.dev0+1910.9a8ec79)

Traceback (most recent call last):
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myst_nb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension myst_nb (exception: No module named 'myst_nb')

Extension error:
Could not import extension myst_nb (exception: No module named 'myst_nb')
```

**Comment by ev-br** [comment]
Also

```
$ python dev.py lint
Traceback (most recent call last):
  File "/home/br/repos/scipy/scipy/tools/lint.py", line 138, in <module>
    main()
  File "/home/br/repos/scipy/scipy/tools/lint.py", line 127, in main
    rc, errors = run_ruff(other_files, fix=args.fix)
  File "/home/br/repos/scipy/scipy/tools/lint.py", line 73, in run_ruff
    res = subprocess.run(
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ruff'
```

**Comment by rgommers** [comment]
Both things work fine for me, and both `myst-nb` and `ruff` are present in `environment.yml`. Not sure what's happening for you, maybe an old environment or some env var set?

**Comment by ev-br** [comment]
OK, does work on nuking the environment and redoing from scratch. Had several hiccups on switching to mamba, so let's call it a user fluke.
