### ISSUE TITLE
BUG: setting mkl to use ILP64 breaks eigh

### ISSUE THREAD

**Issue by johnstill** [scipy/scipy#18480]
### Describe your issue.

I'm working on an extension module via Cython using some MKL vector math functions directly, and we get much better performance from their vector math functions if we set their interface layer to be 64-bit. But to my dismay, this breaks `scipy.linalg.eigh`, as detailed in the repro below. 

I poked around in the source a bit and saw that `get_lapack_funcs` has an `ilp64` argument which `eigh` is not using, which alone is sufficient to effectively hard-code `eigh` to be 32-bit. I know though that there's some more complicated lookup logic behind the scenes, and just using the kwarg wouldn't necessarily be sufficient for `eigh` to work with MKL ILP64.

Is there any simple way to make scipy and ILP64 MKL play nice together? I don't really want to have to drop either from this project, but it seems at the moment that using ILP64 MKL means I can't also use scipy in the same process, which means my library (and _any_ extension code which wishes to use 64-bit `MKL_INT`s) is incompatible with scipy.

### Reproducing Code Example

```python
# cython: language_level=3
# distutils: libraries = ['mkl_rt']
# distutils: define_macros=MKL_ILP64=1

cdef extern from "mkl.h" nogil:
    int mkl_set_interface_layer(int required_interface)

# 0 is LP64, 1 is ILP64
mkl_set_interface_layer(1)

import numpy as np
from scipy import linalg

X = np.random.random_sample((100, 100))
d, u = linalg.eigh(np.dot(X, X.T))
```

### Error message

```shell
$ python -c 'import repro'
                                                                                                        
Intel MKL ERROR: Parameter 6 was incorrect on entry to DSYEVR.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "repro.pyx", line 15, in init repro
    d, u = linalg.eigh(np.dot(X, X.T))
  File "/hd1/stilljm/misc/mamba/envs/inferno/lib/python3.11/site-packages/scipy/linalg/_decomp.py", line 553, in eigh
    lw = _compute_lwork(drvlw, **clw_args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hd1/stilljm/misc/mamba/envs/inferno/lib/python3.11/site-packages/scipy/linalg/lapack.py", line 1004, in _compute_lwork
    raise ValueError("Internal work array size computation failed: "
ValueError: Internal work array size computation failed: -6
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.3 sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /hd1/stilljm/misc/mamba/envs/inferno/include
    lib directory: /hd1/stilljm/misc/mamba/envs/inferno/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /hd1/stilljm/misc/mamba/envs/inferno/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /hd1/stilljm/misc/mamba/envs/inferno/include
    lib directory: /hd1/stilljm/misc/mamba/envs/inferno/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /hd1/stilljm/misc/mamba/envs/inferno/lib/pkgconfig
    version: 3.9.0
Compilers:
  c:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1683900207230/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 12.2.0
  c++:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1683900207230/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 12.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.34
  fortran:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1683900207230/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 12.2.0
  pythran:
    include directory: ../../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pythran
    version: 0.12.2
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /hd1/stilljm/misc/mamba/envs/inferno/bin/python
  version: '3.11'
```

**Comment by johnstill** [comment]
Turns out there is a simple way to get these libs working together: if I compile my extension linking against each ILP64 interface lib directly instead of the shared dynamic library (i.e. `mkl_rt`) and remove the interface call (which only is defined for `mkl_rt`), then whatever dependency resolution mkl is doing behind the scenes, everything seems to just work - I get the 64-bit interface and scipy gets the 32-bit interface.

The library / linking changes: 
```
# cython: language_level=3
# distutils: libraries = ['mkl_intel_ilp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread', 'm', 'dl']
# distutils: extra_link_args = ['-Wl,--no-as-needed']
# distutils: extra_compile_args = ['-m64']
# distutils: define_macros=MKL_ILP64=1
```

I tested this by running an mkl vector math function on more elements than the 32-bit interface allows (e.g. `vdTanh(m, ...)` with `m > 2**31-1`), and also `scipy.linalg.eigh`, in the same process, and so far everything seems to work just fine.

Apologies for the spurious bug report.
