### ISSUE TITLE
bench-compare broken for running a single benchmark?

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#18665]
Trying to run a single benchmark with mamba. Just running `$ python dev.py bench -t GridData` works fine, while `bench --compare main` fails with

```                                                                                        
(scipy-dev) br@gonzales:~/repos/scipy/scipy$ python dev.py bench --compare main -t GridData
💻  ninja -C /home/br/repos/scipy/scipy/build -j4
ninja: Entering directory `/home/br/repos/scipy/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Creating environments.
·· Error running  env create -f /tmp/tmpxx2fo13h.yml -p /home/br/repos/scipy/scipy/benchmarks/env/dc4107ba04c9faab49c4c6d6f6b22097 --force (exit status 1)
   STDOUT -------->
   
   STDERR -------->
   
   SpecNotFound: /tmp/tmpxx2fo13h.yml is not a valid yaml file.
   

·· Failure creating environment for conda-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/scipy-dev/bin/asv", line 10, in <module>
    sys.exit(main())
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/continuous.py", line 63, in run_from_conf_args
    return cls.run(
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/continuous.py", line 100, in run
    result = Run.run(
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/run.py", line 230, in run
    Setup.perform_setup(environments, parallel=parallel)
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/setup.py", line 81, in perform_setup
    list(map(_create, environments))
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/setup.py", line 20, in _create
    env.create()
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/environment.py", line 530, in create
    self._setup()
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/plugins/conda.py", line 149, in _setup
    util.check_output([conda] + ['env', 'create', '-f', env_file.name,
  File "/home/br/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/asv/util.py", line 685, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/br/mambaforge/bin/conda env create -f /tmp/tmpxx2fo13h.yml -p /home/br/repos/scipy/scipy/benchmarks/env/dc4107ba04c9faab49c4c6d6f6b22097 --force' returned non-zero exit status 1
```

Not sure if it's relevant that the traceback mentions `conda` while the environment is managed by `mamba`.

**Comment by tupui** [comment]
Yeah I think we discussed this somewhere. @sayantikabanik I think you were working on that right??

**Comment by sayantikabanik** [comment]
> Yeah I think we discussed this somewhere. @sayantikabanik I think you were working on that right??

Been couple of months since I added this bit. Shall give a try replicating in my system

**Comment by rgommers** [comment]
I tried to reproduce this, but it works for me:
```
$ python dev.py bench -t GridData --compare main
💻  ninja -C /home/rgommers/code/scipy/build -j12
ninja: Entering directory `/home/rgommers/code/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/rgommers/code/scipy/build-install/lib/python3.10/site-packages
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Creating environments........
· Discovering benchmarks.........
·· Uninstalling from virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
·· Building 876c68da <main> for virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran..........................................................................................................................................................................................
·· Installing 876c68da <main> into virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran.
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[  0.00%] · For scipy commit 876c68da <main> (round 1/2):
[  0.00%] ·· Benchmarking virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
[ 25.00%] ··· Running (interpolate.GridData.time_evaluation--).
[ 25.00%] · For scipy commit 876c68da <main> (round 1/2):
[ 25.00%] ·· Benchmarking virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
[ 50.00%] ··· Running (interpolate.GridData.time_evaluation--).
[ 50.00%] · For scipy commit 876c68da <main> (round 2/2):
[ 50.00%] ·· Benchmarking virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
[ 75.00%] ··· interpolate.GridData.time_evaluation                                               ok
[ 75.00%] ··· ========= ============= ============= =============
              --                          method                 
              --------- -----------------------------------------
               n_grids     nearest        linear        cubic    
              ========= ============= ============= =============
                 10j       293±3μs     6.23±0.04ms   7.36±0.05ms 
                 100j    3.77±0.03ms    9.41±0.4ms    11.9±0.4ms 
                1000j      312±6ms       172±3ms       300±2ms   
              ========= ============= ============= =============

[ 75.00%] · For scipy commit 876c68da <main> (round 2/2):
[ 75.00%] ·· Benchmarking virtualenv-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
[100.00%] ··· interpolate.GridData.time_evaluation                                               ok
[100.00%] ··· ========= ============= ============= =============
              --                          method                 
              --------- -----------------------------------------
               n_grids     nearest        linear        cubic    
              ========= ============= ============= =============
                 10j       290±2μs     6.21±0.05ms   7.40±0.03ms 
                 100j    3.76±0.02ms   9.92±0.07ms   12.2±0.02ms 
                1000j      316±7ms       175±2ms      296±0.2ms  
              ========= ============= ============= =============


BENCHMARKS NOT SIGNIFICANTLY CHANGED.
```

It looks like the difference is that my build creates virtualenvs on top of a conda env, which yours tries (and fails) to create conda envs. @ev-br did you modify `asv.json.conf` or anything else? If not, what `asv` version is that?

**Comment by ev-br** [comment]
Did not change anything asv-related, no.

```
$ asv --version
asv 0.4.2
```

For completeness, here's my asv.conf.json:

```
$ cat benchmarks/asv.conf.json 
{
    // The version of the config file format.  Do not change, unless
    // you know what you are doing.
    "version": 1,

    // The name of the project being benchmarked
    "project": "scipy",

    // The project's homepage
    "project_url": "https://scipy.org/",

    // The URL of the source code repository for the project being
    // benchmarked
    "repo": "..",
    "dvcs": "git",
    "branches": ["HEAD"],

    // Customizable commands for building, installing, and
    // uninstalling the project. See asv.conf.json documentation.
    //
    // "install_command": ["in-dir={env_dir} python -mpip install {wheel_file}"],
    // "uninstall_command": ["return-code=any python -mpip uninstall -y {project}"],
    // "build_command": [
    //     "python setup.py build",
    //     "PIP_NO_BUILD_ISOLATION=false python -mpip wheel --no-deps --no-index -w {build_cache_dir} {build_dir}"
    // ],

    // The base URL to "how a commit for the project.
    "show_commit_url": "https://github.com/scipy/scipy/commit/",

    // The Pythons you'd like to test against.  If not provided, defaults
    // to the current version of Python used to run `asv`.
    // "pythons": ["3.6"],

    // The matrix of dependencies to test.  Each key is the name of a
    // package (in PyPI) and the values are version numbers.  An empty
    // list indicates to just test against the default (latest)
    // version.
    "matrix": {
        "numpy": [],
        "Cython": [],
        "pytest": [],
        "pythran": [],
        "pybind11": [],
        "meson-python": [],
    },

    // The directory (relative to the current directory) that benchmarks are
    // stored in.  If not provided, defaults to "benchmarks"
    "benchmark_dir": "benchmarks",

    // The directory (relative to the current directory) to cache the Python
    // environments in.  If not provided, defaults to "env"
    "env_dir": "env",

    // The tool to use to create environments.  May be "conda",
    // "virtualenv" or other value depending on the plugins in use.
    // If missing or the empty string, the tool will be automatically
    // determined by looking for tools on the PATH environment
    // variable.
    // "environment_type": "virtualenv",
    "build_cache_size": 10,

    // The directory (relative to the current directory) that raw benchmark
    // results are stored in.  If not provided, defaults to "results".
    "results_dir": "results",

    // The directory (relative to the current directory) that the html tree
    // should be written to.  If not provided, defaults to "html".
    "html_dir": "html",

    // The number of characters to retain in the commit hashes.
    "hash_length": 8,

    // The commits after which the regression search in `asv publish`
    // should start looking for regressions. Dictionary whose keys are
    // regexps matching to benchmark names, and values corresponding to
    // the commit (exclusive) after which to start looking for
    // regressions.  The default is to start from the first commit
    // with results. If the commit is `null`, regression detection is
    // skipped for the matching benchmark.

    "regressions_first_commits": {
       "io_matlab\\.StructArr\\..*": "67c089a6",  //  structarrs weren't properly implemented before this
    }
}
```

The only maybe non-standard thing in my setup is that I use virtualenvwrapper and explicitly set the path to store the environments. Thus, my .bashrc has

```
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
. $HOME/.local/bin/virtualenvwrapper.sh
```

But this is not _that_ non-standard anyway :-)
