### ISSUE TITLE
BUG: stats.bootstrap with stats.pearsonr() as function raises ValueError

### ISSUE THREAD

**Issue by alexandralehner** [scipy/scipy#18769]
### Describe your issue.

When calling stats.bootstrap() in a python scipt with the Pearson Correlation Coefficient as the statistic, a ValueError is raised.

It seems like the bootstrapping method is working for several iterations until the bootstrapping array lengths suddenly diverge.

### Reproducing Code Example

```python
from scipy import stats
import numpy as np

array1 = np.random.normal(0, 0.1, 20)
array2 = np.random.normal(0, 0.1, 20)

bootstrap_results = stats.bootstrap(
        data=(array1, array2),
        statistic=stats.pearsonr,
        n_resamples=1000,
        confidence_level=0.95
)

#print(bootstrap_results.confidence_interval)
```

### Error message

```shell
python3 main.py
Traceback (most recent call last):
  File "/home/alex/git-repos/corr_coeff-bootstrapping/main.py", line 7, in <module>
    bootstrap_results = stats.bootstrap(
                        ^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/scipy/stats/_resampling.py", line 637, in bootstrap
    interval = _bca_interval(data, statistic, axis=-1, alpha=alpha,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/scipy/stats/_resampling.py", line 130, in _bca_interval
    theta_hat_i.append(statistic(*broadcasted, axis=-1))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/scipy/stats/_resampling.py", line 38, in stat_nd
    return np.apply_along_axis(stat_1d, 0, z)[()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/scipy/stats/_resampling.py", line 36, in stat_1d
    return statistic(*data)
           ^^^^^^^^^^^^^^^^
  File "/home/alex/mambaforge/envs/corr_coeff2/lib/python3.11/site-packages/scipy/stats/_stats_py.py", line 4765, in pearsonr
    raise ValueError('x and y must have the same length.')
ValueError: x and y must have the same length.
```

### SciPy/NumPy/Python version and system information

```shell
1.11.0 1.25.0 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/alex/mambaforge/envs/corr_coeff2/include
    lib directory: /home/alex/mambaforge/envs/corr_coeff2/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /home/alex/mambaforge/envs/corr_coeff2/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /home/alex/mambaforge/envs/corr_coeff2/include
    lib directory: /home/alex/mambaforge/envs/corr_coeff2/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /home/alex/mambaforge/envs/corr_coeff2/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /home/alex/mambaforge/envs/corr_coeff2/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687763411006/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  c++:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687763411006/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687763411006/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /home/alex/mambaforge/envs/corr_coeff2/bin/python
  version: '3.11'
```

**Comment by mdhaber** [comment]
Two modifications are needed in your code:

From the documentation:
![image](https://github.com/scipy/scipy/assets/6570539/978a4a20-60dd-4666-bbdf-85661a8e007f)

Also:
![image](https://github.com/scipy/scipy/assets/6570539/b0022031-4a06-4ded-90d3-d820b6831082)


```python3
from scipy import stats
import numpy as np

array1 = np.random.normal(0, 0.1, 20)
array2 = np.random.normal(0, 0.1, 20)

bootstrap_results = stats.bootstrap(
        data=(array1, array2),
        statistic=lambda x, y: stats.pearsonr(x, y).statistic,  # 
        n_resamples=1000,
        confidence_level=0.95,
        paired=True
)

print(bootstrap_results.confidence_interval)
# ConfidenceInterval(low=-0.31903990164497853, high=0.5209791010182264)
```

**Comment by mdhaber** [comment]
And in version 1.11.0 this configuration is done automatically for you if you use the `method` argument.

![image](https://github.com/scipy/scipy/assets/6570539/55a0e8eb-895c-426b-81dd-7118e1d52625)
