### ISSUE TITLE
BUG: RuntimeError when using numpy==1.21.6 with scipy>=1.11

### ISSUE THREAD

**Issue by wagnerpeer** [scipy/scipy#18791]
### Describe your issue.

In a Python 3.9 environment, when I install numpy==1.21.6 and scipy>=1.11 a RuntimeError is thrown when import specifics from scipy.sparse

The error vanishes, when using a higher numpy version (>=1.22) or a lower scipy version (<1.11)

### Reproducing Code Example

```python
from scipy.sparse import issparse
```

### Error message

```shell
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PWagner\.conda\envs\test\lib\site-packages\scipy\sparse\__init__.py", line 274, in <module>
    from ._csr import *
  File "C:\Users\PWagner\.conda\envs\test\lib\site-packages\scipy\sparse\_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.21.6 sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)
C:\Users\PWagner\.conda\envs\test\lib\site-packages\scipy\__config__.py:146: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.35",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.13.1",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-jaj7sx2z\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.10.4",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-hyzuspuy\\cp39-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.9"
  }
}
```

**Comment by andyfaff** [comment]
The minimum numpy version for SciPy 1.11 on windows is 1.22.3

**Comment by wagnerpeer** [comment]
Hey @andyfaff 
I understand the comment, which I assume is correct. But doesn't this mean, that the dependencies are not pinned correctly?

To check my assumption, I opened up the metadata of the scipy==1.11.1 wheel and found the following:
`Requires-Dist: numpy<1.28.0,>=1.21.6`
Is this a bug and does it require a fix?

**Comment by andyfaff** [comment]
When scipy wheels are built we build against a certain numpy version. For Python3.9 on windows we build against numpy 1.22.3. At runtime numpy wheels later than or equal to 1.22.3 is expected to work, but you can't really use earlier versions because of binary compatibility issues.

For windows+python3.9 we choose a minimum numpy of 1.22.3 because of C-runtime issues with earlier numpy wheels (the c-runtime that numpy used didn't play well with the scipy toolchain). Other platforms (linux/macOS) don't have this issue, so we build against an older numpy, down to 1.21.6.

Note that if you really wanted to use scipy==1.11.1 with numpy==1.21.6 with windows+python3.9 then you could do so, you'd just have to build numpy and scipy yourself (with build isolation).

The relevant part is this: https://github.com/scipy/scipy/blob/e24e2da4e0bf8bfa3ce8bb2a6a58a0cf1d871707/pyproject.toml#L31-L38.

There are often issues with these kinds of version specifiers, but I don't think this is one of those occasions.
