### ISSUE TITLE
BUG: `python dev.py bench` fails

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18849]
Trying to run the benchmarks in WSL seems to create an invalid yaml somewhere along the way, which then fails when trying to create a conda environment based on it.

```
$ python dev.py bench --compare main
[...]
conda env create -f /tmp/tmpop7mwsw6.yml -p /mnt/d/upstreams/scipy/benchmarks/env/dc4107ba04c9faab49c4c6d6f6b22097 --force 
   SpecNotFound: /tmp/tmpop7mwsw6.yml is not a valid yaml file.
```

Not sure if this is a problem in asv, conda, WSL, or our dev.py interface, but it keeps me from running benchmarks. 😑 

<details>
<summary>Stacktrace</summary>

```
$ python dev.py bench --compare main
💻  ninja -C /mnt/d/upstreams/scipy/build -j8
ninja: Entering directory `/mnt/d/upstreams/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
    ... installation in progress (0:01:00.304647 elapsed)
    ... installation in progress (0:02:00.372027 elapsed)
    ... installation in progress (0:03:00.858237 elapsed)
    ... installation in progress (0:04:03.360638 elapsed)
    ... installation in progress (0:05:03.789973 elapsed)
    ... installation in progress (0:06:04.172270 elapsed)
    ... installation in progress (0:07:04.543198 elapsed)
    ... installation in progress (0:08:06.025270 elapsed)
    ... installation in progress (0:09:06.506423 elapsed)
    ... installation in progress (0:10:06.932967 elapsed)
Installation OK
SciPy from development installed path at: /mnt/d/upstreams/scipy/build-install/lib/python3.10/site-packages
********************************************************************************
WARNING: you have uncommitted changes --- these will NOT be benchmarked!
********************************************************************************
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Creating environments.
·· Error running /home/user/miniforge3/bin/conda env create -f /tmp/tmpop7mwsw6.yml -p /mnt/d/upstreams/scipy/benchmarks/env/dc4107ba04c9faab49c4c6d6f6b22097 --force (exit status 1)
   STDOUT -------->

   STDERR -------->

   SpecNotFound: /tmp/tmpop7mwsw6.yml is not a valid yaml file.


·· Failure creating environment for conda-py3.10-Cython-meson-python-numpy-pybind11-pytest-pythran
Traceback (most recent call last):
  File "/home/user/miniforge3/envs/scipy-dev/bin/asv", line 10, in <module>
    sys.exit(main())
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/continuous.py", line 75, in run_from_conf_args
    return cls.run(
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/continuous.py", line 114, in run
    result = Run.run(
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/run.py", line 294, in run
    Setup.perform_setup(environments, parallel=parallel)
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/setup.py", line 89, in perform_setup
    list(map(_create, environments))
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/commands/setup.py", line 21, in _create
    env.create()
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/environment.py", line 704, in create
    self._setup()
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/plugins/conda.py", line 174, in _setup
    self._run_conda(['env', 'create', '-f', env_file_name,
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/plugins/conda.py", line 227, in _run_conda
    return util.check_output([conda] + args, env=env)
  File "/home/user/miniforge3/envs/scipy-dev/lib/python3.10/site-packages/asv/util.py", line 754, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/user/miniforge3/bin/conda env create -f /tmp/tmpop7mwsw6.yml -p /mnt/d/upstreams/scipy/benchmarks/env/dc4107ba04c9faab49c4c6d6f6b22097 --force' returned non-zero exit status 1
```

</details>

**Comment by h-vetinari** [comment]
Same problem when running docker on a linux host...

**Comment by h-vetinari** [comment]
@j-bowhay, you recently ran benchmarks successfully in the big factorial PR. How did you do that? Through `dev.py` or through `asv` directly?

**Comment by h-vetinari** [comment]
This looks like an asv bug TBH. I'm finding the same file `/tmp/tmpop7mwsw6`, but asv is looking for `/tmp/tmpop7mwsw6.yml`, i.e. with a `.yml` extension. However, our `environment.yml` currently has a pin `asv <0.5` since https://github.com/scipy/scipy/commit/ef5ee99afe4396de12f3c8f4476e9560df2ed437; I've tested with 0.5.1 and the problem persists.

The upstream asv code in question has been touched recently by @Haozeke - perhaps they can enlighten us?

**Comment by j-bowhay** [comment]
> @j-bowhay, you recently ran benchmarks successfully in the big factorial PR. How did you do that? Through `dev.py` or through `asv` directly?

Using the `dev.py` interface but on Linux

**Comment by h-vetinari** [comment]
I did that now too (new env on vanilla Ubuntu), and it failed in the same way. #18857 at least seems to work for that (well, aside from regressing the benchmarking CI to the point of timing out)
