### ISSUE TITLE
ENH: improve `python dev.py test` experience caused by imp module DeprecationWarning

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#18951]
When I run
```
python dev.py test
```
I get
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
...
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/scikits/umfpack/_umfpack.py", line 15, in swig_import_helper
INTERNALERROR>     import imp
INTERNALERROR>   File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 31, in <module>
INTERNALERROR>     warnings.warn("the imp module is deprecated in favour of importlib and slated "
INTERNALERROR> DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

====================================== no tests ran in 0.11s =======================================
```
This can be circumvented via
```
python dev.py test -- -Wignore
```
It would be nice to
1. Get rid of this deprecation warning.
2. Get some help in the help of dev.py to set the `-Wignore` option.

Full log
<details>

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 334, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 637, in perform_collect
INTERNALERROR>     fspath, parts = resolve_collection_argument(
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 885, in resolve_collection_argument
INTERNALERROR>     strpath = search_pypath(strpath)
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/_pytest/main.py", line 841, in search_pypath
INTERNALERROR>     spec = importlib.util.find_spec(module_name)
INTERNALERROR>   File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/util.py", line 94, in find_spec
INTERNALERROR>     parent = __import__(parent_name, fromlist=['__path__'])
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 410, in <module>
INTERNALERROR>     from ._optimize import *
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 34, in <module>
INTERNALERROR>     from scipy.sparse.linalg import LinearOperator
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 294, in <module>
INTERNALERROR>     from . import csgraph
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
INTERNALERROR>     from ._laplacian import laplacian
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
INTERNALERROR>     from scipy.sparse.linalg import LinearOperator
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/linalg/__init__.py", line 121, in <module>
INTERNALERROR>     from ._dsolve import *
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/__init__.py", line 58, in <module>
INTERNALERROR>     from .linsolve import *
INTERNALERROR>   File "/github/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 15, in <module>
INTERNALERROR>     import scikits.umfpack as umfpack
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/scikits/umfpack/__init__.py", line 12, in <module>
INTERNALERROR>     from .umfpack import *
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/scikits/umfpack/umfpack.py", line 145, in <module>
INTERNALERROR>     from . import _umfpack as _um
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/scikits/umfpack/_umfpack.py", line 28, in <module>
INTERNALERROR>     __umfpack = swig_import_helper()
INTERNALERROR>   File "/github/python3_scipy/lib/python3.10/site-packages/scikits/umfpack/_umfpack.py", line 15, in swig_import_helper
INTERNALERROR>     import imp
INTERNALERROR>   File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 31, in <module>
INTERNALERROR>     warnings.warn("the imp module is deprecated in favour of importlib and slated "
INTERNALERROR> DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

====================================== no tests ran in 0.11s =======================================
```

</details>

**Comment by tupui** [comment]
Thank you for reporting @lorentzenchr

We had a similar report here #18912

The specific issue is that `umfpack` installs SciPy as well and you need to uninstall it.

To your proposal, I am not sure about adding the option itself. But it might be a good thing to add in the doc that one can do that.
