### ISSUE TITLE
BUG: dev.py has issues with site-packages and Python installed by homebrew.

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#18998]
### Describe your issue.

I'm trying to use a homebrew installed Python3.10. Homebrew Python is found in: `/opt/homebrew/opt/python@3.10/libexec/bin`

It loads site-packages from `/opt/homebrew/lib/python3.10/site-packages`

I add the latter to `PYTHONPATH`.  When I try to call `dev.py` I get the error below, which is resolving paths incorrectly.

@AnirudhDagar, you may be able to help.

### Reproducing Code Example

```python
python dev.py
```

### Error message

```shell
python dev.py build -j3
Traceback (most recent call last):
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/dev.py", line 1517, in <module>
    cli()
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pydevtool/cli.py", line 267, in callback
    sys.exit(self.run_doit_task.__func__({name: kwargs}))
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/dev.py", line 251, in run_doit_task
    return run_tasks(loader, tasks, extra_config={'GLOBAL': doit_config})
  File "/opt/homebrew/lib/python3.10/site-packages/doit/api.py", line 50, in run_tasks
    return command.parse_execute(task_names)
  File "/opt/homebrew/lib/python3.10/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/opt/homebrew/lib/python3.10/site-packages/doit/cmd_base.py", line 556, in execute
    self.task_list = self.loader.load_tasks(cmd=self, pos_args=args)
  File "/opt/homebrew/lib/python3.10/site-packages/doit/cmd_base.py", line 355, in load_tasks
    tasks = loader.load_tasks(
  File "/opt/homebrew/lib/python3.10/site-packages/doit/loader.py", line 222, in load_tasks
    _process_gen(ref, creator_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/doit/loader.py", line 169, in _process_gen
    gen_tasks = generate_tasks(name, ref(**creator_kwargs), ref.__doc__)
  File "/opt/homebrew/lib/python3.10/site-packages/pydevtool/cli.py", line 191, in creator
    task_meta = cls.task_meta(**kwargs)
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/dev.py", line 1077, in task_meta
    dirs = Dirs(build_args)
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/dev.py", line 318, in __init__
    self.site = self.get_site_packages()
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/dev.py", line 349, in get_site_packages
    return self.installed / plat_path.relative_to(sys.exec_prefix)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/opt/homebrew/lib/python3.10/site-packages' is not in the subpath of '/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10' OR one path is relative and the other is absolute.
```

### SciPy/NumPy/Python version and system information

```shell
python3.10
```

**Comment by AnirudhDagar** [comment]
Sorry, I'll be able to look at this only on Thursday. Don't have a laptop with me at the moment (out hiking).

**Comment by rgommers** [comment]
No worries - enjoy the outdoors Anirudh!

**Comment by andyfaff** [comment]
> Hmm, those seem like odd paths, and I haven't seen this error message before I think. Is this new after a Homebrew update

@rgommers, these aren't new errors, I've seen them for a while, but worked around them. I experienced them in the cirrus `macos_arm64_test_task` configuration.

I install Python 3.10 using homebrew, make a symlink to the Python location so I can start Python up, then I pip install all the build dependencies. When I run dev.py I get the errors reported above. The only way to avoid the error message is to use a venv, which will put site-packages in a 'normal place' compared to the Python location.

Without the venv homebrew's site-packages are in a much different place to where the Python location is. dev.py doesn't account for that, but probably should.

**Comment by czgdp1807** [comment]
I cna verify that this is fixed in #21674
