### ISSUE TITLE
BUG: Build Fails on Ubuntu 22.04 with `AssertionError: Bad argument number for Assign: 3, expecting 2`

### ISSUE THREAD

**Issue by Pranavchiku** [scipy/scipy#19017]
### Describe your issue.

I am trying to build SciPy on Ubuntu 22.04 ( dual boot with Windows ). I am following the below given steps
```
git clone https://github.com/scipy/scipy
cd scipy
mamba env create -f environment.yml --force
conda activate scipy-dev 
git submodule update --init
python dev.py test
```

### Reproducing Code Example

```python
NA
```

### Error message

```shell
% python dev.py test
....
[796/1588] Generating scipy/stats/_stats_pythran with a custom command
FAILED: scipy/stats/_stats_pythran.cpp 
/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/bin/pythran -E ../scipy/stats/_stats_pythran.py -o scipy/stats/_stats_pythran.cpp
Traceback (most recent call last):
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/run.py", line 180, in run
    pythran.compile_pythranfile(args.input_file,
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/toolchain.py", line 499, in compile_pythranfile
    output_file = compile_pythrancode(module_name, fd.read(),
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/toolchain.py", line 400, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/toolchain.py", line 143, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/toolchain.py", line 110, in front_middle_end
    refine(pm, ir, optimizations, report_times)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/middlend.py", line 27, in refine
    pm.apply(NormalizeTuples, node, run_times)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 243, in apply
    ret=a.apply(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 200, in apply
    new_node = self.run(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 189, in run
    n = super(Transformation, self).run(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 97, in run
    return self.visit(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/ast.py", line 494, in generic_visit
    value = self.visit(value)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/transformations/normalize_tuples.py", line 198, in visit_FunctionDef
    return self.generic_visit(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/ast.py", line 494, in generic_visit
    value = self.visit(value)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/pranavchiku/mambaforge-pypy3/envs/scipy-dev/lib/python3.10/site-packages/pythran/transformations/normalize_tuples.py", line 157, in visit_Assign
    ast.Assign(
  File "/home/pranavchiku/.local/lib/python3.10/site-packages/gast/gast.py", line 17, in create_node
    assert nbparam in (0, len(Fields)), \
AssertionError: Bad argument number for Assign: 3, expecting 2
[799/1588] Compiling C++ object scipy/sparse/s...ls.cpython-310-x86_64-linux-gnu.so.p/bsr.cxx.o
ninja: build stopped: subcommand failed.
Build failed!
```

### SciPy/NumPy/Python version and system information

```shell
Ubuntu 22.04 Booted directly
x86 system
```

**Comment by certik** [comment]
Thanks @Pranavchiku. Can you also specify if this is Ubuntu inside WSL on Windows, or is it booted directly into Ubuntu? Also are you on x86 or arm?

How exactly did you install conda? I see `mambaforge-pypy3` in the paths. I've never use that, but it might be using pypy, not CPython. Can you install mamba using the links here: https://github.com/conda-forge/miniforge#mambaforge, no `pypy`.

**Comment by Pranavchiku** [comment]
> Can you also specify if this is Ubuntu inside WSL on Windows, or is it booted directly into Ubuntu?

Booted directly into Ubuntu

> Also are you on x86 or arm?

x86

> Can you install mamba using the links here: https://github.com/conda-forge/miniforge#mambaforge, no pypy

I installed it from there only, let me see if I can do something there.

**Comment by Pranavchiku** [comment]
```console
% python 
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by certik** [comment]
Your `python` seems to be regular CPython. Maybe it's the base environment that is pypy based. Try to install mambaforge from the link I sent you, which will be installed into `/home/pranavchiku/mambaforge`, which is what I do and that works for me.

**Comment by Pranavchiku** [comment]
> Try to install mambaforge from https://github.com/conda-forge/miniforge#mambaforge

Yes, with this. It worked. Thanks @certik ! :)

**Comment by certik** [comment]
Excellent, I am glad it is resolved.
