### ISSUE TITLE
BUG: <Compilation of scipy 11.1 falls with python3.12>

### ISSUE THREAD

**Issue by Kadelka** [scipy/scipy#19022]
### Describe your issue.

I installed python3.12 rc1 and tried to install some modules. numpy: -- no problems
scipy results in errors which I cannot solve.
(python3.8 - python3.11 no problems)
I don't know if this is a topic for scipy,python3.12rc1 or cython

### Reproducing Code Example

```python
python setup.py install
```

### Error message

```shell
Note: for reliable uninstall behaviour and dependency installation
and uninstallation, please use pip instead of using
`setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


/giga/install/python312/scipy-1.11.1/setup.py:506: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.core import setup
Cythonizing sources
Running scipy/linalg/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
Running scipy/special/_generate_pyx.py
Processing scipy/linalg/_decomp_update.pyx.in
Processing scipy/linalg/cython_blas.pyx
warning: _decomp_update.pyx:50:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/linalg/_matfuncs_expm.pyx.in
Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
Processing scipy/linalg/_solve_toeplitz.pyx
Processing scipy/linalg/_cythonized_array_utils.pyx
Processing scipy/linalg/cython_lapack.pyx
Processing scipy/linalg/_decomp_lu_cython.pyx
Processing scipy/spatial/_qhull.pyx
Processing scipy/spatial/_ckdtree.pyx
Processing scipy/spatial/_hausdorff.pyx
warning: _ckdtree.pyx:1627:5: Only extern functions can throw C++ exceptions.
Processing scipy/spatial/_voronoi.pyx
Processing scipy/spatial/transform/_rotation.pyx
warning: _voronoi.pyx:22:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/signal/_peak_finding_utils.pyx
Processing scipy/signal/_sosfilt.pyx
Processing scipy/signal/_max_len_seq_inner.pyx
Processing scipy/signal/_upfirdn_apply.pyx
Processing scipy/signal/_spectral.pyx
Processing scipy/stats/_qmc_cy.pyx
Processing scipy/stats/_stats.pyx
warning: _stats.pyx:36:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/stats/_sobol.pyx
warning: _sobol.pyx:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _sobol.pyx:15:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/stats/_biasedurn.pyx
Processing scipy/stats/_boost/src/invgauss_ufunc.pyx
Processing scipy/stats/_boost/src/skewnorm_ufunc.pyx
Processing scipy/stats/_boost/src/binom_ufunc.pyx
Processing scipy/stats/_boost/src/beta_ufunc.pyx
Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
Processing scipy/stats/_boost/src/ncx2_ufunc.pyx
Processing scipy/stats/_boost/src/nct_ufunc.pyx
Processing scipy/stats/_boost/src/ncf_ufunc.pyx
Processing scipy/stats/_boost/src/hypergeom_ufunc.pyx
Processing scipy/stats/_rcont/rcont.pyx
Processing scipy/stats/_unuran/unuran_wrapper.pyx
Processing scipy/stats/_levy_stable/levyst.pyx
Processing scipy/cluster/_hierarchy.pyx
Processing scipy/cluster/_optimal_leaf_ordering.pyx
Processing scipy/cluster/_vq.pyx
Processing scipy/fftpack/convolve.pyx
warning: _vq.pyx:29:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/_csparsetools.pyx.in
Processing scipy/sparse/csgraph/_tools.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/csgraph/_reordering.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/csgraph/_flow.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/csgraph/_traversal.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _traversal.pyx:668:4: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _traversal.pyx:669:4: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _traversal.pyx:778:4: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _traversal.pyx:779:4: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/sparse/csgraph/_shortest_path.pyx
Processing scipy/sparse/csgraph/_matching.pyx
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:14:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: parameters.pxi:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/ndimage/src/_cytest.pyx
Processing scipy/io/matlab/_streams.pyx
warning: _streams.pyx:20:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/io/matlab/_mio5_utils.pyx
Processing scipy/io/matlab/_mio_utils.pyx
warning: _mio5_utils.pyx:54:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _mio5_utils.pyx:56:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: _mio5_utils.pyx:58:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
Processing scipy/optimize/_bglu_dense.pyx
Processing scipy/optimize/_group_columns.pyx
Processing scipy/optimize/cython_optimize/_zeros.pyx.in
Processing scipy/optimize/_trlib/_trlib.pyx

Error compiling Cython file:
------------------------------------------------------------
...

# The following cimport statement provides legacy ABI
# support. Changing it causes an ABI forward-compatibility break
# (gh-11793), so we currently leave it as is (no further cimport
# statements should be used in this file).
from .cython_optimize._zeros cimport (
^
------------------------------------------------------------

/giga/install/python312/scipy-1.11.1/scipy/optimize/cython_optimize.pxd:10:0: 'scipy/optimize/cython_optimize/cython_optimize/_zeros.pxd' not found
Traceback (most recent call last):
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 353, in <module>
    main()
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 349, in main
    find_process_files(root_dir)
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 337, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 337, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
                                                   ^^^^^^^^^^^^^^
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 266, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 155, in process_tempita_pyx
    process_pyx(pyxfile, tofile, cwd)
  File "/giga/install/python312/scipy-1.11.1/tools/cythonize.py", line 118, in process_pyx
    raise Exception('Cython system call failed:\n'
Exception: Cython system call failed:
 cython --fast-fail -3 -o _zeros.c _zeros.pyx
Processing scipy/optimize/tnc/_moduleTNC.pyx
Running from SciPy source directory.
Traceback (most recent call last):
  File "/giga/install/python312/scipy-1.11.1/setup.py", line 532, in <module>
    setup_package()
  File "/giga/install/python312/scipy-1.11.1/setup.py", line 516, in setup_package
    generate_cython()
  File "/giga/install/python312/scipy-1.11.1/setup.py", line 265, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

### SciPy/NumPy/Python version and system information

```shell
ModuleNotFoundError: No module named 'scipy'
```

**Comment by lmmx** [comment]
What version of Cython are you running? It appears to be erroring on the same line as #19026 which was due to the Cython version bump to 3.0 (and was resolved by pinning `Cython<3`)

**Comment by rgommers** [comment]
Please build with `pip install scipy` and stop using `setup.py install`. That way you'll get the proper build dependency handling.

**Comment by Kadelka** [comment]
Since it seems too early trying to use python3.12  I'll close this issue until the official python3.12, if there are still problems.
