### ISSUE TITLE
BUG: non-deterministic NaN values in `scipy.integrate.solve_ivp` when compiling function with `numba`

### ISSUE THREAD

**Issue by abulenok** [scipy/scipy#19031]
### Describe your issue.

- the behaviour is non-deterministic (usually enough to run 100 times to reproduce)
- occurs only when using “BDF” method in scipy.integrate.solve_ivp
- to experience error, it’s enough to compile a function with numba, no need to use it in the code
- occurs both when using @jit and @njit functions, but does not happen, when NUMBA_DISABLE_JIT=1
- seems to occur only on Linux systems (checked only on Debian-based), never observed on Windows or macOS
- setting the fastmath option to True does not change the behaviour
- the problem has been around since at least two-three years (hundreds of occurrences logged on GitHub actions CI) cc @slayoo @piotrbartman

We also submitted an issue to numba some time ago, please see https://github.com/numba/numba/issues/8931 for relevant discussion

### Reproducing Code Example

```python
Code to reproduce a bug:

.py
import scipy.integrate
import numba
import numpy as np
import warnings

@numba.njit("int32(int32)")
def jitted_fun(x):
    return 1

def f(_, y):
  return np.zeros_like(y)

y0 = np.ones(2)

with warnings.catch_warnings(record=True):
    warnings.simplefilter("error")
    for _ in range(100):
        scipy.integrate.solve_ivp(fun=f, t_span=(0, 1), y0=y0, method="BDF")


example Dockerfile to reproduce the issue:
```Dockerfile
FROM ubuntu:22.04
WORKDIR /app
COPY numba_scipy_err.py ./numba_scipy_err.py
RUN apt-get update && apt-get -y install python3.9 && apt-get -y install python3-pip
RUN pip install numba numpy scipy

CMD ["/bin/bash", "-c", "for run in {1..100}; do python3 numba_scipy_err.py; done"]
```
```


### Error message

```shell
Traceback (most recent call last):
  File "/app/numba_scipy_bug.py", line 18, in <module>
    scipy.integrate.solve_ivp(fun=f, t_span=(0, 1), y0=y0, method="BDF")
  File "/usr/local/lib/python3.10/dist-packages/scipy/integrate/_ivp/ivp.py", line 591, in solve_ivp
    message = solver.step()
  File "/usr/local/lib/python3.10/dist-packages/scipy/integrate/_ivp/base.py", line 181, in step
    success, message = self._step_impl()
  File "/usr/local/lib/python3.10/dist-packages/scipy/integrate/_ivp/bdf.py", line 407, in _step_impl
    D[order + 2] = d - D[order + 1]
RuntimeWarning: invalid value encountered in subtract
```
```


### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.24.4 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
/usr/local/lib/python3.10/dist-packages/scipy/__config__.py:146: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.35",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.13.1",
      "include directory": "../../tmp/pip-build-env-hy2eo89f/overlay/lib/python3.10/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.10.4",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp310-cp310/bin/python",
    "version": "3.10"
  }
}
```

**Comment by abulenok** [comment]
New Github Actions run depicting the problem:

https://github.com/slayoo/numba_issue_8931/actions/runs/5802580385/job/15729193807
