### ISSUE TITLE
cannot import name 'QhullError' from 'scipy.spatial'

### ISSUE THREAD

**Issue by onesmallwhite** [scipy/scipy#19096]
### Describe your issue.

The version I installed is 1.5.0. What is the reason for this issue? Can you help me answer it? Thank you

### Reproducing Code Example

```python
def compute_2d_bbox_xywh_from_pose(points, pose, K, width=640, height=480, clip=False):
Traceback (most recent call last):
  File "core/self6dpp/main_self6dpp.py", line 36, in <module>
    from core.self6dpp.datasets.dataset_factory import register_datasets_in_cfg
  File "/home/zhumengjie/self6dpp/core/self6dpp/../../core/self6dpp/datasets/dataset_factory.py", line 11, in <module>
    from core.self6dpp.datasets import (
  File "/home/zhumengjie/self6dpp/core/self6dpp/../../core/self6dpp/datasets/lm_dataset_d2.py", line 22, in <module>
    from lib.utils.mask_utils import binary_mask_to_rle, cocosegm2mask
  File "/home/zhumengjie/self6dpp/core/self6dpp/../../lib/utils/mask_utils.py", line 12, in <module>
    from skimage.morphology import binary_dilation as _binary_dilation_sk
  File "/home/zhumengjie/anaconda3/envs/self6d/lib/python3.8/site-packages/skimage/morphology/__init__.py", line 12, in <module>
    from .convex_hull import convex_hull_image, convex_hull_object
  File "/home/zhumengjie/anaconda3/envs/self6d/lib/python3.8/site-packages/skimage/morphology/convex_hull.py", line 4, in <module>
    from scipy.spatial import ConvexHull, QhullError
ImportError: cannot import name 'QhullError' from 'scipy.spatial' (/home/zhumengjie/anaconda3/envs/self6d/lib/python3.8/site-packages/scipy/spatial/__init__.py)
```

### Error message

```shell
cannot import name 'QhullError' from 'scipy.spatial'
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy
>>> print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0 1.23.0 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
>>> scipy.show_config()
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
>>>
```

**Comment by lucascolley** [comment]
Hi @onesmallwhite, it looks like `QhullError` is only exposed in the `scipy.spatial` namespace from SciPy 1.8 onwards. So you won't be able to import it this way in SciPy 1.5.

**Comment by lucascolley** [comment]
Your traceback includes a scikit-image call to `skimage.morphology`. Do you know which version of scikit-image you are using? From a quick look, I think that the most version to support SciPy 1.5 is v0.19. v0.20 and beyond require SciPy >= 1.8

**Comment by rgommers** [comment]
Thanks for the answers here @lucascolley! They look correct to me, so this is a case of version mismatching. Upgrading SciPy should make the problem go away. There's no bug here, so I'll close the issue.
