### ISSUE TITLE
BUG: optimize.shgo: args/jac passed to minimizer incorrectly

### ISSUE THREAD

**Issue by arthus701** [scipy/scipy#19182]
### Describe your issue.

Hey everyone,
some combination of issues  #12114, #13547 and #12963 seems to persist after #16313. I'm trying to evaluate the jacobian only in the local minimizer, but the combination of `args` and `'jac': True` throws an error. I can provide more context if necessary.

Using `minimize` alone works as expected.

If I change the default value of `jac` in `func` to `True` everything works fine, but then the jacobian is evaluated every time the function is called.

Thanks,
Arthus

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import shgo, minimize


def func(x, jac=False):
    val = np.sum(np.power(x, 2))
    if jac:
        return val, 2 * x
    return val


bounds = np.array([
    [-1, 1],
    [1, 2],
    [-1, 1],
])

# works fine:
minimize(
    func,
    (1, 1, 1),
    args=(True, ),
    jac=True,
    bounds=bounds,
    method='TNC',
)

shgo(
    func,
    bounds=bounds,
    n=100,
    iters=5,
    minimizer_kwargs={
        'method': 'TNC',
        'args': (True, ),
        'jac': True,
    },
)
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/arthus/Documents/mcmc/est/shgo_mwe.py", line 12, in <module>
    shgo(
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo.py", line 454, in shgo
    shc.iterate_all()
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo.py", line 832, in iterate_all
    self.iterate()
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo.py", line 1004, in iterate
    self.iterate_complex()
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo.py", line 1053, in iterate_hypercube
    self.HC.V.process_pools()
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 327, in process_pools
    self.process_fpool()
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 384, in proc_fpool_nog
    self.compute_sfield(v)
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 347, in compute_sfield
    v.f = self.field(v.x_a, *self.field_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/_lib/_util.py", line 360, in __call__
    return self.f(x, *self.args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "/home/arthus/miniforge3/envs/torch/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 72, in _compute_if_needed
    self.jac = fg[1]
               ~~^^^
IndexError: invalid index to scalar variable.
```

### SciPy/NumPy/Python version and system information

```shell
scipy version: 1.11.2 
numpy version: 1.25.2 
sys.version_info(major=3, minor=11, micro=0, releaselevel='final', serial=0)


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-tshsyzfz/overlay/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by andyfaff** [comment]
I don't think this is possible. At the start of the [`SHGO`](https://github.com/scipy/scipy/blob/main/scipy/optimize/_shgo.py#L497) initialisation the objective function is inspected, along with whether `minimizer_kwargs['jac'] is True`. If that's the situation then `func` is assumed to return `f, g`, and treated as such in the rest of the codebase. It's assumed not to return one thing in the local minimiser and another thing in the main SHGO code.

**Comment by arthus701** [comment]
Alright. From the docs I figured i could use `args` in the `minimizer_kwargs` to get what I want, as there's no statement about a "global" consequence of passing `'jac': True`. Having `jac` as an option for the `shgo` function was a bit confusing here, but what I do seems to be a very special case, so I'm not sure if it's worth thinking about updating the docs...Thanks for your reply, feel free to close the issue.

**Comment by andyfaff** [comment]
If you already know how to calculate grad, then you should be able to write wrappers that provide a separate func and grad, but can also share any memoisation and calculation. That's effectively what MemoizeJac is doing.
