### ISSUE TITLE
AttributeError: 'No module named stats.goodness_of_fit' 

### ISSUE THREAD

**Issue by cppt** [scipy/scipy#19339]
### Describe your issue.

Getting a weird attribute error when trying to access the goodness_of_fit method from within scipy.stats.

```
res = st.goodness_of_fit(st.levy, y, {'loc': pars[1], 'scale': pars[2]} )
Traceback (most recent call last):

  File "/tmp/ipykernel_120390/4259087146.py", line 1, in <module>
    res = st.goodness_of_fit(st.levy, y, {'loc': pars[1], 'scale': pars[2]} )

AttributeError: module 'scipy.stats' has no attribute 'goodness_of_fit'
```

Aware scipy doesn't load all subpackages by default given its size, so have tried importing it explicitly with a similar looking error thrown:

```
import scipy.stats.goodness_of_fit as gof
Traceback (most recent call last):

  File "/tmp/ipykernel_120390/2442245245.py", line 1, in <module>
    import scipy.stats.goodness_of_fit as gof

ModuleNotFoundError: No module named 'scipy.stats.goodness_of_fit'`

from scipy.stats import goodness_of_fit
Traceback (most recent call last):

  File "/tmp/ipykernel_120390/3907032109.py", line 1, in <module>
    from scipy.stats import goodness_of_fit

ImportError: cannot import name 'goodness_of_fit' from 'scipy.stats' (/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/__init__.py)
```

Imagine this is user error but not clear how given scipy appears up to date and goodness_of_fit appears to exist within the codebase.  Any ideas?

### Reproducing Code Example

```python
from scipy.stats import goodness_of_fit
```

### Error message

```shell
Traceback (most recent call last):

  File "/tmp/ipykernel_120390/3907032109.py", line 1, in <module>
    from scipy.stats import goodness_of_fit

ImportError: cannot import name 'goodness_of_fit' from 'scipy.stats' (/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/__init__.py)
```

### SciPy/NumPy/Python version and system information

```shell
scipy                         1.9.1
numpy                         1.21.5
numpydoc                      1.4.0
Python 3.9.13
OS Ubuntu 22.04
```

**Comment by rkern** [comment]
It was [introduced in scipy 1.10.0](https://docs.scipy.org/doc/scipy-1.10.0/release.1.10.0.html#scipy-stats-improvements) while you have 1.9.1.
