### ISSUE TITLE
BUG: parameter 'args' of optimize.root_scalar() is not usable

### ISSUE THREAD

**Issue by Menginventor** [scipy/scipy#19343]
### Describe your issue.

I can't pass varible to parameter 'args' because it missmatch with 'root_scalar.<locals>.fprime()' and got this error
`TypeError: root_scalar.<locals>.fprime() takes 1 positional argument but 2 were given`

From now is my investigation.

The problem occur at `scipy\optimize\_root_scalar.py` at line 303

```
        if not fprime:
            # approximate fprime with finite differences

            def fprime(x):
                # `root_scalar` doesn't actually seem to support vectorized
                # use of `newton`. In that case, `approx_derivative` will
                # always get scalar input. Nonetheless, it always returns an
                # array, so we extract the element to produce scalar output.
                return approx_derivative(f, x, method='2-point')[0]
```

As you see, when user not specified `fprime`, it will create `fprime` based on `approx_derivative` which i believed it is finite difference. BTW, this new `fprime` doesn't care about arguments given from the parameter  `args` so it result in argument missmatch.

### Reproducing Code Example

```python
import scipy.optimize as optimize
import scipy
def cost_func(x):
    return (x-1) **2
def cost_func_args(x,args):
    return (x-1) **2

sol = optimize.root_scalar(cost_func, x0=0)

print(scipy.__version__)
print(sol)
sol = optimize.root_scalar(cost_func_args, x0=0,args=(None))
print(sol)
```

### Error message

```shell
1.11.2
      converged: True
           flag: converged
 function_calls: 54
     iterations: 27
           root: 0.9999999894647739
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\neural_vis\scipy_bug.py", line 14, in <module>
    sol = optimize.root_scalar(cost_func_args, x0=0,args=(None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_root_scalar.py", line 315, in root_scalar
    r, sol = methodc(f, x0, args=args, fprime=fprime, fprime2=None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_zeros_py.py", line 306, in newton
    fder = fprime(p0, *args)
           ^^^^^^^^^^^^^^^^^
TypeError: root_scalar.<locals>.fprime() takes 1 positional argument but 2 were given
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.25.2 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-ltcmez9y\overlay\Lib\site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-j5_khsjf\cp311-win_amd64\build\venv\Scripts\python.exe
  version: '3.11'
```

**Comment by mdhaber** [comment]
This was fixed by gh-19091. The code is now:

https://github.com/scipy/scipy/blob/f1e00700f2143158c6f08a426fdc097dea3a0c37/scipy/optimize/_root_scalar.py#L46-L50

but it was not backported to 1.11.2 because the milestone was added as 1.12.0. The fix will be present in 1.12.0
