### ISSUE TITLE
BUG: DiscreteAliasUrn construction fails with UNURANError for certain innocuous PVs

### ISSUE THREAD

**Issue by colehaus** [scipy/scipy#19359]
### Describe your issue.

Certain seemingly arbitrary PVs cause `DiscreteAliasUrn` to crash during construction with an UNURANError.

### Reproducing Code Example

```python
import scipy as sp
from scipy.stats.sampling import DiscreteAliasUrn
import numpy as np

DiscreteAliasUrn(sp.special.softmax(np.ones((1531,))), random_state=None) # Fine
DiscreteAliasUrn(sp.special.softmax(np.ones((1533,))) * 10, random_state=None) # Fine
DiscreteAliasUrn(sp.special.softmax(np.ones((1533,))), random_state=None) # Error
```

### Error message

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "scratch.py", line 7, in <module>
    DiscreteAliasUrn(sp.special.softmax(np.ones((1533,))), random_state=None)
  File "unuran_wrapper.pyx", line 2404, in scipy.stats._unuran.unuran_wrapper.DiscreteAliasUrn.__cinit__
  File "unuran_wrapper.pyx", line 443, in scipy.stats._unuran.unuran_wrapper.Method._set_rng
scipy.stats._unuran.unuran_wrapper.UNURANError: [objid: DAU.003] 240 : unknown error! => error should not happen, report this!
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3
1.26.0
sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-358nkn7q/overlay/lib/python3.11/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by tirthasheshpatel** [comment]
Thanks for the report @colehaus! I confirmed that this is an error in UNU.RAN. It happens because of floating point errors in the computation of the urn table.

**Comment by colehaus** [comment]
Thanks!

**Comment by mdhaber** [comment]
@colehaus if you are able to build a feature branch, can you see whether gh-19364 resolves this for you?
