### ISSUE TITLE
BUG: optimize: warning generated by SLSQP is useless

### ISSUE THREAD

**Issue by MLopez-Ibanez** [scipy/scipy#19362]
https://github.com/scipy/scipy/blob/166e1f2b1ea0a1a2c3d7b030bd829549f8a5844a/scipy/optimize/_optimize.py#L422-L429

The above code generates a warning for some calls to SLSQP (see https://github.com/scipy/scipy/issues/11403#issuecomment-717676023). 

Users cannot do anything with this warning, as the reason for the warning is due to the implementation of SLSQP. The warning is also not informative as the result is correct always, so the message is not warning about any potential problem.

Perhaps scipy developers want to keep the warning during development in case it may catch some unexpected effects of a patch, but it should not be given to users.

**Comment by ilayn** [comment]
There is some development going on to write this in pure Python and after holidays, I am hoping to get the first version out this week. Then we can address this in a better fashion. I'll add this to the list in #19130

**Comment by ilayn** [comment]
In the meantime, would it be possible for you @MLopez-Ibanez to give us a relatively simple example that generates such warnings? I would love to have more test use-cases from the field out there.

**Comment by MLopez-Ibanez** [comment]
My use case is quite complicated. The last line here generates the problem: https://github.com/MLopez-Ibanez/AsteroidRoutingProblem/blob/43100624442f78d0cd79c22746961116df381f76/transfer_example.py#L58

I could track the x and f values and produce a reproducible testcase, but it will be quite sensitive to any rounding.

**Comment by ilayn** [comment]
If you can do that, it would be great. Otherwise, tough luck, we'll find another way.

**Comment by MLopez-Ibanez** [comment]
Need the `.npy` file: 
[bug-19362.npy.zip](https://github.com/scipy/scipy/files/12845202/bug-19362.npy.zip)

Hopefully it works on your end!

```python
import numpy as np
from scipy.optimize import minimize
import warnings
warnings.filterwarnings("error")

cache = np.load("bug-19362.npy")

def fun(x):
    index = np.equal(cache[:,0:2], x).all(axis=1)
    print(index)
    f = cache[index,2]
    if (len(f) != 1):
        print(f'Could not find {x} in the cache')
        assert False
    return f[0]

res = minimize(fun, x0 = [0,30], bounds = ((0,730), (0.01,730)), method = 'SLSQP',
                       options = dict(maxiter=1000))
```

**Comment by andyfaff** [comment]
> Users cannot do anything with this warning, as the reason for the warning is due to the implementation of SLSQP. The warning is also not informative as the result is correct always, so the message is not warning about any potential problem.

The ultimate reason for the clipping is because some user functions absolutely don't want to access outside bounds. THe warning was inserted because clipping is not part of the optimisation algorithm, and it wasn't clear if clipping would adversely affect the minimisation. At the moment it seems to be only SLSQP that uses that specific clipping function.

If the SLSQP iteration could be improved to avoid the clipping that would be even better.

**Comment by ilayn** [comment]
> Hopefully it works on your end!

Yes I can also generate the warning, thank you for the example @MLopez-Ibanez. We are not a big fun of zip attachments due to security reasons. So I've edited your example with the raw data instead for others.

**Comment by ilayn** [comment]
In the new version of SLSQP #22524 I am now getting the following output 

```
[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
[False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
[False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
h1 , h2, acc =  287.62065368484763894,    0.00000000000000000,    0.00000100000000000
[False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
*funx , f0, acc =  324.44191198093199091,  507.86729214661846754,    0.00000100000000000
s norm, acc =   16.95938246767398283,    0.00000100000000000
[False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
[False False False False False  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
h1 , h2, acc =   80.02441750163561096,    0.00000000000000000,    0.00000100000000000
[False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
*funx , f0, acc =  260.37720189168533125,  324.44191198093199091,    0.00000100000000000
s norm, acc =   11.61088984391403933,    0.00000100000000000
[False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
[False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
h1 , h2, acc =   91.44792608315394489,    0.00000000000000000,    0.00000100000000000
[False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
*funx , f0, acc =  192.99746069668549353,  260.37720189168533125,    0.00000100000000000
s norm, acc =   20.70789887113065575,    0.00000100000000000
[False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
[False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
h1 , h2, acc =   58.84072998181901681,    0.00000000000000000,    0.00000100000000000
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False]
Could not find [  1.74503441 103.81590689] in the cache
Traceback (most recent call last):
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\warning_test.py", line 17, in <module>
    res = minimize(fun, x0 = [0,30], bounds = ((0,730), (0.01,730)), method = 'SLSQP',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_minimize.py", line 763, in minimize        
    res = _minimize_slsqp(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_slsqp_py.py", line 472, in _minimize_slsqp 
    fx = wrapped_fun(x)
         ^^^^^^^^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_optimize.py", line 325, in eval
    return func(x)
           ^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 384, in 
fun
    self._update_fun()
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 352, in 
_update_fun
    fx = self._wrapped_fun(self.x)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\scipy\_lib\_util.py", line 665, in __call__
    fx = self.f(np.copy(x), *self.args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ilhan\Documents\GitHub\scipy\build-install\Lib\site-packages\warning_test.py", line 14, in fun
    assert False
AssertionError
```

Is this something expected @MLopez-Ibanez ?

**Comment by MLopez-Ibanez** [comment]
If the code has been rewritten and the sequence of points visited is not the same, then you will get the above error. It may be worth mentioning that previous results may not be reproducible with the new version.

**Comment by MLopez-Ibanez** [comment]
Using the code in https://github.com/scipy/scipy/issues/19362#issuecomment-1752797201 I can reproduce the warning with scipy '1.13.0'.

**Comment by ilayn** [comment]
>  It may be worth mentioning that previous results may not be reproducible with the new version.

Yes but a floating point number look up is almost never possible if there is a change in the toolchain so bit flips can happen even with the same code but different architecture. I'll try to convert it into an approximate equality test.

**Comment by ilayn** [comment]
I checked this again and I can't get it to perform a floating point lookup. Also I'm not sure I understand what @andyfaff reasoned above about the clipping. But if there is anything needed to be added to low level code I can add.

**Comment by MLopez-Ibanez** [comment]
If the code that gives the warning is gone in the new implementation or it is only given when some debug option is enabled, then that should be fine in my opinion.

**Comment by ilayn** [comment]
The check is done at the low level code and there is no possibility of hitting this warning
