### ISSUE TITLE
differential_evolution raises OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by gellnerm** [scipy/scipy#19397]
### Describe your issue.

Differential_evolution() raises an
OSError: [Errno 24] Too many open files
when called in a loop. I thought that the reason is that the multiprocessing.Pool is not joined in [_util.py](https://github.com/scipy/scipy/tree/main/scipy/_lib/_util.py) and that the fix would be

```
    def __exit__(self, exc_type, exc_value, traceback):
        if self._own_pool:
            self.pool.close()
            **self.pool.join()**
            self.pool.terminate()
```
in the MapWrapper class. But that did not fix the issue.

### Reproducing Code Example

```python
def f(a, b):
    return 1

for i in range(1000):
    print(f'round {i}')
    differential_evolution(f, x0=[.0108, .0886, .01005, 0.], maxiter=500, bounds=[(.01, .4), (.01, .4), (.01, .4), (-.6, .6)], args=(1,), workers=16, disp=False)

output:
...
round 487
round 488
<exception>
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/user/Dokumente/Devel/test/./main.py", line 129, in <module>
  File "/home/user/Dokumente/Devel/test/./main.py", line 125, in main
  File "/home/user/Dokumente/Devel/test/./main.py", line 92, in test
  File "/home/user/Dokumente/Devel/test/mod.py", line 92, in mod
  File "/home/user/miniconda3/envs/test/lib/python3.11/site-packages/scipy/optimize/_differentialevolution.py", line 387, in differential_evolution
  File "/home/user/miniconda3/envs/test/lib/python3.11/site-packages/scipy/optimize/_differentialevolution.py", line 663, in __init__
  File "/home/user/miniconda3/envs/test/lib/python3.11/site-packages/scipy/_lib/_util.py", line 399, in __init__
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/context.py", line 119, in Pool
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/pool.py", line 215, in __init__
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/pool.py", line 306, in _repopulate_pool
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/pool.py", line 329, in _repopulate_pool_static
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/process.py", line 121, in start
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/context.py", line 281, in _Popen
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/user/miniconda3/envs/test/lib/python3.11/multiprocessing/popen_fork.py", line 65, in _launch
OSError: [Errno 24] Too many open files
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.11.2 1.24.4 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-tshsyzfz/overlay/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by andyfaff** [comment]
I tested that `Mapwrapper` does call `Pool.close` and `Pool.terminate`, I also checked that the cleanup occurs in the context of `differential_evolution`. I wonder if it's a garbage collection thing?

Can you see what happens if you create the Pool yourself:

```python
from multiprocessing import Pool

for i in range(1000):
    print(f'round {i}')
    with Pool(16) as p:
        differential_evolution(f, x0=[.0108, .0886, .01005, 0.], maxiter=500, bounds=[(.01, .4), (.01, .4), (.01, .4), (-.6, .6)], args=(1,), workers=p.map, disp=False)

```

**Comment by andyfaff** [comment]
In testing on my mac I use `os.getpid()` to figure out what the PID is. I then use `lsof -p 51368 | wc -l` from a terminal to print out the number of open files associated with the PID. When I run your example the number of open files gradually increases, and then fluctuates whilst running. If I run `gc.collect()` on each loop iteration then the number of files increases by a set amount, is constant during the loop, and returns to roughly its original amount at the end of the loop.

I'd therefore say that that the 'open files' aren't fully closed until the garbage collector runs. I don't think it's scipy's responsibility to check that.

**Comment by gellnerm** [comment]
A bug in Python's garbage collection?

**Comment by andyfaff** [comment]
I don't think it's bugged.

My guess is that file descriptors are free/cleaned up (in `__del__`?) when the `Pool` objects are garbage collected. Garbage collection only happens every now and then, leaving the possibility of running out of file descriptors. If you force the collection to occur then you won't run into the problem.

Having said that, this is somewhat of a conjecture. I can't replicate your issue on my computer, I can only look at the number of open files on my own computer (with this example).

**Comment by andyfaff** [comment]
If you could repeat your test with garbage collection in the loop we'll know that the conjecture was right. It won't be a bug in scipy, but it might be a possible improvement in upstream Python

**Comment by andyfaff** [comment]
Note for this particular case you would be much better off with the following. This is because the `Pool` is only created once and then reused. Creating Pools over and over takes a lot of overhead.

```python
from scipy.optimize import differential_evolution
import numpy as np
from multiprocessing import Pool
from func import f

with Pool(16) as p:
    for i in range(1000):
        print(f'round {i}')
        differential_evolution(f, x0=[.0108, .0886, .01005, 0.],
                               maxiter=500,
                               bounds=[(.01, .4), (.01, .4), (.01, .4), (-.6, .6)],
                               args=(1,), workers=p.map
                              )

```
