### ISSUE TITLE
BUG: integrate.solve_ivp fails for some step sizes if dense_output=True with events but no t_eval

### ISSUE THREAD

**Issue by ericjwhitney** [scipy/scipy#19418]
### Describe your issue.

Calling scipy.integrate.solve_ivp under the following combination of conditions results in failure:

- Small step size `max_step`.
- `dense_output = True`
- `events` provided.
- `t_eval` not provided. 

The error appears to be after scipy/integrate/_ivp/ivp.py here: https://github.com/scipy/scipy/blob/43bb524ecf1544743493ae69053e38a93c5aee7c/scipy/integrate/_ivp/ivp.py#L689-L691

If an event is found in the current timestep, that when solved gives a time value _exactly equal_ to the start of the interval (i.e. the end of the last interval), appending that time value means a duplicate entry is added to the `ts` array.  When `dense_output = True` and `t_eval` is `None`, this call to `OdeSolution` fails:  https://github.com/scipy/scipy/blob/43bb524ecf1544743493ae69053e38a93c5aee7c/scipy/integrate/_ivp/ivp.py#L727-L731

This is because a monotonically increasing / decreasing series of time values is required.  It seems to only occur if the maximum step size is controlled to be a small value.  A simple fix might be to simply check for a duplicate value before appending the event time mark, but I haven't thought about this too deeply. 

_Added:_ This error is very similar to https://github.com/scipy/scipy/issues/17066#issue-1381164720  The main issue appears to be when the derivative term happens to be an exact multiple of the timestep, so that when the terminating event is reached the solution rounds to exactly the timestep value again - this giving a repeated value.  My workaround is to slightly offset the timestep by a tiny value to prevent this, but this is undesirable.

### Reproducing Code Example

```python
# Example based on the documentation.
import numpy as np
from scipy.integrate import solve_ivp

def upward_cannon(t, y):
    return [y[1], -9.80665]

def hit_ground(t, y):
    return y[0]

hit_ground.terminal = True
hit_ground.direction = -1

sol = solve_ivp(upward_cannon, [0, np.inf],[0, 0.001],
                max_step=0.05 * 0.001 / 9.80665,
                events=hit_ground, dense_output=True)
print(sol.t_events)
```

### Error message

```shell
Traceback (most recent call last):
  File "C:.........\scratch_4.py", line 17, in <module>
    sol = solve_ivp(upward_cannon, [0, np.inf],[0, 0.001],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:.........\venv\Lib\site-packages\scipy\integrate\_ivp\ivp.py", line 672, in solve_ivp
    sol = OdeSolution(ts, interpolants)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:.........\venv\Lib\site-packages\scipy\integrate\_ivp\common.py", line 159, in __init__
    raise ValueError("`ts` must be strictly increasing or decreasing.")
ValueError: `ts` must be strictly increasing or decreasing.
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
```

**Comment by czgdp1807** [comment]
I am able to reproduce this error on SciPy `main` branch. Let me look into it.
