### ISSUE TITLE
BUG: interpn error ----'The points in dimension 0 must be strictly ascending or descending'

### ISSUE THREAD

**Issue by Y-Antares** [scipy/scipy#19485]
### Describe your issue.

When I used interpn() , I get the err "The points in dimension 0 must be strictly ascending or descending".

### Reproducing Code Example

```python
Dsetvol=np.random.rand(100,100,100)
xx = np.arange(1, Dsetvol.shape[0] + 1) - int((Dsetvol.shape[0] + 1) / 2)
yy = np.arange(1, Dsetvol.shape[1] + 1) - int((Dsetvol.shape[1] + 1) / 2)
zz = np.arange(1, Dsetvol.shape[2] + 1) - int((Dsetvol.shape[2] + 1) / 2)


xxi = np.arange(3 * xx[0], xx[-1] * 3 + 1) / 3
yyi = np.arange(3 * yy[0], yy[-1] * 3 + 1) / 3
zzi = np.arange(3 * zz[0], zz[-1] * 3 + 1) / 3

xxi = xxi[2:]  # Skip the first two elements
yyi = yyi[2:]  
zzi = zzi[2:]  

Y, X, Z = np.meshgrid(yy, xx, zz)
Yi, Xi, Zi = np.meshgrid(yyi, xxi, zzi)

points=(Y, X, Z)
Dsetvol = interpn(points, Dsetvol, (Yi, Xi, Zi), method='linear', bounds_error=False, fill_value=0)
```

### Error message

```shell
runfile('D:/git_for_group/pyAET/pyaet/untitled2.py', wdir='D:/git_for_group/pyAET/pyaet')
Reloaded modules: src.My_paddzero, src.get_box_intensity, src.initial_class_kmean_sub, src.plot_class_hist, src.local_class_kmean_sub
Traceback (most recent call last):

  File "D:\git_for_group\pyAET\pyaet\untitled2.py", line 67, in <module>
    Dsetvol = interpn(points, Dsetvol, (Yi, Xi, Zi), method='linear', bounds_error=False, fill_value=0)

  File "D:\programmmmms\lib\site-packages\scipy\interpolate\_rgi.py", line 564, in interpn
    raise ValueError("The points in dimension %d must be strictly "

ValueError: The points in dimension 0 must be strictly ascending or descending
```

### SciPy/NumPy/Python version and system information

```shell
1.9.1/ 1.26.1 /sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
`intepn` call receives as its `points` argument the tuple of 1D arrays to construct the meshgrid with, not meshgrids. This indeed differs from the `xi` argument which you need to provide as a tuple of meshgrids if you want to evaluate it on the full grid. Might be easier to trace with the `RegularGridInterpolator`:

`>>> interpn(points, values, xi)` is equivalent to

```
>>> rgi = RegularGridInterpolator(points, values)
>>> rgi(xi)
```

Therefore, in the OP the last line should read

````
>>> res = interpn((yy, xx, zz), Dsetvol, (Yi, Xi, Zi), method='linear', bounds_error=False, fill_value=0)
>>> res.shape
(296, 296, 296)
```
