### ISSUE TITLE
DOC/DX: `meson-python` missing from 'required build dependencies'

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19565]
### Issue with current documentation:

During investigation for gh-19563, I stumbled into this issue. In the 'Building from source to use SciPy' section of the [Building from source docs](http://scipy.github.io/devdocs/building/index.html#building-from-source), the 'required build dependencies' part is missing `meson-python`.

<img width="665" alt="image" src="https://github.com/scipy/scipy/assets/51488791/9fbe09c6-dc03-450f-b1a6-26702153fd2b">

This results in an awfully confusing error message which refers to `mesonpy`, as @enn-nafnlaus encountered in https://github.com/scipy/scipy/issues/19153#issuecomment-1699525566.

<details>
<summary>Error Message</summary>

```
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 513, in collect_root_requirements
    reqs = list(
           ^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 474, in _make_requirements_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 577, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 772, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/mambaforge/envs/build-test/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'
```

</details>

The reasonable thing to try upon reading this error message is `mamba install mesonpy` / `pip install mesonpy`, which does not help at all.

### How to reproduce

```
mamba install python numpy cython pythran pybind11 compilers openblas pkg-config # as directed by the docs
git clone https://github.com/scipy/scipy.git
git submodule update --init
pip install . --no-build-isolation
```

### Idea or request for content:

Add `meson-python` into the quoted line in the docs.

**Comment by rgommers** [comment]
Oops yes, that's a mistake - especially because `--no-build-isolation` is used right below it. I have to make some more tweaks, so I'll fix this one.
