### ISSUE TITLE
Developer installation

### ISSUE THREAD

**Issue by tensionhead** [scipy/scipy#19563]
I followed the instructions from this guide [Building from source for SciPy development](http://scipy.github.io/devdocs/building/index.html#building-from-source) and everything worked well including the actual build via:
```bash
python dev.py build
```
Note that I did NOT install the doc and typing/linting dependencies, as I only need the latest `main` branch to work inside a python environment for some testing regarding #14740 .
This is the terminal output directly after the build, which for me looks good:
```bash
[1606/1606] Linking target scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
```

To get an interpreter with the latest SciPy source, I tried
```bash
python dev.py ipython
```
and also 
```
python dev.py python
```
but both fail with
```bash
 ...
  File "/home/xxx/scipy/dev.py", line 536, in install_project                                                              
    raise RuntimeError("Can't install in non-empty directory: "                                                            
RuntimeError: Can't install in non-empty directory: '/home/xxx/scipy/build-install' 
```
I was so bold and deleted the `build-install` directory, repeating `python dev.py ipython` then gives:
```bash
 ...
  File "/home/xxx/scipy/dev.py", line 1161, in run                                                                         
    import IPython                                                                                                         
ModuleNotFoundError: No module named 'IPython'  
```
however `python dev.py python` then actually spawns an interpreter, but then I get
```python
>>> import scipy                                                                                                           
Traceback (most recent call last):                                                                                         
  File "/home/xxx/scipy/__init__.py", line 51, in <module>                                                                 
    from scipy.__config__ import show as show_config                                                                       
ModuleNotFoundError: No module named 'scipy.__config__'                                                                    
                                                                                                                           
The above exception was the direct cause of the following exception:                                                       
                                                                                                                           
Traceback (most recent call last):                                                                                         
  File "<console>", line 1, in <module>                                                                                    
  File "/home/xxx/scipy/__init__.py", line 56, in <module>                                                                 
    raise ImportError(msg) from e                                                                                          
ImportError: Error importing SciPy: you cannot import SciPy while                                                          
    being in scipy source directory; please exit the SciPy source                                                          
    tree first and relaunch your Python interpreter.
```
So here I am stuck, as executing
```bash
python -c "import scipy; print(scipy.__version__)"
```
outside the source directory gives me the correct `1.11.4`, but
```bash
python -c "import scipy.signal; scipy.signal.ShortTimeFFT"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'scipy.signal' has no attribute 'ShortTimeFFT'
```
which should be there as it was merged with PR #17408 and I can also see it [here](https://github.com/scipy/scipy/blob/main/scipy/signal/_short_time_fft.py)

 @lucascolley advised to fire up a `git clean -xdf`, then repeating `python dev.py ipython` lead to the exact same error as above (`ModuleNotFoundError: No module named 'IPython'`).

My system:
- OS: Ubuntu 22.04
- virtual env.: poetry

**Comment by lucascolley** [comment]
It looks like you have tried to build SciPy from source in an environment where you have already installed a SciPy binary.

You have installed SciPy `1.11.4` from binary and are then trying to build SciPy `1.12.0.dev0` (`main`) in the same environment. Please try creating a new development environment first, as stated in the guide, then following the rest of the steps.

**Comment by tensionhead** [comment]
Ok, so my issue of not getting the lastest source in a Python environment was solved my simply installing from source, and not going for a developer install. As described in the [doc](http://scipy.github.io/devdocs/building/index.html#building-from-source), these 3 commands within a virtual env do the trick:
```bash
git clone https://github.com/scipy/scipy.git
git submodule update --init
pip install .
```
However, I am not closing this as I think the section [Building from source for SciPy development](http://scipy.github.io/devdocs/building/index.html#building-from-source-for-scipy-development) needs some adjustments, as what it describes does not work exactly. At least mentioning to delete the `build-install` dir before firing up `python dev.py ipython` might be a good idea.

Yes, @lucascolley now I have `1.12.0` no idea where that binary came from, I will try again in a clean new environment!

**Comment by lucascolley** [comment]
You should run `python dev.py ipython` _from the source directory_ and then `import scipy`. There is no need to import from the build directory - perhaps something could be added to the documentation to make this more clear.

**Comment by tensionhead** [comment]
I am running the `python dev.py ipython` from the source directory, otherwise the `dev.py` would not be found. But then I can't `import scipy` becaus it is the source directory like stated in the initial post here. That's why I tried to import with relative path in `/build` but to no avail.

**Comment by lucascolley** [comment]
> But then I can't import scipy becaus it is the source directory like stated in the initial post here.

I thought that this was because you were in the environment with the SciPy 1.11.4 binary. I just did a fresh build in a clean environment and I can't reproduce the error. `import scipy` should work fine in the source directory when you have built correctly. Can you try again, making sure you're in the clean environment? If that still doesn't work, please can you give a sequence of commands so that I can reproduce the error?

**Comment by tensionhead** [comment]
Ok sure, here are the things I am doing:
```bash
mkdir dev-install
cd dev-install
git clone https://github.com/scipy/scipy.git
cd scipy # this one is missing in the doc, but Ok :)
git submodule update --init
```
Now I am setting up a virtual env via poetry by creating a bogus project:
```bash
cd ..
poetry new venv-scipy
cd venv-scipy
poetry shell # this creates AND activates the virtual env
```

To confirm we have a clean slate:

```bash
which python3
/home/xxx/.cache/pypoetry/virtualenvs/venv-scipy-A-J8Dfol-py3.10/bin/python3
```
and no scipy:
```bash
python -c "import scipy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
```
Then I install all additional dependencies via pip in that venv as in the doc:
```bash
python -m pip install numpy cython pythran pybind11 meson ninja pydevtool rich-click
python -m pip install pytest pytest-xdist pytest-timeout pooch threadpoolctl asv gmpy2 mpmath hypothesis
python -m pip install sphinx "pydata-sphinx-theme==0.9.0" sphinx-design matplotlib numpydoc jupytext myst-nb
python -m pip install mypy typing_extensions types-psutil pycodestyle ruff cython-lint
```
After cd'ing back into the `scipy` source directory, I fire up 
```bash
python dev.py build
```
which succeeds but then already:
```bash
python dev.py ipython
```
fails with `RuntimeError: Can't install in non-empty directory: `. So removing the `build-install` directory (which is not covered by the current [doc](http://scipy.github.io/devdocs/building/index.html#building-from-source-for-scipy-development) as mentioned) and then repeating `python dev.py ipython` I get a running interpreter, but then `import scipy` fails:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/dev-install/scipy/scipy/__init__.py:51
     50 try:
---> 51     from scipy.__config__ import show as show_config
     52 except ImportError as e:

ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import scipy

File ~/dev-install/scipy/scipy/__init__.py:56
     52 except ImportError as e:
     53     msg = """Error importing SciPy: you cannot import SciPy while
     54     being in scipy source directory; please exit the SciPy source
     55     tree first and relaunch your Python interpreter."""
---> 56     raise ImportError(msg) from e
     59 from scipy.version import version as __version__
     62 # Allow distributors to run custom init code

ImportError: Error importing SciPy: you cannot import SciPy while
    being in scipy source directory; please exit the SciPy source
    tree first and relaunch your Python interpreter.
```

**Comment by lucascolley** [comment]
Thanks for giving the steps. I can't immediately see where the problem is, hopefully someone else can chime in.

**Comment by andyfaff** [comment]
Please don't delete the build-install directory, that's where the build places an importable package (provided that it's on the `PYTHONPATH`).

The following commands work for me:

```shell
# I'm already in the scipy directory
git clean -xdf
conda create -n 19563
conda activate 19563
pwd
conda install python=3.10
pip install numpy cython pybind11 pythran jupyter meson ninja meson-python scipy-openblas32
pip install click pydevtool pip install rich-click
python dev.py build --with-scipy-openblas
python dev.py ipython
```

When the console starts I see:
```
In [1]: import scipy

In [2]: scipy.__file__
Out[2]: '/Users/andrew/Documents/Andy/programming/scipy/build-install/lib/python3.10/site-packages/scipy/__init__.py'
```

Can you try using `venv` or `conda` to create the virtual environment instead of `poetry`?

**Comment by tensionhead** [comment]
Well poetry is explicitly mentionend as a possible provider of virt. envs. in the scipy [doc](http://scipy.github.io/devdocs/building/index.html#building-from-source-for-scipy-development). So I am pretty sure it will work with conda, but then maybe poetry has to be removed from that list?!

**Comment by andyfaff** [comment]
It may work, I just want to know if poetry is the cause of the problem

**Comment by tensionhead** [comment]
Yup, can confirm with `venv` it works as described, I end up in an ipython session and can successfully `import scipy`!

**Comment by andyfaff** [comment]
So there's something about everything works with `poetry` that's the issue.

**Comment by lucascolley** [comment]
@tensionhead would you mind editing the title to something like "Build fails in poetry env" so that people can see what the issue is about from a glance?

**Comment by MikhailRyazanov** [comment]
I have similar problems with `virtualenv`.

It seems that `dev.py` tries to do an install even when the build is already installed (`RuntimeError: Can't install in non-empty directory: '<...>/build-install'`). And the install is apparently somehow broken, since deleting `build-install` and running `dev.py python` does the install and launches Python, but then `import scipy` fails with `ModuleNotFoundError: No module named 'scipy.__config__'` and a complaint `you cannot import SciPy while being in scipy source directory`. However, trying to run `dev.py` _not_ from the source directory results in `ERROR: Neither source directory <...>/build' nor build directory None contain a build file meson.build.`.

**Comment by MikhailRyazanov** [comment]
After some investigation: in my case the problems are caused by [`get_site_packages()`](https://github.com/scipy/scipy/blob/3959e8b28a8fdf9f6803fe34bf8f0e34909d840d/dev.py#L328C9-L328C26) working incorrectly. It returns `.../build-install/lib/python3.11/site-packages`, but the actual path is `.../build-install/lib/python3/dist-packages` (note the `dist`/`site` difference mentioned in the docstring, but also the generic `3` instead of `3.11`). I do use Python 3.11 from Debian, but there is no `'deb_system'` in `INSTALL_SCHEMES`.

Manually creating symlinks seems to solve the problem. At least `dev.py python` works from the source directory and can import the built `scipy`. The install, however, is redone every time even if nothing has changed — is this intentional?

Forcing the `if 'deb_system' in INSTALL_SCHEMES:` branch to execute also seems to work, but spits many `Please avoid running ``setup.py`` directly.` warnings.

**Comment by rgommers** [comment]
@MikhailRyazanov that's an unrelated issue (thanks for diagnosing it!), so could you please open a new issue and Cc me? Debian packaging of Python is a pain, so looks like handling that broke again. Please add your exact Debian version to the new issue.

**Comment by MikhailRyazanov** [comment]
@rgommers, OK — see #21080.
