### ISSUE TITLE
Installing scipy on 32 bit.

### ISSUE THREAD

**Issue by Mergevos** [scipy/scipy#19592]
Hi, which version should I install for python 3.10.4 32bit on windows 10.

```
 C:\Users\unkov\Documents\python\mergevos-talk-bot> pip install scipy==1.9.0       
Collecting scipy==1.9.0
  Using cached scipy-1.9.0.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84
      Build dir: C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84\.mesonpy-cz_1iq0r\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.0
      Activating VS 17.8.1
     
      ..\..\meson.build:1:0: ERROR: Compiler cl can not compile programs.
     
      A full log can be found at C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84\.mesonpy-cz_1iq0r\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\unkov\AppData\Local\Programs\Python\Python310-32 C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84 C:\Users\unkov\AppData\Local\Temp\pip-install-nxmvwf62\scipy_40101314805c470d9eb5d61d86974e84\.mesonpy-cz_1iq0r\build
      Traceback (most recent call last):
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>      
          main()
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 909, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 888, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 547, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 463, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 494, in _configure
          self._meson(
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 477, in _meson
          return self._proc('meson', *args)
        File "C:\Users\unkov\AppData\Local\Temp\pip-build-env-2et_272j\overlay\Lib\site-packages\mesonpy\__init__.py", line 472, in _proc
          subprocess.check_call(list(args))
        File "C:\Users\unkov\AppData\Local\Programs\Python\Python310-32\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\unkov\\AppData\\Local\\Temp\\pip-install-nxmvwf62\\scipy_40101314805c470d9eb5d61d86974e84\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\unkov\\AppData\\Local\\Programs\\Python\\Python310-32', 'C:\\Users\\unkov\\AppData\\Local\\Temp\\pip-install-nxmvwf62\\scipy_40101314805c470d9eb5d61d86974e84', 'C:\\Users\\unkov\\AppData\\Local\\Temp\\pip-install-nxmvwf62\\scipy_40101314805c470d9eb5d61d86974e84\\.mesonpy-cz_1iq0r\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```
This is what happens when I try `pip install scipy==1.9.0`

**Comment by andyfaff** [comment]
We aren't making 32-bit executables for windows any more. Your only way of using a more modern version is to install a 64 bit interpreter.
