### ISSUE TITLE
stats: Test failure of `test_plot_iv` because of a Python deprecation in Python 3.12

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#19619]
With `'1.12.0.dev0+2038.f34c611'`, I get the following failure when I run the tests with Python 3.12 on Linux.  I haven't investigated further; this might be a problem in maplotlib or one of its dependencies that is out of our hands.

Short summary:

    FAILED scipy/stats/tests/test_survival.py::TestSurvival::test_plot_iv - DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal i...

<details>
<summary>
Full error report
</summary>

```
______________________________________ TestSurvival.test_plot_iv ______________________________________
[gw6] linux -- Python 3.12.0 /home/warren/py3.12.0/bin/python3
scipy/stats/tests/test_survival.py:382: in test_plot_iv
    import matplotlib.pyplot as plt  # noqa: F401
        _          = array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,...False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False])
        n_unique   = 83
        res        = ECDFResult(cdf=EmpiricalDistributionFunction(quantiles=array([0.01327326, 0.01406269, 0.0302765 , 0.03673028, 0.052658...85899,
       0.10301113, 0.08716326, 0.07923933, 0.06933441, 0.04952458,
       0.03961966, 0.02641311, 0.        ])))
        rng        = Generator(PCG64) at 0x7FC434978820
        sample     = CensoredData(uncensored=array([0.8165432 , 0.65078278, 0.26971902, 0.23666593, 0.85843935, 0.19714283, 0.27266022, 0.6...5842522, 0.0302765 , 0.36740916, 0.96576494, 0.39879276, 0.62778709]), interval=array([], shape=(0, 2), dtype=float64))
        self       = <scipy.stats.tests.test_survival.TestSurvival object at 0x7fc33352d2b0>
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/pyplot.py:66: in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
        AbstractContextManager = <class 'contextlib.AbstractContextManager'>
        Enum       = <enum 'Enum'>
        ExitStack  = <class 'contextlib.ExitStack'>
        FigureCanvasBase = <class 'matplotlib.backend_bases.FigureCanvasBase'>
        FigureManagerBase = <class 'matplotlib.backend_bases.FigureManagerBase'>
        MouseButton = <enum 'MouseButton'>
        __annotations__ = {}
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__pycache__/pyplot.cpython-312.pyc'
        __doc__    = '\n`matplotlib.pyplot` is a state-based interface to matplotlib. It provides\nan implicit,  MATLAB-like, way of plotti...y)\n\n\nSee :ref:`api_interfaces` for an explanation of the tradeoffs between the\nimplicit and explicit interfaces.\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/pyplot.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc336bc83e0>
        __name__   = 'matplotlib.pyplot'
        __package__ = 'matplotlib'
        __spec__   = ModuleSpec(name='matplotlib.pyplot', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc336bc83e0>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/pyplot.py')
        _api       = <module 'matplotlib._api' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/_api/__init__.py'>
        _docstring = <module 'matplotlib._docstring' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/_docstring.py'>
        _pylab_helpers = <module 'matplotlib._pylab_helpers' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/_pylab_helpers.py'>
        annotations = _Feature((3, 7, 0, 'beta', 1), None, 16777216)
        cast       = <function cast at 0x7fc437e9cea0>
        cbook      = <module 'matplotlib.cbook' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/cbook.py'>
        cm         = <module 'matplotlib.cm' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/cm.py'>
        cycler     = <function cycler at 0x7fc334af47c0>
        functools  = <module 'functools' from '/home/warren/py3.12.0/lib/python3.12/functools.py'>
        get_backend = <function get_backend at 0x7fc33492e700>
        importlib  = <module 'importlib' from '/home/warren/py3.12.0/lib/python3.12/importlib/__init__.py'>
        inspect    = <module 'inspect' from '/home/warren/py3.12.0/lib/python3.12/inspect.py'>
        interactive = <function interactive at 0x7fc33492e7a0>
        logging    = <module 'logging' from '/home/warren/py3.12.0/lib/python3.12/logging/__init__.py'>
        matplotlib = <module 'matplotlib' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__init__.py'>
        overload   = <function overload at 0x7fc437e9d580>
        rcParams   = RcParams({'_internal.classic_mode': False,
          'agg.path.chunksize': 0,
          'animation.bitrate': -1,
     ...ize': 2.0,
          'ytick.minor.visible': False,
          'ytick.minor.width': 0.6,
          'ytick.right': False})
        re         = <module 're' from '/home/warren/py3.12.0/lib/python3.12/re/__init__.py'>
        style      = <module 'matplotlib.style' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/style/__init__.py'>
        sys        = <module 'sys' (built-in)>
        threading  = <module 'threading' from '/home/warren/py3.12.0/lib/python3.12/threading.py'>
        time       = <module 'time' (built-in)>
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/figure.py:43: in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
        ExitStack  = <class 'contextlib.ExitStack'>
        Integral   = <class 'numbers.Integral'>
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__pycache__/figure.cpython-312.pyc'
        __doc__    = '\n`matplotlib.figure` implements the following classes:\n\n`Figure`\n    Top level `~matplotlib.artist.Artist`, which...f:`user_interfaces` for a\nlist of examples) .  More information about Figures can be found at\n:ref:`figure-intro`.\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/figure.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333600e0>
        __name__   = 'matplotlib.figure'
        __package__ = 'matplotlib'
        __spec__   = ModuleSpec(name='matplotlib.figure', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333600e0>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/figure.py')
        inspect    = <module 'inspect' from '/home/warren/py3.12.0/lib/python3.12/inspect.py'>
        itertools  = <module 'itertools' (built-in)>
        logging    = <module 'logging' from '/home/warren/py3.12.0/lib/python3.12/logging/__init__.py'>
        mpl        = <module 'matplotlib' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__init__.py'>
        np         = <module 'numpy' from '/home/warren/py3.12.0/lib/python3.12/site-packages/numpy/__init__.py'>
        threading  = <module 'threading' from '/home/warren/py3.12.0/lib/python3.12/threading.py'>
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections/__init__.py:55: in <module>
    from .. import axes, _docstring
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections/__pycache__/__init__.cpython-312.pyc'
        __doc__    = '\nNon-separable transforms that map from data space to screen space.\n\nProjections are defined as `~.axes.Axes` subc...y/misc/custom_projection`.  The polar plot functionality in\n`matplotlib.projections.polar` may also be of interest.\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a4680>
        __name__   = 'matplotlib.projections'
        __package__ = 'matplotlib.projections'
        __path__   = ['/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections']
        __spec__   = ModuleSpec(name='matplotlib.projections', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a4680...__init__.py', submodule_search_locations=['/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections'])
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/__init__.py:2: in <module>
    from ._axes import *
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/__pycache__/__init__.cpython-312.pyc'
        __doc__    = None
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a43e0>
        __name__   = 'matplotlib.axes'
        __package__ = 'matplotlib.axes'
        __path__   = ['/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes']
        __spec__   = ModuleSpec(name='matplotlib.axes', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a43e0>, orig...b/axes/__init__.py', submodule_search_locations=['/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes'])
        _base      = <module 'matplotlib.axes._base' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/_base.py'>
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/_axes.py:11: in <module>
    import matplotlib.category  # Register category unit converter as side effect.
        Integral   = <class 'numbers.Integral'>
        Number     = <class 'numbers.Number'>
        Real       = <class 'numbers.Real'>
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/__pycache__/_axes.cpython-312.pyc'
        __doc__    = None
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/_axes.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a4c20>
        __name__   = 'matplotlib.axes._axes'
        __package__ = 'matplotlib.axes'
        __spec__   = ModuleSpec(name='matplotlib.axes._axes', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a4c20>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/_axes.py')
        functools  = <module 'functools' from '/home/warren/py3.12.0/lib/python3.12/functools.py'>
        itertools  = <module 'itertools' (built-in)>
        logging    = <module 'logging' from '/home/warren/py3.12.0/lib/python3.12/logging/__init__.py'>
        ma         = <module 'numpy.ma' from '/home/warren/py3.12.0/lib/python3.12/site-packages/numpy/ma/__init__.py'>
        math       = <module 'math' from '/home/warren/py3.12.0/lib/python3.12/lib-dynload/math.cpython-312-x86_64-linux-gnu.so'>
        mpl        = <module 'matplotlib' from '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__init__.py'>
        np         = <module 'numpy' from '/home/warren/py3.12.0/lib/python3.12/site-packages/numpy/__init__.py'>
/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/category.py:14: in <module>
    import dateutil.parser
        OrderedDict = <class 'collections.OrderedDict'>
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/__pycache__/category.cpython-312.pyc'
        __doc__    = '\nPlotting of string "category" data: ``plot([\'d\', \'f\', \'a\'], [1, 2, 3])`` will\nplot three points with x-axis ... a tick locator, a tick formatter, and the\n`.UnitData` class that creates and stores the string-to-integer mapping.\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/category.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333dede0>
        __name__   = 'matplotlib.category'
        __package__ = 'matplotlib'
        __spec__   = ModuleSpec(name='matplotlib.category', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333dede0>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/category.py')
/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/__init__.py:2: in <module>
    from ._parser import parse, parser, parserinfo, ParserError
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/__pycache__/__init__.cpython-312.pyc'
        __doc__    = None
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a6120>
        __name__   = 'dateutil.parser'
        __package__ = 'dateutil.parser'
        __path__   = ['/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser']
        __spec__   = ModuleSpec(name='dateutil.parser', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a6120>, orig...parser/__init__.py', submodule_search_locations=['/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser'])
/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/_parser.py:50: in <module>
    from .. import tz
        Decimal    = <class 'decimal.Decimal'>
        StringIO   = <class '_io.StringIO'>
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/__pycache__/_parser.cpython-312.pyc'
        __doc__    = '\nThis module offers a generic date/time string parser which is able to parse\nmost known formats to represent a date...>`_\n- `Java SimpleDateFormat Class\n  <https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html>`_\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/_parser.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a6300>
        __name__   = 'dateutil.parser._parser'
        __package__ = 'dateutil.parser'
        __spec__   = ModuleSpec(name='dateutil.parser._parser', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a6300>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/_parser.py')
        datetime   = <module 'datetime' from '/home/warren/py3.12.0/lib/python3.12/datetime.py'>
        integer_types = (<class 'int'>,)
        monthrange = <function monthrange at 0x7fc436e52e80>
        re         = <module 're' from '/home/warren/py3.12.0/lib/python3.12/re/__init__.py'>
        relativedelta = <module 'dateutil.relativedelta' from '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/relativedelta.py'>
        six        = <module 'six' from '/home/warren/py3.12.0/lib/python3.12/site-packages/six.py'>
        string     = <module 'string' from '/home/warren/py3.12.0/lib/python3.12/string.py'>
        text_type  = <class 'str'>
        time       = <module 'time' (built-in)>
        unicode_literals = _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 2097152)
        warn       = <built-in function warn>
        warnings   = <module 'warnings' from '/home/warren/py3.12.0/lib/python3.12/warnings.py'>
/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/__init__.py:2: in <module>
    from .tz import *
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/__pycache__/__init__.cpython-312.pyc'
        __doc__    = None
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a72f0>
        __name__   = 'dateutil.tz'
        __package__ = 'dateutil.tz'
        __path__   = ['/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz']
        __spec__   = ModuleSpec(name='dateutil.tz', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a72f0>, origin='...ateutil/tz/__init__.py', submodule_search_locations=['/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz'])
/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/tz.py:37: in <module>
    EPOCH = datetime.datetime.utcfromtimestamp(0)
E   DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
        OrderedDict = <class 'collections.OrderedDict'>
        ZERO       = datetime.timedelta(0)
        _TzOffsetFactory = <class 'dateutil.tz._factories._TzOffsetFactory'>
        _TzSingleton = <class 'dateutil.tz._factories._TzSingleton'>
        _TzStrFactory = <class 'dateutil.tz._factories._TzStrFactory'>
        __builtins__ = <builtins>
        __cached__ = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/__pycache__/tz.cpython-312.pyc'
        __doc__    = '\nThis module offers timezone implementations subclassing the abstract\n:py:class:`datetime.tzinfo` type. There are c...), given ranges (with help\nfrom relative deltas), local machine timezone, fixed offset timezone, and UTC\ntimezone.\n'
        __file__   = '/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/tz.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a7410>
        __name__   = 'dateutil.tz.tz'
        __package__ = 'dateutil.tz'
        __spec__   = ModuleSpec(name='dateutil.tz.tz', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc3333a7410>, origin='/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/tz.py')
        __warningregistry__ = {'version': 22181}
        _thread    = <module '_thread' (built-in)>
        _tzinfo    = <class 'dateutil.tz._common._tzinfo'>
        _validate_fromutc_inputs = <function _validate_fromutc_inputs at 0x7fc334257c40>
        bisect     = <module 'bisect' from '/home/warren/py3.12.0/lib/python3.12/bisect.py'>
        datetime   = <module 'datetime' from '/home/warren/py3.12.0/lib/python3.12/datetime.py'>
        enfold     = <function enfold at 0x7fc334257ba0>
        os         = <module 'os' (frozen)>
        six        = <module 'six' from '/home/warren/py3.12.0/lib/python3.12/site-packages/six.py'>
        string_types = (<class 'str'>,)
        struct     = <module 'struct' from '/home/warren/py3.12.0/lib/python3.12/struct.py'>
        sys        = <module 'sys' (built-in)>
        time       = <module 'time' (built-in)>
        tzname_in_python2 = <function tzname_in_python2 at 0x7fc334257b00>
        tzrangebase = <class 'dateutil.tz._common.tzrangebase'>
        tzwin      = None
        tzwinlocal = None
        warn       = <built-in function warn>
        weakref    = <module 'weakref' from '/home/warren/py3.12.0/lib/python3.12/weakref.py'>

```

</details>

**Comment by mdhaber** [comment]
> this might be a problem in maplotlib or one of its dependencies that is out of our hands.

Looks like it, since the offending line appears to be `import matplotlib.pyplot as plt`.

**Comment by WarrenWeckesser** [comment]
Right, the warning arises during the import of `matplotlib.pyplot`:

```
$ python3 -Werror -c "import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/projections/__init__.py", line 55, in <module>
    from .. import axes, _docstring
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/__init__.py", line 2, in <module>
    from ._axes import *
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/axes/_axes.py", line 11, in <module>
    import matplotlib.category  # Register category unit converter as side effect.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/matplotlib/category.py", line 14, in <module>
    import dateutil.parser
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/home/warren/py3.12.0/lib/python3.12/site-packages/dateutil/tz/tz.py", line 37, in <module>
    EPOCH = datetime.datetime.utcfromtimestamp(0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).

```

The root cause is in the `dateutil` module that is used by matplotlib; see https://github.com/dateutil/dateutil/pull/1285, and the request for an updated release of dateutil at https://github.com/dateutil/dateutil/issues/1314.

**Comment by AtsushiSakai** [comment]
I think the new release 2.9.0 of the `dateutil` has been released. We can solve this issue by installing the latest matplotlib. So we can close this issue.
