### ISSUE TITLE
scipy clustering seems to override the provided numpy dtype into float64

### ISSUE THREAD

**Issue by matt-sd-watson** [scipy/scipy#19707]
### Describe your issue.

I am attempting to run `seaborn.clustermap` on an array of size (182440, 34) and continue to get the memory error documented below. In an attempt to reduce the memory overhead required for the array, I have tried to convert the numpy dtype of the arryaypassed to `sns.clustermap` in the code snippet below to a lower byte dtype, it is appears to get overwritten

Is there a particular step in scipy that defaults the array passed into float64? It appears that the clustermap function in seaborn is calling the `linkage` function in `scipy/cluster/hierarchy` as well as `pdist_fn` in `scipy/spatial/distance`, and it would be beneficial to be able to not have the dtype of the array overwritten to float64 due to memory constraints. 

### Reproducing Code Example

```python
low_mem = anndata.AnnData(np.array(adata.X, dtype=np.float32))
sns.clustermap(low_mem.X)
```

### Error message

```shell
warnings.warn(msg)
Traceback (most recent call last):
  File "/home/matt/github/ccramic/sandbox/dendrogram_multiple_levels.py", line 81, in <module>
    sns.clustermap(low_mem.X)
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 1258, in clustermap
    return plotter.plot(metric=metric, method=method,
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 1129, in plot
    self.plot_dendrograms(row_cluster, col_cluster, metric, method,
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 974, in plot_dendrograms
    self.dendrogram_row = dendrogram(
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 687, in dendrogram
    plotter = _DendrogramPlotter(data, linkage=linkage, axis=axis,
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 495, in __init__
    self.linkage = self.calculated_linkage
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 562, in calculated_linkage
    return self._calculate_linkage_scipy()
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 530, in _calculate_linkage_scipy
    linkage = hierarchy.linkage(self.array, method=self.method,
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/scipy/cluster/hierarchy.py", line 1060, in linkage
    y = distance.pdist(y, metric)
  File "/home/matt/github/ccramic/venv/lib/python3.10/site-packages/scipy/spatial/distance.py", line 2233, in pdist
    return pdist_fn(X, out=out, **kwargs)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 124. GiB for an array with shape (16642085580,) and data type float64
```

### SciPy/NumPy/Python version and system information

```shell
1.9.1 1.23.4 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by lucascolley** [comment]
`scipy.spatial.distance.pdist` does seem to output a `float64` dtype for `float32` input. I'll have a look to see if this seems intended or not.

**Comment by lucascolley** [comment]
@matt-sd-watson the conversion to `float64` is intended. gh-11280 already requested that `pdist` support lower-precision dtypes a few years ago, but nothing has happened yet (still in the picture though by the sounds of it).

I'm going to close this as a duplicate now, but please follow gh-11280 or add any thoughts there if you have them. Note that this wouldn't immediately fix your issue, as reduced-precision support would then need to be added to `scipy.cluster.hierarchy.linkage` (and maybe `seaborn.clustermap`?) too, but at least it would be a step in the right direction. For backwards compatibility reasons, the default of using higher precision would be maintained, so the reduced-precision decision would have to be explicit throughout,
