### ISSUE TITLE
BUG: `IndexError` when giving a zero distance matrix to `multiscale_graphcorr`

### ISSUE THREAD

**Issue by Rayerdyne** [scipy/scipy#19769]
### Error
On calling `scipy.stats.multiscale_graphcorr` with either its `x` or `y` parameter (as distance matrices, hence with `compute_distance=None`) contains only zero values, a `IndexError` is raised.

### Investigation
Investigating the stack trace led me to the file `scipy/stats/_stats_py.py` lines 6471 to 6479*, where I see:
```py
    # calculate MGC map and optimal scale
    stat_mgc_map = _local_correlations(distx, disty, global_corr='mgc')

    n, m = stat_mgc_map.shape
    if m == 1 or n == 1:
        # the global scale at is the statistic calculated at maximial nearest
        # neighbors. There is not enough local scale to search over, so
        # default to global scale
        stat = stat_mgc_map[m - 1][n - 1]
```
*these lines number are taken from the version of the file on the repo as of now ([ec98497](https://github.com/scipy/scipy/commit/ec98497595cd7eb39069ba5ab9117d306fe89579))

It appears to me as a mismatch between the definition, `n, m = stat_mgc_map.shape`, and its use as `stat_mgc_map[m - 1][n - 1]`, as it looks like that the arrays output by `_local_correlations` are not necessarily square.

However I cannot say I 100% understood how MGC works, hence I wonder if this is actually intended.

### Context
For information, I got this error through via `hyppo` package, see [this issue](https://github.com/neurodata/hyppo/issues/409).

### Reproducing Code Example

```python
import numpy as np

from scipy.stats import multiscale_graphcorr
from sklearn.metrics import pairwise_distances

n = 6

x = np.arange(n).reshape(-1, 1)
distx = pairwise_distances(x, x)
disty = np.zeros((n, n))
mgc = multiscale_graphcorr(disty, distx, compute_distance=None, reps=0)
```

### Error message

```shell
.../.env/lib/python3.10/site-packages/scipy/stats/_stats_py.py:6477: RuntimeWarning: The number of replications is low (under 1000), and p-value calculations may be unreliable. Use the p-value result, with caution!
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File ".../problem-scipy.py", line 15, in <module>
    main()
  File ".../problem-scipy.py", line 12, in main
    mgc = multiscale_graphcorr(disty, distx, compute_distance=None, reps=0)
  File ".../.env/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 6490, in multiscale_graphcorr
    stat, stat_dict = _mgc_stat(x, y)
  File ".../.env/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 6545, in _mgc_stat
    stat = stat_mgc_map[m - 1][n - 1]
IndexError: index 5 is out of bounds for axis 0 with size 1
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3 1.23.5 sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-6ckgqyn6/overlay/lib/python3.10/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by sampan501** [comment]
@lucascolley I'm the author of both bits of code. Could I be assigned this issue?

**Comment by lucascolley** [comment]
Hi @sampan501 , go ahead! We don't assign people to issues, feel free to take on anything which nobody else is working on 👍

**Comment by sampan501** [comment]
@Rayerdyne Looking into the linked issue, I believe the issue relies more on the MGCX code in `hyppo` rather than the MGC code in `scipy`. The `_local_correlations` function will not output a square matrix each time when there are redundant rows or columns. That is a property of the algorithm.

As for the reproducing code example, I'm realizing now that the code should throw an error when the inputs have 0 variance (it doesn't make much sense to run an independence test in this setting)

**Comment by Rayerdyne** [comment]
@sampan501 I see, thanks!

**Comment by lucascolley** [comment]
> As for the reproducing code example, I'm realizing now that the code should throw an error when the inputs have 0 variance (it doesn't make much sense to run an independence test in this setting)

Would either of you like to submit a PR for this?

**Comment by sampan501** [comment]
I can do this

**Comment by AdrianRasoOnGit** [comment]
It seems that the `IndexError` does have a simple root inside `_mgc_stat`. `mg_stat` does

```python
stat_mgc_map = _local_correlations(distx, disty, global_corr='mgc')

n, m = stat_mgc_map.shape
if m == 1 or n == 1:
       stat = stat_mgc_map[m - 1][n - 1]
```

But the rest of the helpers in its module unpacks the shape as 
```python
m, n = stat_mgc_map.shape
```
and then indexes `stat_mgc_map[m-1][n-1]`. With a map with shape `(1, 6)`, like in the code example, the code would do something like
```
n = 1
m = 6
stat_mgc_map[m-1][n-1] -> stat_mgc_map[5][0]
```
but since axis 0 only has length 1, it raises the error. Swapping `n` and `m` so it follows the convention of the module should fix the bug, and it fixed it for me as far as I could check. I'll open a PR with this change, and I can try to add what @sampan501 suggested too.

**Comment by sampan501** [comment]
sure go for it

**Comment by mdhaber** [comment]
@sampan501 would you take a look at the linked PR (gh-24297)?

Also, after this, what do you think about adding `multiscale_graphcorr` to `hyppo` and having `hyppo` take over maintenance? It seems like the functionality is valuable, but I think users would be better served if this function were to be maintained in `hyppo` and removed from SciPy eventually.

As discussed [on the mailing list](https://mail.python.org/pipermail/scipy-dev/2019-June/023566.html), the rationale for adding `multiscale_graphcorr` to SciPy was that `mgcpy` was slated for deprecation, and former `mcgpy` developers would maintain the code once added to SciPy. But that plan hasn't fully materialized - `hyppo` says that it "is a rebranding of `mgcpy`", and this issue has been open for a while.

Besides that, I'm not sure that SciPy was a perfect place for `multiscale_graphcorr` in the first place. Most features of `scipy.stats` have been standard techniques published in textbooks for decades, whereas all the references for `multiscale_graphcorr` were very recent work from a single lab, all published within the year or so before the original PR. Also, although some users have submitted bug reports, interest from the community has seemed limited. For example, in the mailing list records, I don't see support from users for adding the function.

If `multiscale_graphcorr` were in `hyppo` instead of SciPy, I imagine bugs like this would be sorted out more quickly, and it would be easier to add new features without requiring a SciPy maintainer's review. How does that sound?

**Comment by sampan501** [comment]
@mdhaber Thank you for reaching out. Apologies for the delay on the PR review; it slipped off my radar. It looks like @AdrianRasoOnGit has the right fix, so I'm happy to let them lead on that.

Regarding the mgcpy/hyppo question: You are correct that mgcpy was deprecated. Currently, `hyppo` wraps the SciPy implementation of `multiscale_graphcorr`. `hyppo` exists as its own entity for broader multivariate hypothesis testing, but it currently relies on SciPy for this specific function.

When we originally merged this, the positive mailing list feedback and maintainer interest suggested it was a good fit. I also believe the criticism regarding the "newness" of the method is fair, though I know a number of my collaborators rely on this implementation for their publications.

However, I consider the current SciPy implementation to be feature-complete. I don't foresee requests for new features, and the bug volume has been very low. My hope was that MGC would serve as a stable foundation for multivariate testing in SciPy, which I believe is a growing necessity rather than a niche use case.

That said, I defer to your judgment regarding SciPy's long-term scope. If you prefer to remove it, we should coordinate a deprecation timeline so I can migrate the canonical implementation back to `hyppo` to avoid breaking downstream users.

What do you think?

**Comment by mdhaber** [comment]
Thanks for considering it @sampan501.

>  I don't foresee requests for new features

Maybe, but there are several items we would need to attend to, e.g.
- Regression tests need to be run in CI. (Currently, all but one is skipped because they are all very slow.)
- SPEC 7 transition (`random_state` -> `rng`; gh-21833)
- Array API / masked array (via `marray`) support (gh-20544)
- (potentially) `axis` / `nan_policy` / `keepdims` support (gh-14651)

> we should coordinate a deprecation timeline so I can migrate the canonical implementation back to hyppo to avoid breaking downstream users.

There is no rush (and not much to do on the SciPy side) until there are specific plans for a SciPy 2.0 release. In the meantime, I'd suggest that we close gh-13728, and both functions can be added to `hyppo`. When we have a timeline for SciPy 2.0, we'll deprecate `multiscale_graphcorr` alongside a lot of other outgoing features. The documentation / deprecation message will point to `hyppo`, so if you keep the signature and behavior the same, the transition will be very easy for users.

**Comment by mdhaber** [comment]
@sampan501 We're getting ready for a 2.0 release. The typical deprecation window is two releases, which would mean removal in SciPy 2.2. Do you think that would be sufficient to finish moving `multiscale_graphcorr` to `hyppo` or would it need extra time?
