### ISSUE TITLE
BLD/DOC: M1 Mac missing compilers with `venv` build

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19784]
Minimal Working Example (following https://scipy.github.io/devdocs/building/index.html):

```shell
xcode-select --install
brew install gfortran openblas pkg-config
python3.10 -m venv venv
source venv/bin/activate
python -m pip install -r requirements/all.txt
python dev.py build
```

Error message:

`FileNotFoundError: [Errno 2] No such file or directory: 'arm64-apple-darwin20.0.0-clang'`

<details><summary>Full Traceback</summary>

```
Compiler for C supports arguments -Wno-misleading-indentation: YES (cached)
Traceback (most recent call last):
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 278, in run
    return msetup.run(['--reconfigure'] + args[2:])
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/msetup.py", line 228, in _generate
    intr.run()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 2997, in run
    super().run()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
    self.assignment(cur)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
    value = self.evaluate_statement(node.value)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/baseobjects.py", line 94, in method_call
    return method(args, kwargs)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/interpreter/compiler.py", line 635, in find_library_method
    linkargs = self.compiler.find_library(libname, self.environment, search_dirs, libtype)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1188, in find_library
    return self._find_library_impl(libname, env, extra_dirs, code, libtype, lib_prefix_warning)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1177, in _find_library_impl
    value = self._find_library_real(libname, env, extra_dirs, code, libtype, lib_prefix_warning)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 1136, in _find_library_real
    if self.links(code, env, extra_args=extra_args, disable_cache=True)[0]:
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/compilers.py", line 1322, in links
    return self.compiles(code, env, extra_args=extra_args,
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/compilers.py", line 1307, in compiles
    with self._build_wrapper(code, env, extra_args, dependencies, mode, disable_cache=disable_cache) as p:
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/compilers.py", line 1296, in _build_wrapper
    with self.compile(code, extra_args=args, mode=mode, want_output=want_output, temp_dir=env.scratch_dir) as r:
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/compilers.py", line 859, in compile
    command_list = self.get_exelist(ccache=not no_ccache) + commands.to_native()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/clike.py", line 103, in to_native
    default_dirs = self.compiler.get_default_include_dirs()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/gnu.py", line 423, in get_default_include_dirs
    return gnulike_default_include_dirs(tuple(self.get_exelist(ccache=False)), self.language).copy()
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/compilers/mixins/gnu.py", line 345, in gnulike_default_include_dirs
    _, stdout, _ = mesonlib.Popen_safe(cmd, stderr=subprocess.STDOUT, env=env)
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/mesonbuild/utils/universal.py", line 1485, in Popen_safe
    p = subprocess.Popen(args, universal_newlines=True, encoding=encoding, close_fds=False,
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'arm64-apple-darwin20.0.0-clang'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
FAILED: build.ninja 
/Users/lucascolley/mambaforge/envs/scipy-dev/bin/meson --internal regenerate /Users/lucascolley/programming/scipy .
ninja: error: rebuilding 'build.ninja': subcommand failed
Build failed!
```

</details>

I then tried `python -m pip install compilers`, but that didn't help.

Environment:

`sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)`

<details><summary>`pip list --local`</summary>

```
Package                       Version
----------------------------- ----------
alabaster                     0.7.13
appnope                       0.1.3
asttokens                     2.4.1
asv                           0.6.1
asv_runner                    0.1.0
attrs                         23.2.0
Babel                         2.14.0
beautifulsoup4                4.12.2
beniget                       0.4.1
certifi                       2023.11.17
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
comm                          0.2.0
compilers                     0.0.0
contourpy                     1.2.0
coverage                      7.4.0
cycler                        0.12.1
Cython                        3.0.7
cython-lint                   0.16.0
debugpy                       1.8.0
decorator                     5.1.1
docutils                      0.20.1
doit                          0.36.0
exceptiongroup                1.2.0
execnet                       2.0.2
executing                     2.0.1
fastjsonschema                2.19.1
fonttools                     4.47.0
gast                          0.5.4
hypothesis                    6.92.2
idna                          3.6
imagesize                     1.4.1
importlib-metadata            7.0.1
iniconfig                     2.0.0
ipykernel                     6.28.0
ipython                       8.19.0
jedi                          0.19.1
Jinja2                        3.1.2
json5                         0.9.14
jsonschema                    4.20.0
jsonschema-specifications     2023.12.1
jupyter-cache                 1.0.0
jupyter_client                8.6.0
jupyter_core                  5.5.1
jupytext                      1.16.0
kiwisolver                    1.4.5
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.2
matplotlib-inline             0.1.6
mdit-py-plugins               0.4.0
mdurl                         0.1.2
meson                         1.3.1
meson-python                  0.15.0
mpmath                        1.3.0
mypy                          1.8.0
mypy-extensions               1.0.0
myst-nb                       1.0.0
myst-parser                   2.0.0
nbclient                      0.9.0
nbformat                      5.9.2
nest-asyncio                  1.5.8
ninja                         1.11.1.1
numpy                         1.26.2
numpydoc                      1.6.0
packaging                     23.2
parso                         0.8.3
pexpect                       4.9.0
Pillow                        10.1.0
pip                           23.3.1
platformdirs                  4.1.0
pluggy                        1.3.0
ply                           3.11
pooch                         1.8.0
prompt-toolkit                3.0.43
psutil                        5.9.7
ptyprocess                    0.7.0
pure-eval                     0.2.2
pybind11                      2.11.1
pycodestyle                   2.11.1
pydata-sphinx-theme           0.9.0
pydevtool                     0.3.0
Pygments                      2.17.2
Pympler                       1.0.1
pyparsing                     3.1.1
pyproject-metadata            0.7.1
pytest                        7.4.4
pytest-cov                    4.1.0
pytest-timeout                2.2.0
pytest-xdist                  3.5.0
python-dateutil               2.8.2
pythran                       0.14.0
PyYAML                        6.0.1
pyzmq                         25.1.2
referencing                   0.32.0
requests                      2.31.0
rich                          13.7.0
rich-click                    1.7.2
rpds-py                       0.16.2
ruff                          0.1.9
setuptools                    68.2.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.2.6
sphinx_design                 0.5.0
sphinxcontrib-applehelp       1.0.7
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.6
sphinxcontrib-serializinghtml 1.1.9
SQLAlchemy                    2.0.24
stack-data                    0.6.3
tabulate                      0.9.0
threadpoolctl                 3.2.0
tokenize-rt                   5.2.0
toml                          0.10.2
tomli                         2.0.1
tornado                       6.4
traitlets                     5.14.0
types-psutil                  5.9.5.17
typing_extensions             4.9.0
urllib3                       2.1.0
wcwidth                       0.2.12
zipp                          3.17.0
```

</details>

M1 Mac, macOS Sonoma 14.2.1 (23C71)

---

From `clang --version` I see `Target: arm64-apple-darwin23.2.0`, which seems to disagree with the `arm64-apple-darwin20.0.0-clang` in the error message - maybe that's a hint to the problem?

It may just be that I have missed a step in configuring the system environment, in which case the docs should be updated. Or there may be a bug in the build system (but I think I read somewhere that you've managed to set up fine with `venv` on an M1 Mac before @tylerjereddy ?).

**Comment by tylerjereddy** [comment]
I can use a `venv` on an M2 max laptop, but we have different setups I think since you also have a Python from `conda` and a newer OS version than I.

FWIW, I do see an error with plain `python dev.py build -j 12`:

```
Compiler stderr:
<built-in>: error: unknown value ‘13.5.0’ of ‘-mmacosx-version-min’
```

but everything is "ok" if I tell it which Fortran compiler to use: `FC=gfortran-12 python dev.py build -j 12`

Perhaps you'll have luck with a similar shim? Otherwise, not sure.

**Comment by lucascolley** [comment]
I could try again with Python from a different place if that seems suspicious.

> Perhaps you'll have luck with a similar shim?

I'm not sure what to put in the shim - Meson gives `C compiler for the host machine: arm64-apple-darwin20.0.0-clang` but then `No such file or directory: 'arm64-apple-darwin20.0.0-clang'` further down.

**Comment by tylerjereddy** [comment]
Yeah, I just meant that my error message wasn't super helpful, so trying to specify the name of the Fortran compiler like I did might be worth a shot just in case.

You should be able to build with clang, but could also install the GNU compilers from `brew` and specify those as a backup if you need to get up and running temporarily: `CC=gcc-12 CXX=g++-12 FC=gfortran-12 ...`

(that also works for me)

**Comment by lucascolley** [comment]
> could also install the GNU compilers from brew and specify those as a backup if you need to get up and running temporarily

Thanks, but there's no urgency at all in getting this working since the `conda` build works fine for me.

Someone had the same issue during a sprint so it would be good to figure out what's going wrong (even if it is something upstream out of our control).

**Comment by rgommers** [comment]
I have no problem building with Apple Clang + Homebrew gfortran. From the traceback containing `--reconfigure` it looks like you didn't start from a clean repo @lucascolley. If you switched from a conda build to a venv without cleaning up in between, I can imagine something going wrong. Could you try from a new clone or after `git clean -xdf`?

**Comment by lucascolley** [comment]
I installed Python from python.org/downloads and made a fresh clone in a different directory, however I now see `ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and framework`, despite `brew install openblas` completing successfully.

<details><summary>Full Traceback</summary>

```
(venv) lucascolley@Lucass-MacBook-Air-4 scipy % python dev.py build
💻  meson setup /Users/lucascolley/programming/scipy-venv/scipy/build --prefix /Users/lucascolley/programming/scipy-venv/scipy/build-install
The Meson build system
Version: 1.3.1
Source dir: /Users/lucascolley/programming/scipy-venv/scipy
Build dir: /Users/lucascolley/programming/scipy-venv/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.13.0.dev0
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.1.0.2.5)")
C linker for the host machine: cc ld64 1022.1
C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.1.0.2.5)")
C++ linker for the host machine: c++ ld64 1022.1
Cython compiler for the host machine: cython (cython 3.0.7)
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program python3 found: YES (/Users/lucascolley/programming/scipy-venv/scipy/venv/bin/python3)
Found pkg-config: YES (/opt/homebrew/bin/pkg-config) 0.29.2
Run-time dependency python found: YES 3.10
Program cython found: YES (/Users/lucascolley/programming/scipy-venv/scipy/venv/bin/cython)
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Library m found: YES
Fortran compiler for the host machine: gfortran (gcc 13.2.0 "GNU Fortran (Homebrew GCC 13.2.0) 13.2.0")
Fortran linker for the host machine: gfortran ld64 1022.1
Compiler for Fortran supports arguments -Wno-conversion: YES 
Compiler for C supports link arguments -Wl,-ld_classic: YES 
Checking if "-Wl,--version-script" : links: NO 
Program pythran found: YES (/Users/lucascolley/programming/scipy-venv/scipy/venv/bin/pythran)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xsimd found: NO (tried pkgconfig, framework and cmake)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
pybind11-config found: YES (/Users/lucascolley/programming/scipy-venv/scipy/venv/bin/pybind11-config) 2.11.1
Run-time dependency pybind11 found: YES 2.11.1
Run-time dependency scipy-openblas found: NO (tried pkgconfig, framework and cmake)
Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
Run-time dependency openblas found: NO (tried pkgconfig and framework)

scipy/meson.build:169:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and framework

A full log can be found at /Users/lucascolley/programming/scipy-venv/scipy/build/meson-logs/meson-log.txt
Meson build setup failed!
```

**Comment by rgommers** [comment]
Great, that solves the problem. It's kinda weird that that pkg-config path export is necessary, I'd expect it to work without because both openblas and pkg-config are coming from Homebrew. I'm fairly sure that that used to work, maybe they introduced a bug.

**Comment by lucascolley** [comment]
Homebrew tells me `openblas is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides BLAS in Accelerate.framework.` above the line about the pkg-config export, but I don't know if that's related at all.

**Comment by rgommers** [comment]
Ah yes, that is definitely related. I'm close to finishing up re-enabling Accelerate, but until that is done we should add the `export PKG_CONFIG_PATH` line to the build docs under macOS system dependencies. Do you want to do that?

**Comment by lucascolley** [comment]
Sure thing, is it only Homebrew that this applies to?

**Comment by rgommers** [comment]
Yes indeed, only Homebrew on macOS.
