### ISSUE TITLE
BUG: Potential Hang Issue When Importing scipy.spatial.distance

### ISSUE THREAD

**Issue by 134820134820** [scipy/scipy#20007]
### Describe your issue.

I've encountered a peculiar issue with scipy.spatial.distance where it seems to freeze under specific circumstances. The problem arises when I use import scipy.spatial.distance. Here's the traceback I received:

python
Copy code
Traceback (most recent call last):
  File "E:\buyi_work\MMC5\Login_test.py", line 147, in <module>
    import scipy.spatial.distance
  File "E:\buyi_work\MMC5\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "E:\buyi_work\MMC5\venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "D:\Python3.6.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
After this point, the program stops executing further. Upon initial investigation, this freeze seems to occur when I have already imported the pyminitouch library and scipy.spatial.distance is being imported in a script (for instance, in script b.py with import scipy.spatial.distance, and a importing b). However, if I import scipy.spatial.distance directly in script a, the issue does not arise. This bug is quite intriguing and seems to be dependent on the order and context of imports.

### Reproducing Code Example

```python
will jam
a.py
from pyminitouch import MNTDevice
device = MNTDevice("127.0.0.1:5555")
import b


b.py
import scipy.spatial.distance

no jam
a.py
from pyminitouch import MNTDevice
device = MNTDevice("127.0.0.1:5555")
import scipy.spatial.distance
import b


b.py
import scipy.spatial.distance
```

### Error message

```shell
Traceback (most recent call last):
  File "E:\buyi_work\MMC5\Login_test.py", line 147, in <module>
    import scipy.spatial.distance
  File "E:\buyi_work\MMC5\venv\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "E:\buyi_work\MMC5\venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "D:\Python3.6.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
KeyboardInterrupt
```

### SciPy/NumPy/Python version and system information

```shell
scipy 1.5.4
numpy 1.19.5
python 3.6
```

**Comment by lucascolley** [comment]
Hi @134820134820 , your SciPy version (1.5.4) is very old (NumPy and Python too) - would it be possible for you to try with a more recent version?
