### ISSUE TITLE
BUG: `stats.rv_discrete.ppf`: infinite loop in default implementation

### ISSUE THREAD

**Issue by samorajp** [scipy/scipy#20048]
I am encountering a problem when calculating the inverse of the cumulative distribution function (CDF) for the log-series distribution using SciPy's logser function. Specifically, when I run the following code:

`import scipy.stats as st
print(st.logser(0.25739239425774363).ppf(0.9999999999999999)) # infinite loop begins
`

The issue only arises in a Conda installation; other setups work without any problem. Upon preliminary investigation, it seems that an infinite loop is occurring within the _drv2_ppfsingle function.

![image](https://github.com/scipy/scipy/assets/8436511/18c3d5a5-23a3-4573-b9e0-5d1f3b53df54)

### Reproducing Code Example

```python
import scipy.stats as st
print(st.logser(0.25739239425774363).ppf(0.9999999999999999)) # infinite loop begins
```

### Error message

```shell
The error message is only because I interrupted command in the middle (first works, third works; second loops forever).

(/home/jovyan/conda_py312) jovyan@runner30-0:~$ python -c 'import scipy.stats as st;print(st.logser(0.25739239425774363).ppf(0.999999999999999))'
24.0


(/home/jovyan/conda_py312) jovyan@runner30-0:~$ python -c 'import scipy.stats as st;print(st.logser(0.25739239425774363).ppf(0.9999999999999999))'
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 485, in ppf
    return self.dist.ppf(q, *self.args, **self.kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3625, in ppf
    place(output, cond, self._ppf(*goodargs) + loc)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 1010, in _ppf
    return self._ppfvec(q, *args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2372, in __call__
    return self._call_as_normal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2365, in _call_as_normal
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2455, in _vectorize_call
    outputs = ufunc(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 2977, in _drv2_ppfsingle
    qb = self._cdf(b, *args)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3316, in _cdf
    return self._cdfvec(k, *args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2372, in __call__
    return self._call_as_normal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2365, in _call_as_normal
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/numpy/lib/function_base.py", line 2455, in _vectorize_call
    outputs = ufunc(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3312, in _cdf_single
    return np.sum(self._pmf(m, *args), axis=0)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/stats/_discrete_distns.py", line 899, in _pmf
    return -np.power(p, k) * 1.0 / k / special.log1p(-p)
            ^^^^^^^^^^^^^^
KeyboardInterrupt


code below works
(/home/jovyan/conda_py312) jovyan@runner30-0:~$ python -c 'import scipy.stats as st;print(st.logser(0.25739239425774363).ppf(0.99999999999999999))'
inf
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=12, micro=1, releaselevel='final', serial=0)
/home/jovyan/conda_py312/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../tmp/pip-build-env-tfqmvy7q/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
```

**Comment by ev-br** [comment]
Seems to work on main for me locally:

```
In [3]: st.logser(0.25739239425774363).ppf(0.9999999999999999)
Out[3]: 99.0

In [4]: import scipy

In [5]: scipy.__version__
Out[5]: '1.13.0.dev0+1282.c87635c'
```

**Comment by samorajp** [comment]
Yes, it's platform specific.
I found possible root cause.

When I'm executing this code on setup where bug doesn't arise, I have:
```
import scipy.stats as st
st.logser(0.25739239425774363).cdf(100) == 0.9999999999999999
```

But on problematic machine/setup/conda (I don't know what exactly is the reason):

```
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(100)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(1000)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(10000)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(100000)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(1000000)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(10000000)
0.9999999999999998
>>> import scipy.stats as st; st.logser(0.25739239425774363).cdf(100000000)
0.9999999999999998
```
No value is giving something bigger than argument which is passed to self.ppf().

**Comment by lucascolley** [comment]
>  it seems that it's not _drv2_ppfsingle function problem which assumes monotonicity of cdf, but cdf() which is not strictly increasing from some point.

makes sense, would you mind editing the title of the issue to reflect this?

**Comment by ev-br** [comment]
cross-ref https://github.com/scipy/scipy/issues/3890

**Comment by samorajp** [comment]
> > it seems that it's not _drv2_ppfsingle function problem which assumes monotonicity of cdf, but cdf() which is not strictly increasing from some point.
> 
> makes sense, would you mind editing the title of the issue to reflect this?

ok, I've edited title.

**Comment by fancidev** [comment]
Maybe worth coding an explicit CDF and PPF using formulas from Wikipedia.

**Comment by mdhaber** [comment]
> Maybe worth coding an explicit CDF and PPF using formulas from Wikipedia.

That was proposed in gh-3890. At the time, the underlying special functions were not considered reliable enough. That may have changed since then.

**Comment by mdhaber** [comment]
I'll consider this issue to be about the infinite loop in `_drv2_ppfsingle`. It will be closed by gh-21354, but we'll leave gh-3890 open about improvements to `logser.cdf` and friends.

**Comment by samorajp** [comment]
@mdhaber Thanks for fixing that!
