### ISSUE TITLE
BUG: Using LinearConstraint with optimize.differential_evolution

### ISSUE THREAD

**Issue by josh-hernandez-exe** [scipy/scipy#20041]
### Describe your issue.

When using the `scipy.optimize.differential_evolution` function with `scipy.optimize.LinearConstraint` with a matrix with more than one row results in a `ValueError: cannot reshape array of size ...`.

The code functions if the LinearConstraint only has one row in the matrix, but breaks when there is more than one.

I dug around the issue, and I suspect it's related to [this line](https://github.com/scipy/scipy/blob/0aa5aa9e78f81493f1cd9f6fc149a0bb856c2e11/scipy/optimize/_differentialevolution.py#L1224). If `x` is a 1-D array (shape `(N,)`) and the constraint has multiple rows, then the returned `c` doesn't make sense, as it should be `A @ x`. But if you resize `x` to be a 2-D array (shape `(1,N)`), then the result of `c` lines up with the `lb` and `ub` vectors you will be comparing to.

At the moment I do have a work around as follows.

```python
import functools

import numpy as np
import scipy.optimize._differentialevolution

_old_constraint_violation_fn = scipy.optimize._differentialevolution.DifferentialEvolutionSolver._constraint_violation_fn


@functools.wraps(_old_constraint_violation_fn)
def _constraint_violation_fn(self, x):
    '''
    Note that if x is a one-dimensional vector and
    not a two-dimensional vector (with one of it's dimensions of size 1)
    the resulting violation constraint matrix is incorrect.
    https://github.com/scipy/scipy/blob/0aa5aa9e78f81493f1cd9f6fc149a0bb856c2e11/scipy/optimize/_differentialevolution.py#L1194
    '''
    if isinstance(x, np.ndarray) and len(x.shape) == 1:
        x = x.reshape(1, -1)

    return _old_constraint_violation_fn(self, x)


scipy.optimize._differentialevolution.DifferentialEvolutionSolver._constraint_violation_fn = _constraint_violation_fn
```

### Reproducing Code Example

```python
import sys

import numpy as np
import scipy as sp
from scipy import optimize


def print_info():
    print(sp.__version__, np.__version__, sys.version_info)
    sp.show_config()


def objective_func(vec):
    return np.sum(vec**2)


def make_constraint(num_dims):
    num_equations = 2

    matrix = np.matrix([
        [i for _ in range(num_dims)]
        for i in range(1, num_equations+1)
    ])
    lb = np.zeros(num_equations)
    ub = np.ones(num_equations)

    return optimize.LinearConstraint(
        A=matrix,
        lb=lb,
        ub=ub,
    )


def main():
    iteration_count = 0
    num_dims = 10

    def optimization_callback(xk, convergence):
        '''
        `xk` is the best solution found so far
        `convergence` represents the fractional value of the population convergence

        Note that `convergence` is passed in as a keyword argunment
        '''
        nonlocal iteration_count
        iteration_count += 1

        print(f'{iteration_count=}')
        print(f'{xk=}')

    result = optimize.differential_evolution(
        func=objective_func,
        bounds=[
            (-10, 10)
            for _ in range(num_dims)
        ],
        constraints=[
            make_constraint(num_dims),
        ],
        callback=optimization_callback,
        polish=False,
        x0=[
            1
            for _ in range(num_dims)
        ],
    )
    print(result)


if __name__ == '__main__':
    print_info()
    main()
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/josh/Projects/personal/random/2024-02-07-scipy-bug/test_fixed.py", line 57, in <module>
    main()
  File "/home/josh/Projects/personal/random/2024-02-07-scipy-bug/test_fixed.py", line 37, in main
    result = optimize.differential_evolution(
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 502, in differential_evolution
    ret = solver.solve()
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 1151, in solve
    self._calculate_population_feasibilities(self.population))
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 1455, in _calculate_population_feasibilities
    constraint_violation = np.array([self._constraint_violation_fn(x)
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 1455, in <listcomp>
    constraint_violation = np.array([self._constraint_violation_fn(x)
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 1416, in _constraint_violation_fn
    c = np.reshape(c, (S, con.num_constr))
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/josh/.local/share/virtualenvs/random-PrsCZTb4/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 4 into shape (1,2)
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.3 sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-oj5r1eje/overlay/lib/python3.10/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by andyfaff** [comment]
I have to admit to being a little surprised by this, it's an interesting case. 

For the time being it's easy to get your code to work, just replace the matrix creation by:

```
    matrix = np.array([
        [i for _ in range(num_dims)]
        for i in range(1, num_equations+1)
    ])
```
i.e. *don't use `np.matrix` use `np.array`*. It's not recommended to use np.matrix for code, and it may be removed in the future. When `np.matrix` is used to set up the `LinearConstraint` the constraint violation comes back as having shape `(num_dims, num_dims)` instead of `(1, num_dims)`.

The "fault" is in `optimize._differentialevolution._ConstraintWrapper`. I use fault in quotes because it's not clear that this 
 should be a problem that we should fix (matrix class is not recommended)

```
from scipy.optimize._differentialevolution import _ConstraintWrapper
from scipy.optimize._constraints import LinearConstraint

A = np.array([[1, 1., 1., 1.],
              [2., 2., 2., 2.]])
x = rng.uniform(size=(4,))

lc = LinearConstraint(A, 0, 1)
cw = _ConstraintWrapper(lc, x)

evaluated_constraint = cw.fun(x)   # A.dot(x). The shape of this is (1, 2) instead of (2,). An extra dimension is created when it's not expected in the code.

# work out how much the constraints are violated by
excess_lb = np.maximum(lc.lb - evaluated_constraint.T, 0) # this has shape (2, 2) instead of (2,)
excess_ub = np.maximum(evaluated_constraint.T - lc.ub, 0) # this has shape (2, 2) instead of (2,)
v = (excess_lb + excess_ub).T  # this has shape (2, 2) instead of (2,)
```

**Comment by andyfaff** [comment]
It's not clear to me that that this should be fixed because `matrix` is effectively deprecated, and to work around this issue would add cruft that would obscure the code.
```
def fun(x):
    if issparse(constraint.A):
        A = constraint.A
    else:
        A = np.atleast_2d(constraint.A)
    res = A.dot(x)  
    if x.ndim == 1 and res.ndim > 1:
        res = np.squeeze(res)

    return A.dot(x)

```

**Comment by josh-hernandez-exe** [comment]
Honestly, before now I never knew `numpy.matrix` is not recommended. I'm finding things now, but I likely would of never looked at the docs for this. I do look at the docs frequently, but I suspect I wouldn't for the `numpy.matrix` function. Reading a bit more on the history now on [stackoverflow](https://stackoverflow.com/questions/53254738/deprecation-status-of-the-numpy-matrix-class), I understand that it's hard to officially depreciate but a warning could help a long way. Instead of what is effectively word of mouth to not use `numpy.matrix` . Though I guess this isn't an issue for this repo, unless a warning should be given here when used with  `LinearConstraint`?

**Comment by mdhaber** [comment]
I think a note in the documentation of `LinearConstraint` that `np.matrix`s shouldn't be used is warranted. 

If `LinearConstraint` doesn't work with `matrix`, and if we don't want to fix it (I agree that we shouldn't), I don't think a warning is needed; it can just produce an error. It would be better to get a specific error message that `np.matrix` is not accepted than it would be to get a confusing error later.

**Comment by andyfaff** [comment]
It's not `LinearConstraint` that's the issue here, it's in `optimize._differentialevolution._ConstraintWrapper`. 

`_ConstraintWrapper` was originally added in #10002, probably because some of the functionality that was required wasn't provided in `PreparedConstraint`/`LinearConstraint` (e.g. violation/pickleability, can't remember what).
Things are made more complex because the `_ConstraintWrapper.fun/violation` can be used in a vectorised manner. 

A fix is possible, I'll do it.

But everyone, let's stop using np.matrix.

**Comment by ilayn** [comment]
Just to give more context, `numpy.matrix` deprecation is waiting `scipy.sparse` which is probably the largest consumer. There is a work towards switching to `numpy.array` under the hood. When that happens we will make a much louder noise against `numpy.matrix`.
