### ISSUE TITLE
CI/MAINT: `choco` error for invalid credentials

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20225]
See for example the CI of gh-20224.

```
Run # mingw-w64
  # mingw-w64
  choco install rtools -y --no-progress --force --version=4.0.0.[2](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:2)0220206
  echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\[3](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:3).11.8\x6[4](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:4)
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.11.8\x[6](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:6)4/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.11.8\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.11.8\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.11.8\x64
Chocolatey v2.2.2
Installing the following packages:
rtools
By installing, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az9[7](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:7)[8](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:8)-6[9](https://github.com/scipy/scipy/actions/runs/8223396755/job/22486040140?pr=20224#step:4:9)7 (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by lucascolley** [comment]
I think this has resolved itself?

**Comment by rgommers** [comment]
> I think this has resolved itself?

Looks like it. xref https://github.com/numpy/numpy/issues/25980 for more details.
