### ISSUE TITLE
BUG: interna type error in scipy.sparse.csgraph._matching.min_weight_full_bipartite_matching

### ISSUE THREAD

**Issue by piyushsrv** [scipy/scipy#20249]
### Describe your issue.

scipy.sparse.csgraph._matching.min_weight_full_bipartite_matching reports an internal type error even with simple data.

### Reproducing Code Example

```python
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.sparse.csgraph.min_weight_full_bipartite_matching(scipy.sparse.coo_array(([1, 2, 3], ([0, 1, 2], [0, 1, 2]))), maximize=True)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_matching.pyx", line 499, in scipy.sparse.csgraph._matching.min_weight_full_bipartite_matching
ValueError: Buffer dtype mismatch, expected 'ITYPE_t' but got 'long'
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.26.4 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/piyushs/miniconda3/include
    lib directory: /home/piyushs/miniconda3/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/piyushs/miniconda3/lib/pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /home/piyushs/miniconda3/include
    lib directory: /home/piyushs/miniconda3/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/piyushs/miniconda3/lib/pkgconfig
    version: '2023.1'
  pybind11:
    detection method: pkgconfig
    include directory: /home/piyushs/miniconda3/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: /croot/scipy_1701295040508/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  c++:
    commands: /croot/scipy_1701295040508/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: /croot/scipy_1701295040508/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  pythran:
    include directory: ../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /home/piyushs/miniconda3/bin/python
  version: '3.11'
```

**Comment by piyushsrv** [comment]
I just realized that this is technically not  bug.  The error goes away if I use a `csr_matrix` instead of a `csr_array` as input to the `scipy.sparse.csgraph.min_weight_full_bipartite_matching` function.  This is what the documentation also asks for (it only mentions sparse matrices, not sparse arrays).  However, I was confused because the top-level documentation of `scipy.sparse` seems to recommend users to prefer arrays rather than matrices in new code.  Perhaps a warning in the documentation for `scipy.sparse.csgraph.min_weight_full_bipartite_matching` that the input must be a **sparse matrix** and not a **sparse array** would be sufficient.

**Comment by dschult** [comment]
That indicates it is a bug in the sparse array interface.  If it works for `csr_matrix` it should also work for `csr_array`.
So this is indeed a bug. Thanks for reporting it!

**Comment by dschult** [comment]
This appears to be a bug that the function does not work if the indices are of type `np.int64`. It occurs for `coo_matrix` when indices are big enough to need `int64` to be stored.

```python
import scipy as sp
A = sp.sparse.coo_matrix([1,2,3], ([1,2,3**34], [1,2,3]))
sp.sparse.csgraph.min_weight_full_bipartite_matching(A, maximize=true)  # leads to the same error
```

I don't know enough of the guts of csgraph or cython to figure out if this should work with `np.int64` indices. But that's the fundamental question.

A workaround for `csr_array` with smaller_than_int32max index values is to use int32 values when defining the matrix.
```python
A = sp.sparse.csr_array(([1, 2, 3], (np.array([0, 1, 2], dtype=np.int32), np.array([0, 1, 2], dtype=np.int32))))
```
But the real fix is to make this function work for int64 indices.  [The reason csr_array uses int64 is because it follows the protocol that type should not depend on value -- only dtype of incoming values. And incoming values are python ints.)

**Comment by Kai-Striega** [comment]
I've had a quick look at this. It looks like we are defining the work arrays as `ITYPE` which is an alias for ``np.int32``. You can see the definitions below:

https://github.com/scipy/scipy/blob/9a5118633252eb714e1abcafba036d4295a146be/scipy/sparse/csgraph/_matching.pyx#L580-L597

I'm not 100% sure if this is right, but, maybe we should work on templating the underlying function based on the dtype of the incoming array?

**Comment by qtov** [comment]
I've got the same error for scipy `1.12.0`, but when I downgrade to `1.10.1` it works. `1.11.0` also gives the same error.

I was using a graph dumped by networkx for this.
```python
from scipy.sparse.csgraph import maximum_bipartite_matching

# graph is of type networkx.classes.graph.Graph
g = networkx.to_scipy_sparse_array(graph, dtype=np.int32)
matches = maximum_bipartite_matching(g)
```

Gives this output:
```
>   ???
E   ValueError: Buffer dtype mismatch, expected 'ITYPE_t' but got 'long'

_matching.pyx:142: ValueError
```

Mine is not solved by converting to matrix tho, still gives the same error.
