### ISSUE TITLE
BUG: nightly wheels fail with released numpy

### ISSUE THREAD

**Issue by jorisvandenbossche** [scipy/scipy#20286]
### Describe your issue.

The nightly scipy wheels are built with numpy 2.0.dev, to ensure they are compatible with the numpy nightly version. But normally those wheels should then also be compatible with older versions of numpy. But that doesn't seem to be the case, or at least not in the specific reproducer below.

### Reproducing Code Example

```python
$ mamba create -n test-scipy-wheel python=3.11 pip
$ mamba activate test-scipy-wheel
# installs numpy 1.26.4
$ pip install numpy
# installs scipy 1.14.0.dev0
$ pip install --pre --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --extra-index-url https://pypi.org/simple scipy
```

### Error message

```shell
>>> from scipy.stats import gaussian_kde
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/conda/envs/test-scipy-wheel/lib/python3.11/site-packages/scipy/stats/__init__.py", line 606, in <module>
    from ._stats_py import *
  File "/home/joris/conda/envs/test-scipy-wheel/lib/python3.11/site-packages/scipy/stats/_stats_py.py", line 38, in <module>
    from scipy.spatial.distance import cdist
  File "/home/joris/conda/envs/test-scipy-wheel/lib/python3.11/site-packages/scipy/spatial/__init__.py", line 110, in <module>
    from ._kdtree import *
  File "/home/joris/conda/envs/test-scipy-wheel/lib/python3.11/site-packages/scipy/spatial/_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
  File "_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
ValueError: numpy.broadcast size changed, may indicate binary incompatibility. Expected 816 from C header, got 560 from PyObject
```

### SciPy/NumPy/Python version and system information

```shell
>>> import scipy
>>> scipy.show_config()
/home/joris/conda/envs/test-scipy-wheel/lib/python3.11/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.9",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../opt/python/cp311-cp311/lib/python3.11/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.26",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.26",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp311-cp311/bin/python",
    "version": "3.11"
  }
}
```

**Comment by lucascolley** [comment]
See gh-20268 and the linked NumPy issue

**Comment by jorisvandenbossche** [comment]
Ah, thanks for the link, and sorry for the duplicate! I did search for recent issues, but missed that obvious issue because of including "wheel" in my search instead of just looking at all recent issues ;)

So this should be fixed on numpy's side now (and should be resolved once both numpy and scipy have rebuilt the nightly wheels, I assume).
