### ISSUE TITLE
BUG: Memory optimization in griddata function

### ISSUE THREAD

**Issue by GiggioIlGriggio** [scipy/scipy#20357]
### Describe your issue.

I'm working on interpolating big sparse matrices, and i noticed that upgrading from version 1.11.3 to version 1.12 my code gives me a memory error using the function griddata from scipy.interpolate, saying that is trying to allocate 45 GB.
The exact same code works fine in 1.11.3 allocating 16GB of memory in total.
The matrix in question has a shape of (14790, 12816) and the dtype is float32.
My machine has 32GB of RAM.

### Reproducing Code Example

```python
if depth_mask is not None:
        depth_mask_cut = depth_mask[bottom_index:top_index, left_index:right_index]
        depth_mask_cut = normalize_non_zero_elements(depth_mask_cut)
        print(depth_mask_cut.shape)
        if config.depth_interpolation:
            coords = np.column_stack(np.nonzero(depth_mask_cut))
            values = depth_mask_cut[coords[:, 0], coords[:, 1]]
            grid_x, grid_y = np.mgrid[0:depth_mask_cut.shape[0], 0:depth_mask_cut.shape[1]]
            depth_mask_cut = griddata(coords, values, (grid_x, grid_y), method='cubic')
```

### Error message

```shell
Traceback (most recent call last):
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\preprocess_data.py", line 51, in <module>
    main()
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\preprocess_data.py", line 47, in main
    preprocess_data(config)
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\utils\dataset_handler.py", line 74, in preprocess_data
    cutted_mask, cutted_depth_mask, cutted_image = preprocess_mask_image(mask, image, depth_mask, config)
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\utils\utils.py", line 517, in preprocess_mask_image
    depth_mask_cut = griddata(coords, values, (grid_x, grid_y), method='cubic')
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\building_detection_enviroment\lib\site-packages\scipy\interpolate\_ndgriddata.py", line 329, in griddata
    return ip(xi)
  File "interpnd.pyx", line 192, in scipy.interpolate.interpnd.NDInterpolatorBase.__call__
  File "interpnd.pyx", line 969, in scipy.interpolate.interpnd.CloughTocher2DInterpolator._evaluate_double
  File "interpnd.pyx", line 990, in scipy.interpolate.interpnd.CloughTocher2DInterpolator._do_evaluate
  File "interpnd.pyx", line 172, in scipy.interpolate.interpnd.NDInterpolatorBase._find_simplicies
  File "C:\Users\aleal\Documents\Geoin\Aerial instance segmentation\building-detection\rooftops_detection_from_aerial_images\building_detection_enviroment\lib\site-packages\numpy\lib\function_base.py", line 962, in copy
    return array(a, order=order, subok=subok, copy=True)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 45.2 GiB for an array with shape (189548640, 32) and data type float64
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-bidi1l_7\\overlay\\Lib\\site-packages/pythran"   
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-u773bfjp\\cp310-win_amd64\\build\\venv\\Scripts\\python.exe",        
    "version": "3.10"
  }
}
```

**Comment by ev-br** [comment]
Can you add a reproducible example --- something we can run as a standalone script, which defines all input arrays etc.

**Comment by GiggioIlGriggio** [comment]
I have just updated the issue code section.

**Comment by ev-br** [comment]
Thanks. So sparse matrices here is only a means to construct (rather large) dense inputs to `griddata`: it only receives dense ndarrays and never sees any csr_matrices. Good -- because it never supported and is unlikely to ever support sparse arrays directly.

The only PR which touched CloughTocher2DInterpolator in the 1.12.x time frame was https://github.com/scipy/scipy/pull/18376, any ideas @hovavalon ?

**Comment by hovavalon** [comment]
After inspecting my changes, I think the source of the defect is that after my changes indeed more memory is used, as the data about the location and simplicies of all the input points is kept in the memory at once.
In the `_find_simplicies` function, I use `np.copy` in order to return the locally defined cython arrays as numpy arrays.
I think that a possible solution is to replace the `_find_simplicies` function with `_find_simplex`, which will find a single simplex, and will be used in the `_do_evaluate` function.
A class may override this function so that it computes all the simplicies and saves them, and then just queries the saved results on call.

A possible temporary (and very ugly) solution is to split the data and call  `griddata` a few times. You might need to call the garbage collector between subsequent calls. I am sorry, I should have checked my changes on larger inputs.

What do you think?
Unfortunately, I won't have the time to create a PR in the next few weeks, but I will try to assist, and might fix it later myself if no one else will.

**Comment by ev-br** [comment]
Going back to `_find_simplex` sounds right indeed. This would get us back to the `c` array being `double[NPY_MAXARGS]` instead of O(number_of_data_points times NPY_MAXARGS).
