### ISSUE TITLE
BUG: `optimize.linprog` fails with `list` type `integrality` containing only zeros

### ISSUE THREAD

**Issue by hitonanode** [scipy/scipy#20584]
### Describe your issue.

The code pasted below causes a runtime error. It is simply a modification of the test problem added in https://github.com/scipy/scipy/pull/17513, where all variables have been changed to continuous ones.

I have conducted a local check, and I believe that a modification similar to the one shown in https://github.com/scipy/scipy/compare/main...hitonanode:scipy:fix-linprog-integrality might resolve the issue.

### Reproducing Code Example

```python
from scipy.optimize import linprog

linprog([1, 1], A_ub=[[-1, 0]], b_ub=[-2.5], integrality=[0, 0])
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/test-D9Qlf53g-py3.11/lib/python3.11/site-packages/scipy/optimize/_linprog.py", line 644, in linprog
    _check_result(sol['x'], sol['fun'], sol['status'], sol['slack'],
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/test-D9Qlf53g-py3.11/lib/python3.11/site-packages/scipy/optimize/_linprog_util.py", line 1496, in _check_result
    valid_bounds |= (integrality > 1) & np.isclose(x, 0, atol=tol)
                     ^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'list' and 'int'
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.13.0 1.26.4 sys.version_info(major=3, minor=11, micro=8, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
I'll submit a PR shortly.
