### ISSUE TITLE
BUG: ImportError: DLL load failed while importing nct_ufunc

### ISSUE THREAD

**Issue by JoyLinWQ** [scipy/scipy#20758]
### Describe your issue.

Error 1:
```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\ovdsat\build_prototypes.py", line 25, in <module>
    from sklearn.cluster import KMeans
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\__init__.py", line 87, in <module>
    from .base import clone
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._estimator_html_repr import estimator_html_repr
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\_estimator_html_repr.py", line 10, in <module>
    from .fixes import parse_version
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\fixes.py", line 17, in <module>
    import scipy.stats
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ModuleNotFoundError: No module named 'scipy.stats._boost.nct_ufunc'
```

This led to a forced installation `pip install --ignore-installed scipy` (scipy v1.13.0) as the `C:\Users\XXX\anaconda3\envs\ovdsat\Lib\site-packages\scipy\stats\_boost\nct_ufunc.cp39-win_amd64.pyd` file is missing.

However, the next error below surfaced.

Error 2:
```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\ovdsat\build_prototypes.py", line 25, in <module>
    from sklearn.cluster import KMeans
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\__init__.py", line 87, in <module>
    from .base import clone
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._estimator_html_repr import estimator_html_repr
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\_estimator_html_repr.py", line 10, in <module>
    from .fixes import parse_version
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\sklearn\utils\fixes.py", line 17, in <module>
    import scipy.stats
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ImportError: DLL load failed while importing nct_ufunc: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

Downgrading from scipy v1.13.0 to v1.12.0 solved the problem. 
Pls assist to see why it cannot run on v1.13.0. 
Thanks in advance.

### Reproducing Code Example

```python
Above was from https://github.com/xavibou/ovdsat/tree/main
running the script `bash scripts/init_prototypes.sh`
```

### Error message

```shell
as above
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy
>>> print(scipy.__version__, numpy.__version__, sys.version_info)
1.12.0 1.26.4 sys.version_info(major=3, minor=9, micro=19, releaselevel='final', serial=0)
>>> scipy.show_config()
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-rikezz0v\overlay\Lib\site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-ee1litsm\cp39-win_amd64\build\venv\Scripts\python.exe
  version: '3.9'
```

**Comment by j-bowhay** [comment]
Can you provide an example code  for when this error occurs (preferably that does not use other libraries)

**Comment by JoyLinWQ** [comment]
> Can you provide an example code for when this error occurs (preferably that does not use other libraries)

im not exactly sure how to do that as i only encounter this error when using this package...

**Comment by nickodell** [comment]
>Should i proceed to restore file and re-run test above?

Yes, that sounds good.

**Comment by JoyLinWQ** [comment]
> > Should i proceed to restore file and re-run test above?
> 
> Yes, that sounds good.

Ok, i get the same error message as above.

```
(ovdsat2) PS C:\Users\XXX\Documents\ovdsat> python .\test.py
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\ovdsat\test.py", line 1, in <module>
    import scipy.stats
  File "C:\Users\XXX\anaconda3\envs\ovdsat2\lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\Users\XXX\anaconda3\envs\ovdsat2\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\Users\XXX\anaconda3\envs\ovdsat2\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\Users\XXX\anaconda3\envs\ovdsat2\lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\Users\XXX\anaconda3\envs\ovdsat2\lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ImportError: DLL load failed while importing nct_ufunc: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

**Comment by nickodell** [comment]
Got it. Do you have any other anti-virus software installed, such as Windows Defender?

**Comment by JoyLinWQ** [comment]
> Got it. Do you have any other anti-virus software installed, such as Windows Defender?

Besides mcafee (which i installed) and windows defender (by default i guess?), nothing else i know of. I can check if u have any specific ones in mind. 

2 qns i have in mind though.
1. Scipy 1.12.0 works fine even when the file is quarantined. Is the older version not using this file at all?
2. When scipy 1.13.0 uses this restored file for the imports, is anti-virus still blocking something and causing the DLL error or could it be something else?

**Comment by nickodell** [comment]
>I can check if u have any specific ones in mind.

Can you check if Windows Defender has quarantined this file?

>Is the older version not using this file at all?

I think so. See https://github.com/scipy/scipy/pull/16591, which changed our implementation of the non central T distribution to Boost's version for accuracy reasons. I believe that change happened in 1.13.0.

>When scipy 1.13.0 uses this restored file for the imports, is anti-virus still blocking something and causing the DLL error or could it be something else?

I think this is still being caused by antivirus, based on the error message.

The error message contains the phrase: "Operation did not complete successfully because the file contains a virus or potentially unwanted software."

**Comment by JoyLinWQ** [comment]
> Can you check if Windows Defender has quarantined this file?

Oh, i realised i didnt choose to turn on Windows Defender as Mcafee is active, hence no quarantined files.
