### ISSUE TITLE
BUG: ``optimize.nnls`` sometimes fails when input ``A`` is a Fortran order array

### ISSUE THREAD

**Issue by wangzcl** [scipy/scipy#20813]
### Describe your issue.

Lastest stable version of ``scipy.optimize.nnls`` (1.13.1) is sometimes sensitive to input array memory layout. For certain input arrays, ``nnls`` works fine with c-contiguous arrays, but raises ``RuntimeError`` for Fortran order arrays. 

Interestingly, the reproducibility of this error is very sensitive to the values of the array (see example below).

Older version of nnls (scipy 1.11.4, written in Fortran) always work fine. As far as I know, This error appears on multiple platforms (MacOS, Ubuntu) and multiple python versions (3.8, 3.9, 3.10, 3.12)

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import nnls


A1 = np.array(
    [
        [
            5.6804456109393231e-01,
            7.7293613312687126e-01,
            5.3596749047874905e-02,
            6.6478181730523378e-01,
        ],
        [
            9.2559663829266103e-01,
            8.7034572210281691e-01,
            3.6157431133730261e-01,
            4.8690183372106080e-02,
        ],
        [
            7.1036058197886942e-02,
            9.7838908691940440e-01,
            3.3106681832243329e-01,
            7.0049535992329526e-01,
        ],
        [
            2.0000000000000000e02,
            2.0000000000000000e02,
            2.0000000000000000e02,
            2.0000000000000000e02,
        ],
    ]
)

b1 = np.array(
    [5.680445610939323e-01, 9.255966382926610e-01, 7.103605819788694e-02, 2.000000000000000e02]
)

A2 = np.asfortranarray(A1)
b2 = b1  # or b2 = np.asfortranarray(b1), both will raise Error

print(nnls(A1, b1))  # This works
print(nnls(A2, b2))  # This raises RuntimeError("Maximum number of iterations reached.") 
# Won't be fixed even if ``maxiter`` is set to 1000

"""
Interestingly, when using lower precision but almost same values, There will not be any error:
A1 = np.array(
    [
        [5.68044561e-01, 7.72936133e-01, 5.35967490e-02, 6.64781817e-01],
        [9.25596638e-01, 8.70345722e-01, 3.61574311e-01, 4.86901834e-02],
        [7.10360582e-02, 9.78389087e-01, 3.31066818e-01, 7.00495360e-01],
        [2.00000000e02, 2.00000000e02, 2.00000000e02, 2.00000000e02],
    ]
)

b1 = np.array(
    [5.68044561e-01, 9.25596638e-01, 7.10360582e-02, 2.00000000e02],
)

A2 = np.asfortranarray(A1)
b2 = b1

print(nnls(A1, b1))  # This works
print(nnls(A2, b2))  # This works

"""
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/zwang505/Code/archetypes/examples/test_nnls.py", line 41, in <module>
    print(nnls(A2, b2))  # This raises RuntimeError("Maximum number of iterations reached.")
  File "/Users/zwang505/Code/archetypes/.venv/lib/python3.9/site-packages/scipy/optimize/_nnls.py", line 93, in nnls
    raise RuntimeError("Maximum number of iterations reached.")
RuntimeError: Maximum number of iterations reached.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=9, micro=18, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../../../../../private/var/folders/2f/8t5k6yr535sdw0s4glnpxrzm0000gn/T/pip-build-env-ddcl7dz8/overlay/lib/python3.9/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/2f/8t5k6yr535sdw0s4glnpxrzm0000gn/T/cibw-run-_36keccq/cp39-macosx_arm64/build/venv/bin/python
  version: '3.9'
```

**Comment by tylerjereddy** [comment]
> Older version of nnls (scipy 1.14.0, written in Fortran) always work fine.

Did you mean to write an older version number for SciPy there?

**Comment by wangzcl** [comment]
> > Older version of nnls (scipy 1.14.0, written in Fortran) always work fine.
> 
> Did you mean to write an older version number for SciPy there?

Just fixed it. It should be 1.11.4. The source code was transferred from Fortran to Python in 1.12.0. Sorry for the typo.

**Comment by dschmitz89** [comment]
Cc @ilayn

**Comment by ilayn** [comment]
Such a strange bug indeed. I'll take a look.

**Comment by ilayn** [comment]
This is turning out to be an architectural problem, not to say that it's on us, but there is some upstream issues here. 

On my machine, Win10 and Linux Mint both PyPi installed SciPy I get 

```python
(array([1., 0., 0., 0.]), np.float64(0.0))
(array([1.00000000e+00, 8.37931024e-12, 0.00000000e+00, 0.00000000e+00]), np.float64(7.808184665241417e-12))
```

for the given example. I'm rewriting the code to be a little bit better flowing but this has still not failed as given in the OP. Plot thickens.
