### ISSUE TITLE
BUG: Library not loaded: @rpath/libgfortran.5.dylib for scipy v1.14.0rc1 x86 macos wheels

### ISSUE THREAD

**Issue by matthewfeickert** [scipy/scipy#20852]
### Describe your issue.

For SciPy release candidate [`v1.14.0rc1`](https://pypi.org/project/scipy/1.14.0rc1/#files) the `x86` macOS wheels will error out with

```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
```

on import of `scipy.special`.

![image](https://github.com/scipy/scipy/assets/5142394/f6b8b3d5-e95b-498c-af6c-0928d353703a)

### Reproducing Code Example

Here is the workflow YAML for a full reproducer in GitHub Actions:

```yaml
name: Reproducer

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  example:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade 'scipy==1.14.0rc1'
        python -m pip install --upgrade pyyaml  # given reporting information
        python -m pip list

    - name: Reporting information
      run: |
        python -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()'

    - name: Reproducer
      run: |
        python -c 'from scipy import special'
```

but on an x86 macOS just

```
python -m pip install --upgrade 'scipy==1.14.0rc1'
python -c 'from scipy import special'
```

is enough.

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/special/__init__.py", line 820, in <module>
    from . import _orthogonal
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/linalg/__init__.py", line 222, in <module>
    from ._sketches import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/linalg/_sketches.py", line 9, in <module>
    from scipy.sparse import csc_matrix
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/__init__.py", line 307, in <module>
    from . import csgraph
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/csgraph/__init__.py", line 187, in <module>
    from ._laplacian import laplacian
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/__init__.py", line 132, in <module>
    from ._eigen import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/__init__.py", line 9, in <module>
    from .arpack import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/__init__.py", line 20, in <module>
    from .arpack import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 48, in <module>
    from . import _arpack
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
  Referenced from: <7C2A9D44-8556-309A-BF2C-0E48CBA31E6C> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so
  Reason: tried: '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)
```

### SciPy/NumPy/Python version and system information

<details>

```shell
1.14.0rc1 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Sandybridge
      MAX_THREADS=64
    pc file directory: /Users/runner/work/scipy/scipy
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Sandybridge
      MAX_THREADS=64
    pc file directory: /Users/runner/work/scipy/scipy
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 13.1.6
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 13.1.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 11.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/pip-build-env-usrnp1ch/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
Python Information:
  path: /private/var/folders/n8/w901w1rn4ldg6yskstndsj200000gn/T/cibw-run-dk691tbh/cp312-macosx_x86_64/build/venv/bin/python
  version: '3.12'
```

</details>

**Comment by matthewfeickert** [comment]
Unsurprisingly, the same thing is happening for the [nightly wheels](https://anaconda.org/scientific-python-nightly-wheels/scipy) also:

![image](https://github.com/scipy/scipy/assets/5142394/95c9b6a6-d8a1-4a7b-ac05-5efcc6280bea)


<details>
<summary>Workflow YAML with nightly wheel:</summary>

```yaml
name: Reproducer

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  example:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade 'scipy==1.14.0rc1'
        python -m pip install --upgrade pyyaml  # given reporting information
        python -m pip list

    - name: Reporting information
      run: |
        python -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()'

    - name: Reproducer
      run: |
        python -c 'from scipy import special'

  nightly-wheel:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade scipy  # ensure default install deps
        python -m pip uninstall --yes scipy
        python -m pip install --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scipy
        python -m pip install --upgrade pyyaml  # given reporting information
        python -m pip list

    - name: Reporting information
      run: |
        python -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()'

    - name: Reproducer
      run: |
        python -c 'from scipy import special'
```

</details>

**Comment by lucascolley** [comment]
could this be related to any of your work @thalassemia ?

**Comment by andyfaff** [comment]
@tylerjereddy this will probably be a blocker for the release. I think this will probably be related to @mattip work on scipy_openblas32.

For scipy-1.14.0rc1-cp312-cp312-macosx_10_9_x86_64.whl

Let's look at the libs
```
(dev3) 192-168-1-105:.dylibs andrew$ otool -L *.dylib
libgcc_s.1.1.dylib (architecture x86_64):
	/DLC/scipy/.dylibs/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
libgfortran.5.dylib:
	/DLC/scipy/.dylibs/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	@loader_path/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
libquadmath.0.dylib:
	/DLC/scipy/.dylibs/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
libscipy_openblas.dylib:
	/DLC/scipy/.dylibs/libscipy_openblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	@loader_path/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	@loader_path/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
```

Let's look at one of the dylibs.
```
(dev3) 192-168-1-105:arpack andrew$ otool -L _arpack.cpython-312-darwin.so 
_arpack.cpython-312-darwin.so:
	@loader_path/../../../../.dylibs/libscipy_openblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

It looks like the path isn't fixed properly in the .so.

**Comment by andyfaff** [comment]
```
(dev3) 192-168-1-105:Downloads andrew$ delocate-listdeps scipy-1.14.0rc1-cp312-cp312-macosx_10_9_x86_64.whl 
/usr/local/lib/libgcc_s.1.1.dylib
/usr/local/lib/libgfortran.5.dylib
/usr/local/lib/libquadmath.0.dylib
scipy/.dylibs/libgcc_s.1.1.dylib
scipy/.dylibs/libgfortran.5.dylib
scipy/.dylibs/libquadmath.0.dylib
scipy/.dylibs/libscipy_openblas.dylib
scipy/special/libsf_error_state.dylib
```
I think this is further evidence for the paths not being amended correctly, these should all be `scipy/.dylibs`.

**Comment by andyfaff** [comment]
It looks like the build process is using libgfortran from /usr/local/lib (as installed by cibw_before_build_macos). However, this is prevented from being delocated because paths with `/gfortran` are excluded in the `delocate` call, https://github.com/scipy/scipy/blob/ba7644bb6d69ac8e322b33f1b78673292a93cba5/.github/workflows/wheels.yml#L161

Whilst libgfortran is bundled into the wheel I think delocate isn't patching the non-importable dylibs because the libgfortran they're linked against is excluded, and the delocate process can't find a suitable replacement from its environment.

This is something that Matti will be best placed to address.

**Comment by andyfaff** [comment]
I think a possible solution would be to change PREFIX to something like:

```
PREFIX=DYLD_LIBRARY_PATH=$(python -c "import scipy_openblas32 as sob;print(sob.get_lib_dir())")/../.dylibs"
```

**Comment by andyfaff** [comment]
Hmm, I tried something like the previous comment, but it didn't work. I think it's going to be necessary for all .so to be linked against the same libgfortran dylib. At the moment most of the .so are linked against the compiler libgfortran, but the libscipy_openblas is linked against one from a different location. delocate bundles the one required for libscipy_openblas, but can't recognise that that one is also ok for all the other .so.

**Comment by andyfaff** [comment]
Removed the labels, because issue applies to all .so that link against libgfortran.

**Comment by andyfaff** [comment]
I tried using `install_name_tool` on the _arpack.so in the pre release wheel to make it find the already bundled libgfortran, but there's an immediate segfault.

**Comment by mattip** [comment]
> there's an immediate segfault.

Thanks for looking into this. I think the segfault is because the linking is not done with `headerpad_max_install_names` (i.e. `-Wl,-headerpad_max_install_names`) which will preserve enough space to allow modification of the install name

**Comment by andyfaff** [comment]
The delocate doesn't seem to have attempted to rewrite the libgfortran location for those SO though (not enough info though).
 The location of the libgfortran in the libscipy_openblas  wheel doesn't appear to be provided in the repair invocation, and it's not the library that's linked during the build process

**Comment by mattip** [comment]
Where can I track your changes?

**Comment by rgommers** [comment]
I'm a little confused why the test stage of the relevant wheel build jobs didn't fail here. We should investigate that.

**Comment by andyfaff** [comment]
My guess is that whilst the tests are done in a new python environment, `dyld` can still find the correct library in /usr/local/lib. In order to pick this up you either have to remove the library from that path, or run the tests in a totally new container.

**Comment by andyfaff** [comment]
In https://github.com/andyfaff/scipy/pull/69 I amend the wheel building process to show that removing the libgfortran dylibs that are used for linking (`rm -rf /usr/local/gfortran/lib`) makes the post-build tests fail, see https://github.com/andyfaff/scipy/actions/runs/9342115595/job/25709721944?pr=69 for what happens.

```
  E   ImportError: dlopen(/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-bb9i5_xw/cp312-macosx_arm64/venv-test-arm64/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
```

i.e. the install name for libgfortran is not correct for any fortran SO.

**Comment by rgommers** [comment]
I have yanked the release to avoid more users running into broken wheels:

<img width="586" alt="image" src="https://github.com/scipy/scipy/assets/98330/36b7a2d5-b625-46ae-b1b7-48270612fea7">

**Comment by rgommers** [comment]
> I think it's going to be necessary for all .so to be linked against the same libgfortran dylib

This wasn't the case before gh-20585 either, that PR just changed from the tarball to the wheel install method. So that should be fine I'd expect.

**Comment by andyfaff** [comment]
> Sorry for the mess.

It's just the cost of pushing back the frontiers, don't worry about it.

**Comment by andyfaff** [comment]
The cirrus job is failing because `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` when cibuildwheel starts, so the location isn't being found correctly.
