### ISSUE TITLE
BUG: 'simps' not found from 'scipy.integrate'

### ISSUE THREAD

**Issue by gusmihaian** [scipy/scipy#21070]
### Describe your issue.

I'm trying to install caiman manager into my environment and something seems to be wrong with scipy and doesn't allow me to do it. 'simps' seems to be missing or relocated.

### Reproducing Code Example

```python
caimanmanager install
```

### Error message

```shell
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mescore/bin/caimanmanager", line 7, in <module>
    from caiman.caimanmanager import main
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/__init__.py", line 4, in <module>
    from caiman.base.movies import movie, load, load_movie_chain, _load_behavior, play_movie
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/base/movies.py", line 36, in <module>
    import caiman.summary_images
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/summary_images.py", line 18, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/source_extraction/cnmf/__init__.py", line 4, in <module>
    from . import cnmf
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 30, in <module>
    from caiman.components_evaluation import estimate_components_quality
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/caiman/components_evaluation.py", line 8, in <module>
    import peakutils
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/peakutils/__init__.py", line 2, in <module>
    from .peak import *
  File "/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/peakutils/peak.py", line 7, in <module>
    from scipy.integrate import simps
ImportError: cannot import name 'simps' from 'scipy.integrate' (/opt/miniconda3/envs/mescore/lib/python3.11/site-packages/scipy/integrate/__init__.py)
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
/opt/miniconda3/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "12.0.0",
      "commands": "arm64-apple-darwin20.0.0-clang",
      "args": "-ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /opt/miniconda3/include, -mmacosx-version-min=11.1",
      "linker args": "-Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/opt/miniconda3/lib, -L/opt/miniconda3/lib, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /opt/miniconda3/include, -mmacosx-version-min=11.1"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "12.0.0",
      "commands": "arm64-apple-darwin20.0.0-clang++",
      "args": "-ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /opt/miniconda3/include, -mmacosx-version-min=11.1",
      "linker args": "-Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/opt/miniconda3/lib, -L/opt/miniconda3/lib, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /opt/miniconda3/include, -mmacosx-version-min=11.1"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "11.2.0",
      "commands": "/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/_build_env/bin/arm64-apple-darwin20.0.0-gfortran",
      "args": "-march=armv8-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix",
      "linker args": "-Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/opt/miniconda3/lib, -L/opt/miniconda3/lib, -march=armv8-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /opt/miniconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_41w43uybvr/croot/scipy_1710947318888/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/opt/miniconda3=/usr/local/src/conda-prefix"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../../../../../../../../../../opt/miniconda3/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21",
      "detection method": "pkgconfig",
      "include directory": "/opt/miniconda3/include",
      "lib directory": "/opt/miniconda3/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128",
      "pc file directory": "/opt/miniconda3/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21",
      "detection method": "pkgconfig",
      "include directory": "/opt/miniconda3/include",
      "lib directory": "/opt/miniconda3/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128",
      "pc file directory": "/opt/miniconda3/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.10.4",
      "detection method": "pkgconfig",
      "include directory": "/opt/miniconda3/include"
    }
  },
  "Python Information": {
    "path": "/opt/miniconda3/bin/python",
    "version": "3.12"
  }
}
```

**Comment by j-bowhay** [comment]
Thanks @gusmihaian, `integrate.simps` was deprecated in favour of `integrate.simpson` as per the release notes https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations . Please raise this with the upstream package as this will need to be fixed at their end. In the meantime you can install a version of SciPy older than 1.14

**Comment by gusmihaian** [comment]
Thanks a lot!
