### ISSUE TITLE
BUG/DEV: `PytestUnknownMarkWarning` from `-t`

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21075]
### Describe your issue.

see below

### Reproducing Code Example

```python
python dev.py test -t scipy.stats.tests # works fine
python dev.py test -t scipy.stats.tests.test_stats.py
```

### Error message

```shell
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 335, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 648, in perform_collect
INTERNALERROR>     fspath, parts = resolve_collection_argument(
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 896, in resolve_collection_argument
INTERNALERROR>     strpath = search_pypath(strpath)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/main.py", line 852, in search_pypath
INTERNALERROR>     spec = importlib.util.find_spec(module_name)
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/importlib/util.py", line 94, in find_spec
INTERNALERROR>     parent = __import__(parent_name, fromlist=['__path__'])
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>   File "/Users/lucascolley/programming/scipy/build-install/lib/python3.10/site-packages/scipy/stats/tests/test_stats.py", line 48, in <module>
INTERNALERROR>     skip_xp_backends = pytest.mark.skip_xp_backends
INTERNALERROR>   File "/Users/lucascolley/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/_pytest/mark/structures.py", line 549, in __getattr__
INTERNALERROR>     warnings.warn(
INTERNALERROR> pytest.PytestUnknownMarkWarning: Unknown pytest.mark.skip_xp_backends - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+1018.c509a54 1.26.4 sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    lib directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=128
    pc file directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib/pkgconfig
    version: 0.3.24
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    lib directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=128
    pc file directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib/pkgconfig
    version: 0.3.24
  pybind11:
    detection method: pkgconfig
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include, -D_FORTIFY_SOURCE=2, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -ftree-vectorize, -fPIC,
      -fstack-protector-strong, -O2, -pipe, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: clang
    version: 16.0.6
  c++:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++,
      -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -ftree-vectorize, -fPIC,
      -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden,
      -fmessage-length=0, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: clang
    version: 16.0.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe,
      -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: /Users/lucascolley/mambaforge/envs/scipy-dev/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -march=armv8.3-a, -ftree-vectorize,
      -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/lucascolley/mambaforge/envs/scipy-dev/bin/python3.10
  version: '3.10'
```

**Comment by WarrenWeckesser** [comment]
Don't include `.py` in the name.  The `-t` argument is for Python modules, not filenames.

**Comment by lucascolley** [comment]
Aha, I remember using your second example in the past, and was confused as to what has changed. I replaced the `/`'s with `.`'s, but did not remove `.py`. Thanks Warren!
