### ISSUE TITLE
Error when I try to install Scipy version 1.10.0 on a python:3.9.11-alpine docker image

### ISSUE THREAD

**Issue by MarcusPaiva** [scipy/scipy#21100]
Hello, I'm trying to install a scipy in a docker container with the python:3.9.11-alpine image and when I try to install scipy 1.10.0 it gives this error message in the build:

```
354.1   Downloading scipy-1.10.0.tar.gz (42.4 MB)
355.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 11.3 MB/s eta 0:00:00
365.4   Installing build dependencies: started
375.7   Installing build dependencies: finished with status 'done'
375.7   Getting requirements to build wheel: started
375.7   Getting requirements to build wheel: finished with status 'done'
375.8   Installing backend dependencies: started
377.6   Installing backend dependencies: finished with status 'done'
377.6   Preparing metadata (pyproject.toml): started
438.7   Preparing metadata (pyproject.toml): still running...
525.1   Preparing metadata (pyproject.toml): still running...
544.5   Preparing metadata (pyproject.toml): finished with status 'error'
544.5   error: subprocess-exited-with-error
544.5
544.5   × Preparing metadata (pyproject.toml) did not run successfully.
544.5   │ exit code: 1
544.5   ╰─> [1019 lines of output]
544.5       The Meson build system
544.5       Version: 1.4.1
544.5       Source dir: /tmp/pip-install-7ze1o55k/scipy_6548218fcc6e46b5b47242e1b9d226d4
544.5       Build dir: /tmp/pip-install-7ze1o55k/scipy_6548218fcc6e46b5b47242e1b9d226d4/.mesonpy-du4iuxkl/build
544.5       Build type: native build
544.5       Project name: SciPy
544.5       Project version: 1.10.0
544.5       C compiler for the host machine: cc (gcc 13.2.1 "cc (Alpine 13.2.1_git20240309) 13.2.1 20240309")
544.5       C linker for the host machine: cc ld.bfd 2.42
544.5       C++ compiler for the host machine: c++ (gcc 13.2.1 "c++ (Alpine 13.2.1_git20240309) 13.2.1 20240309")
544.5       C++ linker for the host machine: c++ ld.bfd 2.42
544.5       Host machine cpu family: x86_64
544.5       Host machine cpu: x86_64
544.5       Compiler for C supports arguments -Wno-unused-but-set-variable: YES
544.5       Compiler for C supports arguments -Wno-unused-function: YES
544.5       Compiler for C supports arguments -Wno-conversion: YES
544.5       Compiler for C supports arguments -Wno-misleading-indentation: YES
544.5       Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
544.5       Library m found: YES
544.5       [785/1620] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cpython-310-x86_64-linux-gnu.so.p/csc.cxx.o
544.5       [786/1620] Compiling Fortran object scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-310-x86_64-linux-gnu.so.p/.._.._.._..__build_utils_src_wrap_dummy_g77_abi.f.o
544.5       [787/1620] Generating scipy/stats/statlib_module with a custom command
544.5       [788/1620] Compiling C object scipy/sparse/csgraph/_shortest_path.cpython-310-x86_64-linux-gnu.so.p/meson-generated__shortest_path.c.o
544.5       [789/1620] Linking target scipy/sparse/csgraph/_shortest_path.cpython-310-x86_64-linux-gnu.so
544.5       [790/1620] Compiling C++ object scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/biasedurn_impls.cpp.o
544.5       [791/1620] Module scanner.
544.5       [792/1620] Compiling Fortran object scipy/stats/_statlib.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__statlib-f2pywrappers.f.o
544.5       [793/1620] Generating scipy/stats/mvn_module with a custom command
544.5       [794/1620] Generating scipy/stats/_stats_gen_pyx with a custom command
544.5       [795/1620] Compiling C++ object scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/biasedurn_stoc1.cpp.o
544.5       [796/1620] Module scanner.
544.5       [797/1620] Compiling C++ object scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/biasedurn_fnchyppr.cpp.o
544.5       [798/1620] Compiling C object scipy/stats/_statlib.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__statlibmodule.c.o
544.5       [799/1620] Compiling Fortran object scipy/stats/_mvn.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__mvn-f2pywrappers.f.o
544.5       [800/1620] Linking target scipy/stats/_statlib.cpython-310-x86_64-linux-gnu.so
544.5       [801/1620] Compiling C object scipy/stats/_mvn.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__mvnmodule.c.o
544.5       [802/1620] Compiling C++ object scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/biasedurn_stoc3.cpp.o
544.5       [803/1620] Compiling Fortran object scipy/stats/_mvn.cpython-310-x86_64-linux-gnu.so.p/mvndst.f.o
544.5       [804/1620] Linking target scipy/stats/_mvn.cpython-310-x86_64-linux-gnu.so
544.5       [805/1620] Compiling C object scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__arpackmodule.c.o
544.5       [806/1620] Generating scipy/stats/_stats_pythran with a custom command
544.5       FAILED: scipy/stats/_stats_pythran.cpp
544.5       /tmp/pip-build-env-qxoydj4o/overlay/bin/pythran -E ../../scipy/stats/_stats_pythran.py -o scipy/stats/_stats_pythran.cpp
544.5       Traceback (most recent call last):
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/bin/pythran", line 8, in <module>
544.5           sys.exit(run())
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/run.py", line 180, in run
544.5           pythran.compile_pythranfile(args.input_file,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 481, in compile_pythranfile
544.5           output_file = compile_pythrancode(module_name, fd.read(),
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 399, in compile_pythrancode
544.5           module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 142, in generate_cxx
544.5           pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 109, in front_middle_end
544.5           refine(pm, ir, optimizations, report_times)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/middlend.py", line 57, in refine
544.5           pm.apply(FalsePolymorphism, node, run_times)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 243, in apply
544.5           ret=a.apply(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 200, in apply
544.5           new_node = self.run(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 189, in run
544.5           n = super(Transformation, self).run(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 97, in run
544.5           return self.visit(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
544.5           return super(ContextManager, self).visit(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 418, in visit
544.5           return visitor(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 494, in generic_visit
544.5           value = self.visit(value)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
544.5           return super(ContextManager, self).visit(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 418, in visit
544.5           return visitor(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/transformations/false_polymorphism.py", line 55, in visit_FunctionDef
544.5           if curr.name() != def_.name():
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/beniget/beniget.py", line 112, in name
544.5           elif isinstance(self.node, (ast.MatchStar, ast.MatchAs)):
544.5       AttributeError: module 'gast' has no attribute 'MatchStar'
544.5       [807/1620] Linking target scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-310-x86_64-linux-gnu.so
544.5       [808/1620] Compiling C++ object scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/biasedurn_wnchyppr.cpp.o
544.5       [809/1620] Generating 'scipy/stats/_biasedurn.cpython-310-x86_64-linux-gnu.so.p/_biasedurn.cpp'
544.5       [810/1620] Generating 'scipy/stats/_boost/binom_ufunc.cpython-310-x86_64-linux-gnu.so.p/binom_ufunc.cpp'
544.5       [811/1620] Generating 'scipy/stats/_boost/beta_ufunc.cpython-310-x86_64-linux-gnu.so.p/beta_ufunc.cpp'
544.5       [812/1620] Generating 'scipy/stats/_qmc_cy.cpython-310-x86_64-linux-gnu.so.p/_qmc_cy.cpp'
544.5       [813/1620] Generating 'scipy/stats/_boost/hypergeom_ufunc.cpython-310-x86_64-linux-gnu.so.p/hypergeom_ufunc.cpp'
544.5       [814/1620] Generating 'scipy/stats/_sobol.cpython-310-x86_64-linux-gnu.so.p/_sobol.c'
544.5       [815/1620] Generating 'scipy/stats/_stats.cpython-310-x86_64-linux-gnu.so.p/_stats.c'
544.5       [816/1620] Compiling C object scipy/special/cython_special.cpython-310-x86_64-linux-gnu.so.p/meson-generated_cython_special.c.o
544.5       [817/1620] Compiling C object scipy/linalg/_flapack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__flapackmodule.c.o
544.5       [818/1620] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cpython-310-x86_64-linux-gnu.so.p/csr.cxx.o
544.5       [819/1620] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cpython-310-x86_64-linux-gnu.so.p/bsr.cxx.o
544.5       ninja: build stopped: subcommand failed.
544.5       INFO: autodetecting backend as ninja
544.5       INFO: calculating backend command to run: /tmp/pip-build-env-qxoydj4o/normal/bin/ninja
544.5       + meson setup --prefix=/usr/local /tmp/pip-install-7ze1o55k/scipy_6548218fcc6e46b5b47242e1b9d226d4 /tmp/pip-install-7ze1o55k/scipy_6548218fcc6e46b5b47242e1b9d226d4/.mesonpy-du4iuxkl/build --native-file=/tmp/pip-install-7ze1o55k/scipy_6548218fcc6e46b5b47242e1b9d226d4/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
544.5       + meson compile
544.5       Traceback (most recent call last):
544.5         File "/app/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
544.5           main()
544.5         File "/app/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
544.5           json_out['return_val'] = hook(**hook_input['kwargs'])
544.5         File "/app/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
544.5           whl_basename = backend.build_wheel(metadata_directory, config_settings)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 1061, in build_wheel
544.5           return project.wheel(out).name
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 920, in wheel
544.5           wheel = self._wheel_builder.build(self._build_dir)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 502, in build
544.5           self._project.build()  # ensure project is built
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 737, in build
544.5           self._meson('compile', *self._meson_args['compile'],)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 657, in _meson
544.5           return self._proc('meson', *args)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 652, in _proc
544.5           subprocess.check_call(list(args), env=self._env)
544.5         File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
544.5           raise CalledProcessError(retcode, cmd)
544.5       subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
544.5       [end of output]
544.5
544.5   note: This error originates from a subprocess, and is likely not a problem with pip.
544.6 error: metadata-generation-failed
544.6
544.6 × Encountered error while generating package metadata.
544.6 ╰─> See above for output.
544.6
544.6 note: This is an issue with the package mentioned above, not pip.
544.6 hint: See above for details.
```
------

On 06/27/2024 when I generated the container it worked correctly, but on the day without changing the dockerfile 06/28/2024 it stopped working, simply using the docker-compose build command to mount my images, this container that had nothing different started to assemble and gave this error message, I couldn't figure out what it was.

Would anyone be able to help me with this problem? What's worse is that I can't just update the scipy version

**Comment by lucascolley** [comment]
Here is the relevant section of the traceback:

```
544.5.    [806/1620] Generating scipy/stats/_stats_pythran with a custom command
544.5       FAILED: scipy/stats/_stats_pythran.cpp
544.5       /tmp/pip-build-env-qxoydj4o/overlay/bin/pythran -E ../../scipy/stats/_stats_pythran.py -o scipy/stats/_stats_pythran.cpp
544.5       Traceback (most recent call last):
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/bin/pythran", line 8, in <module>
544.5           sys.exit(run())
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/run.py", line 180, in run
544.5           pythran.compile_pythranfile(args.input_file,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 481, in compile_pythranfile
544.5           output_file = compile_pythrancode(module_name, fd.read(),
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 399, in compile_pythrancode
544.5           module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 142, in generate_cxx
544.5           pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/toolchain.py", line 109, in front_middle_end
544.5           refine(pm, ir, optimizations, report_times)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/middlend.py", line 57, in refine
544.5           pm.apply(FalsePolymorphism, node, run_times)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 243, in apply
544.5           ret=a.apply(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 200, in apply
544.5           new_node = self.run(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 189, in run
544.5           n = super(Transformation, self).run(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 97, in run
544.5           return self.visit(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
544.5           return super(ContextManager, self).visit(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 418, in visit
544.5           return visitor(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 494, in generic_visit
544.5           value = self.visit(value)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/passmanager.py", line 79, in visit
544.5           return super(ContextManager, self).visit(node)
544.5         File "/usr/local/lib/python3.10/ast.py", line 418, in visit
544.5           return visitor(node)
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/pythran/transformations/false_polymorphism.py", line 55, in visit_FunctionDef
544.5           if curr.name() != def_.name():
544.5         File "/tmp/pip-build-env-qxoydj4o/overlay/lib/python3.10/site-packages/beniget/beniget.py", line 112, in name
544.5           elif isinstance(self.node, (ast.MatchStar, ast.MatchAs)):
544.5       AttributeError: module 'gast' has no attribute 'MatchStar'
```

**Comment by lucascolley** [comment]
What is your Pythran version?

**Comment by andyfaff** [comment]
pythran has dependencies on the gast and beniget packages. They both had a release on 28 th June, which is the day that your workflow stopped working. I suggest you try rolling back to an older version of gast/beniget to see if that works.

@serge-sans-paille, it looks like there's an issue in gast or beniget here.

**Comment by rgommers** [comment]
This isn't quite a valid report I think. For SciPy 1.10.x we require Pythran 0.12.x: https://github.com/scipy/scipy/blob/7f2ac6927d460c03bdbaff99e7acd6a596296101/pyproject.toml#L18C6-L18C31

And Pythran 0.12.2 depends on gast<=0.5.3: https://github.com/serge-sans-paille/pythran/blob/0.12.2/requirements.txt#L2. So a new `gast` release breaking something in your build setup here means somehow something is going wrong with build isolation, or you manually installed a different `pythran` version.

Also, please always use the latest patch release for any feature release - so SciPy 1.10.1 not 1.10.0 (not sure it'll make a difference here though).

**Comment by rgommers** [comment]
If you use `pip` with `-vvv` it'll show exactly what versions of `pythran` and `gast` are downloaded.

**Comment by Xophmeister** [comment]
I ran into the same issue. I managed to get SciPy 1.10.1 to build and install by applying this patch:

```patch
--- scipy/pyproject.toml
+++ patched/pyproject.toml
@@ -15,7 +15,10 @@ requires = [
     # conservatively avoid issues from
     # https://github.com/pybind/pybind11/issues/4420
     "pybind11==2.10.1",
-    "pythran>=0.12.0,<0.13.0",
+    "pyproject_metadata==0.8.1",
+    "gast==0.5.0",
+    "beniget==0.4.0",
+    "pythran==0.12.1",
     # `wheel` is needed for non-isolated builds, given that `meson-python`
     # doesn't list it as a runtime requirement (at least in 0.5.0)
     "wheel<0.39.0",
```

**Comment by andyfaff** [comment]
I think we can close this. v1.10 is quite old (we won't be making patches for it any more). musl wheels are now being published as well.
