### ISSUE TITLE
BUG: ARPACK error -9: Starting vector is zero when calling scipy.sparse.linalg.svds on zeros

### ISSUE THREAD

**Issue by ogrisel** [scipy/scipy#21137]
### Describe your issue.

The scikit-learn nightly build CI has found a recent regression:

- https://github.com/scikit-learn/scikit-learn/pull/29428

The reproducer below fails on recent nightly builds of scipy while it use to output the following the last stable release of scipy:

```
scipy version: 1.14.0
[[1.]
 [0.]]
[0.]
[[-0.47655702 -0.87914356]]
```

### Reproducing Code Example

```python
import numpy as np
import scipy
import scipy.sparse as sp

print(f"scipy version: {scipy.__version__}")

for out in sp.linalg.svds(np.zeros((2, 2)), k=1):
    print(out)
```

### Error message

```shell
scipy version: 
Traceback (most recent call last):
  File "/Users/ogrisel/tmp/repro_arpack.py", line 7, in <module>
    for out in sp.linalg.svds(np.zeros((2, 2)), k=1):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 515, in svds
    _, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 1701, in eigsh
    params.iterate()
  File "/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py", line 574, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg._eigen.arpack.arpack.ArpackError: ARPACK error -9: Starting vector is zero.
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+1098.a2c613f 2.1.0.dev0+git20240706.f76def3 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
/Users/ogrisel/miniforge3/envs/scipy-dev/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "13.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../../../../private/var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/pip-build-env-olf25eqk/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.13.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/cibw-run-tcdwbs37/cp312-macosx_arm64/build/venv/bin/python",
    "version": "3.12"
  }
}
```

**Comment by ilayn** [comment]
Thanks @ogrisel. Yes this one is due to the newer version of ARPACK that it does not work with identical zero operators anymore. See ARPACK FAQ  number 2 https://github.com/opencollab/arpack-ng/?tab=readme-ov-file#faq

We are rewriting ARPACK in Python and will address this separately during the rewrite. Until then, we decided to accept this regression.

**Comment by lucascolley** [comment]
> Current prospective plan is to make it to v1.15 so that this is a temporary regression without releasing this into the wild.

@ilayn how are we looking on this?
