### ISSUE TITLE
logm and expm throw errors on NVIDIA Jetson

### ISSUE THREAD

**Issue by eufrizz** [scipy/scipy#21188]
### Describe your issue.

script.lingalg `logm` and `expm` do not work on NVIDIA Jetson AGX Orin. No issues on M2 MacBook.

### Reproducing Code Example

```python
from scipy.linalg import logm, expm
import numpy as np

#1
logm(np.random.rand(4, 4))

#2
logm(np.diag([1, 1]))

#3
expm(np.random.rand(4, 4))

#4 - this one works
expm(np.diag([1, 1]))
```

### Error message

```shell
#1 logm(np.random.rand(4, 4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 203, in logm
    F = scipy.linalg._matfuncs_inv_ssq._logm(A)
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs_inv_ssq.py", line 875, in _logm
    if not np.array_equal(T, np.triu(T)):
TypeError: no implementation found for 'numpy.array_equal' on types that implement __array_function__: [<class 'numpy.ndarray'>, <class 'numpy.ndarray'>]


#2 logm(np.diag([1, 1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 203, in logm
    F = scipy.linalg._matfuncs_inv_ssq._logm(A)
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs_inv_ssq.py", line 871, in _logm
    return _logm_triu(A)
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs_inv_ssq.py", line 784, in _logm_triu
    nodes, weights = scipy.special.p_roots(m)
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/special/_orthogonal.py", line 2452, in roots_legendre
    return _gen_roots_and_weights(m, mu0, an_func, bn_func, f, df, True, mu)
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/special/_orthogonal.py", line 189, in _gen_roots_and_weights
    log_fm = np.log(np.abs(fm))
RecursionError: maximum recursion depth exceeded while calling a Python object


#3 expm(np.random.rand(4, 4))
Traceback (most recent call last):
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/numpy/_core/arrayprint.py", line 34, in <module>
    from . import numerictypes as _nt
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/numpy/_core/numerictypes.py", line 102, in <module>
    from ._type_aliases import (
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/numpy/_core/_type_aliases.py", line 38, in <module>
    allTypes[_abstract_type_name] = getattr(ma, _abstract_type_name)
AttributeError: module 'numpy.core.multiarray' has no attribute 'number'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 326, in expm
    m, s = pick_pade_structure(Am)
  File "scipy/linalg/_matfuncs_expm.pyx", line 128, in scipy.linalg._matfuncs_expm.pick_pade_structure
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/numpy/core/_internal.py", line 855, in array_ufunc_errmsg_formatter
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "/media/ssd/eugene/robotic_manipulation/lerobot_venv/lib/python3.10/site-packages/numpy/core/_internal.py", line 855, in <listcomp>
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
RuntimeError: Unable to configure default ndarray.__repr__
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= NEOVERSEN1 MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= NEOVERSEN1 MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-zk6_f8_r/overlay/lib/python3.10/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: linux
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by nickodell** [comment]
Hi, can you try the latest SciPy stable, 1.14.0?

**Comment by rgommers** [comment]
This is odd, it's not a SciPy problem, but a NumPy one. It's an aarch64 CPU so `numpy` is expected to work. How did you install `numpy`? And can you please run the numpy test suite with `python -c import numpy; numpy.test()` to get a better sense of what is broken?

**Comment by eufrizz** [comment]
Scipy 1.14.0 had the same issue.
Thanks for identifying it as a numpy issue, reinstalled numpy with pip and issue is solved.
Not sure what happened but somehow numpy 1.26.4 and 2.0.0 were both installed/conflicting (the pip installation gave `Found existing installation: numpy 2.0.0`, whilst clearly the version imported was 1.26.4).
