### ISSUE TITLE
BUG: optimize: Hessian update strategy fails on nested minimize functions when using `trust-constr`

### ISSUE THREAD

**Issue by CarrascoCesar** [scipy/scipy#21193]
### Describe your issue.

I have the need to have two nested minimizations.  That is the objective function itself requires the use of a minimization algorithm. I was trying to use the "trust-constr" method in both minimizations but ran into the issue that the hessian update throws an error.  If I switch to the "SLSQP" method for one of the minimizations then the error does not occur.  There appears to be an issue with "contamination"  across the two minimizations.   The error occurs in the "_hessian_update_strategy.py" when attempting wMw = Mw.dot(w) because Mw and w do not have the same shape.  One has shape (2,) and the other (4,) which match the size of the two minimizations problems.

The code I am attaching is for a very unrealistic/silly example just to show the issue.  My actual code is much more complex and would benefit from some of the capabilities of the "trust-constr" method.

### Reproducing Code Example

```python
import numpy as np
from scipy import optimize


def hyp(u, abcd):
    u1, u2 = u
    a, b, c, d = abcd

    return 10.0 + (((u1 - a) ** 2) / c**2 - (u2 - b) ** 2 / d**2)


def of(u):
    d = np.sum(u**2)
    gd = 2.0 * u
    return d, gd


def of_hess(u):
    return 2.0 * np.eye(np.size(u))


def beta(abcd):
    lsf = lambda u: hyp(u, abcd)

    method = "trust-constr"  # "trust-constr", "SLSQP"
    if method == "trust-constr":
        cons = optimize.NonlinearConstraint(lsf, 0, 0)  # , jac=glsf, hess=hlsf)
    else:
        cons = {"type": "eq", "fun": lsf}

    u0 = [0.1, 0.1]
    res = optimize.minimize(
        of,
        u0,
        jac=True,
        hess=of_hess,
        method=method,
        constraints=cons,
    )

    return res.fun


def cd_contraint(abcd):
    a, b, c, d = abcd
    f = 16 - (a**2 + b**2) / (c**2 + d**2)

    return f


method = "trust-constr"  # "trust-constr", "SLSQP"
if method == "trust-constr":
    abcd_cons = optimize.NonlinearConstraint(cd_contraint, 0, 0)
else:
    abcd_cons = {"type": "eq", "fun": cd_contraint}

abc0 = [4.0, 4.0, 2.0, 3.0]
res = optimize.minimize(
    beta,
    abc0,
    method=method,
    constraints=abcd_cons,
)

print(res)
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/Carrasco/Documents/UTEP/ReliabilityExamples/test_minimize.py", line 58, in <module>
    res = optimize.minimize(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_minimize.py", line 746, in minimize
    res = _minimize_trustregion_constr(fun, x0, args, jac, hess, hessp,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 519, in _minimize_trustregion_constr
    _, result = equality_constrained_sqp(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_trustregion_constr/equality_constrained_sqp.py", line 161, in equality_constrained_sqp
    f_next, b_next = fun_and_constr(x_next)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 511, in fun_and_constr
    c_eq, _ = canonical.fun(x)
              ^^^^^^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_trustregion_constr/canonical_constraint.py", line 166, in fun
    return cfun.fun(x) - value, empty_fun
           ^^^^^^^^^^^
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 601, in fun
    self._update_x(x)
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 583, in _update_x
    self._update_x_impl(x)
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 565, in update_x
    self._update_hess()
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 597, in _update_hess
    self._update_hess_impl()
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 551, in update_hess
    self.H.update(delta_x, delta_g)
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_hessian_update_strategy.py", line 242, in update
    self._update_implementation(delta_x, delta_grad)
  File "/Users/Carrasco/miniconda3/envs/rel312/lib/python3.12/site-packages/scipy/optimize/_hessian_update_strategy.py", line 386, in _update_implementation
    wMw = Mw.dot(w)
          ^^^^^^^^^
ValueError: shapes (2,) and (4,) not aligned: 2 (dim 0) != 4 (dim 0)
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0 2.0.0 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/Carrasco/miniconda3/envs/rel312/include
    lib directory: /Users/Carrasco/miniconda3/envs/rel312/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /Users/Carrasco/miniconda3/envs/rel312/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/Carrasco/miniconda3/envs/rel312/include
    lib directory: /Users/Carrasco/miniconda3/envs/rel312/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /Users/Carrasco/miniconda3/envs/rel312/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /Users/Carrasco/miniconda3/envs/rel312/include
    name: pybind11
    version: 2.13.1
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/Carrasco/miniconda3/envs/rel312/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/Carrasco/miniconda3/envs/rel312/lib,
      -L/Users/Carrasco/miniconda3/envs/rel312/lib, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -O2, -pipe, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    name: clang
    version: 16.0.6
  c++:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++,
      -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/Carrasco/miniconda3/envs/rel312/lib,
      -L/Users/Carrasco/miniconda3/envs/rel312/lib, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden, -fmessage-length=0,
      -isystem, /Users/Carrasco/miniconda3/envs/rel312/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -mmacosx-version-min=11.0, -mmacosx-version-min=11.0
    name: clang
    version: 16.0.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe,
      -isystem, /Users/Carrasco/miniconda3/envs/rel312/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix
    commands: /Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/_build_env/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    linker args: -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/Carrasco/miniconda3/envs/rel312/lib,
      -L/Users/Carrasco/miniconda3/envs/rel312/lib, -march=armv8.3-a, -ftree-vectorize,
      -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /Users/Carrasco/miniconda3/envs/rel312/include,
      -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1720323036805/work=/usr/local/src/conda/scipy-split-1.14.0,
      -fdebug-prefix-map=/Users/Carrasco/miniconda3/envs/rel312=/usr/local/src/conda-prefix
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../_build_env/venv/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: true
  host:
    cpu: arm64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/Carrasco/miniconda3/envs/rel312/bin/python
  version: '3.12'
```

**Comment by nickodell** [comment]
This is a really strange one. I experimented with the reproducer to see if I could reduce it to a more minimal example, to more clearly demonstrate the bug. I found the following:

* First and second order derivative information is not required to trigger the bug.
* Calling the minimizer inside the objective function is necessary to trigger the issue. However, it is not required to actually use the result from the minimizer at all.
* Both problems must be constrained, and they must be constrained with a different number of variables.
* This is not a recent regression - I tried this in 1.12.0, 1.13.0, and 1.14.0 and got similar results.

```
import numpy as np
from scipy import optimize


def of(u):
    d = np.sum(u**2)
    return d


def beta(abcd):
    print("In beta")
    _ = optimize.minimize(
        of,
        [0, 0],
        method="trust-constr",
        constraints=optimize.NonlinearConstraint(cd_contraint, 0, 0),
    )
    return of(abcd)


def cd_contraint(abcd):
    a = abcd[0]
    f = 1 - (a**2)

    return f


abc0 = [0, 0, 0]
res = optimize.minimize(
    beta,
    abc0,
    method="trust-constr",
    constraints=optimize.NonlinearConstraint(cd_contraint, 0, 0),
)

print(res)
```

Both of the problems are well formed: they have minimums at [1, 0, 0], and [1, 0], respectively. Both problems can be solved separately, or solved one after another. But they can't be solved at the same time.

**Comment by CarrascoCesar** [comment]
@nickodell thanks for simplifying the code and the analysis of the bug.  This one is for someone way more qualified that I since I have just over a year of experience programming in Python.  Still, will give it a try if somebody can point me to the possible source of the issue.  Thanks again!!

**Comment by nickodell** [comment]
Okay, I think I have a theory about why this happens.

One BFGS object is being shared between two different trust-constr optimization processes. I couldn't initially figure out where this object was coming from, but it's getting created during the creation of the NonlinearConstraint, right here:

```
    def __init__(self, fun, lb, ub, jac='2-point', hess=BFGS(),
                 keep_feasible=False, finite_diff_rel_step=None,
                 finite_diff_jac_sparsity=None):
```

Here's the odd thing about this code: Because this is a default, the BFGS object is created when the function is defined, not when the function is called. If two NonlinearConstraint objects are created, they will share a single BFGS object for the purpose of computing a Hessian.

```
import numpy as np
from scipy import optimize


def constraint_a(x):
    return x[0]


def constraint_b(x):
    return -x[0]


constraint1 = optimize.NonlinearConstraint(constraint_a, 0, 0)
constraint2 = optimize.NonlinearConstraint(constraint_b, 0, 0)
print(constraint1.hess is constraint2.hess)  # prints True
```

Given that the BFGS object is stateful (it has to be in order to efficiently compute the Hessian) it seems odd to share it between multiple different optimization processes.

Here's a patch that seems to fix the issue:

```diff
diff --git a/scipy/optimize/_constraints.py b/scipy/optimize/_constraints.py
index 04103d734..1bae893e2 100644
--- a/scipy/optimize/_constraints.py
+++ b/scipy/optimize/_constraints.py
@@ -105,9 +105,11 @@ class NonlinearConstraint:
     >>> nlc = NonlinearConstraint(con, -np.inf, 1.9)
 
     """
-    def __init__(self, fun, lb, ub, jac='2-point', hess=BFGS(),
+    def __init__(self, fun, lb, ub, jac='2-point', hess=None,
                  keep_feasible=False, finite_diff_rel_step=None,
                  finite_diff_jac_sparsity=None):
+        if hess is None:
+            hess = BFGS()
         self.fun = fun
         self.lb = lb
         self.ub = ub
```

PR incoming.

**Comment by CarrascoCesar** [comment]
@nickodell thanks for coming up with a solution in such a short time.  I can confirm that this patch works in my more complex code.  Thanks again!
