### ISSUE TITLE
BUG: SciPy functions raise an error given lists of extreme integers

### ISSUE THREAD

**Issue by michaelpradel** [scipy/scipy#21205]
### Describe your issue.

The example below leads to a `TypeError` since version 1.13.0 of scipy. Up to version 1.12.0, the output was `ShapiroResult(statistic=0.9446643968771752, pvalue=0.6829615285403758)`, which (I believe) is the expected result.

As a first step toward debugging it: The change in behavior has been introduced by https://github.com/scipy/scipy/pull/19680

### Reproducing Code Example

```python
from scipy import stats

data = [10**20, -10**20, 10**30, -10**30] # Extreme values
r = stats.shapiro(data)
print(r)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scipy/scipy/stats/_axis_nan_policy.py", line 544, in axis_nan_policy_wrapper
    contains_nan = [_contains_nan(sample, nan_policy)[0]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scipy/scipy/_lib/_util.py", line 745, in _contains_nan
    if np.issubdtype(type(el), np.number) and np.isnan(el):
                                              ^^^^^^^^^^^^
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+1043.bbe993d 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /root/conda/envs/scipy-dev/include
    lib directory: /root/conda/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 PRESCOTT MAX_THREADS=128
    pc file directory: /root/conda/envs/scipy-dev/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /root/conda/envs/scipy-dev/include
    lib directory: /root/conda/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 PRESCOTT MAX_THREADS=128
    pc file directory: /root/conda/envs/scipy-dev/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: pkgconfig
    include directory: /root/conda/envs/scipy-dev/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include,
      -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include,
      -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  c++:
    args: -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell,
      -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections,
      -pipe, -isystem, /root/conda/envs/scipy-dev/include, -DNDEBUG, -D_FORTIFY_SOURCE=2,
      -O2, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -fvisibility-inlines-hidden, -fmessage-length=0, -march=nocona, -mtune=haswell,
      -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections,
      -pipe, -isystem, /root/conda/envs/scipy-dev/include, -DNDEBUG, -D_FORTIFY_SOURCE=2,
      -O2, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include
    commands: /root/conda/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    linker args: -Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now,
      -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,--allow-shlib-undefined, -Wl,-rpath,/root/conda/envs/scipy-dev/lib,
      -Wl,-rpath-link,/root/conda/envs/scipy-dev/lib, -L/root/conda/envs/scipy-dev/lib,
      -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /root/conda/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../root/conda/envs/scipy-dev/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /root/conda/envs/scipy-dev/bin/python3.12
  version: '3.12'
```

**Comment by mdhaber** [comment]
`np.asarray([10**20, -10**20, 10**30, -10**30])` results in an object array. I suspect this happens in a few other functions.

**Comment by fancidev** [comment]
One possibility could be to cast the input to float64 before further processing. This may be appropriate for special functions, which always work with floating-point numbers anyway.  (And this could also be done by the ufunc machinery so that no code duplication is needed.)

For stats such casting would disallow certain usage with non-floating input, e.g. it appears some users run a statistical test using input data with unit attached and expect the output to have unit attached. It seems to me impossible to ensure type safety and support duck typing at the same time.

**Comment by mdhaber** [comment]
Thanks @michaelpradel, but since this behavior is not necessarily wrong (not all functions are supposed to be defined for object arrays, and lists of very large `int`s are converted to object arrays), I don't think we can do much here unless NumPy sets a stronger precedent.
```python3
import numpy as np
x = [10**20]
np.sin(x)
# TypeError: loop of ufunc does not support argument 0 of type int which has no callable sin method
```
If they change the behavior for ufuncs, that would carry over to SciPy in many cases, and then it might be worth taking a look at the other cases. In the meantime, users can very easily resolve the problem by adding a period after any one of the numbers if this should occur in practice and if they intend for the argument to be treated as a floating point dtype. All things considered, this is probably a bit better than SciPy preemptively changing every function to which this issue applies.
