### ISSUE TITLE
DOC: doc build failing in CI

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#21212]
eg. #21068
```
/home/circleci/repo/doc/source/tutorial/stats/hypothesis_bartlett.md: Executing notebook using local CWD [mystnb]
/home/circleci/repo/doc/source/tutorial/stats/hypothesis_bartlett.md: Executed notebook in 9.16 seconds [mystnb]

Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 318, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 425, in read
    self._read_serial(docnames)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 477, in _read_serial
    self.read_doc(docname)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 536, in read_doc
    publisher.publish()
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_nb/sphinx_.py", line 157, in parse
    mdit_renderer.render(mdit_tokens, mdit_parser.options, mdit_env)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mdit_to_docutils/base.py", line 243, in render
    self._render_tokens(list(tokens))
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mdit_to_docutils/base.py", line 222, in _render_tokens
    self.rules[f"render_{child.type}"](child)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_nb/core/render.py", line 117, in render_nb_cell_markdown
    self.render_children(token)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mdit_to_docutils/base.py", line 396, in render_children
    self.rules[f"render_{child.type}"](child)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mdit_to_docutils/base.py", line 752, in render_fence
    return self.render_restructuredtext(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mdit_to_docutils/base.py", line 1680, in render_restructuredtext
    MockRSTParser().parse(pseudosource, newdoc)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/myst_parser/mocking.py", line 552, in parse
    super().parse(inputstring, document)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/__init__.py", line 184, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/jupyterlite_sphinx/jupyterlite_sphinx.py", line 368, in run
    shutil.copy(notebook, notebooks_dir)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/circleci/repo/doc/source/_contents/hypothesis_bartlett.ipynb' and PosixPath('/home/circleci/repo/doc/source/_contents/hypothesis_bartlett.ipynb') are the same file

Exception occurred:
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/circleci/repo/doc/source/_contents/hypothesis_bartlett.ipynb' and PosixPath('/home/circleci/repo/doc/source/_contents/hypothesis_bartlett.ipynb') are the same file
The full traceback has been saved in /tmp/sphinx-err-0uustznf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:114: html-build] Error 2
Skipping build

Exited with code exit status 1
```

**Comment by tylerjereddy** [comment]
if you do the release on PyPI and confirm the fix, just close my cognate PR pinning it of course.
