### ISSUE TITLE
`dev.py build --release` complains about default CFLAGS

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#21269]
### Describe your issue.

To run `dev.py build --release`, I seem to have to manually edit the CFLAGS environment variable to remove the `-O2`. The env variable was set automatically by---am guessing here---conda/mamba:

```
$ git clean -xdf
$ python dev.py build --release
Task Error - build => PythonAction Error
╭─────────────────────────────────────── build ────────────────────────────────────────╮
│ Traceback (most recent call last):                                                   │
│   File                                                                               │
│ "/home/ev-br/.conda/envs/scipy-dev/lib/python3.11/site-packages/doit/action.py",     │
│ line 461, in execute                                                                 │
│     returned_value = self.py_callable(*self.args, **kwargs)                          │
│                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          │
│   File "/home/ev-br/repos/scipy/dev.py", line 668, in run                            │
│     env = cls.setup_build(dirs, args)                                                │
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                │
│   File "/home/ev-br/repos/scipy/dev.py", line 507, in setup_build                    │
│     raise ValueError(f"A {buildtype} build isn't possible, "                         │
│ ValueError: A release build isn't possible, because CFLAGS contains `-O2`.Please     │
│ also check CXXFLAGS and FFLAGS.                                                      │
│                                                                                      │
╰───────────────────────────────── PythonAction Error ─────────────────────────────────╯
(scipy-dev) ev-br@qgpu3:~/repos/scipy$ echo $CFLAGS
-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ev-br/.conda/envs/scipy-dev/include
$ mamba deactivate
ev-br@qgpu3:~/repos/scipy$ echo $CFLAGS
<empty>
```

The `scipy-dev` environment is generated with the unmodified `environment.yml` on a bog-standard linux system.

Also of note that both `CXXFLAGS` and `FFLAGS` contain -O2, and having them does not interfere with `dev.py build --release`.

### Reproducing Code Example

```python
.
```

### Error message

```shell
.
```

### SciPy/NumPy/Python version and system information

```shell
main
```

**Comment by tylerjereddy** [comment]
I think we did this intentionally at gh-21171, and I'm pretty sure I agreed with Ralf's approach there re: "pure" debug and release builds. If anything I'd be inclined to potentially even check the other two lang flags you mention and be strict on those too, though that is getting a bit complicated and perhaps the machinery did its job by catching an attempt to build a "pure release" build when the flags were not "pure."

Since the default `dev.py` build mode should work just fine, what exactly is the behavior you are expecting here?

**Comment by rgommers** [comment]
> The `scipy-dev` environment is generated with the unmodified `environment.yml` on a bog-standard linux system.

Yes, this is a major UX problem in conda-forge. That is exactly why the warning is there. If you want a release or debug build in a conda env with conda compilers, you _have to_ unset or modify CFLAGS & co.

Upstream issue is https://github.com/conda-forge/conda-forge.github.io/issues/2002.

We can either close this issue, or you can propose a tweak to the error message that would have helped you.

**Comment by ev-br** [comment]
TBH I'm a bit surprised that `dev.py build --release` cannot unset the flags: a (possibly naive) expectation is that if I request the cetain build "kind", it will set up the build flags fully. As in
- `dev.py build` : rely on whatever default configuration is there
- `dev.py buld --{release,debug}`: set up the compile/link flags to get the "pure" build.

If that's not an option, what would be helpful is
- as Tyler said, fail on bad CXXFLAGS and FFLAGS, too. Currently, if I manually remove `-O2` from CFLAGS and keep CXXFLAGS intact, `dev.py buld --release` succeeds. Not sure if that means the build is someohw "impure"
- The error message could link to the upstream issue. As is, "if you're in a conda environment, see  conda-forge/conda-forge.github.io#2002"

**Comment by rgommers** [comment]
Unsetting environment variables in `dev.py` isn't an option, that's going to have bad side-effects in other ways. Environment variables are for use by users, for a host of different reasons. They're an override of whatever is set by the build itself, so a build should never try to modify them. 

> as Tyler said, fail on bad CXXFLAGS and FFLAGS, too

That's fine with me - it's just some extra boilerplate code.

> The error message could link to the upstream issue

I'd much prefer not to. Having random contributors ping on that issue isn't going to lead to useful dynamics. We should just make the error message clear enough.

**Comment by ev-br** [comment]
dev.py is gone, closing.
