### ISSUE TITLE
BUG: dtype changed for argument to `rv_discrete._pmf`

### ISSUE THREAD

**Issue by oscarbenjamin** [scipy/scipy#21272]
### Describe your issue.

This is coming from a test failure in the SymPy test suite in the job that uses the NumPy and SciPy nightly wheels:
https://github.com/sympy/sympy/actions/runs/10110311336/job/27960035596

The test subclasses `discrete_rv` and defines the `_pmf` method. Previously (in SciPy 1.14.0) the `_pmf` method was passed `float64` arguments. As of a few days ago with the nightly builds it instead receives `int64` arguments. This leads to a failure with:
```
  File "/home/oscar/current/active/sympy/t.py", line 6, in _pmf
    return (2/3)*3**(1 - i)
                 ~^^~~~~~~~
ValueError: Integers to negative integer powers are not allowed.
```

### Reproducing Code Example

```python
from scipy.stats import rv_discrete

class rv_exponential(rv_discrete):
    def _pmf(self, i):
        print(i.dtype)
        return (2/3)*3**(1 - i)

rv = rv_exponential(a=0.0, b=float('inf'))

print(rv.rvs())
```

### Error message

```shell
int64
Traceback (most recent call last):
  File "/home/oscar/current/active/sympy/t.py", line 10, in <module>
    print(rv.rvs())
          ^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3430, in rvs
    return super().rvs(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 1108, in rvs
    vals = self._rvs(*args, size=size, random_state=random_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 1034, in _rvs
    Y = self._ppf(U, *args)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 1049, in _ppf
    return self._ppfvec(q, *args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2470, in __call__
    return self._call_as_normal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2463, in _call_as_normal
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2553, in _vectorize_call
    outputs = ufunc(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3057, in _drv2_ppfsingle
    qb = self._cdf(b, *args)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3396, in _cdf
    return self._cdfvec(k, *args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2470, in __call__
    return self._call_as_normal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2463, in _call_as_normal
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 2553, in _vectorize_call
    outputs = ufunc(*inputs)
              ^^^^^^^^^^^^^^
  File "/home/oscar/.pyenv/versions/sympy-3.12.git/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py", line 3392, in _cdf_single
    return np.sum(self._pmf(m, *args), axis=0)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/oscar/current/active/sympy/t.py", line 6, in _pmf
    return (2/3)*3**(1 - i)
                 ~^^~~~~~~~
ValueError: Integers to negative integer powers are not allowed.
```

### SciPy/NumPy/Python version and system information

The code shown runs fine with current releases SciPy 1.14.0 and NumPy 2.0.1 and outputs:
```shell
$ python t.py 
float64
float64
float64
float64
float64
float64
float64
float64
0
```
It fails with the nightly wheels of SciPy and NumPy printing a single `int64` and then terminating with the error shown:
```shell
$ python t.py 
int64
Traceback (most recent call last):
...
  File "/home/oscar/current/active/sympy/t.py", line 6, in _pmf
    return (2/3)*3**(1 - i)
                 ~^^~~~~~~~
ValueError: Integers to negative integer powers are not allowed.
```

**Comment by lucascolley** [comment]
I can't immediately see a SciPy commit in the past few days that would have caused this. Maybe a NumPy thing? Could you try with SciPy nightly and released NumPy?

(Just a stab in the dark - maybe https://github.com/numpy/numpy/pull/26905 which landed yesterday?)

**Comment by oscarbenjamin** [comment]
> Could you try with SciPy nightly and released NumPy?

I didn't realise those would be compatible...

With released numpy and scipy nightly I don't see the problem.

With nightly numpy and released scipy I do see the problem.

So it looks like the change is something in numpy.

**Comment by oscarbenjamin** [comment]
I've opened a NumPy issue: https://github.com/numpy/numpy/issues/27054

**Comment by lucascolley** [comment]
great! tagged as `upstream bug` but perhaps some adjustments will be needed on our side

**Comment by oscarbenjamin** [comment]
I've bisected this in NumPy to https://github.com/numpy/numpy/commit/6c915672c772b4753641572add2d846cbd7f0d67

**Comment by oscarbenjamin** [comment]
It doesn't look like this is considered a bug in upstream (https://github.com/numpy/numpy/issues/27054#issuecomment-2254492933):

> I need to take a look what is going on in SciPy but I think SciPy relied on floor, ceil, and trunc output cast to float64 which IMO is incorrect, so I think it requires a fix on SciPy side perform explicit casting to float64.

**Comment by lucascolley** [comment]
In which case, it sounds like the problem lies here:

https://github.com/scipy/scipy/blob/2050d49e6b1fd512bd7eba35d3368bb5678bb7f2/scipy/stats/_distn_infrastructure.py#L3394-L3396

**Comment by oscarbenjamin** [comment]
Yes, that looks like it. It took me a moment to understand why `floor` is being used there but I see that the expectation is that `x` might not be integer valued but we can still define cdf for non-integer values for a discrete distribution.

Using `floor` suggests that the expectation was that `x` could be non-integer-valued but that `_cdfvec` might expect only integer values. I had wondered if the coercion of integer to float in `floor` was intended or not. 

It seems odd that the natural expectation in using `floor` is clearly to turn non-integer values into integer values but the effect in this case is that an array of integers is turned into an array of floats.
