### ISSUE TITLE
DOC: build fails with Sphinx 8

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#21323]
For example  https://app.circleci.com/pipelines/github/scipy/scipy/29177/workflows/132cc106-e5de-4d08-9b8a-f963bfdaea81/jobs/98457
```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/events.py", line 100, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/jupyterlite_sphinx/jupyterlite_sphinx.py", line 613, in _process_docstring_examples
    if source_path.endswith(".py"):
       ^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/util/_pathlib.py", line 96, in __getattr__
    warnings.warn(_MSG, RemovedInSphinx90Warning, stacklevel=2)
sphinx.deprecation.RemovedInSphinx90Warning: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/application.py", line 378, in build
    self.builder.build_update()
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 317, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 424, in read
    self._read_serial(docnames)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 476, in _read_serial
    self.read_doc(docname)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 535, in read_doc
    publisher.publish()
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/io.py", line 105, in read
    self.input = self.read_source(settings.env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/io.py", line 115, in read_source
    env.events.emit('source-read', env.docname, arg)
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/sphinx/events.py", line 111, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function _process_docstring_examples at 0x7fd7a79d9080> for event 'source-read' threw an exception (exception: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead.)

Extension error (jupyterlite_sphinx.jupyterlite_sphinx):
Handler <function _process_docstring_examples at 0x7fd7a79d9080> for event 'source-read' threw an exception (exception: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead.)
make: *** [Makefile:114: html-build] Error 2
Skipping build

Exited with code exit status 1
```

**Comment by WarrenWeckesser** [comment]
Something broke with the recently released Sphinx 8.0.2. The error message suggests the problem is in `jupyterlite_sphinx`.  The build still works with Sphinx 7.4.7.

**Comment by WarrenWeckesser** [comment]
It looks like `jupyterlite_sphinx` (https://github.com/jupyterlite/jupyterlite-sphinx/pull/199) and `myst_nb` (https://github.com/executablebooks/MyST-NB/issues/619) need updates to avoid deprecation warnings triggered by using Sphinx 8.0.

**Comment by rgommers** [comment]
This was taken care of in gh-21324, so closing.

**Comment by EwoutH** [comment]
Wait, the issue was mitigated with https://github.com/scipy/scipy/pull/21324, not resolved, right? Builds are still failing with Sphinx 8.

Shouldn't there be somewhere something open that this is the case?

**Comment by lucascolley** [comment]
gh-21482 (but maybe we want an issue too, or to reopen this and rename)

**Comment by agriyakhetarpal** [comment]
Yes, this issue could be renamed to "DOC: build failing in CI with Sphinx 8 / update to Sphinx 8" or similar. I'll keep an eye on when MyST-NB makes a release with executablebooks/MyST-NB#620 in it, and update gh-21482 as appropriate.

**Comment by bsipocz** [comment]
We have made a release of MyST-NB with a fix for this, could you please double check if it works for you now?

**Comment by agriyakhetarpal** [comment]
@bsipocz, thanks for the update. There's one more warning coming from MyST-NB that would need to be fixed, here's a link to workflow run logs from the PR above: https://app.circleci.com/jobs/github/scipy/scipy/105321. I'm happy to contribute a fix for this, but I can step back in case you wish to take it up yourself, please let me know!

**Comment by lucascolley** [comment]
@agriyakhetarpal @bsipocz are we any further along here?

**Comment by bsipocz** [comment]
I have a PR that needs review and merging and then a release, hopefully it will all get sorted next week.
