### ISSUE TITLE
BLD: Pythran build failing in CI

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#21418]
https://app.circleci.com/pipelines/github/scipy/scipy/29547/workflows/012fb38e-c9b6-4495-8a75-9ce3546ad62e/jobs/99701
```
[570/1280] Generating 'scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so.p/_stats_pythran.cpp'
FAILED: scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so.p/_stats_pythran.cpp 
/home/circleci/.pyenv/versions/3.11.9/bin/pythran -E ../scipy/stats/_stats_pythran.py -o scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so.p/_stats_pythran.cpp
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.11.9/bin/pythran", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pythran/run.py", line 190, in run
    pythran.compile_pythranfile(args.input_file,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pythran/__init__.py", line 127, in __getattr__
    import pythran.toolchain
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pythran/toolchain.py", line 11, in <module>
    from pythran.dist import PythranExtension, PythranBuildExt
  File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/pythran/dist.py", line 142, in <module>
    class PythranBuildExt(PythranBuildExtMixIn, LegacyBuildExt, metaclass=PythranBuildExtMeta):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
[571/1280] Generating 'scipy/stats/_levy_stable/levyst.cpython-311-x86_64-linux-gnu.so.p/levyst.c'
ninja: build stopped: subcommand failed.
```

**Comment by j-bowhay** [comment]
Oops duplicate of #21416
