### ISSUE TITLE
BUG: Canonicalization of `scipy.sparse.csr_array` seems broken

### ISSUE THREAD

**Issue by hameerabbasi** [scipy/scipy#21442]
### Describe your issue.

I am uploading a reproducer, with two NPZ files and a `repro.py` file to reproduce the issue.

I canonicalize the two CSR arrays with:

```
arr.sort_indices()
arr.prune()
arr.sum_duplicates()
```

Then; while their dense reprresentations are equal; the `(indices, indptr, data)` tuples don't compare as equal.

[repro.zip](https://github.com/user-attachments/files/16735417/repro.zip)

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse as sps


def npz_to_csr(f: str) -> sps.csr_array:
    npz = np.load(f)
    return sps.csr_array((npz["data"], npz["indices"], npz["indptr"]), shape=(10, 5))

def canonicalize(arr: sps.csr_array) -> sps.csr_array:
    arr.sort_indices()
    arr.prune()
    arr.sum_duplicates()
    return arr

if __name__ == "__main__":
    # These are in repro.zip
    csr1 = canonicalize(npz_to_csr('csr1.npz'))
    csr2 = canonicalize(npz_to_csr('csr2.npz'))

    np.testing.assert_array_equal(csr1.todense(), csr2.todense())  # Succeeds

    # Fails
    np.testing.assert_array_equal(csr1.indptr, csr2.indptr)
    np.testing.assert_array_equal(csr1.indices, csr2.indices)
    np.testing.assert_array_equal(csr1.data, csr2.data)
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/habbasi/Quansight/sparse/repro.py", line 22, in <module>
    np.testing.assert_array_equal(csr1.indptr, csr2.indptr)
  File "/Users/habbasi/miniforge3/envs/sparse/lib/python3.12/site-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/habbasi/miniforge3/envs/sparse/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1025, in assert_array_equal
    assert_array_compare(operator.__eq__, actual, desired, err_msg=err_msg,
  File "/Users/habbasi/miniforge3/envs/sparse/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/habbasi/miniforge3/envs/sparse/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 9 / 11 (81.8%)
Max absolute difference among violations: 3
Max relative difference among violations: 0.14285714
 ACTUAL: array([ 0,  3,  6, 10, 15, 18, 22, 26, 31, 35, 39])
 DESIRED: array([ 0,  3,  7, 11, 16, 19, 23, 27, 32, 37, 42])
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.1.0 sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-bjescfad/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-oogm4_8g/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by hameerabbasi** [comment]
cc @ivirshup @perimosocordiae

**Comment by perimosocordiae** [comment]
Sorry for the extreme delay here. One initial thought: it seems like we should call `sort_indices()` last, because the other operations may end up changing index order.

@dschult kindly offered to try running the reproducer. Please update here with your findings.

**Comment by dschult** [comment]
The short story is that you should use `arr.eliminate_zeros()` rather than `arr.prune()`.

The docs for the method `prune` says `Remove empty space after all non-zero elements.` Note that it doesn't remove zero entries in the middle of the non-zero entries.  You should use `eliminate_zeros` which has doc_string: `Remove zero entries from the array`. 

Your reproducer arrays have sorted indices and no duplicate indices. So the only non-canonical aspect is that `csr2 ` has an explicit zero stored in the sparse array. 

(Note that the `has_canonical_format` attribute does not consider explicit zeros as breaking canonical format. It only considers duplicate indexes and sorted indices.) 

Finally, the `sum_duplicates` method also calls `sort_indices` and `prune` (in case the resulting index arrays have had  any entries removed, leaving zeros at the end).  So you only need:

```python
def canonicalize(arr):
    arr.eliminate_zeros()
    arr.sum_duplicates()
    return arr  # technically not needed since the changes are made in-place
```

I'm going to close this Issue, but if you are still having trouble with it just post here and we'll open it again (or create a new one).
