### ISSUE TITLE
BUG: Invalid treatment of ellipsis in indexing of sparse matrices

### ISSUE THREAD

**Issue by janezd** [scipy/scipy#21615]
### Describe your issue.

`scipy.sparse._index.IndexMixin._validate_indices` computes an incorrect index if the first index is `...`.

This is a bug parallel to the one fixed here: https://github.com/scipy/scipy/commit/ada2bdb797b3e04d6b1f139971bca2612fd5bfce#diff-ce894467ef812afc70d0dfc5c29032d95eb09eaf975c24e69a3aea941cd10dcdR222

I suppose

```
            elif isintlike(idx):
                N = self._shape[index_ndim]
```

must also be changed to something like

```
            elif isintlike(idx):
                N = self._shape[index_ndim] if ellps_pos is None else self._shape[-1]
``` 

### Reproducing Code Example

```python
import scipy.sparse as sp
a = sp.csr_matrix([[1, 2, 3], [4, 5, 6]])
a[..., 2]
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/janez/o3edge/lib/python3.12/site-packages/scipy/sparse/_index.py", line 30, in __getitem__
    index, new_shape = self._validate_indices(key)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janez/o3edge/lib/python3.12/site-packages/scipy/sparse/_index.py", line 230, in _validate_indices
    raise IndexError(f'index ({idx}) out of range')
IndexError: index (2) out of range
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+git20240913.ecf3ff0 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY neoversen1 MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY neoversen1 MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-hzxpyi03/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: linux
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

**Comment by lucascolley** [comment]
cc @dschult @perimosocordiae

**Comment by dschult** [comment]
Thanks very much @janezd!
You've reported the bug and a reasonable fix.

I'll work on some more complete testing as well. :)  If you want to make a PR that'd be fine. Otherwise I'll do it.
