### ISSUE TITLE
BUG: Getting a number of errors with associated imports after updating scipy

### ISSUE THREAD

**Issue by cppt** [scipy/scipy#21650]
### Describe your issue.

Have recently updated scipy and am noticing a host of errors being thrown for related imports that seem to trace back to scipy.  Wonder if anyone can shed some light as to why/which version to revert to to avoid these.  

### Reproducing Code Example

```python
A couple examples:

All of these throw the below error:
```
 statsmodels.api as sm
import seaborn as sns
from scipy.signal import savgol_filter
```


The below works without issue however
`import scipy`


### Error message

```shell
import statsmodels.api as sm
Traceback (most recent call last):

  File "/tmp/ipykernel_386754/2479605915.py", line 1, in <module>
    import statsmodels.api as sm

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/api.py", line 76, in <module>
    from . import datasets, distributions, iolib, regression, robust, tools

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .empirical_distribution import (

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/empirical_distribution.py", line 5, in <module>
    from scipy.interpolate import interp1d

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 14, in <module>
    from . import _fitpack_py

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),

TypeError
```

### SciPy/NumPy/Python version and system information

```shell
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.13.1 1.26.3 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-buf8o3q2/overlay/lib/python3.9/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp39-cp39/bin/python
  version: '3.9'
```

**Comment by nickodell** [comment]
This is the same error message as #21546.

I see you're using SciPy 1.13.1. The latest version is 1.14.1. Does this error show up on the latest version of SciPy?

**Comment by lucascolley** [comment]
(closing as duplicate, please comment over there!)

**Comment by cppt** [comment]
@nickodell thanks.  

```
pip install --upgrade scipy==1.14.1
ERROR: Ignored the following yanked versions: 1.11.0
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement scipy==1.14.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for scipy==1.14.1
```

A little leary about attempting to update other packages further more without understanding the underlying cause.  One remedy yesterday, was downgrading numpy to 1.26.3
  

For reference, yesterday (before restarting Spyder), the error message was the below (attempting similar imports):

```
import statsmodels.api as sm
Traceback (most recent call last):

File "/tmp/ipykernel_284942/2479605915.py", line 1, in
import statsmodels.api as sm

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/api.py", line 78, in
from . import datasets, distributions, iolib, regression, robust, tools

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/init.py", line 7, in
from .discrete import (

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/discrete.py", line 36, in
genpoisson_p = genpoisson_p_gen(name='genpoisson_p',

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 3225, in init
super().init(seed)

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 643, in init
self._random_state = check_random_state(seed)

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/_lib/_util.py", line 265, in check_random_state
return np.random.mtrand._rand

AttributeError: module 'numpy.random' has no attribute 'mtrand'
```
