### ISSUE TITLE
BUG: Passing CuPy array to scipy.stats.mannwhitneyu throws a TypeError

### ISSUE THREAD

**Issue by dbolser** [scipy/scipy#21662]
### Describe your issue.

I may be wrong, but based on what I've read (and now looking at the code a bit) I /think/ I should be able to simply pass `cupy.ndarray`s to mannwhitneyu, however, I'm seeing an error.

I've tried to breakpoint the functions within scipy that are throwing the errors (where I can see code related to CuPy), however, for some reason, vscode isn't breaking and I keep getting 'error'd out' at the mannwhitneyu call in my code.

### Reproducing Code Example

```python
import cupy as cp
from scipy.stats import mannwhitneyu

def random_example():
    scores = cp.random.rand(100000)
    states = cp.random.choice(
        [True, False],
        p=[0.01, 0.99],  # Roughly 1% True, 99% False (on average)
        size=scores.shape,
    )

    return mannwhitneyu(scores[states], scores[~states], alternative="two-sided")
```

### Error message

```shell
Traceback (most recent call last):
  File "~/pwd/test_mann.py", line 198, in <module>
    main()
  File "~/pwd/test_mann.py", line 157, in main
    lovely_result = random_example()
                    ^^^^^^^^^^^^^^^^
  File "~/pwd/test_mann.py", line 153, in random_example
    return mannwhitneyu(scores[states], scores[~states], alternative="two-sided")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/pwd/.venv/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py", line 522, in axis_nan_policy_wrapper
    samples = _broadcast_arrays(samples, axis=axis)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/pwd/.venv/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py", line 48, in _broadcast_arrays
    arrays = [xp.asarray(arr) for arr in arrays]
              ^^^^^^^^^^^^^^^
  File "~/pwd/.venv/lib/python3.12/site-packages/scipy/_lib/array_api_compat/common/_aliases.py", line 353, in _asarray
    return xp.asarray(obj, dtype=dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 1481, in cupy._core.core._ndarray_base.__array__
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, cupy.__version__, sys.version_info); scipy.show_config()
1.14.1 2.1.1 13.3.0 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../tmp/pip-build-env-znxdftlb/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include",
      "lib directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64",
      "pc file directory": "/project"
    },
    "lapack": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include",
      "lib directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64",
      "pc file directory": "/project"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp312-cp312/bin/python",
    "version": "3.12"
  }
}
```

**Comment by lucascolley** [comment]
Support for alternative array types hasn't been added to `stats.mannwhitneyu` yet - see https://github.com/scipy/scipy/issues/20544.

(We know that we need better documentation for which functions have experimental support - we're still thinking about how to implement that!)

**Comment by dbolser** [comment]
These functions are held up by rankdata (possibly among other things), which is waiting for improved array-API support. See https://github.com/scipy/scipy/pull/20639.
