### ISSUE TITLE
BUG: optimize.shgo: not working with `jac=True`

### ISSUE THREAD

**Issue by mariofilho281** [scipy/scipy#21692]
### Describe your issue.

I'm trying to use the shgo function from scipy.optimize to minimize a fairly complicated function of two variables. When computing the cost function, several intermediate results can be used to also compute the gradient, thereby expediting the calculation. According to the documentation, this should be possible by passing options={'jac': True} to shgo. Although the documentation does not provide explicit details on the cost function structure when using this option, I assumed it should work with the same structure of scipy.optimize.minimize, where the cost function returns a tuple containing the function value and the gradient. 

However, this is not working. In order to reproduce the error, below you can find a test code for the much simpler problem of minimizing the function f(x,y) = x² + y² in the square [-1, 1]², with the obvious solution x=y=0.

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import shgo

def cost(x):
    return x[0]**2 + x[1]**2, np.array([2*x[0], 2*x[1]])

result = shgo(cost, [(-1, 1), (-1, 1)], options={'jac': True})
```

### Error message

```shell
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\mario\onedrive\documentos\doutorado\tese\diss\localmodels\untitled2.py:14
    result = shgo(cost, [(-1, 1), (-1, 1)], options={'jac': True})

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo.py:426 in shgo
    shc.construct_complex()

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo.py:751 in construct_complex
    self.iterate()

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo.py:894 in iterate
    self.iterate_complex()

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo.py:916 in iterate_hypercube
    self.HC = Complex(self.dim, self._raw_func, self.args,

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:25 in __init__
    self.n_cube(dim, symmetry=symmetry)

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:80 in n_cube
    self.perm(i_parents, x_parents, origin)

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:105 in perm
    self.V[xi2_t].connect(self.V[xi_t])

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:579 in connect
    if self.minimiser():

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:597 in minimiser
    self._min = all(self.f < v.f for v in self.nn)

  File ~\anaconda3\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py:597 in <genexpr>
    self._min = all(self.f < v.f for v in self.nn)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### SciPy/NumPy/Python version and system information

```shell
sys.version_info); scipy.show_config()
1.10.1 1.23.5 sys.version_info(major=3, minor=9, micro=17, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mario/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mario/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mario/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mario/anaconda3\\Library\\include']
```

**Comment by mdhaber** [comment]
Thanks. This sort of bug was reported before (e.g. gh-16215) but I think those issues were closed prematurely since gh-14013 didn't merge and gh-16313 didn't address them. We'll leave this one open.

**Comment by RafaelLuz** [comment]
I ran @mariofilho281's code using the most recent release of scipy. It didn't work either, but I got a different error:

```
Traceback (most recent call last):
  File "/home/rafael/Workspace/Development/Projects/bspoc/sseng-training/__data/lab.py", line 12, in <module>
    result = shgo(cost, [(-1, 1), (-1, 1)], options={'jac': True})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo.py", line 455, in shgo
    shc.iterate_all()
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo.py", line 836, in iterate_all
    self.iterate()
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo.py", line 1009, in iterate
    self.iterate_complex()
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo.py", line 1058, in iterate_hypercube
    self.HC.V.process_pools()
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 327, in process_pools
    self.process_fpool()
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 384, in proc_fpool_nog
    self.compute_sfield(v)
  File "/home/rafael/.pyenv/versions/bspoc.seng-training/lib/python3.12/site-packages/scipy/optimize/_shgo_lib/_vertex.py", line 352, in compute_sfield
    if np.isnan(v.f):
       ^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

my scipy version:

```
import sys, scipy, numpy 

print(scipy.__version__, numpy.__version__, sys.version_info)
scipy.show_config()

1.14.1 2.1.1 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-znxdftlb/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

**Comment by dschmitz89** [comment]
Cc @Stefan-Endres

**Comment by czgdp1807** [comment]
I am getting the same error as https://github.com/scipy/scipy/issues/21692#issuecomment-2408527983. I will investigate the bug.
