### ISSUE TITLE
BUG: sparse.linalg: calling `norm` on `sparray` does not work for 1-norms

### ISSUE THREAD

**Issue by peoe** [scipy/scipy#21690]
### Describe your issue.

I'm implementing code for sparse matrices and decided to use `sparray` instead of `spmatrix` (trying to preempt the shift towards `sparray` here). I want to compute the 1-norm of a sparse matrix, however I get the error shown below. Similarly, the norm orders `inf`, `-inf`, `0`, `-1` fail to compute.

It seems to me that the reduction in `mat.sum(axis=0)` from a 2D shape to a 1D shape messes up the call to `max(axis=1)`.

### Reproducing Code Example

```python
import scipy.sparse as sps

mat = sps.random_array((100, 100), density=0.1)
sps.linalg.norm(mat, ord=1)
```

### Error message

```shell
Traceback (most recent call last):
  File "[path-to-my-code]/scipy_norm_sparray_bug.py", line 5, in <module>
    sps.linalg.norm(mat, ord=1)
  File "[path-to-my-venv]/lib/python3.10/site-packages/scipy/sparse/linalg/_norm.py", line 151, in norm
    return abs(x).sum(axis=row_axis).max(axis=col_axis)[0,0]
  File "[path-to-my-venv]/lib/python3.10/site-packages/numpy/core/_methods.py", line 41, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 1.26.4 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
[path-to-my-venv]/lib/python3.10/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "13.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-mmy0d4vk/overlay/lib/python3.10/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-d9imboit/cp310-macosx_arm64/build/venv/bin/python",
    "version": "3.10"
  }
}
```

**Comment by dschult** [comment]
I can verify this bug.  And It looks like there is a fairly easy fix because the axis for the second function in each of these types of norms doesn't need to be specified.  
For example, for `ord=1`,
```python
abs(x).sum(axis=row_axis).max().ravel()[0]
```
works for both spmatrix and sparray.

This shows that we have work to do to get `sparse.linalg` and `sparse.csgraph` compatible with the sparse array interface.
Thank you @peoe !!
