### ISSUE TITLE
BUG: boolean indexing of sparse arrays broken on `main`

### ISSUE THREAD

**Issue by dcherian** [scipy/scipy#21747]
### Describe your issue.

Boolean indexing of sparse arrays is broken if an Ellipsis is provided.

### Reproducing Code Example

```python
import numpy as np

dense = np.zeros((1, 3), dtype=bool)
dense[0, 0] = True
array = csc_array(dense)
mask = np.array([True, True, False])
array[:, mask] # works!
array[..., mask] # error below
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deepak/miniforge3/envs/xarray-upstream/lib/python3.12/site-packages/scipy/sparse/_index.py", line 30, in __getitem__
    index, new_shape = self._validate_indices(key)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/miniforge3/envs/xarray-upstream/lib/python3.12/site-packages/scipy/sparse/_index.py", line 237, in _validate_indices
    raise IndexError(
IndexError: bool index 1 has shape (1,) instead of (3,)
```

^ Note that it's trying to index along axis 0 instead of axis 1 as requested.

### SciPy/NumPy/Python version and system information

```shell
1.15.0.dev0+git20241023.59fd061 2.2.0.dev0+git20241022.020e78c sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: Accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: Accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/pip-build-env-jfqgu1eg/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/cibw-run-8jvo626d/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by perimosocordiae** [comment]
This might be related to gh-21615, though I haven't thought too deeply about it. @dschult FYI

**Comment by dschult** [comment]
Yes -- I can verify that this is a problem, and one related to gh-21615, so I initially thought it would have been fixed by [gh-21615](https://github.com/scipy/scipy/pull/21616) but it isn't fixed. I will take a look.

Thanks @dcherian !!
