### ISSUE TITLE
DEV/BLD: `ModuleNotFoundError: No module named 'mesonpy'`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#21766]
### Describe your issue.

Trying to install SciPy from develoment from scratch on my Mac, I get an error `ModuleNotFoundError: No module named 'mesonpy'`.

### Reproducing Code Example

```python
(base) matthaberland@Matts-MacBook-Air scipy % mamba env create -f environment.yml     
(base) matthaberland@Matts-MacBook-Air scipy % mamba activate scipy-dev        
(scipy-dev) matthaberland@Matts-MacBook-Air scipy % python -m pip install --no-build-isolation --editable .
```

### Error message

```shell
Obtaining file:///Users/matthaberland/Desktop/scipy
  Checking if build backend supports build_editable ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
        reqs, check_supported_wheels=not options.target_dir
    )
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 539, in collect_root_requirements
    reqs = list(
        self._make_requirements_from_install_req(
    ...<2 lines>...
        )
    )
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 495, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
        ireq.link,
    ...<2 lines>...
        version=None,
    )
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_base_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
                                           ~~~~~~~~~~~~~~~~~^
        link,
        ^^^^^
    ...<3 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        link=link,
        ^^^^^^^^^^
    ...<4 lines>...
        version=version,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ~~~~~~~~~~~~~^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 338, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 698, in prepare_editable_requirement
    dist = _get_prepared_distribution(
        req,
    ...<3 lines>...
        self.check_build_deps,
    )
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        finder, build_isolation, check_build_deps
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 69, in prepare_distribution_metadata
    self.req.prepare_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/req/req_install.py", line 567, in prepare_metadata
    and self.supports_pyproject_editable
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/functools.py", line 1037, in __get__
    val = self.func(instance)
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_internal/req/req_install.py", line 258, in supports_pyproject_editable
    return "build_editable" in self.pep517_backend._supported_features()
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 153, in _supported_features
    return self._call_hook('_supported_features', {})
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/Users/matthaberland/miniforge3/envs/scipy-dev/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'
```

### SciPy/NumPy/Python version and system information

```shell
-
```

**Comment by lucascolley** [comment]
To confirm: `meson-python` is in `environment.yml` on the branch you are working from?

**Comment by lucascolley** [comment]
The same symptoms (but not the same cause it seems) were observed in https://github.com/scipy/scipy/issues/19565.

**Comment by mdhaber** [comment]
Yes, main.

**Comment by andyfaff** [comment]
Those commands work for me on macOS. `meson-python` is definitely listed in environment.yml. (I use the `conda` command from miniforge instead of mamba). Is `meson-python` present in `conda list`?

**Comment by mdhaber** [comment]
Yes, it is.

**Comment by rgommers** [comment]
Works fine for me as well (tried today in a fresh env). This is almost certainly a broken environment. Please try replacing `python -m pip install ...` with `python -c "import mesonpy"`, check your `python` executable actually is the right one, and/or check the `/Users/matthaberland/miniforge3/scipy-dev/lib/python3.13/site-packages/mesonpy` dir for expected content.

**Comment by mdhaber** [comment]
Same error with `python -c "import mesonpy",`. It's repeatable with a fresh environment. But after changing `environments.yml` to require `meson-python=0.16`, it seems to work.
Separately, tried `mamba install -n meson meson-python`. After activating the new environment, `python -c "import mesonpy"` fails. After `mamba install -c conda-forge meson-python=0.16`, it works. So I guess it's specific to mesonpy 0.17.
Thoughts on what I should report upstream?

**Comment by lucascolley** [comment]
FWIW I can't reproduce with meson-python 0.17.1.

**Comment by rgommers** [comment]
> Thoughts on what I should report upstream?

Could you add the full traceback for `import mesonpy` here? Maybe I can spot the problem. If not, https://github.com/conda-forge/meson-python-feedstock/issues/ is the place to report it.

> In general, I don't get useful error messages with the in-place build. 

Do you have [`MESONPY_EDITABLE_VERBOSE`](https://mesonbuild.com/meson-python/reference/environment-variables.html#envvar-MESONPY_EDITABLE_VERBOSE) set? With that, I'd expect you to see both the output of the build steps and any error messages.

**Comment by mdhaber** [comment]
Full traceback was just
```python3
(meson) matthaberland@Matts-MacBook-Air-2 ~ % python -c "import mesonpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import mesonpy
ModuleNotFoundError: No module named 'mesonpy'
```
Even though `meson-python           0.17.1  pyh70fd9c4_0        conda-forge/noarch   ` was clearly installed.

No, I did not have that set. I'll try setting it.

**Comment by mdhaber** [comment]
Rather than using my SciPy environment, for test purposes my environment is called `meson`. The files end up in:
```
~/miniforge3/envs/meson/site-packages/mesonpy
```
not where it sounds like they should be:
```
~/miniforge3/envs/meson/lib/python3.13/site-packages/mesonpy
```

**Comment by rgommers** [comment]
Hmm I've never seen that before. @h-vetinari maybe you have an idea of how/why a noarch package installs to the wrong directory like in the comment above?

**Comment by mdhaber** [comment]
Interesting, and when I re-upgrade to `mesonpy=0.17.1`, it goes in the right place.

**Comment by h-vetinari** [comment]
Sorry I missed this ping, I'll try to have a look tomorrow
