### ISSUE TITLE
BUG: Multiple DiscreteAliasUrn instances cause MessageStream.close error

### ISSUE THREAD

**Issue by jiang131072** [scipy/scipy#21958]
### Describe your issue.

I'm using the DiscreteAliasUrn method to generate samplers for node2vec random walks, but I've failed to create multiple instances. Is this the expected behavior?

### Reproducing Code Example

```python
from scipy.stats.sampling import DiscreteAliasUrn

t = []
for i in range(512):
    t.append(DiscreteAliasUrn([0.5, 0.5]))
```

### Error message

```shell
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
FileNotFoundError: [WinError 2] The system cannot find the file specified: b'C:\\Users\\UserName\\AppData\\Local\\Temp\\scipy-7gspxvhu'
Exception ignored in: 'scipy._lib.messagestream.MessageStream.__dealloc__'
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
FileNotFoundError: [WinError 2] The system cannot find the file specified: b'C:\\Users\\UserName\\AppData\\Local\\Temp\\scipy-7gspxvhu'
Traceback (most recent call last):
  File "C:\Users\UserName\repo\ws-py\hello.py", line 5, in <module>
    t.append(DiscreteAliasUrn([0.5, 0.5]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "unuran_wrapper.pyx", line 2383, in scipy.stats._unuran.unuran_wrapper.DiscreteAliasUrn.__cinit__
  File "messagestream.pyx", line 43, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: Failed to open file b'C:\\Users\\UserName\\AppData\\Local\\Temp\\scipy-7gspxvhu'
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=12, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=24
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=24
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-q53zt7ci\overlay\Lib\site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-jntqarym\cp312-win_amd64\build\venv\Scripts\python.exe
  version: '3.12'
```

**Comment by rgommers** [comment]
Thanks for the report @jiang131072. 

This `unuran` functionality needs callbacks for error messages, which is done in-memory if possible and via file-based I/O as a fallback. The file-based method may not be robust against multiple instances being created. There were two recent improvements here:
- `1.14.1` fixed an `open_memstream` detection issue: gh-21084
- In `main` (so for 1.15.0)` the usage of the in-memory method was expanded: gh-21860

The example code works fine for me on macOS. Could you please try if you still see this with scipy 1.14.1
@jiang131072? And if you do, could you please also try a nightly from https://anaconda.org/scientific-python-nightly-wheels/scipy/?

**Comment by jiang131072** [comment]
1.14.1 and the nightly version 1.16.0.dev0 have not solved the problem, the error message is completely the same.

1.16.0.dev0 system information:
```log
1.16.0.dev0+git20241207.3673327 2.2.0 sys.version_info(major=3, minor=12, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-av06k28n/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-av06k28n/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-av06k28n/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-av06k28n/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-mk6z86kr\overlay\Lib\site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-av06k28n\cp312-win_amd64\build\venv\Scripts\python.exe
  version: '3.12'
```

**Comment by rgommers** [comment]
I had a closer look at the code in `messagestream.pyx`, and it uses `tempfile.mkstemp` to create files in the file-based fallback method. That should be fine - from the docs: _"Creates a temporary file in the most secure manner possible. There are no race conditions ..."_

It looks like what you're running into here is the limit of 512 open file handles per process, which is a default set by the Windows C runtime libraries: https://learn.microsoft.com/en-us/cpp/c-runtime-library/file-handling?view=msvc-170
Can you confirm that it works for a lower number than 512?

I don't think there's a way to fix this on Windows. Windows doesn't provide `open_memstream` or an equivalent - see [this SO answer](https://stackoverflow.com/questions/2864178/equivalent-of-open-memstream-for-msvc). All the workarounds I can find for things like `fmemopen` and `funopen` also use temporary files on Windows.

For completeness, the build logs of all Windows builds show:
```
Checking for function "open_memstream" : NO 
```

**Comment by mdhaber** [comment]
Looks similar to gh-17360?

**Comment by rgommers** [comment]
I don't think it's the same as gh-17360. That one was failing for unknown reason (and probably fixed along the way) without opening 512 file handles in parallel.
