### ISSUE TITLE
BUG:  `eliminate_zeros` raises when `indptr.dtype` != `indices.dtype`

### ISSUE THREAD

**Issue by DriesSchaumont** [scipy/scipy#21959]
### Describe your issue.

`eliminate_zeros` raises when `inptr.dtype` differs from `indices.dtype`. 
- I am aware that only `np.int32` and `np.int64` are supported data dtypes for `intptr` and `indices`, but the problem occurs when one of the datatypes is `int32` and one is `int64`.
- This might be a known limitation, but I was unable to find a mention of this in the documentation. Happy to close if it is mentioned somewhere.

Thanks!

### Reproducing Code Example

```python
Python 3.11.9 (main, Aug 16 2024, 13:37:14) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> import numpy as np
>>> test_array = scipy.sparse.csr_array([1, 2, 3, 0, 4])
>>> test_array.indptr = test_array.indptr.astype(np.int64)
>>> test_array.eliminate_zeros()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/scipy/sparse/_compressed.py", line 1207, in eliminate_zeros
    _sparsetools.csr_eliminate_zeros(M, N, self.indptr, self.indices, self.data)
ValueError: Output dtype not compatible with inputs.
>>> test_array.indices = test_array.indices.astype(np.int64)
>>> test_array.eliminate_zeros()
```

### Error message

```shell
ValueError: Output dtype not compatible with inputs.
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-k6xvzqr5/overlay/lib/python3.11/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by perimosocordiae** [comment]
Thanks for the report. We do not support different index dtypes for the same sparse array/matrix, because doing so would require a significant increase in the amount of native code required.

That said, this issue indicates that we should:

 - improve the error message for this case 
 - make sure the docs are clear about what we support. 

@dschult FYI

**Comment by DriesSchaumont** [comment]
That makes sense. Might I suggest asserting this and raising on the setters of `indptr` and `indices`? 
From my limited understanding, changing the dtype of inptr or indices should (1) not be possible or (2) there should be a 'safe' method to do this. This is somewhat related to https://github.com/scipy/scipy/pull/21858, but for (2) to be possible, the function propose in this PR (or a derivative) would need to make its way into the public API somehow.

**Comment by WoojinJung-04** [comment]
Hi, I would like to give it a try on this issue if no one is on this. Is anyone working on this, or is this closed?

**Comment by dschult** [comment]
You can work on this issue. And you don't have to request or get permission to fix an issue. :)
Issues are not assigned to people and are open until a PR or a maintainer closes them. So this one is open.
Thanks!
