### ISSUE TITLE
DOC: Deprecation warning in `sphinx` when used with Python 3.13

### ISSUE THREAD

**Issue by czgdp1807** [scipy/scipy#21963]
### Issue with current documentation:

This is related to building of `docs`. When I was working on https://github.com/scipy/scipy/pull/21674, I created an entirely new conda environment. I tried to build the documentation and faced the following error coming from `sphinx`. Same error happens with `sphinx 8.1.3` as well (latest release available on conda). However, there is no such issue with Python 3.12. Only happens with Python 3.13. Probably we should fix, `python<=3.12` in `environment.yml` so that CI job doesn't start to fail. I think SciPy doesn't have to do any updates. Just reporting here for knowledge of the community (if it hasn't already been reported before). **Please close it as a duplicate if someone already reported.**

```zsh
LANG=C python3 -msphinx -WT --keep-going  -b html -d build/doctrees  source build/html 
Running Sphinx v7.4.7
SciPy (VERSION 1.15.0.dev)
loading translations [en]... done

Traceback (most recent call last):
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
                 args.doctreedir, args.builder, args.confoverrides, args.status,
                 args.warning, args.freshenv, args.warningiserror,
                 args.tags, args.verbosity, args.jobs, args.keep_going,
                 args.pdb)
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/sphinx/application.py", line 253, in __init__
    self.setup_extension(extension)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/sphinx/application.py", line 429, in setup_extension
    self.registry.load_extension(self, extname)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/sphinx/registry.py", line 466, in load_extension
    metadata = setup(app)
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/__init__.py", line 8, in setup
    from .sphinx_ext import sphinx_setup
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/sphinx_ext.py", line 22, in <module>
    from myst_nb.ext.download import NbDownloadRole
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/ext/download.py", line 8, in <module>
    from myst_nb.sphinx_ import SphinxEnvType
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/sphinx_.py", line 29, in <module>
    from myst_nb.core.execute import ExecutionResult, create_client
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/core/execute/__init__.py", line 7, in <module>
    from .cache import NotebookClientCache
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/myst_nb/core/execute/cache.py", line 13, in <module>
    from jupyter_cache.executors.utils import single_nb_execution
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 7, in <module>
    from nbclient import execute as executenb
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/nbclient/__init__.py", line 2, in <module>
    from .client import NotebookClient, execute
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/nbclient/client.py", line 31, in <module>
    from .output_widget import OutputWidget
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/nbclient/output_widget.py", line 10, in <module>
    from .jsonutil import json_clean
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/site-packages/nbclient/jsonutil.py", line 29, in <module>
    datetime.strptime("1", "%d")
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/_strptime.py", line 573, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/_strptime.py", line 336, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/_strptime.py", line 282, in compile
    return re_compile(self.pattern(format), IGNORECASE)
                      ~~~~~~~~~~~~^^^^^^^^
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/_strptime.py", line 270, in pattern
                warnings.warn("""\
                ~~~~~~~~~~~~~^^^^^
    Parsing dates involving a day of month without a year specified is ambiguious
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                              DeprecationWarning,
                              ^^^^^^^^^^^^^^^^^^^
                              skip_file_prefixes=(os.path.dirname(__file__),))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.

Exception occurred:
  File "/Users/czgdp1807/mambaforge/envs/scipy-dev-latest/lib/python3.13/_strptime.py", line 270, in pattern
                warnings.warn("""\
                ~~~~~~~~~~~~~^^^^^
    Parsing dates involving a day of month without a year specified is ambiguious
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                              DeprecationWarning,
                              ^^^^^^^^^^^^^^^^^^^
                              skip_file_prefixes=(os.path.dirname(__file__),))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
The full traceback has been saved in /var/folders/q9/813mwlx94cdbjkzc76098f040000gn/T/sphinx-err-ep4vo1un.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html-build] Error 2
```

**Comment by lucascolley** [comment]
related: https://github.com/jupyter/jupyter_client/pull/1027

**Comment by lucascolley** [comment]
I'll send a fix to nbclient

**Comment by lucascolley** [comment]
An unfortunately long dependency chain... sphinx -> myst_nb -> jupyter_cache -> nbclient

**Comment by lucascolley** [comment]
nbclient release is out

**Comment by lucascolley** [comment]
`mm create -f environment.yml` now loads `nbclient 0.10.1`, so closing! Please reopen if the issue persists @czgdp1807
