### ISSUE TITLE
ENH: `ndimage.median_filter`: extended `dtype` support?

### ISSUE THREAD

**Issue by ego-thales** [scipy/scipy#21971]
### Is your feature request related to a problem? Please describe.

I just realized that `ndimage.median_filter` only supports 2 floating types: `float32` and `float64`. Is there a specific reason to that? Could we hope for extended support?

### Describe the solution you'd like.

At least support for `float16` which is pretty standard in use today. Ideally every floating point `dtype`.

### Additional context (e.g. screenshots, GIFs)

```console
 name         : scipy                                                     
 version      : 1.14.1
```

**Comment by ego-thales** [comment]
Hi there @ev-br, @mdhaber!

I tested with `v1.16.0rc1` and still got the following errors.
```pycon
>>> median_filter(np.zeros((1,2), dtype=np.float16), size=2)
Traceback (most recent call last):
  File "<python-input-51>", line 1, in <module>
    median_filter(np.zeros((1,2), dtype=np.float16), size=2)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/scipy/ndimage/_filters.py", line 2105, in median_filter
    return _rank_filter(input, 0, size, footprint, output, mode, cval,
                        origin, 'median', axes=axes)
  File "[...]/scipy/ndimage/_filters.py", line 1992, in _rank_filter
    _nd_image.rank_filter(input, rank, footprint, output, mode, cval, origins)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: array type not supported
>>> median_filter(np.zeros(1, dtype=np.float16), size=2)
Traceback (most recent call last):
  File "<python-input-52>", line 1, in <module>
    median_filter(np.zeros(1, dtype=np.float16), size=2)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/scipy/ndimage/_filters.py", line 2105, in median_filter
    return _rank_filter(input, 0, size, footprint, output, mode, cval,
                        origin, 'median', axes=axes)
  File "[...]/scipy/ndimage/_filters.py", line 1956, in _rank_filter
    return maximum_filter(input, None, footprint, output, mode, cval,
                          origins, axes=None)
  File "[...]/scipy/ndimage/_filters.py", line 1898, in maximum_filter
    return _min_or_max_filter(input, size, footprint, None, output, mode,
                              cval, origin, 0, axes)
  File "[...]/scipy/ndimage/_filters.py", line 1763, in _min_or_max_filter
    filter_(input, int(size), axis, output, mode, cval, origin)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/scipy/ndimage/_filters.py", line 1708, in maximum_filter1d
    _nd_image.min_or_max_filter1d(input, size, axis, output, mode, cval,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                  origin, 0)
                                  ^^^^^^^^^^
RuntimeError: array type dtype('float16') not suppo@mdhaber 
```

Should we reopen the issue or am I doing something wrong?

```pycon
>>> scipy.version.version
'1.16.0rc1'
```

All the best.
Élie

**Comment by lucascolley** [comment]
From the linked PR:

> By documenting the limitations of median_filter and suggesting vectorized_filter as a performant work-around

Indeed, in the Notes of https://scipy.github.io/devdocs/reference/generated/scipy.ndimage.median_filter.html we now have:

> this function does not support the float16 dtype, behavior in the presence of NaNs is undefined, and memory consumption scales with n**4. For float16 support, greater control over the definition of the filter, and to limit memory usage, consider using [vectorized_filter](https://scipy.github.io/devdocs/reference/generated/scipy.ndimage.vectorized_filter.html#scipy.ndimage.vectorized_filter) with NumPy functions np.median or np.nanmedian.

**Comment by ev-br** [comment]
And indeed, 

```
In [5]: from scipy.ndimage import vectorized_filter

In [6]: vectorized_filter(np.zeros((1,2), dtype=np.float16), np.median, size=2)
Out[6]: array([[0., 0.]], dtype=float16)
```

**Comment by ego-thales** [comment]
Oooh, thank you, sorry I didn't pay attention there!
