### ISSUE TITLE
Pythonw does not run on Windows 11 when scipy.fft is being imported

### ISSUE THREAD

**Issue by miguelmaso** [scipy/scipy#22096]
### Describe your issue.

I have developed a small `pyw` which is using `scipy.fft` internally. Recently, I have noticed that this small script stops running on Windows 11.

As a workaround, I have tried to redirect `stdout` and `stderr` before importing `scipy.fft`:
```py
if sys.executable.endswith('pythonw.exe'):
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.path.join(os.getenv('TEMP'), 'stderr-' + os.path.basename(sys.argv[0])), 'w')
```
If so, the python script works well but no error message is captured.

### Reproducing Code Example

```python
import tkinter as tk
from scipy.fft import fft, fftfreq
root = tk.Tk()
root.mainloop()
```

### Error message

```shell
Precisely, there is no error message.
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.14.1 2.0.0 sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-sf8gymnb\overlay\Lib\site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-do_lqnow\cp312-win_amd64\build\venv\Scripts\python.exe
  version: '3.12'
```

**Comment by andyfaff** [comment]
Do you see any problems importing when in an interpreter? If not, then it's unlikely to be a scipy issue.

**Comment by miguelmaso** [comment]
*file1.pyw*
```py
import tkinter as tk
from scipy.fft import fft, fftfreq
root = tk.Tk()
root.mainloop()
```

*file2.pyw*
```py
import tkinter as tk
root = tk.Tk()
root.mainloop()
```

*file3.pyw*
```py
import sys, os
import tkinter as tk
if sys.executable.endswith('pythonw.exe'):
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.path.join(os.getenv('TEMP'), 'stderr-' + os.path.basename(sys.argv[0])), 'w')
from scipy.fft import fft, fftfreq
root = tk.Tk()
root.mainloop()
```

The following command does not run:
```
pythonw.exe file1.py
```

The following command runs well:
```
pythonw.exe file2.py
```

The following command runs well:
```
python.exe file1.py
```

The following command runs well:
```
pythonw.exe file3.py
```

**Comment by andyfaff** [comment]
If `from scipy.fft import fft, fftfreq` works in a python interpreter, then there's not much we can do with this bug report unless there's further information pointing to an issue with scipy.

**Comment by miguelmaso** [comment]
AFAIK with `pythonw.exe`, `sys.stdin`, `sys.stdout` and `sys.stderr` are not available. Hence, explicit calls to them causes the script to abort silently.

When importing `scipy.fft` the script is aborted silently. However, I'm able to import other modules like `numpy` or `scipy` itself.

A possible workaround is to redirect `stdout` and `stderr` before importing `scipy.fft`.

If this is not the place to post this issue, could you give me some advice where to?

**Comment by rgommers** [comment]
Does it happen with other `scipy` modules, or when you import say `numpy.linalg` or `numpy.fft`?

**Comment by rgommers** [comment]
So there's probably some fundamental issue here either with Tkinter + something in the numpy/scipy binaries, or it's broken on your machine.

I have no expectation about whether this is supposed to work or not. Most of `numpy` seems to work, so what about libraries that depend on `numpy` but not `scipy`, like `matplotlib` or `pandas`?

**Comment by miguelmaso** [comment]
I'm afraid it is not matter of Tkinter. I added a small example with tkinter because it is a standard Python library, even though the same problem will happen with pyqt.

The main point is that it seems there is a call to `stderr` or `stdout` when importing `scipy.fft` and other modules, which is causing to terminate the program with `pythonw` interpreter. In the description I wrote

> As a workaround, I have tried to redirect `stdout` and `stderr` before importing `scipy.fft`:

**Comment by rgommers** [comment]
Ah that helps, thanks. I don't see any `sys.stdout`, `sys.stderr`, `print`, `printf`, `std::cout` or similar though. Is there any way you can narrow this down, by getting a traceback, or finding what release or commit introduced the problem (you wrote that it stopped working recently?)?

**Comment by miguelmaso** [comment]
Sorry, I tried to get the traceback by redirecting the output, but I got nothing... Furthermore, it solved the issue. Also, I tried to look for some sys.stdout, sys.stderr, print, printf, std::cout...

As you pointed before, it could be related to a specific part of `numpy` and those libraries that depend on them, are experiencing this problem. Just a possibility

**Comment by czgdp1807** [comment]
So regarding this I am going to begin my investigation in the next couple of hours. I will do it with `ifort` or `ifx` because, `gfortran` is giving build issues (specifically errors at linking stage). I will update here shortly.

**Comment by czgdp1807** [comment]
This is what I get when I use the code in the OP,

```zsh
C:\Users\czgdp1807\Quansight\scipy>pythonw.exe ../debug.pyw

C:\Users\czgdp1807\Quansight\scipy>
```

However, when I comment out, `from scipy.fft import fft, fftfreq` then a window opens (with a feather like icon on LHS and `tk` written). I think that's what we except when `from scipy.fft import fft, fftfreq` is not commented out, right?

**Comment by rgommers** [comment]
Thanks @czgdp1807 for looking into this. 

> It aborts silently if the import is present.

What is needed here is to figure out _why_ the silent abort. Please see if you can narrow it down further, and/or understand what is actually happening.

**Comment by czgdp1807** [comment]
I read, [this answer](https://stackoverflow.com/a/30313091) on stackoverflow. I followed the suggestion, `pythonw.exe yourScript.pyw 1>stdout.txt 2>stderr.txt` on the following example,

```python
import sys, os
import tkinter as tk
import numpy.test
root = tk.Tk()
root.mainloop()
```

and,

I executed, `pythonw.exe ../debug.pyw 1>stdout.txt 2>stderr.txt` and I opened `stderr.txt`,

```zsh
Traceback (most recent call last):
  File "C:\Users\czgdp1807\Quansight\debug.pyw", line 3, in <module>
    import numpy.test
ModuleNotFoundError: No module named 'numpy.test'
```

If you read the above stackoverflow answer it says that `pythonw` launches the script in background and if any exception is unhandled then it aborts silently. I will dig deeper now to figure out the root cause. I will update here if will see a dead end or something significant (pin point root cause of the problem)

**Comment by czgdp1807** [comment]
Here are the final thoughts,

**Case 1** (Setting PYTHONPATH)

Works fine, tinker window opens and I have to close it. The process terminates,

```cmd
C:\Users\czgdp1807\Quansight\scipy>set PYTHONPATH=C:\Users\czgdp1807\Quansight\scipy\build-install\Lib\site-packages

C:\Users\czgdp1807\Quansight\scipy>pythonw.exe ../debug.pyw
```

**Case 2** (Unset PYTHONPATH)

```cmd
C:\Users\czgdp1807\Quansight\scipy>set PYTHONPATH=

C:\Users\czgdp1807\Quansight\scipy>pythonw.exe ../debug.pyw

C:\Users\czgdp1807\Quansight\scipy>echo %PYTHONPATH%
%PYTHONPATH%
```

Aborts silently. Let's the error from `stderr.txt` (by executing, `pythonw.exe ../debug.pyw 1>stdout.txt 2>stderr.txt`)

```txt
Traceback (most recent call last):
  File "C:\Users\czgdp1807\Quansight\debug.pyw", line 2, in <module>
    from scipy.fft import fft, fftfreq
ModuleNotFoundError: No module named 'scipy.fft'
```

So I think we should set PYTHONPATH when building SciPy from source. In general also, make sure that PYTHONPATH is set correctly. And use `pythonw.exe ../debug.pyw 1>stdout.txt 2>stderr.txt` and open `stderr.txt` to see the Traceback in case it aborts silently.

cc: @rgommers @andyfaff

**Comment by rgommers** [comment]
That PYTHONPATH issue doesn't seem relevant. It's not needed when installing `scipy` in a regular way, e.g. with `pip` or `conda`, only when building locally with `dev.py`. 

You only should have to investigate the case where `python.exe` does work, and `pythonw.exe` does not.

> Works fine, tinker window opens and I have to close it. 

That sounds like you cannot reproduce the bug report locally.

**Comment by czgdp1807** [comment]
> You only should have to investigate the case where python.exe does work, and pythonw.exe does not.

There are 4 cases,

1. `python.exe` and `scipy` modules.
2. `pythonw.exe` and `scipy` modules. 
3. `python.exe` and `numpy` modules.
4. `pythonw.exe` and `numpy` modules.

If the issue posted here exists then 1 should work and 2 should not. Similarly, 3 should work and 4 should not. 
Now, here are codes,

<details>

<summary>debug_scipy.py</summary>

```python
import tkinter as tk
import scipy as sp
import scipy.cluster
import scipy.constants
import scipy.datasets
import scipy.fft
import scipy.fftpack
import scipy.integrate
import scipy.interpolate
import scipy.io
import scipy.linalg
import scipy.ndimage
import scipy.odr
import scipy.optimize
import scipy.signal
import scipy.sparse
import scipy.spatial
import scipy.special
import scipy.stats
print(scipy.__version__)
root = tk.Tk()
root.mainloop()
```
</details>

<details>

<summary>debug_numpy.py</summary>

```python
import tkinter as tk
import numpy
import numpy.char
import numpy.compat
import numpy.conftest
import numpy.core
import numpy.ctypeslib
import numpy.doc
import numpy.dtypes
import numpy.exceptions
import numpy.f2py
import numpy.fft
import numpy.lib
import numpy.linalg
import numpy.ma
import numpy.matlib
import numpy.matrixlib
import numpy.polynomial
import numpy.random
import numpy.rec
import numpy.strings
import numpy.testing
import numpy.tests
import numpy.typing
import numpy.version
print(numpy.__version__)
root = tk.Tk()
root.mainloop()
```

</details>

<details>

<summary>debug_scipy.pyw</summary>

```python
import tkinter as tk
import scipy as sp
import scipy.cluster
import scipy.constants
import scipy.datasets
import scipy.fft
import scipy.fftpack
import scipy.integrate
import scipy.interpolate
import scipy.io
import scipy.linalg
import scipy.ndimage
import scipy.odr
import scipy.optimize
import scipy.signal
import scipy.sparse
import scipy.spatial
import scipy.special
import scipy.stats
print(scipy.__version__)
root = tk.Tk()
root.mainloop()
```
</details>

<details>

<summary>debug_numpy.pyw</summary>

```python
import tkinter as tk
import numpy
import numpy.char
import numpy.compat
import numpy.conftest
import numpy.core
import numpy.ctypeslib
import numpy.doc
import numpy.dtypes
import numpy.exceptions
import numpy.f2py
import numpy.fft
import numpy.lib
import numpy.linalg
import numpy.ma
import numpy.matlib
import numpy.matrixlib
import numpy.polynomial
import numpy.random
import numpy.rec
import numpy.strings
import numpy.testing
import numpy.tests
import numpy.typing
import numpy.version
print(numpy.__version__)
root = tk.Tk()
root.mainloop()
```

</details>

SciPy and NumPy both are installed from `pip`,

**Command**

`python.exe Quansight/debug_scipy.py 1>stdout.txt 2>stderr.txt`

**Output (stored in `stdout.txt`)**

```zsh
{'path': 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-afqdhy8b\\cp312-win_amd64\\build\\venv\\Scripts\\python.exe', 'version': '3.12'} 1.15.1
```

**Command**

`pythonw.exe Quansight/debug_scipy.pyw 1>stdout.txt 2>stderr.txt`

**Output (stored in `stdout.txt`)**

```zsh
{'path': 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-afqdhy8b\\cp312-win_amd64\\build\\venv\\Scripts\\python.exe', 'version': '3.12'} 1.15.1
```

**Command**

`python.exe Quansight/debug_numpy.py 1>stdout.txt 2>stderr.txt`

**Output (stored in `stdout.txt`)**

```zsh
{'path': 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-e_e39y2o\\Scripts\\python.exe', 'version': '3.12'} 2.2.2
```

**Command**

`pythonw.exe Quansight/debug_numpy.pyw 1>stdout.txt 2>stderr.txt`

**Output (stored in `stdout.txt`)**

```zsh
{'path': 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\build-env-e_e39y2o\\Scripts\\python.exe', 'version': '3.12'} 2.2.2
```

Everything works perfectly fine on my Windows machine. Results for SciPy built from source are in https://github.com/scipy/scipy/issues/22096#issuecomment-2604427245.


**End Note** - This issue doesn't reproduce on my system. This means this issue doesn't exist on Python installed on Windows (from python.org). I tried with virtual environments as well. The above codes work there too without any issues for both `python.exe` or `pythonw.exe`. 

The issues doesn't exist for me in all the configurations I tried for any of the modules listed in https://github.com/scipy/scipy/issues/22096#issuecomment-2548223996.

**Comment by JTignor-Raltron** [comment]
I experienced this issue trying to use `scipy.interpolate`, but only on one system. My update that included this hasn't rolled out to every system we have, but at least 3 other machines work.

Python is installed as part of an anaconda environment. Same env file used to deploy on all systems. I'm using an older version of both python (3.9) and scipy (1.13.1), but for a hard to replicate bug like this, I figure any hint might be helpful.

Before finding this I did trace the error as far as I could before the jump from python into C, tracing it to the line `from . import _ufuncs` in `_support_alternate_backends.py`.

I also determined the problem is only with stderr being missing as if I only replace `sys.stderr` with a file output stream it works (without needing to replace `sys.stdout`).

**Comment by JTignor-Raltron** [comment]
It is the same environment.yaml file, but that file locks the python version to major python version 3.9 and that restricts a lot of packages to older versions.

I checked the version on the problem machine, but hadn't looked too deeply at the working ones. Just checked and it was on an older version of both python and scipy. Updated both and it still works though. Both are running these specific builds if it helps:
`python                    3.9.20               h8205438_1    main`
`scipy                     1.13.1           py39h8640f81_1    main`

**Comment by PhilipWilkinson** [comment]
I've recently seem a similar issue with Python 3.12.5 and Scipy 1.31.1, Occured when bumping Numpy from 1.26.4. The application runs fine using python.exe but fails using pythonw.exe. Chased it through `from scipy.interpolate import interp1d` to `from numpy import *` in `numpy`. 


Edit: 
Fixed by bumping Scipy to 1.16.0
