### ISSUE TITLE
BUG: `scipy.interpolate._bsplines._make_periodic_spline` crashes the Python Interpreter after correctly raising ValueError

### ISSUE THREAD

**Issue by EgodPrime** [scipy/scipy#22114]
### Describe your issue.

I find this issue when I'm using LLM to generate a call to `scipy.interpolate._bsplines._make_periodic_spline`. 
For this code, the Python Interpreter should raise a ValueError since the input is not valid, and it does so.
I know it's often the case that LLM cannot generate valid inputs for functions, so I wrapped the call to `scipy.interpolate._bsplines._make_periodic_spline` with a "try...except" to avoid the program exit.
However, the Python Interpreter still crashes with a Segmentation fault.
I tested this code on both Python 3,10, 3.11, 3.12 and 3.13, but got the same issue.

### Reproducing Code Example

```python
import numpy as np
import scipy

x = np.linspace(0, 1, 100)
y = np.random.rand(100)
k = 5
t = np.linspace(-1, 4, 1 + 2 * k)[1:-1 + 2 * k]
axis = 0

# scipy.interpolate._bsplines._make_periodic_spline(x, y, t=t, k=k, axis=axis)

try:
    scipy.interpolate._bsplines._make_periodic_spline(x, y, t=t, k=k, axis=axis)
except ValueError as e:
    print(e)
```

### Error message

```shell
# this is what I got without try...except
(py313) root@a475b702ecc0:~# python bug.py 
Traceback (most recent call last):
  File "/root/bug.py", line 10, in <module>
    scipy.interpolate._bsplines._make_periodic_spline(x, y, t=t, k=k, axis=axis)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py313/lib/python3.13/site-packages/scipy/interpolate/_bsplines.py", line 1214, in _make_periodic_spline
    ll += np.diag(ab[i, -kul - (k % 2): n - 1 + 2 * kul - i], k=-i)
ValueError: operands could not be broadcast together with shapes (2,2) (3,3) (2,2) 
Segmentation fault (core dumped)

# this is what I got with try...except
(py313) root@a475b702ecc0:~# python bug.py 
operands could not be broadcast together with shapes (2,2) (3,3) (2,2) 
Segmentation fault (core dumped)
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.2.0 sys.version_info(major=3, minor=13, micro=0, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0rc1/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0rc1/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0rc1/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0rc1/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../opt/python/cp313-cp313/lib/python3.13/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp313-cp31
```

**Comment by ev-br** [comment]
You are trying to reach into non-public functionality, as indicated by the leading underscores, and that's not really supported.

Using the public interface:

```
In [1]: import numpy as np
   ...:
   ...: x = np.linspace(0, 1, 100)
   ...: y = np.random.rand(100)
   ...: k = 5
   ...: t = np.linspace(-1, 4, 1 + 2 * k)[1:-1 + 2 * k]
   ...: axis = 0

In [2]: from scipy.interpolate import make_interp_spline

In [3]: make_interp_spline(x, y, k=5, bc_type='periodic')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 make_interp_spline(x, y, k=5, bc_type='periodic')

File ~/repos/scipy/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_bsplines.py:1516, in make_interp_spline(x, y, k, t, bc_type, axis, check_finite)
   1514 # sanity check the input
   1515 if bc_type == 'periodic' and not np.allclose(y[0], y[-1], atol=1e-15):
-> 1516     raise ValueError("First and last points does not match while "
   1517                      "periodic case expected")
   1518 if x.size != y.shape[0]:
   1519     raise ValueError(f'Shapes of x {x.shape} and y {y.shape} are incompatible')

ValueError: First and last points does not match while periodic case expected

In [4]: y[-1] = y[0]

In [5]: make_interp_spline(x, y, k=5, bc_type='periodic')
Out[5]: <scipy.interpolate._bsplines.BSpline at 0x7f837c723bc0>

```

Also note that indeed, `bc_type="periodic"` does not really support passing in user-constructed knot vectors:

```
In [7]: make_interp_spline(x, y, k=5, t=t, bc_type='periodic')
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[7], line 1
----> 1 make_interp_spline(x, y, k=5, t=t, bc_type='periodic')

File ~/repos/scipy/scipy/build-install/lib/python3.12/site-packages/scipy/interpolate/_bsplines.py:1547, in make_interp_spline(x, y, k, t, bc_type, axis, check_finite)
   1544 k = operator.index(k)
   1546 if bc_type == 'periodic' and t is not None:
-> 1547     raise NotImplementedError("For periodic case t is constructed "
   1548                               "automatically and can not be passed "
   1549                               "manually")
   1551 # come up with a sensible knot vector, if needed
   1552 if t is None:

NotImplementedError: For periodic case t is constructed automatically and can not be passed manually
```

**Comment by EgodPrime** [comment]
You are absolutely right. If the "guard" of the public function is able to ensure the security, and the internal usage is always right, then I believe there is no need to fix this issue. You can close this issue if you like.
