### ISSUE TITLE
QUERY: `stats.ContinuousDistribution`: adopt different broadcasting rules?

### ISSUE THREAD

**Issue by jorenham** [scipy/scipy#22145]
### Describe your issue.

I noticed several cases of unexpected behaviour in some methods of `ContinuousDistribution` types such as `stats.Normal` and `stats.Uniform`, if initialized with >0-d parameters. To illustrate what I mean, I'll take `.pdf` as an example, but this also applies to (at least) all other `*df` methods in the same way.

```pycon
>>> X = Normal(mu=[0, 1])
>>> X.pdf(-1)
array([0.24197072, 0.05399097])
>>> X.pdf(0)
array([0.39894228, 0.24197072])
```

So with 1-d parameters a) it's valid to pass 0-d input, and b) result in 1-d output. So because of these two observations, I expected that with 1-d parameters and 1-d input, I'd get 2-d output. 

```pycon
>>> X.pdf([-1, 0])
array([0.24197072, 0.24197072])
```

So instead, I again got 1-d output, even though the input is now 1-d instead of 0-d. So I tried again with 2-d input:

```pycon
>>> X.pdf([[-1, 0]])
array([[0.24197072, 0.24197072]])
```

This time, an input shape of `(1, 2)` resulted in an output shape of `(1, 2)`. In the previous case, `(2,)` resulted in `(2,)`, so this isn't more unexpected than the the previous case. 

I tried again, but transposed the input to `(2, 1)`, and expected that I'd see an output shape of `(2, 1)`

```pycon
>>> X.pdf([[-1], [0]])
array([[0.24197072, 0.05399097],
       [0.39894228, 0.24197072]])
```

I'm sure you can see how this can be confusing.

Only after I tried again, but with an input shape of `(3,)`, I realized what was going on:

```pycon
>>> X.pdf([-1, 0, 1])
Traceback (most recent call last):
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/stats/_distribution_infrastructure.py", line 882, in filtered
    shape = np.broadcast_shapes(x.shape, shape)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 474, in broadcast_shapes
    return _broadcast_shape(*arrays)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 419, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-36>", line 1, in <module>
    X.pdf([-1, 0, 1])
    ~~~~~^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/stats/_distribution_infrastructure.py", line 890, in filtered
    raise ValueError(message) from e
ValueError: The argument provided to `Normal.pdf` cannot be be broadcast to the same shape as the distribution parameters.
```

So the reason why I was confused, is because scalars are treated differently than >0-d array-like input:

- a scalar will use different parameters
- a vector will use individual parameters

I'm guessing this is because scalars are first turned into an array of the same shape as the parameters.

I can think of two ways that would result in scalars and arrays being treated equally:

- disallow scalar input unless the parameters are also all scalars (
- array input of shape `s1` given parameters of shape `s2` will output an array of shape `s1 + s2` (or perhaps `s2 + s1`), which already is the case if `s1 == ()`.

Personally, I'd prefer the 2nd option, as I think it would be more practical for users. The first option is also more difficult to statically type.

Either way, the current situation is *very* difficult to properly annotate in `scipy-stubs`, and either of the two options would help with that (although the second would help more than the first).

### Reproducing Code Example

```pycon
>>> from scipy.stats import Normal
>>> X = Normal(mu=[0, 1])
>>> X.pdf(-1)
array([0.24197072, 0.05399097])
>>> X.pdf(0)
array([0.39894228, 0.24197072])
>>> X.pdf([-1, 0])
array([0.24197072, 0.24197072])
>>> X.pdf([[-1, 0]])
array([[0.24197072, 0.24197072]])
>>> X.pdf([[-1], [0]])
array([[0.24197072, 0.05399097],
       [0.39894228, 0.24197072]])
>>> X.pdf([-1, 0, 1])
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/stats/_distribution_infrastructure.py", line 882, in filtered
    shape = np.broadcast_shapes(x.shape, shape)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 474, in broadcast_shapes
    return _broadcast_shape(*arrays)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/numpy/lib/_stride_tricks_impl.py", line 419, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-37>", line 1, in <module>
    X.pdf([-1, 0, 1])
    ~~~~~^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/stats/_distribution_infrastructure.py", line 890, in filtered
    raise ValueError(message) from e
ValueError: The argument provided to `Normal.pdf` cannot be be broadcast to the same shape as the distribution parameters.
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0rc1 2.2.0 sys.version_info(major=3, minor=13, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-fa6gfmf0/overlay/lib/python3.13/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp313-cp313/bin/python
  version: '3.13'
```

**Comment by jorenham** [comment]
ping @mdhaber

**Comment by mdhaber** [comment]
It looks like everything you've shown is working as expected. It is just following normal broadcasting rules.

**Comment by jorenham** [comment]
but then why do those broadcasting rules apply to scalars?

**Comment by mdhaber** [comment]
Here's a test for whether there is something inconsistent: take all your arrays and scalars, and instead of using them to work with the new infrastructure, just add them all up (`+`). The result should have the same shape as the output of pretty much any method of the infrastructure, and it should fail in the same circumstances. For example:
```python3
assert Normal(mu=mu, loc=loc).pdf(x).shape == (mu + loc + x).shape
```
Are you seeing violations of this rule? If this seems unfamiliar, please see https://numpy.org/doc/stable/user/basics.broadcasting.html.

**Comment by jorenham** [comment]
I understand broadcasting, but in this case, I'd expect it to always require a value for each of the parameters, that's all 🤷🏻

**Comment by jorenham** [comment]
Perhaps this helps illustrate my point a bit better

---

Observation:

| params shape 👇🏻, input shape 👉🏻  | `()`    | `(m1,)`      | `(m1, m2)` |
|----------------------------------|---------|--------------|------------|
| `()`                             | `()`    | `(m1,)`      | `(m1, m2)` |
| `(n1,)`                          | `(n1,)` | `...`        | `...`      |

My expectation: 

| params shape 👇🏻, input shape 👉🏻  | `()`    | `(m1,)`      | `(m1, m2)`     |
|----------------------------------|---------|--------------|----------------|
| `()`                             | `()`    | `(m1,)`      | `(m1, m2)`     |
| `(n1,)`                          | `(n1,)` | `(m1, n1)`   | `(m1, m2, n1)` |

Actual outcome:

| params shape 👇🏻, input shape 👉🏻  | `()`    | `(m1,)`      | `(m1, m2)` |
|----------------------------------|---------|--------------|------------|
| `()`                             | `()`    | `(m1,)`      | `(m1, m2)` |
| `(n1,)` | `(n1,)` | `(m1,)` if `m1 == n1` else `ValueError` | `(m1, m2)` if `m1 == n1` else `ValueError` |

**Comment by mdhaber** [comment]
Just replace:
```python3
>>> from scipy.stats import Normal
>>> X = Normal(mu=[0, 1])
```
with
```python3
>>> from scipy.stats import norm
>>> X = norm(loc=[0, 1])
```

I think you'll get the same results. 

Although we are still finding issues with array shape parameters in the old infrastructure(e.g. gh-18919), this was the intended behavior, and it what I would have done anyway: when there's a choice between using standard broadcasting rules and making up new ones, I pick standard broadcasting rules. 

> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
> - they are equal, or
> - one of them is 1.

It sounds like you want to remove rule 2?

> Personally, I'd prefer the 2nd option, as I think it would be more practical for users. 

This is how `np.quantile` and `np.percentile` work, and it means you *can't* do the following: for each slice of an array, calculate a different percentile; instead you always calculate *all* percentiles for *all* slices (Cartesian product). Similar here: if you *want* to compute the `pdf` at a different argument for each element of the shape parameter, you can. You can also do the Cartesian product thing just by making the arrays orthogonal to one another.

**Comment by jorenham** [comment]
> Just replace:
> 
> ```python
> >>> from scipy.stats import Normal
> >>> X = Normal(mu=[0, 1])
> ```
> 
> with
> 
> ```python
> >>> from scipy.stats import norm
> >>> X = norm(loc=[0, 1])
> ```
> 
> I think you'll get the same results.

Yea, that also has the same issue. But at this point it a lot easier to still consider an alternative approach 🤷🏻 

> I pick standard broadcasting rules.

Yes, and technically, that makes a lot of sense. But from a user perspective I think that there are alternatives the could be more intuitive.

**Comment by jorenham** [comment]
> > * one of them is 1.
> 
> When you write " I'd expect it to always require a value for each of the parameters,", it sounds like you want to remove/replace rule 2?

Yea that pretty much describes the first alternative I proposed 👌🏻

**Comment by jorenham** [comment]
> > Personally, I'd prefer the 2nd option, as I think it would be more practical for users.
> 
> This is how `np.quantile` and `np.percentile` work, and it means you _can't_ do the following: for each slice of an array, calculate a different percentile; instead you always calculate _all_ percentiles for _all_ slices (Cartesian product).

Exactly; so it's pretty similar to how `ufunc.outer` works I believe.

**Comment by jorenham** [comment]
Another way of looking at option nr 2, is by considering `X.pdf` as a black-box function that's vectorized.

**Comment by mdhaber** [comment]
Well, it's something we can consider. Would you bring it up with NumPy and the other array libraries first? When they switch, I'd be happy to.

**Comment by jorenham** [comment]
> Well, it's something we can consider. Would you bring it up with NumPy and the other array libraries first? When they switch, I'd be happy to.

Oh but I'm not saying we should consider changing broadcasting as a whole; I'm just talking about your shiny new distribution infrastructure

**Comment by jorenham** [comment]
> Another way of looking at option nr 2, is by considering `X.pdf` as a black-box function that's vectorized.

I can imagine that this could be beneficial for performance as well, because it seems easier to parallelize this way.

**Comment by WarrenWeckesser** [comment]
Standard broadcasting is, well, the standard and well-understood method for operating on multiple numpy arrays.  I don't see why we would use something else.  Anyone who uses numpy arrays beyond the "hello world" stage will learn at least the basics of broadcasting, so I don't think it should cause any confusion except perhaps for the absolute beginner.

> vectorization instead of broadcasting

Broadcasting is a form of vectorization, so I'm not sure what to make of that.

**Comment by jorenham** [comment]
> Broadcasting is a form of vectorization, so I'm not sure what to make of that.

My point is that I think it's more intuitive if e.g. `X.pdf` can always be considered as a black-box function, that for `m`-d input returns `(m+n)`-d output, and always places the `n` "parametric" dimensions on the last (or first) axes.

**Comment by jorenham** [comment]
GUFunc semenatics &mdash; that's the description I was looking for

**Comment by mdhaber** [comment]
@jorenham shall we close this since we've already released with standard broadcasting rules? If you want to restrict the interface in this way, it seems as simple as wrapping the class to make method arguments orthogonal to the broadcasted shape of the distribution parameters, e.g.
```
# X is the random variable
x = np.reshape(x, x.shape + X._ndim*(1,))
```
That way, the net shape is just the concatenated shape of the argument and parameters, and you'll always compute for the Cartesian product of the two without the possibility of being more selective.

**Comment by jorenham** [comment]
> @jorenham shall we close this since we've already released with standard broadcasting rules? 

I agree that it's too late to replace the broadcasting behaviour with my proposal at this point.

So how about instead making it configurable? For example when instantiating `Normal` with >0-d there's a property (and maybe a corresponding kwarg) `broadcasting` that can be either `"default"` (the default) or `"vectorized"` (for GUFunc-like behaviour). 
This way, 3rd party libs could then do `X.broadcasting = "vectorized"` within a function `f(X: ContinuousDIstribution)` so that things like `X.icdf(np.linspace(0, 1))` will also work for >0-d parameters.

**Comment by jorenham** [comment]
> @jorenham shall we close this since we've already released with standard broadcasting rules? If you want to restrict the interface in this way, it seems as simple as wrapping the class to make method arguments orthogonal to the broadcasted shape of the distribution parameters, e.g.
> 
> ```
> # X is the random variable
> x = np.reshape(x, x.shape + X._ndim*(1,))
> ```
> 
> That way, the net shape is just the concatenated shape of the argument and parameters, and you'll always compute for the Cartesian product of the two without the possibility of being more selective.

Is there a way to do this by only using the documented public API? Because if not, then there probably should be, e.g. by adding a public `ndim` property or something 🤔.

**Comment by mdhaber** [comment]
I've thought many times about making `ndim` and `shape` public, for sure. But it's very easy to make them public at any time, and quite difficult to retract that if we do, so I left them private in the initial release and have waited for it to be requested. One could have requested the same thing for frozen distributions any time in the past few decades, and to my knowledge it didn't come up, so not a huge omission. But if you're asking, that is more likely to happen than adopting nonstandard broadcasting rules : )
