### ISSUE TITLE
DOC: stats: 5 build warnings locally

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#22178]
### Issue with current documentation:

```
reading sources... [100%] tutorial/stats/continuous_loguniform .. tutorial/thread_safety
/Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/build-install/lib/python3.11/site-packages/scipy/stats/__init__.py:docstring of scipy.stats:47: WARNING: autosummary: stub file not found 'scipy.stats.uniform'. Check your autosummary_generate setting.
/Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/build-install/lib/python3.11/site-packages/scipy/signal/_ltisys.py:docstring of scipy.signal._ltisys.place_poles:127: WARNING: Exception occurred in plotting scipy-signal-place_poles-1
 from /Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/doc/source/reference/generated/scipy.signal.place_poles.rst:
Traceback (most recent call last):
  File "/Users/lucascolley/programming/pixi-dev-scipystack/scipy/.pixi/envs/doc/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 46, in <module>
  File "<__array_function__ internals>", line 200, in det
  File "/Users/lucascolley/programming/pixi-dev-scipystack/scipy/.pixi/envs/doc/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 2139, in det
    r = _umath_linalg.det(a, signature=signature)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: divide by zero encountered in det
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... 
copying static files... done
copying extra files... done
copying assets: done
/Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/build-install/lib/python3.11/site-packages/scipy/stats/__init__.py:docstring of scipy.stats:479:<autosummary>:1: WARNING: py:obj reference target not found: scipy.stats.Uniform
/Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/doc/source/release/1.15.0-notes.rst:254: WARNING: py:obj reference target not found: scipy.stats.Uniform
/Users/lucascolley/programming/pixi-dev-scipystack/scipy/scipy/doc/source/release/1.15.0-notes.rst:260: WARNING: py:obj reference target not found: scipy.stats.Uniform
```

**Comment by tylerjereddy** [comment]
Yeah, I mentioned some of these warnings at https://github.com/scipy/scipy/pull/22150, but ignored them since they weren't blocking CI.

**Comment by mdhaber** [comment]
Huh. I can't tell what the difference is that would cause this for `Uniform` but not `Normal`. @melissawm is this something you could help with while we're working on stats documentation?

**Comment by melissawm** [comment]
I actually can't see these failures locally, but building with Python 3.12 I get other warnings:

```
/home/melissa/projects/scipy/build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py:docstring of scipy.optimize.OptimizeResult.update:1: WARNING: py:class reference target not found: None.  Update D from mapping/iterable E and F.

/home/melissa/projects/scipy/build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py:docstring of scipy.optimize.RootResults.update:1: WARNING: py:class reference target not found: None.  Update D from mapping/iterable E and F.
/home/melissa/projects/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/_dok.py:docstring of scipy.sparse._dok._dok_base.update:1: WARNING: py:class reference target not found: None.  Update D from mapping/iterable E and F.
/home/melissa/projects/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/_dok.py:docstring of scipy.sparse._dok._dok_base.update:1: WARNING: py:class reference target not found: None.  Update D from mapping/iterable E and F.
```

These seem to be coming from the `update` method from dict objects (that then get injected into `_RichResult` so I'm not really sure what could be done about them.

**Comment by melissawm** [comment]
I wonder what is moving here - it seems we are all using the same sphinx version as CI, but some other packages maybe are being updated in the meantime? I am guessing we should pin something but not sure what.

**Comment by lucascolley** [comment]
I believe the warnings I posted were generated with `pixi run doc` via https://github.com/rgommers/pixi-dev-scipystack, so they should be reproducible (albeit with a bit of work). I may be misremembering, though.

**Comment by karthik-ganti-2025** [comment]
Hi guys, I can try owning this issue. If I'm understanding the thread so far correctly, first step is to reproduce the warnings @lucascolley generated by running scipy.stats and scipy.signal within pixi on Python 3.11? Which version of (pixi, scipy, python) should I use for this (if it matters)?

To start off on my own, I can try latest version of pixi with the instructions at this [readme](https://github.com/rgommers/pixi-dev-scipystack/blob/main/README.md) for generating a scipy 1.15 / Python 3.12 version.

It also sounds like all the other pinned issues (as duplicates or where this one was mentioned) are all scenarios where the divide by zero warning was reproduced.

**Comment by lucascolley** [comment]
Hi @karthik-ganti-2025, yes, that would be great. If you use the `main` branch of both `scipy` and `pixi-dev-scipystack`, everything else should be handled by Pixi. Let us know if you can reproduce the warnings! Some may have been fixed by now.

**Comment by karthik-ganti-2025** [comment]
I'm not actually able to use latest pixi-dev-scipystack and latest python installation (with scipy installed per [https://github.com/rgommers/pixi-dev-scipystack/tree/main#](https://github.com/rgommers/pixi-dev-scipystack/tree/main#) to get the pixi.lock and pixi.toml files in the right place) with pixi on my machine.

I got the following warning when I tried initializing with `pixi shell`.

```
(scipy_dev) ... % pixi shell
 WARN Not installing dependency on current platform: (osx-64) as it is not part of this project's supported platforms.
```

Any recommendation of installation I should use? Maybe python 3.11 with scipy and pixi-dev-scipystack set up configured to work with them - or some way I can work around this to get `pixi run doc` to work?

**Comment by karthik-ganti-2025** [comment]
As an update, I just peeked into the pixi.toml file. Unfortunately, my MacBook Air is like 6 years old - before the M series chips came out. I could try running this in a Linux VM though unless there's a simpler solution that avoids all of that.

**Comment by lucascolley** [comment]
@karthik-ganti-2025 you should be able to edit the pixi.toml to add `osx-64` under `platforms`, and I think it should work.

**Comment by karthik-ganti-2025** [comment]
OK, I did that and then ran `pixi run doc`. Summary of build was 4 warnings, 1 error.
1. /pixi-dev-scipystack/scipy/scipy/build-install/usr/lib/python3.12/site-packages/scipy/stats/__init__.py:docstring of scipy.stats:47: WARNING: autosummary: stub file not found 'scipy.stats.uniform'. Check your autosummary_generate setting.
2. pixi-dev-scipystack/scipy/scipy/build-install/usr/lib/python3.12/site-packages/scipy/stats/__init__.py:docstring of scipy.stats:480:<autosummary>:1: WARNING: py:obj reference target not found: scipy.stats.Uniform
3. pixi-dev-scipystack/scipy/scipy/doc/source/release/1.15.0-notes.rst:260: WARNING: py:obj reference target not found: scipy.stats.Uniform
4. pixi-dev-scipystack/scipy/scipy/doc/source/release/1.15.0-notes.rst:266: WARNING: py:obj reference target not found: scipy.stats.Uniform

Just by looking at the warnings, everything seems to have to do with a scipy.stats.uniform file not being generated during the build. I'll see if I can find what was supposed to create the file (I've been given a helpful autosummary_generate' setting to debug as well).

**Comment by karthik-ganti-2025** [comment]
OK, I'm unable to find anything wrong with the /scipy/scipy/scipy/stats/__init__.py side of things.
I can confirm though the warnings in 3 and 4. scipy.stats.Uniform's link doesn't load. It's not clear where the issue causing that is. My main method of troubleshooting right now is to compare how scipy.stats.Normal loads fine while scipy.stats.Uniform doesn't, even though they come from the same ultimate source.

I'll see if I can get it to load by deleting 'invisible whitespace' in the toctree of the /scipy/scipy/scipy/stats/__init__.py or something like that. I can't see anything obviously wrong with the .rst file in doc/source/release/1.15.0-notes.rst for scipy.stats.Uniform as compared to scipy.stats.Normal.

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/ac7bc13c-d7fa-4621-8b9b-ad8ef869a021" />

**Comment by karthik-ganti-2025** [comment]
OK, I'm unable to find anything wrong with the /scipy/scipy/scipy/stats/_ _ init_ _.py side of things.
I can confirm though the warnings in 3 and 4. scipy.stats.Uniform's link doesn't load. It's not clear where the issue causing that is. My main method of troubleshooting right now is to compare how scipy.stats.Normal loads fine while scipy.stats.Uniform doesn't, even though they come from the same ultimate source.

I'll see if I can get it to load by deleting 'invisible whitespace' in the toctree of the /scipy/scipy/scipy/stats/_ _ init_ _.py or something like that. I can't see anything obviously wrong with the .rst file in doc/source/release/1.15.0-notes.rst for scipy.stats.Uniform as compared to scipy.stats.Normal.

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/ac7bc13c-d7fa-4621-8b9b-ad8ef869a021" />

**Comment by mdhaber** [comment]
Whatever is happening will probably change with https://github.com/scipy/scipy/pull/22836. Might want to take a look at that and possibly let that merge before going too deep.

**Comment by karthik-ganti-2025** [comment]
Sounds good, will wait.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by melissawm** [comment]
I have a weird update: I am seeing the error with scipy.stats.Uniform too, but only on a Mac. On Linux, the docs build fine. You are right @mdhaber that I can probably tackle that with #22836 and I'm looking into it right now.

**Comment by mdhaber** [comment]
Oops, I didn't mean to volunteer you @melissawm - I just figured that *something* would change with gh-22836, so it might be worth waiting for that to merge first. But if you think you can look into this, too, great!
