### ISSUE TITLE
Slsqp related failure in statsmodels for Bento build

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#2604]
Statsmodels current master shows 9 failures when building scipy master (any commit in May/June '13) with Bento instead of distutils. Failures seems to be caused by `optimize.slsqp`. Likely related to different Fortran compile args.

Example failure (others also in L1-norm optimization tests):

```
======================================================================
FAIL: statsmodels.discrete.tests.test_discrete.TestProbitL1.test_params
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rgommers/Code/statsmodels/statsmodels/discrete/tests/test_discrete.py", line 378, in test_params
    assert_almost_equal(self.res1.params, self.res2.params, DECIMAL_4)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 452, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 812, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

(mismatch 75.0%)
 x: array([ 0.,  0.,  0.,  0.])
 y: array([-5.40476992,  1.25018458,  0.04744558,  0.        ])
```

**Comment by rgommers** [comment]
Bento related, which we removed - closing
