### ISSUE TITLE
Test failure ``test_matfuncs.TestFractionalMatrixPower``

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#2763]
Fails both with numpy 1.5.1 and numpy master, on 32-bit Linux. Not clear to me if this test is useful or not.

```
===========================================================
FAIL: test_singular (test_matfuncs.TestFractionalMatrixPower)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/Code/scipy/scipy/linalg/tests/test_matfuncs.py", line 531, in test_singular
    assert_(np.isnan(A_power).all())
  File "/home/rgommers/Code/numpy/numpy/testing/utils.py", line 44, in assert_
    raise AssertionError(msg)
AssertionError


(Pdb) fractional_matrix_power(A, p)
array([[ -2.31426182e+11+0.j,   7.71420608e+10+0.j],
       [  1.15713091e+11+0.j,  -3.85710304e+10+0.j]])
(Pdb) print(p)
-0.7
```

**Comment by sethtroisi** [comment]
Bug asks if this test is valid to be failing, an answer was reached (it's not valid) and the test is marked as knownfail with valid reason. No reason to keep this bug open for another 7 years.
