### ISSUE TITLE
scipy.signal.dlsim returns error if number of timesteps in input is less than number of inputs

### ISSUE THREAD

**Issue by RJSSimpson** [scipy/scipy#2853]
The problem is an error in the statement

    if t is None:
            out_samples = max(u.shape)

Which results in this behaviour:

    # Define system
    A=np.array([[1]])
    B=np.array([[1,1,1]])
    C=np.array([[1]])
    D=np.array([[0,0,0]])
    dt = 1.0
    
    # Define input
    U=np.array([[0,0,0],
                [0,0,0]]) # Input tensor with 2 timesteps.
    
    dlsim((A,B,C,D,dt),U)

Traceback (most recent call last):
  File "/home/rjs10/git/SHARPy/src/PyCoupled/Coupled_LinDynamic.py", line 61, in <module>
    dlsim((A,B,C,D,dt),U)
  File "/usr/local/lib/python3.2/dist-packages/scipy/signal/dltisys.py", line 118, in dlsim
    np.dot(d, u_dt[out_samples-1,:])
IndexError: invalid index

The statement should be

    if t is None:
            out_samples = u.shape[0]

Easy fix.

**Comment by e-q** [comment]
As far as I can tell, this is fixed by gh-3741
