### ISSUE TITLE
SciPy Weave File Handling is not Batch Safe [Possible Race Condition?]

### ISSUE THREAD

**Issue by spgarbet** [scipy/scipy#2902]
I'm running a 1000 jobs on a cluster using SciPy using the integrator. SciPy to accomplish this creates temporary files and a shared NAS. It fails in an interesting way when several batches start at the same time, which forces me to keep restarting batches.

I think the directory doesn't exist, and then it does because another job gets in a race condition with the tmp directory creation. A couple possible solutions exist, i.e. one could append the process id to the filename, or trap and ignore the exception (assuming this doesn't cause other issues)

Traceback (most recent call last):
  File "varsens/compute_objective.py", line 29, in <module>
    reference = odesolve(model, t)
  File "/home/garbetsp/.local/lib/python2.7/site-packages/pysb/integrate.py", line 328, in odesolve
    solver = Solver(model, tspan, integrator, **integrator_options)
  File "/home/garbetsp/.local/lib/python2.7/site-packages/pysb/integrate.py", line 97, in __init__
    Solver._test_inline()
  File "/home/garbetsp/.local/lib/python2.7/site-packages/pysb/integrate.py", line 79, in _test_inline
    inline('int i;', force=1)
  File "/home/garbetsp/.local/lib/python2.7/site-packages/scipy/weave/inline_tools.py", line 318, in inline
    **kw)
  File "/home/garbetsp/.local/lib/python2.7/site-packages/scipy/weave/inline_tools.py", line 484, in compile_function
    verbose=verbose, **kw)
  File "/home/garbetsp/.local/lib/python2.7/site-packages/scipy/weave/ext_tools.py", line 365, in compile
    temp = catalog.intermediate_dir()
  File "/home/garbetsp/.local/lib/python2.7/site-packages/scipy/weave/catalog.py", line 220, in intermediate_dir
    os.makedirs(path, mode=0o700)
  File "/usr/local/python2/2.7.4/x86_64/gcc46/nonet/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/garbetsp/python27_intermediate'

**Comment by person142** [comment]
Closing since weave is no longer a part of SciPy. This issue is now tracked at https://github.com/scipy/weave/issues/7.
