### ISSUE TITLE
FAIL: test_qhull.TestUtilities.test_more_barycentric_transforms

### ISSUE THREAD

**Issue by opoplawski** [scipy/scipy#2997]
I'm seeing this on Fedora Rawhide i386 only with numpy 1.8.0rc2 and scipy 0.13.0rc1:
````
FAIL: test_qhull.TestUtilities.test_more_barycentric_transforms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/builddir/build/BUILDROOT/scipy-0.13.0-0.4.rc1.fc21.i386/usr/lib/python2.7/site-packages/scipy/spatial/tests/test_qhull.py", line 354, in test_more_barycentric_transforms
    unit_cube_tol=1e7*eps)
  File "/builddir/build/BUILDROOT/scipy-0.13.0-0.4.rc1.fc21.i386/usr/lib/python2.7/site-packages/scipy/spatial/tests/test_qhull.py", line 279, in _check_barycentric_transforms
    assert_(ok.all(), "%s %s" % (err_msg, np.where(~ok)))
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 44, in assert_
    raise AssertionError(msg)
AssertionError: ndim=4 (array([10627]),)
````

**Comment by rgommers** [comment]
This one has passed my annoyance threshold; fix in gh-5605.
