### ISSUE TITLE
Failure to import scipy.integrate in 0.13.2 and HEAD -- ATLAS link missing?

### ISSUE THREAD

**Issue by dstndstn** [scipy/scipy#3265]
Hi,

In scipy 0.13.2 and HEAD I am getting:

```
$ python -c "import scipy.integrate; print scipy.__file__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scipy/integrate/__init__.py", line 52, in <module>
    from .odepack import *
  File "scipy/integrate/odepack.py", line 6, in <module>
    from . import _odepack
ImportError: scipy/integrate/_odepack.so: undefined symbol: ATL_dcopy
```

This is on ubuntu 12.10, python 2.7.3, numpy 1.8.0.

I'm still digging into this, but it looks like the odepack link command is:

```
/usr/bin/gfortran -Wall -Wall -shared build/temp.linux-x86_64-2.7/scipy/integrate/_odepackmodule.o -L/usr/local/lib -L/usr/lib/atlas-base -Lbuild/temp.linux-x86_64-2.7 -lodepack -llinpack_lite -lmach -latlas -lptf77blas -lptcblas -lgfortran -o build/lib.linux-x86_64-2.7/scipy/integrate/_odepack.so
```

And:

```
$ nm -D build/lib.linux-x86_64-2.7/scipy/integrate/_odepack.so | grep ATL_dcopy
                 U ATL_dcopy
$ ldd build/lib.linux-x86_64-2.7/scipy/integrate/_odepack.so
    linux-vdso.so.1 =>  (0x00007fff1eba3000)
    libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f3c44f91000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3c44c95000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3c44a7e000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c446be000)
    libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f3c44488000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f3c45500000)
```

Ideas?

**Comment by rgommers** [comment]
no update or new reports in 5 years, so closing this.
