### ISSUE TITLE
SciPy 0.13.3 - CentOS5 - Errors in test_arpack

### ISSUE THREAD

**Issue by wcardoen** [scipy/scipy#3568]
Hello,

I compiled scipy 0.13.3 succesfully on my CentOS laptop on which I run the following kernel:
2.6.32-431.11.2.el6.x86_64 

I have a two core proc (0,1) of the following type:
>> more /proc/cpuinfo
processor       : 0               
vendor_id       : GenuineIntel    
cpu family      : 6               
model           : 23              
model name      : Intel(R) Core(TM)2 Duo CPU     U9600  @ 1.60GHz
stepping        : 10                                             
cpu MHz         : 800.000                                        
cache size      : 3072 KB                                        
physical id     : 0                                              
siblings        : 2                                              
core id         : 0                                              
cpu cores       : 2                                              
apicid          : 0                                              
initial apicid  : 0                                              
fpu             : yes                                            
fpu_exception   : yes                                            
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm const
ant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm ida dts tpr_shadow vnmi
 flexpriority
bogomips        : 3192.04
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
....
(I omitted the second core)

I used the gcc and gfortran to compile the scipy code
gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

In order to compile scipy I compiled the following packages from source:
 a.OpenBlas 0.2.8 (single threaded) (blas, lapack)
 b.SuiteSparse suite (amd,umfpack) using the OpenBlas libraries 
 c. numpy, nose and setuptools 
with the same gcc/gfortran compilers.
I ran the full numpy test suite successfully.
python3 -c "import numpy; numpy.test(label='full',verbose=10)"  >&  np_test.out
tail -9 np_test.out

--------------------------------------------------------------------------------------------------------
Ran 5334 tests in 614.631s

OK (KNOWNFAIL=6, SKIP=3)
Running unit tests for numpy
NumPy version 1.8.1
NumPy is installed in /software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy
Python version 3.3.5 (default, Apr 22 2014, 13:31:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
nose version 1.3.1
----------------------------------------------------------------------------------------------------------

Besides the Arpack errors I also got three other errors (The errors can be found below)
Please let me know if you need more info.

Thanks in advance,

Wim
======================================================================
FAIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LM', None, 0.1, <function asarray at 0x7f7bdbc64f80>, 'r')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/nose-1.3.1-py3.3.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.000357628, atol=0.000357628
error for eigs:standard, typ=f, which=LM, sigma=0.1, mattype=asarray, OPpart=r, mode=normal
(mismatch 100.0%)
 x: array([[-0.11649324+0.j, -0.05435310+0.j],
       [ 0.13801208+0.j, -0.05894032+0.j],
       [-0.21229853+0.j, -0.02815625+0.j],...
 y: array([[-0.05698580+0.08018474j, -0.05435318+0.j        ],
       [ 0.06439485-0.09061003j, -0.05894023+0.j        ],
       [-0.12503998+0.17594382j, -0.02815617+0.j        ],...

======================================================================
AIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, None, <function aslinearoperator at 0x7f7bcf0c1170>, None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/nose-1.3.1-py3.3.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.00178814, atol=0.000357628
error for eigs:standard, typ=f, which=LR, sigma=None, mattype=aslinearoperator, OPpart=None, mode=normal
(mismatch 100.0%)
 x: array([[ 0.13884316+0.j, -1.07112074+0.j],
       [-0.08962911+0.j, -1.39801252+0.j],
       [ 0.21701422+0.j, -0.93968379+0.j],...
 y: array([[ 0.06020537+0.08471544j, -1.07112110+0.j        ],
       [-0.07497437-0.10549703j, -1.39801240+0.j        ],
       [ 0.13326693+0.18752094j, -0.93968397+0.j        ],...

======================================================================
FAIL: test_basic.test_xlogy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/nose-1.3.1-py3.3.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/special/tests/test_basic.py", line 2736, in test_xlogy
    assert_func_equal(special.xlogy, w2, z2, rtol=1e-13, atol=1e-13)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/special/_testutils.py", line 87, in assert_func_equal
    fdata.check()
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/special/_testutils.py", line 292, in check
    assert_(False, "\n".join(msg))
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 44, in assert_
    raise AssertionError(msg)
AssertionError:
Max |adiff|: 712.209
Max |rdiff|: 1027.5
Bad results (3 out of 6) for the following points (in output 0):
                            0j                        (nan+0j) =>                        (-0+0j) !=                     (nan+nanj)  (rdiff                            0.0)
                        (1+0j)                          (2+0j) => (-711.5156069932148+0.7853981633976757j) !=        (0.6931471805599453+0j)  (rdiff             1027.5006624894627)
                        (1+0j)                              1j => (-711.5156069932148+0.7853981633976757j) !=            1.5707963267948966j  (rdiff              452.9651797194877)

======================================================================
FAIL: test_lambertw.test_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/nose-1.3.1-py3.3.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/special/tests/test_lambertw.py", line 21, in test_values
    assert_equal(lambertw(inf,1).real, inf)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 304, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: nan
 DESIRED: inf

======================================================================
FAIL: test_lambertw.test_ufunc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 581, in chk_same_position
    assert_array_equal(x_id, y_id)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 66.66666666666666%)
 x: array([False,  True,  True], dtype=bool)
 y: array([False, False, False], dtype=bool)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/nose-1.3.1-py3.3.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy/special/tests/test_lambertw.py", line 93, in test_ufunc
    lambertw(r_[0., e, 1.]), r_[0., 1., 0.567143290409783873])
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 811, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 607, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "/software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy/testing/utils.py", line 587, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

x and y nan location mismatch:
 x: array([  0.+0.j,  nan+0.j,  nan+0.j])
 y: array([ 0.   ,  1.   ,  0.567])

----------------------------------------------------------------------
Ran 9532 tests in 698.956s

FAILED (KNOWNFAIL=130, SKIP=324, failures=5)
Running unit tests for scipy
NumPy version 1.8.1
NumPy is installed in /software/pkg/python/3.3.5/lib/python3.3/site-packages/numpy
SciPy version 0.13.3
SciPy is installed in /software/pkg/python/3.3.5/lib/python3.3/site-packages/scipy
Python version 3.3.5 (default, Apr 22 2014, 13:31:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
nose version 1.3.1

**Comment by pv** [comment]
Probably fixed by gh-6074
