### ISSUE TITLE
scipy.io.netcdf: " 'netcdf_file' object has no attribute 'fp' " when using deepcopy

### ISSUE THREAD

**Issue by Khris777** [scipy/scipy#3690]
Hi.
I suddenly get this error when trying to use deepcopy on a netcdf object. I've been using deepcopy with netcdf files for a long time now and it always worked fine. Now I suddenly get this error.

Example code:

```
import scipy.io.netcdf as cdf
import copy

f = cdf.netcdf_file('somefile.nc','r')
fc = copy.deepcopy(f)
```

This leads to this error:

```
Traceceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: Required argument 'fileno' (pos 1) not found
```

Trying to access fc after this error then leads to:

```
Exception AttributeError: "'netcdf_file' object has no attribute 'fp'" in <bound method netcdf_file.close of <scipy.io.netcdf.netcdf_file object at 0x2bec950>> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fc' is not defined
```

**Comment by mckib2** [comment]
Current exception is:
```
TypeError: cannot pickle '_io.BufferedReader' object
```
This seems like a reasonable limitation as file handles are usually hard to serialize.  Propose closing as `won't fix`?

**Comment by rgommers** [comment]
agreed
