### ISSUE TITLE
scipy.interpolate.UnivariateSpline segfault

### ISSUE THREAD

**Issue by dalessan** [scipy/scipy#3691]
Hi!

With the current version of scipy (0.14.0), I experience a segfault when I try to execute the following code:

``` python
from scipy import interpolate

x = range(109)
y = [  0. ,   0. ,   0. ,   0. ,   0. ,  10.9,   0. ,  11. ,   0. ,
         0. ,   0. ,  10.9,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
        10.9,   0. ,   0. ,   0. ,  11. ,   0. ,   0. ,   0. ,  10.9,
         0. ,   0. ,   0. ,  10.5,   0. ,   0. ,   0. ,  10.7,   0. ,
         0. ,   0. ,  11. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
        10.9,   0. ,   0. ,  10.7,   0. ,   0. ,   0. ,  10.6,   0. ,
         0. ,   0. ,  10.5,   0. ,   0. ,  10.7,   0. ,   0. ,  10.5,
         0. ,   0. ,  11.5,   0. ,   0. ,   0. ,  10.7,   0. ,   0. ,
        10.7,   0. ,   0. ,  10.9,   0. ,   0. ,  10.8,   0. ,   0. ,
         0. ,  10.7,   0. ,   0. ,  10.6,   0. ,   0. ,   0. ,  10.4,
         0. ,   0. ,  10.6,   0. ,   0. ,  10.5,   0. ,   0. ,   0. ,
        10.7,   0. ,   0. ,   0. ,  10.4,   0. ,   0. ,   0. ,  10.8,   0. ]
interpolate.UnivariateSpline(x, y, k=1)
```

The following is the backtrace produced by gdb:

```
Program received signal SIGBUS, Bus error.
0x00007ffff0fc4334 in fpknot_ () from /home/daniele/Development/telecom/scipy/test/local/lib/python2.7/site-packages/scipy/interpolate/dfitpack.so
(gdb) bt
#0  0x00007ffff0fc4334 in fpknot_ () from /home/daniele/Development/telecom/scipy/test/local/lib/python2.7/site-packages/scipy/interpolate/dfitpack.so
#1  0x00007ffff0fb8781 in fpcurf_ () from /home/daniele/Development/telecom/scipy/test/local/lib/python2.7/site-packages/scipy/interpolate/dfitpack.so
#2  0x00007ffff0fa4428 in f2py_rout_dfitpack_fpcurf1 (capi_self=<optimized out>, capi_args=<optimized out>, capi_keywds=<optimized out>, f2py_func=0x7ffff0fb6b00 <fpcurf_>)
    at build/src.linux-x86_64-2.7/scipy/interpolate/src/dfitpackmodule.c:2701
#3  0x0000000000562fe1 in PyEval_EvalFrameEx ()
#4  0x000000000054b7d4 in PyEval_EvalCodeEx ()
#5  0x00000000005614dd in PyEval_EvalFrameEx ()
#6  0x0000000000556cea in ?? ()
#7  0x00000000004b5164 in ?? ()
#8  0x000000000050704c in ?? ()
#9  0x00000000005336db in ?? ()
#10 0x0000000000561669 in PyEval_EvalFrameEx ()
#11 0x000000000054b7d4 in PyEval_EvalCodeEx ()
#12 0x000000000055830c in ?? ()
#13 0x00000000004683a0 in PyRun_InteractiveOneFlags ()
#14 0x00000000004684bc in PyRun_InteractiveLoopFlags ()
#15 0x0000000000468b71 in PyRun_AnyFileExFlags ()
#16 0x000000000046a1e3 in Py_Main ()
#17 0x00007ffff7816de5 in __libc_start_main (main=0x46a2a1 <main>, argc=1, ubp_av=0x7fffffffdd98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd88) at libc-start.c:260
#18 0x00000000005735fe in _start ()
```

I'm using Ubuntu 13.10 (64-bit version) and Python 2.7. I've installed the latest version of Scipy and Numpy using pip.

Let me know if you need additional information.

Cheers.

**Comment by AtsushiSakai** [comment]
This issue still exists now.

System error message is:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fca181c5020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [24301]

VM Regions Near 0x7fca181c5020:
    MALLOC_SMALL             7fc9c6000000-7fc9c6800000 [ 8192K] rw-/rwx SM=PRV  
--> 
    STACK GUARD              7ffeea7fd000-7ffeea7fe000 [    4K] ---/rwx SM=NUL  stack guard for thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dfitpack.cpython-39-darwin.so 	0x0000000114c17e93 fpknot_ + 1443
1   dfitpack.cpython-39-darwin.so 	0x0000000114c06f8c fpcurf_ + 5196
2   dfitpack.cpython-39-darwin.so 	0x0000000114c06f8c fpcurf_ + 5196
3   dfitpack.cpython-39-darwin.so 	0x0000000114c06f8c fpcurf_ + 5196
4   dfitpack.cpython-39-darwin.so 	0x0000000114c06f8c fpcurf_ + 5196
5   dfitpack.cpython-39-darwin.so 	0x0000000114c06f8c fpcurf_ + 5196
```

My environment is: 
1.6.0 1.20.0 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)

**Comment by nkaretnikov** [comment]
fixed in https://github.com/scipy/scipy/pull/16288, lmk what you think
