### ISSUE TITLE
wrap_function seems not to be working when wrapper_args is a one element list

### ISSUE THREAD

**Issue by gbakalian** [scipy/scipy#3816]
optimize.optimize.py line 274-283

```
x0
Out[179]: array([-1800.])

[d]
Out[180]: [Timestamp('2014-07-23 00:00:00+0200', tz='Europe/Berlin')]

optimal_flows = (opt.fmin_slsqp(func=objective_function, x0=x0,
     ...:                  f_ieqcons=f_ieqcons, bounds=bounds, args=[d],
     ...:                  iter=iter, iprint=0, full_output=False, epsilon=100))
Traceback (most recent call last):

  File "<ipython-input-181-5ade67dafaf1>", line 3, in <module>
    iter=iter, iprint=0, full_output=False, epsilon=100))

  File "C:\Users\uk40291\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\optimize\slsqp.py", line 200, in fmin_slsqp
    constraints=cons, **opts)

  File "C:\Users\uk40291\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\optimize\slsqp.py", line 354, in _minimize_slsqp
    fx = func(x)

  File "C:\Users\uk40291\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\optimize\optimize.py", line 281, in function_wrapper
    return function(*(wrapper_args + args))

TypeError: can only concatenate tuple (not "list") to tuple


debug
> c:\users\uk40291\appdata\local\continuum\anaconda\lib\site-packages\scipy\optimize\optimize.py(281)function_wrapper()
280         ncalls[0] += 1
```

--> 281         return function(*(wrapper_args + args))
    282 

```
ipdb> wrapper_args
(array([-1800.]),)

ipdb> print args
[Timestamp('2014-07-23 00:00:00+0200', tz='Europe/Berlin')]

ipdb> exit
```

**Comment by ilayn** [comment]
Not quite sure what is needed here or if it is really that simple but I can add this in #22524 but I need someone to confirm the fix

**Comment by andyfaff** [comment]
Closing as won't fix. Please see https://github.com/scipy/scipy/pull/22652 for further details on the decision.
