### ISSUE TITLE
New test error against numpy 1.10-devel 

### ISSUE THREAD

**Issue by charris** [scipy/scipy#4361]
```
ERROR: test_diric_broadcasting (test_basic.TestCephes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/special/tests/test_basic.py", line 251, in test_diric_broadcasting
    assert_(special.diric(x[:, np.newaxis], n).shape == (x.size, n.size))
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/special/basic.py", line 100, in diric
    x /= 2.0
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/4352
