### ISSUE TITLE
Failures with MKL

### ISSUE THREAD

**Issue by ziyuang** [scipy/scipy#4387]
Here are the error messages from `scipy.test()` of bcdb9a85 with Intel MKL/icc/ifort. The numpy version is 1.9.1, also compiled by Intel C++ with MKL

    ======================================================================
    FAIL: test_lorentz (test_odr.TestODR)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/scipy/odr/tests/test_odr.py", line 293, in test_lorentz
        3.7798193600109009e+00]),
      File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
        precision=decimal)
      File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
        raise AssertionError(msg)
    AssertionError:
    Arrays are not almost equal to 6 decimals
    
    (mismatch 100.0%)
     x: array([  1.000000e+03,   1.000000e-01,   3.800000e+00])
     y: array([  1.430678e+03,   1.339051e-01,   3.779819e+00])
    
    ======================================================================
    FAIL: test_multi (test_odr.TestODR)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/scipy/odr/tests/test_odr.py", line 190, in test_multi
        0.5101147161764654, 0.5173902330489161]),
      File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
        precision=decimal)
      File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
        raise AssertionError(msg)
    AssertionError:
    Arrays are not almost equal to 6 decimals
    
    (mismatch 100.0%)
     x: array([ 4. ,  2. ,  7. ,  0.4,  0.5])
     y: array([ 4.379988,  2.433306,  8.002885,  0.510115,  0.51739 ])
        
        ======================================================================
        FAIL: test_pearson (test_odr.TestODR)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/scipy/odr/tests/test_odr.py", line 236, in test_pearson
            np.array([5.4767400299231674, -0.4796082367610305]),
          File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
            precision=decimal)
          File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
            raise AssertionError(msg)
        AssertionError:
        Arrays are not almost equal to 6 decimals
        
        (mismatch 100.0%)
         x: array([ 1.,  1.])
         y: array([ 5.47674 , -0.479608])
        
        ----------------------------------------------------------------------
        Ran 17160 tests in 179.551s
        
        FAILED (KNOWNFAIL=96, SKIP=1205, failures=3)

**Comment by ziyuang** [comment]
See #3340
