### ISSUE TITLE
FAIL: test_syr_her (test_blas.TestFBLAS2Simple) on Windows python2.7.9 32 bit scipy0.15.0 numpy0.19.1

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#4410]
remark : zero failure on python3.4.2 32/64bit and python2.7.9 64 bit windows
````
Running unit tests for scipy
NumPy version 1.9.1
NumPy is installed in D:\result_tests\WinPython-32bit-2.7.9.2\python-2.7.9\lib\site-packages\numpy
SciPy version 0.15.0
SciPy is installed in D:\result_tests\WinPython-32bit-2.7.9.2\python-2.7.9\lib\site-packages\scipy
Python version 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
nose version 1.3.4
...
````
````
======================================================================
FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\result_tests\WinPython-32bit-2.7.9.2\python-2.7.9\lib\site-packages\scipy\linalg\tests\test_blas.py", line 321, in test_syr_her
    assert_(a is b)
  File "D:\result_tests\WinPython-32bit-2.7.9.2\python-2.7.9\lib\site-packages\numpy\testing\utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 17001 tests in 529.021s

FAILED (KNOWNFAIL=96, SKIP=1194, failures=1)
````

**Comment by pv** [comment]
The test appears incorrect --- it's not guaranteed that `a is b` here.

**Comment by ev-br** [comment]
`np.may_share_memory(a, b)`?

**Comment by pv** [comment]
a and b can be separate arrays, since it's f2py intent(in,out) and not
intent(inout).

**Comment by ewmoore** [comment]
It makes me wonder how to force f2py to actually overwrite that array if owning its own data, being aligned and of fortran order isn't enough.  This seems a lot like numpy/numpy#5365.  

I've made a pr that removes these `a is b` asserts.

**Comment by stonebig** [comment]
ah, two FAIL  on python3.3.5 64 bit scipy0.15.0 numpy0.19.1
````
>>> import scipy;scipy.test()
Running unit tests for scipy
NumPy version 1.9.1
NumPy is installed in D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\numpy
SciPy version 0.15.0
SciPy is installed in D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\scipy
Python version 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (Intel)]
nose version 1.3.4
````
....
````
======================================================================
FAIL: test_her2 (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\scipy\linalg\tests\test_blas.py", line 440, in test_her2
    assert_(a is b)
  File "D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\numpy\testing\utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

======================================================================
FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\scipy\linalg\tests\test_blas.py", line 321, in test_syr_her
    assert_(a is b)
  File "D:\result_tests\WinPython-32bit-3.3.5.5\python-3.3.5\lib\site-packages\numpy\testing\utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 16842 tests in 612.338s

FAILED (KNOWNFAIL=97, SKIP=1184, failures=2)
<nose.result.TextTestResult run=16842 errors=0 failures=2>
````

**Comment by ewmoore** [comment]
Those lines are also indicate failed overwrites of complex arrays.  Also
captured by the PR in #4413.

**Comment by stonebig** [comment]
thanks !
