### ISSUE TITLE
error on scipy 0.15.1 win32 python3.4.2

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#4466]
```
Running unit tests for scipy
NumPy version 1.9.1
NumPy is installed in D:\WinPython\basedir34\build1\winpython-3.4.2\python-3.4.2\lib\site-packages\numpy
SciPy version 0.15.1
SciPy is installed in D:\WinPython\basedir34\build1\winpython-3.4.2\python-3.4.2\lib\site-packages\scipy
Python version 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)]
nose version 1.3.4
```

...

```
FAIL: test_her2 (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build1\winpython-3.4.2\python-3.4.2\lib\site-packages\scipy\linalg\tests\test_blas.py", line 436, in test_her2
    assert_allclose(a, resxy, rtol=rtol)
  File "D:\WinPython\basedir34\build1\winpython-3.4.2\python-3.4.2\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "D:\WinPython\basedir34\build1\winpython-3.4.2\python-3.4.2\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-14, atol=0

(mismatch 100.0%)
 x: array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])
 y: array([[  58. +0.j,  102. +4.j,  146. +8.j,  190.+12.j],
       [   0. +0.j,  162. +0.j,  222. +4.j,  282. +8.j],
       [   0. +0.j,    0. +0.j,  298. +0.j,  374. +4.j],
       [   0. +0.j,    0. +0.j,    0. +0.j,  466. +0.j]])


----------------------------------------------------------------------
Ran 16842 tests in 652.623s

FAILED (KNOWNFAIL=97, SKIP=1184, failures=1)
<nose.result.TextTestResult run=16842 errors=0 failures=1>
>>> 
```

numpy january 21rst wheel version compiled by Christoph Gohlke
scipy  january 18th wheel version compiled by Christoph Gohlke

**Comment by pv** [comment]
Looks like a BLAS bug.

**Comment by pv** [comment]
Sorry, the test itself is wrong (overwrite_a does not imply that a is necessarily overwritten, just that it may be overridden if memory layout is suitable). The failure can be just ignored.

**Comment by rgommers** [comment]
outdated, hasn't been reported since - closing.
