### ISSUE TITLE
Test fail (Mac OsX 10.9.5) when installing with openblas

### ISSUE THREAD

**Issue by lbenet** [scipy/scipy#4539]
Hi,

I just (re)installed scipy 0.15.1 on a mac using homebrew (python 2.7.9) with the command `brew install scipy --with-openblas`. The installation went ok, but tests fail. The relevant part is:
```
======================================================================
FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/tests/test_blas.py", line 316, in test_syr_her
    resz_reverse, rtol=rtol)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]], dtype=complex64)
 y: array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])

----------------------------------------------------------------------
Ran 17003 tests in 128.494s

FAILED (KNOWNFAIL=96, SKIP=1192, failures=1)
```

Seemingly something like this has appeared before (https://github.com/scipy/scipy/issues/4453, https://github.com/xianyi/OpenBLAS/issues/492).

Is this ok? Any suggestion? Thanks.

**Comment by pv** [comment]
Openblas bug: https://github.com/xianyi/OpenBLAS/issues/492

**Comment by pv** [comment]
As indicated in those links, it's an openblas bug.
