### ISSUE TITLE
compare a benchmark between branches?

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4574]
As suggested in https://github.com/scipy/scipy/pull/4553#issuecomment-76532068
(I'm pretty sure this is a user error)

`python runtests.py --bench <BENCHMARK>` works:

```
(scipy-dev)br@ymir:~/installs/scipy-dev/scipy$ python runtests.py --bench sparse.Arithmetic
Building, see build.log...
Build OK
Running benchmarks for Scipy version 0.16.0.dev0+1f08ad3 at /home/br/installs/scipy-dev/scipy/build/testenv/lib/python2.7/site-packages/scipy/__init__.pyc
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Building for /home/br/virtualenvs/scipy-dev/bin/python
[  0.00%] ·· Benchmarking /home/br/virtualenvs/scipy-dev/bin/python
[100.00%] ··· Running sparse.Arithmetic.time_arithmetic                      ok
[100.00%] ···· 
               ======== ==== ========= ========= ========== =========
               --                               op                   
               ------------- ----------------------------------------
                format   XY   __add__   __sub__   multiply   __mul__ 
               ======== ==== ========= ========= ========== =========
                 csr     AA    1.65ms    1.49ms    1.66ms    14.82ms 
                 csr     AB   10.79ms   10.68ms   11.35ms    33.35ms 
                 csr     BA   10.56ms   10.59ms   10.58ms    37.68ms 
                 csr     BB   11.80ms   10.52ms   11.93ms    85.57ms 
               ======== ==== ========= ========= ========== =========
```

Now when I'm trying to compare a single benchmark between two branches (eg "current branch vs master"), it fails:  

```
(scipy-dev)br@ymir:~/installs/scipy-dev/scipy$ python runtests.py --bench-compare master sparse.Arithmetic
· Fetching recent changes
· virtualenv must be installed to run asv with the given Python executable
Traceback (most recent call last):
  File "runtests.py", line 436, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 215, in main
    subprocess.check_call(cmd + bench_args + [commit_b + "^!"])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/br/virtualenvs/scipy-dev/bin/python', '/home/br/installs/scipy-dev/scipy/benchmarks/run.py', '--current-repo', 'run', '--skip-existing', '-j', '2', '--bench', 'sparse.Arithmetic', '1f08ad317cb3f5da2c3bc077025203182751a1be^!']' returned non-zero exit status 1
```

I'm a bit puzzled by this. First of all, this *is* in a virtualenv. Second, what I expected it to do was roughly equivalent to 
run the specified benchmark, change the branch to master, run the specified benchmark again, maybe change the branch back. 

I tried to do `python runtests --shell` and then come up with the right incantation for `asv run`  so that it would just reuse the same environment and switch branches but failed at doing this as well.

**Comment by ev-br** [comment]
Trying `python runtests --shell` and wrangling with `asv` itself:

```
$ asv dev --python=same --bench sparse.Arithmetic
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Building for /home/br/virtualenvs/scipy-dev/bin/python
[  0.00%] ·· Benchmarking /home/br/virtualenvs/scipy-dev/bin/python
[100.00%] ··· Running sparse.Arithmetic.time_arithmetic
^C
```
but (trying to specify the commit range)

```
$ asv dev --python=same --bench sparse.Arithmetic master..HEAD
· Discovering benchmarks
· No benchmarks selected
$
```

and 

```
$ asv run --python=same --bench sparse.Arithmetic master
· No range spec may be specified if benchmarking in an existing environment
```

I'm sure I'm missing something very simple.

**Comment by pv** [comment]
You may need to give the full benchmark name in --bench-compare
This could be improved

**Comment by pv** [comment]
Also, to make it work, maybe you need to install `virtualenv` inside your virtualenv, if you are running it in a virtualenv?

**Comment by pv** [comment]
The reason why you got `No benchmarks selected` message from `asv dev` is that `--bench` takes multiple arguments and `argparse` parsed your `master..HEAD` as an argument to it.
That's probably something that should be fixed.

**Comment by pv** [comment]
gh-234 was merged, so this should be better now.
