### ISSUE TITLE
test_idl fails with numpy master

### ISSUE THREAD

**Issue by juliantaylor** [scipy/scipy#4589]
```
ERROR: test_idl.TestStructures.test_scalars_replicated_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/scipy/io/tests/test_idl.py", line 190, in test_scalars_replicated_3d
    s = readsav(path.join(DATA_PATH, 'struct_scalars_replicated_3d.sav'), verbose=False)
  File "/usr/lib/python2.7/dist-packages/scipy/io/idl.py", line 813, in readsav
    replace, new = _replace_heap(r['data'], heap)
  File "/usr/lib/python2.7/dist-packages/scipy/io/idl.py", line 599, in _replace_heap
    for ir, record in enumerate(variable):
  File "/tmp/local/lib/python2.7/site-packages/numpy/core/records.py", line 481, in __getitem__
    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))
  File "/tmp/local/lib/python2.7/site-packages/numpy/core/records.py", line 540, in view
    return ndarray.view(self, dtype)
  File "/tmp/local/lib/python2.7/site-packages/numpy/core/records.py", line 457, in __setattr__
    raise exctype(value)
TypeError: Cannot change data-type for object array.
```

caused by this change, didn't check any further yet

https://github.com/numpy/numpy/pull/5523

**Comment by astrofrog** [comment]
I can look into it. As a side note, one thing we've done in Astropy is to create a GitHub read-only team with everyone who we might want to assign issues to - this would allow you to assign any scipy.io.idl issue to me without having to give me write-access to the repo.

**Comment by astrofrog** [comment]
I think this may be a Numpy bug - I've opened an issue here with a minimal example:

https://github.com/numpy/numpy/issues/5762

**Comment by rgommers** [comment]
numpy regression which will be fixed by https://github.com/numpy/numpy/pull/5548, so closing this

**Comment by rgommers** [comment]
thanks for looking into it @astrofrog
