### ISSUE TITLE
scipy.optimize.linprog IndexError when a callback is providen

### ISSUE THREAD

**Issue by DjAntaki** [scipy/scipy#4594]
```
Traceback (most recent call last):
  File "linprog_fail.py", line 41, in <module>
    result = optimize.linprog(objective_vector, A_eq=b, b_eq=m, callback = lambda *x, **kwargs : None)
  File "/home/ntak/.local/lib/python3.4/site-packages/scipy/optimize/_linprog.py", line 954, in linprog
    bounds=bounds, callback=callback, **options)
  File "/home/ntak/.local/lib/python3.4/site-packages/scipy/optimize/_linprog.py", line 753, in _linprog_simplex
    bland=bland)
  File "/home/ntak/.local/lib/python3.4/site-packages/scipy/optimize/_linprog.py", line 335, in _solve_simplex
    solution[basis[:m]] = T[:m, -1]
IndexError: index 3 is out of bounds for axis 0 with size 2
```

The error happens on the following input:

```python
b = np.matrix(
       [[-1, 1],
        [1, -1]],
dtype='int64')
m = np.array([-2,2])
t=0
objective_vector = [-1,0]
result = optimize.linprog(objective_vector,A_eq=b, b_eq=m, callback=None) # works
result = optimize.linprog(objective_vector, A_eq=b, b_eq=m, callback = lambda *x, **kwargs: None) # fail
```

**Comment by DjAntaki** [comment]
any insight anyone?

**Comment by rgommers** [comment]
The line where you say ``# works`` doesn't raise an error but doesn't actually work:

    In [7]: result.message
    Out[7]: 'Optimization failed. The problem appears to be unbounded.'

Something is probably mis-specified in your code.

**Comment by DjAntaki** [comment]
The problem is unbounded. the output is the expected output for that call.

**Comment by argriffing** [comment]
@robfalck?  I would guess that this is a 'masked array' bug in `_pivot_row`, and that it's the same bug as in https://github.com/scipy/scipy/pull/3888.

**Comment by argriffing** [comment]
Or maybe not... in any case, here's the info right before the exception-raising attempt to create the solution vector to pass to the callback:
```python
{'complete': True, 'basis': array([0, 3]), 'tableau': array([[ 1., -1.,  2.],
       [ 0.,  0.,  0.],
       [ 0., -1.,  2.]]), 'phase': 2, 'pivot': (nan, 1), 'nit': 1}
```
