### ISSUE TITLE
Failing tests in stats with numpy master.

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4734]
These seem to be related to gh-4693. ping @aeklant 

```
$ python runtests.py -s stats
Building, see build.log...
Build OK
Running unit tests for scipy.stats
NumPy version 1.10.0.dev0+0752872
NumPy relaxed strides checking option: True
NumPy is installed in /home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy
SciPy version 0.16.0.dev0+4f65e8e
SciPy is installed in /home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy
Python version 2.7.3 (default, Sep 26 2013, 20:03:06) [GCC 4.6.3]
nose version 1.3.4

<snip>

======================================================================
ERROR: test_describe_scalar (test_stats.TestDescribe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 2317, in test_describe_scalar
    n, mm, m, v, sk, kurt = stats.describe(4.)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 1178, in describe
    v = np.var(a, axis=axis, ddof=ddof)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 3060, in var
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 117, in _var
    ret = ret.dtype.type(ret / rcount)
RuntimeWarning: invalid value encountered in double_scalars

======================================================================
ERROR: test_nanmedian_scalars (test_stats.TestNanFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 230, in test_nanmedian_scalars
    assert_equal(stats.nanmedian(np.nan), np.median(np.nan))
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/utils.py", line 97, in newfunc
    return func(*args, **kwds)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 470, in nanmedian
    return np.nanmedian(x, axis)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py", line 831, in nanmedian
    overwrite_input=overwrite_input)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2860, in _ureduce
    r = func(a, **kwargs)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py", line 716, in _nanmedian
    return _nanmedian1d(part, overwrite_input)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py", line 689, in _nanmedian1d
    warnings.warn("All-NaN slice encountered", RuntimeWarning)
RuntimeWarning: All-NaN slice encountered

======================================================================
ERROR: test_onesample (test_stats.TestStudentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 1498, in test_onesample
    t, p = stats.ttest_1samp(4., 3.)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 3305, in ttest_1samp
    v = np.var(a, axis, ddof=1)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 3060, in var
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 117, in _var
    ret = ret.dtype.type(ret / rcount)
RuntimeWarning: invalid value encountered in double_scalars

======================================================================
ERROR: test_sem (test_stats.TestVariability)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 1295, in test_sem
    y = stats.sem(self.scalar_testcase)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 2023, in sem
    s = np.std(a, axis=axis, ddof=ddof) / np.sqrt(n)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2952, in std
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 125, in _std
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 117, in _var
    ret = ret.dtype.type(ret / rcount)
RuntimeWarning: invalid value encountered in double_scalars

======================================================================
ERROR: test_stats.test_ttest_rel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 2064, in test_ttest_rel
    t, p = stats.ttest_rel(4., 3.)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 3580, in ttest_rel
    v = np.var(d, axis, ddof=1)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 3060, in var
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 117, in _var
    ret = ret.dtype.type(ret / rcount)
RuntimeWarning: invalid value encountered in double_scalars

======================================================================
ERROR: test_stats.test_ttest_ind
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 2140, in test_ttest_ind
    t, p = stats.ttest_ind(4., 3.)
  File "/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/stats.py", line 3501, in ttest_ind
    v1 = np.var(a, axis, ddof=1)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 3060, in var
    keepdims=keepdims)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 117, in _var
    ret = ret.dtype.type(ret / rcount)
RuntimeWarning: invalid value encountered in double_scalars

----------------------------------------------------------------------
Ran 2177 tests in 10.729s

FAILED (KNOWNFAIL=4, SKIP=3, errors=6)
```

**Comment by aeklant** [comment]
Are all `RuntimeWarning`s treated as errors in numpy 1.10? The tests run well under numpy 1.9.2

**Comment by argriffing** [comment]
> Are all `RuntimeWarning`s treated as errors in numpy 1.10? The tests run well under numpy 1.9.2

`RuntimeWarning`s are treated as errors when numpy is built with this [flag](http://docs.scipy.org/doc/numpy/reference/c-api.deprecations.html#deprecation-mechanism-npy-no-deprecated-api).  The development versions are built with this flag, currently including version 1.10.

**Comment by argriffing** [comment]
I think the `RuntimeWarning`s being treated as errors is more about the unreleased status of 1.10 (for example https://github.com/numpy/numpy/pull/219).  Numpy has different settings for unreleased vs. released versions.

**Comment by aeklant** [comment]
I see. In all of these tests we are expecting `nan` to be the result (or a part of the result). These functions are being tested for corner cases so a few warnings are to be expected, I think. 

I could try and adapt the tests to avoid or catch the warning but then I think they would miss the point. Either way, let me know if you think this should be addressed.

*Note:* The `test_nanmedian_scalars` was not part of #4693. I remember because `stats.nan*` are deprecated since scipy 0.15 as mentioned in #4550 (but I would bet the problem goes along the same lines).

**Comment by rgommers** [comment]
@aeklant yes would be good to change the tests. Note that they shouldn't test anything differently (that would indeed miss the point), but the test suite should be free of warnings. This is usually easily achieved by putting this in the test function:

    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=RuntimeWarning)

Of course ``category`` should be set to relevant class, or in some cases it's easier to filter on the warning text.

**Comment by aeklant** [comment]
Alright, it seems reasonable. Should I include `test_nanmeadian_scalars` even though its deprecated?

**Comment by ev-br** [comment]
That nanmedian test is not filtered out is likely an oversight of https://github.com/scipy/scipy/pull/4117

**Comment by rgommers** [comment]
yes, please include all tests that give a warning

**Comment by aeklant** [comment]
Alright, I've made some changes. Please let me know if the implementation is properly done or you have any feedback.

**Comment by ev-br** [comment]
Fixed by gh-4738, so closing.

**Comment by aeklant** [comment]
Great. Thanks @ev-br for finding the issue and to @argriffing and @rgommers for the feedback and tips.
