### ISSUE TITLE
lsim2 cannot simulate a MIMO system that simply passes the input to the output unchanged

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4794]
This issue has been extracted from the stalled PR https://github.com/scipy/scipy/pull/2862.

```python
import numpy as np
from scipy.signal import lsim2

A = np.zeros((1,1))
B = np.zeros((1,2))
C = np.zeros((2,1))
D = np.eye(2)

t = np.arange(3)
u0 = np.arange(3)
u1 = 2*u0
u = np.vstack((u0,u1)).T
lsim2((A,B,C,D),T=t,U=u)
```

```
Traceback (most recent call last):
  File "[...]", line 13, in <module>
    lsim2((A,B,C,D),T=t,U=u)
  File "[...]/scipy/signal/ltisys.py", line 555, in lsim2
    sys = lti(*system)
  File "[...]/scipy/signal/ltisys.py", line 328, in __init__
    self._update(N)
  File "[...]/scipy/signal/ltisys.py", line 439, in _update
    self.C, self.D)
  File "[...]/scipy/signal/ltisys.py", line 270, in ss2zpk
    return tf2zpk(*ss2tf(A, B, C, D, input=input))
  File "[...]/scipy/signal/filter_design.py", line 587, in tf2zpk
    z = roots(b)
  File "[...]/numpy/lib/polynomial.py", line 203, in roots
    raise ValueError("Input must be a rank-1 array.")
```

**Comment by DietBru** [comment]
The `lsim2` function was removed in favor of the [lsim] function in SciPy [SciPy 1.13.0].

[lsim]: https://scipy.github.io/devdocs/reference/generated/scipy.signal.lsim.html
[SciPy 1.13.0]: https://docs.scipy.org/doc/scipy-1.18.0/release/1.13.0-notes.html#expired-deprecations
