### ISSUE TITLE
Test error for matrix norms (py3.3, numpy 1.8.0)

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4813]
Test was introduced in gh-4642. Might be numpy version specific, didn't check.

    Running unit tests for scipy
    NumPy version 1.8.0
    NumPy is installed in /home/rgommers/.local/lib/python3.3/site-packages/numpy
    SciPy version 0.16.0.dev0+8644798
    SciPy is installed in /home/rgommers/Code/bldscipy/build/testenv/lib/python3.3/site-packages/scipy
    Python version 3.3.0 (default, Dec 16 2012, 14:26:16) [GCC 4.6.3]
    nose version 1.2.1

    ======================================================================
    ERROR: test_basic.TestMatrixNorms.test_matrix_norms
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/rgommers/Code/pythons/lib/python3.3/site-packages/nose-1.2.1-py3.3.egg/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/bldscipy/build/testenv/lib/python3.3/site-packages/scipy/linalg/tests/test_basic.py", line 929, in test_matrix_norms
        actual = norm(A, ord=order)
      File "/home/rgommers/Code/bldscipy/build/testenv/lib/python3.3/site-packages/scipy/linalg/misc.py", line 140, in norm
        return np.linalg.norm(a, ord=ord)
      File "/home/rgommers/.local/lib/python3.3/site-packages/numpy/linalg/linalg.py", line 2099, in norm
        return _multi_svd_norm(x, row_axis, col_axis, amax)
      File "/home/rgommers/.local/lib/python3.3/site-packages/numpy/linalg/linalg.py", line 1920, in _multi_svd_norm
        result = op(svd(y, compute_uv=0), axis=-1)
      File "/home/rgommers/.local/lib/python3.3/site-packages/numpy/linalg/linalg.py", line 1339, in svd
        s = gufunc(a, signature=signature, extobj=extobj)
    TypeError: No loop matching the specified signature was found for ufunc svd_m

**Comment by argriffing** [comment]
I'm almost positive it's https://github.com/numpy/numpy/issues/5232 and that it is fixed in more recent releases of `1.8.x`.

**Comment by rgommers** [comment]
Thanks, I'll check

**Comment by rgommers** [comment]
Indeed, works with 1.8.2
