### ISSUE TITLE
VS instructions are too sparse

### ISSUE THREAD

**Issue by kousu** [scipy/scipy#4822]
http://www.scipy.org/scipylib/building/windows.html claims "The installation is quite straightforward;" but this has not been my experience. I have Visual Studio 2013---which is what was available to me---and it does not build scipy in its default configuration. Rather, distutils doesn't find it. This isn't a scipy bug strictly speaking, but the documentation is misleading.

My motivation to do this is that there are no 64 bit binary packages available.

This is a semi-known issue:
- http://stackoverflow.com/questions/84404/using-visual-studios-cl-from-a-normal-command-line
- http://bugs.python.org/issue2943
  but there does not seem to be a clear answer. It shouldn't be so hard to just find Visual Studio, should it? It seems that distutils/msvc9compiler.py is being used rather than distutils/msvccompiler.py; I'm not sure why this is the default, and your setup.py mentions nothing about which VS version to use.

A build log from 64 bit Windows 7 (with VS 2013 installed) using pip:

```
C:\Users\john                                                                                                                                             
λ pip install scipy                                                                                                                                       
You are using pip version 6.0.8, however version 6.1.1 is available.                                                                                      
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                                
Collecting scipy                                                                                                                                          
  Using cached scipy-0.15.1.tar.gz                                                                                                                        
    non-existing path in 'numpy\\distutils': 'site.cfg'                                                                                                   
    non-existing path in 'numpy\\f2py': 'docs'                                                                                                            
    non-existing path in 'numpy\\f2py': 'f2py.1'                                                                                                          
    non-existing path in 'numpy\\lib': 'benchmarks'                                                                                                       
    Running from numpy source directory.                                                                                                                  
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1603: UserWarning:                                  
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.                                                                                   
        Directories to search for the libraries can be specified in the                                                                                   
        numpy/distutils/site.cfg file (section [atlas]) or by setting                                                                                     
        the ATLAS environment variable.                                                                                                                   
      warnings.warn(AtlasNotFoundError.__doc__)                                                                                                           
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1612: UserWarning:                                  
        Blas (http://www.netlib.org/blas/) libraries not found.                                                                                           
        Directories to search for the libraries can be specified in the                                                                                   
        numpy/distutils/site.cfg file (section [blas]) or by setting                                                                                      
        the BLAS environment variable.                                                                                                                    
      warnings.warn(BlasNotFoundError.__doc__)                                                                                                            
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1615: UserWarning:                                  
        Blas (http://www.netlib.org/blas/) sources not found.                                                                                             
        Directories to search for the sources can be specified in the                                                                                     
        numpy/distutils/site.cfg file (section [blas_src]) or by setting                                                                                  
        the BLAS_SRC environment variable.                                                                                                                
      warnings.warn(BlasSrcNotFoundError.__doc__)                                                                                                         
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1505: UserWarning:                                  
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.                                                                                   
        Directories to search for the libraries can be specified in the                                                                                   
        numpy/distutils/site.cfg file (section [atlas]) or by setting                                                                                     
        the ATLAS environment variable.                                                                                                                   
      warnings.warn(AtlasNotFoundError.__doc__)                                                                                                           
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1516: UserWarning:                                  
        Lapack (http://www.netlib.org/lapack/) libraries not found.                                                                                       
        Directories to search for the libraries can be specified in the                                                                                   
        numpy/distutils/site.cfg file (section [lapack]) or by setting                                                                                    
        the LAPACK environment variable.                                                                                                                  
      warnings.warn(LapackNotFoundError.__doc__)                                                                                                          
    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1519: UserWarning:                                  
        Lapack (http://www.netlib.org/lapack/) sources not found.                                                                                         
        Directories to search for the sources can be specified in the                                                                                     
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting                                                                                
        the LAPACK_SRC environment variable.                                                                                                              
      warnings.warn(LapackSrcNotFoundError.__doc__)                                                                                                       
    C:\tools\python3\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'define_macros'                                                 
      warnings.warn(msg)                                                                                                                                  
    Traceback (most recent call last):                                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall                                                  
        return unpatched['query_vcvarsall'](version, *args, **kwargs)                                                                                     
      File "C:\tools\python3\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall                                                                
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")                                                                                      
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat                                                                                 
    During handling of the above exception, another exception occurred:                                                                                   
    Traceback (most recent call last):                                                                                                                    
      File "C:\tools\python3\lib\distutils\core.py", line 148, in setup                                                                                   
        dist.run_commands()                                                                                                                               
      File "C:\tools\python3\lib\distutils\dist.py", line 955, in run_commands                                                                            
        self.run_command(cmd)                                                                                                                             
      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             
        cmd_obj.run()                                                                                                                                     
      File "C:\tools\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 152, in run                                                         
        self.run_command("egg_info")                                                                                                                      
      File "C:\tools\python3\lib\distutils\cmd.py", line 313, in run_command                                                                              
        self.distribution.run_command(command)                                                                                                            
      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             
        cmd_obj.run()                                                                                                                                     
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\egg_info.py", line 10, in run                      
      File "C:\tools\python3\lib\distutils\cmd.py", line 313, in run_command                                                                              
        self.distribution.run_command(command)                                                                                                            
      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             
        cmd_obj.run()                                                                                                                                     
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 153, in run                    
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 164, in build_sources          
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 299, in build_library_sources  
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 386, in generate_sources       
      File "numpy\core\setup.py", line 684, in get_mathlib_info                                                                                           
      File "C:\tools\python3\lib\distutils\command\config.py", line 243, in try_link                                                                      
        self._check_compiler()                                                                                                                            
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\config.py", line 57, in _check_compiler            
      File "C:\tools\python3\lib\distutils\msvc9compiler.py", line 371, in initialize                                                                     
        vc_env = query_vcvarsall(VERSION, plat_spec)                                                                                                      
      File "C:\tools\python3\lib\site-packages\setuptools\msvc9_support.py", line 62, in query_vcvarsall                                                  
        raise distutils.errors.DistutilsPlatformError(message)                                                                                            
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                        
    During handling of the above exception, another exception occurred:                                                                                   
    Traceback (most recent call last):                                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules                                                          
        yield saved                                                                                                                                       
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         
        yield                                                                                                                                             
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup                                                             
        DirectorySandbox(setup_dir).run(runner)                                                                                                           
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 265, in run                                                                   
        return func()                                                                                                                                     
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 234, in runner                                                                
        _execfile(setup_script, ns)                                                                                                                       
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile                                                              
        exec(code, globals, locals)                                                                                                                       
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 251, in <module>                                           
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 243, in setup_package                                      
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\core.py", line 169, in setup                               
      File "C:\tools\python3\lib\distutils\core.py", line 163, in setup                                                                                   
        raise SystemExit("error: " + str(msg))                                                                                                            
    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                                              
    During handling of the above exception, another exception occurred:                                                                                   
    Traceback (most recent call last):                                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1052, in run_setup                                               
        run_setup(setup_script, args)                                                                                                                     
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 238, in run_setup                                                             
        raise                                                                                                                                             
      File "C:\tools\python3\lib\contextlib.py", line 77, in __exit__                                                                                     
        self.gen.throw(type, value, traceback)                                                                                                            
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         
        yield                                                                                                                                             
      File "C:\tools\python3\lib\contextlib.py", line 77, in __exit__                                                                                     
        self.gen.throw(type, value, traceback)                                                                                                            
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 162, in save_modules                                                          
        saved_exc.resume()                                                                                                                                
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 137, in resume                                                                
        compat.reraise(type, exc, self._tb)                                                                                                               
      File "C:\tools\python3\lib\site-packages\setuptools\compat.py", line 65, in reraise                                                                 
        raise value.with_traceback(tb)                                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules                                                          
        yield saved                                                                                                                                       
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         
        yield                                                                                                                                             
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup                                                             
        DirectorySandbox(setup_dir).run(runner)                                                                                                           
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 265, in run                                                                   
        return func()                                                                                                                                     
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 234, in runner                                                                
        _execfile(setup_script, ns)                                                                                                                       
      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile                                                              
        exec(code, globals, locals)                                                                                                                       
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 251, in <module>                                           
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 243, in setup_package                                      
      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\core.py", line 169, in setup                               
      File "C:\tools\python3\lib\distutils\core.py", line 163, in setup                                                                                   
        raise SystemExit("error: " + str(msg))                                                                                                            
    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                                              
    During handling of the above exception, another exception occurred:                                                                                   
    Traceback (most recent call last):                                                                                                                    
      File "<string>", line 20, in <module>                                                                                                               
      File "C:\Users\john\AppData\Local\Temp\pip-build-rmtc9b4o\scipy\setup.py", line 249, in <module>                                                    
        setup_package()                                                                                                                                   
      File "C:\Users\john\AppData\Local\Temp\pip-build-rmtc9b4o\scipy\setup.py", line 246, in setup_package                                               
        setup(**metadata)                                                                                                                                 
      File "C:\tools\python3\lib\distutils\core.py", line 108, in setup                                                                                   
        _setup_distribution = dist = klass(attrs)                                                                                                         
      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 265, in __init__                                                                 
        self.fetch_build_eggs(attrs['setup_requires'])                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 311, in fetch_build_eggs                                                         
        replace_conflicting=True,                                                                                                                         
      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 797, in resolve                                                           
        dist = best[req.key] = env.best_match(req, ws, installer)                                                                                         
      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 1047, in best_match                                                       
        return self.obtain(req, installer)                                                                                                                
      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 1059, in obtain                                                           
        return installer(requirement)                                                                                                                     
      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 378, in fetch_build_egg                                                          
        return cmd.easy_install(req)                                                                                                                      
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 623, in easy_install                                             
        return self.install_item(spec, dist.location, tmpdir, deps)                                                                                       
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 653, in install_item                                             
        dists = self.install_eggs(spec, download, tmpdir)                                                                                                 
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 838, in install_eggs                                             
        return self.build_and_install(setup_script, setup_base)                                                                                           
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1066, in build_and_install                                       
        self.run_setup(setup_script, setup_base, args)                                                                                                    
      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1054, in run_setup                                               
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))                                                                                
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                
    Complete output from command python setup.py egg_info:                                                                                                
    non-existing path in 'numpy\\distutils': 'site.cfg'                                                                                                   

    non-existing path in 'numpy\\f2py': 'docs'                                                                                                            

    non-existing path in 'numpy\\f2py': 'f2py.1'                                                                                                          

    non-existing path in 'numpy\\lib': 'benchmarks'                                                                                                       

    Running from numpy source directory.                                                                                                                  

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1603: UserWarning:                                  

        Atlas (http://math-atlas.sourceforge.net/) libraries not found.                                                                                   

        Directories to search for the libraries can be specified in the                                                                                   

        numpy/distutils/site.cfg file (section [atlas]) or by setting                                                                                     

        the ATLAS environment variable.                                                                                                                   

      warnings.warn(AtlasNotFoundError.__doc__)                                                                                                           

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1612: UserWarning:                                  

        Blas (http://www.netlib.org/blas/) libraries not found.                                                                                           

        Directories to search for the libraries can be specified in the                                                                                   

        numpy/distutils/site.cfg file (section [blas]) or by setting                                                                                      

        the BLAS environment variable.                                                                                                                    

      warnings.warn(BlasNotFoundError.__doc__)                                                                                                            

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1615: UserWarning:                                  

        Blas (http://www.netlib.org/blas/) sources not found.                                                                                             

        Directories to search for the sources can be specified in the                                                                                     

        numpy/distutils/site.cfg file (section [blas_src]) or by setting                                                                                  

        the BLAS_SRC environment variable.                                                                                                                

      warnings.warn(BlasSrcNotFoundError.__doc__)                                                                                                         

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1505: UserWarning:                                  

        Atlas (http://math-atlas.sourceforge.net/) libraries not found.                                                                                   

        Directories to search for the libraries can be specified in the                                                                                   

        numpy/distutils/site.cfg file (section [atlas]) or by setting                                                                                     

        the ATLAS environment variable.                                                                                                                   

      warnings.warn(AtlasNotFoundError.__doc__)                                                                                                           

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1516: UserWarning:                                  

        Lapack (http://www.netlib.org/lapack/) libraries not found.                                                                                       

        Directories to search for the libraries can be specified in the                                                                                   

        numpy/distutils/site.cfg file (section [lapack]) or by setting                                                                                    

        the LAPACK environment variable.                                                                                                                  

      warnings.warn(LapackNotFoundError.__doc__)                                                                                                          

    C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\system_info.py:1519: UserWarning:                                  

        Lapack (http://www.netlib.org/lapack/) sources not found.                                                                                         

        Directories to search for the sources can be specified in the                                                                                     

        numpy/distutils/site.cfg file (section [lapack_src]) or by setting                                                                                

        the LAPACK_SRC environment variable.                                                                                                              

      warnings.warn(LapackSrcNotFoundError.__doc__)                                                                                                       

    C:\tools\python3\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'define_macros'                                                 

      warnings.warn(msg)                                                                                                                                  

    Traceback (most recent call last):                                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall                                                  

        return unpatched['query_vcvarsall'](version, *args, **kwargs)                                                                                     

      File "C:\tools\python3\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall                                                                

        raise DistutilsPlatformError("Unable to find vcvarsall.bat")                                                                                      

    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat                                                                                 



    During handling of the above exception, another exception occurred:                                                                                   



    Traceback (most recent call last):                                                                                                                    

      File "C:\tools\python3\lib\distutils\core.py", line 148, in setup                                                                                   

        dist.run_commands()                                                                                                                               

      File "C:\tools\python3\lib\distutils\dist.py", line 955, in run_commands                                                                            

        self.run_command(cmd)                                                                                                                             

      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             

        cmd_obj.run()                                                                                                                                     

      File "C:\tools\python3\lib\site-packages\setuptools\command\bdist_egg.py", line 152, in run                                                         

        self.run_command("egg_info")                                                                                                                      

      File "C:\tools\python3\lib\distutils\cmd.py", line 313, in run_command                                                                              

        self.distribution.run_command(command)                                                                                                            

      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             

        cmd_obj.run()                                                                                                                                     

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\egg_info.py", line 10, in run                      

      File "C:\tools\python3\lib\distutils\cmd.py", line 313, in run_command                                                                              

        self.distribution.run_command(command)                                                                                                            

      File "C:\tools\python3\lib\distutils\dist.py", line 974, in run_command                                                                             

        cmd_obj.run()                                                                                                                                     

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 153, in run                    

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 164, in build_sources          

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 299, in build_library_sources  

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\build_src.py", line 386, in generate_sources       

      File "numpy\core\setup.py", line 684, in get_mathlib_info                                                                                           

      File "C:\tools\python3\lib\distutils\command\config.py", line 243, in try_link                                                                      

        self._check_compiler()                                                                                                                            

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\command\config.py", line 57, in _check_compiler            

      File "C:\tools\python3\lib\distutils\msvc9compiler.py", line 371, in initialize                                                                     

        vc_env = query_vcvarsall(VERSION, plat_spec)                                                                                                      

      File "C:\tools\python3\lib\site-packages\setuptools\msvc9_support.py", line 62, in query_vcvarsall                                                  

        raise distutils.errors.DistutilsPlatformError(message)                                                                                            

    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                        



    During handling of the above exception, another exception occurred:                                                                                   



    Traceback (most recent call last):                                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules                                                          

        yield saved                                                                                                                                       

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         

        yield                                                                                                                                             

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup                                                             

        DirectorySandbox(setup_dir).run(runner)                                                                                                           

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 265, in run                                                                   

        return func()                                                                                                                                     

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 234, in runner                                                                

        _execfile(setup_script, ns)                                                                                                                       

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile                                                              

        exec(code, globals, locals)                                                                                                                       

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 251, in <module>                                           

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 243, in setup_package                                      



      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\core.py", line 169, in setup                               

      File "C:\tools\python3\lib\distutils\core.py", line 163, in setup                                                                                   

        raise SystemExit("error: " + str(msg))                                                                                                            

    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                                              



    During handling of the above exception, another exception occurred:                                                                                   



    Traceback (most recent call last):                                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1052, in run_setup                                               

        run_setup(setup_script, args)                                                                                                                     

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 238, in run_setup                                                             

        raise                                                                                                                                             

      File "C:\tools\python3\lib\contextlib.py", line 77, in __exit__                                                                                     

        self.gen.throw(type, value, traceback)                                                                                                            

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         

        yield                                                                                                                                             

      File "C:\tools\python3\lib\contextlib.py", line 77, in __exit__                                                                                     

        self.gen.throw(type, value, traceback)                                                                                                            

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 162, in save_modules                                                          

        saved_exc.resume()                                                                                                                                

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 137, in resume                                                                

        compat.reraise(type, exc, self._tb)                                                                                                               

      File "C:\tools\python3\lib\site-packages\setuptools\compat.py", line 65, in reraise                                                                 

        raise value.with_traceback(tb)                                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 150, in save_modules                                                          

        yield saved                                                                                                                                       

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 191, in setup_context                                                         

        yield                                                                                                                                             

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 235, in run_setup                                                             

        DirectorySandbox(setup_dir).run(runner)                                                                                                           

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 265, in run                                                                   

        return func()                                                                                                                                     

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 234, in runner                                                                

        _execfile(setup_script, ns)                                                                                                                       

      File "C:\tools\python3\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile                                                              

        exec(code, globals, locals)                                                                                                                       

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 251, in <module>                                           

      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\setup.py", line 243, in setup_package                                      



      File "C:\Users\john\AppData\Local\Temp\easy_install-m1e3mwta\numpy-1.9.2\numpy\distutils\core.py", line 169, in setup                               

      File "C:\tools\python3\lib\distutils\core.py", line 163, in setup                                                                                   

        raise SystemExit("error: " + str(msg))                                                                                                            

    SystemExit: error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                                                              



    During handling of the above exception, another exception occurred:                                                                                   



    Traceback (most recent call last):                                                                                                                    

      File "<string>", line 20, in <module>                                                                                                               

      File "C:\Users\john\AppData\Local\Temp\pip-build-rmtc9b4o\scipy\setup.py", line 249, in <module>                                                    

        setup_package()                                                                                                                                   

      File "C:\Users\john\AppData\Local\Temp\pip-build-rmtc9b4o\scipy\setup.py", line 246, in setup_package                                               

        setup(**metadata)                                                                                                                                 

      File "C:\tools\python3\lib\distutils\core.py", line 108, in setup                                                                                   

        _setup_distribution = dist = klass(attrs)                                                                                                         

      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 265, in __init__                                                                 

        self.fetch_build_eggs(attrs['setup_requires'])                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 311, in fetch_build_eggs                                                         

        replace_conflicting=True,                                                                                                                         

      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 797, in resolve                                                           

        dist = best[req.key] = env.best_match(req, ws, installer)                                                                                         

      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 1047, in best_match                                                       

        return self.obtain(req, installer)                                                                                                                

      File "C:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 1059, in obtain                                                           

        return installer(requirement)                                                                                                                     

      File "C:\tools\python3\lib\site-packages\setuptools\dist.py", line 378, in fetch_build_egg                                                          

        return cmd.easy_install(req)                                                                                                                      

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 623, in easy_install                                             

        return self.install_item(spec, dist.location, tmpdir, deps)                                                                                       

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 653, in install_item                                             

        dists = self.install_eggs(spec, download, tmpdir)                                                                                                 

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 838, in install_eggs                                             

        return self.build_and_install(setup_script, setup_base)                                                                                           

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1066, in build_and_install                                       

        self.run_setup(setup_script, setup_base, args)                                                                                                    

      File "C:\tools\python3\lib\site-packages\setuptools\command\easy_install.py", line 1054, in run_setup                                               

        raise DistutilsError("Setup script exited with %s" % (v.args[0],))                                                                                

    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).                

    ----------------------------------------                                                                                                              
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\john\AppData\Local\Temp\pip-build-rmtc9b4o\scipy                              

```

**Comment by jaimefrio** [comment]
That distutils does not find your VS 2013 should be the least of your worries, the fun would begin once it found it. To make a long story short, when using Microsoft compilers, you have to compile extension modules with the same version the Python version you are using was. That means 2008 for Python 2.7 and 2010 for the latest Python 3.x. There really is no simple way around it, sorry.

**Comment by matthew-brett** [comment]
Unfortunately, as Jamie said, your problems are not only starting, because you also need a Fortran compiler to compile scipy.  The only free option is to instead use MinGW to compile both C and Fortran - or better - MinGW-w64.

**Comment by kousu** [comment]
Ah, I was worried about that--it's ABI incompatibility, right?--but I couldn't get a clear answer.

May I request that http://www.scipy.org/scipylib/building/windows.html be updated to mention this? Perhaps a big ol' **don't build with VS** ;)

**Comment by rgommers** [comment]
That's not exactly the right message. MSVC + Intel Fortran (+ MKL) is the most robust option on Windows, it's just not free. Here's a guide for that: https://software.intel.com/en-us/articles/building-numpyscipy-with-intel-mkl-and-intel-fortran-on-windows

We should indeed update those docs.

**Comment by drbo** [comment]
That option is a no-go for many, though: it is expensive, and the resulting binaries cannot be redistributed by those without an Intel compiler license.

**Comment by rgommers** [comment]
This is still a pain point. MSVC + Intel Fortran is still the best option for people with an ifort license. If not, better to avoid Windows by building in WSL (Windows Subsystem for Linux). If someone is really determined to bite the bullet with MSVC + gfortran, look at https://github.com/MacPython/scipy-wheels for how we do it for our wheels.

**Comment by pv** [comment]
The instructions were updated in the meantime though, so this issue probably is not actionable.

In the absence of open-source Fortran compiler CRT-compatible with Python.org binaries, I don't think we can do much more.
