### ISSUE TITLE
signal.spectrogram test failure

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#4844]
I'm getting a test failure:

```
~$ python -c "import scipy.signal as m; m.test('full')"
Running unit tests for scipy.signal
NumPy version 1.9.2
NumPy is installed in /Users/warren/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.16.0.dev0+808013c
SciPy is installed in /Users/warren/local_scipy/lib/python2.7/site-packages/scipy
Python version 2.7.9 |Anaconda 1.8.0 (x86_64)| (default, Dec 15 2014, 10:37:34) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.6
................................................................................................................................................................................................................../Users/warren/local_scipy/lib/python2.7/site-packages/scipy/signal/filter_design.py:1055: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)
../Users/warren/local_scipy/lib/python2.7/site-packages/scipy/signal/filter_design.py:1055: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)
................................................................................................................................................................................................................................................................................................................................................................................................................................................F............................................................................
======================================================================
FAIL: test_spectral.TestSpectrogram.test_average_all_segments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/warren/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/signal/tests/test_spectral.py", line 783, in test_average_all_segments
    assert_allclose(f, fw)
  File "/Users/warren/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/warren/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 620, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(shapes (73,), (9,) mismatch)
 x: array([    8.,    22.,    36.,    50.,    64.,    78.,    92.,   106.,
         120.,   134.,   148.,   162.,   176.,   190.,   204.,   218.,
         232.,   246.,   260.,   274.,   288.,   302.,   316.,   330.,...
 y: array([ 0.    ,  0.0625,  0.125 ,  0.1875,  0.25  ,  0.3125,  0.375 ,
        0.4375,  0.5   ])

----------------------------------------------------------------------
Ran 721 tests in 5.523s

FAILED (failures=1)
~$ 
```

Looks like `spectrogram` and `welch` are returning completely different arrays of frequencies.

**Comment by WarrenWeckesser** [comment]
Looks like a bug in the test.  This line

    f, _, P = spectrogram(x, fs, window, nperseg, noverlap)

should be

    _, f, P = spectrogram(x, fs, window, nperseg, noverlap)

I'll start a PR with the fix.

But I wonder how this test passed on Travis or for @e-q?

**Comment by WarrenWeckesser** [comment]
The docstring for `spectrogram` says

```
    Returns
    -------
    f : ndarray
        Array of sample frequencies.
    t : ndarray
        Array of segment times.
    Sxx : ndarray
        Spectrogram of x. By default, the last axis of Sxx corresponds to the
        segment times.
```

but the `return` statement is

    return time, freqs, Pxy

Given that `f` and `t` are the coordinates associated with the first and second dimensions of the 2-D array `Sxx`, it seems reasonable to use the order given in the docstring.  A PR to fix the return order is upcoming.

**Comment by WarrenWeckesser** [comment]
Pull request is https://github.com/scipy/scipy/pull/4845

**Comment by rgommers** [comment]
This is the second time recently that TravisCI misses a failure. I think nose may be skipping tests again, that has happened before.

**Comment by rgommers** [comment]
This was 3 days ago: https://github.com/scipy/scipy/pull/4709#issuecomment-99342536

**Comment by ev-br** [comment]
> But I wonder how this test passed on Travis 

It didn't: https://github.com/scipy/scipy/issues/4847
