### ISSUE TITLE
MKL test failures

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#4885]
On Ubuntu 14.10 64-bit with system Python 2.7, latest MKL (15.0.0), cython 0.22.x, numpy 1.9.2, scipy 0.16 branch I get about 22 failures/errors with `scipy.test('full')`. `numpy.test('full')` passes (except for one test that runs out of disk space). I was running MKL version 13 last week and had similar failures.

I have tried the following, but they all fail in similar but not identical ways:

- using the default values in `numpy/distuils/*`
- [intel's instructions] (https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl)
- another [person's instructions] (https://gehrcke.de/2014/02/building-numpy-and-scipy-with-intel-compilers-and-intel-mkl-on-a-64-bit-machine)

I have also rolled back to the `maintenance/0.15.x` branch, and I get about ~~16~~ EDIT: 3 failures there, too -- so I assume there is something wrong with my compilation setup but I'm not sure what it could be...

All failures are [in this gist] (https://gist.github.com/Eric89GXL/cc95600b8dc0d67cce66), but here are a few example failures:

```
======================================================================
ERROR: test_decomp_update.TestQRdelete_f.test_economic_p_row_fat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 230, in test_economic_p_row_fat
    self.base_economic_p_row_xxx(7)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 216, in base_economic_p_row_xxx
    q1, r1 = qr_delete(q, r, row, ndel, overwrite_qr=False)
  File "scipy/linalg/_decomp_update.pyx", line 1652, in scipy.linalg._decomp_update.qr_delete (scipy/linalg/_decomp_update.c:27659)
ValueError: Reorthogonalization Failed, unable to perform row deletion.

======================================================================
FAIL: test_decomp_update.TestQRdelete_D.test_economic_1_row
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 207, in test_economic_1_row
    check_qr(q1, r1, a1, self.rtol, self.atol, False)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 32, in check_qr
    assert_unitary(q, rtol, atol, assert_sqr)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 21, in assert_unitary
    assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-13, atol=2.22045e-15

(mismatch 100.0%)
 x: array([[  9.803958e-01+0.j      ,   2.215354e-02-0.092053j,
          2.161659e-02-0.030168j,  -4.511673e-04-0.013876j,
         -4.492602e-04-0.090115j,   3.500837e-02-0.059986j,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],...

======================================================================
FAIL: test_multi (test_odr.TestODR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/odr/tests/test_odr.py", line 190, in test_multi
    0.5101147161764654, 0.5173902330489161]),
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([ 4. ,  2. ,  7. ,  0.4,  0.5])
 y: array([ 4.379988,  2.433306,  8.002885,  0.510115,  0.51739 ])
```

**Comment by Eric89GXL** [comment]
Correction: I only get 3 errors on 0.15, and they are all in `TestODR` for `test_lorentz`, `test_multi`, and `test_pearson` of a similar form:
```
======================================================================
FAIL: test_pearson (test_odr.TestODR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/odr/tests/test_odr.py", line 236, in test_pearson
    np.array([5.4767400299231674, -0.4796082367610305]),
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([ 1.,  1.])
 y: array([ 5.47674 , -0.479608])
```
So it looks like most of these errors are new problems for 0.16 :(

**Comment by rgommers** [comment]
@Eric89GXL you're on 64-bit Linux right? And does gh-4854 fix any of the failures for you?

**Comment by rgommers** [comment]
Some of the failures look very similar to gh-4848 (which was 32-bit linux) except that the failures are also for float64/complex128 in addition to float32/complex64.

The test errors (``ValueError: Reorthogonalization Failed, unable to perform row deletion.``) are new.

**Comment by rgommers** [comment]
The ``ODR`` issues are gh-3340, and can be solved by compiling with ``-O1`` instead of ``-O2``. So for this issue it's just the qr updating routines to worry about (not bothered about the weird ``weave`` issue - deprecated anyway).

**Comment by Eric89GXL** [comment]
Yep, 64-bit linux.

I pulled the change from #4854, and recompiled numpy/scipy with `-O1` instead of `-O3` in both the C and Fortran compiler settings. This yields 16 failures, all from `test_decomp_update.TestQRdelete_*` functions and they all look similar to this:
```
======================================================================
FAIL: test_decomp_update.TestQRdelete_f.test_economic_p_row_sqr
...
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 226, in test_economic_p_row_sqr
    self.base_economic_p_row_xxx(5)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 218, in base_economic_p_row_xxx
    check_qr(q1, r1, a1, self.rtol, self.atol, False)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 32, in check_qr
    assert_unitary(q, rtol, atol, assert_sqr)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 21, in assert_unitary
    assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
...
Not equal to tolerance rtol=0.0001, atol=1.19209e-06

(mismatch 100.0%)
 x: array([[ 0.984587,  0.070094,  0.008218,  0.007741,  0.00821 , -0.019064,
        -0.015823],
       [ 0.070094,  0.550056, -0.036018, -0.083303, -0.064271,  0.115993,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],...
```
If I bump the C compiler optimizations back up to `-O3` (but leave fortran at `-O1`), I'm back to 6 errors and 17 failures.

**Comment by Eric89GXL** [comment]
So to summarize:
```
 C   F  Failures Errors
O3  O1        17      6
O1  O3        22      0
O1  O1        16      0
```
So it looks like the optimizations are problematic for both C and Fortran, and there is some new issue in `scipy` relative to 0.15 that isn't solved by `-O1`ing both of them, namely the `test_decomp_update.*` functions.

**Comment by rgommers** [comment]
Fixed in gh-4990
