### ISSUE TITLE
Unable to run ScrollingPlot example

### ISSUE THREAD

**Issue by wakatana** [scipy/scipy#4988]
Following example http://wiki.scipy.org/Cookbook/Matplotlib/ScrollingPlot?action=show throws following error:
Traceback (most recent call last):
  File "scrollingPlot.py", line 88, in <module>
    app = MyApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "scrollingPlot.py", line 82, in OnInit
    self.frame = MyFrame(parent=None,id=-1)
  File "scrollingPlot.py", line 21, in __init__
    self.scroll_range)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 11226, in SetScrollbar
    return _core_.Window_SetScrollbar(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "sb" failed at ../src/gtk/window.cpp(4754) in SetScrollbar(): this window is not scrollable

The discussion is also on SO http://stackoverflow.com/questions/31001713/plotting-the-data-with-scrollable-x-time-horizontal-axis-on-linux

**Comment by rgommers** [comment]
@wakatana this is about Matplotlib, not Scipy. So you'll want to report this at https://github.com/matplotlib/matplotlib.

**Comment by rgommers** [comment]
By the way, if it turns out that it's the example that needs editing because it is outdated instead of an actual Matplotlib or WxPython bug, and none of the Matplotlib devs have edit rights on that page, then feel free to ping me here.

**Comment by wakatana** [comment]
@rgommers I've opened the issue on matplotlib https://github.com/matplotlib/matplotlib/issues/4552
