### ISSUE TITLE
failing stats.histogram test with numpy 1.10

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5173]
The failing test seems to be incorrect and needs fixing, see details at https://github.com/numpy/numpy/issues/6120

    FAIL: test_weighting (test_stats.TestHistogram)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 892, in test_weighting
        decimal=2)
      File "/home/charris/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
        precision=decimal)
      File "/home/charris/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not almost equal to 2 decimals

    (mismatch 40.0%)
     x: array([   4. ,    0. ,    4.5,   -0.9,    0. ,    0.3,  110.2,    0. ,
              0. ,   42. ])
     y: array([   4. ,    0. ,    4.5,   -0.9,    0.3,    0. ,    7. ,  103.2,
              0. ,   42. ])

**Comment by rgommers** [comment]
(planned on fixing this, but I won't get around to it anytime soon)

**Comment by rgommers** [comment]
ideally this should go into 0.16.1
