### ISSUE TITLE
Scipy 0.16.x - TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

### ISSUE THREAD

**Issue by cgohlke** [scipy/scipy#5191]
The scipy maintenance 0.16.x branch fails the following tests. See also <https://github.com/scipy/scipy/commit/6692cd63694f967eb9d7b31a4916421d41117946> and <https://github.com/scipy/scipy/blob/maintenance/0.16.x/scipy/_lib/_util.py#L92>.
```
======================================================================
ERROR: test_basic.TestOverwrite.test_solve_banded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 957, in test_solve_banded
    [(4,6), (6,)])
  File "X:\Python35\lib\site-packages\scipy\linalg\_testutils.py", line 62, in assert_no_overwrite
    call(*inputs)
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 956, in <lambda>
    assert_no_overwrite(lambda ab, b: solve_banded((2,1), ab, b),
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_1x1 (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 160, in test_1x1
    x = solve_banded((1, 1), [[0], [1], [0]], [[1, 2, 3]])
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_bad_shape (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 153, in test_bad_shape
    assert_raises(ValueError, solve_banded, (l, u), ab, bad)
  File "X:\Python35\lib\site-packages\numpy\testing\utils.py", line 1054, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "X:\Python35\lib\unittest\case.py", line 724, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "X:\Python35\lib\unittest\case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_check_finite (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 143, in test_check_finite
    x = solve_banded((l, u), ab, b4, check_finite=False)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_complex (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 91, in test_complex
    x = solve_banded((l, u), ab, b)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_real (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 67, in test_real
    x = solve_banded((l, u), ab, b)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_tridiag_complex (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 129, in test_tridiag_complex
    x = solve_banded((1, 1), ab, b)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'

======================================================================
ERROR: test_tridiag_real (test_basic.TestSolveBanded)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_basic.py", line 110, in test_tridiag_real
    x = solve_banded((1, 1), ab, b)
  File "X:\Python35\lib\site-packages\scipy\linalg\basic.py", line 216, in solve_banded
    a1 = _asarray_validated(ab, check_finite=check_finite, as_inexact=True)
TypeError: _asarray_validated() got an unexpected keyword argument 'as_inexact'
```

**Comment by ev-br** [comment]
Thanks --- fix in gh-5192.
