### ISSUE TITLE
mstats: test_kurtosis fails (ULP max is 2)

### ISSUE THREAD

**Issue by andsor** [scipy/scipy#5197]
Hi, today I came across and wanted to report this minor issue in a cluster environment, using Python 3.4.3 (GCC 4.7.2), numpy 1.9.2 and scipy 0.16.0:

```bash
$ python -c 'import scipy; scipy.test()'
Running unit tests for scipy
NumPy version 1.9.2
NumPy is installed in /home/sorge/install-numpy/lib/python3.4/site-packages/numpy
SciPy version 0.16.0
SciPy is installed in /home/sorge/install-numpy/lib/python3.4/site-packages/scipy
Python version 3.4.3 (default, Aug 27 2015, 23:08:30) [GCC 4.7.2]
nose version 1.3.7
...
======================================================================
FAIL: test_kurtosis (test_mstats_basic.TestMoments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sorge/install-numpy/lib/python3.4/site-packages/scipy/stats/tests/test_mstats_basic.py", line 414, in test_kurtosis
    stats.kurtosis(self.testcase_2d[2, :]))
  File "/home/sorge/install-numpy/lib/python3.4/site-packages/numpy/testing/utils.py", line 1358, in assert_array_almost_equal_nulp
    raise AssertionError(msg)
AssertionError: X and Y are not equal to 1 ULP (max is 2)

----------------------------------------------------------------------
Ran 18295 tests in 244.049s

FAILED (KNOWNFAIL=98, SKIP=1190, failures=1)
```

Here is some debug output
```python
        import numpy as np
        ax = np.abs(x)
        ay = np.abs(y)
        ref = nulp * np.spacing(np.where(ax > ay, ax, ay))
        if not np.all(np.abs(x-y) <= ref):
            if np.iscomplexobj(x) or np.iscomplexobj(y):
                msg = "X and Y are not equal to %d ULP" % nulp
            else:
                max_nulp = np.max(nulp_diff(x, y))
                msg = "X and Y are not equal to %d ULP (max is %g)" % (nulp, max_nulp)
>           raise AssertionError(msg)
E           AssertionError: X and Y are not equal to 1 ULP (max is 2)

../../../numpy/testing/utils.py:1358: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/sorge/install-numpy/lib/python3.4/site-packages/numpy/testing/utils.py(1358)assert_array_almost_equal_nulp()
-> raise AssertionError(msg)
(Pdb) p x, y, ax, ay, nulp, ref, x - y, nulp_diff(x, y)
(-1.4724705238455413, -1.472470523845541, 1.4724705238455413, 1.4724705238455409, 1, 2.2204460492503131e-16, -4.4408920985006262e-16, 2.0)
```

```bash
$ python -c 'import scipy; scipy.show_config()'
atlas_blas_threads_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
    library_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    include_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/include']
    language = f77
    libraries = ['lapack', 'f77blas', 'cblas', 'atlas']
blas_opt_info:
    library_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    include_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/include']
    language = c
    libraries = ['f77blas', 'cblas', 'atlas']
atlas_blas_info:
    library_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    include_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/include']
    language = c
    libraries = ['f77blas', 'cblas', 'atlas']
atlas_3_10_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
lapack_opt_info:
    library_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.4\\""')]
    include_dirs = ['/usr/nld/atlas-3.8.4-skadi-seq/include']
    language = f77
    libraries = ['lapack', 'f77blas', 'cblas', 'atlas']
openblas_lapack_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
```

ATLAS has been compiled with GCC 4.3.4

Some system info:
```python
{'architecture': ('64bit', 'ELF'),
 'libc_ver': ('glibc', '2.9'),
 'linux_distribution': ('SUSE Linux Enterprise Server ', '11', 'x86_64'),
 'machine': 'x86_64',
 'packages': {'nose': '1.3.7',
              'numpy': '1.9.2',
              'pip': '7.1.2',
              'pkginfo': '1.2.1',
              'py': '1.4.30',
              'pytest': '2.7.2',
              'readline': '6.2.4.1',
              'scipy': '0.16.0',
              'setuptools': '18.2',
              'six': '1.9.0'},
 'platform_info': 'Linux-2.6.32.59-0.7-default-x86_64-with-SuSE-11-x86_64',
 'platform_release': '2.6.32.59-0.7-default',
 'prefix': '/home/sorge/install-numpy',
 'processor': 'x86_64',
 'python_branch': '',
 'python_build': ('default', 'Aug 27 2015 23:08:30'),
 'python_compiler': 'GCC 4.7.2',
 'python_executable': '/home/sorge/install-numpy/bin/python',
 'python_implementation': 'CPython',
 'python_revision': '',
 'python_version': '3.4.3',
 'python_version_info': sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0),
 'system': 'Linux',
 'system_version': '#1 SMP 2012-07-13 15:50:56 +0200'}
```

**Comment by ev-br** [comment]
Ugh. This is strange given that stats.kurtosis (https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L1270) and mstats.kurtosis (https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py#L1898) are essentially the same modulo nan_policy/masked stuff.
I don't believe it's the difference between `n*n` vs `n**2`, can it be.

Maybe it's a test case being too strinent --- we often check equality in floating point by just `assert_allclose(..., ..., rtol=1e-14)`.

I tried reproducing the problem on py 2.7 and I cannot (is it something about py/3?). Are you interested in looking into the @andsor?

**Comment by andsor** [comment]
Hm, debugging stats.kurtosis and mstats.kurtosis in parallel with the test dataset, I get different values for m2:

mstats.kurtosis.m2:
```
masked_array(data = 0.11202148916932528,
             mask = False,
       fill_value = 1e+20)
```

stats.kurtosis.m2:
```
0.11202148916932526
```

Investigating further, it turns out that in stats.moments the following is broken:
```
(Pdb) p a_zero_mean[0]
0.25375743000000001
(Pdb) a_zero_mean[0]**2
0.064392833280204911
(Pdb) p s[0]
0.064392833280204897
(Pdb) p s[0] - a_zero_mean[0]**2
-1.3877787807814457e-17
```

while in mstats
```
(Pdb) p s[0]
0.064392833280204911
(Pdb) p a_zero_mean[0]
0.25375743000000001
(Pdb) a_zero_mean[0]**2
0.064392833280204911
(Pdb) p s[0] - a_zero_mean[0]**2
0.0
```

Here is the file I use:
```
from __future__ import division, print_function, absolute_import

import numpy as np
import numpy.ma as ma

import scipy.stats.mstats as mstats
from scipy import stats
from numpy.ma.testutils import assert_array_almost_equal_nulp

from pprint import pprint


testcase_2d = ma.array(
np.array([[0.05245846, 0.50344235, 0.86589117, 0.36936353, 0.46961149],
       [0.11574073, 0.31299969, 0.45925772, 0.72618805, 0.75194407],
       [0.67696689, 0.91878127, 0.09769044, 0.04645137, 0.37615733],
       [0.05903624, 0.29908861, 0.34088298, 0.66216337, 0.83160998],
       [0.64619526, 0.94894632, 0.27855892, 0.0706151, 0.39962917]]),
mask=np.array([[True, False, False, True, False],
       [True, True, True, False, True],
       [False, False, False, False, False],
       [True, True, True, True, True],
       [False, False, True, False, False]], dtype=np.bool))

pprint(testcase_2d)

import pdb; pdb.set_trace()

mstats_kurtosis = mstats.kurtosis(testcase_2d[2, :])
stats_kurtosis = stats.kurtosis(testcase_2d[2, :])

pprint(mstats_kurtosis)
pprint(stats_kurtosis)

# Check consistency between stats and mstats implementations
assert_array_almost_equal_nulp(mstats_kurtosis, stats_kurtosis)
```

**Comment by ev-br** [comment]
This is baffling. Can it be that `a.mean()` with `a` being a masked array with all mask=False and `np.mean(a)` with a an `ndarray` being different by an ulp? Chasing an ulp of a difference is pretty weird

**Comment by andsor** [comment]
Agree. And I have no problem with relaxing the test a bit. I think it is the **2 operation. Running the following

```python
from __future__ import division, print_function, absolute_import

import numpy as np
import numpy.ma as ma

import scipy.stats.mstats as mstats
from scipy import stats

from pprint import pprint


testcase_2d = ma.array(
np.array([[0.05245846, 0.50344235, 0.86589117, 0.36936353, 0.46961149],
       [0.11574073, 0.31299969, 0.45925772, 0.72618805, 0.75194407],
       [0.67696689, 0.91878127, 0.09769044, 0.04645137, 0.37615733],
       [0.05903624, 0.29908861, 0.34088298, 0.66216337, 0.83160998],
       [0.64619526, 0.94894632, 0.27855892, 0.0706151, 0.39962917]]),
mask=np.array([[True, False, False, True, False],
       [True, True, True, False, True],
       [False, False, False, False, False],
       [True, True, True, True, True],
       [False, False, True, False, False]], dtype=np.bool))

pprint(testcase_2d)

a = testcase_2d[2, :]
axis = 0

mstats_a_zero_mean = a - ma.expand_dims(a.mean(axis), axis)
a = np.asarray(a)
stats_a_zero_mean = a - np.expand_dims(np.mean(a, axis), axis)
pprint(mstats_a_zero_mean - stats_a_zero_mean)

mstats_s = mstats_a_zero_mean**2
stats_s = stats_a_zero_mean**2

pprint(mstats_s - stats_s)

```

outputs

```python
masked_array(data =
 [[-- 0.50344235 0.86589117 -- 0.46961149]
 [-- -- -- 0.72618805 --]
 [0.67696689 0.91878127 0.09769044 0.04645137 0.37615733]
 [-- -- -- -- --]
 [0.64619526 0.94894632 -- 0.0706151 0.39962917]],
             mask =
 [[ True False False  True False]
 [ True  True  True False  True]
 [False False False False False]
 [ True  True  True  True  True]
 [False False  True False False]],
       fill_value = 1e+20)

masked_array(data = [0.0 0.0 0.0 0.0 0.0],
             mask = [False False False False False],
       fill_value = 1e+20)

masked_array(data = [  1.38777878e-17   0.00000000e+00   1.38777878e-17   0.00000000e+00
   0.00000000e+00],
             mask = False,
       fill_value = 1e+20)

```

**Comment by andsor** [comment]
As it seems to be a local or a numpy issue, I think we can close this here for now. However, the test could still be relaxed?

**Comment by rgommers** [comment]
Let's keep this open until we've relaxed the test tolerance. Maybe 1 ulp to 4 ulp to be on the safe side.

Marking as easy-fix.

**Comment by andsor** [comment]
OK thanks, I submitted a PR
