### ISSUE TITLE
ImportError: No module named decorator

### ISSUE THREAD

**Issue by jpiabrantes** [scipy/scipy#5240]
Yesterday I installed python scikit-learn to use its PCA algorithm and it worked fine. Today I rebooted the computer and when I try to import the PCA module by doing: ```from sklearn.decomposition import PCA```

Scipy gives me the following error on one IDE:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/joao/PCA/dices.py", line 11, in <module>
    from sklearn.decomposition import PCA
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/__init__.py", line 7, in <module>
    from .nmf import NMF, ProjectedGradientNMF
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/nmf.py", line 19, in <module>
    from scipy.optimize import nnls
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/__init__.py", line 148, in <module>
    from ._root import *
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/_root.py", line 20, in <module>
    from . import nonlin
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/nonlin.py", line 122, in <module>
    import scipy.sparse.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/__init__.py", line 108, in <module>
    from .isolve import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 7, in <module>
    from . import _iterative
ImportError: cannot import name _iterative
```

and this one on another:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/__init__.py", line 7, in <module>
    from .nmf import NMF, ProjectedGradientNMF
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/nmf.py", line 19, in <module>
    from scipy.optimize import nnls
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/__init__.py", line 148, in <module>
    from ._root import *
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/_root.py", line 20, in <module>
    from . import nonlin
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/nonlin.py", line 122, in <module>
    import scipy.sparse.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/__init__.py", line 108, in <module>
    from .isolve import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 11, in <module>
    from scipy.lib.decorator import decorator
ImportError: No module named decorator
```

I am using ubuntu 14

**Comment by larsmans** [comment]
Is the file `/usr/lib/python2.7/dist-packages/scipy/lib/decorator.py` present on your system?

**Comment by rgommers** [comment]
``scipy.lib`` was renamed to ``scipy._lib`` quite a while ago, so this is for some older Scipy install or a mixup of two Scipy installs. So closing.

@jpiabrantes feel free to follow up though, we'll help you out if you're still stuck.

**Comment by DanlanChen** [comment]
what is the solution, I am using scipy 0.17.0, I do not have decorator in my scipy._lib

**Comment by DanlanChen** [comment]
I checked my decorator.py is an archive file,what should i do?

**Comment by ilayn** [comment]
Seems like you have two scipy installations interfering with each other. The solution is actually "That shouldn't happened"

**Comment by LujunWeng** [comment]
I got a similar issue. Uninstalling and reinstalling scipy solved it.

**Comment by yosunpeng** [comment]
Your scipy version is old, try ' pip install -U scipy ' .  If it is failed, you may check  #issue504 https://github.com/blockstack/blockstack-core/issues/504

**Comment by monjoybme** [comment]
This is just an update. I also faced same error. Solution of this issue is installation of below package.
`sudo apt install --reinstall python*-decorator`
