### ISSUE TITLE
0.16.0 Fails to install in MacOS with easy-install 2.7 and setuptools==18.3.2 

### ISSUE THREAD

**Issue by papachoco** [scipy/scipy#5284]
When trying to install scipy with easy-install-2.7 (after successfully installing numpy) I get the error below. 

Carlos

Reading https://pypi.python.org/simple/scipy/
Best match: scipy 0.16.0
Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.16.0.zip#md5=1764bd452a72698b968ad13e51e28053
Processing scipy-0.16.0.zip
Writing /tmp/easy_install-Kq8fx1/scipy-0.16.0/setup.cfg
Running scipy-0.16.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Kq8fx1/scipy-0.16.0/egg-dist-tmp-smgRw6
Running from scipy source directory.
Splitting linalg.interpolative Fortran source files
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.9.3-py2.7-macosx-10.10-x86_64.egg/numpy/distutils/system_info.py:594: UserWarning: Specified path /usr/local/include/python2.7 is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
non-existing path in '/private/tmp/easy_install-Kq8fx1/scipy-0.16.0/scipy/spatial': 'ckdtree.cxx'
non-existing path in '/private/tmp/easy_install-Kq8fx1/scipy-0.16.0/scipy/spatial': 'ckdtree/src/ckdtree_decl.h'
non-existing path in '/private/tmp/easy_install-Kq8fx1/scipy-0.16.0/scipy/spatial': 'ckdtree/src/ckdtree_exc.h'
non-existing path in '/private/tmp/easy_install-Kq8fx1/scipy-0.16.0/scipy/spatial': 'ckdtree/src/ckdtree_methods.h'
non-existing path in '/private/tmp/easy_install-Kq8fx1/scipy-0.16.0/scipy/spatial': 'ckdtree/src/ckdtree_utils.h'
Traceback (most recent call last):
  File "./bin/easy_install-2.7", line 9, in <module>
    load_entry_point('setuptools==18.3.2', 'console_scripts', 'easy_install-2.7')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2279, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 638, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1065, in run_setup
    run_setup(setup_script, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 138, in resume
    type, exc = map(pickle.loads, self._saved)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by papachoco** [comment]
Not sure if this is a setuptools bug...

**Comment by matthew-brett** [comment]
It might be - I'm afraid I don't think any developer is using `easy_install` these days.  Could you try pip instead?

**Comment by papachoco** [comment]
I am trying to install scipy under zc.buildout. Cython and numpy install fine w/ setuptools (easy-install). I am trying other buildout recipes to use pip.

**Comment by rgommers** [comment]
@papachoco ``easy_install`` isn't supported anymore and hasn't been for a long time (not by us nor by the Python packaging developers), so I'm going to go ahead and close this issue. Please reopen or open a new issue if you run into an issue installing Scipy with Pip.
