### ISSUE TITLE
Test failure when building with Python v 3.5

### ISSUE THREAD

**Issue by woodscn** [scipy/scipy#5298]
Running scipy.test() yields an assertion error under Python3.5. It looks like a new DeprecationWarning preempted the expected OptimizeWarning. Am I correct to assume that this is probably nothing to worry about?

Cython, numpy, nose installed with conda, scipy built from source. OS X 10.10, clang v 6.1.0 (clang-602.0.53), gfortran 5.1.0, FFLAGS=-ff2c

```=====================================================================
FAIL: test_indeterminate_covariance (test_minpack.TestCurveFit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lwoodscn/anaconda/envs/scipy_dev/lib/python3.5/site-packages/scipy/optimize/tests/test_minpack.py", line 397, in test_indeterminate_covariance
    _assert_warns(OptimizeWarning, curve_fit, lambda x, a, b: a*x, xdata, ydata)
  File "/Users/lwoodscn/anaconda/envs/scipy_dev/lib/python3.5/site-packages/numpy/testing/utils.py", line 1603, in assert_warns
    "%s( is %s)" % (func.__name__, warning_class, l[0]))
AssertionError: First warning for curve_fit is not a <class 'scipy.optimize.optimize.OptimizeWarning'>( is {message : DeprecationWarning('inspect.getargspec() is deprecated, use inspect.signature() instead',), category : 'DeprecationWarning', filename : '/Users/lwoodscn/anaconda/envs/scipy_dev/lib/python3.5/site-packages/scipy/optimize/minpack.py', lineno : 545, line : None})```

**Comment by ev-br** [comment]
This is mostly harmless and is going to be fixed by either gh-4928 or gh-5248, whichever lands first.

**Comment by woodscn** [comment]
Good to hear. I figured as much.

**Comment by rgommers** [comment]
gh-5248 now merged, so this is fixed.
