### ISSUE TITLE
what is np.square of a sparse matrix

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#5317]
According to http://stackoverflow.com/questions/32958913 it is the matrix square, which is inconsistent with np.ndarray and np.matrix where it is the elementwise square.

I can imagine an alternate history where it would have been one of these functions:
https://github.com/scipy/scipy/blob/maintenance/0.16.x/scipy/sparse/base.py#L51

**Comment by pv** [comment]
np.square of sparse matrix is undefined behavior, similarly as in
calling other np. functions on sparse matrices. What it currently does
is that it probably casts sparse matrices to 1-element scalar object
arrays and works from there...

**Comment by argriffing** [comment]
> similarly as in calling other np. functions on sparse matrices

Maybe similar to some, but not similar to np.sin, np.tan, np.arcsin, np.arctan, np.sinh, np.tanh, np.arcsinh, np.arctanh, np.rint, np.sign, np.expm1, np.log1p, np.deg2rad, np.rad2deg, np.floor, np.ceil, np.trunc, np.sqrt. Would it make sense to add np.square to this list with deprecation?

**Comment by pv** [comment]
This all follows from the crazy object array stuff that ufuncs do. ``np.sin(spmatrix)`` is equivalent to
```
tmp = np.array([spmatrix], dtype=object)
tmp2 = np.sin(tmp)
# -> np.sin is an ufunc with explicit object array fallback that does
#     for i in range(tmp.size): tmp2[i] = tmp[i].sin()
return tmp2.item()
```
The `square` ufunc of course just does `tmp2[i] = tmp[i]*tmp[i]` so there's no way to override it.

Of course, the `numpy_ufunc` stuff would allow fixing the situation, but following the discussion it probably cannot actually be used for sparse matrices, because the design we finally converged to enforces ndarray semantics too strongly.

**Comment by pv** [comment]
This part of Numpy codebase is not very easy to find, so here is the relevant part:
https://github.com/numpy/numpy/blob/master/numpy/core/code_generators/generate_umath.py#L332
The object array fallback `Py_square(obj)` is defined as `PyNumber_Multiply(obj,obj)`.

**Comment by argriffing** [comment]
Using recent numpy and scipy I tried this:
```python
>>> s = csr_matrix(np.ones((2, 2)))
>>> s.toarray()
array([[ 1.,  1.],
       [ 1.,  1.]])
>>> np.square(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __numpy_ufunc__ not implemented for this type.
```
and with the similar result for lil_matrix.

Using the example on stackexchange:
```python
>>> a = np.array([np.arange(5), np.arange(5), np.arange(5), np.arange(5), np.arange(5)])
>>> a
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])
>>> b = scipy.sparse.lil_matrix(a)
>>> c = np.square(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __numpy_ufunc__ not implemented for this type.
```

**Comment by pv** [comment]
The `numpy_ufunc` implementation in numpy master is subject to change --- what it does currently is not so important. It's not present in released versions.

**Comment by argriffing** [comment]
I see, this must be related to the discussion on that numpy dispatching thread https://github.com/numpy/numpy/issues/5844

**Comment by rgommers** [comment]
With recent numpy the behavior changed, e.g. with 1.16.4 (should still be the same in 1.17.x):

``` python
>>> s = csr_matrix(np.ones((2, 2)))
>>> s.toarray()
array([[ 1.,  1.],
       [ 1.,  1.]])
>>> np.square(s)
>>> s = csr_matrix(np.ones((2, 2)))
>>> s.toarray()
```

``` python
>>> a = np.array([np.arange(5), np.arange(5), np.arange(5), np.arange(5), np.arange(5)])
>>> a
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])
>>> b = scipy.sparse.lil_matrix(a)
>>> c = np.square(b)
>>> b                                                                                 
<5x5 sparse matrix of type '<class 'numpy.int64'>'
        with 20 stored elements in LInked List format>
>>> c                                                                                 
<5x5 sparse matrix of type '<class 'numpy.int64'>'
        with 20 stored elements in Compressed Sparse Row format>
>>> b.data                                                                            
array([list([1, 2, 3, 4]), list([1, 2, 3, 4]), list([1, 2, 3, 4]),
       list([1, 2, 3, 4]), list([1, 2, 3, 4])], dtype=object)
>>> c.data                                                                            
array([40, 30, 20, 10, 40, 30, 20, 10, 40, 30, 20, 10, 40, 30, 20, 10, 40,
       30, 20, 10], dtype=int64)
```

still not the same as `np.square(b.toarray())` of course.
