### ISSUE TITLE
errors on windows 32 and 64 bit with numpy 1.10.0

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#5331]
sorry, not sure I should post on Numpy or scipy
````
`Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scipy;scipy.test()
Running unit tests for scipy
NumPy version 1.10.0
NumPy relaxed strides checking option: True
NumPy is installed in D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy
SciPy version 0.16.0
SciPy is installed in D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy
Python version 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
nose version 1.3.7
...................
````
````
======================================================================
ERROR: test_basic.test_xlogy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3080, in test_xlogy
    w2 = np.vectorize(xfunc)(z2[:,0], z2[:,1])
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\lib\function_base.py", line 1811, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\lib\function_base.py", line 1880, in _vectorize_call
    outputs = ufunc(*inputs)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3073, in xfunc
    return x*np.log(y)
RuntimeWarning: invalid value encountered in log

======================================================================
ERROR: test_stats.test_chisquare_masked_arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\tests\test_stats.py", line 1931, in test_chisquare_masked_arrays
    chisq, p = stats.chisquare(np.ma.array([]))
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\stats.py", line 4143, in chisquare
    lambda_="pearson")
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\stats.py", line 3997, in power_divergence
    f_exp = np.atleast_1d(f_obs.mean(axis=axis))
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\ma\core.py", line 4987, in mean
    result = super(MaskedArray, self).mean(axis=axis, dtype=dtype)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\core\_methods.py", line 59, in _mean
    warnings.warn("Mean of empty slice.", RuntimeWarning)
RuntimeWarning: Mean of empty slice.

======================================================================
FAIL: test_weighting (test_stats.TestHistogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\tests\test_stats.py", line 892, in test_weighting
    decimal=2)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\testing\utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 40.0%)
 x: array([   4. ,    0. ,    4.5,   -0.9,    0. ,    0.3,  110.2,    0. ,
          0. ,   42. ])
 y: array([   4. ,    0. ,    4.5,   -0.9,    0.3,    0. ,    7. ,  103.2,
          0. ,   42. ])

----------------------------------------------------------------------
Ran 18296 tests in 680.155s

FAILED (KNOWNFAIL=98, SKIP=1168, errors=2, failures=1)
<nose.result.TextTestResult run=18296 errors=2 failures=1>
>>> 
```

**Comment by stonebig** [comment]
also some Warnings, I'm not sure if it's important:
````
Warning (from warnings module):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\matrixlib\defmatrix.py", line 318
    out = N.ndarray.__getitem__(self, index)
VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 10 but corresponding boolean dimension is 5
````

**Comment by charris** [comment]
The last is a known issue for scipy. The first two runtime warnings should have been ignored rather than raising errors unless you are running a development numpy version.  So no real problems, but there may be a bug in the distribution. Where did you get numpy?

**Comment by stonebig** [comment]
at cgohlke's

**Comment by charris** [comment]
Hmm, so you don't have the source. The numpy 1.10.0 source looks correct here, so raising RuntimeWarnings as errors should be disabled, but there may be a flaw in the test runner logic somewhere. Anyway, you should be good.

**Comment by stonebig** [comment]
I'm asking  cgohlke for the warning option

**Comment by charris** [comment]
This is looking like a problem with the test runner.

**Comment by stonebig** [comment]
a yes, I didn't rolled up at that time because the bottom result was "ok".

**Comment by stonebig** [comment]
with numpy 0.10.1 no change:
````
>>> import scipy;scipy.test()
Running unit tests for scipy
NumPy version 1.10.1
NumPy relaxed strides checking option: True
NumPy is installed in D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy
SciPy version 0.16.0
SciPy is installed in D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy
Python version 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
nose version 1.3.7
......................

======================================================================
ERROR: test_basic.test_xlogy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3080, in test_xlogy
    w2 = np.vectorize(xfunc)(z2[:,0], z2[:,1])
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\lib\function_base.py", line 1811, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\lib\function_base.py", line 1880, in _vectorize_call
    outputs = ufunc(*inputs)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3073, in xfunc
    return x*np.log(y)
RuntimeWarning: invalid value encountered in log

======================================================================
ERROR: test_stats.test_chisquare_masked_arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\tests\test_stats.py", line 1931, in test_chisquare_masked_arrays
    chisq, p = stats.chisquare(np.ma.array([]))
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\stats.py", line 4143, in chisquare
    lambda_="pearson")
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\stats.py", line 3997, in power_divergence
    f_exp = np.atleast_1d(f_obs.mean(axis=axis))
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\ma\core.py", line 4987, in mean
    result = super(MaskedArray, self).mean(axis=axis, dtype=dtype)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\core\_methods.py", line 59, in _mean
    warnings.warn("Mean of empty slice.", RuntimeWarning)
RuntimeWarning: Mean of empty slice.

======================================================================
FAIL: test_weighting (test_stats.TestHistogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\scipy\stats\tests\test_stats.py", line 892, in test_weighting
    decimal=2)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\testing\utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 40.0%)
 x: array([   4. ,    0. ,    4.5,   -0.9,    0. ,    0.3,  110.2,    0. ,
          0. ,   42. ])
 y: array([   4. ,    0. ,    4.5,   -0.9,    0.3,    0. ,    7. ,  103.2,
          0. ,   42. ])

----------------------------------------------------------------------
Ran 18296 tests in 545.021s

FAILED (KNOWNFAIL=98, SKIP=1168, errors=2, failures=1)
<nose.result.TextTestResult run=18296 errors=2 failures=1>
>>> 
````

**Comment by rgommers** [comment]
It's a ``numpy.testing`` issue in 1.10.x, I'll send a fix.

**Comment by rgommers** [comment]
This was forgotten: https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt#handle-test-warnings

**Comment by rgommers** [comment]
We should also fix the warnings in the scipy test suite. Will do that.

**Comment by stonebig** [comment]
so numpy 1.10.1 is `safe` ?

**Comment by rgommers** [comment]
The numpy issue is now fixed in 1.10.x (will be in 1.10.2) and the warnings and test failures are both fixed in scipy 0.16.1 which will be released this weekend. So closing this.

@stonebig and yes, 1.10.1 is safe to use. Thanks for reporting these issues.

**Comment by stonebig** [comment]
today, on cgohlke wheel 1.10.2 of december 15th, I stille get that error:

````
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scipy;scipy.test()
Running unit tests for scipy
NumPy version 1.10.2
NumPy relaxed strides checking option: False
NumPy is installed in D:\WinPython\basedir34\build\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\numpy
SciPy version 0.16.1
SciPy is installed in D:\WinPython\basedir34\build\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\scipy
Python version 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
nose version 1.3.7
....

Warning (from warnings module):
  File "D:\WinPython\basedir34\build\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3084
    return x*np.log(y)
RuntimeWarning: invalid value encountered in log
````

**Comment by stonebig** [comment]
apparently, the warning is still there:
````
invalid value encountered in log

**Comment by ev-br** [comment]
Which test is this --- can you run `>>> scipy.test(verbose=2)`

**Comment by stonebig** [comment]
````
test_basic.test_legacy ... ok
test_basic.test_xlogy ... 
Warning (from warnings module):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\scipy\special\tests\test_basic.py", line 3111
    return x*np.log(y)
RuntimeWarning: invalid value encountered in log
ok
test_basic.test_xlog1py ... ok
````
