### ISSUE TITLE
pip install fails on Raspbian Jessy with Raspberry Pi 1

### ISSUE THREAD

**Issue by Arn-O** [scipy/scipy#5342]
Hi.

I was able to install SciPy with ``pip`` on Raspbian Wheezy, but on the very same device, the very same install fails.

Here is the tail in high verbosity:

```
    c++: scipy/sparse/sparsetools/csr.cxx
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from scipy/sparse/sparsetools/sparsetools.h:5,
                     from scipy/sparse/sparsetools/csr.cxx:4:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    c++: scipy/sparse/sparsetools/other.cxx
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from scipy/sparse/sparsetools/sparsetools.h:5,
                     from scipy/sparse/sparsetools/other.cxx:4:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    c++: scipy/sparse/sparsetools/bsr.cxx
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from scipy/sparse/sparsetools/sparsetools.h:5,
                     from scipy/sparse/sparsetools/bsr.cxx:4:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                     from scipy/sparse/sparsetools/sparsetools.h:5,
                     from scipy/sparse/sparsetools/bsr.cxx:4:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
    error: Command "c++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__STDC_FORMAT_MACROS=1 -Iscipy/sparse/sparsetools -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c scipy/sparse/sparsetools/bsr.cxx -o build/temp.linux-armv6l-2.7/scipy/sparse/sparsetools/bsr.o" failed with exit status 4
    
    ----------------------------------------
Cleaning up...
  Removing source in /tmp/pip-build-Ccs3JC/scipy
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 852, in install
    show_stdout=False,
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ccs3JC/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KgyOIr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Ccs3JC/scipy
 ```

I tried 2 times from scratch, after a fresh OS install.

Link to the full output:

https://www.dropbox.com/s/dyq0lc080jrn466/scipy.log?dl=0

Ar.

**Comment by rgommers** [comment]
I think you're simply running out of memory here. Try shutting down everything that you don't need and recompile. Then have a look at memory consumption while it's compiling  ``sparsetools``. You'll need 2Gb at least I believe.

**Comment by Arn-O** [comment]
Hi.

That's interesting. It doesn't explain why I have been able to build SciPy on Weezy, but since I'm not sure about the pre-installed package I had, there could be many explanations.

The RPi is limited in RAM to 512 GB of RAM. Nothing else is running apart from the compilation (even no graphical desktop). So I will temporarily extend the swap up to 2 GB following this link:

http://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space

Ar.
