### ISSUE TITLE
TypeError: minpack2.dcsrch() 2nd argument (f) can't be converted to double

### ISSUE THREAD

**Issue by ccorcos** [scipy/scipy#5360]
```
Traceback (most recent call last):
  File "forcast2.py", line 108, in <module>
    result = minimize(getCost, numpy.array(initialValues), method='BFGS', jac=costGrad, options={'disp': True})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/_minimize.py", line 370, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/optimize.py", line 850, in _minimize_bfgs
    old_fval, old_old_fval)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/optimize.py", line 685, in _line_search_wolfe12
    **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/linesearch.py", line 96, in line_search_wolfe1
    c1=c1, c2=c2, amax=amax, amin=amin, xtol=xtol)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/optimize/linesearch.py", line 164, in scalar_search_wolfe1
    amin, amax, isave, dsave)
TypeError: minpack2.dcsrch() 2nd argument (f) can't be converted to double
```

Not sure whats going on here.

```py
print 'initial values...'
print initialValues
print 'initial gradients...'
print costGrad(initialValues)

print 'optimizing...'
from scipy.optimize import minimize
result = minimize(getCost, initialValues, method='BFGS', jac=costGrad, options={'disp': True})
```

my initial gradients print out:

```
[ 15382.89863014  15382.89863013  15382.89863013  15382.89863014
  15382.89863016  15382.89863012  15382.89863013  15382.89863014
  15382.89863013  15382.89863013  15382.89863014  15382.89863016
  15382.89863012  15382.89863013  15382.89863014  15382.89863013
  15382.89863013  15382.89863014  15382.89863016  15382.89863012
  15382.89863013  15382.89863014  15382.89863013  15382.89863013
  15382.89863014  15382.89863016  15382.89863012  15382.89863013
  15382.89863014  15382.89863013  15382.89863013   7972.88767123
   7972.88767125   7972.88767122   7972.88767123   7972.88767124
   7972.88767123   7972.88767123   7972.88767123   7972.88767125
   7972.88767122   7972.88767123   7972.88767124   7972.88767123
   7972.88767123   7972.88767123   7972.88767125   7972.88767122
   7972.88767123   7972.88767124   7972.88767123   7972.88767123
   7972.88767123   7972.88767125   7972.88767122   7972.88767123
   7972.88767124   7972.88767123   7972.88767123  10999.3369863
  10999.33698632  10999.33698629  10999.3369863   10999.33698631
  10999.3369863   10999.3369863   10999.3369863   10999.33698632
  10999.33698629  10999.3369863   10999.33698631  10999.3369863
  10999.3369863   10999.3369863   10999.33698632  10999.33698629
  10999.3369863   10999.33698631  10999.3369863   10999.3369863
  10999.3369863   10999.33698632  10999.33698629  10999.3369863
  10999.33698631  10999.3369863   10999.3369863   10999.3369863
  10999.33698632  10999.33698629   8894.63013698   8894.63013699
   8894.63013698   8894.63013698   8894.63013699   8894.630137
   8894.63013697   8894.63013698   8894.63013699   8894.63013698
   8894.63013698   8894.63013699   8894.630137     8894.63013697
   8894.63013698   8894.63013699   8894.63013698   8894.63013698
   8894.63013699   8894.630137     8894.63013697   8894.63013698
   8894.63013699   8894.63013698   8894.63013698   8894.63013699
   8894.630137     8894.63013697   8894.63013698   8894.63013699
   9903.44657534   9903.44657534   9903.44657534   9903.44657536
   9903.44657533   9903.44657534   9903.44657535   9903.44657534
   9903.44657534   9903.44657534   9903.44657536   9903.44657533
   9903.44657534   9903.44657535   9903.44657534   9903.44657534
   9903.44657534   9903.44657536   9903.44657533   9903.44657534
   9903.44657535   9903.44657534   9903.44657534   9903.44657534
   9903.44657536   9903.44657533   9903.44657534   9903.44657535
   9903.44657534   9903.44657534   9903.44657534   5606.95890413
   5606.9589041    5606.95890411   5606.95890412   5606.95890411
   5606.9589041    5606.95890411   5606.95890413   5606.9589041
   5606.95890411   5606.95890412   5606.95890411   5606.9589041
   5606.95890411   5606.95890413   5606.9589041    5606.95890411
   5606.95890412   5606.95890411   5606.9589041    5606.95890411
   5606.95890413   5606.9589041    5606.95890411   5606.95890412
   5606.95890411   5606.9589041    5606.95890411   5606.95890413
   5606.9589041    1684.26849315   1684.26849316   1684.26849315
   1684.26849315   1684.26849315   1684.26849317   1684.26849314
   1684.26849315   1684.26849316   1684.26849315   1684.26849315
   1684.26849315   1684.26849317   1684.26849314   1684.26849315
   1684.26849316   1684.26849315   1684.26849315   1684.26849315
   1684.26849317   1684.26849314   1684.26849315   1684.26849316
   1684.26849315   1684.26849315   1684.26849315   1684.26849317
   1684.26849314   1684.26849315   1684.26849316   1684.26849315
  -1055.45753425  -1055.45753425  -1055.45753423  -1055.45753426
  -1055.45753425  -1055.45753424  -1055.45753425  -1055.45753425
  -1055.45753425  -1055.45753423  -1055.45753426  -1055.45753425
  -1055.45753424  -1055.45753425  -1055.45753425  -1055.45753425
  -1055.45753423  -1055.45753426  -1055.45753425  -1055.45753424
  -1055.45753425  -1055.45753425  -1055.45753425  -1055.45753423
  -1055.45753426  -1055.45753425  -1055.45753424  -1055.45753425
  -1055.45753425  -1055.45753425  -1055.45753423  -8091.67123289
  -8091.67123288  -8091.67123287  -8091.67123288  -8091.67123288
  -8091.67123288  -8091.67123286  -8091.67123289  -8091.67123288
  -8091.67123287  -8091.67123288  -8091.67123288  -8091.67123288
  -8091.67123286  -8091.67123289  -8091.67123288  -8091.67123287
  -8091.67123288  -8091.67123288  -8091.67123288  -8091.67123286
  -8091.67123289  -8091.67123288  -8091.67123287  -8091.67123288
  -8091.67123288  -8091.67123288  -8091.67123286  -8091.67123289
  -8091.67123288  -9274.63561643  -9274.63561644  -9274.63561644
  -9274.63561644  -9274.63561642  -9274.63561645  -9274.63561644
  -9274.63561643  -9274.63561644  -9274.63561644  -9274.63561642
  -9274.63561645  -9274.63561643  -9274.63561644  -9274.63561643
  -9274.63561644  -9274.63561644  -9274.63561644  -9274.63561642
  -9274.63561645  -9274.63561644  -9274.63561643  -9274.63561644
  -9274.63561644  -9274.63561644  -9274.63561642  -9274.63561645
  -9274.63561644  -9274.63561643  -9274.63561645  -9274.63561645
 -13571.12328767 -13571.12328765 -13571.12328768 -13571.12328768
 -13571.12328766 -13571.12328767 -13571.12328768 -13571.12328767
 -13571.12328765 -13571.12328768 -13571.12328768 -13571.12328766
 -13571.12328767 -13571.12328768 -13571.12328767 -13571.12328765
 -13571.12328768 -13571.12328768 -13571.12328766 -13571.12328767
 -13571.12328768 -13571.12328767 -13571.12328765 -13571.12328768
 -13571.12328768 -13571.12328766 -13571.12328767 -13571.12328768
 -13571.12328767 -13571.12328765 -28452.71780823 -28452.71780822
 -28452.71780821 -28452.71780822 -28452.71780822 -28452.71780822
 -28452.7178082  -28452.71780823 -28452.71780822 -28452.71780821
 -28452.71780822 -28452.71780822 -28452.71780822 -28452.7178082
 -28452.71780823 -28452.71780822 -28452.71780821 -28452.71780822
 -28452.71780822 -28452.71780822 -28452.7178082  -28452.71780823
 -28452.71780822 -28452.71780821 -28452.71780822 -28452.71780822
 -28452.71780822 -28452.7178082  -28452.71780823 -28452.71780822
 -28452.71780822]
```

and my initialValues

```
[284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109, 284109]
```

Nothing fancy going on here... just following aloing in this documentation:

http://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html

**Comment by pv** [comment]
Does your getCost return a single number?

**Comment by ccorcos** [comment]
ah. crap. its returning a theano tensor...
