### ISSUE TITLE
Test issue with test_quadpack and libm.so as a linker script

### ISSUE THREAD

**Issue by opoplawski** [scipy/scipy#5370]
On Fedora Rawhide (F24):

~~~~~
ERROR: test_typical (test_quadpack.TestCtypesQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/builddir/build/BUILDROOT/scipy-0.16.0-1.fc24.x86_64/usr/lib64/python2.7/site-packages/scipy/integrate/tests/test_quadpack.py", line 42, in setUp
    self.lib = ctypes.CDLL(file)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so: invalid ELF header
~~~~~
This is because libm.so is a GNU ld script:
~~~~~
# cat /usr/lib64/libm.so
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib64/libm.so.6  AS_NEEDED ( /lib64/libmvec.so.1 ) )
~~~~~

**Comment by opoplawski** [comment]
Some background: http://www.gossamer-threads.com/lists/python/dev/941581

**Comment by rgommers** [comment]
Thanks @opoplawski. Looks like it's just the test that needs a tweak. I'll send a fix for simply catching ``OSError``.
