### ISSUE TITLE
issue installing in Python 3.5

### ISSUE THREAD

**Issue by blade3** [scipy/scipy#5507]
HI,

someone can be help me?
I got an error when I use : 

```
pip install scipy
```

the stacktrace is:

```
C:\>pip install scipy
Collecting scipy
  Using cached scipy-0.16.1.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy
    Complete output from command c:\users\atchou\appdata\local\programs\python\python35-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\atchou\\AppData\\Local\\Temp\\pip-build-kwlcps1l\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\atchou\AppData\Local\Temp\pip-p1drhr4h-record\install-record.txt --single-version-externally-managed --compile:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
      libraries lapack_atlas not found in c:\users\atchou\appdata\local\programs\python\python35-32\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\atchou\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\atchou\AppData\Local\Temp\pip-build-kwlcps1l\scipy\setup.py", line 253, in <module>
        setup_package()
      File "C:\Users\atchou\AppData\Local\Temp\pip-build-kwlcps1l\scipy\setup.py", line 250, in setup_package
        setup(**metadata)
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\atchou\AppData\Local\Temp\pip-build-kwlcps1l\scipy\setup.py", line 175, in configuration
        config.add_subpackage('scipy')
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\atchou\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\atchou\appdata\local\programs\python\python35-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\atchou\\AppData\\Local\\Temp\\pip-build-kwlcps1l\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\atchou\AppData\Local\Temp\pip-p1drhr4h-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\atchou\AppData\Local\Temp\pip-build-kwlcps1l\scipy
```

**Comment by rgommers** [comment]
It can't find numpy, which should be installed first.

But more importantly: using ``pip`` will install Scipy from source. Unless you really know what you're doing, don't try that! Use a distribution like Anaconda or Canopy instead.
