### ISSUE TITLE
NetCDF maskandscale test failure on Windows XP

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5541]
```
======================================================================
ERROR: test_netcdf.test_maskandscale
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\scipy\io\tests\test_netcdf.py", line 330, in test_maskandscale
    assert_allclose(Temp[:].compressed(), expected)
  File "C:\Python27\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Python27\lib\site-packages\scipy\_lib\_tmpdirs.py", line 55, in in_tempdir
    rmtree(d)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\docume~1\\br\\locals~1\\temp\\tmpy1jbmg\\ms.nc'
```

same build as in #5540 and #5539.

@efiring any ideas on what this might be?

**Comment by pv** [comment]
The mmap cannot be closed because the `Temp` variable is still around.
Workaround for this test: use `mmap=False`

**Comment by efiring** [comment]
@pv Thanks--I would have been baffled.  It looks like an alternative fix would be to explicitly delete Temp at the end of the loop, correct?  And do you know why this problem crops up specifically with XP?

**Comment by ev-br** [comment]
FWIW it's not specific to XP, it shows up in Wine, too.

**Comment by pv** [comment]
On windows, open files cannot be unlinked.

**Comment by efiring** [comment]
So if Temp were deleted at the end of the loop, then the inner context manager would close the file, and the outer context manager would succeed, correct?
