### ISSUE TITLE
._ufuncs cannot load in scipy.special on Python 3.5. Something seems to be missing.

### ISSUE THREAD

**Issue by nashv** [scipy/scipy#5570]
Here is a traceback

>>> import czifile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\czifile.py", line 117, in <module>
    from scipy.ndimage.interpolation import zoom
  File "C:\Python35\lib\site-packages\scipy\ndimage\__init__.py", line 172, in <module>
    from .filters import *
  File "C:\Python35\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "C:\Python35\lib\site-packages\scipy\misc\__init__.py", line 49, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "C:\Python35\lib\site-packages\scipy\special\__init__.py", line 601, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
>>>

I verified that the .pyd file exists in the installation, but shouldn't there be a .py file as well ?
See screenshot 
![2015-12-02_05-45-33](https://cloud.githubusercontent.com/assets/62116/11522525/1dcd32a0-98b8-11e5-906d-3d198909282e.png)

**Comment by matthew-brett** [comment]
I'm guessing you're using Christoph Gohlke's wheels from : http://www.lfd.uci.edu/~gohlke/pythonlibs ?

I just made this mistake, but he points out at the top of the page, that you need the Visual C++ runtime from http://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by nashv** [comment]
Thanks for the reply, Matthew. But I have the Visual C++ Runtimes installed. I redid it just to be sure. Still the same issue.

![2015-12-02_05-56-47](https://cloud.githubusercontent.com/assets/62116/11522635/842efa32-98b9-11e5-8504-34a6a7583f73.png)

**Comment by pv** [comment]
Closing (feel free to discuss, but this bug is not fixable by us as it's 3rd party binaries).
