### ISSUE TITLE
tests in scipy 0.16.1 on top of numpy 1.10.1 yield DeprecationWarning

### ISSUE THREAD

**Issue by boegel** [scipy/scipy#5575]
```
$ python -c 'import numpy; import scipy; scipy.test(verbose=2)'
```

exits with exit code 1, and output below (only tail shown).

Python 2.7.10, numpy 1.10.1, and scipy 0.16.1 were built with the Intel compilers (2015.3.187) on top of GCC 4.9.3 and (correctly) linked against Intel MKL version 11.2.3.187 (but that's probably irrelevant here).

Seems like the issue is a new deprecation being triggered in numpy?

```
...
====================================================================== 
Running unit tests for scipy
NumPy version 1.10.1
NumPy relaxed strides checking option: True
NumPy is installed in /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy
SciPy version 0.16.1
SciPy is installed in /tmp/eb-QExiPA/tmp7jPnTC/lib/python2.7/site-packages/scipy
Python version 2.7.10 (default, Nov 11 2015, 20:29:34) [GCC Intel(R) C++ gcc 4.9 mode]
nose version 1.3.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 438, in test
    t = NumpyTestProgram(argv=argv, exit=False, plugins=plugins)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/core.py", line 121, in __init__
    **extra_args)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/noseclasses.py", line 351, in runTests
    self.result = self.testRunner.run(self.test)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/core.py", line 66, in run
    result.printErrors()
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/result.py", line 103, in printErrors
    _TextTestResult.printErrors(self)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/unittest/runner.py", line 108, in printErrors
    self.printErrorList('ERROR', self.errors)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/unittest/runner.py", line 114, in printErrorList
    self.stream.writeln("%s: %s" % (flavour,self.getDescription(test)))
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/result.py", line 82, in getDescription
    return test.shortDescription() or str(test)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/case.py", line 51, in __str__
    return str(self.test)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/case.py", line 286, in __str__
    name = "%s%s" % (name, arg)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/core/numeric.py", line 1709, in array_repr
    ', ', "array(")
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 447, in array2string
    separator, prefix, formatter=formatter)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 260, in _array2string
    'int': IntegerFormat(data),
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numpy/1.10.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 637, in __init__
    max_str_len = max(len(str(maximum.reduce(data))),
DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error
 (at easybuild/tools/run.py:397 in parse_cmd_output)
```

**Comment by rgommers** [comment]
Hmm, not sure what's going on there - that deprecation doesn't look familiar. Needs investigating. Added the 0.18.0 milestone to not forget before the next release.

**Comment by boegel** [comment]
I'm not seeing this in a slightly different situation, when installing numpy 1.10.1 and scipy 0.16.1 with Python 2.7.11, in the same installation prefix as Python itself.

With the error above, numpy and scipy were being installed in their own installation prefix, and `$PYTHONPATH` was being updated accordingly.

**Comment by boegel** [comment]
See also https://mail.scipy.org/pipermail/scipy-dev/2015-November/021062.html, seems like this is a bug in numpy 1.10.1 that is fixe already in 1.10.2rc1?

**Comment by rgommers** [comment]
That bug is that the deprecation warning is converted to a test error. But 1.10.2 doesn't revert the deprecation itself I think. From the above traceback I can't tell where the deprecation is triggered. Do you see a deprecation warning in the test output when run against 1.10.2rc1 with ``python -Wd -c "import scipy; scipy.test()"``?

**Comment by boegel** [comment]
I'm not seeing this problem anymore when testing scipy 0.16.1 on top of numpy 1.10.4, closing this issue.

**Comment by rgommers** [comment]
great, thanks for following up @boegel
