### ISSUE TITLE
test_idl.test_invalid_pointer fails for second and subsequent runs of the test suite

### ISSUE THREAD

**Issue by billsacks** [scipy/scipy#5638]
If I run scipy.io.test() multiple times in a python interpreter, the test suite passes the first time, but in second and subsequent times, test_idl.test_invalid_pointer fails:

```
In [1]: import scipy.io

In [2]: scipy.io.test()
Running unit tests for scipy.io
NumPy version 1.9.2
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
SciPy version 0.18.0.dev0+9c39001
SciPy is installed in scipy
Python version 2.7.9 (default, Feb 10 2015, 03:28:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
nose version 1.3.4
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 596 tests in 3.015s

OK
Out[2]: <nose.result.TextTestResult run=596 errors=0 failures=0>

In [3]: scipy.io.test()
Running unit tests for scipy.io
NumPy version 1.9.2
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
SciPy version 0.18.0.dev0+9c39001
SciPy is installed in scipy
Python version 2.7.9 (default, Feb 10 2015, 03:28:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
nose version 1.3.4
......................................................................................................................................................................................................................................................................................................................................................................F.............................................................................................................................................................................................................................................
======================================================================
FAIL: test_idl.test_invalid_pointer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/sacks/scipy/scipy/io/tests/test_idl.py", line 427, in test_invalid_pointer
    assert_(len(w) == 1)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 596 tests in 2.924s

FAILED (failures=1)
Out[3]: <nose.result.TextTestResult run=596 errors=0 failures=1>

In [4]: scipy.io.test()
Running unit tests for scipy.io
NumPy version 1.9.2
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
SciPy version 0.18.0.dev0+9c39001
SciPy is installed in scipy
Python version 2.7.9 (default, Feb 10 2015, 03:28:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
nose version 1.3.4
......................................................................................................................................................................................................................................................................................................................................................................F.............................................................................................................................................................................................................................................
======================================================================
FAIL: test_idl.test_invalid_pointer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/sacks/scipy/scipy/io/tests/test_idl.py", line 427, in test_invalid_pointer
    assert_(len(w) == 1)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
Ran 596 tests in 2.940s

FAILED (failures=1)
Out[4]: <nose.result.TextTestResult run=596 errors=0 failures=1>
```

**Comment by rgommers** [comment]
Looks like this is due to the behavior of Python's warnings - they only get issued once by default, so the check fails the second time around. IIRC this is fixed with numpy 1.10.2 by resetting all warnings and showing deprecationwarnings always.
