### ISSUE TITLE
still "Pending" DeprecationWarning in arffread.py ?

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#5673]
Testing with Python 3.5.1, my eye was caught by this unusual warning message.

````
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scupy;scipy.test()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import scupy;scipy.test()
ImportError: No module named 'scupy'
>>> import scipy
>>> scipy.test()
Running unit tests for scipy
NumPy version 1.10.2
NumPy relaxed strides checking option: False
NumPy is installed in D:\WinPython\basedir35\build\winpython-3.5.1.amd64\python-3.5.1.amd64\lib\site-packages\numpy
SciPy version 0.17.0rc1
SciPy is installed in D:\WinPython\basedir35\build\winpython-3.5.1.amd64\python-3.5.1.amd64\lib\site-packages\scipy
Python version 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
...
...
Warning (from warnings module):
  File "D:\WinPython\basedir35\build\winpython-3.5.1.amd64\python-3.5.1.amd64\lib\site-packages\scipy\io\arff\arffread.py", line 638
    data = np.fromiter(a, descr)
PendingDeprecationWarning: generator '_loadarff.<locals>.generator' raised StopIteration
````

**Comment by rgommers** [comment]
Comes from deprecating using ``StopIteration`` from inside a generator: https://www.python.org/dev/peps/pep-0479/. Looks like the ``generator`` function in ``_loadarff`` needs changing.
