### ISSUE TITLE
Test failed with sgelsy

### ISSUE THREAD

**Issue by huiyiqun** [scipy/scipy#5850]
```
======================================================================
ERROR: test_random_overdet (test_basic.TestLstsq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/huiyiqun/Develop/scipy/venv/lib/python3.5/site-packages/scipy/linalg/tests/test_basic.py", line 962, in test_random_overdet
    overwrite_b=overwrite)
  File "/home/huiyiqun/Develop/scipy/venv/lib/python3.5/site-packages/scipy/linalg/basic.py", line 917, in lstsq
    lwork, False, False)
_flapack.error: (lwork>=MAX(minmn+3*n+1, 2*minmn*nrhs)) failed for 5th argument lwork: sgelsy:lwork=9

----------------------------------------------------------------------
Ran 20768 tests in 475.896s

FAILED (KNOWNFAIL=97, SKIP=1638, errors=1)
```

**Comment by ev-br** [comment]
What OS, what LAPACK and how did you install SciPy?

**Comment by huiyiqun** [comment]
OS: Archlinux
LAPACK: atlas-lapack-base(3.10.2-3)

I tested with following methods but all failed.
1. Install scipy from archlinux repo and run `scipy.test()` with `ipython`.
2. Clone code from github and run `python runtest.py`.
3. Clone code from github, install scipy in virtualenv and run `scipy.test()` with `ipython`.

**Comment by ev-br** [comment]
From a quick glance, it looks like a LAPACK problem with lwork.
I cannot reproduce it on my machine, so I'm going to ask you to debug it a bit:

Could you throw in a pdb breakpoint, e.g.,

```
diff --git a/scipy/linalg/tests/test_basic.py b/scipy/linalg/tests/test_basic.py
index 0cf14be..2a761fa 100644
--- a/scipy/linalg/tests/test_basic.py
+++ b/scipy/linalg/tests/test_basic.py
@@ -956,6 +956,9 @@ class TestLstsq(TestCase):
                             a1 = a.copy()
                             b1 = b.copy()
                             try:
+
+                                import pdb; pdb.set_trace()
+
                                 out = lstsq(a1, b1,
                                             lapack_driver=lapack_driver,
                                             overwrite_a=overwrite,
-- 
1.7.9.5
```

and then use a variant of your method 2 above: `$ python runtests.py -s linalg` to get to the pdb debugger. Then find the failing case, this will be around these lines in `basic.py`:

```
    elif driver == 'gelsy':
        lwork = _compute_lwork(lapack_lwork, m, n, nrhs, cond)
        jptv = np.zeros((a1.shape[1],1), dtype=np.int32)
        v, x, j, rank, info = lapack_func(a1, b1, jptv, cond,
                                           lwork, False, False)
```

and check what happens if you manually bump `lwork` upwards as compated to 9 which `_compute_lwork` returns: does the call to `lapack_func` succeed?

**Comment by huiyiqun** [comment]
Here are arguements of `lapack_func`
```
(Pdb) args
a = array([[  4.25120926e+00,   9.86197412e-01],
       [  1.86788648e-01,   6.84171152e+00],
       [  6.26357079e-01,   1.06136024e-01],
       [  6.79280341e-01,   8.83470476e-01],
       [  1.62345394e-01,   3.88879895e-01],
       [  6.82844341e-01,   6.04191124e-01],
       [  1.04133919e-01,   9.96868253e-01],
       [  6.77639246e-01,   6.88485265e-01],
       [  1.02999404e-01,   5.06841600e-01],
       [  5.73319674e-01,   9.32663500e-01],
       [  9.83318686e-01,   3.38559657e-01],
       [  3.81854832e-01,   3.28522414e-01],
       [  8.94370615e-01,   2.62654543e-01],
       [  9.97252285e-01,   6.24460816e-01],
       [  1.65172294e-01,   7.85761237e-01],
       [  5.23447454e-01,   4.37177211e-01],
       [  9.73603368e-01,   5.00134528e-01],
       [  8.67843866e-01,   1.26011923e-01],
       [  1.02918401e-01,   7.70083427e-01],
       [  4.17553574e-01,   3.34887177e-01],
       [  6.99342549e-01,   2.50014782e-01],
       [  6.55155778e-01,   6.25899971e-01],
       [  7.30419338e-01,   8.95980656e-01],
       [  6.11975372e-01,   7.81950474e-01],
       [  2.95676589e-01,   3.62062633e-01],
       [  4.42312151e-01,   5.19834161e-01],
       [  4.08352405e-01,   1.92265689e-01],
       [  1.14632964e-01,   7.19004810e-01],
       [  4.80340838e-01,   5.07137239e-01],
       [  5.85331202e-01,   2.51691282e-01],
       [  5.65643311e-01,   1.85201839e-01],
       [  1.31312326e-01,   9.60846126e-01],
       [  1.35019198e-01,   1.26885012e-01],
       [  4.32779789e-01,   3.76062781e-01],
       [  5.92824280e-01,   6.90457344e-01],
       [  5.14869988e-01,   4.97031629e-01],
       [  9.20831621e-01,   6.95581809e-02],
       [  2.89154679e-01,   7.24526882e-01],
       [  3.46201956e-01,   4.27912593e-01],
       [  1.38691530e-01,   5.13610303e-01],
       [  2.04632327e-01,   4.32456210e-02],
       [  6.56970620e-01,   8.43024909e-01],
       [  9.29915249e-01,   3.89505893e-01],
       [  1.28811076e-01,   2.19600320e-01],
       [  1.18140087e-01,   4.07988906e-01],
       [  5.79706490e-01,   9.79852796e-01],
       [  2.05821052e-01,   3.85649085e-01],
       [  6.09454453e-01,   4.50418413e-01],
       [  3.60509083e-02,   8.44115853e-01],
       [  7.68917918e-01,   2.11666375e-02],
       [  3.29879075e-01,   9.43829715e-01],
       [  4.91271615e-01,   3.95590097e-01],
       [  2.76450098e-01,   4.37604219e-01],
       [  1.86240599e-01,   2.35082805e-01],
       [  4.34259057e-01,   3.23189467e-01],
       [  2.27511048e-01,   8.68727267e-01],
       [  8.15813661e-01,   7.52778172e-01],
       [  6.62494898e-01,   5.16423404e-01],
       [  6.29482210e-01,   9.57683682e-01],
       [  2.93605864e-01,   5.91362752e-02],
       [  6.11819685e-01,   9.41382706e-01],
       [  1.68103009e-01,   4.75815326e-01],
       [  9.78386939e-01,   3.47570449e-01],
       [  5.61407328e-01,   6.99327528e-01],
       [  4.84044611e-01,   6.77053556e-02],
       [  1.38564631e-01,   3.39556158e-01],
       [  5.53798079e-01,   4.68224049e-01],
       [  7.11037993e-01,   4.47323233e-01],
       [  5.21496713e-01,   2.87165791e-01],
       [  5.47939017e-02,   8.29891562e-01],
       [  7.30439782e-01,   5.94524741e-01],
       [  8.75862896e-01,   9.47249234e-01],
       [  6.62841320e-01,   2.24165872e-01],
       [  4.34957594e-01,   6.68911278e-01],
       [  3.23434860e-01,   4.84255314e-01],
       [  3.39397997e-01,   2.20592663e-01],
       [  3.59023273e-01,   1.29913550e-03],
       [  9.16901648e-01,   5.51669896e-01],
       [  8.26961815e-01,   9.24059749e-01],
       [  6.17857456e-01,   3.38311970e-01],
       [  8.11157167e-01,   6.60264790e-01],
       [  6.99947774e-01,   8.38509560e-01],
       [  5.96015573e-01,   5.15726388e-01],
       [  4.91313964e-01,   3.39988708e-01],
       [  7.52279222e-01,   7.44305849e-01],
       [  8.27799976e-01,   7.68468261e-01],
       [  2.08688140e-01,   1.11517549e-01],
       [  9.02629554e-01,   7.72090480e-02],
       [  2.20502652e-02,   1.27678961e-01],
       [  9.66568947e-01,   5.09326339e-01],
       [  2.28136382e-03,   7.45599747e-01],
       [  2.41348282e-01,   4.30649579e-01],
       [  3.65192145e-01,   7.77924716e-01],
       [  7.73575008e-01,   4.86393832e-02],
       [  4.13262159e-01,   8.35227251e-01],
       [  8.91907215e-01,   3.04270834e-01],
       [  7.25080550e-01,   9.11060095e-01],
       [  5.39687052e-02,   3.08380842e-01],
       [  6.38829112e-01,   1.73541948e-01],
       [  7.13638544e-01,   6.77080333e-01],
       [  4.26666796e-01,   5.74184120e-01],
       [  7.33318210e-01,   3.69992256e-01],
       [  5.54597020e-01,   2.82755345e-01],
       [  9.32713032e-01,   2.91316986e-01],
       [  5.99603616e-02,   5.76539114e-02],
       [  9.20129836e-01,   2.84160167e-01],
       [  6.77316114e-02,   9.95797992e-01],
       [  3.34643185e-01,   3.88466805e-01],
       [  6.84812307e-01,   6.57099903e-01],
       [  2.27842793e-01,   3.11044119e-02],
       [  2.43776977e-01,   2.94911951e-01],
       [  9.04141843e-01,   8.45391691e-01],
       [  9.73313332e-01,   3.85532290e-01],
       [  4.60968971e-01,   3.81709933e-01],
       [  3.93307626e-01,   6.68525934e-01],
       [  3.22121233e-01,   8.18526268e-01],
       [  9.44410563e-01,   6.30031884e-01],
       [  6.11271679e-01,   3.76455337e-01],
       [  5.82144082e-01,   2.30376586e-01],
       [  9.00816739e-01,   1.41599312e-01],
       [  3.31885546e-01,   2.84880430e-01],
       [  2.61886865e-01,   1.18497983e-01],
       [  2.89256334e-01,   1.57842897e-02],
       [  8.20918143e-01,   7.03733531e-04],
       [  5.26518822e-01,   9.73271847e-01],
       [  5.02266347e-01,   6.13627017e-01],
       [  7.95796886e-02,   3.53657871e-01],
       [  2.41871193e-01,   9.71060455e-01],
       [  6.53695583e-01,   8.74692261e-01],
       [  2.67820686e-01,   9.87754583e-01],
       [  5.82336009e-01,   9.56799090e-01],
       [  4.39766705e-01,   6.76780820e-01],
       [  8.21245968e-01,   9.96417701e-01],
       [  4.10333365e-01,   8.16620827e-01],
       [  4.83810186e-01,   2.79721588e-01],
       [  5.47905087e-01,   7.03266740e-01],
       [  5.35172582e-01,   6.89258993e-01],
       [  2.79128164e-01,   8.92742455e-01],
       [  9.81063783e-01,   2.14309171e-01],
       [  4.48534757e-01,   8.61361384e-01],
       [  2.58106589e-02,   9.64038491e-01],
       [  5.68688273e-01,   5.49844027e-01],
       [  2.39046291e-01,   5.04270494e-01],
       [  7.67318070e-01,   6.68866158e-01],
       [  3.07028323e-01,   5.62439084e-01],
       [  8.13199282e-01,   6.88318729e-01],
       [  3.40021074e-01,   8.30354869e-01],
       [  9.64657813e-02,   9.64548945e-01],
       [  4.97877784e-02,   8.89392376e-01],
       [  3.99132043e-01,   2.46338472e-01],
       [  6.77095830e-01,   3.91603619e-01],
       [  9.76773381e-01,   1.22895688e-01],
       [  6.26508832e-01,   3.75950217e-01],
       [  7.76036501e-01,   7.83562779e-01],
       [  8.12455490e-02,   3.89962316e-01],
       [  5.38519025e-01,   1.97736651e-01],
       [  6.79883957e-01,   9.32250142e-01],
       [  5.98244190e-01,   8.36940110e-01],
       [  5.77270806e-01,   4.92469102e-01],
       [  2.98696786e-01,   7.06617951e-01],
       [  5.64570189e-01,   8.36196840e-02],
       [  2.87187278e-01,   4.62238014e-01],
       [  6.55285954e-01,   8.10677409e-01],
       [  8.43999267e-01,   5.14587224e-01],
       [  4.71615821e-01,   3.75436217e-01],
       [  1.41209364e-01,   4.99402642e-01],
       [  2.14003995e-01,   4.82188642e-01],
       [  7.88538754e-01,   1.41458958e-01],
       [  6.04250282e-02,   8.87085617e-01],
       [  5.13827503e-01,   9.85307992e-03],
       [  3.10701430e-01,   2.29539536e-02],
       [  9.67116773e-01,   3.55697960e-01],
       [  2.12671533e-01,   7.68261850e-01],
       [  4.59640235e-01,   6.97153807e-01],
       [  2.79111564e-01,   6.98128641e-01],
       [  8.95996630e-01,   4.44034308e-01],
       [  1.09771825e-01,   7.37508476e-01],
       [  3.43585759e-01,   1.30852209e-02],
       [  2.08522335e-01,   8.79144073e-02],
       [  3.08453411e-01,   7.86451876e-01],
       [  4.83827233e-01,   7.16646910e-01],
       [  5.47506213e-01,   2.10668266e-01],
       [  7.69257367e-01,   6.58829212e-01],
       [  9.53773320e-01,   7.67383635e-01],
       [  2.76902348e-01,   7.62737095e-01],
       [  2.48175874e-01,   6.51926041e-01],
       [  8.23772728e-01,   5.72111368e-01],
       [  2.41858095e-01,   1.96521685e-01],
       [  3.51335406e-01,   7.18168855e-01],
       [  3.94085534e-02,   6.41311824e-01],
       [  1.08086541e-01,   2.42720753e-01],
       [  9.51557875e-01,   3.61566901e-01],
       [  9.30738509e-01,   8.28126073e-01],
       [  4.80249494e-01,   4.94533330e-01],
       [  4.49504226e-01,   2.52188057e-01],
       [  1.43624276e-01,   8.78331959e-01],
       [  7.07953811e-01,   5.22176266e-01],
       [  3.86237383e-01,   6.53811455e-01],
       [  5.54970324e-01,   1.12982251e-01],
       [  4.35086787e-01,   3.43928486e-01]], dtype=float32)
b = array([[ 0.40374833,  0.1045744 ,  0.83134848],
       [ 0.63375372,  0.90045625,  0.24592997],
       [ 0.55508637,  0.54366726,  0.65396488],
       [ 0.19104575,  0.54176253,  0.16288278],
       [ 0.85707933,  0.21449913,  0.50782764],
       [ 0.11324996,  0.57088047,  0.93475145],
       [ 0.23901145,  0.24336785,  0.68634164],
       [ 0.02856768,  0.25062418,  0.37526909],
       [ 0.41309875,  0.37457529,  0.20755428],
       [ 0.53206265,  0.66920751,  0.22092026],
       [ 0.67903459,  0.27809888,  0.02045669],
       [ 0.30333263,  0.71679318,  0.76401377],
       [ 0.87203991,  0.33001408,  0.61246675],
       [ 0.66623229,  0.66599977,  0.77407068],
       [ 0.19523214,  0.04679029,  0.01444619],
       [ 0.15811601,  0.71393794,  0.14906999],
       [ 0.88854545,  0.76266968,  0.21715958],
       [ 0.48165935,  0.33340177,  0.87891722],
       [ 0.62451231,  0.42354244,  0.51816911],
       [ 0.80389547,  0.77766091,  0.11573373],
       [ 0.78779578,  0.56337595,  0.59801966],
       [ 0.1318296 ,  0.66380721,  0.11982719],
       [ 0.89488524,  0.81732672,  0.38320053],
       [ 0.38137722,  0.99038613,  0.89410251],
       [ 0.04826644,  0.98649067,  0.8389082 ],
       [ 0.70725036,  0.73988038,  0.92291898],
       [ 0.03494283,  0.55386996,  0.32162151],
       [ 0.32630157,  0.32485622,  0.6181646 ],
       [ 0.71851164,  0.31706437,  0.58077466],
       [ 0.51762688,  0.28379804,  0.90445518],
       [ 0.48577371,  0.1295609 ,  0.62254852],
       [ 0.87836957,  0.02278413,  0.38258213],
       [ 0.81557739,  0.08623672,  0.22657144],
       [ 0.48333001,  0.44604802,  0.85525179],
       [ 0.51025027,  0.94432086,  0.9970907 ],
       [ 0.1203615 ,  0.85879391,  0.02642208],
       [ 0.1804373 ,  0.45096141,  0.40440381],
       [ 0.42265335,  0.49220201,  0.22952586],
       [ 0.63610494,  0.08233908,  0.76425308],
       [ 0.65750545,  0.09693262,  0.12362955],
       [ 0.26238418,  0.76139283,  0.75451136],
       [ 0.30284563,  0.28571498,  0.28334451],
       [ 0.07543352,  0.27223986,  0.82554364],
       [ 0.03958919,  0.74049604,  0.18279906],
       [ 0.22622624,  0.18212996,  0.99435252],
       [ 0.15134044,  0.17326927,  0.7922076 ],
       [ 0.89840883,  0.9925009 ,  0.88534331],
       [ 0.72186559,  0.33227324,  0.24106362],
       [ 0.03494603,  0.91604483,  0.5266307 ],
       [ 0.85613388,  0.06569115,  0.21927975],
       [ 0.64834803,  0.04248258,  0.37596548],
       [ 0.06959049,  0.09822855,  0.98746836],
       [ 0.3564254 ,  0.57974875,  0.58824617],
       [ 0.62303305,  0.2857725 ,  0.09438396],
       [ 0.79095191,  0.2503573 ,  0.83576542],
       [ 0.6291815 ,  0.13938843,  0.91122019],
       [ 0.29863092,  0.13975763,  0.9481293 ],
       [ 0.172686  ,  0.53277558,  0.46397936],
       [ 0.28328463,  0.73107058,  0.69110948],
       [ 0.35079122,  0.73335856,  0.09653579],
       [ 0.20416909,  0.27394333,  0.42631397],
       [ 0.1775561 ,  0.64450502,  0.8763051 ],
       [ 0.80107045,  0.4967795 ,  0.93475151],
       [ 0.52609605,  0.60206801,  0.78601837],
       [ 0.7400893 ,  0.5341211 ,  0.90559858],
       [ 0.13388757,  0.74630356,  0.65713483],
       [ 0.4565585 ,  0.57668358,  0.90590101],
       [ 0.95539898,  0.67291707,  0.04714337],
       [ 0.17308891,  0.4541809 ,  0.81322193],
       [ 0.54115784,  0.33433077,  0.96495867],
       [ 0.99190277,  0.32120246,  0.74621075],
       [ 0.71036428,  0.53722149,  0.78411031],
       [ 0.46837938,  0.75602388,  0.10141898],
       [ 0.81216067,  0.15368915,  0.77910876],
       [ 0.79574436,  0.64963007,  0.08468161],
       [ 0.913028  ,  0.8670314 ,  0.81837225],
       [ 0.29394999,  0.1323771 ,  0.1509366 ],
       [ 0.88263428,  0.68135923,  0.99717754],
       [ 0.49223593,  0.98576456,  0.71879733],
       [ 0.33631116,  0.84915525,  0.67009127],
       [ 0.09605277,  0.90963358,  0.0460927 ],
       [ 0.48304737,  0.46995956,  0.56092763],
       [ 0.483017  ,  0.16762026,  0.75073707],
       [ 0.44379452,  0.68575513,  0.1009127 ],
       [ 0.77966291,  0.21742156,  0.09870682],
       [ 0.1621791 ,  0.87584555,  0.89119321],
       [ 0.69543576,  0.30878156,  0.43270826],
       [ 0.60241222,  0.86384469,  0.82991803],
       [ 0.56493175,  0.23275656,  0.12892905],
       [ 0.44606364,  0.36302873,  0.97025049],
       [ 0.42765838,  0.30881387,  0.96010071],
       [ 0.25184721,  0.62391984,  0.04191104],
       [ 0.98561144,  0.61384237,  0.82282692],
       [ 0.71245235,  0.12567101,  0.82992184],
       [ 0.18423702,  0.44052795,  0.8504734 ],
       [ 0.53085542,  0.0021003 ,  0.43678993],
       [ 0.15861353,  0.05722966,  0.4940016 ],
       [ 0.62221164,  0.2278147 ,  0.68508565],
       [ 0.73816025,  0.25048846,  0.35816705],
       [ 0.75953865,  0.79656738,  0.71061665],
       [ 0.07681944,  0.6061545 ,  0.07094733],
       [ 0.70528406,  0.44175905,  0.86245573],
       [ 0.66215336,  0.65702832,  0.29990679],
       [ 0.23167393,  0.72307408,  0.94702786],
       [ 0.32798859,  0.286944  ,  0.51408029],
       [ 0.57780677,  0.084934  ,  0.23963037],
       [ 0.494656  ,  0.32189268,  0.96925694],
       [ 0.06973047,  0.66071349,  0.98511946],
       [ 0.90258086,  0.49344128,  0.1778492 ],
       [ 0.45117062,  0.23164134,  0.9076212 ],
       [ 0.74261588,  0.31745195,  0.04284552],
       [ 0.21894205,  0.23661014,  0.52490252],
       [ 0.81156588,  0.75960457,  0.20284756],
       [ 0.70031589,  0.62949944,  0.76783299],
       [ 0.35653874,  0.58118862,  0.72332805],
       [ 0.18527915,  0.48827273,  0.88509905],
       [ 0.88627481,  0.70175153,  0.39671108],
       [ 0.92557448,  0.07316224,  0.3957594 ],
       [ 0.89691144,  0.20794035,  0.27153319],
       [ 0.24633402,  0.90847355,  0.97873211],
       [ 0.07910097,  0.87787634,  0.25438091],
       [ 0.30277303,  0.12932275,  0.37003368],
       [ 0.47711238,  0.41952896,  0.64167958],
       [ 0.4981766 ,  0.76445448,  0.70330781],
       [ 0.02637909,  0.783225  ,  0.90432656],
       [ 0.58342677,  0.667669  ,  0.03645344],
       [ 0.94666827,  0.93378609,  0.40868956],
       [ 0.5612154 ,  0.84480697,  0.89026076],
       [ 0.31058189,  0.56189603,  0.67522717],
       [ 0.47373533,  0.54303157,  0.85511732],
       [ 0.27730566,  0.50039631,  0.91159356],
       [ 0.12096414,  0.52630961,  0.29545408],
       [ 0.78084677,  0.41922101,  0.88244867],
       [ 0.53580707,  0.22192205,  0.37848702],
       [ 0.22266921,  0.73234057,  0.87483031],
       [ 0.88814747,  0.40736452,  0.83888721],
       [ 0.02071682,  0.33964539,  0.68257642],
       [ 0.97885776,  0.13913967,  0.96819246],
       [ 0.74318671,  0.83558607,  0.23258349],
       [ 0.41957697,  0.98573196,  0.04163929],
       [ 0.82467902,  0.10981342,  0.4967418 ],
       [ 0.26342201,  0.7769013 ,  0.07020397],
       [ 0.52413523,  0.71742845,  0.6912145 ],
       [ 0.80007327,  0.03591533,  0.2931743 ],
       [ 0.32570606,  0.05772548,  0.47920653],
       [ 0.71473306,  0.6109792 ,  0.88276327],
       [ 0.30175662,  0.5802325 ,  0.90499973],
       [ 0.03740332,  0.98336381,  0.48313826],
       [ 0.75107723,  0.06440293,  0.18037058],
       [ 0.3936455 ,  0.71840215,  0.2185688 ],
       [ 0.72079891,  0.29154003,  0.65269172],
       [ 0.54344893,  0.15250835,  0.63496405],
       [ 0.40379387,  0.67122126,  0.03449463],
       [ 0.19020411,  0.66969562,  0.33018926],
       [ 0.78716266,  0.6735546 ,  0.99368507],
       [ 0.48067892,  0.04173397,  0.42078957],
       [ 0.14847746,  0.06667811,  0.0344035 ],
       [ 0.57056075,  0.71076947,  0.16229464],
       [ 0.47856551,  0.99085772,  0.17680113],
       [ 0.60132807,  0.14238663,  0.69604254],
       [ 0.99847341,  0.95054674,  0.39357111],
       [ 0.70985979,  0.67726707,  0.97119868],
       [ 0.28504166,  0.24533753,  0.7885772 ],
       [ 0.54481274,  0.87179732,  0.58015293],
       [ 0.1781936 ,  0.4252668 ,  0.80253619],
       [ 0.75425434,  0.05024556,  0.78935695],
       [ 0.17278853,  0.48102015,  0.830311  ],
       [ 0.83389145,  0.35784006,  0.45426589],
       [ 0.73579907,  0.71632701,  0.54778516],
       [ 0.90880227,  0.57839167,  0.12314356],
       [ 0.89298117,  0.6954546 ,  0.38596427],
       [ 0.48919448,  0.96140128,  0.88450974],
       [ 0.186628  ,  0.33311847,  0.95609963],
       [ 0.0433334 ,  0.29136127,  0.60743999],
       [ 0.28339931,  0.72664201,  0.83169401],
       [ 0.71211845,  0.06843273,  0.75386769],
       [ 0.52694607,  0.34082523,  0.25749114],
       [ 0.66037434,  0.64958215,  0.44968528],
       [ 0.81677222,  0.18042144,  0.47944385],
       [ 0.33358762,  0.46266848,  0.31734529],
       [ 0.19578891,  0.05909585,  0.52910346],
       [ 0.19379097,  0.84942341,  0.6655333 ],
       [ 0.91118866,  0.99797934,  0.50725979],
       [ 0.12414391,  0.63825512,  0.99922556],
       [ 0.54641694,  0.78739434,  0.48462379],
       [ 0.20284498,  0.15970412,  0.0895252 ],
       [ 0.38312343,  0.9043054 ,  0.38250881],
       [ 0.28262681,  0.8935681 ,  0.60657609],
       [ 0.8772887 ,  0.88903958,  0.65051943],
       [ 0.80860585,  0.19331647,  0.06739015],
       [ 0.20392627,  0.36478579,  0.10001424],
       [ 0.09010188,  0.72694808,  0.55746752],
       [ 0.89870274,  0.40650743,  0.11083042],
       [ 0.07716312,  0.29026565,  0.93037593],
       [ 0.66266423,  0.20692763,  0.1432834 ],
       [ 0.88580704,  0.05749288,  0.75520456],
       [ 0.98188913,  0.7357133 ,  0.94970518],
       [ 0.97367334,  0.67457283,  0.90096128],
       [ 0.18642659,  0.60248017,  0.3231838 ],
       [ 0.54524732,  0.7897566 ,  0.03598128]], dtype=float32)
cond = 1.1920929e-07
overwrite_a = True
overwrite_b = True
check_finite = True
lapack_driver = 'gelsy'
```

`longlist` points to here:
```
913         elif driver == 'gelsy':
914             lwork = _compute_lwork(lapack_lwork, m, n, nrhs, cond)
915             jptv = np.zeros((a1.shape[1],1), dtype=np.int32)
916             v, x, j, rank, info = lapack_func(a1, b1, jptv, cond,
917  ->                                            lwork, False, False)
918             if info < 0:
919                 raise ValueError("illegal value in %d-th argument of internal "
920                                  "gelsy" % -info)
```

**Comment by pv** [comment]
The lwork requirement in the .pyf file seems typoed (`2*minmn*nrhs` instead of `2*minmn+nrhs`).
LAPACK docs say 
```
                     The unblocked strategy requires that:
                        LWORK >= MAX( MN+3*N+1, 2*MN+NRHS ),
                     where MN = min( M, N ).
                     The block algorithm requires that:
                        LWORK >= MAX( MN+2*N+NB*(N+1), 2*MN+NB*NRHS ),
```

**Comment by ev-br** [comment]
@huiyiqun  could you check that https://github.com/scipy/scipy/pull/5971 fixes the problem?

**Comment by huiyiqun** [comment]
Yes, It fixed.
