### ISSUE TITLE
BUG: optimize test error for root when using lgmres 

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5959]
Shows up on OS X (numpy 1.10.4, python 2.7). 

    ======================================================================
    ERROR: test__root.TestRoot.test_tol_parameter
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/scipy/scipy/optimize/tests/test__root.py", line 34, in test_tol_parameter
        sol1 = root(func, [1.1,1.1], jac=jac, tol=1e-4, method=method)
      File "/Users/rgommers/Code/scipy/scipy/optimize/_root.py", line 198, in root
        **options)
      File "/Users/rgommers/Code/scipy/scipy/optimize/_root.py", line 301, in _root_nonlin_solve
        raise_exception=False)
      File "/Users/rgommers/Code/scipy/scipy/optimize/nonlin.py", line 309, in nonlin_solve
        dx = -jacobian.solve(Fx, tol=tol)
      File "/Users/rgommers/Code/scipy/scipy/optimize/nonlin.py", line 1457, in solve
        sol, info = self.method(self.op, rhs, tol=tol, **self.method_kw)
      File "/Users/rgommers/Code/scipy/scipy/sparse/linalg/isolve/lgmres.py", line 255, in lgmres
        dx = ws[0]*y[0]
    IndexError: list index out of range

**Comment by rgommers** [comment]
also a failure:

     ======================================================================
    FAIL: test_nonlin.TestJacobianDotSolve.test_krylov
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/scipy/scipy/optimize/tests/test_nonlin.py", line 358, in test_krylov
        self._check_dot(nonlin.KrylovJacobian, complex=True, tol=1e-4)
      File "/Users/rgommers/Code/scipy/scipy/optimize/tests/test_nonlin.py", line 322, in _check_dot
        assert_close(Jv, Jv2, 'dot vs solve')
      File "/Users/rgommers/Code/scipy/scipy/optimize/tests/test_nonlin.py", line 287, in assert_close
        raise AssertionError('%s: err %g' % (msg, d))
    AssertionError: dot vs solve: err 0.000839853

**Comment by pv** [comment]
Both solved by gh-5905 afaik

**Comment by rgommers** [comment]
Indeed, fixes both of them. Thanks.
