### ISSUE TITLE
python3.5: cannot install

### ISSUE THREAD

**Issue by AHEADer** [scipy/scipy#5992]
when I am use archlinux,I cannot install scipy-0.17.0 by pip
after a lot of warnings,I cut the wrong information:
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g6ko6u0h/scipy/setup.py", line 265, in <module>
        setup_package()
      File "/tmp/pip-build-g6ko6u0h/scipy/setup.py", line 262, in setup_package
        setup(**metadata)
      File "/usr/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-g6ko6u0h/scipy/setup.py", line 182, in configuration
        config.add_subpackage('scipy')
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g6ko6u0h/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_v5nkhp8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-g6ko6u0h/scipy/

**Comment by rgommers** [comment]
As the message says, you haven't got BLAS/LAPACK installed. And that's a necessary dependency. So you need the archlinux variant of ``sudo apt-get install libatlas3-base`` (which works for Debian/Ubuntu).
