### ISSUE TITLE
_lazywhere TypeError for functions with complex output

### ISSUE THREAD

**Issue by tpudlik** [scipy/scipy#6043]
If you pass `scipy._lib._util._lazywhere` a function that returns outputs of a dtype that cannot be safely cast to float64, you get errors.  For example,

    >>> a, b = np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])
    >>> def g(a, b): return np.sqrt(-a + 0j)
    >>> _lazywhere(a > 2, (a, b), g, np.nan)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/ad/eng/users/t/p/tpudlik/scipy/build/testenv/lib/python2.7/site-packages/scipy/_lib/_util.py", line 53, in _lazywhere
        np.place(out, cond, f(*temp))
      File "/home/tpudlik/.conda/envs/scipydev/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1595, in place
        return _insert(arr, mask, vals)
    TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'

In contrast, `np.where` returns,

    >>> np.where(a > 2, g(a,b), np.nan)
    array([ nan+0.j        ,  nan+0.j        ,   0.+1.73205081j,   0.+2.j        ])

I think the fix is to pass `_valarray` a `typecode` argument, but I'm not sure how to elegantly determine the appropriate dtype.

**Comment by tpudlik** [comment]
@ev-br You mentioned that https://github.com/scipy/scipy/pull/5869 should fix this, but I think it won't.  It seems to me that the fix in https://github.com/scipy/scipy/pull/5869/commits/4b65eabd6510914ee167e530ee1d20bb2bae216a only works for functions which have the same input and output types.  So, it fixes the problem for functions that map 'complex128' to 'complex128', but not for the function in the example above, which maps 'float64' to 'complex128'.

I think you'd have to call `mintypecode` on the results of `f(*temp)` and `f2(*temp)`, no?

**Comment by ev-br** [comment]
Yup, 4b65eab is only a minimal fix so that complex step derivative test passes for complex valued erf.

**Comment by j-bowhay** [comment]
Closing as `_lazywhere` has been moved to array API extra
