### ISSUE TITLE
test_orthogonal j, js roots failures on 32-bit Linux with system blas / lapack

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6092]
32-bit Ubuntu 12.04, numpy 1.11.0 system blas / lapack:

```
======================================================================
FAIL: test_orthogonal.test_j_roots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 312, in test_j_roots
    vgq(rf(0.5, -0.5), ef(0.5, -0.5), wf(0.5, -0.5), -1., 1., 100, atol=1e-12)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 286, in verify_gauss_quad
    assert_allclose(vv, np.eye(N), rtol, atol)
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=1e-12

(mismatch 29.16%)
 x: array([[  1.000000e+00,   1.968788e-12,  -1.966810e-12, ...,
          6.198497e-14,  -2.997552e-14,  -3.320739e-16],
       [  1.968861e-12,   1.000000e+00,   1.968029e-12, ...,...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],...

======================================================================
FAIL: test_orthogonal.test_js_roots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 381, in test_js_roots
    vgq(rf(1, 0.5), ef(1, 0.5), wf(1, 0.5), 0., 1., 100, atol=1e-12)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 286, in verify_gauss_quad
    assert_allclose(vv, np.eye(N), rtol, atol)
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=1e-12

(mismatch 29.18%)
 x: array([[  1.000000e+00,   1.968788e-12,  -1.966856e-12, ...,
          6.231325e-14,  -2.979876e-14,  -1.689169e-16],
       [  1.968861e-12,   1.000000e+00,   1.968029e-12, ...,...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],...
```

I do not get this error testing against openblas (32-bit).

```
$ python -c 'import scipy; scipy.show_config()'
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
openblas_lapack_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
atlas_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```

**Comment by person142** [comment]
Some more data points: I see this on 32-bit Ubuntu 12.04, but not on 32-bit Ubuntu 14.04 or 16.04. Not seeing it on 14.04 is somewhat surprising since 12.04 and 14.04 seem to be using the same stock blas:

http://packages.ubuntu.com/precise/libblas-dev
http://packages.ubuntu.com/trusty/libblas-dev

**Comment by rgommers** [comment]
different gcc versions?

**Comment by ev-br** [comment]
Given that it works fine on 14.04 and above, ISTM it's reasonable to take no action. Thoughts?

**Comment by person142** [comment]
> ISTM it's reasonable to take no action

+1 from me-seeing as it's likely a gcc/blas/lapack issue and 12.04 is EOL next August I imagine that we're de facto going to take no action anyway.

Maybe label as not action but leave open until 12.04 is officially toast?

**Comment by person142** [comment]
12.04 is EOL; closing this unless someone objects.
