### ISSUE TITLE
optimize.curve_fit bug: math.pow in fit function causes entire x_val array to be passed to fit function

### ISSUE THREAD

**Issue by joseortiz3** [scipy/scipy#6142]
```
from scipy import optimize
import math
def fit_func(x, p):
    print x
    return math.pow(x, p)
x_vals = [1,2,3,4]
y_vals = [1,4,9,16]
y_sigs = [1,1,1,1]
p0 = 2.43
popt = optimize.curve_fit(fit_func,x_vals,y_vals,p0,y_sigs,True)
```
The above code prints 
```
[1 2 3 4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Joey\Anaconda2\lib\site-packages\scipy\optimize\minpack.py", line 651, in curve_fit
    res = leastsq(func, p0, args=args, full_output=1, **kwargs)
  File "C:\Users\Joey\Anaconda2\lib\site-packages\scipy\optimize\minpack.py", line 377, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "C:\Users\Joey\Anaconda2\lib\site-packages\scipy\optimize\minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "C:\Users\Joey\Anaconda2\lib\site-packages\scipy\optimize\minpack.py", line 457, in _weighted_general_function
    return weights * (function(xdata, *params) - ydata)
  File "<stdin>", line 3, in fit_func
TypeError: only length-1 arrays can be converted to Python scalars
```

curve_fit is passing the entire x_vals array to fit_func! From my testing, math.pow specifically causes this.

**Comment by pv** [comment]
It is as intended. Ask on stackoverflow or on mailing lists if you have difficulty using it.

**Comment by joseortiz3** [comment]
Want to save me an hour and offer a two sentence explanation?

**Comment by joseortiz3** [comment]
Oh, [great](http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.optimize.curve_fit.html), only took me twenty minutes.

scipy.optimize.curve_fit(f, xdata, ydata, p0=None, sigma=None, absolute_sigma=False, check_finite=True, **kw)[source]
Use non-linear least squares to fit a function, f, to data.
**
Assumes ydata = f(xdata, *params) + eps**
