### ISSUE TITLE
 cannot import name 'moduleTNC'

### ISSUE THREAD

**Issue by Rhuax** [scipy/scipy#6188]
I'm using sklearn, and i get this error 
`    from scipy.optimize import moduleTNC, approx_fprime
ImportError: cannot import name 'moduleTNC'`

These are all the errors:
`Traceback (most recent call last):
  File "dcsn.py", line 3, in <module>
    from csnm import csv_2_numpy, Csnm
  File "Z:\My Documents\GitHub\dcsn\csnm.py", line 9, in <module>
    import csn as CSN
  File "Z:\My Documents\GitHub\dcsn\csn.py", line 9, in <module>
    import sklearn.mixture
  File "Z:\Anaconda3\lib\site-packages\sklearn\mixture\__init__.py", line 5, in <module>
    from .gmm import sample_gaussian, log_multivariate_normal_density
  File "Z:\Anaconda3\lib\site-packages\sklearn\mixture\gmm.py", line 21, in <module>
    from .. import cluster
  File "Z:\Anaconda3\lib\site-packages\sklearn\cluster\__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "Z:\Anaconda3\lib\site-packages\sklearn\cluster\spectral.py", line 16, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "Z:\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py", line 7, in <module>
    from .ranking import auc
  File "Z:\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py", line 32, in <module>
    from ..utils.stats import rankdata
  File "Z:\Anaconda3\lib\site-packages\sklearn\utils\stats.py", line 2, in <module>
    from scipy.stats import rankdata as _sp_rankdata
  File "Z:\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 338, in <module>
    from .stats import *
  File "Z:\Anaconda3\lib\site-packages\scipy\stats\stats.py", line 183, in <module>
    from . import distributions
  File "Z:\Anaconda3\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "Z:\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "Z:\Anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 233, in <module>
    from ._minimize import *
  File "Z:\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py", line 31, in <module>
    from .tnc import _minimize_tnc
  File "Z:\Anaconda3\lib\site-packages\scipy\optimize\tnc.py", line 37, in <module>
    from scipy.optimize import moduleTNC, approx_fprime
ImportError: cannot import name 'moduleTNC'`

What can I do?

**Comment by rgommers** [comment]
This is an issue with Scipy being incorrectly installed in Anaconda. I found two more reports like these. This should solve it:

    conda remove scipy scikit-learn -y
    conda install scipy scikit-learn -y

I'd also like to figure out if anything is wrong in Anaconda / conda. How did you install Anaconda, and did you upgrade or reinstall Scipy with conda?

**Comment by rgommers** [comment]
Actually seems to be happening for quite a few people: https://github.com/scikit-learn/scikit-learn/issues/4830. That has been going on since August it looks like.

**Comment by sscherfke** [comment]
https://stackoverflow.com/questions/31012216/updated-anaconda-error-message-cannot-import-name-moduletnc-when-importing

The file gets isntalled as `moduletnc...` and needs to be renamed to `moduleTNC...`.  Had this issue with 0.19.1 and the 1.0 rc2 on Windows.

**Comment by pv** [comment]
That looks like a bug either in conda, pip, or anaconda python.

**Comment by sscherfke** [comment]
I was using pypi and gohlke packages via pip.

**Comment by pv** [comment]
You can try to find a way to reproduce the issue reliably, then check if the filenames are right in the binary wheels that you are using (they're zip files). If yes, then it looks like a pip bug that should be reported to them.
