### ISSUE TITLE
scipy.linregress: unsupported operand type(s)

### ISSUE THREAD

**Issue by phpfs** [scipy/scipy#6191]
Hello!

When I try to use SparkysWidgets/MinipHBFW in Python3, I get this error:
```shell
user@host.domain:~$ python3 pHReader.py          
Traceback (most recent call last):     
  File "pHReader.py", line 69, in <module>          
    main()     
  File "pHReader.py", line 60, in main     
    phr = pHReader()     
  File "pHReader.py", line 33, in __init__     
    self.params = pHParams.pHParams()     
  File "/home/user/pHParams.py", line 31, in __init__     
    self.slope, self.intercept = self.calc_ph_slope()     
  File "/home/user/pHParams.py", line 97, in calc_ph_slope     
    slope, intercept, r_value, p_value, std_err = scipy.linregress(x, y)     
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 3008, in linregress     
    ymean = np.mean(y,None)     
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2716, in mean     
    out=out, keepdims=keepdims)     
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 69, in _mean     
    ret = ret / rcount     
TypeError: unsupported operand type(s) for /: 'dict_values' and 'int'     
```

Is it related to scipy or a problem of MinipHBFW?

Thank you for helping me out :)

Greetings, phpfs

**Comment by ev-br** [comment]
The error is actually in numpy. You're feedong something non-numeric to linregress, and that's not supported. Best check what dict_values are and why they end up in the array of ordinates.

**Comment by phpfs** [comment]
Thank you :)
