### ISSUE TITLE
Two test errors for SciPy version 0.18.0.dev0+8346eea on Fedora 23

### ISSUE THREAD

**Issue by charris** [scipy/scipy#6286]
Only the first is unexpected.

```
======================================================================
FAIL: test_highpass (test_filter_design.TestCheb2ord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/signal/tests/test_filter_design.py", line 755, in test_highpass
    assert_array_less(dB(h[w <= ws]), -rs + 0.1)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+812ca6f-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 987, in assert_array_less
    header='Arrays are not less-ordered')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+812ca6f-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 701, in assert_array_compare
    chk_same_position(x == -inf, y == -inf, hasval='-inf')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+812ca6f-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 677, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not less-ordered

x and y -inf location mismatch:
 x: array([      -inf, -91.742285, -85.750423, -82.276594, -79.845227,
       -77.994061, -76.51738 , -75.30565 , -74.293708, -73.439756,
       -72.715507, -72.101054, -71.581996, -71.147714, -70.790307,...
 y: array(-69.9)

======================================================================
FAIL: test_qhull.TestUtilities.test_degenerate_barycentric_transforms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/spatial/tests/test_qhull.py", line 325, in test_degenerate_barycentric_transforms
    assert_(bad_count < 20, bad_count)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+812ca6f-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 63, in assert_
    raise AssertionError(smsg)
AssertionError: 20

----------------------------------------------------------------------
Ran 22939 tests in 196.724s
```

**Comment by ev-br** [comment]
Cheb2ord seems to have not been touched for quite a while. Any ideas what causes the failure?

**Comment by rgommers** [comment]
The ``-inf`` in the first element of ``x`` is -277.25 for me. This is a decibel number, so the input to the ``dB`` function is ``10**(-277.25/20) = 1.37e-14``. So maybe nothing changed but your new Fedora has some library which lost some accuracy.

**Comment by charris** [comment]
Yes, I expect some library/compiler error. Hmm, looks like I'm using openblas-0.2.18, I didn't expect that, I have atlas installed also. Don't see an obvious connection but I'll try for the atlas version.

**Comment by charris** [comment]
Looks like it was openblas, so closing this.

**Comment by rgommers** [comment]
@charris did you file an issue against OpenBLAS? This is expected to work I think.

**Comment by charris** [comment]
@rgommers No. I need to spend the time to narrow it down and provide a simple test, which I haven't done yet.

**Comment by charris** [comment]
In Scipy master using OpenBLAS 0.18, gcc 6.1.1 I get three errors
```
======================================================================
FAIL: test_highpass (test_filter_design.TestCheb2ord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/signal/tests/test_filter_design.py", line 755, in test_highpass
    assert_array_less(dB(h[w <= ws]), -rs + 0.1)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 992, in assert_array_less
    header='Arrays are not less-ordered')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 704, in assert_array_compare
    chk_same_position(x == -inf, y == -inf, hasval='-inf')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 680, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not less-ordered

x and y -inf location mismatch:
 x: array([      -inf, -91.742285, -85.750423, -82.276594, -79.845227,
       -77.994061, -76.51738 , -75.30565 , -74.293708, -73.439756,
       -72.715507, -72.101054, -71.581996, -71.147714, -70.790307,...
 y: array(-69.9)

======================================================================
FAIL: test_basic (test_signaltools.TestFiltFilt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 1299, in test_basic
    assert_equal(out, arange(12))
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 314, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 812, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 737, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([ -1.634248e-12,   1.000000e+00,   2.000000e+00,   3.000000e+00,
         4.000000e+00,   5.000000e+00,   6.000000e+00,   7.000000e+00,
         8.000000e+00,   9.000000e+00,   1.000000e+01,   1.100000e+01])
 y: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

======================================================================
FAIL: test_basic (test_signaltools.TestSOSFiltFilt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 1299, in test_basic
    assert_equal(out, arange(12))
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 314, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 812, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/charris/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+36508b2-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 737, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([ -1.634248e-12,   1.000000e+00,   2.000000e+00,   3.000000e+00,
         4.000000e+00,   5.000000e+00,   6.000000e+00,   7.000000e+00,
         8.000000e+00,   9.000000e+00,   1.000000e+01,   1.100000e+01])
 y: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

```
Possibly related to the first
```
/home/charris/Workspace/scipy.git/build/testenv/lib64/python2.7/site-packages/scipy/signal/tests/test_filter_design.py:553: RuntimeWarning: divide by zero encountered in log10
  return 20 * np.log10(abs(x))
```

**Comment by charris** [comment]
The second and third errors also happen with ATLAS, so probably newly introduced errors. The first is gone along with the divide by zero warning, so seems specific to OpenBLAS. It was in the original report also.

**Comment by ev-br** [comment]
Second and third seem to be checking exact equality in floating point.

**Comment by charris** [comment]
BTW, this is now with Fedora 24. I made the gamble to upgrade before releasing 1.11.1, which cost me a day to track down a bug in Sphinx ;)

**Comment by ev-br** [comment]
OK, as long as the remaining error is OpenBLAS specific, ISTM it's not a blocker. (It'd be of course nice to get to chase it down.) Unless there are strong opinions to the contrary, I'm going to cut 0.18.0rc2 without this one (tomorrow if time permits, early next week otherwise).

**Comment by rgommers** [comment]
I agree, not a blocker

**Comment by chohner** [comment]
First off, thanks for all the great work! Is there an ETA for 0.18.0?

**Comment by ev-br** [comment]
@chohner Yes there is: https://github.com/scipy/scipy/releases/tag/v0.18.0 :-)

**Comment by ev-br** [comment]
Would be nice to re-check if these happen on a new Fedora, as a part of the rc testing (when the rc is available, that is). Meanwhile, detaching the milestone.

**Comment by larsoner** [comment]
On `master` the two `signal` tests are now `assert_allclose(out, arange(12), atol=1e-11)`, and the first failure seems to be OpenBLAS specific. So I'm going to close for now since it seems to be an upstream bug. Feel free to reopen if I'm missing something.
