### ISSUE TITLE
Test failure of arffread

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#6288]
I just got a test failure in the master branch (commit 6643554ff3):

```
~$ ~/anaconda/bin/python -c "from scipy import io; io.test('full')"
Running unit tests for scipy.io
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /Users/warren/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.18.0.dev0+6643554
SciPy is installed in /Users/warren/local_scipy/lib/python2.7/site-packages/scipy-0.18.0.dev0+6643554-py2.7-macosx-10.5-x86_64.egg/scipy
Python version 2.7.11 |Anaconda 1.8.0 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.7
......F......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
FAIL: test_datetime_missing (test_arffread.DateAttributeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy-0.18.0.dev0+6643554-py2.7-macosx-10.5-x86_64.egg/scipy/io/arff/tests/test_arffread.py", line 243, in test_datetime_missing
    assert_array_equal(self.data["attr_datetime_missing"], expected)
  File "/Users/warren/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 787, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/warren/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 33.3333333333%)
 x: array(['NaT', '2004-12-01T18:59-0500', 'NaT', 'NaT',
       '2013-11-29T23:55-0500', '1631-10-15T20:04Z'], dtype='datetime64[m]')
 y: array(['NaT', '2004-12-01T23:59-0500', 'NaT', 'NaT',
       '2013-11-30T04:55-0500', '1631-10-15T20:04Z'], dtype='datetime64[m]')

----------------------------------------------------------------------
Ran 605 tests in 2.108s

FAILED (failures=1)
```

This is on OS X 10.9.5.

**Comment by WarrenWeckesser** [comment]
The test passes if I revert 0555bb773f883584e2

**Comment by WarrenWeckesser** [comment]
Ping @rgommers.

The failure might be dependent on the numpy version.  I have numpy 1.10.4 installed.

**Comment by rgommers** [comment]
Hmm, I'll have a look. On TravisCI we run tests against numpy 1.11.0, 1.10.2 and 1.7.2, so if it's numpy version it must have been a short-lived change.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/6289 bumps the numpy version on TravisCI to 1.10.4. (tests pass)

**Comment by WarrenWeckesser** [comment]
I removed the 0.18 milestone.  I'll look into it more--maybe it's a quirk of my installation.

**Comment by matthew-brett** [comment]
@WarrenWeckesser - can this one be closed?

**Comment by WarrenWeckesser** [comment]
@matthew-brett Thanks for the reminder.  I'm getting getting the failure anymore, so I'm closing the issue.
