### ISSUE TITLE
Python 3 unorderable type errors in test_sparsetools.TestInt32Overflow

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6292]
Testing Scipy 0.18.0rc1 64-bit wheels on Linux, I am getting 12 errors in `test_sparsetools.TestInt32Overflow`, of form: 

```
======================================================================
ERROR: test_sparsetools.TestInt32Overflow.test_bsr_1_block('matmat',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.4/site-packages/scipy/sparse/tests/test_sparsetools.py", line 150, in check
    m = bsr_matrix((data, indices, indptr), blocksize=(n, n), copy=False)
  File "/venv/lib/python3.4/site-packages/scipy/sparse/bsr.py", line 169, in __init__
    maxval = max(maxval, max(blocksize))
TypeError: unorderable types: int() > NoneType()
```

See: https://travis-ci.org/MacPython/scipy-wheels/jobs/139084459#L368

**Comment by ev-br** [comment]
Huh. I nearly wrote "cannot reproduce it", but --- ran verbose tests, and

```
test_sparsetools.TestInt32Overflow.test_bsr_1_block('matmat',) ... SKIP: test requires 5000 MB of free memory
```

OK, free the memory (close the browser), and hey presto,

```
test_sparsetools.TestInt32Overflow.test_bsr_1_block('matmat',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_1_block('matvecs',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_1_block('matvec',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_1_block('diagonal',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_1_block('sort_indices',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_1_block('transpose',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('matmat',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('matvecs',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('matvec',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('diagonal',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('sort_indices',) ... ERROR
test_sparsetools.TestInt32Overflow.test_bsr_n_block('transpose',) ... ERROR
```

**Comment by ev-br** [comment]
Ok, so the problem comes from this:

https://github.com/scipy/scipy/commit/65244b9a817b3b30e2c89259cca07baf750bed5f#diff-91f2a1b3e76907865e88d529447df8f8R169

```
                 maxval = None
                 if shape is not None:
                     maxval = max(shape)
                 if blocksize is not None:
                     maxval = max(maxval, max(blocksize))
```

In the test, `shape is None`, so `maxval` stays being None, and the last line tries to compare None and an integer.

**Comment by ev-br** [comment]
A band-aid fix and a test which actually runs: https://github.com/scipy/scipy/pull/6295
