### ISSUE TITLE
hyp0f1 and struveh/struvel test failures

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#6365]
With the 0.18.0rc2 32-bit Linux wheel from PyPI:

```
======================================================================
FAIL: test_mpmath.TestSystematic.test_hyp0f1_complex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/tests/test_mpmath.py", line 1198, in test_hyp0f1_complex
    [Arg(-25, 25), ComplexArg(complex(-120, -120), complex(120, 120))])
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 225, in assert_mpmath_equal
    d.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 212, in check
    reraise(*sys.exc_info())
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 208, in check
    param_filter=self.param_filter)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 125, in assert_func_equal
    fdata.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 344, in check
    assert_(False, "\n".join(msg))
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: 
Max |adiff|: 4.98453e+25
Max |rdiff|: 1.16226e+14
Bad results (2 out of 5491) for the following points (in output 0):
                   (-1e-30+0j)                      (1e-30+0j) =>    (-5.811323644522354e-17+0j) !=                    (-5e-31+0j)  (rdiff             116226472890446.06)
                    (1e-30+0j)                     (-1e-30+0j) =>    (-5.811323644522253e-17+0j) !=                     (5e-31+0j)  (rdiff             116226472890446.06)

======================================================================
FAIL: test_mpmath.TestSystematic.test_struveh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/tests/test_mpmath.py", line 1609, in test_struveh
    rtol=5e-10)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 225, in assert_mpmath_equal
    d.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 212, in check
    reraise(*sys.exc_info())
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 208, in check
    param_filter=self.param_filter)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 125, in assert_func_equal
    fdata.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 344, in check
    assert_(False, "\n".join(msg))
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: 
Max |adiff|: 6.00153e+281
Max |rdiff|: 1.04376e-06
Bad results (17 out of 2610) for the following points (in output 0):
                         -10.0              27.825594022071243 =>            0.08538849163456759 !=             0.0853885807600122  (rdiff         1.0437630396775024e-06)
        -1.584893192461111e-07               16.68100537200059 =>          0.0030327868849725037 !=          0.0030327868586599417  (rdiff          8.676034012477932e-09)
        -2.511886431509572e-13               16.68100537200059 =>           0.003032859340241818 !=           0.003032859357762292  (rdiff         5.7768831831575855e-09)
       -3.9810717055349853e-19               16.68100537200059 =>          0.0030328593642341573 !=          0.0030328593578771955  (rdiff         2.0960292192322536e-09)
        -6.309573444801943e-25               16.68100537200059 =>           0.003032859386511313 !=          0.0030328593578771955  (rdiff           9.44129425983736e-09)
                        -1e-30               16.68100537200059 =>           0.003032859382870125 !=          0.0030328593578771955  (rdiff          8.240714999191768e-09)
                           0.0               16.68100537200059 =>           0.003032859337594946 !=          0.0030328593578771955  (rdiff          6.687500807317889e-09)
                         1e-30               16.68100537200059 =>          0.0030328593420661386 !=          0.0030328593578771955  (rdiff           5.21325093752338e-09)
         6.309573444801943e-25               16.68100537200059 =>          0.0030328593496474253 !=          0.0030328593578771955  (rdiff          2.713535048232232e-09)
        3.9810717055349853e-19               16.68100537200059 =>          0.0030328593802469183 !=           0.003032859357877196  (rdiff          7.375786264466402e-09)
         2.511886431509572e-13               16.68100537200059 =>          0.0030328593792583133 !=          0.0030328593579920992  (rdiff          7.011935450985688e-09)
         1.584893192461111e-07               16.68100537200059 =>          0.0030329318165232045 !=          0.0030329318571076067  (rdiff         1.3381244310934225e-08)
                           0.1               16.68100537200059 =>           0.051432929176759075 !=           0.051432929221421814  (rdiff          8.683685619545708e-10)
           0.10000000000000009               16.68100537200059 =>            0.05143292918322988 !=           0.051432929221421855  (rdiff          7.425588613477252e-10)
              77.4263682681127                77.4263682681127 =>             124408928.42117062 !=             124408929.01600471  (rdiff          4.781281327505454e-09)
            215.44346900318823               129.1549665014884 =>          2.449041958118309e-22 !=         2.4490419531540947e-22  (rdiff         2.0270025182055675e-09)
             599.4842503189409              215.44346900318823 =>         6.090078970541256e-190 !=          6.09007895879149e-190  (rdiff         1.9293290039418937e-09)

======================================================================
FAIL: test_mpmath.TestSystematic.test_struvel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/tests/test_mpmath.py", line 1627, in test_struvel
    ignore_inf_sign=True)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 225, in assert_mpmath_equal
    d.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 212, in check
    reraise(*sys.exc_info())
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 208, in check
    param_filter=self.param_filter)
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 125, in assert_func_equal
    fdata.check()
  File "/home/rgommers/.local/lib/python2.7/site-packages/scipy/special/_testutils.py", line 344, in check
    assert_(False, "\n".join(msg))
  File "/home/rgommers/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: 
Max |adiff|: 6.00153e+281
Max |rdiff|: 1.34067e-08
Bad results (2 out of 2612) for the following points (in output 0):
            -599.4842503189409              215.44346900318823 =>         7.496028765368905e+182 !=         7.496028788983548e+182  (rdiff          3.150287113158528e-09)
           -215.44346900318823               129.1549665014884 =>         1.8527173939362396e+16 !=          1.852717369097493e+16  (rdiff          1.340665727773665e-08)
```

The `hyp0f1` is not specific to this wheel I think, but the `struve` ones I've never seen before.

**Comment by matthew-brett** [comment]
I added the mpmath tests to the wheel build / test repo, and get the same failures : https://travis-ci.org/MacPython/scipy-wheels/jobs/143830834

**Comment by pv** [comment]
Can you check the compiler flags for C code from the build log. E.g. no 
"-O3" or "-ffast-math". Do the errors go away if compiling with `export 
OPT="-O1"`?

**Comment by pv** [comment]
The other suspect is bugs in libc math routines (if I understand 
correctly, these wheels use old libc versions):
.
https://sourceware.org/bugzilla/buglist.cgi?bug_status=RESOLVED&component=math&order=changeddate%20DESC%2Cpriority%2Cbug_severity&product=glibc&query_format=advanced&resolution=FIXED

**Comment by matthew-brett** [comment]
I added `export OPT='-01' to the build flags : 

https://github.com/MacPython/scipy-wheels/commit/2d79afdba7d493ef5919dd4e67c17b622e2fc934

The 32-bit error is the same:

https://travis-ci.org/MacPython/scipy-wheels/jobs/143854017

Aren't the glibc routines blacklisted by numpy?  Can we blacklist extra glibc routines from scipy?

**Comment by pv** [comment]
Numpy has special implementations only for complex functions. What it 
would take to get to the bottom of this, is to run the code (compiled 
with OPT="-ggdb -O0") in debugger (breakpoint at struve_hl for python -c 
'import scipy.special as s; s.struve(-10.0, 27.825594022071243)'), 
compare the run with a build on a working platform, and then determine 
what part was miscompiled.

**Comment by matthew-brett** [comment]
Sorry for my ignorance, but I am not familiar with gdb.  Is there anything I can to help someone who is?

**Comment by person142** [comment]
No repro on master with Ubuntu 16.04 32 bit, so going to blame it on old versions of glibc and say there's not much to do about it now.
