### ISSUE TITLE
Signal periodogram error:'multiply' did not contain a loop with signature matching types dtype('S64') dtype('S64') dtype('S64')

### ISSUE THREAD

**Issue by MilenkoM** [scipy/scipy#6376]
My code 
```
from scipy import signal
import numpy as np
import matplotlib.pyplot as plt

x = [line.rstrip('\n') for line in open('27000.dat')]
x = np.array(x)
fs=64

f, Pxx_den = signal.periodogram(x, fs)
plt.semilogy(f, Pxx_den)
plt.xlabel('frequency [Hz]')
plt.ylabel('PSD [V**2/Hz]')
plt.show()
```

Couple of lines from 27000.dat
-2.039246573184e+03
-2.058789646080e+03
-2.049676763520e+03

On Ubuntu 16.04,I got this
```
Traceback (most recent call last):
  File "m3.py", line 9, in <module>
    f, Pxx_den = signal.periodogram(x, fs)
  File "/home/milenko/miniconda2/lib/python2.7/site-packages/scipy/signal/spectral.py", line 141, in periodogram
    scaling, axis)
  File "/home/milenko/miniconda2/lib/python2.7/site-packages/scipy/signal/spectral.py", line 273, in welch
    return_onesided, scaling, axis)
  File "/home/milenko/miniconda2/lib/python2.7/site-packages/scipy/signal/spectral.py", line 391, in csd
    mode='psd')
  File "/home/milenko/miniconda2/lib/python2.7/site-packages/scipy/signal/spectral.py", line 824, in _spectral_helper
    scale = 1.0 / (fs * (win*win).sum())
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('S64') dtype('S64') dtype('S64')
```

Why?

**Comment by WarrenWeckesser** [comment]
`'S64'` is a string type.  You haven't converted your data to floating point, so `x` is an array of strings.

Try this:

    x = [float(line.rstrip('\n')) for line in open('27000.dat')]

Or, you could replace these two lines

    x = [line.rstrip('\n') for line in open('27000.dat')]
    x = np.array(x)

with

    x = np.loadtxt('27000.dat')
