### ISSUE TITLE
logm function is incomplete

### ISSUE THREAD

**Issue by szaiser** [scipy/scipy#6378]
With 

    In[57]: scipy.__version__
    Out[57]: '0.17.1'

    In[55]: scipy.linalg.__version__
    Out[55]: '0.4.9'

the line `scipy.linalg.logm(np.diag([-1.j, 1.j]))` results in the Exception

```
Traceback (most recent call last):
  File "D:\Python\Canopy\User\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-66da7c2c9d22>", line 1, in <module>
    scipy.linalg.logm(np.diag([-1.j, 1.j]))
  File "D:\Python\Canopy\User\lib\site-packages\scipy\linalg\matfuncs.py", line 200, in logm
    F = scipy.linalg._matfuncs_inv_ssq._logm(A)
  File "D:\Python\Canopy\User\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 874, in _logm
    return _logm_triu(A)
  File "D:\Python\Canopy\User\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 815, in _logm_triu
    U[i, i+1] = _logm_superdiag_entry(l1, l2, t12)
  File "D:\Python\Canopy\User\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 306, in _logm_superdiag_entry
    ub = _unwindk(np.log(1+z) - np.log(1-z))
  File "D:\Python\Canopy\User\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 153, in _unwindk
    return int(np.ceil((z.imag - np.pi) / (2*np.pi)))
ValueError: cannot convert float NaN to integer
```

In matlab the equivalent call to logm however produces valid output. Is this known?

**Comment by pv** [comment]
Seems to work fine in scipy 0.18.0rc*

**Comment by szaiser** [comment]
It indeed does. Thank you for testing!
