### ISSUE TITLE
Problems running benchmarks because cython_special is not defined

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#6478]
I'm having problems running some benchmarks. When I try to run a specific benchmark I'm getting a `NameError` because the name `cython_special` is not defined.

    (dev3)p0100m-bld-87:scipy anz$ python runtests.py --bench optimize.BenchGlobal
    Building, see build.log...
        ... build in progress
        ... build in progress
        ... build in progress
    Build OK
    Running benchmarks for Scipy version 0.19.0.dev0+f7deeac at /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/scipy-0.19.0.dev0+f7deeac-py3.4-macosx-10.6-x86_64.egg/scipy/__init__.py
    · Discovering benchmarks
    ·· Error running /Users/anz/miniconda3/envs/dev3/bin/python /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py discover /Users/anz/Documents/Andy/programming/scipy/benchmarks/benchmarks /var/folders/d0/kxzh7pwd4c10bzx7wffq8s740000gn/T/tmpfq981qzd
                 STDOUT -------->
             
                 STDERR -------->
                 Traceback (most recent call last):
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py", line 794, in <module>
                     commands[mode](args)
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py", line 739, in main_discover
                     list_benchmarks(benchmark_dir, fp)
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py", line 724, in list_benchmarks
                     for benchmark in disc_benchmarks(root):
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py", line 709, in disc_benchmarks
                     for module in disc_files(root, os.path.basename(root) + '.'):
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py", line 698, in disc_files
                     module = import_module(package + filename)
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/importlib/__init__.py", line 109, in import_module
                     return _bootstrap._gcd_import(name[level:], package, level)
                   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
                   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
                   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
                   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
                   File "<frozen importlib._bootstrap>", line 1129, in _exec
                   File "<frozen importlib._bootstrap>", line 1471, in exec_module
                   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
                   File "/Users/anz/Documents/Andy/programming/scipy/benchmarks/benchmarks/cython_special.py", line 72, in <module>
                     class CythonSpecial(six.with_metaclass(_CythonSpecialMeta)):
                   File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/six.py", line 808, in __new__
                     return meta(name, bases, d)
                   File "/Users/anz/Documents/Andy/programming/scipy/benchmarks/benchmarks/cython_special.py", line 62, in __new__
                     for name in dir(cython_special):
                 NameError: name 'cython_special' is not defined
    Traceback (most recent call last):
      File "/Users/anz/miniconda3/envs/dev3/bin/asv", line 9, in <module>
        load_entry_point('asv==0.2.dev1009+ce80d24a', 'console_scripts', 'asv')()
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/main.py", line 38, in main
        result = args.func(args)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/commands/__init__.py", line 48, in run_from_args
        return cls.run_from_conf_args(conf, args)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/commands/run.py", line 123, in run_from_conf_args
        **kwargs
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/commands/run.py", line 180, in run
        benchmarks = Benchmarks(conf, repo, environments, regex=bench)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmarks.py", line 299, in __init__
        benchmarks = self.disc_benchmarks(conf, repo, environments)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmarks.py", line 348, in disc_benchmarks
        dots=False)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/environment.py", line 617, in run
        self._executable] + args, **kwargs)
      File "/Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/util.py", line 512, in check_output
        raise ProcessError(args, retcode, stdout, stderr)
    asv.util.ProcessError: Command '/Users/anz/miniconda3/envs/dev3/bin/python /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/asv-0.2.dev1009+ce80d24a-py3.4-macosx-10.6-x86_64.egg/asv/benchmark.py discover /Users/anz/Documents/Andy/programming/scipy/benchmarks/benchmarks /var/folders/d0/kxzh7pwd4c10bzx7wffq8s740000gn/T/tmpfq981qzd' returned non-zero exit status 1

**Comment by pv** [comment]
Right, these benchmarks are actually written wrong --- the set of 
benchmarks should not depend on whether the cython_special module exists 
or not, so `for name in dir(cython_special) ... if re.match ...` should 
be replaced with `for name in FUNC_ARGS.keys(): ...` and the `py_func = 
getattr(...)` should be changed to `self.py_func = ...` and moved to 
`def setup` below.
