### ISSUE TITLE
Running cythonized failed !

### ISSUE THREAD

**Issue by Faris137** [scipy/scipy#6514]
I have tried to install scipy using pip and it failed several times. I have tried after upgrading pip to the latest version but it was still failing. I have tried to clone the repository and then python setup.py and it fail again. 
I am using windows 10 and python 2.7, I want to install scipy into my python not to be part of the conda.
 This is the error message:

C:\.....\scipy-master\scipy-master>python setup.py
Cythonizing sources
Processing scipy\cluster\_hierarchy.pyx
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython.Compiler.Main
Traceback (most recent call last):
  File "C:\Users\Fares\Desktop\fhees\learn python\scipy-master\scipy-master\tools\cythonize.py", line 198, in <module>
    main()
  File "C:\Users\Fares\Desktop\fhees\learn python\scipy-master\scipy-master\tools\cythonize.py", line 194, in main
    find_process_files(root_dir)
  File "C:\Users\Fares\Desktop\fhees\learn python\scipy-master\scipy-master\tools\cythonize.py", line 186, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "C:\Users\Fares\Desktop\fhees\learn python\scipy-master\scipy-master\tools\cythonize.py", line 160, in process
    processor_function(fromfile, tofile)
  File "C:\Users\Fares\Desktop\fhees\learn python\scipy-master\scipy-master\tools\cythonize.py", line 80, in process_pyx
    raise Exception("Cython either isn't installed or it failed.")
Exception: Cython either isn't installed or it failed.
Traceback (most recent call last):
  File "setup.py", line 415, in <module>
    setup_package()
  File "setup.py", line 399, in setup_package
    generate_cython()
  File "setup.py", line 205, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

**Comment by person142** [comment]
At the risk of stating the obvious, have you installed cython? (`pip install cython`)

In general, take a look at these instructions:

https://scipy.org/scipylib/building/windows.html

**Comment by pv** [comment]
Closing, reopen if cython was installed.

**Comment by doudouzhangdi** [comment]
run cythonize failed after installing cython
