### ISSUE TITLE
from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks

### ISSUE THREAD

**Issue by chaosnightmare2008** [scipy/scipy#6548]
When I upgrade the python from 3.4x into 3.5.2 then the error was raised as below:
"
import scipy.sparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scipy\sparse\__init__.py", line 213, in <module>
    from .csr import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: The specified module could not be found.
"
I did almost everything i can to solve it .Finally,i reinstall the python 3.4.4,and everything is ok.
It cost me over 2 days to found the reason which is version incompatibility.
Wish u guys can solve it ,then i can upgrade then python version.
(Sorry for the poor english, I'm not a people from  English speaking country.)

**Comment by ev-br** [comment]
I suppose you'll need to tell us more about how you installed scipy.

**Comment by pv** [comment]
No reply, closing.
