### ISSUE TITLE
Python: Concatenating scipy sparse matrix . ValueError: blocks must be 2-D

### ISSUE THREAD

**Issue by zohairzohair4** [scipy/scipy#6555]
I am trying to Concatenate 2 sparse matrix by the help of hstack function. xtrain_cat is the output of DictVectorizer(encodes categorical values) and xtrain_num is a pandas cvs file.

Error : 

```
> (1000, 2778)
> <class 'scipy.sparse.csr.csr_matrix'>
> <class 'scipy.sparse.csr.csr_matrix'>
> (1000, 2778)
> (1000, 968)
> Traceback (most recent call last):
>   File "D:\Projects\Zohair\Bosch\Bosch.py", line 360, in <module>
>     x_train_data = hstack(xtrain_cat,xtrain_num)
>   File "C:\Users\Public\Documents\anaconda2\lib\site-packages\scipy\sparse\construct.py", line 464, in hstack
>     return bmat([blocks], format=format, dtype=dtype)
>   File "C:\Users\Public\Documents\anaconda2\lib\site-packages\scipy\sparse\construct.py", line 547, in bmat
>     raise ValueError('blocks must be 2-D')
> ValueError: blocks must be 2-D
```

Can someone identify what is the probelm

**Comment by perimosocordiae** [comment]
Help for usage questions is available on stackoverflow.com, this issue tracker is intended for reporting bugs.
