### ISSUE TITLE
RectSphereBivariateSpline(u, v, r) fails if min(v) >= pi

### ISSUE THREAD

**Issue by AkimboEG** [scipy/scipy#6556]
For a `scipy.interpolate.RectSphereBivariateSpline(u, v, r)` call, from [the docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.html):
* `u` must lie within the interval (0, pi).
* `v` must lie within the interval (0, 2pi).

However, I believe the function call breaks when v is in the range [pi, 2pi).
Note the terminology: round brackets are *open intervals* and square brackets are *closed intervals*.

### Examples
This one works (`min(v) < pi`)
```python
>>> u = np.linspace(1, 3)
>>> v = np.linspace(np.pi - 1e-6, 6)
>>> r = np.zeros([u.size, v.size])
>>> RectSphereBivariateSpline(u, v, r)
```
```python-traceback
<scipy.interpolate.fitpack2.RectSphereBivariateSpline object at 0x7f353b4e1b70>
```

This one doesn't work (`min(v) >= pi`)
```python
>>> u = np.linspace(1, 3)
>>> v = np.linspace(np.pi, 6)
>>> r = np.zeros([u.size, v.size])
>>> RectSphereBivariateSpline(u, v, r)
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scipy/interpolate/fitpack2.py", line 1697, in __init__
    raise ValueError(msg)
ValueError: 
ERROR: on entry, the input data are controlled on validity
       the following restrictions must be satisfied.
          -1<=iopt(1)<=1, 0<=iopt(2)<=1, 0<=iopt(3)<=1,
          -1<=ider(1)<=1, 0<=ider(2)<=1, ider(2)=0 if iopt(2)=0.
          -1<=ider(3)<=1, 0<=ider(4)<=1, ider(4)=0 if iopt(3)=0.
          mu >= mumin (see above), mv >= 4, nuest >=8, nvest >= 8,
          kwrk>=5+mu+mv+nuest+nvest,
          lwrk >= 12+nuest*(mv+nvest+3)+nvest*24+4*mu+8*mv+max(nuest,mv+nvest)
          0< u(i-1)<u(i)< pi,i=2,..,mu,
          -pi<=v(1)< pi, v(1)<v(i-1)<v(i)<v(1)+2*pi, i=3,...,mv
          if iopt(1)=-1: 8<=nu<=min(nuest,mu+6+iopt(2)+iopt(3))
                         0<tu(5)<tu(6)<...<tu(nu-4)< pi
                         8<=nv<=min(nvest,mv+7)
                         v(1)<tv(5)<tv(6)<...<tv(nv-4)<v(1)+2*pi
                         the schoenberg-whitney conditions, i.e. there must be
                         subset of grid co-ordinates uu(p) and vv(q) such that
                            tu(p) < uu(p) < tu(p+4) ,p=1,...,nu-4
                            (iopt(2)=1 and iopt(3)=1 also count for a uu-value
                            tv(q) < vv(q) < tv(q+4) ,q=1,...,nv-4
                            (vv(q) is either a value v(j) or v(j)+2*pi)
          if iopt(1)>=0: s>=0
          if s=0: nuest>=mu+6+iopt(2)+iopt(3), nvest>=mv+7
       if one of these conditions is found to be violated,control is
       immediately repassed to the calling program. in that case there is no
       approximation returned.
```

I don't know if the issue is with SciPy or the underlying FITPACK.

**Comment by pv** [comment]
Looks like a FITPACK restriction --- the error message states the requirement `-pi<=v(1)< pi`.

**Comment by person142** [comment]
The Fortran source:

https://github.com/scipy/scipy/blob/master/scipy/interpolate/fitpack/spgrid.f#L99

defines `v` as:

``` fortran
c  v     : real array of dimension at least (mv). before entry, v(j)
c          must be set to the v-co-ordinate of the j-th grid point
c          along the v-axis, for j=1,2,...,mv. these values must be
c          supplied in strictly ascending order. unchanged on exit.
c          -pi <= v(1) < pi , v(mv) < v(1)+2*pi.
```

So the scipy documentation should be updated to reflect that. Looks like a nice easy fix for anyone looking to get their ears wet.

**Comment by sriki18** [comment]
Just submitted #6665 addressing this.
