### ISSUE TITLE
pip install and python setup.py build of scipy bot fail during "build_ext"

### ISSUE THREAD

**Issue by aixtools** [scipy/scipy#6684]
Current setup:
System: POWER6, AIX 6.1, python 2.7.12
root@x065:[/data/prj/python/pipbuilds/scipy-0.18.1]pip list
Cython (0.24.1)
numpy (1.11.2)
pandas (0.19.0)
pip (8.1.1)
python-dateutil (2.5.3)
pytz (2016.7)
setuptools (20.10.1)
six (1.10.0)

I would try to just run the (sub) setup.py to see why it ends with an index error, but have no clue which one I need - there are "several" to choose from.

It goes a long way, but both install methods fail at:

The C++ compiler is installed, but until now has not been needed (or it has worked).

So, would it be enough (or at least worth trying) to define CXX in _sysconfigdata.py? (Currently undefined.)

root@x065:[/opt/lib/python2.7]grep CXX *.py
_osx_support.py:                            'BLDSHARED', 'LDSHARED', 'CC', 'CXX',
_osx_support.py:_COMPILER_CONFIG_VARS = ('BLDSHARED', 'LDSHARED', 'CC', 'CXX')
_osx_support.py:                cv_split[0] = cc if cv != 'CXX' else cc + '++'
_sysconfigdata.py: 'CXX': '',
_sysconfigdata.py: 'LDCXXSHARED': '/opt/lib/python2.7/config/ld_so_aix xlc_r -bI:/opt/lib/python2.7/config/python.exp'

FAILS with:
customize UnixCCompiler
#### ['xlc_r', '-I/opt/include', '-O3', '-qmaxmem=-1', '-qarch=pwr5', '-q64', '-I/opt/buildaix/includes', '-DNDEBUG'] #######
customize UnixCCompiler using build_ext
Traceback (most recent call last):
  File "./setup.py", line 415, in <module>
    setup_package()
  File "./setup.py", line 411, in setup_package
    setup(**metadata)
  File "/opt/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/opt/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/lib/python2.7/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/opt/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/opt/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 206, in run
    self._cxx_compiler = compiler.cxx_compiler()
  File "/opt/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 516, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]
IndexError: list index out of range

**Comment by aixtools** [comment]
UPDATE: setting 'CXX: 'xlC_r' in _sysconfigdata.py resolves this issue - so this is something to review when building python - and can be closed. Sorry for the noise!
