### ISSUE TITLE
Can not install scipy using pip

### ISSUE THREAD

**Issue by GHeitem** [scipy/scipy#6851]
I have some problems while installing scipy. 
OS: Windows.
Python: 3.5.1
CMD:

```
C:\Users\Manat Rashidov>pip install scipy
Collecting scipy
  Using cached scipy-0.18.1.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command c:\python\python35\python.exe -u -c "import set
uptools, tokenize;__file__='C:\\Users\\MANATR~1\\AppData\\Local\\Temp\\pip-build
-3uik7cbv\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.r
ead().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" ins
tall --record C:\Users\MANATR~1\AppData\Local\Temp\pip-cvzvs2ed-record\install-r
ecord.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['c:\\python\\python35\\lib', 'C:\\', 'c:\
\python\\python35\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\python\\python35\\lib', 'C:\\', 'c:\\p
ython\\python35\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\python\python35\lib\site-packages\numpy\distutils\system_info.py:639: Use
rWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-bu
ilds\atlas-3.11.38-sse2-64\lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\python\python35\lib\site-packages\numpy\distutils\system_info.py:1532: Us
erWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    lapack_info:
      libraries lapack not found in ['c:\\python\\python35\\lib', 'C:\\', 'c:\\p
ython\\python35\\libs']
      NOT AVAILABLE

    c:\python\python35\lib\site-packages\numpy\distutils\system_info.py:1543: Us
erWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    lapack_src_info:
      NOT AVAILABLE

    c:\python\python35\lib\site-packages\numpy\distutils\system_info.py:1546: Us
erWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MANATR~1\AppData\Local\Temp\pip-build-3uik7cbv\scipy\setup.
py", line 415, in <module>
        setup_package()
      File "C:\Users\MANATR~1\AppData\Local\Temp\pip-build-3uik7cbv\scipy\setup.
py", line 411, in setup_package
        setup(**metadata)
      File "c:\python\python35\lib\site-packages\numpy\distutils\core.py", line
135, in setup
        config = configuration()
      File "C:\Users\MANATR~1\AppData\Local\Temp\pip-build-3uik7cbv\scipy\setup.
py", line 335, in configuration
        config.add_subpackage('scipy')
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 1000, in add_subpackage
        caller_level = 2)
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 969, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 906, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 1000, in add_subpackage
        caller_level = 2)
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 969, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\python\python35\lib\site-packages\numpy\distutils\misc_util.py",
line 906, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\python\python35\python.exe -u -c "import setuptools, tokenize;__file
__='C:\\Users\\MANATR~1\\AppData\\Local\\Temp\\pip-build-3uik7cbv\\scipy\\setup.
py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\
n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\M
ANATR~1\AppData\Local\Temp\pip-cvzvs2ed-record\install-record.txt --single-versi
on-externally-managed --compile" failed with error code 1 in C:\Users\MANATR~1\A
ppData\Local\Temp\pip-build-3uik7cbv\scipy\ 
````

**Comment by pv** [comment]
https://scipy.org/install.html

**Comment by IFDAAS** [comment]
the easiest way is in the following steps: Fixing scipy for python [ 2.n < python < 3.n ]

Download the necessary files from: http://www.lfd.uci.edu/~gohlke/pythonlibs/

Download the version of numpy+mkl (needed to run scipy) and then download scipy for your python type (2.n python written as 2n) or (3.n python written as 3n), n is a variable. Note you must know whether you have a 32bit or 64bit processor.

Create a directory somewhere on your computer, example [C:\DIRECTORY] to install the files numpy+mkd.whl and scipy.whl

Once both file are downloaded, find the location of the file on your computer and move it to the directory you created.

Example: first file installation is needed for scipy is in---> C:\DIRECTORY\numpy\numpy-0.0.0+mkl-cp2n-cp2nm-win_amd32.whl

Example: second file installation is in---> C:\DIRECTORY\scipy\scipy-0.0.0-cp2n-cp2nm-win_amd32.whl

Go to your command prompt and proceed the following example for a python version 2.n:

py -2.n -m pip install C:\DIRECTORY\numpy\numpy-0.0.0+mkl-cp2n-cp2nm-win_amd32.whl

should install

py -2.n -m pip install C:\DIRECTORY\scipy\scipy-0.0.0-cp2n-cp2nm-win_amd32.whl

should install

Test both modules on your python IDLE as following: import numpy import scipy

the modules are working if no errors are returned.

IFDAAS

**Comment by arifwib** [comment]
after install with those two .whl files, i still have a problem when compiling with blas.py:
import numpy as _np
from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

is there any other solution ?

my sistem win10 64, with python27 and numpy+mkl, scipy, scikit-image installer.
and log compiler:
C:\Python27\python.exe D:/SharedProjects/PycharmProjects/display_ocr/digital_display_ocr.py
Traceback (most recent call last):
  File "D:/SharedProjects/PycharmProjects/display_ocr/digital_display_ocr.py", line 4, in <module>
    from skimage import exposure
  File "C:\Python27\lib\site-packages\skimage\exposure\__init__.py", line 1, in <module>
    from .exposure import histogram, equalize_hist, \
  File "C:\Python27\lib\site-packages\skimage\exposure\exposure.py", line 4, in <module>
    from ..color import rgb2gray
  File "C:\Python27\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Python27\lib\site-packages\skimage\color\colorconv.py", line 59, in <module>
    from scipy import linalg
  File "C:\Python27\lib\site-packages\scipy\linalg\__init__.py", line 175, in <module>
    from .misc import *
  File "C:\Python27\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Python27\lib\site-packages\scipy\linalg\blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by addyh** [comment]
arifwib - download and save the 6 .dll and .lib files (which correspond to your system) at this link to your C:Python27\libs directory

https://icl.cs.utk.edu/lapack-for-windows/lapack/#libraries

**Comment by pv** [comment]
The easiest approach on Windows is `pip install scipy==1.0.0rc2` if you're happy to use a prerelease version.

**Comment by George35mk** [comment]
@pv OMG THNX WORKS
