### ISSUE TITLE
Unable to install scipy with python3.7 on ubuntu 16.10

### ISSUE THREAD

**Issue by jmunsch** [scipy/scipy#6912]
I tried installing via: `python3.7 -m pip install scipy`

As well as: `git clone` and `make`

Any suggestions?

```
root@vultr:/# free --mega
                   total        used        free      shared  buff/cache   available
Mem:            499          56          32           0         411         427
Swap:          4194          24        4169


------
os.name='posix'
------
sys.platform='linux'
------
sys.version:
3.7.0a0 (default:803c3c21c3bc, Jan  2 2017, 04:04:30) 
[GCC 6.2.0 20161005]
------
sys.prefix:
/usr/local
------
sys.path=':/usr/local/lib/python37.zip:/root/cpython/Lib:/root/cpython/build/lib.linux-x86_64-3.7-pydebug:/usr/local/lib/python3.7/site-packages'
------
Found new numpy version '1.11.3' in /usr/local/lib/python3.7/site-packages/numpy/__init__.py
Found f2py2e version '2' in /usr/local/lib/python3.7/site-packages/numpy/f2py/f2py2e.py
Found numpy.distutils version '0.4.0' in '/usr/local/lib/python3.7/site-packages/numpy/distutils/__init__.py'
------
Importing numpy.distutils.fcompiler ... ok
------
Checking availability of supported Fortran compilers:
Gnu95FCompiler instance properties:
  archiver        = ['/usr/bin/gfortran', '-cr']
  compile_switch  = '-c'
  compiler_f77    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-
                    fno-second-underscore', '-fPIC', '-O3', '-funroll-loops']
  compiler_f90    = ['/usr/bin/gfortran', '-Wall', '-g', '-fno-second-
                    underscore', '-fPIC', '-O3', '-funroll-loops']
  compiler_fix    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-
                    fno-second-underscore', '-Wall', '-g', '-fno-second-
                    underscore', '-fPIC', '-O3', '-funroll-loops']
  libraries       = ['gfortran']
  library_dirs    = []
  linker_exe      = ['/usr/bin/gfortran', '-Wall', '-Wall']
  linker_so       = ['/usr/bin/gfortran', '-Wall', '-g', '-Wall', '-g', '-
                    shared']
  object_switch   = '-o '
  ranlib          = ['/usr/bin/gfortran']
  version         = LooseVersion ('6.2.0')
  version_cmd     = ['/usr/bin/gfortran', '-dumpversion']
Fortran compilers found:
  --fcompiler=gnu95  GNU Fortran 95 compiler (6.2.0)
Compilers available for this platform, but not found:
  --fcompiler=absoft   Absoft Corp Fortran Compiler
  --fcompiler=compaq   Compaq Fortran Compiler
  --fcompiler=g95      G95 Fortran Compiler
  --fcompiler=gnu      GNU Fortran 77 compiler
  --fcompiler=intel    Intel Fortran Compiler for 32-bit apps
  --fcompiler=intele   Intel Fortran Compiler for Itanium apps
  --fcompiler=intelem  Intel Fortran Compiler for 64-bit apps
  --fcompiler=lahey    Lahey/Fujitsu Fortran 95 Compiler
  --fcompiler=nag      NAGWare Fortran 95 Compiler
  --fcompiler=pathf95  PathScale Fortran Compiler
  --fcompiler=pg       Portland Group Fortran Compiler
  --fcompiler=vast     Pacific-Sierra Research Fortran 90 Compiler
Compilers not available on this platform:
  --fcompiler=hpux      HP Fortran 90 Compiler
  --fcompiler=ibm       IBM XL Fortran Compiler
  --fcompiler=intelev   Intel Visual Fortran Compiler for Itanium apps
  --fcompiler=intelv    Intel Visual Fortran Compiler for 32-bit apps
  --fcompiler=intelvem  Intel Visual Fortran Compiler for 64-bit apps
  --fcompiler=mips      MIPSpro Fortran Compiler
  --fcompiler=none      Fake Fortran compiler
  --fcompiler=sun       Sun or Forte Fortran 95 Compiler
For compiler details, run 'config_fc --verbose' setup command.
------
Importing numpy.distutils.cpuinfo ... ok
------
CPU information: CPUInfoBase__get_nbits getNCPUs has_mmx has_sse has_sse2 has_sse3 has_ssse3 is_64bit is_Intel is_i686 is_singleCPU ------




root@vultr:/# ldd ./usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-35m-x86_64-linux-gnu.so
  linux-vdso.so.1 =>  (0x00007ffc3094a000)
  libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f27d9425000)
  libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f27d920e000)
  libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f27d8ff0000)
  libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f27d8c29000)
  libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f27d8920000)
  /lib64/ld-linux-x86-64.so.2 (0x000055d458727000)


root@vultr:/# cp /usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-37dm-x86_64-linux-gnu.so
root@vultr:/# python3.7 /var/opt/weather-forecast-api/get_lat_lon.py
Traceback (most recent call last):
  File "/var/opt/weather-forecast-api/get_lat_lon.py", line 5, in <module>
    from jankydb import (get_city_states,
  File "/var/opt/weather-forecast-api/jankydb.py", line 4, in <module>
    from scipy.spatial import distance
  File "/usr/local/lib/python3.7/scipy/spatial/__init__.py", line 91, in <module>
    from .kdtree import *
  File "/usr/local/lib/python3.7/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/usr/local/lib/python3.7/scipy/sparse/__init__.py", line 214, in <module>
    from .csr import *
  File "/usr/local/lib/python3.7/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-37dm-x86_64-linux-gnu.so: undefined symbol: PyModule_Create2
```

**Comment by rgommers** [comment]
``PyModule_Create2`` didn't disappear from 3.7-dev, so maybe something to do with how you built Python?

**Comment by jmunsch** [comment]
I think I botched the install by trying to pull the prebuilt binaries for ubuntu, which used python3.5 and then tried to rename stuff like below:

```
cp /usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-35m-x86_64-linux-gnu.so /usr/local/lib/python3.7/scipy/sparse/_sparsetools.cpython-37dm-x86_64-linux-gnu.so
```

The thought being at the time, if its a memory limit (512MB of ram, and 4GB of swap) maybe I could just rename a few things and it might work.

I will retry with more ram sometime this week.

**Comment by matthew-brett** [comment]
Try this:

```
pip install --user numpy scipy
```

Does that work?

**Comment by rgommers** [comment]
> maybe I could just rename a few things and it might work.

This will never work for any compiled Python extension - builds are specific to a single Python version (at least up to Python 3.6).
