### ISSUE TITLE
signature mismatches for LowLevelCallable

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#6926]
Haven't figured out the cause. The only thing I thought looked possibly problematic on 32-bit Python is the ``size_t`` casts at the end of ``_ccallback.pyx``. Everything else just uses plains ``int``s.

    ======================================================================
    ERROR: test_ccallback.test_callbacks('cython', 'ctypes', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
      File "scipy/_lib/_ccallback_c.pyx", line 163, in scipy._lib._ccallback_c.test_call_cython (../scipy/_lib/_ccallback_c.c:2063)
        ccallback_prepare(&callback, signatures, callback_obj, CCALLBACK_DEFAULTS)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('cython', 'ctypes', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
      File "scipy/_lib/_ccallback_c.pyx", line 163, in scipy._lib._ccallback_c.test_call_cython (../scipy/_lib/_ccallback_c.c:2063)
        ccallback_prepare(&callback, signatures, callback_obj, CCALLBACK_DEFAULTS)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('cython', 'ctypes_b', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
      File "scipy/_lib/_ccallback_c.pyx", line 163, in scipy._lib._ccallback_c.test_call_cython (../scipy/_lib/_ccallback_c.c:2063)
        ccallback_prepare(&callback, signatures, callback_obj, CCALLBACK_DEFAULTS)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('cython', 'ctypes_b', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
      File "scipy/_lib/_ccallback_c.pyx", line 163, in scipy._lib._ccallback_c.test_call_cython (../scipy/_lib/_ccallback_c.c:2063)
        ccallback_prepare(&callback, signatures, callback_obj, CCALLBACK_DEFAULTS)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nodata', 'ctypes', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nodata', 'ctypes', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nodata', 'ctypes_b', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nodata', 'ctypes_b', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nonlocal', 'ctypes', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nonlocal', 'ctypes', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nonlocal', 'ctypes_b', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('nonlocal', 'ctypes_b', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('simple', 'ctypes', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('simple', 'ctypes', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('simple', 'ctypes_b', 'capsule')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

    ======================================================================
    ERROR: test_ccallback.test_callbacks('simple', 'ctypes_b', 'ctypes')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py", line 109, in check
        assert_equal(caller(func, 1.0), 2.0)
    ValueError: Invalid function signature in PyCapsule

**Comment by rgommers** [comment]
The other thing I didn't quite understand was that the ``cffi`` signatures start with ``double (*)`` while the ones used in ``_test_ccallback`` start with ``double``.

    FUNCS = {
        'python': lambda: callback_python,
        'capsule': lambda: _test_ccallback.test_get_plus1_capsule(),
        'cython': lambda: LowLevelCallable.from_cython(_test_ccallback_cython, "plus1_cython"),
        'ctypes': lambda: _test_ccallback_cython.plus1_ctypes,
        'cffi': lambda: _get_cffi_func(_test_ccallback_cython.plus1_ctypes,
                                       'double (*)(double, int *, void *)'),
        'capsule_b': lambda: _test_ccallback.test_get_plus1b_capsule(),
        'cython_b': lambda: LowLevelCallable.from_cython(_test_ccallback_cython, "plus1b_cython"),
        'ctypes_b': lambda: _test_ccallback_cython.plus1b_ctypes,
        'cffi_b': lambda: _get_cffi_func(_test_ccallback_cython.plus1b_ctypes,
                                         'double (*)(double, double, int *, void *)'),
    }

**Comment by pv** [comment]
This is on 32bit? Will take a look once back from traveling.
.
Cffi and cython differ in signatures here. This is just convention, the
precise content of the signatures doesnt matter since they are only used as
tokens.

5.1.2017 2.21 "Ralf Gommers" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
Probable cause is int vs long, which is accpunted for in ndimage/quadpack,
but not iirc in the test code.

6.1.2017 10.12 "Pauli Virtanen" <pvirtn@gmail.com> kirjoitti:

**Comment by pv** [comment]
If so, fix is to add similar ifdefs as in quadpack/ndimage tovthe test code.

6.1.2017 10.14 "Pauli Virtanen" <pvirtn@gmail.com> kirjoitti:

**Comment by rgommers** [comment]
> This is on 32bit? 

indeed

> Probable cause is int vs long

That's what it usually is, but I couldn't find any ``long``s except in an ``info`` field which wasn't used. I'll have a look again.

**Comment by rgommers** [comment]
Okay found it, the ctypes ``func.argtypes`` produces ``LP_c_long`` type names.
