### ISSUE TITLE
scipy.optimize ImportError: cannot import name '_zeta'

### ISSUE THREAD

**Issue by adyomin** [scipy/scipy#6927]
Hi!

I ran into scipy.optimize import error today: whenever I try to import scipy.optimize I get "ImportError: cannot import name '_zeta'" error.  As other similar SO posts suggested, I tried updating scipy (conda upgrade scipy -f) and conda (conda update --all) as well. My macOS system has no uninstalled updates.  I tried rebooting the system.

Here is the error message I get:

> Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.optimize as spo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/optimize/__init__.py", line 233, in <module>
    from ._minimize import *
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 44, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 116, in <module>
    from .matfuncs import *
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py", line 19, in <module>
    import scipy.misc
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/misc/__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/special/__init__.py", line 638, in <module>
    from .basic import *
  File "/Users/adyomin/anaconda/lib/python3.5/site-packages/scipy/special/basic.py", line 15, in <module>
    from ._ufuncs import (ellipkm1, mathieu_a, mathieu_b, iv, jv, gamma,
ImportError: cannot import name '_zeta'
>>> 

I am sorry if I am wasting the team's time, but googling the issue did not help me at all and I cannot really tell myself whether it is something reportable or not.

A.

**Comment by person142** [comment]
Sounds like you have an old version of `special._ufuncs`--the function `zeta` in there was renamed to `_zeta` somewhat recently. What happens if you completely uninstall SciPy and then reinstall a fresh version? (Also, what version of SciPy are you using?)

**Comment by adyomin** [comment]
@person142 conda list was showing both scipy 0.18.1 and scipy 0.17.1 installed.  Just in case I removed conda completely, ran a fresh installation + conda update --all - that did the trick!

Thank you very much for taking time to look into my case!
