### ISSUE TITLE
BUG: special: `generate_ufuncs.py` is broken

### ISSUE THREAD

**Issue by person142** [scipy/scipy#6972]
Running it currently gives the error:

```
Traceback (most recent call last):
  File "generate_ufuncs.py", line 1616, in <module>
    main()
  File "generate_ufuncs.py", line 1609, in main
    ufuncs = Ufunc.parse_all(FUNCS)
  File "generate_ufuncs.py", line 831, in parse_all
    ufuncs.append(cls(m.group(1), m.group(2), m.group(3)))
  File "generate_ufuncs.py", line 863, in __init__
    super(Ufunc, self).__init__(name, signatures, headers)
  File "generate_ufuncs.py", line 757, in __init__
    self.signatures = self._parse_signatures(signatures, headers)
  File "generate_ufuncs.py", line 768, in _parse_signatures
    return [self._parse_signature(x) + (h,) for x, h in zip(sigs, headers)]
  File "generate_ufuncs.py", line 768, in <listcomp>
    return [self._parse_signature(x) + (h,) for x, h in zip(sigs, headers)]
  File "generate_ufuncs.py", line 781, in _parse_signature
    raise ValueError("%s: Invalid signature: %r" % (self.name, sig))
ValueError: _struve_asymp_large_z: Invalid signature: 'struve_asymp_large_z: ddi*d->d'
```

From the history, the root cause is probably https://github.com/scipy/scipy/pull/6861.

**Comment by pv** [comment]
Correct, there's `\\*` in the regexp that should be `\*` with r-prefix.
