### ISSUE TITLE
FAIL:  scipy.integrate - test_odeint_full_jac

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#7038]
teapot:scipy andrew$ python runtests.py -s integrate
Building, see build.log...
Build OK
Running unit tests for scipy.integrate
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy
SciPy version 0.19.0.dev0+
SciPy is installed in /Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy
Python version 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
nose version 1.3.7
.......................................................................................................................................................................................................................F...K............................................
======================================================================
FAIL: test_odeint_jac.test_odeint_full_jac
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 71, in test_odeint_full_jac
    check_odeint(JACTYPE_FULL)
  File "/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy/integrate/tests/test_odeint_jac.py", line 66, in check_odeint
    assert_allclose(yfinal, y1, rtol=1e-12)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-12, atol=0

(mismatch 100.0%)
 x: array([  4.266167e-04,   2.668761e-05,   2.054494e-06,   2.566184e-08,
         3.395174e-10])
 y: array([  4.266167e-04,   2.668761e-05,   2.054494e-06,   2.566184e-08,
         3.395237e-10])

----------------------------------------------------------------------
Ran 264 tests in 2.622s

**Comment by rgommers** [comment]
That failure looked familiar - discussed at https://github.com/scipy/scipy/issues/5335#issuecomment-147944449

Not quite clear why it doesn't fail reproducible between systems.

**Comment by andyfaff** [comment]
Just cleaned the source directory + rebuilt. Problem disappears (so closing).
