### ISSUE TITLE
FAIL - test_decomp.TestEig.test_falker and an IndentationError

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#7039]
Clean and rebuild master on OSX=10.12.3.

teapot:scipy andrew$ python runtests.py
Building, see build.log...
Build OK
Running unit tests for scipy
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy
SciPy version 0.19.0.dev0+
SciPy is installed in /Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy
Python version 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) [GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
nose version 1.3.7

======================================================================
ERROR: Failure: IndentationError (unexpected indent (__init__.py, line 1))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy/cluster/__init__.py", line 1
    """
    ^
IndentationError: unexpected indent

======================================================================
FAIL: test_decomp.TestEig.test_falker
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy/linalg/tests/test_decomp.py", line 286, in test_falker
    self._check_gen_eig(A, B)
  File "/Users/andrew/Documents/Andy/programming/scipy/build/testenv/lib/python3.5/site-packages/scipy/linalg/tests/test_decomp.py", line 228, in _check_gen_eig
    assert_allclose(w[:,perm], wt[:,permt], err_msg=msg)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.5/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.,  1.,  1.],
       [ 0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  1.,  1., -2.]])
array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.]])
(mismatch 16.66666666666667%)
 x: array([[  1.000000e+00 +0.000000e+00j,   1.264977e-16 +6.189609e-09j,
         -1.204097e-01 -1.570127e+00j,  -1.289389e-01 +1.681346e+00j,
         -2.475162e+00 +0.000000e+00j,   2.309522e-16 -1.130063e-08j],...
 y: array([[  1.000000e+00 +0.000000e+00j,   1.164811e-16 +1.003676e-08j,
         -1.204097e-01 -1.570127e+00j,  -1.289389e-01 +1.681346e+00j,
         -2.475162e+00 +0.000000e+00j,   2.126644e-16 -1.832452e-08j],...

----------------------------------------------------------------------
Ran 23941 tests in 308.604s

**Comment by pv** [comment]
How can there be an indentation error?

**Comment by andyfaff** [comment]
No idea, just writing down what the test procedure reported.
