### ISSUE TITLE
Segmentation fault in scipy.ndimage.morphology.grey_opening

### ISSUE THREAD

**Issue by kwohlfahrt** [scipy/scipy#7202]
I'm running into a segmentation fault with an all-false footprint in `grey_opening`. Oddly, it requires the `print` function call to crash after a successful call to `grey_opening` (see sample). Without the successful call, it always crashes.

Looking at pdb, it breaks on `scipy.ndimage.filters._min_or_max_filter` (line 990), specifically the call to `_nd_image.min_or_max_filter`.

```
>>> scipy.version.version
'0.18.1'
```

Sample:

```
import numpy as np
from scipy.ndimage import morphology

data = np.linspace(0, 1, 10, dtype='float')

# Works
#footprint = np.array([False, True], dtype='bool')
#morphology.grey_opening(data, footprint=footprint)
#print(footprint) # Necessary for crash if '# Works' block is present

# SIGSEGV
footprint = np.array([False, False], dtype='bool')
morphology.grey_opening(data, footprint=footprint)
```

Backtrace:

```
(gdb) run test.py
Starting program: /usr/bin/python3 test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2cfa9e2 in NI_MinOrMaxFilter () from /usr/lib/python3/dist-packages/scipy/ndimage/_nd_image.cpython-35m-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007ffff2cfa9e2 in NI_MinOrMaxFilter () from /usr/lib/python3/dist-packages/scipy/ndimage/_nd_image.cpython-35m-x86_64-linux-gnu.so
#1  0x00007ffff2cf82ca in ?? () from /usr/lib/python3/dist-packages/scipy/ndimage/_nd_image.cpython-35m-x86_64-linux-gnu.so
#2  0x00005555557146df in PyCFunction_Call ()
#3  0x00005555556d46e9 in PyEval_EvalFrameEx ()
#4  0x00005555556d97bf in ?? ()
#5  0x00005555556d54c9 in PyEval_EvalFrameEx ()
#6  0x00005555556d9286 in ?? ()
#7  0x00005555556d50a9 in PyEval_EvalFrameEx ()
#8  0x00005555556d9286 in ?? ()
#9  0x00005555556d50a9 in PyEval_EvalFrameEx ()
#10 0x00005555556d9286 in ?? ()
#11 0x00005555556d9f9f in PyEval_EvalCode ()
#12 0x00005555557a78f2 in ?? ()
#13 0x00005555557a9e1d in PyRun_FileExFlags ()
#14 0x00005555557aa5be in PyRun_SimpleFileExFlags ()
#15 0x00005555557d84d7 in Py_Main ()
#16 0x0000555555668c01 in main ()
```

**Comment by rgommers** [comment]
Thanks for the report Kai. This was fixed in 0.19.0 by gh-6877.
