### ISSUE TITLE
scipy.signal.lsim fails if ZeroPolesGain to StateSpace produces complex matrix coefficients

### ISSUE THREAD

**Issue by lafras** [scipy/scipy#7228]
The following script,

    import scipy
    import scipy.signal

    zeros = [1.]
    poles = [1, 1j]
    gain = 1

    system = scipy.signal.lti(
        zeros, poles, gain
    )
    time = scipy.linspace(
        0, 10, 10**4
    )
    input = scipy.square(
        time
    )
    scipy.signal.lsim(
        system, time,  input
    )

fails with,

    Traceback (most recent call last):
      File "bug_demo.py", line 18, in <module>
        system, time,  input
      File ".../.local/lib/python3.5/site-packages/scipy/signal/ltisys.py", line 1969, in lsim
        return lsim2(system, U, T, X0)
      File ".../.local/lib/python3.5/site-packages/scipy/signal/ltisys.py", line 1845, in lsim2
        xout = integrate.odeint(fprime, X0, T, args=(sys, ufunc), **kwargs)
      File ".../.local/lib/python3.5/site-packages/scipy/integrate/odepack.py", line 215, in odeint
        ixpr, mxstep, mxhnil, mxordn, mxords)
    TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'

It is often desirable to specify complex valued poles and zeros. Complex valued states are also required, for example complex voltages and currents in transmission line models.

I suspect the solution could be as simple as passing state space models with complex valued coefficient matrices, or more precisely the `fprime` function from `scipy.signal.ltisys`, to `scipy.integrate.complex_ode`. I'm going to try it and see if it works.

**Comment by ilayn** [comment]
I'm afraid that would be a major undertaking as transfers with complex coefficients require very delicate handling since most of the codebase is specialized for real data. Even Matlab which has a huge capacity behind it does not support fully. For this specific case it might be easy though.

**Comment by rgommers** [comment]
We could at least at a clear error message. The current one just happens to mention something about complex dtype, but that's coming from ``interpolate``.
