### ISSUE TITLE
LAPACK not linked?

### ISSUE THREAD

**Issue by robertsawko** [scipy/scipy#7245]
Hi,

I am building from source Python3 with packages and I came across a strange problem with `scipy`. LAPACK, BLAS and ATLAS are all installed in a non-standard place so I use appropriate variables to point the build process there. I run `python setup.py build` and everything is fine, but the following breaks:

```bash
python -c "import scipy.integrate; print(scipy.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/panther/local/apps/python3/3.6.0/lib/python3.6/site-packages/scipy-0.19.0rc2-py3.6-linux-ppc64le.egg/scipy/integrate/__init__.py", line 55, in <module>
    from .quadrature import *
  File "/gpfs/panther/local/apps/python3/3.6.0/lib/python3.6/site-packages/scipy-0.19.0rc2-py3.6-linux-ppc64le.egg/scipy/integrate/quadrature.py", line 10, in <module>
    from scipy.special import roots_legendre
  File "/gpfs/panther/local/apps/python3/3.6.0/lib/python3.6/site-packages/scipy-0.19.0rc2-py3.6-linux-ppc64le.egg/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: /gpfs/panther/local/apps/python3/3.6.0/lib/python3.6/site-packages/scipy-0.19.0rc2-py3.6-linux-ppc64le.egg/scipy/special/_ufuncs.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: dstevr_
```
Importing scipy on its own will work.

If I add said libraries to `LD_PRELOAD`, then everything works, but would prefer to avoid it. Is there a step I am missing? Happy to share the build log etc.

Thanks.

**Comment by rgommers** [comment]
Maybe a bit late but replying in case others find this.

>  LAPACK, BLAS and ATLAS are all installed in a non-standard place so I use appropriate variables to point the build process there

I suppose you meant environment variables? I suspect that if you'd use a ``site.cfg`` file instead then everything would work as expected.

**Comment by rgommers** [comment]
Closing since this is a query and not a SciPy bug. Feel free to post more though.
