### ISSUE TITLE
Threadsafety parallel threads error on daily builds

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7276]
Apparently a new error, on Python 2.7 wide unicode 64-bit only, but maybe this test has some degree of uncertainty, and this run just happened to hit a failing condition?

```
======================================================================
FAIL: test__threadsafety.test_parallel_threads
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/venv/local/lib/python2.7/site-packages/scipy/_lib/tests/test__threadsafety.py", line 28, in test_parallel_threads
    assert_equal(results, sorted(results))
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 255, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k, err_msg), verbose)
  File "/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 317, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
item=1

 ACTUAL: 2
 DESIRED: 1
```

https://travis-ci.org/MacPython/scipy-wheels/jobs/219597620

**Comment by rgommers** [comment]
was fixed in gh-7711
