### ISSUE TITLE
npymath.ini not found by scipy setup.py

### ISSUE THREAD

**Issue by AgilentGCMS** [scipy/scipy#7289]
I'm trying to install scipy 0.19.0 on top of numpy 1.12.1 that I installed using setup.py. Numpy installed successfully, but when I try to install scipy, it fails. Specifically:

```
$ python setup.py config --compiler=intelem --fcompiler=intelem
setup.py:323: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command, proceeding with "
lapack_opt_info:
lapack_mkl_info:
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/include', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/include', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib']

non-existing path in 'scipy/cluster': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/cluster': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
Running from scipy source directory.
non-existing path in 'scipy/integrate': 'quadpack.h'
Splitting linalg.interpolative Fortran source files
non-existing path in 'scipy/linalg': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/system_info.py:664: UserWarning: Specified path /discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include is invalid.
/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/system_info.py:664: UserWarning: Specified path /discover/nobackup/projects/tm5var4d/packages/python/include/python2.7 is invalid.
/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/system_info.py:664: UserWarning: Specified path /usr/local/include/python2.7 is invalid.
/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/system_info.py:664: UserWarning: Specified path /usr/include/python2.7 is invalid.
blas_opt_info:
blas_mkl_info:
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/include', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/include', '/usr/local/intel/2017/compilers_and_libraries_2017.2.174/linux/mkl/lib']

non-existing path in 'scipy/sparse/csgraph': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/sparse/csgraph': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/sparse/csgraph': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/sparse/csgraph': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/sparse/csgraph': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/sparse': 'sparsetools/sparsetools_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/bsr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csc_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/other_impl.h'
non-existing path in 'scipy/spatial': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
non-existing path in 'scipy/spatial': '/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/include'
Traceback (most recent call last):
  File "setup.py", line 416, in <module>
    setup_package()
  File "setup.py", line 412, in setup_package
    setup(**metadata)
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/core.py", line 135, in setup
  File "setup.py", line 336, in configuration
    config.add_subpackage('scipy')
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 1001, in add_subpackage
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 970, in get_subpackage
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
  File "scipy/setup.py", line 22, in configuration
    config.add_subpackage('spatial')
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 1001, in add_subpackage
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 970, in get_subpackage
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
  File "scipy/spatial/setup.py", line 80, in configuration
    extra_info=get_misc_info("npymath"))
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 2170, in get_info
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/misc_util.py", line 2122, in get_pkg_info
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/npy_pkg_config.py", line 375, in read_config
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/npy_pkg_config.py", line 311, in _read_config_imp
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/npy_pkg_config.py", line 294, in _read_config
  File "/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/distutils/npy_pkg_config.py", line 266, in parse_config
numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg/numpy/core/lib/npy-pkg-config/npymath.ini']
```

I've checked that the file npymath.ini does exist in the egg:

```
$ unzip -l /discover/nobackup/projects/tm5var4d/packages/python/lib/python2.7/site-packages/numpy-1.12.1-py2.7-linux-x86_64.egg | grep npymath
   374958  04-11-2017 14:29   numpy/core/lib/libnpymath.a
      360  04-11-2017 14:29   numpy/core/lib/npy-pkg-config/npymath.ini
```

So I'm not sure why this problem occurs. Any help will be greatly appreciated!

**Comment by AgilentGCMS** [comment]
P.S. - I installed numpy with 'python setup.py install', and that's the route I'm trying to follow for scipy.
