### ISSUE TITLE
SciPy / NLTK import syntax error

### ISSUE THREAD

**Issue by sharmalakshay93** [scipy/scipy#7328]
Not sure what's happening here. The one thing that strikes me as odd is that it looks in python 3.5.2 directories, and then somehow ends up looking into a python 2.6 directory, and then the exception is raised. Please help?

```
Traceback (most recent call last):
  File "svm_bigram.py", line 15, in <module>
    from feature_extractors import FeatureExtractor, UnigramFeatureExtractor
  File "/home/ls4170/Desktop/ml2017project/code/util/feature_extractors.py", line 1, in <module>
    from nltk import word_tokenize
  File "/usr/local/pkg/python/3.5.2/lib/python3.5/site-packages/nltk/__init__.py", line 114, in <module>
    from nltk.collocations import *
  File "/usr/local/pkg/python/3.5.2/lib/python3.5/site-packages/nltk/collocations.py", line 39, in <module>
    from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
  File "/usr/local/pkg/python/3.5.2/lib/python3.5/site-packages/nltk/metrics/__init__.py", line 16, in <module>
    from nltk.metrics.scores import          (accuracy, precision, recall, f_measure,
  File "/usr/local/pkg/python/3.5.2/lib/python3.5/site-packages/nltk/metrics/scores.py", line 16, in <module>
    from scipy.stats.stats import betai
  File "/usr/lib64/python2.6/site-packages/scipy/__init__.py", line 13
    raise ImportError,"Cannot import scipy when running from numpy source directory."
                     ^
SyntaxError: invalid syntax
```

**Comment by pv** [comment]
This looks like you have some problem with your local setup. You can ask unix usage help
e.g. on superuser.com or stackoverflow.com
