### ISSUE TITLE
scipy.signal.dlti(A,B,C,D).freqresp() fails

### ISSUE THREAD

**Issue by drestebon** [scipy/scipy#7335]
Calling the `fresqresp()` method on a `scipy.signal.dlti()` instance is broken in version 0.19. The issue is not there in 0.18.

### Reproducing code example:
```
import scipy.signal as sig
w, h = sig.dlti([[.1]], [[.1]], [[.1]], [[.1]]).freqresp()
```

### Error message:
```
Traceback (most recent call last):
  File "issue.py", line 3, in <module>
    w, h = sig.dlti([[.1]], [[.1]], [[.1]], [[.1]]).freqresp()      
  File "/usr/lib/python3.6/site-packages/scipy/signal/ltisys.py", line 649, in freqresp
    return dfreqresp(self, w=w, n=n, whole=whole)
  File "/usr/lib/python3.6/site-packages/scipy/signal/ltisys.py", line 3588, in dfreqresp
    return w, h
UnboundLocalError: local variable 'h' referenced before assignment
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```

**Comment by e-q** [comment]
Oof, looks like an unfortunate typo in gh-6059. The fix is quick, but I'll need to write some tests for discrete SS systems.

Thanks @drestebon!
