### ISSUE TITLE
attribute "Power" not found

### ISSUE THREAD

**Issue by gwfami** [scipy/scipy#7338]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I'm attempting to run a QGIS plugin, hotspot analysis (https://github.com/danioxoli/HotSpotAnalysis_Plugin).  When ran, it errors out.  

### Reproducing code example:
```
```

### Error message:
```
<Traceback (most recent call last):
  File "/Users/xxx/.qgis2/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 574, in run
    w = DistanceBand(t, threshold1, p=2, binary=False)
  File "/Library/Python/2.7/site-packages/pysal/weights/Distance.py", line 789, in __init__
    neighbors, weights = self._distance_to_W(ids)
  File "/Library/Python/2.7/site-packages/pysal/weights/Distance.py", line 888, in _distance_to_W
    weighted = self.dmat.power(self.alpha)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/sparse/base.py", line 440, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: power not found
```

### Scipy/Numpy/Python version information:
```
('0.13.0b1', '1.9.2', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
Your scipy version is probably too old for the plugin.
You can reopen this issue after testing with a newer version.
