### ISSUE TITLE
Failure on test_parallel threads

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7392]
The daily wheel builds just generated this failure from one build (perhaps coincidentally a 32-bit narrow unicode build):

```
======================================================================
FAIL: test__threadsafety.test_parallel_threads
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/venv/lib/python2.7/site-packages/scipy/_lib/tests/test__threadsafety.py", line 28, in test_parallel_threads
    assert_equal(results, sorted(results))
  File "/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 255, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k, err_msg), verbose)
  File "/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 317, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
item=0

 ACTUAL: 1
 DESIRED: 0
```

https://travis-ci.org/MacPython/scipy-wheels/jobs/230671983

**Comment by rgommers** [comment]
Random one-off failure or was something fixed? Latest daily build looks fine.

**Comment by rgommers** [comment]
Related to gh-7276 I assume, very similar error and also not visible in latest daily build.

**Comment by pv** [comment]
There's a timing issue in the test.

**Comment by matthew-brett** [comment]
Another one: https://travis-ci.org/MacPython/scipy-wheels/jobs/246121508

**Comment by pv** [comment]
fixed in gh-7711
