### ISSUE TITLE
BUG: sparse: load_npz is failing with numpy master

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#7418]
See the Travis test from an unrelated PR: https://travis-ci.org/scipy/scipy/builds/233577623

All of the scipy.sparse.load_npz tests are failing, with the following error:
```
======================================================================
ERROR: test_matrix_io.test_save_and_load_random
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/sparse/_matrix_io.py", line 121, in load_npz
    cls = getattr(scipy.sparse, '{}_matrix'.format(matrix_format))
AttributeError: module 'scipy.sparse' has no attribute ''csc'_matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/sparse/tests/test_matrix_io.py", line 34, in test_save_and_load_random
    _check_save_and_load(dense_matrix)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/sparse/tests/test_matrix_io.py", line 23, in _check_save_and_load
    loaded_matrix = _save_and_load(matrix)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/sparse/tests/test_matrix_io.py", line 15, in _save_and_load
    loaded_matrix = load_npz(tmpfile)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/sparse/_matrix_io.py", line 123, in load_npz
    raise ValueError('Unknown matrix format "{}"'.format(matrix_format))
ValueError: Unknown matrix format "'csc'"
```

The `matrix_format` variable is read directly from an .npz file, so something must have changed in either `np.savez` or `np.load` to produce extra quote characters.

**Comment by pv** [comment]
Numpy bug? Doesn't sound intentional change.
.
Also, the call to `np.load` in `load_npz` certainly should use 
`allow_pickle=False` (needs to check if the numpy version is new enough).

**Comment by charris** [comment]
Seems to be https://github.com/numpy/numpy/pull/8983, although why is another question...

**Comment by WarrenWeckesser** [comment]
This change seems relevant:

With numpy 1.12.1:

```
In [134]: np.__version__
Out[134]: '1.12.1'

In [135]: print(np.array('foo'))
foo
```

With numpy master branch:

```
In [5]: np.__version__
Out[5]: '1.14.0.dev0+1ec9ad6'

In [6]: print(np.array('foo'))
'foo'
```
There are now single quotes in the output.

**Comment by pv** [comment]
Should be fixed by gh-7419 I think. The reliance on how numpy formats bytes scalars to unicode strings is a bit shady and best removed.
