### ISSUE TITLE
test_matrix_norms() in scipy/linalg/tests/test_basic.py calls non-existent np.assert_allclose() 

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7429]
In some circumstances, `test_matrix_norms()` in scipy/linalg/tests/test_basic.py calls `np.assert_allclose()`, which doesn't exist.

```
    def test_matrix_norms(self):
...
                    actual = norm(A, ord=order)
                    desired = np.linalg.norm(A, ord=order)
                    # SciPy may return higher precision matrix norms.
                    # This is a consequence of using LAPACK.
                    if not np.allclose(actual, desired):
                        desired = np.linalg.norm(A.astype(t_high), ord=order)
                        np.assert_allclose(actual, desired)  # <- This line fails

```
### Reproducing code example:
This appeared during an invocation of "python runtests.py", but the ability to trigger this particular code path is likely machine/installation dependent.

### Error message:
```
======================================================================
ERROR: test_basic.TestMatrixNorms.test_matrix_norms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Paul/anaconda/envs/py36scipydev/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/Paul/src/python/scipy/build/testenv/lib/python3.6/site-packages/scipy/linalg/tests/test_basic.py", line 1404, in test_matrix_norms
    np.assert_allclose(actual, desired)
AttributeError: module 'numpy' has no attribute 'assert_allclose'
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.14.0.dev0+d1ff805 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Fixed by gh-7454
