### ISSUE TITLE
DOC: Morphological iterations cannot be float

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7452]
In the docs of [`binary_dilation`]( https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.binary_dilation.html#scipy.ndimage.binary_dilation ), [`binary_erosion`]( https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.binary_erosion.html#scipy.ndimage.binary_erosion ), and probably others `iterations` is described as being `int` or `float`. Not only does `float` type not make sense for `iterations`, it is actually not supported (see code snippet).

Code snippet:

<details>

```python
>>> import numpy as np
>>> import scipy.ndimage as spnd
>>> a = np.zeros((10, 11), dtype=np.uint8)
>>> spnd.binary_dilation(a, iterations=0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zopt/conda2/envs/sptest/lib/python2.7/site-packages/scipy/ndimage/morphology.py", line 502, in binary_dilation
    output, border_value, origin, 1, brute_force)
  File "/zopt/conda2/envs/sptest/lib/python2.7/site-packages/scipy/ndimage/morphology.py", line 268, in _binary_erosion
    origin, invert, coordinate_list)
TypeError: integer argument expected, got float
>>> spnd.binary_dilation(a, iterations=1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zopt/conda2/envs/sptest/lib/python2.7/site-packages/scipy/ndimage/morphology.py", line 502, in binary_dilation
    output, border_value, origin, 1, brute_force)
  File "/zopt/conda2/envs/sptest/lib/python2.7/site-packages/scipy/ndimage/morphology.py", line 268, in _binary_erosion
    origin, invert, coordinate_list)
TypeError: integer argument expected, got float
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: sptest
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::python=2.7.13=1
- conda-forge::readline=6.2=0
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::zlib=1.2.11=0
```

</details>

**Comment by person142** [comment]
I imagine that it is referring to this:

```python
>>> import numpy as np
>>> import scipy.ndimage as spnd
>>> a = np.zeros((10, 11), dtype=np.uint8)
>>> spnd.binary_dilation(a, iterations=1.0)
array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False]], dtype=bool)
```

**Comment by jakirkham** [comment]
That must be it. Though I can't see why that is particularly valuable. Would it make sense to deprecate it?

**Comment by perimosocordiae** [comment]
I'm +1 for deprecating this behavior.

**Comment by sethtroisi** [comment]
This is an old bug but I'm happy to starting a deprecation cycle if there's consensus.

**Comment by rgommers** [comment]
This just seems like something that worked by accident, and then was later documented as accepting `float`. Fine to deprecate I think, go for it @sethtroisi

**Comment by sethtroisi** [comment]
Looks like this was fixed in https://github.com/scipy/scipy/pull/9729 without a dep cycle because it segfaulted. 

I checked that there are no other 'iter.*float' with
```
pcregrep --color -riI -M 'iter.*\n.*float' scipy 2>/dev/null
```
