### ISSUE TITLE
NumPy 1.13 test issue

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7472]
Encountering a test failure when building SciPy 0.19.0 with NumPy 1.13.0. The same error does not occur with NumPy 1.11 or 1.12. The traceback differs between Python 2 and 3, but the same test is failing in both cases and the failure appears very similar. The failure appears identical on both Python 3.5 and 3.6. All other tests pass. Have linked the Travis CI (macOS 10.10) build log below. More details about how it was built can be found in the conda-forge PR ( https://github.com/conda-forge/scipy-feedstock/pull/61 ).

Python 2:

<details>
 
```python
======================================================================
FAIL: test_wrightomega.test_wrightomega_inf_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/scipy_1496908553873/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/travis/miniconda3/conda-bld/scipy_1496908553873/_t_env/lib/python2.7/site-packages/scipy/special/tests/test_wrightomega.py", line 26, in test_wrightomega_inf_branch
    assert_equal(res, 0)
  File "/Users/travis/miniconda3/conda-bld/scipy_1496908553873/_t_env/lib/python2.7/site-packages/numpy/testing/utils.py", line 371, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0j
 DESIRED: 0
----------------------------------------------------------------------
```

</details>

<br>

Python 3:

<details>
 
```python
======================================================================
FAIL: test_wrightomega.test_wrightomega_inf_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/scipy_1496911976288/_t_env/lib/python3.6/site-packages/numpy/testing/utils.py", line 369, in assert_equal
    assert_equal(actuali, desiredi)
  File "/Users/travis/miniconda3/conda-bld/scipy_1496911976288/_t_env/lib/python3.6/site-packages/numpy/testing/utils.py", line 394, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0.0
 DESIRED: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/scipy_1496911976288/_t_env/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/travis/miniconda3/conda-bld/scipy_1496911976288/_t_env/lib/python3.6/site-packages/scipy/special/tests/test_wrightomega.py", line 26, in test_wrightomega_inf_branch
    assert_equal(res, 0)
  File "/Users/travis/miniconda3/conda-bld/scipy_1496911976288/_t_env/lib/python3.6/site-packages/numpy/testing/utils.py", line 371, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0j
 DESIRED: 0
----------------------------------------------------------------------
```

</details>

<br>

ref: https://travis-ci.org/conda-forge/scipy-feedstock/builds/240659843

**Comment by WarrenWeckesser** [comment]
See https://github.com/scipy/scipy/issues/7227

**Comment by jakirkham** [comment]
So then PR ( https://github.com/scipy/scipy/pull/7229 ) should fix this, correct?

**Comment by WarrenWeckesser** [comment]
Yes.  #7229 changes the test so it should work with both the latest numpy and older versions of numpy.

**Comment by jakirkham** [comment]
Great thanks. I'll give that a try and report back.

**Comment by jakirkham** [comment]
That patch solved it for us. Thanks. 😄
