### ISSUE TITLE
OSX test fail - test_ltisys.TestPlacePoles.test_real

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#7590]
I'm experiencing a test failure on current master - OSX 10.12.5.

### Reproducing code example:
```
python -c "import scipy as s; s.test()"
```

### Error message:
```
======================================================================
ERROR: test_ltisys.TestPlacePoles.test_real
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/scipy/signal/tests/test_ltisys.py", line 69, in test_real
    self._check(A, B, (2,2,3,3))
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/scipy/signal/tests/test_ltisys.py", line 45, in _check
    fsf = place_poles(A, B, P, **kwargs)
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/scipy/signal/ltisys.py", line 3006, in place_poles
    poles, B, maxiter, rtol)
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/scipy/signal/ltisys.py", line 2646, in _YT_loop
    det_transfer_matrixb = np.abs(np.linalg.det(transfer_matrix))
  File "/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1804, in det
    r = _umath_linalg.det(a, signature=signature)
RuntimeWarning: invalid value encountered in det

----------------------------------------------------------------------
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.0.dev0+c019b87 1.13.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
I'm not seeing this one on the same OS X version and with numpy 1.13.1. Probably related to Python version, warning behavior is often inconsistent over versions.

**Comment by seberg** [comment]
Well, if this is a bug, it would be a numpy bug, but I guess it just needs `with np.errstate(invalid="ignore")` in the test since fpe flags are pretty inconsistent (unless the warning is bad, in which case I suppose it could put into .

**Comment by rgommers** [comment]
@andyfaff if you still see this failure, could you try fixing it the way @seberg suggests? Would be good to get this one closed.

**Comment by andyfaff** [comment]
I can't reproduce this on 10.12.6, Python 3.6.2, numpy 1.13.1 (home computer). This error was occurring on my work computer which I've now upgraded to 10.12.6, so will have the same config. 

I can try and see if the error is still occurring when I get to work tomorrow, otherwise I'll close it.

**Comment by larsoner** [comment]
Any luck @andyfaff? If you can reproduce and let me know the environment I can try to recreate and fix it for 1.0.

**Comment by andyfaff** [comment]
I can still see the issue on my work computer. This morning I rebased on the tippy top of master, then did a "git clean -xdf", followed by "python runtests.py". Unfortunately I don't have time to fix this myself (vacation next week).

```
OSX 10.12.6,
Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:25:17) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
pytest-3.2.1, py-1.4.34, pluggy-0.4.0.
numpy.version.version='1.13.1'
```
The fail this morning is:
```
=================================================== FAILURES ====================================================
___________________________________________ TestPlacePoles.test_real ____________________________________________


self = <scipy.signal.tests.test_ltisys.TestPlacePoles object at 0x1243729e8>

    def test_real(self):
        # Test real pole placement using KNV and YT0 algorithm and example 1 in
        # section 4 of the reference publication (see place_poles docstring)
        A = np.array([1.380, -0.2077, 6.715, -5.676, -0.5814, -4.290, 0,
                      0.6750, 1.067, 4.273, -6.654, 5.893, 0.0480, 4.273,
                      1.343, -2.104]).reshape(4, 4)
        B = np.array([0, 5.679, 1.136, 1.136, 0, 0, -3.146,0]).reshape(4, 2)
        P = np.array([-0.2, -0.5, -5.0566, -8.6659])
    
        # Check that both KNV and YT compute correct K matrix
        self._check(A, B, P, method='KNV0')
        self._check(A, B, P, method='YT')
    
        # Try to reach the specific case in _YT_real where two singular
        # values are almost equal. This is to improve code coverage but I
        # have no way to be sure this code is really reached
    
>       self._check(A, B, (2,2,3,3))

A          = array([[ 1.38  , -0.2077,  6.715 , -5.676 ],
       [-0.5814, -4.29  ,  0.    ,  0.675 ],
       [ 1.067 ,  4.273 , -6.654 ,  5.893 ],
       [ 0.048 ,  4.273 ,  1.343 , -2.104 ]])
B          = array([[ 0.   ,  5.679],
       [ 1.136,  1.136],
       [ 0.   ,  0.   ],
       [-3.146,  0.   ]])
P          = array([-0.2   , -0.5   , -5.0566, -8.6659])
self       = <scipy.signal.tests.test_ltisys.TestPlacePoles object at 0x1243729e8>

scipy/signal/tests/test_ltisys.py:71: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
scipy/signal/tests/test_ltisys.py:47: in _check
    fsf = place_poles(A, B, P, **kwargs)
scipy/signal/ltisys.py:3006: in place_poles
    poles, B, maxiter, rtol)
scipy/signal/ltisys.py:2646: in _YT_loop
    det_transfer_matrixb = np.abs(np.linalg.det(transfer_matrix))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = array([[ 0.19217467,  0.19217467,  0.24827647,  0.24827647],
       [-0.06100367, -0.06100367, -0.08944558, -0.0894455...    [ 0.54689237,  0.54689237,  0.49367072,  0.49367072],
       [ 0.81256149,  0.81256149,  0.82864196,  0.82864196]])

    def det(a):
        """
        Compute the determinant of an array.
    
        Parameters
        ----------
        a : (..., M, M) array_like
            Input array to compute determinants for.
    
        Returns
        -------
        det : (...) array_like
            Determinant of `a`.
    
        See Also
        --------
        slogdet : Another way to representing the determinant, more suitable
          for large matrices where underflow/overflow may occur.
    
        Notes
        -----
    
        .. versionadded:: 1.8.0
    
        Broadcasting rules apply, see the `numpy.linalg` documentation for
        details.
    
        The determinant is computed via LU factorization using the LAPACK
        routine z/dgetrf.
    
        Examples
        --------
        The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
        >>> a = np.array([[1, 2], [3, 4]])
        >>> np.linalg.det(a)
        -2.0
    
        Computing determinants for a stack of matrices:
    
        >>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
        >>> a.shape
        (3, 2, 2)
        >>> np.linalg.det(a)
        array([-2., -3., -8.])
    
        """
        a = asarray(a)
        _assertRankAtLeast2(a)
        _assertNdSquareness(a)
        t, result_t = _commonType(a)
        signature = 'D->D' if isComplexType(t) else 'd->d'
>       r = _umath_linalg.det(a, signature=signature)
E       RuntimeWarning: invalid value encountered in det

a          = array([[ 0.19217467,  0.19217467,  0.24827647,  0.24827647],
       [-0.06100367, -0.06100367, -0.08944558, -0.0894455...    [ 0.54689237,  0.54689237,  0.49367072,  0.49367072],
       [ 0.81256149,  0.81256149,  0.82864196,  0.82864196]])
result_t   = <class 'numpy.float64'>
signature  = 'd->d'
t          = <class 'numpy.float64'>

/Users/anz/miniconda3/envs/dev3/lib/python3.6/site-packages/numpy/linalg/linalg.py:1804: RuntimeWarning
============================================= 577 tests deselected ==============================================
========= 1 failed, 12086 passed, 1347 skipped, 577 deselected, 73 xfailed, 4 xpassed in 446.08 seconds =========
 DVODE--  At current T (=R1), MXSTEP (=I1) steps   
       taken on this call before reaching TOUT     
      In above message,  I1 =         1
      In above message,  R1 =  0.2569611864708D-12
 ZVODE--  At current T (=R1), MXSTEP (=I1) steps   
       taken on this call before reaching TOUT     
      In above message,  I1 =         1
      In above message,  R1 =  0.2569611864708D-12
 lsoda--  at current t (=r1), mxstep (=i1) steps   
       taken on this call before reaching tout     
      in above message,  i1 =         1
      in above message,  r1 =  0.9999999999999D-09
```

**Comment by larsoner** [comment]
What is your `conda list` for that env? I set one up to hopefully be equivalent but had no errors:
```
# packages in environment at /Users/larsoner/anaconda/envs/py36:
#
certifi                   2016.2.28                py36_0  
cython                    0.26                     py36_0  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0  
pip                       9.0.1                    py36_1  
pluggy                    0.4.0                     <pip>
py                        1.4.34                   py36_0  
pytest                    3.2.1                    py36_0  
python                    3.6.1                         2  
readline                  6.2                           2  
setuptools                36.4.0                   py36_0  
sqlite                    3.13.0                        0  
tempita                   0.5.3                    py36_0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0
```

**Comment by larsoner** [comment]
Oh sorry just saw you posted about `mkl`. Can you try updating to latest `conda` and then the env? I doubt it will help as I suspect this is a MKL/LAPACK architecture issue, so might be difficult to reproduce.

Maybe the easiest thing to do is just catch the warning, saying it happens on some platforms.

**Comment by andyfaff** [comment]
Warning does not appear after upgrading conda, making a new environment and installing python3.6, numpy + mkl.

Original environment list:
```
3alabaster                 0.7.10                   py36_0  
algopy                    0.5.3                     <pip>
altgraph                  0.13                      <pip>
appdirs                   1.4.3                     <pip>
appnope                   0.1.0                    py36_0  
babel                     2.4.0                    py36_0  
bleach                    1.5.0                    py36_0  
bumps                     0.7.6                     <pip>
corner                    2.0.1                     <pip>
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
decorator                 4.0.11                   py36_0  
docutils                  0.13.1                   py36_0  
emcee                     2.2.1                     <pip>
entrypoints               0.2.2                    py36_1  
flake8                    3.3.0                    py36_0  
freetype                  2.5.5                         2  
h5py                      2.7.0               np113py36_0  
hdf5                      1.8.17                        1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.6.1                    py36_0  
ipython                   6.0.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
jbig                      2.1                           0  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
libgpuarray               0.6.9                         0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
line_profiler             2.0                      py36_0  
lmfit                     0.9.6                     <pip>
lxml                      3.8.0                     <pip>
mako                      1.0.6                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np113py36_0  
mccabe                    0.6.1                    py36_0  
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
modulegraph               0.14                      <pip>
mpi4py                    2.0.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numdifftools              0.9.20                    <pip>
numpy                     1.13.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
olefile                   0.44                     py36_0  
openmpi                   1.6.3                         1  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.20.2              np113py36_0  
pandocfilters             1.4.1                    py36_0  
path.py                   10.3.1                   py36_0  
periodictable             1.5.0                     <pip>
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.2.1                    py36_0  
pip                       9.0.1                    py36_1  
pkginfo                   1.4.1                     <pip>
prompt_toolkit            1.0.14                   py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.34                   py36_0  
pycodestyle               2.3.1                    py36_0  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pygpu                     0.6.9               np113py36_0    conda-forge
PyInstaller               3.3.dev0+g8477437           <pip>
PyInstaller               3.3.dev0+g964547c           <pip>
PyInstaller               3.2.1                     <pip>
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytest                    3.2.1                    py36_0  
pytest                    3.1.3                     <pip>
python                    3.6.1                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         0  
qtconsole                 4.3.0                    py36_0  
readline                  6.2                           2  
refl1d                    0.7.9a2                   <pip>
refnx                     0.0.12.dev0+48e167f           <pip>
requests                  2.14.2                   py36_0  
requests-toolbelt         0.8.0                     <pip>
scipy                     0.19.0              np113py36_0  
scipy                     1.0.0.dev0+ebf8f6d           <pip>
setuptools                35.0.2                    <pip>
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sphinx                    1.6.2                    py36_0  
sphinxcontrib             1.0                      py36_0  
sphinxcontrib-websupport  1.0.1                    py36_0  
sqlite                    3.13.0                        0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
theano                    0.9.0                    py36_0  
tk                        8.5.18                        0  
tornado                   4.5.1                    py36_0  
tqdm                      4.15.0                    <pip>
traitlets                 4.3.2                    py36_0  
twine                     1.9.1                     <pip>
uncertainties             3.0.1                     <pip>
virtualenv                15.1.0                    <pip>
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
xlrd                      1.0.0                    py36_0  
xrdtools                  0.1.0                     <pip>
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```
New environment list:
```
certifi                   2016.2.28                py36_0  
cython                    0.26                     py36_0  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0  
pip                       9.0.1                    py36_1  
py                        1.4.34                   py36_0  
pytest                    3.2.1                    py36_0  
python                    3.6.2                         0  
readline                  6.2                           2  
setuptools                36.4.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0  
```

The mkl versions are different. Not sure if it's that.

**Comment by andyfaff** [comment]
I think it's a good idea to close the issue if #7589 passes.

**Comment by andyfaff** [comment]
In my original environment where I was experiencing the issue, I upgraded mkl from `2017.0.1` to `2017.0.3`. The fail no longer occurs. Thus, it seems that the problem was an issue with mkl. So I think this issue can be closed. I would still merge 7589 though.
