### ISSUE TITLE
BUG: Trimmed stats tests are failing on numpy master

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#7598]
Unrelated recent PRs (gh-7596, gh-7123, gh-7592) have started failing on the Python 3.5 / numpy master configuration for the following tests:
```
======================================================================
ERROR: test_stats.TestTrimmedStats.test_tmax
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/scipy/stats/tests/test_stats.py", line 123, in test_tmax
    assert_equal(stats.tmax(x), np.nan)
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/scipy/stats/stats.py", line 721, in tmax
    res = ma.maximum.reduce(am, axis).data
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/numpy/ma/core.py", line 6348, in reduce
    t = self.ufunc.reduce(target, **kwargs)
RuntimeWarning: invalid value encountered in reduce

======================================================================
ERROR: test_stats.TestTrimmedStats.test_tmin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/scipy/stats/tests/test_stats.py", line 98, in test_tmin
    assert_equal(stats.tmin(x), np.nan)
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/scipy/stats/stats.py", line 663, in tmin
    res = ma.minimum.reduce(am, axis).data
  File "/home/travis/build/scipy/scipy/venv/lib/python3.5/site-packages/numpy/ma/core.py", line 6348, in reduce
    t = self.ufunc.reduce(target, **kwargs)
RuntimeWarning: invalid value encountered in reduce

----------------------------------------------------------------------
Ran 21825 tests in 774.595s

FAILED (KNOWNFAIL=91, SKIP=1372, errors=2)
```

Anyone know of recent numpy changes that might cause this?

**Comment by perimosocordiae** [comment]
Looks like numpy/numpy#9020 is the likely source.
