### ISSUE TITLE
test_paths.TestPaths.test_whosmat failure on Python 3.6, 32-bit

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7636]
```
======================================================================
FAIL: test_paths.TestPaths.test_whosmat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/venv/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/scipy/io/tests/test_paths.py", line 58, in test_whosmat
    assert_(contents[0] == ('data', (1, 5), 'int64'))
  File "/venv/lib/python3.6/site-packages/numpy/testing/utils.py", line 77, in assert_
    raise AssertionError(smsg)
AssertionError
```

Failing job: https://travis-ci.org/MacPython/scipy-wheels/jobs/255588602

Scipy wheel build matrix: https://travis-ci.org/MacPython/scipy-wheels/builds/255588592

**Comment by rgommers** [comment]
That's for version scipy-1.0.0.dev0+85287f9, so including gh-7634. So still something wrong @pv

**Comment by pv** [comment]
It's probably int32 vs int64

**Comment by mruffalo** [comment]
Sorry about that -- overly strict check for the results of `whosmat`. See #7649 for updated test code.
