### ISSUE TITLE
Error while passing dok matrix into joblib.Parallel

### ISSUE THREAD

**Issue by StrikerRUS** [scipy/scipy#7699]
Hello!

I have one strange bug with scipy dok matrix when I'm trying to use it in multithread code. This bug occurs only with dok-matrix and on Python 2.7, 3.4, 3.5, 3.6. It says that dok-matrix hasn't attribute **shape**.
I've google a lot and found similar issue closed a few days ago: #1188.
If I replace dok-matrix with any other everything is OK.
Any thoughts?

### Reproducing code example:
``` python
from scipy import sparse
from sklearn.externals.joblib import Parallel, delayed
from my_test import some_action
import numpy as np

test = np.eye(100)
test = sparse.dok_matrix(test)

tmp = Parallel(n_jobs=-1)(delayed(some_action)(test) for _ in range(3))
```
`some_action` is a function wraped into a module to avoid known problem with Python multiprocessing:
```
def some_action(sparse_X):
    return 42
```

### Error message:
```
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\externals\joblib\pool.py", line 362, in get
    return recv()
  File "C:\Program Files\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\dok.py", line 244, in __setitem__
    if (isintlike(i) and isintlike(j) and 0 <= i < self.shape[0]
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\base.py", line 576, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\externals\joblib\pool.py", line 362, in get
    return recv()
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\dok.py", line 244, in __setitem__
    if (isintlike(i) and isintlike(j) and 0 <= i < self.shape[0]
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\base.py", line 576, in __getattr__
    raise AttributeError(attr + " not found")
  File "C:\Program Files\Anaconda3\lib\site-packages\sklearn\externals\joblib\pool.py", line 362, in get
    return recv()
AttributeError: shape not found
  File "C:\Program Files\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\dok.py", line 244, in __setitem__
    if (isintlike(i) and isintlike(j) and 0 <= i < self.shape[0]
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\sparse\base.py", line 576, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found
```

### Scipy/Numpy/Python version information:
```
scipy: 0.19.1
numpy: 1.13.1 
All Python versions
```

**Comment by perimosocordiae** [comment]
This is due to the lack of pickle support for DOK matrices in Python3. There's an open PR (gh-7673) that should fix this bug.

**Comment by person142** [comment]
Now that gh-7673 is in the code runs fine.
