### ISSUE TITLE
Cannot run a single test file in scipy.stats

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#7789]
```
$ python runtests.py -t scipy/stats/tests/test_stats.py 
Building, see build.log...
Build OK (0:00:03.004887 elapsed)
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/br/repos/scipy, inifile: pytest.ini
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 110, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 155, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 645, in perform_collect
INTERNALERROR>     items = self._perform_collect(args, genitems)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 664, in _perform_collect
INTERNALERROR>     parts = self._parsearg(arg)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 758, in _parsearg
INTERNALERROR>     parts[0] = self._tryconvertpyarg(parts[0])
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/main.py", line 738, in _tryconvertpyarg
INTERNALERROR>     loader = pkgutil.find_loader(x)
INTERNALERROR>   File "/usr/lib/python3.5/pkgutil.py", line 485, in find_loader
INTERNALERROR>     spec = importlib.util.find_spec(fullname)
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/importlib/util.py", line 88, in find_spec
INTERNALERROR>     parent = __import__(parent_name, fromlist=['__path__'])
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
INTERNALERROR>   File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
INTERNALERROR>     py.builtin.exec_(co, mod.__dict__)
INTERNALERROR>   File "/home/br/repos/scipy/build/testenv/lib/python3.5/site-packages/scipy/stats/tests/test_stats.py", line 32, in <module>
INTERNALERROR>     from .common_tests import check_named_results
INTERNALERROR> SystemError: Parent module '' not loaded, cannot perform relative import

========================= no tests ran in 0.25 seconds ======
```

OTOH, `$ python runtests.py -s stats` works. Other submodules seem fine, e.g. $ python runtests.py -s linalg$ works. This certainly used to work before, so I'm guessing it's related to `__init__.py` files in the test directories.

**Comment by pv** [comment]
The exact command that you tried actually works for me, on current
scipy master. Another syntax that works is `python runtests.py -t
scipy.stats.tests.test_stats`.

**Comment by pv** [comment]
Maybe try `rm -rf build`?

**Comment by pv** [comment]
However, I think INTERNALERROR is a sign of a Pytest bug that can be reported to them. Of course, that it isn't reproducible makes positive outcomes less likely unless you can find out what's different...

**Comment by ev-br** [comment]
`$ git clean -xdf && python setup.py build` does not make any difference. 

Dotted import path works, thanks! I now see that it's documented with `dotted.paths.like.python.import`, not `path/to/scipy/submodule/tests` in the runtests.py. OK, so it's the way then. 

If pytest bug is suspect, then we should probably compare the environments: this report is with `platform linux -- Python 3.5.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0` on xenial.

Just for the record: trying to use an absolute path fails in a different way:
```
$ python runtests.py -t $PWD/scipy/stats/tests/test_stats.py 
Building, see build.log...
Build OK (0:00:03.004914 elapsed)
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/br/repos/scipy/scipy/stats/tests/test_stats.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/br/repos/scipy/scipy/stats/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/br/repos/scipy/scipy/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/py/_path/local.py", line 680, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
py._path.local.LocalPath.ImportMismatchError: ('scipy.conftest', '/home/br/repos/scipy/build/testenv/lib/python3.5/site-packages/scipy/conftest.py', local('/home/br/repos/scipy/scipy/conftest.py'))
ERROR: could not load /home/br/repos/scipy/scipy/conftest.py
```

**Comment by pv** [comment]
I was using
```
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/pauli/prj/scipy/scipy, inifile: pytest.ini
plugins: xdist-1.15.0, timeout-1.0.0, faulthandler-1.3.0, cov-2.4.0, hypothesis-3.12.0
```
However, I can reproduce the failure with
```
platform linux -- Python 3.5.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/pauli/prj/scipy/scipy, inifile: pytest.ini
plugins: xdist-1.20.0, timeout-1.2.0, forked-0.2, faulthandler-1.3.1, cov-2.5.1, hypothesis-3.21.0
```
So it seems the issue is Python version 3.5. It works for me also on Python 2.7.

**Comment by pv** [comment]
The absolute paths do not work, but that's sort of an intended slightly evil thing.
The run chdirs first to build/testenv/.../site-packages, so it picks the relative path file from the built scipy distribution which can be imported in-place.
