### ISSUE TITLE
intermittent linprog test failure

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7877]
Made it fail less often in gh-7874, but running it in a loop still produces a failure sometimes. There's something in ``linprog`` or in the test case that's not reproducible.

    __________________________________ TestLinprogIPSparse.test_bug_6690 ___________________________________

    self = <scipy.optimize.tests.test_linprog.TestLinprogIPSparse object at 0x969b5a0c>

        def test_bug_6690(self):
            # https://github.com/scipy/scipy/issues/6690
            A_eq = np.array([[0., 0., 0., 0.93, 0., 0.65, 0., 0., 0.83, 0.]])
            b_eq = np.array([0.9626])
            A_ub = np.array([[0., 0., 0., 1.18, 0., 0., 0., -0.2, 0.,
                              -0.22],
                             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                             [0., 0., 0., 0.43, 0., 0., 0., 0., 0., 0.],
                             [0., -1.22, -0.25, 0., 0., 0., -2.06, 0., 0.,
                              1.37],
                             [0., 0., 0., 0., 0., 0., 0., -0.25, 0., 0.]])
            b_ub = np.array([0.615, 0., 0.172, -0.869, -0.022])
            bounds = np.array(
                [[-0.84, -0.97, 0.34, 0.4, -0.33, -0.74, 0.47, 0.09, -1.45, -0.73],
                 [0.37, 0.02, 2.86, 0.86, 1.18, 0.5, 1.76, 0.17, 0.32, -0.15]]).T
            c = np.array([-1.64, 0.7, 1.8, -1.06, -1.16,
                          0.26, 2.13, 1.53, 0.66, 0.28])
        
            with suppress_warnings() as sup:
                sup.filter(RuntimeWarning, "scipy.linalg.solve\nIll...")
                sup.filter(OptimizeWarning, "Solving system with option...")
                sol = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq,
                              bounds=bounds, method=self.method,
                              options=self.options)
    >       _assert_success(sol, desired_fun=-1.191, rtol=1e-6)

    A_eq       = array([[ 0.  ,  0.  ,  0.  ,  0.93,  0.  ,  0.65,  0.  ,  0.  ,  0.83,  0.  ]])
    A_ub       = array([[ 0.  ,  0.  ,  0.  ,  1.18,  0.  ,  0.  ,  0.  , -0.2 ,  0.  ,
           ...       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.25,  0.  ,  0.  ]])
    b_eq       = array([ 0.9626])
    b_ub       = array([ 0.615,  0.   ,  0.172, -0.869, -0.022])
    bounds     = array([[-0.84,  0.37],
           [-0.97,  0.02],
           [ 0.34,  2.86],
           [ ...,  1.76],
           [ 0.09,  0.17],
           [-1.45,  0.32],
           [-0.73, -0.15]])
    c          = array([-1.64,  0.7 ,  1.8 , -1.06, -1.16,  0.26,  2.13,  1.53,  0.66,  0.28])
    self       = <scipy.optimize.tests.test_linprog.TestLinprogIPSparse object at 0x969b5a0c>
    sol        =      con: array([ -3.39662796e-08])
         fun: -1.1887295500861423
     message: 'T...     ,
            0.49999936,  0.47024822,  0.09028211,  0.32000054, -0.72920656])
    sup        = <numpy.testing.utils.suppress_warnings object at 0x969b858c>

    ../scipy/scipy/optimize/tests/test_linprog.py:690: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    res =      con: array([ -3.39662796e-08])
         fun: -1.1887295500861423
     message: 'T...     ,
            0.49999936,  0.47024822,  0.09028211,  0.32000054, -0.72920656])
    desired_fun = -1.191, desired_x = None, rtol = 1e-06, atol = 1e-08

        def _assert_success(res, desired_fun=None, desired_x=None,
                            rtol=1e-8, atol=1e-8):
            # res: linprog result object
            # desired_fun: desired objective function value or None
            # desired_x: desired solution or None
    >       assert_(res.success)
    E       AssertionError

    atol       = 1e-08
    desired_fun = -1.191
    desired_x  = None
    res        =      con: array([ -3.39662796e-08])
         fun: -1.1887295500861423
     message: 'T...     ,
            0.49999936,  0.47024822,  0.09028211,  0.32000054, -0.72920656])
    rtol       = 1e-06

    ../scipy/scipy/optimize/tests/test_linprog.py:118: AssertionError
    ============ 1 failed, 12559 passed, 1398 skipped, 124 xfailed, 8 xpassed in 818.10 seconds

**Comment by rgommers** [comment]
For ``options = {"sparse": False}`` the test passes.

For ``options = {"sparse": True}`` I see 3 types of failures:

- status 3, 'The algorithm terminated successfully and determined that the problem is unbounded.'
- status 2, 'The algorithm terminated successfully and determined that the problem is infeasible.'
- status 0 (success), but not reaching the 1e-6 tolerance

For ``options = {"sparse": True, "_sparse_presolve": True}`` I see 3 types of failures:

- status 1, 'The iteration limit was reached before the algorithm converged.'
- status 3, 'The algorithm terminated successfully and determined that the problem is unbounded.'
- status 2, 'The algorithm terminated successfully and determined that the problem is infeasible.'
- status 0 (success), but not reaching the 1e-6 tolerance
- test errors with ``ZeroDivisionError``:

```
    /home/rgommers/Code/scipy/scipy/sparse/linalg/isolve/lsqr.py:390: RuntimeWarning: invalid value encountered in double_scalars
      arnorm = alfa * beta
    /home/rgommers/Code/scipy/scipy/sparse/linalg/isolve/lsqr.py:431: RuntimeWarning: invalid value encountered in double_scalars
      cs1 = rhobar / rhobar1
    Traceback (most recent call last):
      File "tmp.py", line 57, in <module>
        options=options)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog.py", line 1038, in linprog
        bounds=bounds, callback=callback, **options)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog_ip.py", line 2106, in _linprog_ip
        pc, ip, permc_spec)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog_ip.py", line 1639, in _ip_hsd
        sparse, lstsq, sym_pos, cholesky, pc, ip, permc_spec)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog_ip.py", line 1204, in _get_delta
        (1 / x) * rhatxs, rhatp, solve, splu)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog_ip.py", line 1275, in _sym_solve
        v = solve(M, r)
      File "/home/rgommers/Code/scipy/scipy/optimize/_linprog_ip.py", line 997, in solve
        return sps.linalg.lsqr(M, r)[0]
      File "/home/rgommers/Code/scipy/scipy/sparse/linalg/isolve/lsqr.py", line 432, in lsqr
        sn1 = damp / rhobar1
    ZeroDivisionError: float division by zero
```

**Comment by rgommers** [comment]
There's no use of random numbers; the problem is somewhere in the sparse linalg used. I'll do a bit of testing with compile options to see if it matters. Most likely I'll send a PR to mark the sparse tests as knownfail.

**Comment by rgommers** [comment]
It's an ATLAS bug. The 1.0.0b1 wheels which use OpenBLAS work fine, but compiling against ATLAS 3.10.1 doesn't work with either Bento or setuptools.

**Comment by rgommers** [comment]
Test program for reference:

```
import numpy as np
from scipy.optimize import linprog, OptimizeWarning
from numpy.testing import *
from scipy._lib._numpy_compat import suppress_warnings

# TODO:
# - change assert for res.success to give more info

method = "interior-point"
options = {"sparse": False}


def _assert_success(res, desired_fun=None, desired_x=None,
                    rtol=1e-8, atol=1e-8):
    # res: linprog result object
    # desired_fun: desired objective function value or None
    # desired_x: desired solution or None
    if not res.success:
        print(res)
        raise AssertionError('Not successful')

    assert_equal(res.status, 0)
    if desired_fun is not None:
        assert_allclose(res.fun, desired_fun,
                        err_msg="converged to an unexpected objective value",
                        rtol=rtol, atol=atol)
    if desired_x is not None:
        assert_allclose(res.x, desired_x,
                        err_msg="converged to an unexpected solution",
                        rtol=rtol, atol=atol)


for ix in range(100):
    print(ix)
    # https://github.com/scipy/scipy/issues/6690
    A_eq = np.array([[0., 0., 0., 0.93, 0., 0.65, 0., 0., 0.83, 0.]])
    b_eq = np.array([0.9626])
    A_ub = np.array([[0., 0., 0., 1.18, 0., 0., 0., -0.2, 0.,
                      -0.22],
                     [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                     [0., 0., 0., 0.43, 0., 0., 0., 0., 0., 0.],
                     [0., -1.22, -0.25, 0., 0., 0., -2.06, 0., 0.,
                      1.37],
                     [0., 0., 0., 0., 0., 0., 0., -0.25, 0., 0.]])
    b_ub = np.array([0.615, 0., 0.172, -0.869, -0.022])
    bounds = np.array(
        [[-0.84, -0.97, 0.34, 0.4, -0.33, -0.74, 0.47, 0.09, -1.45, -0.73],
         [0.37, 0.02, 2.86, 0.86, 1.18, 0.5, 1.76, 0.17, 0.32, -0.15]]).T
    c = np.array([-1.64, 0.7, 1.8, -1.06, -1.16,
                  0.26, 2.13, 1.53, 0.66, 0.28])

    with suppress_warnings() as sup:
        sup.filter(RuntimeWarning, "scipy.linalg.solve\nIll...")
        sup.filter(OptimizeWarning, "Solving system with option...")
        sol = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq,
                      bounds=bounds, method=method,
                      options=options)
    _assert_success(sol, desired_fun=-1.191, rtol=1e-6)

```

**Comment by pv** [comment]
Might not necessarily be a bug per se, could also be the problem is ill conditioned somehow and fp rounding errors (generally not reproducible even inside same process) make the results change.

**Comment by rgommers** [comment]
True, the changing failure modes hint at ill conditioning.

**Comment by rgommers** [comment]
@mdhaber pinging you FYI. It doesn't look like an urgent issue to solve.

**Comment by mdhaber** [comment]
OK I'll take a look at some point. This test case came from #6690, which the simplex method always failed on, and which the interior-point method seemed to solve. The cause was that the problem had redundancy. The presolve should be taking care of that and making it easy. Is this still only happening on 32-bit linux @rgommers ?

**Comment by rgommers** [comment]
> Is this still only happening on 32-bit linux @rgommers ?

Not sure, I don't have builds against ATLAS on other platforms available to test right now.

**Comment by mdhaber** [comment]
Unfortunately I'm not able to reproduce this on my machine, and I'm not able to explore building against ATLAS these days. Without something to play with, this would be tough to figure out.

Additional options that would be useful for debugging would be to try:
`options = {"sparse": False, "presolve":False}`, 
`options = {"sparse": True, "presolve":False}`, 
`options = {"sparse": False, "rr":False}`, and
`options = {"sparse": True, "rr":False}`.
It would be good to know whether the problem exists without presolve/redundancy removal since this problem is known to have redundancy.

**Comment by rgommers** [comment]
``options = {"sparse": True, "rr":False}`` fails, the other three options pass.

**Comment by mdhaber** [comment]
@rgommers Are we still having this problem?
