### ISSUE TITLE
Can not import seaborn becasue of something wrong with SciPy

### ISSUE THREAD

**Issue by ycao72** [scipy/scipy#7899]
When I tried to import seaborn, I got following messages:

```
.import seaborn
Traceback (most recent call last):

  File "<ipython-input-4-085c0287ecb5>", line 1, in <module>
    import seaborn

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\seaborn\__init__.py", line 6, in <module>
    from .rcmod import *

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\seaborn\rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\seaborn\palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\seaborn\utils.py", line 7, in <module>
    from scipy import stats

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 348, in <module>
    from .stats import *

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\stats\stats.py", line 175, in <module>
    import scipy.special as special

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal

  File "C:\Users\yc\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm

ImportError: cannot import name '_ellipsoid'
```

Can anybody help me solve this problem?

**Comment by Lewn** [comment]
Could you give a bit more information about your system, like:
Output of
```
import sys; print(sys.version_info)
import numpy; print(numpy.__version__)
import scipy; print(scipy.__version__)
```
Also I see that you are using the conda package manager, so could you run `conda list` from your command prompt and give the output?

**Comment by pv** [comment]
Looks like a broken installation, not a sign of a bug in scipy.
