### ISSUE TITLE
failing scipy-wheels build cython 0.27 with numpy 1.8.2

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7944]
Fails repeatably, see https://travis-ci.org/MacPython/scipy-wheels/jobs/280352607. Not yet clear what is going on exactly, needs investigating. It's the Python 3.5 OS X build. All other 1.0.0rc1 wheels are uploaded as expected to http://wheels.scipy.org/

Details:

```
$ export PLAT=x86_64

$ export NP_BUILD_DEP="numpy==1.8.2"

$ export NP_TEST_DEP="numpy==1.8.2"

$ export UNICODE_WIDTH=32

$ export MANYLINUX_URL="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"

$ export WHEELHOUSE_UPLOADER_USERNAME=travis-worker

$ export WHEELHOUSE_UPLOADER_SECRET=[secure]

$ export DAILY_COMMIT=master

$ export MB_PYTHON_VERSION=3.5

$ export NP_BUILD_DEP=numpy==1.8.2

$ export NP_TEST_DEP=numpy==1.9.3
```

Traceback:

    Collecting numpy==1.8.2

    Downloading numpy-1.8.2.tar.gz (3.8MB)

    Collecting Cython

    Downloading Cython-0.27-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.6MB)

    Building wheels for collected packages: numpy

    Running setup.py bdist_wheel for numpy: started

    Running setup.py bdist_wheel for numpy: still running...

    Running setup.py bdist_wheel for numpy: still running...

    Running setup.py bdist_wheel for numpy: finished with status 'done'

    Stored in directory: /Users/travis/Library/Caches/pip/wheels/48/d7/8b/b2e37adc3a510c826347246df0149aa5b76bf7cdaa3fb79966

    Successfully built numpy

    Installing collected packages: numpy, Cython

    Successfully installed Cython-0.27 numpy-1.8.2

    Processing /Users/travis/build/MacPython/scipy-wheels/scipy

    Building wheels for collected packages: scipy

    Running setup.py bdist_wheel for scipy: started

    Running setup.py bdist_wheel for scipy: finished with status 'error'

    Complete output from command /Users/travis/build/MacPython/scipy-wheels/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpavauuy5rpip-wheel-:

    Cythonizing sources

    Running scipy/linalg/_generate_pyx.py

    Running scipy/special/_generate_pyx.py

    Processing scipy/_lib/_ccallback_c.pyx

    Processing scipy/_lib/messagestream.pyx

    Traceback (most recent call last):

        File "/Users/travis/build/MacPython/scipy-wheels/venv/bin/cython", line 7, in <module>

        from Cython.Compiler.Main import setuptools_main

        File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>

        from .Scanning import PyrexScanner, FileSourceDescriptor

    ImportError: dlopen(/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet

        Referenced from: /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

        Expected in: flat namespace

    in /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

    Traceback (most recent call last):

        File "/Users/travis/build/MacPython/scipy-wheels/venv/bin/cython", line 7, in <module>

        from Cython.Compiler.Main import setuptools_main

        File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>

        from .Scanning import PyrexScanner, FileSourceDescriptor

    ImportError: dlopen(/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet

        Referenced from: /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

        Expected in: flat namespace

    in /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

    Processing scipy/cluster/_hierarchy.pyx

    Processing scipy/cluster/_optimal_leaf_ordering.pyx

    Traceback (most recent call last):

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 265, in <module>

        main()

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 261, in main

        find_process_files(root_dir)

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 250, in find_process_files

        for result in pool.imap(lambda args: process(*args), jobs):

        File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 695, in next

        raise value

        File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 119, in worker

        result = (True, func(*args, **kwds))

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 250, in <lambda>

        for result in pool.imap(lambda args: process(*args), jobs):

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 195, in process

        processor_function(fromfile, tofile, cwd=path)

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/tools/cythonize.py", line 72, in process_pyx

        raise Exception('Cython failed')

    Exception: Cython failed

    Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/setup.py", line 418, in <module>

        setup_package()

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/setup.py", line 402, in setup_package

        generate_cython()

        File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/setup.py", line 206, in generate_cython

        raise RuntimeError("Running cythonize failed!")

    RuntimeError: Running cythonize failed!

    Traceback (most recent call last):

        File "/Users/travis/build/MacPython/scipy-wheels/venv/bin/cython", line 7, in <module>

        from Cython.Compiler.Main import setuptools_main

        File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>

        from .Scanning import PyrexScanner, FileSourceDescriptor

    ImportError: dlopen(/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet

        Referenced from: /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

        Expected in: flat namespace

    in /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

    Traceback (most recent call last):

        File "/Users/travis/build/MacPython/scipy-wheels/venv/bin/cython", line 7, in <module>

        from Cython.Compiler.Main import setuptools_main

        File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 28, in <module>

        from .Scanning import PyrexScanner, FileSourceDescriptor

    ImportError: dlopen(/Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet

        Referenced from: /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

        Expected in: flat namespace

    in /Users/travis/build/MacPython/scipy-wheels/venv/lib/python3.5/site-packages/Cython/Compiler/Scanning.cpython-35m-darwin.so

    

    ----------------------------------------

    Failed building wheel for scipy

    Running setup.py clean for scipy

    Complete output from command /Users/travis/build/MacPython/scipy-wheels/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-rsv8vc85-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

    

    `setup.py clean` is not supported, use one of the following instead:

    

        - `git clean -xdf` (cleans all files)

        - `git clean -Xdf` (cleans all versioned files, doesn't touch

                            files that aren't checked into the git repo)

    

    Add `--force` to your command to use it anyway if you must (unsupported).

    

    

    ----------------------------------------

    Failed cleaning build dir for scipy

    Failed to build scipy

    ERROR: Failed to build one or more wheel

**Comment by matthew-brett** [comment]
Thats https://github.com/cython/cython/issues/1880 - should be fixed in imminent new Cython release.

**Comment by rgommers** [comment]
Thanks, good to know. Not blocking for 1.0.0rc1 then - will just upload the 3.5 OS X wheel later.

**Comment by pv** [comment]
The wheel builds should probably pin dependency versions in the html files.

27.9.2017 22.53 "Ralf Gommers" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
*yml

27.9.2017 22.53 "Ralf Gommers" <notifications@github.com> kirjoitti:

**Comment by rgommers** [comment]
Yes, I think the master branch should use pins, while the daily branch should probably use the latest version of dependencies to detect problems like this as soon as possible.
