### ISSUE TITLE
scipy_solve_discrete_are wont solve (while MATLAB will)

### ISSUE THREAD

**Issue by Sup3rGeo** [scipy/scipy#7971]
I am using the python control module to compute a DLQR controller with the values from this matfile included:
[ufsm lqr from python.zip](https://github.com/scipy/scipy/files/1352291/ufsm.lqr.from.python.zip)

However when solving it I get a exception:

```
Traceback (most recent call last): File "C:/Users/Victor/PycharmProjects/convertercontrol/routine_with_matfile.py", line 14, in <module> control.dare(mat["A_til"], mat["B_til"], mat["Q"], mat["R"], S=None, E=None) File "C:\Python27\lib\site-packages\control\mateqn.py", line 700, in dare X = solve_discrete_are(A, B, Qmat, Rmat) File "C:\Python27\lib\site-packages\scipy\linalg\_solvers.py", line 354, in solve_discrete_are raise ValueError('Matrix A in the algebraic Riccati equation solver ' ValueError: Matrix A in the algebraic Riccati equation solver is ill-conditioned
```

but MATLAB will give me the gains with the data imported from this same file.

Is this a bug in scipy? Or a known limitation?

From documentation I have seen that they use different algorithms:

MATLAB:
[1] Arnold, W.F., III and A.J. Laub, "Generalized Eigenproblem Algorithms and Software for Algebraic Riccati Equations," Proc. IEEE®, 72 (1984), pp. 1746-1754.

SCIPY:

[R127] | (1, 2, 3) P. van Dooren , “A Generalized Eigenvalue Approach For Solving Riccati Equations.”, SIAM Journal on Scientific and Statistical Computing, Vol.2(2), DOI: 10.1137/0902010

[R128] | (1, 2) A.J. Laub, “A Schur Method for Solving Algebraic Riccati Equations.”, Massachusetts Institute of Technology. Laboratory for Information and Decision Systems. LIDS-R ; 859. Available online : http://hdl.handle.net/1721.1/1301

[R129] | (1, 2) P. Benner, “Symplectic Balancing of Hamiltonian Matrices”, 2001, SIAM J. Sci. Comput., 2001, Vol.22(5), DOI: 10.1137/S1064827500367993

### Scipy/Numpy/Python version information:
```
('0.17.1', '1.13.3', sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0))
```

**Comment by ilayn** [comment]
I've given an answer already on https://github.com/python-control/python-control/issues/157 but this is not reproducible on SciPy version 0.19.0 and SciPy 0.19.1

**Comment by rgommers** [comment]
Thanks @ilayn, closing then.

**Comment by Sup3rGeo** [comment]
Updating to version SciPy 0.19.1 solves the problem. Again, thanks to @ilayn.
