### ISSUE TITLE
scipy 1.0.0rc1 doesn't build under fink build system as fink-bld user

### ISSUE THREAD

**Issue by jwhowarth** [scipy/scipy#7979]
The scipy-1.0.0rc1 release fails to build under the fink packaging system as the fink-bld user...

```
creating build/src.macosx-10.13-x86_64-3.6/scipy/_lib
customize Gnu95FCompiler
Found executable /sw/lib/gcc6/bin/gfortran
Traceback (most recent call last):
  File "setup.py", line 418, in <module>
    setup_package()
  File "setup.py", line 414, in setup_package
    setup(**metadata)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/sw/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/sw/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/sw/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/sw/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/sw/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/sw/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
    sources = self.generate_sources(sources, ext)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "scipy/_lib/setup.py", line 32, in get_messagestream_config
    if config_cmd.check_func('open_memstream', decl=True, call=True):
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/config.py", line 312, in check_func
    self._check_compiler()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/command/config.py", line 83, in _check_compiler
    self.fcompiler.customize(self.distribution)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 502, in customize
    get_flags('opt', oflags)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 493, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
  File "/sw/lib/python3.6/site-packages/numpy/distutils/environment.py", line 39, in __getattr__
    return self._get_var(name, conf_desc)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/environment.py", line 53, in _get_var
    var = self._hook_handler(name, hook)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 700, in _environment_hook
    return hook()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/gnu.py", line 364, in get_flags_opt
    return GnuFCompiler.get_flags_opt(self)
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/gnu.py", line 212, in get_flags_opt
    v = self.get_version()
  File "/sw/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 434, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
### execution of /tmp/fink.i4sZ8 failed, exit code 1
### execution of /tmp/fink.n22cf failed, exit code 1
```

### Reproducing code example:
```
The current fink scipy-py.info packaging file can be used to reproduce the issue with the change...

Index: scipy-py.info
===================================================================
RCS file: /cvsroot/fink/dists/10.9-libcxx/stable/main/finkinfo/sci/scipy-py.info,v
retrieving revision 1.12
diff -u -r1.12 scipy-py.info
--- scipy-py.info	23 Jun 2017 20:34:52 -0000	1.12
+++ scipy-py.info	5 Oct 2017 11:10:00 -0000
@@ -1,9 +1,10 @@
 Info2: <<
 Package: scipy-py%type_pkg[python]
-Version: 0.19.1
+Version: 1.0.0rc1
 Epoch: 1
 Revision: 1
 Maintainer: None <fink-devel@lists.sourceforge.net>
+BuildAsNobody: true
 Type: python (2.7 3.4 3.5 3.6), gcc (6)
 Depends: <<
 	cython-py%type_pkg[python],
@@ -23,7 +24,7 @@
 <<
 #Source: mirror:sourceforge:scipy/scipy-%v.tar.gz
 Source: http://github.com/scipy/scipy/releases/download/v%v/scipy-%v.tar.xz
-Source-MD5: cad6bac0638b176f72c00fe81ed54d19
+Source-MD5: ed1da4d65cc16706665aa5f8fdc97b1b
 PatchScript: <<
 #!/bin/bash -ev
   cat <<EOF > site.cfg
@@ -81,7 +82,7 @@
  fi
 <<
 InfoTest: <<
-TestDepends: nose-py%type_pkg[python]
+TestDepends: nose-py%type_pkg[python], pytest-py%type_pkg[python]
 TestScript: touch %b/INSTALL_MAKE_CHECK
 <<
 DocFiles: INSTALL.rst.txt LICENSE.txt
```

### Error message:
```
numpy.distutils.fcompiler.CompilerNotFound
```

### Scipy/Numpy/Python version information:
```
scipy 1.0.0rc1, numpy 1.13.3 and python 3.6.2
```

**Comment by jwhowarth** [comment]
Building the sci-py 1.0.0rc1 package as root instead of the fink-bld user eliminates the build failure. This is done in the fink scipy-py.info packaging file by changing...

BuildAsNobody: true

to

BuildAsNobody: false

**Comment by jwhowarth** [comment]
A similar issue was introduced in the numpy 1.13.x release series which fails to build in the fink build system as the fink-bld user with the error...

```
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I/sw/include

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/sw/include/python3.6m -c'
gcc: _configtest.c

failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 392, in <module>
    setup_package()
  File "setup.py", line 384, in setup_package
    setup(**metadata)
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/sw/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/sw/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/sw/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/sw/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/sw/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/sw/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/command/build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/sw/src/fink.build/numpy-py36-1.13.3-1/numpy-1.13.3/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 674, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program
### execution of ATLAS=None failed, exit code 1
### execution of /tmp/fink.akp9X failed, exit code 1
```

**Comment by jwhowarth** [comment]
It appears the problem its that the build is attempted to write the  _configtest.c file into a directory that the fink-bld user doesn't have write permission for but I have been unable to get python to spew the details of where exactly the source and compiled files during the configuration tests are being placed.

**Comment by jwhowarth** [comment]
Likewise, for the numpy 1.13.x series, building as root instead of as the normal fink-bld user is the only workaround to avoid the build failures under the fink packaging system.

**Comment by jwhowarth** [comment]
FYI, the fink packaging system is available at http://www.finkproject.org.

**Comment by matthew-brett** [comment]
Can we write `_configtest.c` to a temporary directory instead?

**Comment by pv** [comment]
Not an issue in scipy. This is a numpy.distutils or python distutils 
issue issue, and probably ultimately an issue in the configuration of 
the specific build environment.

Note in particular that buildbots of Linux distributions, or standard 
OSX or Linux builds do not require root access.

**Comment by pv** [comment]
@matthew-brett: afaik the location of the file is decided by Python 
distutils and not controlled by us. I think it just puts it to the 
current working directory.

**Comment by jwhowarth** [comment]
The actual problem has been pinpointed to be that the fink-bld user account created for the fink packaging system doesn't define a shell. By passing 'SHELL=/bin/sh' when python is being executed, the build failures are eliminated in both numpy 1.13.3 and scipy 1.0.0.

[https://marc.info/?l=fink-devel&m=150993626715362&w=2](url)

**Comment by person142** [comment]
Thanks for following up @jwhowarth.

**Comment by dhomeier** [comment]
Just beat me to it! In numpy/distutils/exec_command.py:_exec_command()
```
    if os.name == 'posix' and use_shell:
        # On POSIX, subprocess always uses /bin/sh, override
        sh = os.environ.get('SHELL', '/bin/sh')
        if is_sequence(command):
            command = [sh, '-c', ' '.join(command)]
        else:
            command = [sh, '-c', command]
        use_shell = False
```
The actual problem is the environment variable **being** defined, but `SHELL=/usr/bin/false` for this non-privileged account. Instead of setting it to a working shell, unsetting it also solves the problem. Question is perhaps, does POSIX mandate `SHELL` to be set to a functional shell? Otherwise one could add a check here (but `/usr/bin/false` is  even executable, so that might not be that easy to catch). Anyway re-defining or unsetting `SHELL` should work for the Fink build environment.
