### ISSUE TITLE
Shape bug in scipy.optimize.least_squares (trf) with custom loss function and jac as linear operator

### ISSUE THREAD

**Issue by rmcgibbo** [scipy/scipy#8023]
I believe there is a shape/broadcasting bug in the scipy.optimize._lsq.common::left_multiplied_operator's matmat implementation, which causes a crash when using scipy.optimize.least_squares with a jacobian passed as a linearoperator and a custom loss function

### Reproducing code example:
```
import numpy as np
import scipy.optimize
from scipy.optimize._numdiff import approx_derivative
from scipy.sparse.linalg import aslinearoperator

X = np.linspace(1,10)
Y = 2*X + 1 + 0.01 * np.random.RandomState(0).randn(len(X))

def fun(p):
    return X*p[0] + p[1] - Y

def jac(x):
    return aslinearoperator(approx_derivative(fun, x))

r = scipy.optimize.least_squares(
    fun=lambda p: X*p[0] + p[1] - Y,
    jac=jac,
    x0=[0, 0],
    loss='huber',
)
```

### Error message:
```
Traceback (most recent call last):
  File "example.py", line 19, in <module>
    loss='huber,
  File "/prefix/lib/python2.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 908, in least_squares
    tr_options.copy(), verbose)
  File "/prefix/lib/python2.7/site-packages/scipy/optimize/_lsq/trf.py", line 124, in trf
    loss_function, tr_solver, tr_options, verbose)
  File "/prefix/lib/python2.7/site-packages/scipy/optimize/_lsq/trf.py", line 491, in trf_no_bounds
    JS = J_h.dot(S)
  File "/prefix/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 364, in dot
    return self.matmat(x)
  File "/prefix/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 326, in matmat
    Y = self._matmat(X)
  File "/prefix/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 466, in _matmat
    return self.__matmat_impl(X)
  File "/prefix/lib/python2.7/site-packages/scipy/optimize/_lsq/common.py", line 642, in matmat
    return J.matmat(X * d[:, np.newaxis])
  File "/prefix/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 326, in matmat
    Y = self._matmat(X)
  File "/prefix/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 466, in _matmat
    return self.__matmat_impl(X)
  File "/prefix/lib/python2.7/site-packages/scipy/optimize/_lsq/common.py", line 625, in matmat
    return d * J.matmat(X)
ValueError: operands could not be broadcast together with shapes (50,) (50,2)
```

### Scipy/Numpy/Python version information:
```
$ python -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'
('0.19.1', '1.13.1', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by rmcgibbo** [comment]
I believe that the fix is to change [this line](https://github.com/scipy/scipy/blob/master/scipy/optimize/_lsq/common.py#L625) from `return d * J.matmat(X)` to `return d[:, np.newaxis] * J.matmat(X)`.

**Comment by nmayorov** [comment]
Thanks for the report. Wasn't tested because the option is not that useful and widely used. I sent a fix.
