### ISSUE TITLE
scipy.io.savemat throws error when dict key is unicode

### ISSUE THREAD

**Issue by talih0** [scipy/scipy#8026]
scipy.io.savemat throws error (from numpy) when dict key is unicode
Error only shows up with an embedded dict

### Reproducing code example:
import scipy.io as sio
test_dict = {u'a':{u'b':1}} 
sio.savemat('dat_name.mat', test_dict)

### Error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 211, in savemat
    MW.put_variables(mdict)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 847, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 588, in write_top
    self.write(arr)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 606, in write
    narr = to_writeable(arr)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 444, in to_writeable
    return np.array([tuple(values)], dtype)
TypeError: data type not understood

### Scipy/Numpy/Python version information:
('0.19.1', '1.11.0', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))

**Comment by ilayn** [comment]
Is it related to your typo? If I correct the variable name I don't get any problems.

**Comment by talih0** [comment]
The problem is still there when I fixed the typo. I believe the error is coming from numpy (I'm using version 1.11.0)

**Comment by ilayn** [comment]
It is possible, I'm using 1.13.1

**Comment by talih0** [comment]
The problem can be fixed by change line 440 in scipy/io/matlab/mio5.py from 
dtype.append((field, object)) to dtype.append((str(field), object))
