### ISSUE TITLE
Installing scipy from pip on linux x86 does not get the wheel anymore

### ISSUE THREAD

**Issue by david-caro** [scipy/scipy#8077]
Hi,
Since the last release (1.0.0) when trying to install it on a linux box (using a fedora docker container) it does not download the wheel anymore, and attempts to build it from the source and fails (as the machine is not properly configured for it).

I've noticed that when installing the previous rc version, it pulls the wheel:

```
 (virtualenv)[test@0de41f02ca21 code]$ pip install --pre scipy=='1.0.0rc2'
Collecting scipy==1.0.0rc2
  Downloading scipy-1.0.0rc2-cp27-cp27mu-manylinux1_x86_64.whl (46.7MB)
    100% |████████████████████████████████| 46.7MB 23kB/s 
Requirement already satisfied: numpy>=1.8.2 in /virtualenv/lib/python2.7/site-packages (from scipy==1.0.0rc2)
Installing collected packages: scipy
  Found existing installation: scipy 1.0.0rc1
    Uninstalling scipy-1.0.0rc1:
      Successfully uninstalled scipy-1.0.0rc1
```
but on pipy I there's no `cp27mu` wheel, just `cp27m`. I have no idea (yet) of what that means but might help you debug.

Thanks!

### Reproducing code example:
```
docker run -ti --rm fedora bash
$ dnf install python-pip
$ pip install scipy
```

### Error message:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-V2OUzP/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip-build-V2OUzP/scipy/setup.py", line 414, in setup_package
        setup(**metadata)
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 336, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 419, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1126, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1138, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 491, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 671, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 697, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 878, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1117, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/setup.py", line 392, in <module>
        # This import is here because it needs to be done before importing setup()
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/setup.py", line 384, in setup_package
    
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/core.py", line 169, in setup
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 152, in run
        self.run_command("egg_info")
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/command/egg_info.py", line 26, in run
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/command/build_src.py", line 148, in run
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/command/build_src.py", line 159, in build_sources
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/command/build_src.py", line 294, in build_library_sources
      File "/tmp/easy_install-sAFDS6/numpy-1.13.3/numpy/distutils/command/build_src.py", line 377, in generate_sources
      File "numpy/core/setup.py", line 674, in get_mathlib_info
    
    RuntimeError: Broken toolchain: cannot link a simple C program
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
('1.0.0rc2', '1.13.3', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by matthew-brett** [comment]
Yes, I'm very sorry about that.   Our wheel-building procedure failed for that wheel, because of a problem with Travis-CI - see: https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

We'll put up the wheel as soon as we can.

**Comment by david-caro** [comment]
Hehehe, we are suffering that issue too :), completely sympathize.

**Comment by dabercro** [comment]
It might not be my place, but I would recommend completing all the wheel builds before announcing a release. An awful lot of us open-source science people are using linux.

**Comment by matthew-brett** [comment]
I can't say if it's your place or not - but yes - that is our policy - to complete the wheel builds before uploading.  I think we just tripped up on that this time.  Sorry about that.  Python 2.7 wheels should be up now.  One 32-bit Python 3.6 wheel remains to build - the Travis-CI problem continues.

**Comment by matthew-brett** [comment]
Wheels all uploaded now.

**Comment by rgommers** [comment]
thanks Matthew.

**Comment by rgommers** [comment]
> I can't say if it's your place or not - but yes - that is our policy - to complete the wheel builds before uploading. I think we just tripped up on that this time.

That is the policy in general, but in this case there was too much to coordinate, limited time to do it and no timeline on the TravisCI fix. So a conscious choice.

We also try to be careful to upload first wheels and then tarballs, but this is not commonplace for Python projects. If your setup cannot handle building from source, you should use ``pip install --binary-only`` so it fetches an older wheel rather than picks up a new tarball.

**Comment by matthew-brett** [comment]
I hope that next time, there will not be as hard a deadline for the release.  It was unlucky that we happened to this Travis-CI problem just at release time, it's unusual to get a problem this general and long-lasting.

Luckily, projects are gradually starting to release wheels first, partly in response to feedback like yours.

**Comment by ilayn** [comment]
I think trusting TravisCI is not a fault on our side. They have a really excellent reputation, rightly so. I think the number 1.0 made everybody a bit excited and hence impatient :)

**Comment by hcho3** [comment]
Hello all,

Sorry to hijack the thread, but I just noticed that one Linux x86 wheel is missing for the 1.0.0 release. The [PyPI page](https://pypi.python.org/pypi/scipy/1.0.0) does not list `scipy-1.0.0-cp36-cp36m-manylinux1_i686.whl`.

I do see all wheels present for the 1.0.0rc2, so for now I'll stick with that version. Thank you all for your work.

**Comment by matthew-brett** [comment]
Oh dear - sorry - my fault - the upload broke before it finished on my laptop.  I just uploaded again, it should be OK now.

**Comment by hcho3** [comment]
@matthew-brett Thanks!
