### ISSUE TITLE
32-bit Intel tests for python2 for test_fitpack fail with segfault in fpbisp

### ISSUE THREAD

**Issue by andreasbaumann** [scipy/scipy#8122]
Environment: Archlinux 32, python-scipy 1.0.0, python-numpy 1.13.3, python 2.7.14

```
linux32 arch-chroot /var/lib/archbuild/staging-i686/copy
cd /var/lib/archbuild/staging-i686/copy/build/python-scipy/src/
export PYTHONPATH=/build/python-scipy/src/test/usr/lib/python2.7/site-packages/
python2 -c "from scipy import test; test('full')"
...
test/usr/lib/python2.7/site-packages/scipy/interpolate/tests/test_fitpack.py ..................Segmentation fault (core dumped)
gdb /usr/bin/python2 core
Core was generated by `python2 -c from scipy import test; test('full')'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf4236019 in fpbisp (tx=..., nx=13, ty=..., ny=13, c=..., kx=1, ky=1, x=..., mx=2621440, y=...,
    my=2621440, z=..., wx=..., wy=..., lx=..., ly=...) at scipy/interpolate/fitpack/fpbisp.f:74
74                z(m) = sp
(gdb) bt
#0  0xf4236019 in fpbisp (tx=..., nx=13, ty=..., ny=13, c=..., kx=1, ky=1, x=..., mx=2621440, y=...,
    my=2621440, z=..., wx=..., wy=..., lx=..., ly=...) at scipy/interpolate/fitpack/fpbisp.f:74
#1  0xf42373e8 in bispev (tx=..., nx=13, ty=..., ny=13, c=..., kx=1, ky=1, x=..., mx=2621440, y=...,
    my=2621440, z=..., wrk=..., lwrk=10485760, iwrk=..., kwrk=5242880, ier=0)
    at scipy/interpolate/fitpack/bispev.f:101
#2  0xf4230011 in fitpack_bispev ()
   from /build/python-scipy/src/test/usr/lib/python2.7/site-packages/scipy/interpolate/_fitpack.so
#3  0xf7414fdf in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#4  0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#5  0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#6  0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#7  0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#8  0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#9  0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#10 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#11 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#12 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#13 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#14 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#15 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#16 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#17 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#18 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#19 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#20 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
#21 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#22 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#23 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#24 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#25 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#26 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#27 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
#28 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#29 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#30 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#31 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#32 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#33 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#34 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#35 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#36 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#37 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#38 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#39 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#40 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#41 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#42 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#43 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#44 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#45 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
#46 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#47 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#48 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#49 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#50 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#51 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#52 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#53 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#54 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#55 0xf749aacb in PyEval_CallObjectWithKeywords () from /usr/lib/libpython2.7.so.1.0
#56 0xf744af8e in PyInstance_New () from /usr/lib/libpython2.7.so.1.0
#57 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#58 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#59 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#60 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#61 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#62 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#63 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#64 0xf741a5f4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#65 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#66 0xf741a5f4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#67 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#68 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#69 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#70 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
#71 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#72 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#73 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#74 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#75 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#76 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#77 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#78 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#79 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#80 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
#81 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#82 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#83 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#84 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#85 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#86 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#87 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#88 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#89 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#90 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#91 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#92 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#93 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#94 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#95 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
---Type <return> to continue, or q <return> to quit---
#96 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
#97 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#98 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#99 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#100 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#101 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#102 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#103 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#104 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#105 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#106 0xf7417dd5 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#107 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#108 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#109 0xf741aaf4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#110 0xf74156a0 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#111 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#112 0xf7445c28 in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#113 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#114 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#115 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#116 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
#117 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#118 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#119 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#120 0xf741a5f4 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#121 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#122 0xf7445a5a in function_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#123 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#124 0xf7464422 in instancemethod_call.lto_priv () from /usr/lib/libpython2.7.so.1.0
#125 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#126 0xf74ad21b in slot_tp_call () from /usr/lib/libpython2.7.so.1.0
#127 0xf73f27a9 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#128 0xf741a4a3 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#129 0xf749b3ca in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#130 0xf74a355d in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
#131 0xf74b7b9a in run_mod () from /usr/lib/libpython2.7.so.1.0
#132 0xf74b9a39 in PyRun_StringFlags () from /usr/lib/libpython2.7.so.1.0
#133 0xf74b9aa7 in PyRun_SimpleStringFlags () from /usr/lib/libpython2.7.so.1.0
#134 0xf74a2b4e in Py_Main () from /usr/lib/libpython2.7.so.1.0
#135 0x565905c6 in main ()
```

See also https://bbs.archlinux32.org/viewtopic.php?pid=595#p595

**Comment by rgommers** [comment]
How did you install or build SciPy? Compiler versions, build log?

**Comment by andreasbaumann** [comment]
The Archlinux build log is here: [build.log](https://github.com/scipy/scipy/files/1457463/build.log)

gcc --version
gcc (GCC) 7.2.0

**Comment by rgommers** [comment]
One uncommon warning:
```
/usr/lib/python3.6/site-packages/numpy/distutils/system_info.py:572: UserWarning: 
*********************************************************************
    Could not find lapack library within the ATLAS installation.
*********************************************************************
```

This is very weird, the test suite completes (with 1 failure), and then a new build is started (the test suite of which segfaults). No build command is visible. Never seen that before, looks like something the Archlinux build setup does. Any idea why?
```
test/usr/lib/python3.6/site-packages/scipy/special/tests/test_orthogonal.py:297: AssertionError
 1 failed, 12423 passed, 1565 skipped, 101 xfailed, 6 xpassed in 1565.40 seconds 

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE
```


```
test/usr/lib/python2.7/site-packages/scipy/interpolate/tests/test_fitpack.py ................../startdir/PKGBUILD: line 41:  8425 Segmentation fault      (core dumped) python2 -c "from scipy import test; test('full')"
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Build failed, check /data/archbuild/staging-i686/copy/build
```

**Comment by andreasbaumann** [comment]
Ah. Thanks. Now I have can dig deeper. Maybe the math support in atlas, blas, etc. is broken in
Archlinux32..

**Comment by ilayn** [comment]
Closing this one as it seems to be dusting on the shelf. We can repoen if it comes back again.
