### ISSUE TITLE
Inconsistent handling of inf by scipy.linalg.norm and numpy.linalg.norm

### ISSUE THREAD

**Issue by jfowkes** [scipy/scipy#8143]
The latest version of scipy throws an error when calling scipy.linalg.norm on np.inf, previously this returned inf as numpy.linalg.norm does. This is not only unexpected behaviour but also inconsistent.    

### Reproducing code example:
```
import numpy as np
import scipy.linalg as linalg
np.linalg.norm(np.inf) # inf
linalg.norm(np.inf) # error (should be inf)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/misc.py", line 129, in norm
    a = np.asarray_chkfinite(a)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1215, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by ilayn** [comment]
Yes, this is also reflected in the source https://github.com/scipy/scipy/blob/master/scipy/linalg/misc.py#L136

But this has been so since the last 6 years according to `git blame`

**Comment by jfowkes** [comment]
Sorry, yes but either way it's unexpected and inconsistent behaviour compared to numpy norm.

**Comment by ilayn** [comment]
Sure, I didn't mean to imply that a change is unnecessary. Docs need some refreshments apparently.

**Comment by jfowkes** [comment]
Sure, is there any reason for not using numpy norm's inf handling?
