### ISSUE TITLE
scipy.sparse.bmat fails if all submatrices have same number of rows

### ISSUE THREAD

**Issue by andreasbuhr** [scipy/scipy#8190]
scipy.sparse.bmat fails if all submatrices have same number of rows

### Reproducing code example:
```
import numpy as np
import scipy
import scipy.sparse

blocks = [
[ np.ones(2,3), np.ones(2,4)],
[ np.ones(2,3), np.ones(2,4)]
]

scipy.sparse.bmat(blocks)
```

### Error message:
```
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    [ np.ones(2,3), np.ones(2,4)],
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 190, in ones
    a = empty(shape, dtype, order)
TypeError: data type not understood
```

### Scipy/Numpy/Python version information:
```
('0.17.0', '1.11.0', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
That error is from your own code, before the execution reaches 
scipy.sparse.bmat

**Comment by andreasbuhr** [comment]
yes, sorry, was a typo while reducing the reproducer. Now the code is as intended, after edit

**Comment by pv** [comment]
Workaround: pass the input as an object array

 >>> blocks = np.zeros([2, 2], dtype='object')
 >>> blocks[0,0] = np.ones((2,3))
...
 >>> scipy.sparse.bmat(blocks)

**Comment by perimosocordiae** [comment]
Reproduced with scipy 1.0.0 and numpy 1.13.3. It seems that `np.array` has trouble handling the nested lists containing submatrices, despite the `dtype=object` argument.

**Comment by pv** [comment]
bmat could be ok just doing `n = len(blocks); m = len(blocks[0])`, maybe 
as a fallback...

**Comment by andreasbuhr** [comment]
I worked around it by appending a row of matrices with zero rows each to "blocks".

**Comment by perimosocordiae** [comment]
I'm not familiar with how `np.array` coercion logic works, but this seems like a bug to me.
