### ISSUE TITLE
using scipy.sparse.csr_matrix in spark cause error

### ISSUE THREAD

**Issue by wangty6** [scipy/scipy#8254]
While using scipy.sparse.csr_matrix as a part of a rdd in pyspark, error occurs when spark is doing shuffle.

### Reproducing code example:
```
product = left.join(
            right
            # RDD[(bi, bk, bj), (blk_1, blk_2)], bkl is csr_matrix
        ).mapValues(
            lambda (blk1, blk2): blk1 * blk2
            # RDD[(bi, bk, bj), blk]
        ).map(
            lambda ((i, k, j), blk): ((i, j), blk)
            # RDD[(bi, bj), blk]
        ).reduceByKey(
            lambda blk1, blk2: blk1 + blk2
            # RDD[(bi, bj), blk]
        )   

```
notice that the reduceByKey cause shuffling

### Error message:
```
17/12/28 16:28:02 WARN scheduler.TaskSetManager: Lost task 16.0 in stage 19.0 (TID 1942, sparkSlaveRec9, executor 15): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/data5/hadoop/tmp/usercache/wangtianyu/appcache/application_1511613193444_46759/container_1511613193444_46759_01_000016/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/data5/hadoop/tmp/usercache/wangtianyu/appcache/application_1511613193444_46759/container_1511613193444_46759_01_000016/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/data/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
  File "/data/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
  File "/data/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 346, in func
  File "/data/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1828, in combineLocally
  File "/data5/hadoop/tmp/usercache/wangtianyu/appcache/application_1511613193444_46759/container_1511613193444_46759_01_000016/pyspark.zip/pyspark/shuffle.py", line 236, in mergeValues
    for k, v in iterator:
  File "/data/opt/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1950, in <lambda>
  File "/home/wangtianyu/recommend_alg/welog/matrix_mult/module/block_matrix.py", line 58, in <lambda>
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 303, in __mul__
    return self._mul_sparse_matrix(other)
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py", line 514, in _mul_sparse_matrix
    fn = getattr(sparsetools, self.format + '_matmat_pass1')
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 440, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: format not found

```

### Scipy/Numpy/Python version information:
```
('0.19.1', '1.8.2', sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0))
```

**Comment by andyfaff** [comment]
It's not clear to me that this is a scipy issue. Do you have a minimum reproducible example using scipy alone?

**Comment by pv** [comment]
Doesn't look like scipy issue (self.format is here always `csr` or `csc` both of which have the matmat_pass1 routine), probably there's a custom sparse matrix subclass or something like that involved, as one can guess from having a `block_matrix.py`?
