### ISSUE TITLE
multiple test failures 

### ISSUE THREAD

**Issue by rahilhastu** [scipy/scipy#8365]
The test gave 6 failures on python 2.7.12,ubuntu 16.04 after successful installation of Scipy.

### Reproducing code example:
```
import scipy
scipy.test()
```

### Error message:
```
FAIL: test_indeterminate_covariance (test_minpack.TestCurveFit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/tests/test_minpack.py", line 402, in test_indeterminate_covariance
    lambda x, a, b: a*x, xdata, ydata)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1724, in assert_warns
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1676, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling curve_fit

======================================================================
FAIL: test_singular (test_filter_design.TestGroupDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/signal/tests/test_filter_design.py", line 2135, in test_singular
    assert_warns(UserWarning, group_delay, (b, a), w=w)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1724, in assert_warns
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1676, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling group_delay

======================================================================
FAIL: Regression test for #651: better handling of badly conditioned
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/signal/tests/test_filter_design.py", line 167, in test_bad_filter
    assert_raises(BadCoefficients, tf2zpk, [1e-15], [1.0, 1.0])
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1141, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: BadCoefficients not raised

======================================================================
FAIL: test_example1a (test_morestats.TestAndersonKSamp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/stats/tests/test_morestats.py", line 215, in test_example1a
    midrank=False)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1724, in assert_warns
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1676, in _assert_warns_context
    raise AssertionError("No warning raised" + name_str)
AssertionError: No warning raised when calling anderson_ksamp

======================================================================
FAIL: test_nanmedian_all (test_stats.TestNanFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/stats/tests/test_stats.py", line 234, in test_nanmedian_all
    assert_equal(len(w), 2)  # Deprecation & RuntimeWarning
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 375, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0
 DESIRED: 2

======================================================================
FAIL: test_nanmedian_all_axis (test_stats.TestNanFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/stats/tests/test_stats.py", line 243, in test_nanmedian_all_axis
    assert_equal(len(w), 4)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 375, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 3
 DESIRED: 4

```

### Scipy/Numpy/Python version information:
```
Scipy.__version__ ->0.17.0 
Numpy.__version__ ->1.11.0 
sys.version_info->sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
This is not reproducible on the recent versions of SciPy and NumPy.

**Comment by rahilhastu** [comment]
On upgading my Scipy and numpy versions it gives the following errors(these are just a few as there are many Errors but all of the same type { pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.} ):
### Reproducing code example:
```
import scipy
scipy.test()
```
### Error message:
```

________________ ERROR at setup of TestCircFuncs.test_circfuncs ________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestCircFuncs.test_circfuncs_small _____________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestCircFuncs.test_circmean_axis ______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestCircFuncs.test_circvar_axis _______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestCircFuncs.test_circstd_axis _______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
__________ ERROR at setup of TestCircFuncs.test_circfuncs_array_like ___________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
__________________ ERROR at setup of TestCircFuncs.test_empty __________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestCircFuncs.test_circmean_scalar _____________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestCircFuncs.test_circmean_range ______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestCircFuncs.test_circfuncs_unit8 _____________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
___________________ ERROR at setup of test_accuracy_wilcoxon ___________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of test_wilcoxon_result_attributes _______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________________ ERROR at setup of test_wilcoxon_tie ______________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestMedianTest.test_bad_n_samples ______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestMedianTest.test_empty_sample ______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
________ ERROR at setup of TestMedianTest.test_empty_when_ties_ignored _________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_________ ERROR at setup of TestMedianTest.test_empty_contingency_row __________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
________________ ERROR at setup of TestMedianTest.test_bad_ties ________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_____________ ERROR at setup of TestMedianTest.test_bad_nan_policy _____________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestMedianTest.test_bad_keyword _______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_________________ ERROR at setup of TestMedianTest.test_simple _________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
______________ ERROR at setup of TestMedianTest.test_ties_options ______________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
___________ ERROR at setup of TestMedianTest.test_nan_policy_options ___________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
_________________ ERROR at setup of TestMedianTest.test_basic __________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23
________ ERROR at setup of TestMquantiles.test_mquantiles_limit_keyword ________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator and let the consumer call and iterate over it.:

    @pytest.fixture(scope="function", autouse=True)
    def check_fpu_mode(request):
        """
        Check FPU mode was not changed during the test.
        """
        old_mode = get_fpu_mode()
        yield
        new_mode = get_fpu_mode()
    
        if old_mode != new_mode:
            warnings.warn("FPU mode changed from {0:#x} to {1:#x} during "
                          "the test".format(old_mode, new_mode),
                          category=FPUModeChangeWarning, stacklevel=0)
/home/rahilhastu/.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/conftest.py:23

``` 
### Scipy/Numpy/Python version information:
Scipy version -> 1.1.0.dev0+5531da3
Numpy version -> 1.14.0
Sys version info -> sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
Python version -> 2.7.12

**Comment by pv** [comment]
You probably have too old version of pytest.

**Comment by ilayn** [comment]
You might upgrade your pytest

**Comment by rahilhastu** [comment]
```
scipy.test() 
```
on upgrading pytest worked fine .but,
```
import scipy
scipy.test("full")
```
gave the following errors:
### Error Messages:
```
=================================== FAILURES ===================================
________________ TestLineSearch.test_line_search_wolfe2_bounds _________________

self = <scipy.optimize.tests.test_linesearch.TestLineSearch object at 0x7f833e4ba6d0>

    def test_line_search_wolfe2_bounds(self):
        # See gh-7475
    
        # For this f and p, starting at a point on axis 0, the strong Wolfe
        # condition 2 is met if and only if the step length s satisfies
        # |x + s| <= c2 * |x|
        f = lambda x: np.dot(x, x)
        fp = lambda x: 2 * x
        p = np.array([1, 0])
    
        # Smallest s satisfying strong Wolfe conditions for these arguments is 30
        x = -60 * p
        c2 = 0.5
    
        s, _, _, _, _, _ = ls.line_search_wolfe2(f, fp, x, p, amax=30, c2=c2)
        assert_line_wolfe(x, p, s, f, fp)
    
        s, _, _, _, _, _ = assert_warns(LineSearchWarning,
                                        ls.line_search_wolfe2, f, fp, x, p,
                                        amax=29, c2=c2)
        assert_(s is None)
    
        # s=30 will only be tried on the 6th iteration, so this won't converge
        assert_warns(LineSearchWarning, ls.line_search_wolfe2, f, fp, x, p,
>                    c2=c2, maxiter=5)

_          = None
c2         = 0.5
f          = <function <lambda> at 0x7f834d994a28>
fp         = <function <lambda> at 0x7f834d9949b0>
p          = array([1, 0])
s          = None
self       = <scipy.optimize.tests.test_linesearch.TestLineSearch object at 0x7f833e4ba6d0>
x          = array([-60,   0])

.local/lib/python2.7/site-packages/scipy-1.1.0.dev0+5531da3-py2.7-linux-x86_64.egg/scipy/optimize/tests/test_linesearch.py:236: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/dist-packages/numpy/testing/nose_tools/utils.py:1731: in assert_warns
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib.GeneratorContextManager object at 0x7f833e4baa50>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               self.gen.next()
E               AssertionError: No warning raised when calling line_search_wolfe2

self       = <contextlib.GeneratorContextManager object at 0x7f833e4baa50>
traceback  = None
type       = None
value      = None

/usr/lib/python2.7/contextlib.py:24: AssertionError

```
