### ISSUE TITLE
while running a python program i am getting this error

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [scipy/scipy#8399]
Traceback (most recent call last):
  File "quick_test.py", line 12, in <module>
    from utils import save_data, load_dataset, save_dataset, sort_result, predict_label, extract_melgrams
  File "I:\Coding\Music-Genre-Classification-with-Deep-Learning-master\utils.py", line 5, in <module>
    import librosa
  File "C:\Users\dsemw\env_songs\lib\site-packages\librosa\__init__.py", line 11, in <module>
    from . import core
  File "C:\Users\dsemw\env_songs\lib\site-packages\librosa\core\__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\dsemw\env_songs\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\dsemw\env_songs\lib\site-packages\librosa\util\__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\dsemw\env_songs\lib\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\ndimage\__init__.py", line 161, in <module>
    from .filters import *
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\misc\__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\interpolate\__init__.py", line 175, in <module>
    from .interpolate import *
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\interpolate\interpolate.py", line 21, in <module>
    import scipy.special as spec
  File "C:\Users\dsemw\env_songs\lib\site-packages\scipy\special\__init__.py", line 644, in <module>
    from . import specfun
ImportError: cannot import name specfun

**Comment by HimanshuAwasthi95** [comment]
Seems like you didn't setup properly

**Comment by matthew-brett** [comment]
@DAKSHSEMWAL - how did you install Scipy?    What happens if you do this from a `cmd` window?

```
cd c:\
python -c 'import scipy.special'
```

**Comment by DAKSHSEMWAL** [comment]
I installed scipy using
pip install scipy

**Comment by matthew-brett** [comment]
What do you get for the commands above?

**Comment by czgdp1807** [comment]
As @HimanshuAwasthi95 said, there is a problem with the setup. You can perform a complete reinstall to solve the issue. Though the chances are low but still try it out.

**Comment by ilayn** [comment]
no repro, closing.
