### ISSUE TITLE
function thereshold in scipy.stats seems to not exist anymore

### ISSUE THREAD

**Issue by ami88** [scipy/scipy#8450]
I am trying to use a python module that uses scipy. When I import it, I get an error, apparently because is trying to import the function threshold but this does not exist in the scipy version that is installed in my institution. Is there an easy way to fix this? (Note: I do not have root permissions in my computer, so I cannot fix this by myself, but I could transmit whatever advice to the team with root permissions.)

### Reproducing code example:
```
import mpdaf
```
### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/__init__.py", line 37, in <module>
    from . import drs, MUSE, obj, sdetect, tools
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/drs/__init__.py", line 34, in <module>
    from .rawobj import *
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/drs/rawobj.py", line 46, in <module>
    from ..obj import Image, WCS
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/obj/__init__.py", line 35, in <module>
    from .cube import *
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/obj/cube.py", line 55, in <module>
    from .image import Image
  File "/usr/pkg/python/Python-2.7.9/lib/python2.7/site-packages/mpdaf/obj/image.py", line 53, in <module>
    from scipy.stats import threshold
ImportError: cannot import name threshold
```
### Scipy/Numpy/Python version information:
```
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0))
```

**Comment by ilayn** [comment]
A couple of years ago, `threshold` has been deprecated in #4976 if I understand correctly in version 0.17. You can see the announcement in the old release notes regarding `np.clip` https://docs.scipy.org/doc/scipy/reference/release.0.17.0.html#deprecated-features 

Hence mpdaf needs to update or you have to downgrade your version of scipy.
