### ISSUE TITLE
Error in SmoothSphereBivariateSpline(): "ValueError: Error code returned by bispev: 10"

### ISSUE THREAD

**Issue by Ethunxxx** [scipy/scipy#8565]
The following code produces the error message below. I'm not 100% sure if this is a bug or just an error in the code. Regardless, the error message is not very meaninful IMO.

### Reproducing code example:
```
import numpy as np
from scipy.interpolate import SmoothSphereBivariateSpline

#Define the input data and the original sampling points
NSamp = 2000
Theta = np.random.uniform(0,np.pi,NSamp)
Phi   = np.random.uniform(0,2*np.pi, NSamp)
Data  = np.ones(NSamp)

Interpolator = SmoothSphereBivariateSpline(Theta, Phi, Data, s=3.5)

#Prepare the grid to which the input shall be interpolated
NLon = 64
NLat = 32
GridPosLons = np.arange(NLon)/NLon * 2 * np.pi
GridPosLats = np.arange(NLat)/NLat * np.pi
LatsGrid, LonsGrid = np.meshgrid(GridPosLats, GridPosLons)
Lats = LatsGrid.ravel()
Lons = LonsGrid.ravel()

#Interpolate
Interpolator(Lats, Lons)
```

### Error message:
```Traceback (most recent call last):

  File "<ipython-input-127-81e0ea6e3eed>", line 1, in <module>
    runfile('/home/username/Documents/Python/Playground/TestFile.py', wdir='/home/username/Documents/Python/Playground')

  File "/home/username/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/username/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/username/Documents/Python/Playground/TestFile.py", line 36, in <module>
    Interpolator(Lats, Lons)

  File "/home/username/anaconda3/lib/python3.6/site-packages/scipy/interpolate/fitpack2.py", line 1265, in __call__
    dx=dtheta, dy=dphi, grid=grid)

  File "/home/username/anaconda3/lib/python3.6/site-packages/scipy/interpolate/fitpack2.py", line 845, in __call__
    raise ValueError("Error code returned by bispev: %s" % ier)

ValueError: Error code returned by bispev: 10
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.1 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment]
As answered in https://stackoverflow.com/questions/49318113/error-when-trying-to-interpolate-using-smoothspherebivariatespline-valueerro, if `np.meshgrid` is already used for input data, the interpolate function should be called like `Interpolator(Lats, Lons, grid=False)`.

I think "Error code returned by bispev: 10" means invalid input.
https://github.com/scipy/scipy/blob/2a9e4923aa2be5cd54ccf2196fc0da32fe459e76/scipy/interpolate/fitpack/bispev.f#L45-L50
So, I think it is possible to improve the error message.

**Comment by AtsushiSakai** [comment]
I think this is also related #9850
