### ISSUE TITLE
Q: Does runtests.py --refguide-check need env (or other) variables set when run on a local machine?

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8703]
Building the refguide on my local machine fails with an ASCII UnicodeDecodeError.

### Reproducing code example:
```
python runtests.py -g --refguide-check
```

### Error message:
```
Building, see build.log...
Build OK (0:00:11.577518 elapsed)
Running checks for 29 modules:
scipy.cluster .. 
scipy.cluster.hierarchy ............................................F................... 
scipy.cluster.vq .......... 
scipy.constants ......................................................................................................................................................................... 
scipy.fftpack ................................................................ 
scipy.fftpack.convolve ......... 
scipy.integrate ............................................F....F...F.. 
scipy.interpolate .................................................................................................. 
scipy.io ..............F........... 
scipy.io.arff ......... 
scipy.io.wavfile ....... 
scipy.linalg ..................................................................................................................................................F.......................................... 
scipy.linalg.blas ................................................................................................................................................. 
scipy.linalg.lapack ........................................................................................................................................................................................................................................................................................................................... 
scipy.linalg.interpolative ........................ 
scipy.misc F........... 
scipy.ndimage .................................................................................................................................................. 
scipy.odr .................................. 
scipy.optimize .......................................................................................................F.............. 
scipy.signal ..............................................................................................................................................................FF......................................................F........................................................F............................................................ 
scipy.signal.windows ..................................................
scipy.sparse ............................................................................ 
scipy.sparse.csgraph ................................................ 
scipy.sparse.linalg .................................................................. 
scipy.spatial .........................F........ 
scipy.spatial.distance ............................................................ 
scipy.special ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F....................................................................................................................F..................................... 
scipy.stats .....F..FF..F..FF.F.FF.FFF.FF....F.F.FFF.FFF.....FFFF.F..F..FFFFF.FF......F.F...FFF...FF....FFFFF.F..F...F.FF..F.FF.F.F.FFF.FF..F.FF.....FF..F..F......FFF.F.FF.F.FFF.FF.F...F....FFF...F.F..F..F..F....F.FFF.FF.F...........F............................F..............F........................................F......F....F...............................................................F...................F............F...... 
scipy.stats.mstats ...........................................................................F.................F......F.......................................

Checking tutorial files at doc/source/tutorial/*.rst:

arpack.rst F
basic.rst .
csgraph.rst .
fftpack.rst .
general.rst .
index.rst .
integrate.rst .
interpolate.rst .
io.rst 
linalg.rst Traceback (most recent call last):
  File "/Users/Paul/src/python/scipy/tools/refguide_check.py", line 941, in <module>
    main(argv=sys.argv[1:])
  File "/Users/Paul/src/python/scipy/tools/refguide_check.py", line 894, in main
    dots=dots, doctest_warnings=args.doctest_warnings)
  File "/Users/Paul/src/python/scipy/tools/refguide_check.py", line 758, in check_doctests_testfile
    text = open(fname).read()
  File "/Users/Paul/anaconda/envs/py36scipydev/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28785: ordinal not in range(128)
```

The culprit is line 816 in doc/source/tutorial/linalg.rst:
`scaling and a Padé approximation for :math:`e^{x}` . This algorithm is`
which contains the valid UTF-8 character sequence `P a d \xc3 \xa9 ` but is being decoded as ASCII and fails. (\xc3 \xa9 = \u00E9  = LATIN SMALL LETTER E WITH ACUTE.)

`check_doctests_testfile()` in ref guide_check.py doesn't specify an encoding when it calls `open(flame)`, so Python uses a default encoding, which appears to be ASCII
```
$ python -c "import locale; print(locale.getpreferredencoding(False))"
US-ASCII
```

The machine is Mac OS High Sierra, 10.13.4, with Anaconda Python 3.6, and the environment has:
```
LANG=en_US.UTF-8
LC_ALL=POSIX
```
If I display the line on my terminal via `$ head -n 816 ./doc/source/tutorial/linalg.rst | tail -n 1` then the acute e is displayed correctly, so the terminal appears to be OK.

Is there some environment variable (or other setting) that needs to be set in order to build the refguide?

### Scipy/Numpy/Python version information:
```
1.1.0.dev0+3885541 1.13.1 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
That line probably should have `open(fname, encoding='utf-8')`.

The refguide-check runs OK on my machine, though, but not OSX.

**Comment by pvanmulbregt** [comment]
Py2 doesn't have the `encoding` option.  Perhaps
`text = io.open(fname, encoding='utf-8').read()` 
But that would make the text a Unicode object in Py2, which may not be expected in later processing.
I'll try separating the PY2 and PY3 opening/reading of the file.

**Comment by pv** [comment]
For this script, we might not care about supporting Python 2.

**Comment by pvanmulbregt** [comment]
Got further.  Now seeing lots of errors due to whitespace differences.  E.g.
```
scipy.cluster.hierarchy.inconsistent
------------------------------------

File "build/testenv/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1321, in inconsistent
Failed example:
    print(Z)
Expected:
    [[ 5.          6.          0.          2.        ]
     [ 2.          7.          0.          2.        ]
     [ 0.          4.          1.          2.        ]
     [ 1.          8.          1.15470054  3.        ]
     [ 9.         10.          2.12132034  4.        ]
     [ 3.         12.          4.11096096  5.        ]
     [11.         13.         14.07183949  8.        ]]
Got:
    [[  5.           6.           0.           2.        ]
     [  2.           7.           0.           2.        ]
     [  0.           4.           1.           2.        ]
     [  1.           8.           1.15470054   3.        ]
     [  9.          10.           2.12132034   4.        ]
     [  3.          12.           4.11096096   5.        ]
     [ 11.          13.          14.07183949   8.        ]]
```
and
```
scipy.integrate.romb
--------------------

File "build/testenv/lib/python3.6/site-packages/scipy/integrate/quadrature.py", line 507, in romb
Failed example:
    integrate.romb(y, show=True)
Expected:
    Richardson Extrapolation Table for Romberg Integration       
    ====================================================================
    -0.81576 
    4.63862  6.45674 
    -1.10581 -3.02062 -3.65245 
    -2.57379 -3.06311 -3.06595 -3.05664 
    -1.34093 -0.92997 -0.78776 -0.75160 -0.74256 
    ====================================================================
    -0.742561336672229
Got:
    <BLANKLINE>
           Richardson Extrapolation Table for Romberg Integration       
    ====================================================================
    -0.81576 
     4.63862  6.45674 
    -1.10581 -3.02062 -3.65245 
    -2.57379 -3.06311 -3.06595 -3.05664 
    -1.34093 -0.92997 -0.78776 -0.75160 -0.74256 
    ====================================================================
    <BLANKLINE>
    -0.74256133667222901
```
Any suggestions?

**Comment by pv** [comment]
Numpy >= 1.14.2 is required to get the "new" float print style.

**Comment by pvanmulbregt** [comment]
Updated to Numpy 1.14.2  I now get 3 types of errors:

1. Vector is scaled by -1 in an SVD example
```
scipy.linalg.null_space
-----------------------

File "build/testenv/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 363, in null_space
Failed example:
    null_space(A)
Expected:
    array([[-0.70710678],
           [ 0.70710678]])
Got:
    array([[ 0.70710678],
           [-0.70710678]])
```
This example is using the svd to compute the null space.  The matrix is rank 1, and has singular values [2, 0].  Is the returned matrix uniquely determined? (The computed singular values are actually `array([  2.00000000e+00,   3.35470445e-17])` and I'm guessing that the sign of the second one is random.  And that the vectors in the null-space can be multiplied by -1 without changing their properties.  And all depend on the particular LAPACK in use.)

2. Deprecated and other objects from scipy.misc
```
==========
scipy.misc
==========

Non-deprecated objects in __all__: 5
Objects in refguide: 23

Deprecated objects in refguide::

    comb
    factorial
    factorial2
    factorialk
    info
    logsumexp
    pade
    source
    who
ERROR: objects in refguide but not in scipy.misc.__all__::

    bytescale
    fromimage
    imfilter
    imread
    imresize
    imrotate
    imsave
    imshow
    toimage

This issue should likely be fixed by removing these objects
from the function listing in __init__.py for this module
or adding them to __all__.

scipy.misc.imread
-----------------

scipy.misc.imread has no docstring
...
scipy.misc.toimage
------------------

scipy.misc.toimage has no docstring

```

Q: Do I need to install PIL to do the refguide-check?  [Since the functions were marked deprecated, I hadn't installed PIL.]


3.  Lots of `Inline strong start-string without end-string.` errors such as 
```
scipy.stats.gausshyper
----------------------

scipy.stats.gausshyper:93: (WARNING/2) Inline strong start-string without end-string.::
    
    ------------------------------------------------------------------------
    1       
    2       
    3       A Gauss hypergeometric continuous random variable.
    4       
...
    91                                                             fit(data, a, b, c, z, loc=0, scale=1)  Parameter estimates for generic data.  
    92      expect(func, args=(a, b, c, z), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)  Expected value of a function (of one argument) with respect to the distribution.  
    93                                                                median(a, b, c, z, loc=0, scale=1)  Median of the distribution.  
```

I saw gh-3926 adding back-ticks, and gh-8639 removing them and a comment about a new version of numpydoc.  So I went into doc and did `git submodule init; git submodule update`.  That fixed errors of type 3.
Q. Is there a way to keep the submodules kept up-to-date?

**Comment by pvanmulbregt** [comment]
Installing pillow fixed the scipy.misc.errors.  Just leaves the svd example which appears dependent on the LAPACK.
