### ISSUE TITLE
make_interp_spline leads to operation between list and float

### ISSUE THREAD

**Issue by EdorianDark** [scipy/scipy#8714]
I am trying to make a simple B-spline interpolation:

```
scipy.interpolate.make_interp_spline([0.0, 1.0, 2.0, 3.0], [0.0, 1.0, 4.0, 8.0], 2)
```
which leads to
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "...\scipy\interpolate\_bsplines.py", line 733, in make_interp_spline
    t = (x[1:] + x[:-1]) / 2.
TypeError: unsupported operand type(s) for /: 'list' and 'float'
```

Version info:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.1 1.14.2 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

And the current git version looks the same:
https://github.com/scipy/scipy/blob/b21e2469bea82d15657dbc23b0ec3d8569e4961c/scipy/interpolate/_bsplines.py#L758

**Comment by ev-br** [comment]
Thanks for the report. The fix would be to move the array conversion of x and y to occur before the selection of the knot vector. A PR would be welcome. Otherwise, I'll send a PR with the fix later today.

**Comment by EdorianDark** [comment]
I am still not sure how the correct solution would look like.
