### ISSUE TITLE
ImportError: cannot import name 'LinearNDInterpolator'

### ISSUE THREAD

**Issue by djokester** [scipy/scipy#8809]
I received the following import error while importing keras.
### Reproducing code example:
`>>> import keras
`

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 7, in <module>
    from . import datasets
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/datasets/__init__.py", line 4, in <module>
    from . import imdb
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/datasets/imdb.py", line 8, in <module>
    from ..preprocessing.sequence import _remove_long_seq
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/preprocessing/__init__.py", line 1, in <module>
    from . import image
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/preprocessing/image.py", line 13, in <module>
    import scipy.ndimage as ndi
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/ndimage/__init__.py", line 161, in <module>
    from .filters import *
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/misc/__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 187, in <module>
    from .ndgriddata import *
  File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 10, in <module>
    from .interpnd import LinearNDInterpolator, NDInterpolatorBase, \
ImportError: cannot import name 'LinearNDInterpolator'

```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by matthew-brett** [comment]
It looks like you have an Anaconda installation with a broken Scipy.  I think your best bet is to raise an issue with them, over at https://github.com/ContinuumIO/anaconda-issues .

**Comment by djokester** [comment]
Hey!
Here are the steps I followed.
Updated Conda -> No Effect
Updated SciPy with updated Conda-> No Effect
Updated Keras with updated Conda-> Fixed the Issue.
Leaving the comment here as there arent many LinearNDInterpolator issues on the net.

**Comment by carlosbarrod** [comment]
> pip uninstall Scipy

It worked!!!

**Comment by danagibbon** [comment]
I've been attempting to use `Scipy` in the R package `reticulate`. 
Had been receiving the following errors:
`ImportError: /lib64/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /home/gibbond/anaconda3/envs/r-reticulate/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)`
and
`ImportError: cannot import name 'LinearNDInterpolator' from 'scipy.interpolate.interpnd' (unknown location)` 
Installing through`pip install` instead of `conda install` did the trick. Thanks for posting!

**Comment by sunnyHelen** [comment]
I tried 'pip uninstall Scipy' and 'pip install Scipy'.
But it doesn't work~ 
So sad. Any other solution?
