### ISSUE TITLE
No module named 'mmap'

### ISSUE THREAD

**Issue by mvaccariunipi** [scipy/scipy#8828]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
When importing scipy.io in Python 3.6 the code gives this error  
ModuleNotFoundError: No module named 'mmap' 
reporting module "mmap" is missing

### Reproducing code example:
```
from __future__ import print_function
from builtins import str
from builtins import range
from casadi import *
from casadi.tools import *
from matplotlib import pylab as plt
import math
import scipy.linalg as scla
import scipy.optimize as scopt
from scipy.integrate import odeint
import scipy.io as sio 
```

### Error message:
```
Traceback (most recent call last):

  File "<ipython-input-9-b18abc6b48e0>", line 1, in <module>
    import scipy.io

  File "/Users/marcovaccari/anaconda2/envs/pitone36/lib/python3.6/site-packages/scipy/io/__init__.py", line 100, in <module>
    from .netcdf import netcdf_file, netcdf_variable

  File "/Users/marcovaccari/anaconda2/envs/pitone36/lib/python3.6/site-packages/scipy/io/netcdf.py", line 44, in <module>
    import mmap as mm

ModuleNotFoundError: No module named 'mmap'
```

### Scipy/Numpy/Python version information:
```
1.0.1 1.14.3 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
mmap is Python standard library module, so your Python installation is
probably broken in some way e.g. you have something that overrides the
standard library mmap module.
https://docs.python.org/3/library/mmap.html

**Comment by mvaccariunipi** [comment]
Thanks, problem solved.
