### ISSUE TITLE
CI failing after new pytest release

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#8866]
See e.g. gh-8864.

Pytest had a new release on May 23rd: https://pypi.org/project/pytest/#files. Still needs to be investigated if it's a pytest regression or if we're using something private/incorrectly.

```
.........s.............................................................. [ 35%]
............................................................s........... [ 35%]
.................................s............................INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 65, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 84, in run_one_test
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/warnings.py", line 94, in pytest_runtest_protocol
INTERNALERROR>     with catch_warnings_for_item(item):
INTERNALERROR>   File "/opt/python/3.5.5/lib/python3.5/contextlib.py", line 59, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/warnings.py", line 63, in catch_warnings_for_item
INTERNALERROR>     for mark in item.iter_markers(name='filterwarnings'):
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/nodes.py", line 192, in <genexpr>
INTERNALERROR>     return (x[1] for x in self.iter_markers_with_node(name=name))
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/nodes.py", line 203, in iter_markers_with_node
INTERNALERROR>     if name is None or getattr(mark, 'name', None) == name:
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/mark/structures.py", line 20, in warned
INTERNALERROR>     warnings.warn(warning, stacklevel=2)
INTERNALERROR> _pytest.deprecated.RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
INTERNALERROR> Please use node.get_closest_marker(name) or node.iter_markers(name).
INTERNALERROR> Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/xdist/dsession.py", line 116, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/xdist/dsession.py", line 139, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/xdist/dsession.py", line 181, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('scipy/sparse/tests/test_base.py::Test64Bit::()::test_resiliency_limit_10[TestCSC-test_inplace_dense]', <WorkerController gw2>)
INTERNALERROR> assert not 'scipy/sparse/tests/test_base.py::Test64Bit::()::test_resiliency_limit_10[TestCSC-test_inplace_dense]'

======= 5214 passed, 23 skipped, 10 xfailed, 4 xpassed in 314.38 seconds =======
```

**Comment by rgommers** [comment]
Should be https://github.com/pytest-dev/pytest/issues/3503

**Comment by WarrenWeckesser** [comment]
Can we pin `pytest` to an older version while they figure out a fix?

**Comment by rgommers** [comment]
that makes sense. any volunteers? (I'm really short of time, not allowed to look at computer screens all day)

**Comment by larsoner** [comment]
#8869

**Comment by pv** [comment]
Pytest bug report, seems pretty clearly to be pytest bug: https://github.com/pytest-dev/pytest/issues/3515
