### ISSUE TITLE
np.int64 in scipy.fftpack.next_fast_len

### ISSUE THREAD

**Issue by Nodd** [scipy/scipy#8947]
`scipy.fftpack.next_fast_len` crashes when the argument is big enough and not a python int.

### Reproducing code example:
```python
import scipy.fftpack
import numpy
scipy.fftpack.next_fast_len(25700)  # works
scipy.fftpack.next_fast_len(numpy.int64(25700))  # crashes
```

### Error message:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/scipy/fftpack/helper.py", line 134, in next_fast_len
    p2 = 2**((quotient - 1).bit_length())
AttributeError: 'numpy.int64' object has no attribute 'bit_length'
```

### Scipy/Numpy/Python version information:
```
1.0.1 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
fix in gh-8955
