### ISSUE TITLE
Overflow occurs when load '.mat' file larger than 4GB on windows 10

### ISSUE THREAD

**Issue by Lincoln12w** [scipy/scipy#8967]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Overflow occurs when load '.mat' file larger than 4GB on windows 10.

### Reproducing code example:
```
from scipy.io import loadmat
data = loadmat('path/to/mat/file.mat)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 400, in get_variables
    self.mat_stream.seek(next_position)
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 375, in read_var_array
    `process`.
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 137, in array_from_header
    arr = self.read_full_array(hdr)
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 207, in read_full_array
    res_j = self.read_sub_array(hdr, copy=False)
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 173, in read_sub_array
    num_bytes *= d
ValueError: read length must be positive or -1
```

### Scipy/Numpy/Python version information:
```
>>> print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

When I try to fix the overflow by manually set the dim in dims into `int` as follow:
``` scipy/io/matlab/mio4.py
170        num_bytes = dt.itemsize
171        for d in dims:
172            num_bytes *= int(d)
173        buffer = self.mat_stream.read(int(num_bytes))
```

new error occurs:

```
>>> data = loadmat('datasets/datas/905147-3d.mat')
C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py:355: RuntimeWarning: overflow encountered in long_scalars
  remaining_bytes = hdr.dtype.itemsize * n
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Python3.6.5\lib\site-packages\scipy\io\matlab\mio4.py", line 403, in get_variables
    if variable_names is not None:
OSError: [Errno 22] Invalid argument
```

**Comment by sturlamolden** [comment]
Windows API ```ReadFile``` function use a ```DWORD``` for its ```nNumberOfBytesToRead```. This means that it is impossible to read a larger chunk than 4 GB from a file on Windows, as ```DWORD``` is an unsigned 32 bit integer even on 64 bit systems.  Line 173 ```buffer = self.mat_stream.read(int(num_bytes))``` tries to read the whole mat file in one chunk. If a file size of 4 GB is exceeded, we must do multiple reads and concatenate the returned buffers.

**Comment by Lincoln12w** [comment]
> Looking at the code I don't think it is reading a > 4GB file that fails, but rather reading a file with a > 4 GB array.

What's the difference between these two files.  Does the only solution to this is to split the '.mat' file in other OS or other software before loading it with scipy on windows?

**Comment by ev-br** [comment]
Looks like this is a limitation, which is best worked around on the user side?

**Comment by sturlamolden** [comment]
@Lincoln12w Sorry for not answering earlier. 4 GB is the biggest chunk of data the Windows API allows us to read from a file. A .mat file might exceed 4 GB if it contains a lot of small arrays as well.

**Comment by sturlamolden** [comment]
@ev-br yes
