### ISSUE TITLE
NotFoundError: no lapack/blas resources found

### ISSUE THREAD

**Issue by Justin-E-Taylor** [scipy/scipy#9005]
I'm trying to install scipy.  I had a numpy issue (https://github.com/numpy/numpy/issues/11317) but with help I got around it.

When I try to install scipy using pip3, I get a "NotFoundError: no lapack/blas resources found" error.

Here's the stacktrace:
```
-bash-4.3$ pip3 install scipy

Collecting scipy

  Using cached https://files.pythonhosted.org/packages/07/76/7e844757b9f3bf5ab9f951ccd3e4a8eed91ab8720b0aac8c2adcc2fdae9f/scipy-1.1.0.tar.gz

Building wheels for collected packages: scipy

  Running setup.py bdist_wheel for scipy ... error

  Complete output from command /QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo_ft1e6/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppaa878v3pip-wheel- --python-tag cp36:

  lapack_opt_info:

  lapack_mkl_info:

  customize UnixCCompiler

    libraries mkl_rt not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

    NOT AVAILABLE

 

  openblas_lapack_info:

  customize UnixCCompiler

  customize UnixCCompiler

    libraries openblas not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

    NOT AVAILABLE

 

  openblas_clapack_info:

  customize UnixCCompiler

  customize UnixCCompiler

    libraries openblas,lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

    NOT AVAILABLE

 

  atlas_3_10_threads_info:

  Setting PTATLAS=ATLAS

  customize UnixCCompiler

    libraries tatlas,tatlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries tatlas,tatlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries tatlas,tatlas not found in /usr/lib64

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries tatlas,tatlas not found in /usr/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib

  customize UnixCCompiler

    libraries tatlas,tatlas not found in /usr/lib/

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib/

  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

    NOT AVAILABLE

 

  atlas_3_10_info:

  customize UnixCCompiler

    libraries satlas,satlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries satlas,satlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries satlas,satlas not found in /usr/lib64

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries satlas,satlas not found in /usr/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib

  customize UnixCCompiler

    libraries satlas,satlas not found in /usr/lib/

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib/

  <class 'numpy.distutils.system_info.atlas_3_10_info'>

    NOT AVAILABLE

 

  atlas_threads_info:

  Setting PTATLAS=ATLAS

  customize UnixCCompiler

    libraries ptf77blas,ptcblas,atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries ptf77blas,ptcblas,atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries ptf77blas,ptcblas,atlas not found in /usr/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib

  customize UnixCCompiler

    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib/

  <class 'numpy.distutils.system_info.atlas_threads_info'>

    NOT AVAILABLE

 

  atlas_info:

  customize UnixCCompiler

    libraries f77blas,cblas,atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /QOpenSys/pkgs/lib

  customize UnixCCompiler

    libraries f77blas,cblas,atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/local/lib

  customize UnixCCompiler

    libraries f77blas,cblas,atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib64

  customize UnixCCompiler

    libraries f77blas,cblas,atlas not found in /usr/lib

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib

  customize UnixCCompiler

    libraries f77blas,cblas,atlas not found in /usr/lib/

  customize UnixCCompiler

    libraries lapack_atlas not found in /usr/lib/

  <class 'numpy.distutils.system_info.atlas_info'>

    NOT AVAILABLE

 

  /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

      Atlas (http://math-atlas.sourceforge.net/) libraries not found.

      Directories to search for the libraries can be specified in the

      numpy/distutils/site.cfg file (section [atlas]) or by setting

      the ATLAS environment variable.

    self.calc_info()

  lapack_info:

  customize UnixCCompiler

    libraries lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

    NOT AVAILABLE

 

  /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

      Lapack (http://www.netlib.org/lapack/) libraries not found.

      Directories to search for the libraries can be specified in the

      numpy/distutils/site.cfg file (section [lapack]) or by setting

      the LAPACK environment variable.

    self.calc_info()

  lapack_src_info:

    NOT AVAILABLE

 

  /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

      Lapack (http://www.netlib.org/lapack/) sources not found.

      Directories to search for the sources can be specified in the

      numpy/distutils/site.cfg file (section [lapack_src]) or by setting

      the LAPACK_SRC environment variable.

    self.calc_info()

    NOT AVAILABLE

 

  Running from scipy source directory.

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 474, in <module>

      setup_package()

    File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 470, in setup_package

      setup(**metadata)

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup

      config = configuration()

    File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 388, in configuration

      config.add_subpackage('scipy')

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

      caller_level = 2)

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

      caller_level = caller_level + 1)

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

      config = setup_module.configuration(*args)

    File "scipy/setup.py", line 15, in configuration

      config.add_subpackage('linalg')

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

      caller_level = 2)

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

      caller_level = caller_level + 1)

    File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

      config = setup_module.configuration(*args)

    File "scipy/linalg/setup.py", line 19, in configuration

      raise NotFoundError('no lapack/blas resources found')

  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

 

  ----------------------------------------

  Failed building wheel for scipy

  Running setup.py clean for scipy

  Complete output from command /QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo_ft1e6/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

 

  `setup.py clean` is not supported, use one of the following instead:

 

    - `git clean -xdf` (cleans all files)

    - `git clean -Xdf` (cleans all versioned files, doesn't touch

                        files that aren't checked into the git repo)

 

  Add `--force` to your command to use it anyway if you must (unsupported).

 

 

  ----------------------------------------

  Failed cleaning build dir for scipy

Failed to build scipy

Installing collected packages: scipy

  Running setup.py install for scipy ... error

    Complete output from command /QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo_ft1e6/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ff_3g9ut-record/install-record.txt --single-version-externally-managed --compile:

 

    Note: if you need reliable uninstall behavior, then install

    with pip instead of using `setup.py install`:

 

      - `pip install .`       (from a git repo or downloaded source

                               release)

      - `pip install scipy`   (last SciPy release on PyPI)

 

 

    lapack_opt_info:

    lapack_mkl_info:

    customize UnixCCompiler

      libraries mkl_rt not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    openblas_lapack_info:

    customize UnixCCompiler

    customize UnixCCompiler

      libraries openblas not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    openblas_clapack_info:

    customize UnixCCompiler

    customize UnixCCompiler

      libraries openblas,lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    atlas_3_10_threads_info:

    Setting PTATLAS=ATLAS

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

      NOT AVAILABLE

 

    atlas_3_10_info:

    customize UnixCCompiler

      libraries satlas,satlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_3_10_info'>

      NOT AVAILABLE

 

    atlas_threads_info:

    Setting PTATLAS=ATLAS

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_threads_info'>

      NOT AVAILABLE

 

    atlas_info:

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_info'>

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Atlas (http://math-atlas.sourceforge.net/) libraries not found.

        Directories to search for the libraries can be specified in the

        numpy/distutils/site.cfg file (section [atlas]) or by setting

        the ATLAS environment variable.

      self.calc_info()

    lapack_info:

    customize UnixCCompiler

      libraries lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Lapack (http://www.netlib.org/lapack/) libraries not found.

        Directories to search for the libraries can be specified in the

        numpy/distutils/site.cfg file (section [lapack]) or by setting

        the LAPACK environment variable.

      self.calc_info()

    lapack_src_info:

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Lapack (http://www.netlib.org/lapack/) sources not found.

        Directories to search for the sources can be specified in the

        numpy/distutils/site.cfg file (section [lapack_src]) or by setting

        the LAPACK_SRC environment variable.

      self.calc_info()

      NOT AVAILABLE

 

    Running from scipy source directory.

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 474, in <module>

        setup_package()

      File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 470, in setup_package

        setup(**metadata)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup

        config = configuration()

      File "/tmp/pip-build-lo_ft1e6/scipy/setup.py", line 388, in configuration

        config.add_subpackage('scipy')

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

        caller_level = 2)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

        caller_level = caller_level + 1)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

        config = setup_module.configuration(*args)

      File "scipy/setup.py", line 15, in configuration

        config.add_subpackage('linalg')

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

        caller_level = 2)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

        caller_level = caller_level + 1)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

        config = setup_module.configuration(*args)

      File "scipy/linalg/setup.py", line 19, in configuration

        raise NotFoundError('no lapack/blas resources found')

   numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

 

    ----------------------------------------

Command "/QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo_ft1e6/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ff_3g9ut-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lo_ft1e6/scipy/

-bash-4.3$
```

Here's what I currently have installed:
```
-bash-4.3$ pip3 list
backcall (0.1.0)
Cython (0.28.3)
decorator (4.3.0)
freetype-py (1.2.1)
ibm-db (2.0.5.7)
ipython-genutils (0.2.0)
itoolkit (1.4.0)
jedi (0.12.1)
numpy (1.14.5)
parso (0.3.0)
pexpect (4.6.0)
pickleshare (0.7.4)
pip (10.0.1)
pkg-config (0.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.6.0)
Pygments (2.2.0)
pypng (0.0.18)
python-dateutil (2.7.3) pytz (2018.4)
setuptools (39.2.0)
simplegeneric (0.8.1)
six (1.11.0)
traitlets (4.3.2)
wcwidth (0.1.7)
wheel (0.31.1)
```

I'm running Python 3.6.5-1 on IBMi OS.

TIA

**Comment by pv** [comment]
We do not distribute prebuilt binaries for this architecture.
You need to build from sources (which is what pip is attempting above), how to do this see the documentation, the linux instructions probably are close to what you need to do.
https://docs.scipy.org/doc/scipy-1.1.0/reference/building/index.html

**Comment by Justin-E-Taylor** [comment]
FWIW, the official IBM repo now has numpy, scikit-learn and scipy for Python3.

**Comment by Light--** [comment]
the best solution for me:

```
sudo apt-get install gfortran libopenblas-dev liblapack-dev
sudo pip install scipy==1.2.1
```
Thanks Peter Mortensen @　https://stackoverflow.com/questions/7496547/does-python-scipy-need-blas

**Comment by MareksNo** [comment]
> sudo apt-get install gfortran libopenblas-dev liblapack-dev

Does that work for windows and if yes, where?

**Comment by golyalpha** [comment]
@MareksNo Doesn't Windows have pre-built wheels?

**Comment by aphex3k** [comment]
> the best solution for me:
> 
> ```
> sudo apt-get install gfortran libopenblas-dev liblapack-dev
> sudo pip install scipy==1.2.1
> ```
> 
> Thanks Peter Mortensen @　https://stackoverflow.com/questions/7496547/does-python-scipy-need-blas

The equivalent for Alpine would be:

```
apk add gfortran openblas-dev lapack-dev --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
```

It solves a similar if not same issue when building scipy from source.

**Comment by zhgqcn** [comment]
I solved the problem by:

1. `sudo apt autoremove python-scipy`
2. `python -m pip install --upgrade pip`
3. `pip install scipy==1.5.4`

![image](https://user-images.githubusercontent.com/44897668/175755139-62508a4e-29ef-416f-9e7a-da75dd976975.png)
