### ISSUE TITLE
optimize.minimize(method=`trust-constr`) result dict does not contain `success`

### ISSUE THREAD

**Issue by pv** [scipy/scipy#9044]
The result dictionary from all optimizers is supposed to be uniform and contain e.g. a `success` boolean flag.

The `success` flag is missing for `method='trust-constr'`.
The result `nit` is called `niter` in the result dict.

### Reproducing code example:
```
from scipy.optimize import minimize
sol = minimize(lambda x: x**2, [0], jac=lambda x: 2*x, 
    hess=lambda x: 2, method='trust-constr')
print(sorted(sol.keys()))
assert sol.success
```

### Error message:
```
['cg_niter', 'cg_stop_cond', 'constr', 'constr_nfev', 'constr_nhev', 
 'constr_njev', 'constr_penalty', 'constr_violation', 'execution_time', 
 'fun', 'grad', 'jac', 'lagrangian_grad', 'message', 'method', 'nfev', 
 'nhev', 'niter', 'njev', 'optimality', 'status', 'tr_radius', 'v', 'x']
Traceback (most recent call last):
  File "<ipython-input-13-492cf8a99d03>", line 3, in <module>
    assert sol.success
  File "/home/pauli/.local/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 116, in __getattr__
    raise AttributeError(name)
AttributeError: success
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.5 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
and
1.2.0.dev0+7e41406 1.14.5 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
fixed in gh-9217
