### ISSUE TITLE
Minimize trust-constr with no constraints and bounds ?

### ISSUE THREAD

**Issue by denis-bz** [scipy/scipy#9146]
Minimize trust-constr works well with no constraints and no bounds,
so well that it would be nice if bounds worked too --
make `trust-constr` the method of choice.
But constraints=() and bounds
-> ValueError in tr_interior_point.py BarrierSubproblem,
`n_eq 0` -> arrays of shape `(0, n_ineq)`
(I added a couple of debug prints, but a fix is way over my head).

### Reproducing code example:
A test case with logs is in
https://gist.github.com/denis-bz/9e3151f7dee1797d62d85009161da80f

    run test_trustconstr.py  [func=rosen  dim=5  lb=0 ...

in ipython or shell.

<details>

```
#!/usr/bin/env python2
""" scipy minimize trust-constr with no constraints, no bounds works very well
    but bounds:
debug tr_interior_point.py BarrierSubproblem: n_eq 0  n_ineq 2  jac_eq0 (0, 2)  jac_ineq0 (1, 1)  s0 (2,)
debug tr_interior_point.py _compute_jacobian: J_eq (0, 2)  zeros (0, 2)  J_ineq (1, 1)  S (2, 2)
optimize/_trustregion_constr/tr_interior_point.pyc in _compute_jacobian(self, J_eq, J_ineq, s)
    163                 return np.asarray(np.bmat([[J_eq, zeros],
--> 164                                            [J_ineq, S]]))
ValueError: all the input array dimensions except for the concatenation axis must match exactly

Also, jac and hessp 2-point / 3-point callables -> approx_derivative
"""

# https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
# https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html
# $scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py

from __future__ import division, print_function
import sys
import numpy as np
from scipy.optimize import minimize, rosen, Bounds, BFGS
from scipy.optimize._numdiff import approx_derivative

__version__ = "2018-08-15 Aug  denis-bz-py t-online de"

np.set_printoptions( threshold=100, edgeitems=10, linewidth=140,
        formatter = dict( float = lambda x: "%.3g" % x ))  # float arrays %.3g
print( "\n", 80 * "=" )
# print( nu.versions(), "\n" )

#...........................................................................
def jac_2point( x ):
    return approx_derivative( func, x, method="2-point" )  # , bounds=(lb, ub)

def jac_3point( x ):
    return approx_derivative( func, x, method="3-point" )

def hessp_2point( x, p, h=1e-5 ):
    return (jac_2point( x + h*p ) - jac_2point(x)) / h

def hessp_3point( x, p, h=1e-5 ):
    return (jac_3point( x + h*p ) - jac_3point(x)) / h

def _bound( b, inf, dim ):
    """ -> scalar * ones(dim) """
    if b is None:
        b = inf
    if np.isscalar(b):
        b = b * np.ones(dim)
    return b

def nesterov( x ):
    """ Nesterov's nonsmooth Chebyshev-Rosenbrock function, Overton 2011 variant 2 """
    x = np.asarray(x)
    x0 = x[:-1]
    x1 = x[1:]
    return np.abs( 1 - x[0] ) / 4 \
        + np.sum( np.abs( x1 - 2 * np.abs(x0) + 1 ))

#...........................................................................
func = rosen
# func = nesterov
dim = 3
jac = 2  # 2-point / 3-point
hess = 2
lb = 0  # None -> -inf
ub = np.inf

    # minimize params --
ftol = 1e-8  # dF < ftol * cost = sum rho( f_i^2 ) / 2  not trust-constr
gtol = 1e-2  # maxnorm(g_scaled) < gtol
xtol = 1e-6  # |dx| < xtol * (xtol + |x|)
diffstep = 1e-5  # 3-point: eps^(1/3) ~ 1e-5  NR p. 230  * x
maxiter = 100
minverbose = 1  # 2: per iter

    # to change these params, run this.py a=1 b=None 'c = "str"'  in sh or ipython
for arg in sys.argv[1:]:
    exec( arg )

x0 = np.zeros( dim )
jacf = { 2: jac_2point, 3: jac_3point }[jac]
hessp = { 2: hessp_2point, 3: hessp_3point }[hess]

lb = _bound( lb, - np.inf, dim )
ub = _bound( ub, np.inf, dim )

options = dict( gtol=gtol, xtol=xtol, # no ftol
        maxiter=maxiter,
        finite_diff_rel_step=diffstep,
        verbose=minverbose )

print( "func: %s  %dd  x0: %s" % (func.__name__, dim, x0) ) 
print( "jac:", jacf.__name__ ) 
print( "hessp:", hessp.__name__ ) 
print( "options:", sorted( options.items() ))

#...........................................................................
def callback( x, res=None ):
    """ print f x grad with caller's printoptions """
        # only trust-constr has res
        # todo: df |dx| datalogger
    f = res.fun if res \
        else func(x)
    grad = jacf( x )  # res.jac is []
    if res and res.niter == 1:
        print( "\nminimize: func         x       grad " )
    print( "minimize: f %-12g  x %s\t g %s" % (
            f, x, grad ))

#...........................................................................
res = minimize( func, x0, method="trust-constr", constraints=(),
        jac=jacf,  # callable / 2-point / 3-point
        hessp=hessp,  # rosen 2d hessp_2point: 18 iter gtol
        # hess=BFGS(),  # rosen 2d: 38 iter gtol
        bounds=Bounds( lb, ub ),
        options=options,
        callback=callback
        )
# nu.pdict( res )
```

</details>

### Error message:
```
Traceback (most recent call last):
  File "test_trustconstr.py", line 117, in <module>
    callback=callback
  File "/Library/Python/2.7/site-packages/scipy/optimize/_minimize.py", line 618, in minimize
    callback=callback, **options)
  File "/Library/Python/2.7/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 506, in _minimize_trustregion_constr
    factorization_method)
  File "/Library/Python/2.7/site-packages/scipy/optimize/_trustregion_constr/tr_interior_point.py", line 317, in tr_interior_point
    constr_eq0, jac_eq0)
  File "/Library/Python/2.7/site-packages/scipy/optimize/_trustregion_constr/tr_interior_point.py", line 60, in __init__
    self.jac0 = self._compute_jacobian(jac_eq0, jac_ineq0, s0)
  File "/Library/Python/2.7/site-packages/scipy/optimize/_trustregion_constr/tr_interior_point.py", line 172, in _compute_jacobian
    [J_ineq, S]]))
  File "/Library/Python/2.7/site-packages/numpy/matrixlib/defmatrix.py", line 1098, in bmat
    arr_rows.append(concatenate(row, axis=-1))
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

### Scipy/Numpy/Python version information:
```
numpy 1.15.0  scipy 1.1.0  python 2.7.15  mac 10.10.5 
```

**Comment by aldanor** [comment]
Any updates re: this? Just hit this as well.

**Comment by denis-bz** [comment]
@aldanor, as a workaround you could add

    constraints = LinearConstraint( A=np.eye(n), lb=lb, ub=ub )
    
to your other constraints.  Or, you could add penalties, cubic not quadratic for smooth hessp.  
Experts please comment.

(Would you have a standalone test case for trust-constr ?
Hard test cases sharpen tools.)

**Comment by pv** [comment]
Doesn't seem to occur in current master branch?

**Comment by onodip** [comment]
@pv I still encounter this issue with SciPy 1.2

**Comment by grld66** [comment]
I faced a similar situation when using the trust-constr algorithm without defining any constraints. It worked out very well but I don't understand how the algorihm is behaving.
My question is what the algoirthm is doing, if no constraints are given. Is it falling back to unconstraitn trust region algorithms like trust-ncg, trust-krylov or trust-exact?
In the documentation it just says that in case of equality constraints, trust-constr uses a EQSQP-based algorithm whereas for inequality constraints TRIP is used. But what if no constraints at all are defined? 
Thanks for your help!

**Comment by Marten-Reehorst** [comment]
trust-constr seems to just completely ignore the bounds I give it. See also https://stackoverflow.com/questions/52098146/scipy-how-can-i-use-bounds-with-trust-constr (not me but seems to have the same problem). Has anyone found an alternative? I need to be able to supply both the jacobian and the Hessian.

**Comment by denis-bz** [comment]
@Marten-Reehorst,
can you point to a minimal example on the web ? How do you give your [Bounds](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.Bounds.html) ? How do you give grad and hess / hessp ?
(Your link to SO works with `Bounds`.)
Also, the `Elec` test in [test_minimize_constrained.py](https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test_minimize_constrained.py) works with Bounds and n_electrons=50, albeit SR1:

    scipy/optimize/_hessian_update_strategy.py:186: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.

I like to nudge a matrix towards posdef by adding say 1e-8 I; can you try that ?

**Comment by mdhaber** [comment]
The link from the top post by @denis-bz is broken, but the issue describes an error experienced by `minimize` with `method='trust-constr'` when there are no constraints except for bounds. Here is an example of such a problem.

```python3
import numpy as np
from scipy import optimize
rng = np.random.default_rng(492346984573)

x0 = rng.random(3)
bounds = optimize.Bounds([0.1, 0.2, 0.3], [0.5, 0.75, 3])
res = optimize.minimize(optimize.rosen, x0=x0, bounds=bounds, 
                        method='trust-constr')
ref = optimize.minimize(optimize.rosen, x0=x0, bounds=bounds, 
                        method='l-bfgs-b')
np.testing.assert_allclose(res.x, ref.x, rtol=1e-6)
print(bounds.residual(res.x))
# (array([3.99999976e-01, 1.75622469e-01, 7.60754466e-08]), 
#  array([2.42675061e-08, 3.74377531e-01, 2.69999992e+00]))
```
For me, trust-constr produces the same solution vector as l-bfgs-b. The residuals are printed to show that some bounds are active and some are not, so it is not a totally trivial problem.

The other examples reported by this issue are linked by @Marten-Reehorst:
```python3

import numpy as np
from scipy import optimize

def RosenbrockN(x):
    result = 0
    for i in range(len(x)-1):
        result += 100*(x[i+1]-x[i]**2)**2+(1-x[i])**2
    return result
x0 = [0.0, 0.0, 0.0]
bounds = [(-2.0,2.0),(-0.5,0.8),(-2.0,0.7)] 
res = optimize.minimize(RosenbrockN, x0, 
                        method = 'trust-constr', bounds = bounds, 
                        jac = '2-point', hess = optimize.SR1())
ref = optimize.minimize(RosenbrockN, x0, 
                        method = 'l-bfgs-b', bounds = bounds, 
                        jac = '2-point', hess = optimize.SR1())
np.testing.assert_allclose(res.x, ref.x, atol=1e-6)
```
and
```python3
import numpy as np
from scipy.optimize import minimize, LinearConstraint, Bounds
  
def RosenbrockN(x):
    result = 0
    for i in range(len(x)-1):
        result += 100*(x[i+1]-x[i]**2)**2+(1-x[i])**2
    return result

x0 = [0.0, 0.0, 0.0]

# This will not work:
bounds = Bounds([-2.0,-0.5,-2.0],[2.0,0.8,0.7])

res = minimize(RosenbrockN, x0, method = 'trust-constr', bounds=bounds) 
ref = minimize(RosenbrockN, x0, method = 'l-bfgs-b', bounds=bounds) 
np.testing.assert_allclose(res.x, ref.x, atol=2e-6)
```
These both pass for me.

Without a problem that can be used to reproduce the issue, I'll go ahead and close.
If anyone finds a problem similar to these that exposes the issue, please open a new issue and refer to this one.
