### ISSUE TITLE
MemoryError when rank filtering with a large image

### ISSUE THREAD

**Issue by jni** [scipy/scipy#9173]
I'm trying to do median filtering of a reasonably large image (2048, 2560) with a large footprint (513, 513). Using `ndimage.percentile_filter` or `ndimage.median_filter` results in a `MemoryError`. Based on [the `NI_RankFilter` code](https://github.com/scipy/scipy/blob/b944bac904a2edb78556de3c8c5680dc78f1d461/scipy/ndimage/src/ni_filters.c#L724-L751), and on first principles, I would expect that this should only happen when `a * image.nbytes + b * footprint.nbytes`, for `a = 2` and `b = 2`, approximately, is larger than RAM. In this case they are much smaller. Anyone have any idea why this is happening?

### Reproducing code example:
```
import numpy as np
from scipy import ndimage as ndi

image = np.random.random((2048, 2560))
median = ndi.median_filter(image, size=513)
```

### Error message:
```
Traceback (most recent call last):
  File "memory_error.py", line 5, in <module>
    median = ndi.median_filter(image, size=513)
  File "/home/jni/miniconda3/envs/cf/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 1224, in median_filter
    origin, 'median')
  File "/home/jni/miniconda3/envs/cf/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 1145, in _rank_filter
    origins)
MemoryError
```

### Scipy/Numpy/Python version information:
```
1.1.0
1.14.3
sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

Thanks!

**Comment by ewmoore** [comment]
See gh-4878
