### ISSUE TITLE
 from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \ ImportError: DLL load failed: Не найден указанный модуль.

### ISSUE THREAD

**Issue by DenisRang** [scipy/scipy#9230]
In PyCharm I want to install scipy in project interpreter. But some errors was thrown

### Error message:
```
Traceback (most recent call last):
  File "C:/Users/Den/PycharmProjects/LogisticRegressionForIris/main.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "C:\Users\Den\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "C:\Users\Den\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\base.py", line 11, in <module>
    from scipy import sparse
  File "C:\Users\Den\AppData\Roaming\Python\Python37\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\Den\AppData\Roaming\Python\Python37\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: Не найден указанный модуль.
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Your Scipy installation is broken. Examples: #6548 https://github.com/hmmlearn/hmmlearn/issues/87 http://www.xavierdupre.fr/app/pymyinstall/helpsphinx/blog/2015/2015-11-09_issue_sklearn.html

It might be the Python 3.7 wheels but this usually happens when two different SciPy or Python installations interfere. For example virtual environment tries to access system installation etc.

**Comment by gunman7840** [comment]
Tried to install different versions of python and scipy with no success. Then realized that i don't have this problem on two machines with visual studio installed. So my working configuration : VS 2019 Community edition, Python x64, scipy from scikit-learn pip installation.
