### ISSUE TITLE
multivariate_normal should checks for positive definite covariance

### ISSUE THREAD

**Issue by giampierosalvi** [scipy/scipy#9257]
The multivariate_normal function in stats correctly raises a ValueError if the covariance matrix is not positive semidefinite. However, this is not enough to ensure that the distribution can be computed. In fact, it the determinant is zero this is not possible, and numpy linalg raises a LinAlgError: singular matrix.

The user of this function at the moment needs to catch two different exceptions. It would be much cleaner if multivariate_normal raised the ValueError if the covariance matrix is not positive DEFINITE, including the singular case.

### Reproducing code example:
```
from scipy.stats import multivariate_normal
import numpy as np
mu = np.array([0, 0])
s_negative = np.array([[1, 2], [2, 1]])
rv_negative = multivariate_normal(mu, s_negative)
s_singular = np.array([[1, 1], [1, 1]])
rv_singular = multivariate_normal(mu, s_singular)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 358, in __call__
    seed=seed)
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 728, in __init__
    self.cov_info = _PSD(self.cov, allow_singular=allow_singular)
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 156, in __init__
    raise ValueError('the input matrix must be positive semidefinite')
ValueError: the input matrix must be positive semidefinite

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 358, in __call__
    seed=seed)
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 728, in __init__
    self.cov_info = _PSD(self.cov, allow_singular=allow_singular)
  File "/home/giampi/anaconda3/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 159, in __init__
    raise np.linalg.LinAlgError('singular matrix')
numpy.linalg.linalg.LinAlgError: singular matrix
```

### Scipy/Numpy/Python version information:
```
scipy 1.1.0
numpy 1.14.3
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by giampierosalvi** [comment]
I saw now that there is an option "allow_singular" to handle singular matrices. The question remains: why raising two different exceptions and not ValueError in both cases? That is:
ValueError('the input matrix must be positive semidefinite') (allow_singular=True)
or
ValueError('the input matrix must be positive definite') (allow_singular=False)

**Comment by chrisb83** [comment]
Positive-semidefinite should be ok, if the covariance matrix does not have full rank, then there is no density though but random variates could still be generated in principle.


Not sure about the scipy implementation though

**Comment by mdhaber** [comment]
I think we should track this in gh-5286. Closing.
