### ISSUE TITLE
Allow LinearOperator with shape (1,n) in singular value calculations

### ISSUE THREAD

**Issue by SebastianSemper** [scipy/scipy#9284]
I have come across the issue, that it is impossible to calculate the singular values of for instance a LinearOperator originating from a (1, n) Matrix is currently not possible, although this should not pose any mathematical problem. At least one singular value should be calculatable, since the gram-matrix always has at least dimension (1x1).

### Reproducing code example:
```
import numpy as np
from scipy.sparse.linalg import LinearOperator
from scipy.sparse.linalg import svds

L = LinearOperator(
    shape=(1,2),
    matvec=(lambda x: np.sum(x)),
    rmatvec=(lambda X: np.array(x[0], x[0])),
    matmat=(lambda x: np.sum(x, axis=0)),
    dtype=np.float64
)

svds(L, 1, return_singular_vectors=False)
```

### Error message:
```
Traceback (most recent call last):
 
  File "fastmat/Matrix.pyx", line 666, in fastmat.Matrix.Matrix._getLargestSV
    result = linalg.svds(
  File "/usr/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1770, in svds
    raise ValueError("k must be between 1 and min(A.shape), k=%d" % k)
ValueError: k must be between 1 and min(A.shape), k=1

```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by lobpcg** [comment]
I fully agree. Moreover, it makes no practical sense to call ARPACK for small matrices anyway. After https://github.com/scipy/scipy/pull/10830 is finished, I'll make a PR to address it: if solver = None (meaning the user does not care) and the smallest size is small enough (e.g.,  <200) the fix would generate a full matrix from the LinearOperator, and call a standard LAPACK solver - this will cover your proposed case of a 1x1 normal matrix automatically.
