### ISSUE TITLE
Including scipy as a dependency requires numpy to be installed outside of setup script

### ISSUE THREAD

**Issue by pkerpedjiev** [scipy/scipy#9297]
When scipy is included as a dependency using setuptools, the build fails complaining about `numpy` not being installed, even when `numpy` is included in `setup_requires`. Here's the `setup.py` script:

### Reproducing code example:

```
from setuptools import setup

install_requires = [
    'numpy',
    'scipy',
]

setup(
    name='test-scipy-dependency',
    version='0.1.0',
    description='Testing the installation of a library with a scipy dependency',
    author='Peter Kerpedjiev',
    author_email='pkerpedjiev@gmail.com',
    url='',
    install_requires=install_requires,
    setup_requires=['numpy'],
    packages=['blah']
)
```

A working failing example can be found here: 

https://github.com/pkerpedjiev/test-scipy-dependency

### Error message:

```
Traceback (most recent call last):
  File "scipy/special/utils/makenpz.py", line 11, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/test9/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/Users/peter/miniconda3/envs/test9/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/Users/peter/miniconda3/envs/test9/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/Users/peter/miniconda3/envs/test9/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/var/folders/0b/8w70cc7n675fwfd_gsvdvpb00000gp/T/easy_install-iyu15g70/scipy-1.1.0/setup.py", line 474, in <module>
  File "/var/folders/0b/8w70cc7n675fwfd_gsvdvpb00000gp/T/easy_install-iyu15g70/scipy-1.1.0/setup.py", line 470, in setup_package
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "/var/folders/0b/8w70cc7n675fwfd_gsvdvpb00000gp/T/easy_install-iyu15g70/scipy-1.1.0/setup.py", line 388, in configuration
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 1034, in add_subpackage
    caller_level = 2)
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 1003, in get_subpackage
    caller_level = caller_level + 1)
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 23, in configuration
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 1034, in add_subpackage
    caller_level = 2)
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 1003, in get_subpackage
    caller_level = caller_level + 1)
  File "/Users/peter/projects/test-scipy-dependency/.eggs/numpy-1.15.1-py3.6-macosx-10.7-x86_64.egg/numpy/distutils/misc_util.py", line 940, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/special/setup.py", line 149, in configuration
  File "/Users/peter/miniconda3/envs/test9/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/peter/miniconda3/envs/test9/bin/python', 'scipy/special/utils/makenpz.py', '--use-timestamp', 'scipy/special/tests/data/boost']' returned non-zero exit status 1.
```

### Scipy/Numpy/Python version information:

Fails with `scipy>=1.1.0` works with `scipy==1.0`. The change that introduced this issues seems to be https://github.com/scipy/scipy/commit/6c6ded8f552cc4c7ee103e7bf3b2be36041aa67c. The scipy install script is calling an external command where numpy is not yet installed.

**Comment by pv** [comment]
Blocked by: https://github.com/scipy/scipy/issues/8734 
The current pip versions probably have everything necessary.

I doubt 6c6ded8 is the issue --- the build requires installed numpy, and will fail without it at some stage.

**Comment by rgommers** [comment]
`pyproject.toml` was added back, so this works now (in master, will be in 1.3.0).
