### ISSUE TITLE
In solve_ivp method, first_step cannot be used with "backwards" time integration in LSODA

### ISSUE THREAD

**Issue by MatthewFlamm** [scipy/scipy#9366]
Using solve_ivp with the LSODA method, both "forwards" and "backwards" time integration is successful.  The first_step parameter can be specified for the "forwards" case as well.

```
from scipy.integrate import solve_ivp

def fun(x, y):
    return y

y0=[1]

res = solve_ivp(fun,[0, 1], y0, method='LSODA')
print(res.message)
res = solve_ivp(fun,[0, -1], y0, method='LSODA')
print(res.message)
res = solve_ivp(fun,[0, 1], y0, method='LSODA', first_step=0.1)
print(res.message)
```

returns

```
The solver successfully reached the end of the integration interval.
The solver successfully reached the end of the integration interval.
The solver successfully reached the end of the integration interval.
```

as expected.  However, using a positive first_step with a "backwards" time integration fails.

```
res = solve_ivp(fun,[0, -1], y0, method='LSODA', first_step=0.1)
print(res.message)
```

returns

```
 lsoda--  tout (=r1) behind t (=r2)      
      in above,  r1 = -0.1000000000000D+01   r2 =  0.0000000000000D+00
       integration direction is given by h0 (=r1)  
      in above message,  r1 =  0.1000000000000D+00
/path/to/scipy/integrate/_ode.py:1348: UserWarning: lsoda: Illegal input detected (internal error).
  self.messages.get(istate, unexpected_istate_msg)))
Unexpected istate in LSODA.
```

Also, using a negative first_step with a "backwards" time integration fails.

```
res = solve_ivp(fun,[0, -1], y0, method='LSODA', first_step=-0.1)
print(res.message)
```

returns

```
Traceback (most recent call last):
  File "lsoda_first_step_test.py", line 16, in <module>
    res = solve_ivp(fun,[0, -1], y0, method='LSODA', first_step=-0.1)
  File "/path/to/scipy/integrate/_ivp/ivp.py", line 454, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
  File "/path/to/scipy/integrate/_ivp/lsoda.py", line 114, in __init__
    raise ValueError("`first_step` must be positive or None.")
ValueError: `first_step` must be positive or None.
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.2 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by drhagen** [comment]
Yep, this is a bug.
