### ISSUE TITLE
scipy.interpolate.griddata() doesn't work when set method = nearest

### ISSUE THREAD

**Issue by Clarmy** [scipy/scipy#9433]
I have some irregular meteorological data, and I want to make them into grid form. So I'm going to use scipy.interpolate.griddata() to do that. But there is something wrong.
The griddata() function doesn't work when I set `method='nearest'`, but if `method='linear'` or other options, it can work.
I suspect it's a bug, or maybe I haven't learnt how to use it.

### Reproducing code example:

Following codes is a module named as `makegrid2.py`, and example data file is here: [201810220000.txt](https://github.com/scipy/scipy/files/2541496/201810220000.txt)

```python
# coding:utf-8
'''
module's name: makegrid2
'''
import sys
sys.path.append('..')
import json as js
import numpy as np
import netCDF4 as nc
from scipy.interpolate import griddata, interp1d
import datetime
import ipdb


def load_data(filepath):
    '''加载json数据'''
    with open(filepath) as file_obj:
        raw_content = file_obj.readlines()

    data = [js.loads(line) for line in raw_content]

    return data


def get_attr_dict():
    attr_dict = {'HWD':{'long_name':'Horizontal Wind Direction',
                        'units':'degree'},
                 'HWS':{'long_name':'Horizontal Wind Speed',
                        'units':'m/s'},
                 'VWS':{'long_name':'Vertical Wind Speed',
                        'units':'m/s'},
                 'HDR':{'long_name':'Horizontal Direction Reliability',
                        'units':'%'},
                 'VDR':{'long_name':'Vertical Direction Reliability',
                        'units':'%'},
                 'level':{'long_name':'Sampling Height level',
                        'units':'m'},
                 'lon':{'long_name':'longitudes','units':'degree_east'},
                 'lat':{'long_name':'latitudes','units':'degree_north'},
                 'time':{'long_name':'datetime',
                         'units':'minutes since 2018-01-01 00:00:00'}}
    return attr_dict


def std_sh():
    '''获取标准采样高度层'''
    sh1 = range(100,2000,100)
    sh2 = range(2000,5000,250)
    sh3 = range(5000,9500,500)
    sh = list(sh1)+list(sh2)+list(sh3)

    return sh


def veticl_interpolate(single_ds):
    '''垂直插值单站数据集

    输入参数
    -------
    single_ds : `dict`
        单站数据字典，包含有高度、站点信息及需插值变量等变量。

    返回值
    -----
    new_single_ds : `dict`
        经过垂直插值处理后的单站数据集，经处理后其高度层为统一结构（100~9000,40层），
        缺省值为np.nan。
    '''
    # 制作标准高度层
    sh = std_sh()

    raw_sh = single_ds['SH']

    # 获取上下边界索引
    raw_top = max(raw_sh)
    raw_bottom = min(raw_sh)

    for n, height in enumerate(sh):
        if height > raw_top:
            top_index = n
            break
    else:
        top_index = len(sh)

    for n, height in enumerate(sh):
        if height > raw_bottom:
            bottom_index = n
            break

    nsh = sh[bottom_index:top_index]
    headcount = len(sh[:bottom_index])
    tailcount = len(sh[top_index:])

    intp_vars = ['HWD', 'HWS', 'VWS', 'HDR', 'VDR', 'CN2']
    attr_vars = ['station', 'lon', 'lat', 'altitude', 'wave', 'time']

    new_single_ds = {}
    new_single_ds['SH'] = sh
    for av in attr_vars:
        new_single_ds[av] = single_ds[av]

    for var in intp_vars:
        intp_func = interp1d(raw_sh, single_ds[var], kind='slinear')
        new_single_ds[var] = [np.nan] * headcount + list(intp_func(nsh)) +\
            [np.nan] * tailcount

    return new_single_ds


def multi_station_vetcl_intp(raw_dataset):
    '''多站（全数据集）垂直积分

    输入参数
    -------
    raw_dataset : `list`
        多站数据列表，单行是单站数据（字典格式）

    返回值
    -----
    `list`
        经插值处理后的多站数据列表
    '''
    return [veticl_interpolate(line) for line in raw_dataset]


def complete_interpolate(pfn,varkeys=['HWD', 'HWS', 'VWS', 'HDR',
    'VDR', 'CN2']):
    '''在单个站点垂直插值的基础上对所有站点所有层次进行插值处理

    输入参数
    -------
    pfn : `str`
        多站数据列表，单行是单站数据（字典格式）
    varkeys : `list`
        变量名列表

    返回值
    -----
    `ndarray`

    '''
    def get_datetime(pfn):
        timestr = pfn.split('/')[-1].split('.')[0]
        yyyy = int(timestr[:4])
        mm = int(timestr[4:6])
        dd = int(timestr[6:8])
        HH = int(timestr[8:10])
        MM = int(timestr[10:])
        time_obj = datetime.datetime(yyyy,mm,dd,HH,MM)
        time_units = 'minutes since 2018-01-01 00:00:00'
        return nc.date2num(time_obj,time_units)

    dataset = multi_station_vetcl_intp(load_data(pfn))
    sh = std_sh()

    min_lon = 85
    max_lon = 125
    min_lat = 14
    max_lat = 45
    grd_lon = np.arange(min_lon,max_lon,0.5)
    grd_lat = np.arange(min_lat,max_lat,0.5)
    grd_lons, grd_lats = np.meshgrid(grd_lon,grd_lat)

    data_dict = {}
    for varkey in varkeys:
        multigrds = []
        for height in sh:
            sh_index = sh.index(height)
            lon = []
            lat = []
            values = []

            for line in dataset:
                try:
                    int(line[varkey][sh_index])
                except ValueError:
                    continue
                else:
                    lon.append(line['lon'])
                    lat.append(line['lat'])
                    values.append(line[varkey][sh_index])

            lon = np.array(lon)
            lat = np.array(lat)

            grds = griddata((lon,lat),values,(grd_lons,grd_lats),method='nearest')
            multigrds.append(grds)
            data_dict[varkey] = np.array(multigrds)

    data_dict['lon'] = grd_lon
    data_dict['lat'] = grd_lat
    data_dict['level'] = np.array(sh)
    data_dict['time'] = get_datetime(pfn)

    attr_dict = get_attr_dict()

    return data_dict,attr_dict


def main():
    pfn = './201810220000.txt'
    dataset = complete_interpolate(pfn)


if __name__ == '__main__':
    main()

```

### Error message:

I ran the script above `python makegrid2.py` , and then it showed error messages as follow:
```
Traceback (most recent call last):
  File "makegrid2.py", line 206, in <module>
    main()
  File "makegrid2.py", line 202, in main
    dataset = complete_interpolate(pfn)
  File "makegrid2.py", line 186, in complete_interpolate
    grds = griddata((lon,lat),values,(grd_lons,grd_lats),method='nearest')
  File "/anaconda2/envs/py3/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 219, in griddata
    return ip(xi)
  File "/anaconda2/envs/py3/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 81, in __call__
    return self.values[i]
TypeError: only integer scalar arrays can be converted to a scalar index
```
While, if I change the parameter `method='nearest'` to `method='linear'`(line 186), it won't show any error. 

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.13.3 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
This might have been fixed already because I can't replicate it as a standalone problem. 

```python
import numpy as np
from scipy.interpolate import griddata

values = np.array([43.26666667, 282.63333333, 121.66666667, 253.2,
                   298.5, 94.33333333, 237.06666667, 109.36666667,
                   69.1, 306.16666667, 313.76666667, 355.06666667])

lon = np.array([103.8881, 116.9147, 119.0331, 117.985, 119.3878, 117.2833,
                120.0869, 121.1503, 120.7667,  87.6458, 119.7025, 113.1161])

lat = np.array([36.0575, 38.9253, 29.6081, 27.6167, 25.7233, 39.7333, 29.3414,
                27.8344, 30.7333, 43.7889, 30.2181, 33.7708])


grd_lon = np.arange(85, 125, 0.5)
grd_lat = np.arange(14, 45, 0.5)
grd_lons, grd_lats = np.meshgrid(grd_lon, grd_lat)
grds = griddata((lon, lat), values, (grd_lons, grd_lats), method='nearest')
```

Please isolate an example as above that replicates your problem

**Comment by Clarmy** [comment]
I known what's the key of this problem. 
The key is the type of `values`. When `values` is the type of `numpy.ndarray` it can work well, but when it is the type of `list`, it will raise the Exception what I saw. In other words, please change 
```python
values = np.array([43.26666667, 282.63333333, 121.66666667, 253.2,
                   298.5, 94.33333333, 237.06666667, 109.36666667,
                   69.1, 306.16666667, 313.76666667, 355.06666667])
```
into
```python
values = [43.26666667, 282.63333333, 121.66666667, 253.2,
          298.5, 94.33333333, 237.06666667, 109.36666667,
          69.1, 306.16666667, 313.76666667, 355.06666667]
```
rerun it and error will appear.

**Comment by ilayn** [comment]
The documentation is explicit on that. It is expecting an ndarray object not a sequence.

**Comment by Clarmy** [comment]
Sorry, it's my fault.  Thank you very much!
