### ISSUE TITLE
ImportError: No module named scipy.signal

### ISSUE THREAD

**Issue by alexmiera** [scipy/scipy#9483]
When I run the following code...
```
import pandas as pd  # for data analysis
import numpy as np  # for math functions
from scipy.signal import argrelextrema
import matplotlib.pyplot as plt  # for plotting data

data = pd.read_csv("/Users/alexmiera1/PycharmProjects/Trading_test/Data/EURUSD.csv")

data.columns = [['Date','open','high','low','close','vol']]

data = data.drop_duplicates(keep=False)  # Eliminates duplicates

data.Date = pd.to_datetime(data.Date,format='%d.%m.%Y %H:%M:%S.%f')  # reformat the data

data = data.set_index(data.Date)  # Sets indexes using the column "Date"

data = data [['open','high','low','close','vol']]  # drops the "Date" column above by renaming data

price = data.close.iloc[:100]  # selects the latest :X rows to work with

max_idx = list(argrelextrema(price.values,np.greater, order=1)[0])
min_idx = list(argrelextrema(price.values,np.less, order=1)[0])

idx = max_idx + min_idx  #list(price.values)
idx.sort()

peaks = price.values[idx]
plt.plot(price.values)
plt.scatter(idx,peaks, c ='r')
plt.show()
```
###  I get this .. Error message:
```
/Users/alexmiera1/PycharmProjects/Trading_test/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 61963 --file "/Users/alexmiera1/PycharmProjects/Trading_test/Results/Plot Chart.py"
pydev debugger: process 22898 is connecting

Connected to pydev debugger (build 182.5107.22)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/alexmiera1/PycharmProjects/Trading_test/Results/Plot Chart.py", line 3, in <module>
    from scipy.signal import argrelextrema
ImportError: No module named scipy.signal

Process finished with exit code 1
```
I've tried many things but still can't find why it does not work! It looks like scipy 1.1.0 has been correctly imported, but python does not read/see it. I am doing something wrong here., but don't know what else to try... 

I have:
- Mac OS High Sierra
- Python v3.7 ( I'm working with Pycharm)
- Anaconda installed
- Scipy 1.1.0
- Numpy and Pandas installed 

Any idea / clue?

Thanks in advance for your help!

**Comment by ilayn** [comment]
This is a typical installation problem. I don't know the exact reason but in most cases people reported that reinstalling with the proper channels solve the problem. Here are all the results 

https://www.google.com/search?q=ImportError:+No+module+named+scipy.signal+site:stackoverflow.com&client=firefox-b&sa=X&ved=2ahUKEwijp9K3wNbeAhXpw4sKHUfCAJ8QrQIoBDAEegQICBAO&biw=1920&bih=966
