### ISSUE TITLE
cannot import name logsumexp

### ISSUE THREAD

**Issue by zamantousif** [scipy/scipy#9546]
My issue is related to use of scipy in cvxpy. I am using scipy version mentioned below and upon running the example code (link provided below), I get an error pointing that there is no module named logsumexp. Could you help me fix this? why is this module no longer in the latest version of scipy?

### Reproducing code example:

```
Sample code to reproduce the problem:

The code example from this link http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/intro/control.ipynb

```

### Error message:

```
Traceback (most recent call last):
  File "/home/zaman/Documents/Python/optim.py", line 4, in <module>
    from cvxpy import *
  File "/home/zaman/.local/lib/python2.7/site-packages/cvxpy-1.0.10-py2.7-linux-x86_64.egg/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/home/zaman/.local/lib/python2.7/site-packages/cvxpy-1.0.10-py2.7-linux-x86_64.egg/cvxpy/atoms/__init__.py", line 24, in <module>
    from cvxpy.atoms.log_sum_exp import log_sum_exp
  File "/home/zaman/.local/lib/python2.7/site-packages/cvxpy-1.0.10-py2.7-linux-x86_64.egg/cvxpy/atoms/log_sum_exp.py", line 20, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name logsumexp
```

**Comment by zamantousif** [comment]
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.3.0.dev0+0781734', '1.16.0.dev0+11a316e', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))

**Comment by rkern** [comment]
It was moved to `scipy.special.logsumexp` in 2016, and was finally deleted from `scipy.misc` after a period of deprecation. `cvxpy` should have updated its calls in that time.

**Comment by ilayn** [comment]
Have a look at thebackwards incompatible changes section here https://github.com/scipy/scipy/blob/master/doc/release/1.3.0-notes.rst 

scipy.misc had quite a few deprecations since version 1.0.0
