### ISSUE TITLE
Regression in 1.2: Cannot import RectBivariateSpline, UnivariateSpline

### ISSUE THREAD

**Issue by ideasrule** [scipy/scipy#9548]
Importing from scipy.interpolate causes exception in pre-release candidate 1.2.0rc1, at least when done in Travis CI:

### Reproducing code example:

```
 from scipy.interpolate import RectBivariateSpline, UnivariateSpline
```

### Error message:

```
Traceback (most recent call last):
  File "examples/transit_depth_example.py", line 6, in <module>
    from platon.transit_depth_calculator import TransitDepthCalculator
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/platon-2.1-py2.7.egg/platon/transit_depth_calculator.py", line 7, in <module>
    from scipy.interpolate import RectBivariateSpline, UnivariateSpline
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/interpolate/interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/spatial/__init__.py", line 104, in <module>
    from . import transform
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/spatial/transform/__init__.py", line 22, in <module>
    from .rotation import Rotation, Slerp
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/spatial/transform/rotation.py", line 1574
SyntaxError: Non-ASCII character '\xe2' in file /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/scipy-1.2.0rc1-py2.7-linux-x86_64.egg/scipy/spatial/transform/rotation.py on line 1575, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Scipy/Numpy/Python version information:
scipy 1.2.0rc1, Python 2.7.14

**Comment by rgommers** [comment]
thanks for the report @ideasrule. known issue (gh-9540), already fixed. next 1.2.0 release candidate should work fine
