### ISSUE TITLE
Importing error in scipy.spatial.distance

### ISSUE THREAD

**Issue by mayesha-mukarrama** [scipy/scipy#9552]
I am getting an error while importing scipy.spatial.distance.

### Reproducing code example:

Getting this error,

Traceback (most recent call last):
  File "cos1.py", line 3, in <module>
    from scipy.spatial.distance import pdist
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/spatial/__init__.py", line 94, in <module>
    from .kdtree import *
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/sparse/csr.py", line 20, in <module>
    from .compressed import _cs_matrix
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 11, in <module>
    from scipy._lib._util import _prune_array
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/_lib/_util.py", line 9, in <module>
    import inspect
  File "/usr/lib/python2.7/inspect.py", line 37, in <module>
    import dis
  File "/home/mayesha/dis.py", line 2, in <module>
    from scipy.spatial.distance import pdist
  File "/home/mayesha/venv/local/lib/python2.7/site-packages/scipy/spatial/distance.py", line 119, in <module>
    from scipy._lib._util import _asarray_validated
ImportError: cannot import name _asarray_validated

**Comment by perimosocordiae** [comment]
Based on your traceback, it appears that you have a file named `dis.py` on your $PYTHONPATH, which is being used in place of the standard library `dis` module.

Shadowing stdlib modules is a bad idea, so if you can, rename your version to something else.
