### ISSUE TITLE
improper handling of multidimensional input in stats.rv_sample

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9565]
My issue is about ...

### Reproducing code example:

```
from scipy import stats
import numpy as np

xk = np.arange(6).reshape((3, 2))
pk = (1/3, 1/3, 1/3)
custm = stats.rv_discrete(values=(xk, pk))
```
The implementation of `rv_sample` only checks the following:

```
if len(xk) != len(pk):
            raise ValueError("xk and pk need to have the same length.")
```

Afterwards, xk and pk are ravelled, leading to different lengths.

### Error message:

`IndexError: index 3 is out of bounds for size 3`

```
Traceback (most recent call last):

  File "<ipython-input-15-0a2191a05404>", line 3, in <module>
    custm = stats.rv_discrete(values=(xk, pk))

  File "c:\users\christoph\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 3332, in __init__
    self.pk = np.take(np.ravel(pk), indx, 0)

  File "c:\users\christoph\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)

  File "c:\users\christoph\anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: index 3 is out of bounds for size 3
```

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.2 sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
... and once this is fixed, most likely something's going to break down the line, too. Am labelling this as an enhancement.
