### ISSUE TITLE
SciPy Source Build fails on Cython

### ISSUE THREAD

**Issue by dmadeka** [scipy/scipy#9744]
### Reproducing code example:
Running `python setup.py install` gives the following error:

```python
~/dev/scipy (master*)$ python setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Cythonizing sources
Running scipy/special/_generate_pyx.py
Running scipy/linalg/_generate_pyx.py
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
Processing scipy/special/_ellip_harm_2.pyx
Processing scipy/special/_ufuncs.pyx
Processing scipy/special/cython_special.pyx
Processing scipy/special/_ufuncs_cxx.pyx
Traceback (most recent call last):
  File "/home/local/ANT/maded/anaconda3/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
Traceback (most recent call last):
  File "/home/local/ANT/maded/anaconda3/bin/cython", line 11, in <module>
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
    sys.exit(setuptools_main())
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
Traceback (most recent call last):
  File "/home/local/ANT/maded/anaconda3/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
Traceback (most recent call last):
  File "/home/local/ANT/maded/anaconda3/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 788, in setuptools_main
    return main(command_line = 1)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 806, in main
    result = compile(sources, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_multiple(source, options)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 748, in compile_multiple
    context = options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
Processing scipy/special/_comb.pyx
Traceback (most recent call last):
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 306, in <module>
    main()
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 302, in main
    find_process_files(root_dir)
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 291, in find_process_files
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 291, in <lambda>
    for result in pool.imap_unordered(lambda args: process(*args), jobs):
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 230, in process
    processor_function(fromfile, tofile, cwd=path)
  File "/home/local/ANT/maded/dev/scipy/tools/cythonize.py", line 95, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 488, in <module>
    setup_package()
  File "setup.py", line 472, in setup_package
    generate_cython()
  File "setup.py", line 249, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

### Scipy/Numpy/Python version information:
```python
>>> import sys, Cython, numpy; print(Cython.__version__, numpy.__version__, sys.version_info)
0.29.4 1.16.1 sys.version_info(major=3, minor=5, micro=0, releaselevel='final', serial=0)
```

**Comment by dmadeka** [comment]
Same issue with `numpy==1.15.4`

**Comment by rgommers** [comment]
It's an unusual error, can't find much info on it. Likely something in your environment then. Can you compile a simple standalone Cython file, and can you build NumPy from source?

**Comment by dmadeka** [comment]
Nope on either:

```python
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ ls
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ vim helloworld.pyx
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ vim setup.py
maded@uc4346b707fc2594ae9f1:~/dev/helloworld $ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("helloworld.pyx")
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 958, in cythonize
    ctx = c_options.create_context()
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/local/ANT/maded/anaconda3/lib/python3.5/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
```

**Comment by rgommers** [comment]
Thanks @dmadeka. Not a SciPy bug then, so closing.
