### ISSUE TITLE
scipy.linalg.solve_continuous_are different behavior in Windows and Linux

### ISSUE THREAD

**Issue by shestakov-sa** [scipy/scipy#9846]
Solving algebraic Riccati equation produces different outcome for Windows and Linux-based systems. 
```
import pickle
import scipy
import scipy.linalg
import numpy
import sys

# a = float.fromhex('0x1.6e36000000001p+21')
a = 3e6

# check versions of packages
print(scipy.__version__, numpy.__version__, sys.version)

with open('dump.txt', 'rb') as file_:
    [systemMtx, B, Q] = pickle.load(file_)
R = a*numpy.eye(3)

# check, that it is the same variables
print(hash(tuple(map(tuple, systemMtx))))
print(hash(tuple(map(tuple, B))))
print(hash(tuple(map(tuple, Q))))
print(hash(tuple(map(tuple, R))))

# do the job
P = scipy.linalg.solve_continuous_are(systemMtx, B, Q, R)
```
On linux it works and produces a desirable outcome, on windows it crashes with an error. 
Both platform produce correct package versions (python 3.7.1 on win, 3.6.8 on mint) and hash values of variables.
Windows:
```
1.2.0 1.15.4 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
3000000.0000000005
6375929551331530611
1977263370690184329
-307158487027226819
-1889920678466370224
```
Linux:
```
1.2.0 1.15.4 3.6.8 |Anaconda, Inc.| (default, Dec 20 2018, 01:22:34) [GCC 7.3.0]
3000000.0000000005
6375929551331530611
1977263370690184329
-307158487027226819
-1889920678466370224
```
### But Windows also crashes afterwards with error message:

```
Traceback (most recent call last):
  File "C:\Users\Sergey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a26cf195d5b7>", line 3, in <module>
    runfile('C:/Users/Sergey/PycharmProjects/thejob/source/pupa.py', wdir='C:/Users/Sergey/PycharmProjects/thejob/source')
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Sergey/PycharmProjects/thejob/source/pupa.py", line 55, in <module>
    P = scipy.linalg.solve_continuous_are(systemMtx, B, Q, R)
  File "C:\Users\Sergey\Anaconda3\lib\site-packages\scipy\linalg\_solvers.py", line 494, in solve_continuous_are
    output=out_str)
  File "C:\Users\Sergey\Anaconda3\lib\site-packages\scipy\linalg\_decomp_qz.py", line 390, in ordqz
    raise ValueError("Reordering of (A, B) failed because the transformed"
ValueError: Reordering of (A, B) failed because the transformed matrix pair (A, B) would be too far from generalized Schur form; the problem is very ill-conditioned. (A, B) may have been partially reorded. If requested, 0 is returned in DIF(*), PL, and PR.

```
Tracing back all calls I think, that the problem is in different lapack routines:
_flapack.cp37-win_amd64.pyd
and
_flapack.cpython-36m-x86_64-linux-gnu.so
May be it is something wrong with library or so.

I am attaching data file dump.txt, it is actually binary, produced with pickle and contains three aforementioned matrices.
[dump.txt](https://github.com/scipy/scipy/files/2880204/dump.txt)

**Comment by ilayn** [comment]
This sounds like the LAPACK and BLAS versions are different. Can you test it outside the Anaconda environment ?

**Comment by shestakov-sa** [comment]
> 
> 
> This sounds like the LAPACK and BLAS versions are different. Can you test it outside the Anaconda environment ?
> 
> Can you please explicitly spell out the matrices for testing?

How to? I can produce ```scipy.__config__``` output but what to do to test outside the Anaconda?

I've produced three matrices by
```
numpy.savetxt('MATRIX.txt', MATRIX, delimiter=',', fmt='%1.16e')
```
so I believe 
```
numpy.loadtxt('MATRIX.txt', delimiter=',')
```
would do the trick.

[B.txt](https://github.com/scipy/scipy/files/2880557/B.txt)
[Q.txt](https://github.com/scipy/scipy/files/2880558/Q.txt)
[systemMtx.txt](https://github.com/scipy/scipy/files/2880559/systemMtx.txt)

**Comment by ilayn** [comment]
Anaconda uses MKL library and the remaining wheels are compiled against OpenBLAS so there can be differences. Especially QZ decomposition is inherently unstable so these things can be expected including matlab. But nevermind I can reproduce that outside the anaconda env anyways. 

Here A has almost all eigs on the imaginary axis so the stable subspace generation is failing and this type of failures are to be expected. Different architectures unfortunately hit different precision levels and this type of branches are quite common.
