### ISSUE TITLE
"++" initialization in kmeans2 fails for univariate data

### ISSUE THREAD

**Issue by davidaknowles** [scipy/scipy#9950]
This works fine for the other initialization methods.
```
from scipy.cluster.vq import kmeans2
kmeans2(np.random.rand(30),3,minit="++")
```
Error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/scipy/cluster/vq.py", line 706, in kmeans2
    label = vq(data, code_book)[0]
  File "/usr/local/lib/python3.7/site-packages/scipy/cluster/vq.py", line 210, in vq
    return _vq.vq(c_obs, c_code_book)
  File "_vq.pyx", line 211, in scipy.cluster._vq.vq
ValueError: observation and code should have same number of dimensions
```
### Scipy/Numpy/Python version information:
```
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by yuanx749** [comment]
The issue still exists. From the traceback, it seems kmeans++ does not support 1D array.
```Python traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiao/scipy/scipy/cluster/vq.py", line 814, in kmeans2
    code_book = init_meth(data, code_book, rng, xp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/scipy/scipy/cluster/vq.py", line 611, in _kpp
    init[i, :] = data[rng_integers(rng, data.shape[0]), :]
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
